### ISSUE TITLE
App crashes when adding style="background-color" on a <CheckBox>

### ISSUE THREAD

**Issue by GenaAiv** [NativeScript/NativeScript#10015]
### Issue Description

<CheckBox checked="false" style="background-color: transparent;"></CheckBox>
When adding the "background-color" property inside the style property on a Checkbox, the app crashes.
It is not because of the "transparent" value, because if i change it to any other color i get the same error.

System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method onCreateView failed
  System.err: Error: Cannot convert number to Landroid/content/res/ColorStateList; at index 0
  System.err:
  System.err: StackTrace:
  System.err: _applyBackground(file: node_modules\@nativescript\core\ui\core\view\index.android.js:921:0)
  System.err:   at onBackgroundOrBorderPropertyChanged(file: node_modules\@nativescript\core\ui\core\view\index.android.js:1003:0)
  System.err:   at _redrawNativeBackground(file: node_modules\@nativescript\core\ui\core\view\index.android.js:959:0)
  System.err:   at [backgroundInternal:setNative](file: node_modules\@nativescript\core\ui\core\view\index.android.js:898:0)
  System.err:   at applyAllNativeSetters(file: node_modules\@nativescript\core\ui\core\properties\index.js:1152:0)
  System.err:   at initNativeView(file: node_modules\@nativescript\core\ui\core\properties\index.js:1079:0)
  System.err:   at onResumeNativeUpdates(file: node_modules\@nativescript\core\ui\core\view-base\index.js:739:22)
  System.err:   at _resumeNativeUpdates(file: node_modules\@nativescript\core\ui\core\view-base\index.js:280:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:235:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\view-common.js:107:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\index.android.js:317:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
  System.err:   at callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at loadView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
  System.err:   at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
  System.err:   at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:772:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\view-common.js:107:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\index.android.js:317:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
  System.err:   at callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at loadView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
  System.err:   at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
  System.err:   at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:772:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\view-common.js:107:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\index.android.js:317:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
  System.err:   at callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at loadView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
  System.err:   at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
  System.err:   at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:772:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\view-common.js:107:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\index.android.js:317:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
  System.err:   at callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at loadView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
  System.err:   at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
  System.err:   at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:772:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\view-common.js:107:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\core\view\index.android.js:317:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at onLoaded(file: node_modules\@nativescript\core\ui\page\index.android.js:38:0)
  System.err:   at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
  System.err:   at callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
  System.err:   at loadView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
  System.err:   at _addViewCore(file: node_modules\@nativescript\core\ui\core\view-base\index.js:453:0)
  System.err:   at _addView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:439:0)
  System.err:   at onCreateView(file: node_modules\@nativescript\core\ui\frame\index.android.js:751:18)
  System.err:   at onCreateView(file: node_modules\@nativescript\core\ui\frame\fragment.android.js:28:0)
  System.err:   at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err:   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
  System.err:   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1175)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1153)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1149)
  System.err:   at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
  System.err:   at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
  System.err:   at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
  System.err:   at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
  System.err:   at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
  System.err:   at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
  System.err:   at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
  System.err:   at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
  System.err:   at android.os.Handler.handleCallback(Handler.java:938)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:99)
  System.err:   at android.os.Looper.loopOnce(Looper.java:201)
  System.err:   at android.os.Looper.loop(Looper.java:288)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:7842)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Environment

```yaml
OS: Windows 10 10.0.22000
CPU: (8) x64 Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
Shell: Not Found
node: 16.17.0
npm: 8.15.0
nativescript: Not Found

# android
java: 15.0.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.10.6
python3: Not Found
ruby: 3.1.2
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular-devkit/core": "^11.2.19",
  "@angular-devkit/schematics": "^11.2.19",
  "@angular/animations": "^14.2.0",
  "@angular/common": "^14.2.0",
  "@angular/compiler": "^14.2.0",
  "@angular/core": "^14.2.0",
  "@angular/forms": "^14.2.0",
  "@angular/platform-browser": "^14.2.0",
  "@angular/platform-browser-dynamic": "^14.2.0",
  "@angular/router": "^14.2.0",
  "@dsvishchov/nativescript-ngx-shadow": "^7.0.3",
  "@nativescript-community/ui-image": "^4.0.20",
  "@nativescript/angular": "^14.2.0",
  "@nativescript/camera": "^5.0.2",
  "@nativescript/core": "~8.3.0",
  "@nativescript/directions": "^2.0.0",
  "@nativescript/firebase-core": "^2.3.3",
  "@nativescript/firebase-firestore": "^2.3.1",
  "@nativescript/firebase-messaging": "^2.3.1",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/google-maps": "^1.4.6",
  "@nativescript/schematics": "^11.2.0",
  "@nativescript/types": "^8.3.1",
  "@nstudio/nativescript-checkbox": "^2.0.4",
  "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
  "@nstudio/nativescript-loading-indicator": "3.0.4",
  "@sergeymell/nativescript-svg": "^1.0.5",
  "angular-feather": "6.0.10",
  "fs": "0.0.1-security",
  "gradle": "^1.2.4",
  "hide-virtual-keyboard": "^1.0.1",
  "html-entities": "1.3.1",
  "jsonfile": "^6.1.0",
  "nativescript-audio": "^6.2.6",
  "nativescript-background-http": "4.2.1",
  "nativescript-carousel": "^7.0.1",
  "nativescript-directions": "^1.4.0",
  "nativescript-geolocation": "^5.1.0",
  "nativescript-image-popup": "^1.0.1",
  "nativescript-localstorage": "2.0.1",
  "nativescript-lottie": "^5.0.4",
  "nativescript-modal-datetimepicker": "1.2.2",
  "nativescript-permissions": "1.3.9",
  "nativescript-phone": "2.0.0",
  "nativescript-social-share": "1.6.0",
  "nativescript-theme-core": "2.0.24",
  "nativescript-ui-autocomplete": "file:nativescript-ui-autocomplete-7.0.2.tgz",
  "nativescript-ui-listview": "10.2.0",
  "nativescript-ui-sidedrawer": "^10.0.0",
  "nativescript-videoplayer": "^5.0.1",
  "nativescript-windowed-modal": "^7.0.0",
  "reflect-metadata": "0.1.13",
  "rxjs": "6.6.0",
  "tslint": "^5.16.0",
  "util": "^0.12.4",
  "webpack": "^5.74.0",
  "yarn": "^1.22.19",
  "zone.js": "^0.11.8"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^14.2.1",
  "@angular/compiler-cli": "^14.2.0",
  "@nativescript/android": "8.3.1",
  "@nativescript/ios": "~8.3.0",
  "@nativescript/preview-cli": "1.0.0",
  "@nativescript/webpack": "^5.0.8",
  "@ngtools/webpack": "^14.2.1",
  "@types/node": "^18.7.14",
  "copy-webpack-plugin": "^11.0.0",
  "typescript": "4.8.2"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
@GenaAiv Is it a plugin?
I think `@nstudio/nativescript-checkbox` needs property `fillColor` to style background.
See docs: https://www.npmjs.com/package/@nstudio/nativescript-checkbox

**Comment by cheroridedan** [comment]
I  also have the same problem
