### ISSUE TITLE
'ReferenceError: NativeClass is not defined' when using TypeScript 4.8+

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#10024]
### Issue Description

after upgrading typescript dev-dependency in the NativeScript TypeScript to version 4.8.3 using `npm install --save-dev typescript@latest` the app crashes with the following error:

`ReferenceError: NativeClass is not defined`
(see full log below in this thread)

I created a new project and added this dummy-component to the project:

```
//component.android.ts
@NativeClass()
class CustomClass extends android.view.View {}
```

```
//component.ios.ts
@NativeClass()
class MyDelegate extends UIResponder implements UIApplicationDelegate {
	public static ObjCProtocols = [UIApplicationDelegate];
}
```

And I import that in app.ts:
```
//app.ts
require("./components/component");
```

When using typescript 4.7.4, everything works as expected, but after migrating to 4.8.3, the app starts crashing.

### Reproduction

demo app:
[ns-nativeclass-issue.zip](https://github.com/NativeScript/NativeScript/files/9558227/ns-nativeclass-issue.zip)

### Relevant log output (if applicable)

```shell
Android stacktrace:

  System.err: ReferenceError: NativeClass is not defined
  System.err: File: (file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:27:0)
  System.err:
  System.err: StackTrace:
  System.err: ./app/components/component.android.ts(file: app/webpack:/ns-nativeclass-issue/app/components/component.android.ts:2:6)
  System.err:   at __webpack_require__(file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:24:0)
  System.err:   at fn(file: app/webpack:/ns-nativeclass-issue/webpack/runtime/hot module replacement:62:0)
  System.err:   at ./app/app.ts(file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:54:1)
  System.err:   at __webpack_require__(file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:24:0)
  System.err:   at __webpack_exec__(file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:322:39)
  System.err:   at (file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:323:318)
  System.err:   at __webpack_require__.X(file: app/webpack:/ns-nativeclass-issue/webpack/runtime/startup entrypoint:6:0)
  System.err:   at (file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:323:47)
  System.err:   at (file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:328:3)
  System.err:   at require(:1:266)
  System.err:
  System.err:
  System.err: ReferenceError: NativeClass is not defined
  System.err:
  System.err: StackTrace:
  System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
  System.err: ReferenceError: NativeClass is not defined
  System.err: File: (file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:27:0)
  System.err:
  System.err: StackTrace:
  System.err: ./app/components/component.android.ts(file: app/webpack:/ns-nativeclass-issue/app/components/component.android.ts:2:6)
  System.err:   at __webpack_require__(file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:24:0)
  System.err:   at fn(file: app/webpack:/ns-nativeclass-issue/webpack/runtime/hot module replacement:62:0)
  System.err:   at ./app/app.ts(file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:54:1)
  System.err:   at __webpack_require__(file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:24:0)
  System.err:   at __webpack_exec__(file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:322:39)
  System.err:   at (file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:323:318)
  System.err:   at __webpack_require__.X(file: app/webpack:/ns-nativeclass-issue/webpack/runtime/startup entrypoint:6:0)
  System.err:   at (file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:323:47)
  System.err:   at (file:///data/data/org.nativescript.nsnativeclassissue/files/app/bundle.js:328:3)
  System.err:   at require(:1:266)


iOS stacktrace:
  ***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
  at
  ./app/components/component.ios.ts(file: app/webpack:/ns-nativeclass-issue/app/components/component.ios.ts:2:6)
  at __webpack_require__(file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:24:0)
  at fn(file: app/webpack:/ns-nativeclass-issue/webpack/runtime/hot module replacement:62:0)
  at ./app/app.ts(file:///app/bundle.js:54:1)
  at __webpack_require__(file: app/webpack:/ns-nativeclass-issue/webpack/bootstrap:24:0)
  at __webpack_exec__(file:///app/bundle.js:323:39)
  at (file:///app/bundle.js:324:318)
  at __webpack_require__.X(file: app/webpack:/ns-nativeclass-issue/webpack/runtime/startup entrypoint:6:0)
  at (file:///app/bundle.js:324:47)
  at (file:///app/bundle.js:329:3)
  at require(:1:137)
```

### Environment

```yaml
OS: macOS 12.5.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.17.0
npm: 8.19.1
nativescript: 8.3.3

# android
java: 11.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.7
ruby: 2.7.4
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "^8.3.4",
  "@nativescript/theme": "~3.0.2"
},
"devDependencies": {
  "@nativescript/android": "^8.3.1",
  "@nativescript/ios": "^8.3.3",
  "@nativescript/types": "^8.3.1",
  "@nativescript/webpack": "^5.0.8",
  "typescript": "^4.8.3"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
@felixkrautschuk TypeScript 4.8 has breaking changes regarding annotations and this breaks things for us too.
For the time being, avoid using TS 4.8 at all costs.
