### ISSUE TITLE
Module 'Tabs' not found for element 'Tabs' {N} 8.3.0

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/NativeScript#10042]
### Issue Description

When adding the TABS component, the app does not show it {N} 8.3.0.

### Reproduction

Add <Tabs>  in proyect {N} 8.3.0

### Relevant log output (if applicable)

```shell
System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method onItemClick failed
  System.err: Error: Building UI from XML. @./components/viiatask/tasks/details/details.xml:7:9
  System.err:  > Module 'Tabs' not found for element 'Tabs'.
  System.err:    > instanceType is not a constructor
  System.err:
  System.err: StackTrace:
  System.err: ScopeError(file: app\webpack:\Invian\node_modules\@nativescript\core\utils\debug.js:51:0)
  System.err:   at SourceError(file: app\webpack:\Invian\node_modules\@nativescript\core\utils\debug.js:58:0)
  System.err:   at (file: app\webpack:\Invian\node_modules\@nativescript\core\ui\builder\xml2ui.js:54:0)
  System.err:   at (file: app\webpack:\Invian\node_modules\@nativescript\core\ui\builder\xml2ui.js:32:0)
  System.err:   at (file: app\webpack:\Invian\node_modules\@nativescript\core\xml\index.js:411:0)
  System.err:   at EasySAXParser.parse(file: app\webpack:\Invian\node_modules\@nativescript\core\js-libs\easysax\easysax.js:751:0)
  System.err:   at parse(file: app\webpack:\Invian\node_modules\@nativescript\core\xml\index.js:454:0)
  System.err:   at parse(file: app\webpack:\Invian\node_modules\@nativescript\core\ui\builder\xml2ui.js:41:0)
  System.err:   at parseInternal(file: app\webpack:\Invian\node_modules\@nativescript\core\ui\builder\index.js:181:0)
  System.err:   at loadInternal(file: app\webpack:\Invian\node_modules\@nativescript\core\ui\builder\index.js:93:0)
  System.err:   at createViewFromEntry(file: app\webpack:\Invian\node_modules\@nativescript\core\ui\builder\index.js:35:0)
  System.err:   at navigate(file: app\webpack:\Invian\node_modules\@nativescript\core\ui\frame\frame-common.js:180:21)
  System.err:   at goToFunc(file: app\webpack:\Invian\app\common\nav.js:11:0)
  System.err:   at exports.goTo(file: app\webpack:\Invian\app\common\nav.js:5:0)
  System.err:   at exports.itemTap(file: app\webpack:\Invian\app\components\viiatask\tasks\tasks.js:55:0)
  System.err:   at _handleEvent(file: app\webpack:\Invian\node_modules\@nativescript\core\data\observable\index.js:233:0)
  System.err:   at notify(file: app\webpack:\Invian\node_modules\@nativescript\core\data\observable\index.js:216:0)
  System.err:   at ItemClickListenerImpl.onItemClick(file: app\webpack:\Invian\node_modules\@nativescript\core\ui\list-view\index.android.js:28:0)
  System.err:   at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err:   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
  System.err:   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1175)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1153)
  System.err:   at com.tns.gen.java.lang.Object_vendor_30607_28_ItemClickListenerImpl.onItemClick(Object_vendor_30607_28_ItemClickListenerImpl.java:26)                                                                                                               istenerImpl.java:26)      
  System.err:   at android.widget.AdapterView.performItemClick(AdapterView.java:330)
  System.err:   at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
  System.err:   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3190)
  System.err:   at android.widget.AbsListView$3.run(AbsListView.java:4166)
  System.err:   at android.os.Handler.handleCallback(Handler.java:938)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:99)
  System.err:   at android.os.Looper.loopOnce(Looper.java:201)
  System.err:   at android.os.Looper.loop(Looper.java:288)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:7842)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Environment

```json
"dependencies": {
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.13",
  "@nativescript/core": "~8.3.0",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/google-maps": "^1.4.4",
  "@nativescript/imagepicker": "^1.0.7",
  "@nativescript/social-share": "^2.0.4",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/ui-charts": "^0.2.4",
  "@nstudio/nativescript-camera-plus": "^4.1.6",
  "@viia/nativescript-video-editor": "file:viia-nativescript-video-editor-1.0.0.tgz",
  "nativescript-videoplayer": "^5.0.1"
},
"devDependencies": {
  "@nativescript/android": "8.3.1",
  "@nativescript/webpack": "~5.0.6",
  "eslint": "^8.23.1"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
@vicmasa This component was removed in NativeScript 8.0 along with BottomNavigation. To use either of those, take a look at community plugins for material components. For tabs, `@nativescript-community/ui-material-tabs` is the right replacement.
