### ISSUE TITLE
XML parsing bug

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10091]
### Issue Description

Hi,

There is a parsing error with xml parser especially with the char `&` .. please see the [the sample project](https://stackblitz.com/edit/nativescript-stackblitz-templates-jngz37?file=app%2Fmain-page.xml,app%2Fmain-view-model.ts&title=NativeScript%20Starter%20TypeScript) and see that it throw an error 

### Relevant log output (if applicable)

```shell
ERROR in ./app/main-page.xml
Module build failed (from ./node_modules/@nativescript/webpack/dist/loaders/xml-namespace-loader/index.js):
Error: Invalid character in entity name
Line: 10
Column: 117
Char: =
    at error (/home/projects/nativescript-stackblitz-templates-jngz37/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/projects/nativescript-stackblitz-templates-jngz37/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/home/projects/nativescript-stackblitz-templates-jngz37/node_modules/sax/lib/sax.js:1491:13)
    at Object.parseXML (/home/projects/nativescript-stackblitz-templates-jngz37/node_modules/@nativescript/webpack/dist/loaders/xml-namespace-loader/index.js:151:15)
    at Object.loader (/home/projects/nativescript-stackblitz-templates-jngz37/node_modules/@nativescript/webpack/dist/loaders/xml-namespace-loader/index.js:16:20)
 @ ./app/ sync \.(xml%7Cjs%7C(?<%21\.d\.)ts%7Cs?css)$ ./main-page.xml
 @ ./node_modules/@nativescript/webpack/dist/stubs/virtual-entry-typescript.js 3:16-103
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by shirakaba** [comment]
This is expected and correct behaviour - `&` is a reserved character in XML, so you need to escape it appropriately when using it in an XML element’s attribute. See: https://www.ibm.com/docs/en/was-liberty/base?topic=SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_xml_escape.htm
