### ISSUE TITLE
Core modules incompatible with JSC runtime

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#10150]
### Issue Description

Seems the latest core modules are incompatible with the JSC runtime. Seems caused because of the use of nullish operators. When trying to start the app i get an immediate crash:
```
  Unzipping LiveSync folder. This could take a while...
  Unzipped 8 entries in 69.108009ms.
  ***** Fatal JavaScript exception - application has been terminated. *****
  Native stack trace:
  1   0x103416348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
  2   0x103460428 -[TNSRuntime executeModule:referredBy:]
  3   0x1028d7884 main
  4   0x1dd80a960 <redacted>
  JavaScript stack trace:
  file: node_modules/@nativescript/core/accessibility/accessibility-service-common.js:11:0
  at asyncFunctionResume([native code])
  at [native code]
  at promiseReactionJob([native code])
  at require([native code])
  at file: app/webpack/runtime/require chunk loading:29:0
  at file: app/webpack/runtime/ensure chunk:6:0
  at reduce([native code])
  at file: app/webpack/runtime/ensure chunk:5:0
  at map([native code])
  at file: app/webpack/runtime/startup entrypoint:5:0
  at file:///app/bundle.js:15732:48
  at anonymous(file:///app/bundle.js:15737:3)
  at evaluate([native code])
  at moduleEvaluation([native code])
  at [native code]
  at asyncFunctionResume([native code])
  at [native code]
  at promiseReactionJob([native code])
  JavaScript error:
  file: node_modules/@nativescript/core/accessibility/accessibility-service-common.js:11:0: JS ERROR SyntaxError: Unexpected token '.'
  ***** Fatal JavaScript exception - application has been terminated. *****
  Native stack trace:
  1   0x1050da348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
  2   0x105124428 -[TNSRuntime executeModule:referredBy:]
  3   0x10457b884 main
  4   0x1dd80a960 <redacted>
  JavaScript stack trace:
  file: node_modules/@nativescript/core/accessibility/accessibility-service-common.js:11:0
  at asyncFunctionResume([native code])
  at [native code]
  at promiseReactionJob([native code])
  at require([native code])
  at file: app/webpack/runtime/require chunk loading:29:0
  at file: app/webpack/runtime/ensure chunk:6:0
  at reduce([native code])
  at file: app/webpack/runtime/ensure chunk:5:0
  at map([native code])
  at file: app/webpack/runtime/startup entrypoint:5:0
  at file:///app/bundle.js:15732:48
  at anonymous(file:///app/bundle.js:15737:3)
  at evaluate([native code])
  at moduleEvaluation([native code])
  at [native code]
  at asyncFunctionResume([native code])
  at [native code]
  at promiseReactionJob([native code])
  JavaScript error:
  file: node_modules/@nativescript/core/accessibility/accessibility-service-common.js:11:0: JS ERROR SyntaxError: Unexpected token '.'
```
Happens here, in the first line of the callback:
```js
        function callback() {
            const self = ref?.get();
            if (!self) {
                sharedA11YObservable.off(Observable.propertyChangeEvent, callback);
                return;
            }
            const newValue = !!sharedA11YObservable.accessibilityServiceEnabled;
            if (newValue !== lastValue) {
                self.set(AccessibilityServiceEnabledPropName, newValue);
                lastValue = newValue;
            }
        }
```
Is there anyway we can get the latest core modules working on the JSC runtime? So far up until 8.4 version I have used latest core modules with the old JSC runtime. Tried couple of times to use the v8 iOS runtime but the app is unstable and crashes way too often to be actually usable in production environment. And we actually need the 8.4 code modules because of Android 33 related changes that are in there.

### Environment

```yaml
OS: macOS 13.0.1
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Shell: /bin/zsh
node: 16.14.2
npm: 8.12.1
nativescript: 8.4.0

# android
java: 11.0.14.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.7.5
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.2",
  "@nativescript-community/ui-pulltorefresh": "^2.5.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/camera": "^5.0.9",
  "@nativescript/core": "8.4.2",
  "@nativescript/datetimepicker": "^2.1.9",
  "@nativescript/directions": "^2.0.0",
  "@nativescript/fingerprint-auth": "file:_local-packages/nativescript-fingerprint-auth-8.0.0.tgz",
  "@nativescript/firebase-messaging-core": "^2.5.2",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/imagepicker": "^1.0.6",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/local-notifications": "^6.0.0",
  "@nativescript/secure-storage": "^3.0.0",
  "@proplugins/nativescript-azure-notification-hubs": "^3.0.0",
  "@proplugins/nativescript-drawingpad": "file:_local-packages/proplugins-nativescript-drawingpad-4.0.0.tgz",
  "@proplugins/nativescript-drop-down": "^9.0.2",
  "@proplugins/nativescript-masked-text-field": "^6.0.0",
  "@proplugins/nativescript-orientation": "^2.5.0",
  "@triniwiz/nativescript-couchbase": "^1.3.1",
  "crypto-js": "^3.1.9-1",
  "jwt-decode": "^2.2.0",
  "moment": "^2.24.0",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-converters": "^2.0.0",
  "nativescript-feedback": "^2.0.0",
  "nativescript-theme-core": "^1.0.6",
  "nativescript-ui-autocomplete": "^8.0.1",
  "nativescript-ui-listview": "^10.0.2",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "tslib": "^2.3.0"
},
"devDependencies": {
  "@nativescript/android": "8.4.0",
  "@nativescript/eslint-plugin": "0.0.4",
  "@nativescript/ios": "^6.5.6",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "^5.0.0",
  "@types/crypto-js": "^3.1.43",
  "@typescript-eslint/eslint-plugin": "^5.20.0",
  "@typescript-eslint/eslint-plugin-tslint": "^5.20.0",
  "@typescript-eslint/parser": "^5.20.0",
  "eslint": "^7.32.0",
  "eslint-import-resolver-typescript": "^2.7.1",
  "eslint-plugin-import": "^2.26.0",
  "eslint-plugin-import-newlines": "^1.2.2",
  "eslint-plugin-prefer-arrow": "^1.2.3",
  "eslint-plugin-simple-import-sort": "^7.0.0",
  "replace-in-file": "^5.0.2",
  "ts-patch": "^1.3.4",
  "typescript": "~4.3.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Can try configuring babel to transpile any potentially unsupported code.

**Comment by PeterStaev** [comment]
@rigor789 , that sounds like an interesting idea, but I've never done/seen anything similar. I would research to see if i can find anything. Do you have any refs to something similar (not necessarily related to NS)?

**Comment by rigor789** [comment]
babel-loader: https://www.npmjs.com/package/babel-loader
adding a loader: https://docs.nativescript.org/webpack.html#adding-a-loader
`--env.verbose` to inspect webpack config, since you'll be making changes to an existing rule (for ts/js).

**Comment by PeterStaev** [comment]
@rigor789 , I've added the babel loader, this resolved the problem with the optional chaining usages, but now there is a problem because of the migration to the new `WeakRef` types that is listed as a breaking change in 8.4. I'm getting tons of errors that `deref` is not a function.

**Comment by PeterStaev** [comment]
Added a PR: https://github.com/NativeScript/ios-runtime/pull/1299 that adds the `deref` function. Sadly can't build this locally on mac as seems the build scripts are not compatible with latest Xcode, so no way for me to test this locally. Hopefully it will resolve the undefined function problem.

**Comment by edusperoni** [comment]
Hey, you should be able to just polyfill instead:


```
WeakRef.prototype.deref = WeakRef.prototype.get
```

Might be easier then waiting for a new JSC version.

**Comment by PeterStaev** [comment]
Thanks @edusperoni , this worked like a charm!

**Comment by PeterStaev** [comment]
Here is the webpack config that I used:
```ts
const webpack = require("@nativescript/webpack");
module.exports = (env) => {
    webpack.init(env);

    webpack.chainWebpack((config) => {
        config.module
            .rule("babel-loader-node-modules")
            .test(/node_modules\/.*\.js$/)
            .use("babel-loader")
            .loader("babel-loader")
            .options({
                presets: [
                    ["@babel/preset-env", { targets: "chrome 79" }]
                ],
            });
    });

    return webpack.resolveConfig()
}
```
