### ISSUE TITLE
RadListView - This application depends upon a library published using Angular version 14.2.2, which requires Angular version 14.0.0 or newer to work correctly

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [NativeScript/NativeScript#10172]
### Issue Description

I'm trying to work with RadListView in my project following the documentation from here
https://docs.nativescript.org/plugins/nativescript-ui/rad-list-view.html#overview

Scenario 1:
After the installation of the plugin
`npm install nativescript-ui-listview
`
and following the instruction from the old documentation site: https://v7.docs.nativescript.org/angular/ui/ng-components/ng-radlistview/getting-started

I got this error on the run time (ns run android)

**This application depends upon a library published using Angular version 15.0.1, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.**

For more details of the error and the project configuration please find bellow the snapshot image and logs
 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/46108848/212902383-4086bfce-e31b-43d0-94ef-36f76c68dc09.png">

Scenario 2:
Removing NativeScriptUIListViewModule from app.module.ts (that because on the new documentation this step is not specified as in the old one ) then the list of my items is not printed anymore.

I'm sure the the list of issues it's sent to UI because just removing the prefix Rad the list is printed.

```
<ListView [items]="dataItems">
        <ng-template tkListItemTemplate let-item="item">
            <StackLayout orientation="vertical">
                <Label class="nameLabel" [text]="item.name"></Label>
                <Label class="descriptionLabel" [text]="item.description"></Label>
            </StackLayout>
        </ng-template>
</ListView>
```

### Reproduction

N/A

### Relevant log output (if applicable)

```shell
ERROR in ./node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs
Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs: This application depends upon a library published using Angular version 15.0.1, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  992 | }
  993 | CdkPortal.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.0.1", ngImport: i0, type: CdkPortal, deps: [{ token: i0.TemplateRef }, { token: i0.ViewContainerRef }], target: i0.ɵɵFactoryTarget.Directive });
> 994 | CdkPortal.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "15.0.1", type: CdkPortal, selector: "[cdkPortal]", exportAs: ["cdkPortal"], usesInheritance: true, ngImport: i0 });
      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  995 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "15.0.1", ngImport: i0, type: CdkPortal, decorators: [{
  996 |             type: Directive,
  997 |             args: [{'
    at run (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/@babel/core/lib/transformation/index.js:37:15)
    at run.next (<anonymous>)
    at Function.transform (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:261:32)
    at /Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:223:11)
    at /Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:37:40
 @ ./src/main.ts 3:0-88 5:0-25 6:30-50

ERROR in ./node_modules/nativescript-ui-listview/angular/fesm2015/nativescript-ui-listview-angular.mjs
Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/nativescript-ui-listview/angular/fesm2015/nativescript-ui-listview-angular.mjs: This application depends upon a library published using Angular version 14.2.2, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  464 | }
  465 | RadListViewComponent.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.2.2", ngImport: i0, type: RadListViewComponent, deps: [{ token: ElementRef }, { token: IterableDiffers }, { token: NativeScriptRendererFactory }, { token: NgZone }], target: i0.ɵɵFactoryTarget.Component });
> 466 | RadListViewComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "14.2.2", type: RadListViewComponent, selector: "RadListView", inputs: { autoReuseViews: "autoReuseViews", changeAnimationsEnabled: "changeAnimationsEnabled", trackBy: "trackBy", items: "items" }, outputs: { setupItemView: "setupItemView" }, host: { listeners: { "itemLoadingInternal": "onItemLoadingInternal($event)", "itemReappearingInternal": "onItemReappearingInternal($event)", "itemRecyclingInternal": "onItemRecyclingInternal($event)", "itemDisposingInternal": "onItemDisposingInternal($event)" } }, queries: [{ propertyName: "itemTemplateQuery", first: true, predicate: TemplateRef, descendants: true, read: TemplateRef }], viewQueries: [{ propertyName: "loader", first: true, predicate: ["loader"], descendants: true, read: ViewContainerRef }], ngImport: i0, template: `
      |                             ^
  467 |                 <DetachedContainer>
  468 |                         <ng-container #loader></ng-container>
  469 |                 </DetachedContainer>'
    at run (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/@babel/core/lib/transformation/index.js:37:15)
    at run.next (<anonymous>)
    at Function.transform (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:261:32)
    at /Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:223:11)
    at /Users/ittradconsulting/Development/PROJECTS/MOBILE/ANGULAR_NATIVESCRIPT/newdevelopment/fidelity-card-client/node_modules/gensync/index.js:37:40
 @ ./src/app/app.module.ts 5:0-80 30:12-40
 @ ./src/main.ts 4:0-45 6:69-78

webpack 5.75.0 compiled with 2 errors in 22664 ms
Webpack compilation complete. Watching for file changes.
```

### Environment

```yaml
OS: macOS 12.6.1
CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Shell: /bin/bash
node: 17.4.0
npm: 8.15.0
nativescript: 8.4.0

# android
java: 13.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: /undefined
cocoapods: 1.11.2
python: Not Found
python3: 3.7.3
ruby: 2.6.10
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~13.1.1",
  "@angular/common": "~13.1.1",
  "@angular/compiler": "~13.1.1",
  "@angular/core": "~13.1.1",
  "@angular/forms": "~13.1.1",
  "@angular/platform-browser": "~13.1.1",
  "@angular/platform-browser-dynamic": "~13.1.1",
  "@angular/router": "~13.1.1",
  "@nativescript-community/ui-material-snackbar": "^7.0.25",
  "@nativescript-community/ui-pulltorefresh": "^2.5.1",
  "@nativescript/angular": "^15.0.1",
  "@nativescript/core": "^8.4.4",
  "@nativescript/facebook": "^2.1.3",
  "@nativescript/firebase-auth": "^1.0.0-alpha.42",
  "@nativescript/firebase-core": "^1.0.0-alpha.42",
  "@nativescript/google-signin": "^1.0.0-alpha.0",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "~3.0.1",
  "@nativescript/twitter": "^1.0.0",
  "js-sha512": "^0.8.0",
  "nativescript-ui-listview": "^14.2.4",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "rxjs": "~7.4.0",
  "zone.js": "~0.11.4"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^13.2.3",
  "@angular/compiler-cli": "~13.1.1",
  "@nativescript/android": "8.1.1",
  "@nativescript/ios": "8.1.0",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "^5.0.4",
  "@ngtools/webpack": "~13.1.1",
  "typescript": "~4.4.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
Hi @ittrad-mobile-lab give you are using less than Angular 14, you can use this version:
```
"nativescript-ui-listview": "~10.2.8"
```
Then `ns clean`.

**Comment by ittrad-mobile-lab** [comment]
> 10.2.8

No way I got the same error and I got also more info:
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/46108848/213003991-061534ac-da43-44fe-86dc-13d9b18679dd.png">

Nevertheless I succeed to makes it work, on run time, using the version 9.1.4, but the printed list is not as expected but:
[object.Object]
[object.Object]
[object.Object]... (10 times)  

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/46108848/213004456-81cc54bc-b8a1-4320-8796-0fd2cf11a450.png">

In this case I'm wondering if it exists a decent tutorial to migrate/upgrade my project to angular 14?

Many thanks

**Comment by NathanWalker** [comment]
Give this a try (make sure using node 16, 17 or 18):

npm install -g nativescript 

confirm with “ns -v” that you have 8.4 then:

ns migrate

**Comment by ittrad-mobile-lab** [comment]
> Give this a try (make sure using node 16, 17 or 18):
> 
> npm install -g nativescript
> 
> confirm with “ns -v” that you have 8.4 then:
> 
> ns migrate

Great advice. Doing so now is working fine.
On the migration I got only a problem with the twitter SDK I wish I investigate more and also
I have to make the modification from the image below to make it work

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/46108848/213029275-14da208f-fd03-4f32-8c1f-61ca3a0ebd58.png">

**Comment by NathanWalker** [comment]
That makes sense @ittrad-mobile-lab good to hear. I would target 33 - General advice as of now would be to use these app.gradle settings:

```
android {
  compileSdkVersion 33
  buildToolsVersion "33.0.0"
  defaultConfig {
    minSdkVersion 23
    targetSdkVersion 33
```
