### ISSUE TITLE
[Android][NS 8.4] Exception thrown when restoring state for ScrollView

### ISSUE THREAD

**Issue by jcassidyav** [NativeScript/NativeScript#10200]
### Issue Description

When an app which contains a Vertical ScrollView has it's state restored, (e.g. after it has been sent to the background and then brought forward, and the os has decided to remove the activity from memory.) the following exception will be thrown:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.scrollViewCrash/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Reproduction

1. create a plain ns typescript app
2. add a scrollView 
3. Enable in Developer settings on the phone "Don't Keep activities, Destroy every activity as soon as the user leaves it" 
4. run app , send to background
5. bring app to forground
6. Error will be shown.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by vallemar** [comment]
@jcassidyav you can fix this with this Code: https://github.com/NativeScript/plugins/issues/375#issuecomment-1344155953

**Comment by CatchABus** [comment]
@vallemar Unfortunately, this is a different case that occurs due to a certain phone setting.
@farfromrefug This started with the addition of `NestedScrollView` inheritance. That class has built-in support for saved state along with a dozen of methods we copied to `VerticalScrollView` itself.

Check these 2 classes:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/core/core/src/main/java/androidx/core/widget/NestedScrollView.java
https://github.com/NativeScript/NativeScript/blob/main/packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/VerticalScrollView.java

You'll notice the latter has always contained source code from the first one. #9199 will definitely still more work, cleanup mostly.

**Comment by farfromrefug** [comment]
@jcassidyav are you using native-api-usage?

**Comment by lambourn** [comment]
Thanks @CatchABus for the PR. 

This issue is hitting us as well with a release build in the field :-( 

Is there any other quick fix/workaround for now, maybe a monkey-patch applied at run- or build-time?

**Comment by CatchABus** [comment]
> Thanks @CatchABus for the PR.
> 
> This issue is hitting us as well with a release build in the field :-(
> 
> Is there any other quick fix/workaround for now, maybe a monkey-patch applied at run- or build-time?

This is still in progress for the time being.
If it's urgent, you can use an older version of android widgets build inside your core package.
This version is right before vertical scrollview update: https://github.com/NativeScript/NativeScript/blob/75eefa669deaea09f79e4a15593f1af985a0fea1/packages/core/platforms/android/widgets-release.aar

**Comment by lambourn** [comment]
one potential fix for now is to use the `activityPausedEvent` to navigate to a non-scroll view and use `activityResumedEvent` to go back. That seems to work as a quick fix.

**Comment by vallemar** [comment]
@CatchABus  I don't know if it's the same error but I'm getting this with version `"@nativescript/android": "^8.5.0-alpha.1"`.

```
Exception com.tns.NativeScriptException:
  at com.tns.Runtime.callJSMethodNative
  at com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1302)
  at com.tns.Runtime.callJSMethodImpl (Runtime.java:1188)
  at com.tns.Runtime.callJSMethod (Runtime.java:1175)
  at com.tns.Runtime.callJSMethod (Runtime.java:1153)
  at com.tns.Runtime.callJSMethod (Runtime.java:1149)
  at com.tns.NativeScriptActivity.onStart (NativeScriptActivity.java:33)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1511)
  at android.app.Activity.performStart (Activity.java:8489)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3800)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2363)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:210)
  at android.os.Looper.loop (Looper.java:299)
  at android.app.ActivityThread.main (ActivityThread.java:8116)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:559)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
Caused by java.lang.ClassCastException:
  at org.nativescript.widgets.VerticalScrollView.onRestoreInstanceState (VerticalScrollView.java:235)
  at android.view.View.dispatchRestoreInstanceState (View.java:21672)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4012)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4018)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4018)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4018)
  at android.view.View.restoreHierarchyState (View.java:21650)
  at androidx.fragment.app.Fragment.restoreViewState (Fragment.java:689)
  at androidx.fragment.app.Fragment.restoreViewState (Fragment.java:3151)
  at androidx.fragment.app.Fragment.performActivityCreated (Fragment.java:3142)
  at androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java:579)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:264)
  at androidx.fragment.app.FragmentStore.moveToExpectedState (FragmentStore.java:113)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1433)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2977)
  at androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:2895)
  at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:263)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:351)
  at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:248)
```

Should I open a new problem or is it related to this one?

**Comment by CatchABus** [comment]
> @CatchABus I don't know if it's the same error but I'm getting this with version `"@nativescript/android": "^8.5.0-alpha.1"`.
> 
> ```
> Exception com.tns.NativeScriptException:
>   at com.tns.Runtime.callJSMethodNative
>   at com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1302)
>   at com.tns.Runtime.callJSMethodImpl (Runtime.java:1188)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1175)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1153)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1149)
>   at com.tns.NativeScriptActivity.onStart (NativeScriptActivity.java:33)
>   at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1511)
>   at android.app.Activity.performStart (Activity.java:8489)
>   at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3800)
>   at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
>   at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
>   at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
>   at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2363)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loopOnce (Looper.java:210)
>   at android.os.Looper.loop (Looper.java:299)
>   at android.app.ActivityThread.main (ActivityThread.java:8116)
>   at java.lang.reflect.Method.invoke
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:559)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
> Caused by java.lang.ClassCastException:
>   at org.nativescript.widgets.VerticalScrollView.onRestoreInstanceState (VerticalScrollView.java:235)
>   at android.view.View.dispatchRestoreInstanceState (View.java:21672)
>   at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4012)
>   at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4018)
>   at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4018)
>   at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:4018)
>   at android.view.View.restoreHierarchyState (View.java:21650)
>   at androidx.fragment.app.Fragment.restoreViewState (Fragment.java:689)
>   at androidx.fragment.app.Fragment.restoreViewState (Fragment.java:3151)
>   at androidx.fragment.app.Fragment.performActivityCreated (Fragment.java:3142)
>   at androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java:579)
>   at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:264)
>   at androidx.fragment.app.FragmentStore.moveToExpectedState (FragmentStore.java:113)
>   at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1433)
>   at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2977)
>   at androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:2895)
>   at androidx.fragment.app.FragmentController.dispatchActivityCreated (FragmentController.java:263)
>   at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:351)
>   at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:248)
> ```
> 
> Should I open a new problem or is it related to this one?

Fix is actually included in core package. Do you mean you use latest core alpha but android alpha gives you trouble?
I think a new issue with requested information would be helpful.

**Comment by vallemar** [comment]
@CatchABus  sorry, I got confused with the version of android and core. I'll try the latest version of core and let you know if I have any bugs. Thank you!

**Comment by SeanKelly369** [comment]
It's still occurring on Samsung devices using Android 12
