### ISSUE TITLE
Integrating NS Angular app to existing Native Android app is crashing.

### ISSUE THREAD

**Issue by Ashish-A360** [NativeScript/NativeScript#10342]
### Issue Description

When we are integrating the NativeScript (angular) App into our existing Native Android app, while navigating from Native screen to NativeScript screen first time navigation is working fine. But when we come back to Native screen and navigate again to NativeScript part, the app is crashing.

The same issue happening even with the sample Hello world app/Drawer app.

PS: With or without embedded flag the app is crashing. However we specifically needs embedded to be true.

![Screenshot_1689094046](https://github.com/NativeScript/NativeScript/assets/139355685/c2feb1e9-7871-4cd2-8fd6-23608290897c)
 

### Reproduction

1. Integrate latest NS app to Native Android App
2. Launch the app
3. Navigate from Native screen to NativeScript Screen
4. Press back and come back to Native Screen
5. Repeat step 3
6. App is crashing
![Screenshot_1689094001](https://github.com/NativeScript/NativeScript/assets/139355685/cdcfd99c-9ca4-4085-a0be-53c9660fa3f7)

### Relevant log output (if applicable)

```shell
2023-07-12 18:51:06.976  3455-3455  AndroidRuntime          com.example.nsthirdapp               E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.nsthirdapp, PID: 3455
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.nsthirdapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
                                                                                                    TypeError: Cannot read properties of undefined (reading 'cssClasses')
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
                                                                                                    TypeError: Cannot read properties of undefined (reading 'cssClasses')
                                                                                                    	at com.tns.Runtime.callJSMethodNative(Native Method)
                                                                                                    	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
                                                                                                    	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
                                                                                                    	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
                                                                                                    	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
                                                                                                    	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
                                                                                                    	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:57)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	... 12 more
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
The error is likely from one of these lines:

https://github.com/search?q=repo%3ANativeScript%2FNativeScript%20path%3Apackages%2Fcore%2Fapplication%2Fapplication-common.ts%20%22.cssClasses%22&type=code

![image](https://github.com/NativeScript/NativeScript/assets/879060/8ceef64b-1ed3-4aef-af1f-d96e9a4aa560)

We might need to adjust the application lifecycle in the embedded case on android. Looking into it further to determine proper fix...

**Comment by Ashish-A360** [comment]
@rigor789 What is the status of bug? When can we expect the fix?

**Comment by rigor789** [comment]
I believe https://github.com/NativeScript/NativeScript/commit/bd8e1b8e79f95335d4e813a6ab283b43e1a8d6e0 should help here, though there may be other issues to address in core. Give latest patch 8.5.9 a try see how it does.
