### ISSUE TITLE
[Svelte] Svelte starter project errors on preview. 

### ISSUE THREAD

**Issue by kamiifx** [NativeScript/NativeScript#10410]
### Issue Description

When I do  : 

`ns create example-app --svelte `  and then   `ns preview` (Connecting to device succesfully)

I get on build : 

```
✖ Building for android
  Compiled with some errors in 47.01ms

error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

ERROR in ./app/App.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: [svelte-preprocess] Encountered type error
    at throwError (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\modules\errors.js:5:11)
    at throwTypescriptError (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\modules\errors.js:9:28)
    at transpileTs (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\transformers\typescript.js:177:47)
    at mixedImportsTranspiler (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\transformers\typescript.js:232:60)
    at transformer (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\transformers\typescript.js:302:11)
    at transform (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\autoProcess.js:37:12)
    at async C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\autoProcess.js:118:29
    at async script (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte-preprocess\dist\autoProcess.js:148:33)
    at async process_single_tag (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte\compiler.js:32587:28)
    at async Promise.all (index 0)
    at async replace_in_code (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte\compiler.js:32477:27)
    at async process_tag (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte\compiler.js:32601:30)
    at async preprocess (C:\Users\kamii\Documents\Projects\dostn\node_modules\svelte\compiler.js:32638:31)
 @ ./app/app.ts 9:0-31 10:20-23

webpack compiled with 1 error
```

### Reproduction

I reproduced this by following the example on: https://docs.nativescript.org/tutorials/build-a-master-detail-app-with-svelte

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
Closing as not related to core.
