### ISSUE TITLE
ListView : change one item's backgroundColor apply on several

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1265]
Hi,

When i tap on an item of a ListView, i want to change its background color.
Unfortunately, when i set the backgroundColor property, the color applies also on several other items.

* https://appetize.io/app/qjq797e7zhk0f4hhu0k20btucc
* http://dl.free.fr/vD62PWbdy

I think the problem occurs when the ListView is scrollable or when a CSS class is applied inside the itemTemplate.
If you remove the CSS class on the GridLayout inside the itemTemplate, the ListView is fully rendering in the screen and the issue doesn't appear.

* Windows 10
* TNS 1.5.1
* Android SDK 23.1.0

Regards,
Guillaume

**Comment by N3ll** [comment]
@guillaume-roy , can you please post the code that you are using to build the ListView.

**Comment by guillaume-roy** [comment]
Hi @N3ll ,

In my previous post you can find the full source code zipped.
But, here is my code :

* main-page.xml
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout orientation="vertical">
    <Label text="Tap on an item"/>
    <ListView items="{{items}}" itemTap="onSelectItem">
		<ListView.itemTemplate>
			<GridLayout class="list-view-item">
				<Label text="{{name}}"/>
			</GridLayout>
		</ListView.itemTemplate>
    </ListView>
  </StackLayout>
</Page>
```

* main-page.js
```javascript
var vmModule = require("./main-view-model");
var colorModule = require("color");

function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = vmModule.mainViewModel;
}
exports.pageLoaded = pageLoaded;

function onSelectItem(args) {
	var gridLayout = args.view;
	gridLayout.backgroundColor = new colorModule.Color("#DCEDC8");
}
exports.onSelectItem = onSelectItem;
```
* main-view-model.js
```javascript
var observable = require("data/observable");
var HelloWorldModel = (function (_super) {
    __extends(HelloWorldModel, _super);
    function HelloWorldModel() {
        _super.call(this);
        this.items = [];
        for(var i = 0; i < 20; i++) {
            this.items.push({
                id: i,
                name: "Item " + i
            });
        }
    }
    return HelloWorldModel;
})(observable.Observable);
exports.HelloWorldModel = HelloWorldModel;
exports.mainViewModel = new HelloWorldModel();
```
* app.css
```css
.list-view-item {
  height: 48;
  font-size: 16;
  color: #212121;
  padding-top: 16;
  padding-bottom: 16;
  padding-left: 16;
  padding-right: 16; }
```

Regards,
Guillaume

**Comment by bradmartin** [comment]
Not certain but isn't this because the listview is reusing the actual elements it creates? So if you have 20 items on screen and start scrolling and adding in more, its still approximately the 20 elements you had initially. Just what I thought was happening from my understanding, pretty certain that's why on web based apps when scrolling long lists you use 'virtual scrolling' which reuses DOM elements because painting new elements when scrolling is a memory nightmare waiting to  happen.

 Ive also seen this before in a listview with infinite  scrolling.

**Comment by N3ll** [comment]
@guillaume-roy , sorry for making you paste the code! I guess, I just got lost in the french :) @bradmartin  is absolutely right about the reusing of the cells.
What you can do is to attach an [itemLoadingEvent](https://docs.nativescript.org/ApiReference/ui/list-view/ListView.html) to the ListView and check whether the item, which is loading, should be selected - thus colored or not - thus using the default color.

**Comment by guillaume-roy** [comment]
@N3ll  thanks for your reply.
Your solution is fine when i load the view and when there is items already selected.
But at first, how can i change the background when the user tap on item ?

**Comment by N3ll** [comment]
Hey, @guillaume-roy! I looked more deeply in the project and I found a better solution. It is more correct to work with the data and not with the UI. Thus I made the items in the ListView **Observable** and added one new property **isSelected**. Every time the **function onSelectItem(args)** is called the **isSelected** will be switch the the opposite value. This property is bound to the value of the CSS class in the XML. Depending on whether the item is selected or not, there will be a suitable CSS class to be applied. Check out the code below and tell me if it works for you

**main-page.xml**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout orientation="vertical">
    <Label text="Tap on an item"/>
    <ListView items="{{items}}" itemTap="onSelectItem">
        <ListView.itemTemplate >
            <GridLayout >
                <Label text="{{name}}"  class="{{isSelected ? 'selected' : 'list-view-item'}}"/>
            </GridLayout>
        </ListView.itemTemplate>
    </ListView>
  </StackLayout>
</Page>
```
**main-page.js**
```
var vmModule = require("./main-view-model");
var colorModule = require("color");

function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = vmModule.mainViewModel;
}
exports.pageLoaded = pageLoaded;

function onSelectItem(args) {
    var gridLayout = args.view;
    var bindingCtx = gridLayout.bindingContext;

    bindingCtx.isSelected =  !bindingCtx.isSelected;
}
exports.onSelectItem = onSelectItem;
```
**main-view-model.js**
```
var observable = require("data/observable");

var HelloWorldModel = (function (_super) {
    __extends(HelloWorldModel, _super);
    function HelloWorldModel() {
        _super.call(this);

        this.items = [];
        for(var i = 0; i < 20; i++) {
            this.items.push(new observable.Observable({
                id: i,
                name: "Item " + i,
                isSelected : false
            }));
        }
    }
    return HelloWorldModel;
})(observable.Observable);
exports.HelloWorldModel = HelloWorldModel;
exports.mainViewModel = new HelloWorldModel();
```
**app.css**
```
.list-view-item {
  height: 48;
  font-size: 16;
  color: #212121;
  background-color: #FFFFFF;
  padding-top: 16;
  padding-bottom: 16;
  padding-left: 16;
  padding-right: 16; 
}

.selected {
  height: 48;
  font-size: 16;
  background-color: #DCEDC8;
  padding-top: 16;
  padding-bottom: 16;
  padding-left: 16;
  padding-right: 16;
}
```

**Comment by guillaume-roy** [comment]
@N3ll Thank you, this solution is working for me. :+1:

**Comment by mayureshjadhav** [comment]
Hello,

I am getting following error. Can you please help me?

java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(14, class android.widget.ListView) with Adapter(class com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l47_c38__ListViewAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1562)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:3838)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3637)
	at android.view.View.dispatchTouchEvent(View.java:8476)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
	at android.view.View.dispatchPointerEvent(View.java:8671)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by francorobles** [comment]
This bug exists again in 4.2.0.

**Comment by francorobles** [comment]
@guillaume-roy have you tried this in the latest Nativescript version?

**Comment by guillaume-roy** [comment]
@francorobles No sorry, I don't maintain my app anymore.
