### ISSUE TITLE
TabView crashes the app when Don't keep activities option is turned on

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#1415]
App under test: https://github.com/NativeScript/NativeScript/blob/master/apps/gallery-app/content/tab-view.xml

App crashes if there is TabView on the page and the app is minimized/restored when 
Developer options -> Don't keep activities option is turned on of the phone.

Console log:
```
E/AndroidRuntime(24588): FATAL EXCEPTION: main
E/AndroidRuntime(24588): Process: org.nativescript.TestApp, PID: 24588
E/AndroidRuntime(24588): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.TestApp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
E/AndroidRuntime(24588): Calling js method onCreate failed
E/AndroidRuntime(24588): 
E/AndroidRuntime(24588): Error: View already has a parent. View: GridLayout(41) Parent: TabView(40)
E/AndroidRuntime(24588): File: "/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view-common.js, line: 884, column: 12
E/AndroidRuntime(24588): 
E/AndroidRuntime(24588): StackTrace: 
E/AndroidRuntime(24588):        Frame: function:'View._addView', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view-common.js', line: 884, column: 19
E/AndroidRuntime(24588):        Frame: function:'', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/tab-view/tab-view.js', line: 199, column: 23
E/AndroidRuntime(24588):        Frame: function:'TabView._onItemsPropertyChangedSetNativeValue', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/tab-view/tab-view.js', line: 194, column: 19
E/AndroidRuntime(24588):        Frame: function:'itemsProperty.metadata.onSetNativeValue', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/tab-view/tab-view-common.js', line: 80, column: 13
E/AndroidRuntime(24588):        Frame: function:'ProxyObject._trySetNativeValue', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/proxy.js', line: 81, column: 27
E/AndroidRuntime(24588):        Frame: function:'eachPropertyCallback', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/proxy.js', line: 57, column: 18
E/AndroidRuntime(24588):        Frame: function:'DependencyObservable._eachSetProperty', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/dependency-observable.js', line: 384, column: 22
E/AndroidRuntime(24588):        Frame: function:'ProxyObject._syncNativeProperties', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/proxy.js', line: 60, column: 14
E/AndroidRuntime(24588):        Frame: function:'View._syncNativeProperties', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view-common.js', line: 953, column: 48
E/AndroidRuntime(24588):        Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js', line: 211, column: 14
E/AndroidRuntime(24588):        Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js', line: 163, column: 14
E/AndroidRuntime(24588):        Frame: function:'eachChild', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js', line: 168, column: 23
E/AndroidRuntime(24588):        Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/content-view/content-view.js', line: 44, column: 13
E/AndroidRuntime(24588):        Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/page/page-common.js', line: 235, column: 41
E/AndroidRuntime(24588):        Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js', line: 174, column: 18
E/AndroidRuntime(24588):        Frame: function:'eachChild', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js', line: 168, column: 23
E/AndroidRuntime(24588):        Frame: function:'Frame._eachChildView', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/frame/frame-common.js', line: 296, column: 13
E/AndroidRuntime(24588):        Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js', line: 174, column: 18
E/AndroidRuntime(24588):        Frame: function:'Frame._onActivityCreated', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/frame/frame.js', line: 240, column: 14
E/AndroidRuntime(24588):        Frame: function:'NativeActivity.onCreate', file:'/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/frame/frame.js', line: 332, column: 20
E/AndroidRuntime(24588): 
E/AndroidRuntime(24588): 
E/AndroidRuntime(24588):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
E/AndroidRuntime(24588):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
E/AndroidRuntime(24588):        at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime(24588):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
E/AndroidRuntime(24588):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(24588):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(24588):        at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(24588):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24588):        at java.lang.reflect.Method.invoke(Method.
```

**Comment by nsndeck** [comment]
Fixed with commit #1419.
