### ISSUE TITLE
Exception thrown in device when changin anything in app.css

### ISSUE THREAD

**Issue by markens** [NativeScript/NativeScript#1540]
Hi everyone,

I started trying to run an existing app for styling purposes and when I run livesync --watch to a connected Android device, and I modified some properties inside app.css, then this exception is shown on the device's screen: 
`com.tns.NativeScriptException: 
Calling js method onCreateView failed
platform cannot be initialized with different sets of providers.
File: "/data/data/com.gft.appverse.showcase/files/app/tns_modules/angular2/src/core/application_ref.js, line: 78, column: 12
StackTrace: 
Frame: function:'platform', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/angular2/src/core/application_ref.js', line: 78, column: 13
Frame: function:'bootstrap', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/nativescript-angular/application.js', line: 51, column: 19
Frame: function:'onLoadedHandler', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/nativescript-angular/application.js', line: 67, column: 17
Frame: function:'Observable.notify', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/data/observable/observable.js', line: 155, column: 23
Frame: function:'Observable._emit', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/data/observable/observable.js', line: 174, column: 18
Frame: function:'View.onLoaded', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/core/view-common.js', line: 590, column: 14
Frame: function:'View.onLoaded', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/core/view.js', line: 101, column: 35
Frame: function:'Page.onLoaded', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/page/page-common.js', line: 33, column: 35
Frame: function:'View._addViewCore', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/core/view-common.js', line: 913, column: 18
Frame: function:'View._addViewCore', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/core/view.js', line: 145, column: 39
Frame: function:'View._addView', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/core/view-common.js', line: 901, column: 14
Frame: function:'onFragmentShown', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/frame/frame.js', line: 89, column: 11
Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/com.gft.appverse.showcase/files/app/tns_modules/ui/frame/frame.js', line: 36, column: 17
at com.tns.Platform.callJSMethodNative(Native Method)
at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:799)
at com.tns.Platform.callJSMethod(Platform.java:700)
at com.tns.Platform.callJSMethod(Platform.java:680)
at com.tns.Platform.callJSMethod(Platform.java:670)
at com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l21_c42__.onCreateView(android.app.Fragment.java)
at android.app.Fragment.performCreateView(Fragment.java:2053)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
at android.app.BackStackRecord.run(BackStackRecord.java:834)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5294)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
`
It's only displayed on the device, nothing wrong happens in tns livesync process...
Then the only thing I can do is stop the app and relaunching it..

Any ideas? 

Thanks ;)

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-angular#64
