### ISSUE TITLE
'Array.create' is not a function?

### ISSUE THREAD

**Issue by gabrielbiga** [NativeScript/NativeScript#1551]
Hi! I'm getting this error when I use the segmented bar in Android.

```xml
<SegmentedBar selectedindex="{{ selectedScreen }}" cssClass="example-types-bar" iOS:selectedBackgroundColor="#F5F5F5" android:selectedBackgroundColor="#00E676">
    <SegmentedBar.items>
        <SegmentedBarItem title="Ranked"/>
        <SegmentedBarItem title="New"/>
        <SegmentedBarItem title="Trending"/>
     </SegmentedBar.items>
</SegmentedBar>
```

In iOS works fine, but in Android I'm getting this stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.liquare.maya/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
Calling js method onCreateView failed
 
TypeError: Array.create is not a function
File: "/data/data/org.liquare.maya/files/app/tns_modules/ui/segmented-bar/segmented-bar.js, line: 66, column: 32
 
StackTrace:
    Frame: function:'onItemsPropertyChanged', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/segmented-bar/segmented-bar.js', line: 66, column: 33
    Frame: function:'ProxyObject._trySetNativeValue', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/proxy.js', line: 81, column: 27
    Frame: function:'eachPropertyCallback', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/proxy.js', line: 60, column: 18
    Frame: function:'DependencyObservable._eachSetProperty', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/dependency-observable.js', line: 386, column: 22
    Frame: function:'ProxyObject._syncNativeProperties', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/proxy.js', line: 63, column: 14
    Frame: function:'View._syncNativeProperties', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view-common.js', line: 984, column: 48
    Frame: function:'View._onContextChanged', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 212, column: 14
    Frame: function:'View._onAttached', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 164, column: 14
    Frame: function:'eachChild', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 169, column: 23
    Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/layouts/layout-base.js', line: 139, column: 22
    Frame: function:'View._onAttached', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 175, column: 18
    Frame: function:'eachChild', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 169, column: 23
    Frame: function:'RadSideDrawer._eachChildView', file:'/data/data/org.liquare.maya/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer-common.js', line: 166, column: 13
    Frame: function:'View._onAttached', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 175, column: 18
    Frame: function:'eachChild', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 169, column: 23
    Frame: function:'ContentView._eachChildView', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/content-view/content-view.js', line: 45, column: 13
    Frame: function:'Page._eachChildView', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/page/page-common.js', line: 246, column: 41
    Frame: function:'View._onAttached', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 175, column: 18
    Frame: function:'View._addViewCore', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view.js', line: 144, column: 18
    Frame: function:'View._addView', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/core/view-common.js', line: 913, column: 14
    Frame: function:'onFragmentShown', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/frame/frame.js', line: 90, column: 11
    Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/org.liquare.maya/files/app/tns_modules/ui/frame/frame.js', line: 37, column: 17
 
 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException:
Calling js method onCreateView failed 
```

I did some tests and I can't use any android native array types (such Array.fromJavaType and something like that)

What I need to do get this thing working?

Thanks!

**Comment by enchev** [comment]
Most probably you are using latest modules with old android runtime. If you use build from our master branch make sure that you have all components up to date (android, ios runtimes, etc.)

**Comment by PanayotCankov** [comment]
We had similar problem. It appeared when we were using new modules with old Android runtime.
Array.create is a shorthand function that creates native (read Java) arrays, and was introduced recently. It is used in the SegmentedBar in the master branch of the modules.

Can you share the versions of the tns-code-modules and the CLI you are using? Updating to official versions should fix the problem.
