### ISSUE TITLE
Another Android Bug after NativeScript 1.6, maybe can help your team to improve( not sure )

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1705]
The test phone is a Huawei P8 lite version( Android 5.0 ), it's very easy to re-show the issue, just like my loginUI, if I do type in the "password" field, it will crash( sometimes need to long press to show up the "copy/paste" floating mean to cause crash ), UI super simple, looks like this:

[https://drive.google.com/file/d/0B-AooW_48tzISmZCbnNNeDB2ZUU/view?usp=sharing](url)

And here is the crash log output, if your team found something, that's good, if have no idea, then just ignore it, I just want to do a "potential bug report" :)

```javascript
com.tns.NativeScriptException: No weak reference found. Attempt to use cleared object reference id=366
at com.tns.Platform.getJavaObjectByID(Platform.java:633)
at com.tns.Platform.callJSMethodNative(Native Method)
at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
at com.tns.Platform.callJSMethod(Platform.java:711)
at com.tns.Platform.callJSMethod(Platform.java:690)
at com.tns.Platform.callJSMethod(Platform.java:680)
at com.tns.gen.android.text.TextWatcher_ftns_modules_ui_editable-text-base_editable-text-base_l22_c29__.afterTextChanged(android.text.TextWatcher.java)
at android.widget.TextView.sendAfterTextChanged(TextView.java:7771)
at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9563)
at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:976)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:520)
at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:216)
at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:33)
at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:249)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:398)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:82)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by mikeres0** [comment]
+1 I've got something very similar to this.

**Comment by enchev** [comment]
Hey @slavchev can you help with this? I've tried to fix it [here](https://github.com/NativeScript/NativeScript/issues/1405) however it seems that we still have problems.

**Comment by slavchev** [comment]
@wisonye @mikeres0 

This seems like a bug in {N} for Android runtime. We had this bug reported from other customers as well but unfortunately we didn't reproduce it. I am very interested in a small repro project, if possible, as this error is critical as it indicates wrong object lifetime management.

**Comment by wisonye** [comment]
@slavchev

I think NativeScript team should put this on a high priority, as it's already happen many many times in my product, and it's a very basic situation and easy to happen in Android, it maybe can cause more.developers afriad to use NativeScritp for this reason, it's very important !!!

**Comment by slavchev** [comment]
@wisonye 

Can you help us by sending a simple repro project?

**Comment by slavchev** [comment]
Move this issue https://github.com/NativeScript/android-runtime/issues/382
