### ISSUE TITLE
Android: Crash when suspend application

### ISSUE THREAD

**Issue by gabrielbiga** [NativeScript/NativeScript#1812]
## Please, provide the details below:
After updating the platform to 1.7.0 I can't suspend my application

### Tell us about the problem
When I suspend the application the first time works, but the second time I get a stacktrace.

### Which platform(s) does your issue occur on?
Android - Genymotion emulator

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.7.0
- Cross-platform modules: 1.7.0
- Runtime(s): 1.7.0 

### Please tell us how to recreate the issue in as much detail as possible.
1 - Open app
2 - Suspend app
3 - Restore app
4 - Suspend again
5 - Application stopped working  

Java stacktrace:
```
The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
com.tns.NativeScriptException: Cannot find object id for instance=com.tns.NativeScriptApplication@240c405b
	at com.tns.Platform.callJSMethod(Platform.java:709)
	at com.tns.Platform.callJSMethod(Platform.java:694)
	at com.tns.Platform.callJSMethod(Platform.java:684)
	at com.tns.NativeScriptApplication.onTrimMemory(NativeScriptApplication.java:30)
	at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4251)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by Daxito** [comment]
@gabrielbiga I had the exact same issue and https://github.com/NativeScript/NativeScript/issues/1779#issuecomment-198332165 seemed to fix it.

**Comment by gabrielbiga** [comment]
Thanks @Daxito! Seems isn't fixed yet. I'll close this and follow up with your issue...
