### ISSUE TITLE
IOS pod plugin

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#1872]
Hi,

I'm getting a error in this situation. I have a plugin to Google SignIn has Podefile to configure a lib. When I add in demo project and run: `tns run ios --log trace` the project execute normally, but when execute for the second time this error is showed:

`SyntaxError: Expected "/*", "//" or "{" but "<" found.`

Only is posible see this error because I changed the errors.js file, that is seems to be a bug. I change `nativescript/lib/common/errors.js - line 9` to:

`var stackLines = error.stack ? error.stack.split("\n") : error.toString().split("\n");`

Then SyntaxError is throwed in file  `nativescript/node_modules/xcode/lib/parser/pbxproj.js line 325`

To show stacktrace I change:

`return "Expected " + expectedDesc + " but " + foundDesc + " found."`

to

`throw Error("Expected " + expectedDesc + " but " + foundDesc + " found.");`

Then the result was:

`
Error: Expected "/*", "//" or "{" but "<" found.
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/errors.js:123:33
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/services/commands-service.js:84:106
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/yok.js:208:124
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/services/commands-service.js:51:55
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/errors.js:123:33
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    - - - - -
    at Error (native)
    at buildMessage (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/xcode/lib/parser/pbxproj.js:327:15)
    at peg$buildException (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/xcode/lib/parser/pbxproj.js:338:38)
    at Object.parse (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/xcode/lib/parser/pbxproj.js:1838:13)
    at pbxProject.parseSync (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/xcode/lib/pbxProject.js:46:24)
    at IOSProjectService.createPbxProj (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/services/ios-project-service.js:469:17)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/services/ios-project-service.js:321:33
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/services/platform-service.js:228:66
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/helpers.js:215:36
    at PlatformService.descriptor.value [as preparePlatformCore] (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/common/helpers.js:182:24)
    at /Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/lib/services/platform-service.js:182:26
    at Function.settle (/Users/ricardobocchi/.nvm/versions/node/v5.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
`

I noticed that when I add platform ios the file `platform/ios/demo.xcodeproj/project.pbxproj` has a format content, and when I add the plugin with Podfile the file, the file format content is changed... the first is a kind of comment and the second is the xml normally of xcode. I think that this is the cause of bug.

Steps:

1 - Create a project
2 - Add ios platform - work fine allways - the file project.pbxproj has a content format
3 - Add Google SignIn plugin - or another.. I tried with facebbok plugin too
3 - run `tns run ios --log trace`  - pod is installed
4 - App running file - the file project.pbxproj already has another content format
5 - run again `tns run ios --log trace` 
6 - SyntaxError erro is showed

thanks!

**Comment by NickIliev** [comment]
This problem is referred to this issue [#1639 ](https://github.com/NativeScript/nativescript-cli/issues/1639 )
