### ISSUE TITLE
Problem with Gradle

### ISSUE THREAD

**Issue by munseym** [NativeScript/NativeScript#1897]
tns doctor recognizes my gradle installation:
[log2.txt](https://github.com/NativeScript/NativeScript/files/205510/log2.txt)

However, when I run tns run android or tns emulate android, it tries to download gradle, and fails on the proxy setting.  Proxy is correctly set in config.json, but this piece does not seem to honor that setting.  Proxy is also set in the Java installation and http_proxy environment variable.

C:\Users\xxxx\Documents\angular\sample-ng-todomvc>tns run android
Executing before-prepare hook from C:\Users\xxxx\Documents\angular\sample-ng-todomvc\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.8.9
Project successfully prepared
Downloading https://services.gradle.org/distributions/gradle-2.8-bin.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:59)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Command C:\Users\xxxx\Documents\angular\sample-ng-todomvc\platforms\android\gradlew.bat failed with exit code 1

**Comment by xuezier** [comment]
set the http proxy to the download.
In Console window. enter the code:
`set http_proxy=http://127.0.0.1:your_proxy_port`
`set https_proxy=http://127.0.0.1:your_proxy_prot`

Should be able to solve the problem.

**Comment by NickIliev** [comment]
@munseym 
Can you verify @xuezier solution?

Also you can check the following steps as described [here](https://github.com/NativeScript/nativescript-cli#configure-proxy-usage)

- On your file system, locate the directory where the nativescript npm package is installed.
- In a text editor, open config → config.json.
- Set USE_PROXY to true.
- Set PROXY_PORT.
- Set PROXY_HOSTNAME.
- Make sure to preserve the quotation marks and commas as in the initial config.json file.

Alternativly you can check this discussion [#302](https://github.com/NativeScript/nativescript-cli/issues/302)

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#414
