### ISSUE TITLE
There is a crash when executing animations in Android too fast

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/NativeScript#1935]

**Comment by vchimev** [comment]
```
D/AndroidRuntime( 2413): Shutting down VM
E/AndroidRuntime( 2413): FATAL EXCEPTION: main
E/AndroidRuntime( 2413): Process: org.nativescript.animationdemo, PID: 2413
E/AndroidRuntime( 2413): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: java.lang.NullPointerException: Attempt to invoke direct method 'java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[])' on a null object reference
E/AndroidRuntime( 2413): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
E/AndroidRuntime( 2413): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/AndroidRuntime( 2413): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/AndroidRuntime( 2413): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2413): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2413): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 2413): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2413): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 2413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 2413): Caused by: java.lang.NullPointerException: Attempt to invoke direct method 'java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[])' on a null object reference
E/AndroidRuntime( 2413): 	at com.tns.Runtime.callJSMethod(Runtime.java:770)
E/AndroidRuntime( 2413): 	at com.tns.Runtime.callJSMethod(Runtime.java:751)
E/AndroidRuntime( 2413): 	at com.tns.Runtime.callJSMethod(Runtime.java:741)
E/AndroidRuntime( 2413): 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
E/AndroidRuntime( 2413): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
E/AndroidRuntime( 2413): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
E/AndroidRuntime( 2413): 	... 9 more
W/ActivityManager(  738):   Force finishing activity 1 org.nativescript.animationdemo/com.tns.ErrorReportActivity
E/EGL_emulation(  719): tid 719: eglCreateSyncKHR(1209): error 0x3004 (EGL_BAD_ATTRIBUTE)
```
