### ISSUE TITLE
Error at running cli after install

### ISSUE THREAD

**Issue by elidiazgt** [NativeScript/NativeScript#208]
$ nativescript --help
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Function.Object.defineProperty.get [as killSwitchDir] (/usr/lib/node_modules/nativescript/lib/com
mon/services/cancellation.js:55:25)
    at new CancellationService (/usr/lib/node_modules/nativescript/lib/common/services/cancellation.js:1
3:53)
    at Yok.resolveConstructor (/usr/lib/node_modules/nativescript/lib/common/yok.js:289:18)
    at Yok.resolveByName (/usr/lib/node_modules/nativescript/lib/common/yok.js:315:44)
    at Yok.resolve (/usr/lib/node_modules/nativescript/lib/common/yok.js:247:25)
    at /usr/lib/node_modules/nativescript/lib/common/yok.js:280:30
    at Array.map (native)

**Comment by Nathanaela** [comment]
Looking at the source it is looking for one of these environmental variables:
**process.env.SUDO_USER**  or  **process.env.USER**   or  **process.env.USERNAME**

What unix variant are you running that one of those isn't defined?    Can you run a output your exports and see what variable actually has your user name in it?

**Comment by teobugslayer** [comment]
Hi @elidiazgt,

can you run ```nativescript --help --log trace > log.txt``` and post the contents of log.txt?

**Comment by elidiazgt** [comment]
Hello @teobugslayer 
This is te log.txt content

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Function.Object.defineProperty.get [as killSwitchDir] (/usr/lib/node_modules/nativescript/lib/com
mon/services/cancellation.js:55:25)
    at new CancellationService (/usr/lib/node_modules/nativescript/lib/common/services/cancellation.js:1
3:53)
    at Yok.resolveConstructor (/usr/lib/node_modules/nativescript/lib/common/yok.js:289:18)
    at Yok.resolveByName (/usr/lib/node_modules/nativescript/lib/common/yok.js:315:44)
    at Yok.resolve (/usr/lib/node_modules/nativescript/lib/common/yok.js:247:25)
    at /usr/lib/node_modules/nativescript/lib/common/yok.js:280:30
    at Array.map (native)

**Comment by elidiazgt** [comment]
hello @Nathanaela  am using a docker container, if i run this commands
echo $USER
echo $SUDO_USER
echo $USERNAME
the result is empty, i need to set those variables? can i mantain my virgen docker?

**Comment by Nathanaela** [comment]
@teobugslayer -- the issue is a missing environmental variable -- their are a couple places in the TNS/NativeScript cli & several gruntfiles where Telerik is assuming a environmental variable is set and it will crash if they are not.   This is one of those cases...

@elidiazgt - you can either before you run TNS/NativeScript, do a **export USER="\<user\>"** where \<user\> is the user in the container so that the TNS command can create the lock directory.  Another choice would be to type **"set | grep -i \<user\>"** again where \<user\> is what user that is running inside the docker container and see which environmental variable IS set to have the user name.  Then I (or someone at Telerik) can commit a quick change that will add that environmental variable to the list of valid variables to pull the environment from.  A third possibility would be for you to do a quick **export USER=\<user\>** once before you run the TNS command so that user is set.

**Comment by Nathanaela** [comment]
@teobugslayer -- since you actually appear to be one of the Telerik devs on CLI; the issue is the "cancellation.ts" file inside the mobile-cli-lib project.   https://github.com/telerik/mobile-cli-lib/blob/master/services/cancellation.ts#L61 -- I'll did a pull request https://github.com/telerik/mobile-cli-lib/pull/345 to fix this.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#498
