### ISSUE TITLE
Android ActionBar.titleView throws with specific CSS attached to the top element

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2184]
**Duplicate of https://github.com/NativeScript/NativeScript/issues/1710**

When we have ActionBar.titleView with the extended syntax and CSS is applied to its top element Android will crash with the following error :  
```
java.lang.ClassCastException: org.nativescript.widgets.CommonLayoutParams cannot be cast to android.support.v7.widget.Toolbar$LayoutParams
```
Code to reproduce the issue :  

in _main-page.xml_
```
  <Page.actionBar>
      <ActionBar>
          <ActionBar.titleView>
              <Label text="TITLE" class="logo" />
          </ActionBar.titleView>
          <ActionBar.actionItems>
              <ActionItem text="Left"  />
              <ActionItem text="Right"  />
          </ActionBar.actionItems> 
      </ActionBar>
  </Page.actionBar>
```

_main-page.css_
```
.logo {
    margin:10;
}

```

Will throw also with **_width, height, margin-top, margin-bottom, margin-right, margin-left_**

**Comment by NathanWalker** [comment]
Seems like any layout css applied to ActionBar via `app.android.css` causes this error.
Ran into also with:
`horizontal-align:left`.

**Comment by hamorphis** [comment]
```
06-29 11:14:16.037 7987-7987/? D/NSLayout: org.nativescript.widgets.GridLayout{3c0472d V.E...... ......I. 0,0-0,0} :measureChild: android.support.v7.widget.Toolbar{200a24f V.E...... ......ID 0,0-0,0} MeasureSpec: EXACTLY 1080, MeasureSpec: UNSPECIFIED 0
06-29 11:14:16.063 7987-7987/? D/AndroidRuntime: Shutting down VM
06-29 11:14:16.065 7987-7987/? W/System.err: java.lang.ClassCastException: org.nativescript.widgets.CommonLayoutParams cannot be cast to android.support.v7.widget.Toolbar$LayoutParams
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.support.v7.widget.Toolbar.onMeasure(Toolbar.java:1320)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.View.measure(View.java:18788)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:231)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumns(GridLayout.java:959)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.MeasureHelper.measureFixedColumnsNoStarRows(GridLayout.java:757)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:850)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.View.measure(View.java:18788)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:231)
06-29 11:14:16.065 7987-7987/? W/System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.View.measure(View.java:18788)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.View.measure(View.java:18788)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.View.measure(View.java:18788)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-29 11:14:16.065 7987-7987/? W/System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.View.measure(View.java:18788)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:606)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-29 11:14:16.065 7987-7987/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-29 11:14:16.065 7987-7987/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-29 11:14:16.065 7987-7987/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-29 11:14:16.065 7987-7987/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hamorphis** [comment]
Sample project: https://github.com/hamorphis/issue-2184
