### ISSUE TITLE
Error: Cannot set property '_FRAGMENT' of undefined

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#2188]
### Did you verify this is a real problem by searching
Yes, Nothing found

### Tell us about the problem
I am using Telerik Analytics and there is this Uncaught Error that is showing in our logs a bunch of times, I am not able to duplicate it since I am not sure how, all I can see is the log and I guess a user whose App keeps crashing.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): Android 2.0.0
- Plugin(s): `"lodash": "^4.12.0",
		"moment": "^2.13.0",
		"nativescript-appversion": "^1.2.0",
		"nativescript-dom": "^1.0.3",
		"nativescript-drawingpad": "^1.0.2",
		"nativescript-geolocation": "0.0.11",
		"nativescript-globalevents": "^1.1.0",
		"nativescript-iqkeyboardmanager": "^1.0.1",
		"nativescript-loading-indicator": "^2.0.1",
		"nativescript-master-technology": "^1.0.4",		
		"nativescript-screenshot": "0.0.2",
		"nativescript-snackbar": "^1.0.3",
		"nativescript-sqlite": "^1.0.8",
		"nativescript-telerik-analytics": "^1.0.0",
		"nativescript-telerik-ui-pro": "file:plugins/nativescript-ui-pro.tgz",
		"numeral": "^1.5.3",
		"pubsub-js": "^1.5.3",
		"string": "^3.3.1"`

### Please tell us how to recreate the issue in as much detail as possible.
I don't know how to duplicate this issue, seems like random for the end user, my hope is that by looking at the call stack and the error message you can tell what could be wrong.

### Is there code involved? 

I have the call stack

```
`{
  "nativeException": {
    
  },
  "stackTrace": "java.lang.RuntimeException: Unable to resume activity {com.abc.abc/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onDestroy failed
TypeError: Cannot set property '_FRAGMENT' of undefined
File: \"/data/data/com.abc.abc/files/app/tns_modules/ui/frame/frame.js, line: 554, column: 29\n\nStackTrace: 
Frame: function:'FragmentClass.onDestroy', file:'/data/data/com.abc.abc/files/app/tns_modules/ui/frame/frame.js', line: 554, column: 30


at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
at android.app.ActivityThread.access$900(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Caused by: com.tns.NativeScriptException: \nCalling js method onDestroy failed
TypeError: Cannot set property '_FRAGMENT' of undefined\nFile: \"/data/data/com.abc.abc/files/app/tns_modules/ui/frame/frame.js, line: 554, column: 29\n\nStackTrace: \n\tFrame: function:'FragmentClass.onDestroy', file:'/data/data/com.abc.abc/files/app/tns_modules/ui/frame/frame.js', line: 554, column: 30


at com.tns.Runtime.callJSMethodNative(Native Method)\n\tat com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
at com.tns.Runtime.callJSMethod(Runtime.java:712)
at com.tns.Runtime.callJSMethod(Runtime.java:693)
at com.tns.Runtime.callJSMethod(Runtime.java:683)
at com.tns.FragmentClass.onDestroy(FragmentClass.java:61)
at android.app.Fragment.performDestroy(Fragment.java:2266)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1172)
at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:1589)
at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1556)
at android.app.FragmentManagerImpl$3.run(FragmentManager.java:506)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
at android.app.Activity.performResume(Activity.java:6087)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
... 12 more
"
}`

```

**Comment by Daxito** [comment]
I think you need to add a check like this:
`if (typeof this.entry != 'undefined'){
 this.entry[FRAGMENT] = undefined; 
}`
To the file `ui\frame\frame.android.js` line 554.
I am going to add it since I see this error in my logs a lot of times now.

**Comment by hamorphis** [comment]
We have almost totally re-written the entire fragment navigation logic. This issue should be gone with the upcoming release of version 2.1 at the end of June. Please, re-open this issue in case the problem persists after upgrading to version 2.1.
