### ISSUE TITLE
ListView inside Custom Dialog error

### ISSUE THREAD

**Issue by gnocetti** [NativeScript/NativeScript#2201]
VERSIONS:

tns --version: 2.0.1

tns_core_modules: "version": "2.0.1"

app packages.json:

"tns-android": {
			"version": "2.0.0"
		}

Plugins:

	"dependencies": {
		"@angular/common": "2.0.0-rc.1",
		"@angular/compiler": "2.0.0-rc.1",
		"@angular/core": "2.0.0-rc.1",
		"@angular/http": "^2.0.0-rc.1",
		"@angular/platform-browser": "2.0.0-rc.1",
		"@angular/platform-browser-dynamic": "2.0.0-rc.1",
		"@angular/platform-server": "2.0.0-rc.1",
		"@angular/router-deprecated": "2.0.0-rc.1",
		"nativescript-angular": "0.1.1",
		"nativescript-sqlite": "^1.0.8",
		"nativescript-telerik-ui": "^1.1.1",
		"tns-core-modules": "^2.0.1"
	},
	"devDependencies": {
		"babel-traverse": "6.9.0",
		"babel-types": "6.9.0",
		"babylon": "6.8.0",
		"filewalker": "0.1.2",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.3.2",
		"typescript": "^1.8.10"
	}

I am trying to use ListView inside a Custom Dialog, I follow tutorial about custom dialog in Angular (project is NativeScript angular2). All is rendered ok, but when I go back from custom dialog I get this error:

```
JS: EXCEPTION: TypeError: Cannot read property '_removeView' of undefined
JS: STACKTRACE:
JS: TypeError: Cannot read property '_removeView' of undefined
JS:     at ListView._onDetached (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/list-view/list-view.js:109:24)
JS:     at eachChild (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/core/view.js:187:27)
JS:     at StackLayout.LayoutBase._eachChildView (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/layouts/layout-base-common.js:146:22)
JS:     at StackLayout.View._onDetached (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/core/view.js:191:18)
JS:     at eachChild (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/core/view.js:187:27)
JS:     at StackLayout.LayoutBase._eachChildView (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/layouts/layout-base-common.js:146:22)
JS:     at StackLayout.View._onDetached (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/core/view.js:191:18)
JS:     at eachChild (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/core/view.js:187:27)
JS:     at ProxyViewContainer.LayoutBase._eachChildView (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/layouts/layout-base-common.js:146:22)
JS:     at ProxyViewContainer.View._onDetached (/data/data/org.nativescript.coconsolticqueuereport/files/app/tns_modules/ui/core/view.js:191:18)
JS: Cancel
```

Error occurs: when CustomdDialog returns       this.params.closeCallback(resultado); or when I back from custom dialog pressing back android button. Same error.

Code Attached:

pages/principal/principal.component.ts:

```
import {Component, ElementRef, OnInit, ViewChild} from "@angular/core";
import {ModalDialogService, ModalDialogOptions, ModalDialogHost} from "nativescript-angular/modal-dialog";

import {ListPicker} from '../../components/list-picker/list-picker';

@Component({
  selector: "principal-page",
  providers: [RemoteService,ModalDialogService],
  directives: [ModalDialogHost],
  templateUrl: "pages/principal/principal.html",
  styleUrls: ["pages/principal/principal-common.css"],
})
export class PrincipalPage implements OnInit {
   constructor(private _router: Router, private _remoteService: RemoteService, private page: Page, private globalApp: globalApp, private modalService: ModalDialogService) {
   }

  dialogoFechas()
  {
    var opciones: ModalDialogOptions = {      
      fullscreen: true
    }
    this.modalService.showModal(ListPicker,opciones).then((resultado) => {
      console.log(resultado)
    })
  }
}
```

pages/principal/principal.html:

```
<ActionBar title="Principal">
  <ActionItem (tap)="onShare()"
      ios.systemIcon="9" ios.position="right"
      android.position="right"
      android.systemIcon="ic_menu_share" 
      android.position="actionBar"
      (tap)="refrescar()"></ActionItem>    
</ActionBar>

<StackLayout orientation="vertical" modal-dialog-host>
    <Button [text]="fecha1" (tap)="dialogoFechas()"></Button>
    <Button [text]="fecha2"></Button>
</StackLayout>
```

components/list-picker/list-picker.ts

```
import {Component, ElementRef, OnInit, ViewChild} from "@angular/core";
import {ModalDialogParams} from "nativescript-angular/modal-dialog";
import {Page} from "ui/page";
import {ListView} from "ui/list-view";
import {Router} from "@angular/router-deprecated";

@Component({
  selector: "modal-content",
  templateUrl: "components/list-picker/list-picker.html",
  styleUrls: ["components/list-picker/list-picker-common.css"],
})
export class ListPicker {
    
    private listaElementos: Array<any> = [];
    private _selectedCallback: (selectedItem: any) => void;
    private _items: any[];
    private _itemSeleccionado: ListItem;
    
    public result: ListItem;
    constructor(private params: ModalDialogParams)    
    {
        console.log(params);
        this._items = [];
        this._items.push({Id: 1, Name: "Pruebas"});
        this._items.push({Id: 1, Name: "Pruebas 2"});
    }
    
    public close(resultado: string)
    {
      this.params.closeCallback(resultado);
    }
    
    seleccionarItem(item: ListItem) {
        if (this._itemSeleccionado) {
            this._itemSeleccionado.isSelected = false;
        }

        this._itemSeleccionado = item;
        if (this._itemSeleccionado) {
            this._itemSeleccionado.isSelected = true;
        }
    }    
    
    public itemSeleccionado(args)
    {
        console.log("------------------------ ItemTapped: " + args.index);
        //this._selectedCallback(this._itemSeleccionado);
    }
    
    listo()
    {
      
    }
}

```

components/list-picker/list-picker.html

```
<GridLayout rows="auto, *">
    
  <GridLayout row="0" columns="*, auto" class="add-bar">
    <TextField #groceryTextField hint="Enter a grocery item" col="0"></TextField>    
  </GridLayout>    
    
        <ListView [items]="_items" (itemTap)="itemSeleccionado($event)" row="1" >
            <template let-item="item">
                <Label [text]="item.Name">
                    
                </Label>
            </template>
        </ListView>
 
</GridLayout>
```

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#265
