### ISSUE TITLE
livesync error in fibers/future.js: [object Object] is not a future

### ISSUE THREAD

**Issue by stnguyen** [NativeScript/NativeScript#2336]
I can run the app fine on iOS simulator, but when I try livesync, it doesn't work

> tns livesync ios --emulator --watch --log trace

```
Project successfully prepared
AfterHookName for command prepare is after-prepare
BeforeHookName for command livesync is before-livesync
Executing before-livesync hook from /Users/stnguyenvn/sandbox/sample-Groceries/hooks/before-livesync/nativescript-angular-sync .js
Executing before-livesync hook at location /Users/stnguyenvn/sandbox/sample-Groceries/hooks/before-livesync/nativescript-angular-sync .js in-process
Hook completed
Error: [object Object] is not a future
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:123:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:84:106
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/dispatchers.js:38:85
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:21:45
    - - - - -
    at getFutures (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:202:10)
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:214:16)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:231:28
    at arrayMap (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/lodash/index.js:1378:25)
    at Function.map (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/lodash/index.js:6154:14)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:228:29
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:257:55
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/livesync-service-base.js:197:63
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/livesync-service-base.js:38:45
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, info, init, install, livesync, platform, platform|add, platform|remove, platform|update, plugin, plugin|add, plugin|find, plugin|remove, plugin|search, prepare, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, usage-reporting
Reading help for command 'livesync'. FileName is 'livesync.md'.
# livesync
┌─────────┬───────────────────────────┐
│ Usage   │ Synopsis                  │
│ General │ $ tns livesync <Platform> │
└─────────┴───────────────────────────┘

Synchronizes the latest changes in your project to devices.

### Attributes
<Platform> is the target mobile platform to which you want to synchronize your changes. You can set the following target platforms.


    * android - Synchronizes the latest changes in your project to connected Android devices.
    * ios - Synchronizes the latest changes in your project to connected iOS devices.

Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track exception with message '[object Object] is not a future'.
```

My environment:

node v4.4.5
npm v2.15.4

**Comment by bisonte-az** [comment]
Sample groceries master presents the same problem

**Comment by bathejasumeet** [comment]
even the sample app created while running tns create app_name produces the same problem for iOS during livesync

**Comment by jlooper** [comment]
I normally simply use tns livesync iOS --watch, does that produce the same problem?

**Comment by stnguyen** [comment]
@jlooper yep same problem

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#1862
