### ISSUE TITLE
Karma Bug

### ISSUE THREAD

**Issue by nikhiljha** [NativeScript/NativeScript#2361]
### Which platform(s) does your issue occur on?
Android Physical Device

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1

### Please tell us how to recreate the issue in as much detail as possible.
tns create whatever
tns platform add ios
tns platform add android
tns test android

Console Output
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/Oalecj/Dev/NEMStat/node_modules/karma/lib/server'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at process.<anonymous> (/Users/Oalecj/.nvm/versions/node/v4.4.6/lib/node_modules/nativescript/lib/services/karma-execution.js:5:103)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

I tried doing npm install karma --save but then it complains about not being configured correctly?

**Comment by tsonevn** [comment]
Hi @nikhiljha 
Thank you for reporting your problem.

I reviewed the given exception and found that you should run `tns test init` before `tns test android`, which will to config your project for unit testing. The steps are:
```
tns create whatever
tns platform add android
tns test init
tns test android
``` 

In addition you could make those configurations after you make `npm install karma --save` following the steps [here](https://www.npmjs.com/package/karma#using-it)

I hope this helps

**Comment by nikhiljha** [comment]
That worked, but it wasn't documented anywhere. Thanks!
