### ISSUE TITLE
Make 'tns doctor' report incompatible Java versions

### ISSUE THREAD

**Issue by ginev** [NativeScript/NativeScript#2379]
If an incompatible Java version is present on the machine the Gradle build fails with the following error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ig/GetInterfaceNames : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

This issue is fixed by updating JDK but this is not clear from the messages that pop up in the CLI. We can uprgade 'tns doctor' to check for incompatible Java versions and warn the user to update their JDK to avoid confusing Gradle errors.

**Comment by ginev** [comment]
This issue was moved to NativeScript/nativescript-cli#1887
