### ISSUE TITLE
After Updating to 2.1.0 .... everything got broken... 

### ISSUE THREAD

**Issue by Milewski** [NativeScript/NativeScript#2399]
# On android

mysteriously i started to get this error when playing videos:

```
com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.ClassNotFoundException: com.tns.gen.android.media.MediaPlayer$OnPreparedListener
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:317)
java.lang.Class.forName(Class.java:275)
com.tns.Runtime.getClassForName(Runtime.java:772)
com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
com.tns.Runtime.resolveClass(Runtime.java:310)
com.tns.Runtime.callJSMethodNative(Native Method)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
com.tns.Runtime.callJSMethod(Runtime.java:712)
com.tns.Runtime.callJSMethod(Runtime.java:693)
com.tns.Runtime.callJSMethod(Runtime.java:683)
com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
android.app.Fragment.performCreateView(Fragment.java:2069)
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:906)
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1079)
android.app.BackStackRecord.run(BackStackRecord.java:852)
android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1485)
android.app.FragmentManagerImpl$1.run(FragmentManager.java:457)
android.os.Handler.handleCallback(Handler.java:815)
android.os.Handler.dispatchMessage(Handler.java:104)
android.os.Looper.loop(Looper.java:194)
android.app.ActivityThread.main(ActivityThread.java:5803)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.gen.android.media.MediaPlayer$OnPreparedListener" on path: DexPathList[[zip file "/data/app/com.demo.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.app-1/lib/arm, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass(ClassLoader.java:511)
java.lang.ClassLoader.loadClass(ClassLoader.java:469)
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:317)
java.lang.Class.forName(Class.java:275)
com.tns.Runtime.getClassForName(Runtime.java:772)
com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
com.tns.Runtime.resolveClass(Runtime.java:310)
com.tns.Runtime.callJSMethodNative(Native Method)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
com.tns.Runtime.callJSMethod(Runtime.java:712)
com.tns.Runtime.callJSMethod(Runtime.java:693)
com.tns.Runtime.callJSMethod(Runtime.java:683)
com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
android.app.Fragment.performCreateView(Fragment.java:2069)
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:906)
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1079)
android.app.BackStackRecord.run(BackStackRecord.java:852)
android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1485)
android.app.FragmentManagerImpl$1.run(FragmentManager.java:457)
android.os.Handler.handleCallback(Handler.java:815)
android.os.Handler.dispatchMessage(Handler.java:104)
android.os.Looper.loop(Looper.java:194)
android.app.ActivityThread.main(ActivityThread.java:5803)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
File: "/data/data/com.demo.app/files/app/Views/video/video.js, line: 29, column: 193

StackTrace: 
Frame: function:'', file:'/data/data/com.demo.app/files/app/Views/video/video.js', line: 29, column: 194
Frame: function:'setOrientation', file:'/data/data/com.demo.app/files/app/tns_modules/nativescript-screen-orientation/screen-orientation.js', line: 20, column: 17
Frame: function:'navigatedTo', file:'/data/data/com.demo.app/files/app/Views/video/video.js', line: 28, column: 23
Frame: function:'Observable.notify', file:'/data/data/com.demo.app/files/app/tns_modules/data/observable/observable.js', line: 155, column: 23
Frame: function:'Page.onNavigatedTo', file:'/data/data/com.demo.app/files/app/tns_modules/ui/page/page-common.js', line: 176, column: 14
Frame: function:'_completePageAddition', file:'/data/data/com.demo.app/files/app/tns_modules/ui/transition/transition.js', line: 311, column: 10
Frame: function:'_onFragmentShown', file:'/data/data/com.demo.app/files/app/tns_modules/ui/transition/transition.js', line: 269, column: 9
Frame: function:'onFragmentShown', file:'/data/data/com.demo.app/files/app/tns_modules/ui/frame/frame.js', line: 45, column: 22
Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/com.demo.app/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
Frame: function:'FragmentClass.onCreateView', file:'/data/data/com.demo.app/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38


at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
at com.tns.Runtime.callJSMethod(Runtime.java:712)
at com.tns.Runtime.callJSMethod(Runtime.java:693)
at com.tns.Runtime.callJSMethod(Runtime.java:683)
at com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
at android.app.Fragment.performCreateView(Fragment.java:2069)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:906)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1079)
at android.app.BackStackRecord.run(BackStackRecord.java:852)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1485)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:457)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5803)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
Caused by: java.lang.ClassNotFoundException: com.tns.gen.android.media.MediaPlayer$OnPreparedListener
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:317)
at java.lang.Class.forName(Class.java:275)
at com.tns.Runtime.getClassForName(Runtime.java:772)
at com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
at com.tns.Runtime.resolveClass(Runtime.java:310)
... 21 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.gen.android.media.MediaPlayer$OnPreparedListener" on path: DexPathList[[zip file "/data/app/com.demo.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.app-1/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 27 more
Suppressed: java.lang.ClassNotFoundException: com.tns.gen.android.media.MediaPlayer$OnPreparedListener
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 28 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

on calling this simple script

```

let uri = android.net.Uri.parse('.....url to a video.mp4'),
    controller = new android.widget.MediaController(videoView.getContext()),
    listener = android.media.MediaPlayer.OnPreparedListener.extend({
    onPrepared(player){
        player.start();
     }
});

videoView.setMediaController(controller);
videoView.setVideoURI(uri);
videoView.setZOrderOnTop(true);
videoView.requestFocus();
videoView.setOnPreparedListener(new listener());


.......

export function createView(args:CreateViewEventData) {
    videoView = new android.widget.VideoView(args.context);
}

```

# on iOS....

Some Layout are broken...

```
<StackLayout row="2" class="progress-container">

    <Label text="{{ MAIN_PAGE_TITLE }}" class="mini-label"/>
    <Label text="{{ MY_COLLECTION }}" class="large-label"/>
    <Progress id="progress"/>
    <Label text="{{ progress_text }}" class="progress-text"/>

</StackLayout>
```
### before updating
![before](https://cloud.githubusercontent.com/assets/2874967/16516020/06bb3f2a-3fa8-11e6-8b63-d1f2d19658bd.png)

### after
![after](https://cloud.githubusercontent.com/assets/2874967/16515889/43a29128-3fa7-11e6-9694-4af42135c96c.png)

**Comment by hshristov** [comment]
Hi @Milewski,
Could you send us sample project so that we can check what is wrong?

**Comment by Milewski** [comment]
@hshristov 

Here you are the error on playing video on android:

[https://github.com/Milewski/AndroidVideoError](https://github.com/Milewski/AndroidVideoError)

for this all i did was:

```
tns create demo --template=typescript
```

**Comment by hshristov** [comment]
@Milewski I checked your project. There is one issue - interfaces cannot be extended, they must be instantiated. And you don't need `videoView.setZOrderOnTop(true);` anymore.
Here are the changes:
```
     listener = new android.media.MediaPlayer.OnPreparedListener({
...
    // videoView.setZOrderOnTop(true);
...
    videoView.setOnPreparedListener(listener);

```

**Comment by Milewski** [comment]
thanks it worked, 

so this extended -> to -> instantiated is new in 2.1.0 ?

**Comment by hshristov** [comment]
@Milewski nope it has always been the same. I don't know how it was working before (if it was). @Pip3r4o @slavchev @Plamen5kov @blagoev will know better.

**Comment by Pip3r4o** [comment]
http://docs.nativescript.org/runtimes/android/generator/extend-class-interface has not been updated for quite some time now, but the information inside is still accurate. 

You `extend` **classes** (`A = a.b.C.extend({})` ==> `new A()`), and create instances (`new a.b.c.Interface({})`)  of interface implementations

**Comment by Milewski** [comment]
it was working for me since the version 1.7 of nativescript.... only after this update this issue pop up

**Comment by slavchev** [comment]
@Milewski see my [comment](https://github.com/NativeScript/android-runtime/issues/514#issuecomment-230697433)
