### ISSUE TITLE
Cannot run default project created with tns 2.1.0 (startup error)

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/NativeScript#2407]
This worked in `tns` 2.0.1 but it's broken in 2.1.0

1. `tns create Foo --ng`
2. `tns platform add android`
3. `tns livesync android --watch`

Result (in console):

```
07-02 23:38:20.147  6558  6558 W System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
07-02 23:38:20.147  6558  6558 W System.err: Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
07-02 23:38:20.147  6558  6558 W System.err:    at com.tns.Runtime.createJSInstanceNative(Native Method)
07-02 23:38:20.147  6558  6558 W System.err:    at com.tns.Runtime.createJSInstance(Runtime.java:367)
8:38:32 PM - Compilation complete. Watching for file changes.
```

Result (on device): 

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
	at com.tns.Runtime.createJSInstanceNative(Native Method)
	at com.tns.Runtime.createJSInstance(Runtime.java:367)
```

- `CLI`: 2.1.0
- `core modules`: 2.1.0
- `tns-android`: 2.1.1
- OS: Win 10 x64
- Emulator: Genymotion

**Comment by tsonevn** [comment]
Hi @victorhurdugaci,

I have followed the above-given steps, however  I was unable to reproduce this problem. It would help if you give us more info for the given problem or if you provide sample application, which can be debugged.


Regards,
@tsonevn

**Comment by nsndeck** [comment]
@victorhurdugaci You could try to clean npm cache (`npm cache clean`) then remove `node_modules` and `platforms` directories from your project and run `tns run android` (with started Genymotion). If this does not help we will need some more info which @tsonevn asked for.

**Comment by victorhurdugaci** [comment]
Cleaning the cache and removing the node modules solved the problem.
