### ISSUE TITLE
Could not find an emulator image to run your project

### ISSUE THREAD

**Issue by alvintkb** [NativeScript/NativeScript#2434]
Hey there,

i'm getting this error when i try to run with emulator tns run android --emulator, below is my log trace, hope someone can help me solved this problem.
--------------------

```
alvintkb@ubuntu:~/lookma$ tns run android --emulator --log trace


execFile: /home/alvintkb/lookma/android-sdk-linux/platform-tools/adb "help"
execFile: /home/alvintkb/lookma/android-sdk-linux/platform-tools/adb "help"
spawn: /home/alvintkb/lookma/android-sdk-linux/platform-tools/adb "--help"
Socket {
  connecting: false,
  _hadError: false,
  _handle: 
   Pipe {
     bytesRead: 0,
     _externalStream: {},
     fd: 14,
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread],
     reading: true },
  _parent: null,
  _host: null,
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: 
   { end: { [Function: g] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     close: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: false,
  allowHalfOpen: false,
  destroyed: false,
  _bytesDispatched: 0,
  _sockname: null,
  _writev: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null }
Exec uname -a 
 stdout: Linux ubuntu 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 
 stderr: 
Exec npm -v 
 stdout: 3.10.3
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout: v3.0.3
 
 stderr: 
Exec '/home/alvintkb/lookma/android-sdk-linux/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.36
Revision fd9e4d07b0f5-android
 
 stderr: 
spawn: /home/alvintkb/lookma/android-sdk-linux/tools/android "-h"
Result when throw error is false:
{ stdout: '\n       Usage:\n       android [global options] action [action options]\n       Global options:\n  -s --silent     : Silent mode, shows errors only.\n  -v --verbose    : Verbose mode, shows errors, warnings and all messages.\n     --clear-cache: Clear the SDK Manager repository manifest cache.\n  -h --help       : Help on a specific command.\n\n                                                                    Valid\n                                                                    actions\n                                                                    are\n                                                                    composed\n                                                                    of a verb\n                                                                    and an\n                                                                    optional\n                                                                    direct\n                                                                    object:\n-    sdk              : Displays the SDK Manager window.\n-    avd              : Displays the AVD Manager window.\n-   list              : Lists existing targets or virtual devices.\n-   list avd          : Lists existing Android Virtual Devices.\n-   list target       : Lists existing targets.\n-   list device       : Lists existing devices.\n-   list sdk          : Lists remote SDK repository.\n- create avd          : Creates a new Android Virtual Device.\n-   move avd          : Moves or renames an Android Virtual Device.\n- delete avd          : Deletes an Android Virtual Device.\n- update avd          : Updates an Android Virtual Device to match the folders\n                        of a new SDK.\n- create project      : Creates a new Android project.\n- update project      : Updates an Android project (must already have an\n                        AndroidManifest.xml).\n- create test-project : Creates a new Android project for a test package.\n- update test-project : Updates the Android project for a test package (must\n                        already have an AndroidManifest.xml).\n- create lib-project  : Creates a new Android library project.\n- update lib-project  : Updates an Android library project (must already have\n                        an AndroidManifest.xml).\n- create uitest-project: Creates a new UI test project.\n- update adb          : Updates adb to support the USB devices declared in the\n                        SDK add-ons.\n- update sdk          : Updates the SDK by suggesting new platforms to install\n                        if available.\n',
  stderr: '',
  exitCode: 1 }
Exec mono --version 
 stdout:  
 stderr: /bin/sh: 1: mono: not found

Exec git --version 
 stdout: git version 2.7.4
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: /bin/sh: 1: gradle: not found

Exec "/usr/lib/jvm/java-8-oracle/bin/javac" -version 
 stdout:  
 stderr: javac 1.8.0_91

System information:
{ procInfo: 'nativescript/2.1.1',
  platform: 'linux',
  os: 'Linux ubuntu 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v6.3.0',
  npmVer: '3.10.3',
  javaVer: '1.8.0',
  nodeGypVer: 'v3.0.3\n',
  xcodeVer: null,
  xcodeprojGemLocation: null,
  itunesInstalled: false,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.36',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.7.4',
  gradleVer: null,
  javacVersion: '1.8.0_91' }
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'run'.
Looking for project in '/home/alvintkb/lookma'
Project directory is '/home/alvintkb/lookma'.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'run|android'.
startLookingForDevices; platform is Android
spawn: /home/alvintkb/lookma/android-sdk-linux/platform-tools/adb "start-server"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: /home/alvintkb/lookma/android-sdk-linux/platform-tools/adb "devices"
Could not find an emulator image to run your project.
Error: Could not find an emulator image to run your project.
    at Object.<anonymous> (/home/alvintkb/.nvm/versions/node/v6.3.0/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/alvintkb/.nvm/versions/node/v6.3.0/lib/node_modules/nativescript/lib/nativescript-cli.js:9:16)
    at Module._compile (module.js:541:32)
```

**Comment by tsonevn** [comment]
Hi @alvintkb,
Thank you for reporting your problem.

Could you try to start your AVD Manager and see if there is image which targets at least API level 17.
You could also try to start your emulator manually and try again to run `tns run android --emulator`. Another option is to run your project with `tns run android --device <image_name>`, where `<image_name>` is the name of one of your images listed when you start AVD Manager. I found that similar problem has been discussed in [this ](https://github.com/NativeScript/nativescript-cli/issues/363) issue.

I hope this helps

**Comment by devna13** [comment]
also running **tns device** and you should see all the devices/emulators available.

**Comment by alvintkb** [comment]
Thanks, that solved my problem.

Date: Mon, 11 Jul 2016 08:58:01 -0700

**Comment by alvintkb** [comment]
thanks , manage to solved the problem.

Date: Mon, 11 Jul 2016 05:46:05 -0700

**Comment by alvintkb** [comment]
dear sir, I encounter below problem, please advise how to solved this issues.
fatboy@ubuntu:~$ tns create hello^[Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443# create

Date: Mon, 11 Jul 2016 05:46:05 -0700
