### ISSUE TITLE
Fibers installation problems caused failed.

### ISSUE THREAD

**Issue by hantsy** [NativeScript/NativeScript#2677]
Windows 10(v1607) 64 bit, Node JS 6.5 

I have installed VS 2015 community and install build tools for C++.

When I tried to install Nativescript via command `npm i -g nativescript` and got the following errors.

```
> fibers@1.0.13 install E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
> node build.js || nodejs build.js


E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
..\src\fibers.cc(727): warning C4244: 'argument': conversion from 'std::size_t'
 to 'double', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_m
odules\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(731): warning C4244: '=': conversion from 'double' to 'std::si
ze_t', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_modules\
nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(738): warning C4244: 'argument': conversion from 'std::size_t'
 to 'double', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_m
odules\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(137): warning C4552: '!': operator has no effect; expected
operator with side-effect [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nat
ivescript\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(214): warning C4267: 'argument': conversion from 'size_t' t
o 'unsigned int', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\no
de_modules\nativescript\node_modules\fibers\build\fibers.vcxproj]
  coro.c
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type
 modifiers [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_
modules\fibers\build\fibers.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
E:\Users\hantsy\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1
```

I have tried to uninstall the previous nativescript and node-gyp etc via `npm uninstall -g xxxx` before installing it or run as Administrator, but no help to overcome this error.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#2036
