### ISSUE TITLE
[ERROR] Processing node_modules failed. TypeError: Invalid Version: 2.3

### ISSUE THREAD

**Issue by roblav96** [NativeScript/NativeScript#2726]
I was trying to avoid upgrading to `2.3.0` all together but then it wouldn't build saying:
```
Processing node_modules failed. TypeError: Invalid Version: 2.3
```

So I updated everything to `2.3.0` and still I get this error.

## `tns prepare android --log trace`
```shell
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-intl for android.
[TypeError: Invalid Version: 2.3]
TypeError: Invalid Version: 2.3
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:246:118
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/helpers.js:224:36
    at PlatformService.descriptor.value [as preparePlatformCore] (/usr/local/lib/node_modules/nativescript/lib/common/helpers.js:191:24)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:193:26
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/commands/prepare.js:12:66
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:51:55
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:128:33
    - - - - -
    at new SemVer (/usr/local/lib/node_modules/nativescript/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/nativescript/node_modules/semver/semver.js:569:10)
    at Function.gt (/usr/local/lib/node_modules/nativescript/node_modules/semver/semver.js:598:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/plugins-service.js:306:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/plugins-service.js:126:75
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/tools/broccoli/node-modules-dest-copy.js:68:69
    at /usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:2654:24)
    at /usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:4380:18
    at Function.forEach (/usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:8634:14)
    at DestCopy.rebuildChangedDirectories (/usr/local/lib/node_modules/nativescript/lib/tools/broccoli/node-modules-dest-copy.js:64:11)
    at /usr/local/lib/node_modules/nativescript/lib/tools/broccoli/builder.js:133:22
Processing node_modules failed. TypeError: Invalid Version: 2.3
Error: Processing node_modules failed. TypeError: Invalid Version: 2.3
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:10:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track exception with message 'Processing node_modules failed. TypeError: Invalid Version: 2.3'.
Waiting for analytics to send information. Will check in a 1000ms.
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000

roblav96@Roberts-iMac:/Volumes/OSX HD/Projects/sandbox/client$
```

## package.json
```json
{
	"nativescript": {
		"id": "com.roblav96.sandbox",
		"tns-android": {
			"version": "2.3.0"
		},
		"tns-ios": {
			"version": "2.3.0"
		}
	},
	"name": "sandbox",
	"author": "Rob Laverty <rob@roblav96.com>",
	"description": "sandbox",
	"license": "MINE",
	"repository": {
		"type": "git",
		"url": "git://github.com/roblav96/sandbox.git"
	},
	"bugs": {
		"url": "https://github.com/roblav96/sandbox/issues"
	},
	"homepage": "https://github.com/roblav96/sandbox",
	"dependencies": {
		"@angular/common": "2.0.0",
		"@angular/compiler": "2.0.0",
		"@angular/core": "2.0.0",
		"@angular/forms": "2.0.0",
		"@angular/http": "2.0.0",
		"@angular/platform-browser": "2.0.0",
		"@angular/platform-browser-dynamic": "2.0.0",
		"@angular/platform-server": "2.0.0",
		"@angular/router": "3.0.0",
		"ansicolors": "latest",
		"ansistyles": "latest",
		"eventemitter3": "latest",
		"lodash": "latest",
		"lokijs": "latest",
		"moment": "latest",
		"nativescript-afnetworking": "latest",
		"nativescript-angular": "latest",
		"nativescript-checkbox": "latest",
		"nativescript-contacts": "latest",
		"nativescript-fcuuid": "latest",
		"nativescript-floatingactionbutton": "latest",
		"nativescript-loading-indicator": "latest",
		"nativescript-onesignal": "latest",
		"nativescript-snackbar": "latest",
		"nativescript-socketio": "latest",
		"nativescript-tesseract-ios": "latest",
		"reflect-metadata": "latest",
		"rxjs": "latest",
		"tns-core-modules": "latest",
		"zone.js": "latest"
	},
	"devDependencies": {
		"babel-traverse": "6.15.0",
		"babel-types": "6.15.0",
		"babylon": "6.9.1",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.3.2",
		"typescript": "^1.8.10"
	}
}
```

## `npm list`
```shell
├── @angular/common@2.0.0
├── @angular/compiler@2.0.0
├── @angular/core@2.0.0
├── @angular/forms@2.0.0
├── @angular/http@2.0.0
├── @angular/platform-browser@2.0.0
├── @angular/platform-browser-dynamic@2.0.0
├── @angular/platform-server@2.0.0
├── @angular/router@3.0.0
├── ansicolors@0.3.2
├── ansistyles@0.1.3
├── babel-traverse@6.15.0
├── babel-types@6.15.0
├── babylon@6.9.1
├── eventemitter3@2.0.0
├── lazy@1.0.11
├── lodash@4.15.0
├── lokijs@1.4.1
├── moment@2.15.0
├── nativescript-afnetworking@1.0.3
├── nativescript-angular@1.0.0
├── nativescript-checkbox@1.1.5
├── nativescript-contacts@1.5.0
├── nativescript-dev-typescript@0.3.2
├── nativescript-fcuuid@1.0.2
├── nativescript-floatingactionbutton@2.2.4
├── nativescript-loading-indicator@2.1.0
├── nativescript-onesignal@1.0.4
├── nativescript-snackbar@1.1.3
├── nativescript-socketio@2.2.1
├── nativescript-tesseract-ios@1.0.8
├── reflect-metadata@0.1.8
├── rxjs@5.0.0-beta.12
├── tns-core-modules@2.3.0
├── typescript@1.8.10
└── zone.js@0.6.23
```

**Comment by roblav96** [comment]
`npm remove nativescript -g` then `npm install nativescript -g` resolved the issue.
