### ISSUE TITLE
Android crashes using tns-core-modules@next

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2772]
After updating tns-core-modules to workaround issue https://github.com/NativeScript/NativeScript/issues/2733 Android now crashes with the following log:

```
java.lang.RuntimeException: Unable to resume activity {com.transistorsoft.backgroundgeolocation.nativescript/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.Exception: Failed resolving method refresh on class org.nativescript.widgets.BorderDrawable
    com.tns.Runtime.resolveMethodOverload(Runtime.java:816)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
    com.tns.Runtime.callJSMethod(Runtime.java:716)
    com.tns.Runtime.callJSMethod(Runtime.java:697)
    com.tns.Runtime.callJSMethod(Runtime.java:687)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2112)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
    android.app.BackStackRecord.run(BackStackRecord.java:834)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1468)
    android.app.Activity.performResume(Activity.java:6315)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:3398)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2774)
    android.app.ActivityThread.access$900(ActivityThread.java:177)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5910)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
File: "/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/background.js, line: 101, column: 23

StackTrace: 
Frame: function:'refreshBorderDrawable', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/background.js', line: 101, column: 24
Frame: function:'onBackgroundOrBorderPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/background.js', line: 55, column: 17
Frame: function:'ViewStyler.setBackgroundAndBorder', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view.js', line: 408, column: 23
Frame: function:'StylePropertyChangedHandler.applyProperty', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 1263, column: 14
Frame: function:'Style._applyStyleProperty', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 1036, column: 25
Frame: function:'Style._applyProperty', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 999, column: 14
Frame: function:'Style._onPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 980, column: 14
Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 302, column: 18
Frame: function:'DependencyObservable._setValue', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 136, column: 14
Frame: function:'onBackgroundColorPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 1280, column: 15
Frame: function:'DependencyObservable._onPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 211, column: 13
Frame: function:'Style._onPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 978, column: 45
Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 302, column: 18
Frame: function:'DependencyObservable._setValue', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 136, column: 14
Frame: function:'Page.onLoaded', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/page/page-common.js', line: 40, column: 20
Frame: function:'View._addViewCore', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view-common.js', line: 1082, column: 18
Frame: function:'View._addViewCore', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view.js', line: 127, column: 39
Frame: function:'View._addView', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view-common.js', line: 1072, column: 14
Frame: function:'onFragmentShown', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
Frame: function:'FragmentClass.onCreateView', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38

at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3409)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2774)
at android.app.ActivityThread.access$900(ActivityThread.java:177)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5910)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.Exception: Failed resolving method refresh on class org.nativescript.widgets.BorderDrawable
    com.tns.Runtime.resolveMethodOverload(Runtime.java:816)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
    com.tns.Runtime.callJSMethod(Runtime.java:716)
    com.tns.Runtime.callJSMethod(Runtime.java:697)
    com.tns.Runtime.callJSMethod(Runtime.java:687)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2112)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
    android.app.BackStackRecord.run(BackStackRecord.java:834)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1468)
    android.app.Activity.performResume(Activity.java:6315)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:3398)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2774)
    android.app.ActivityThread.access$900(ActivityThread.java:177)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5910)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
File: "/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/background.js, line: 101, column: 23

StackTrace: 
Frame: function:'refreshBorderDrawable', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/background.js', line: 101, column: 24
Frame: function:'onBackgroundOrBorderPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/background.js', line: 55, column: 17
Frame: function:'ViewStyler.setBackgroundAndBorder', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view.js', line: 408, column: 23
Frame: function:'StylePropertyChangedHandler.applyProperty', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 1263, column: 14
Frame: function:'Style._applyStyleProperty', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 1036, column: 25
Frame: function:'Style._applyProperty', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 999, column: 14
Frame: function:'Style._onPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 980, column: 14
Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 302, column: 18
Frame: function:'DependencyObservable._setValue', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 136, column: 14
Frame: function:'onBackgroundColorPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 1280, column: 15
Frame: function:'DependencyObservable._onPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 211, column: 13
Frame: function:'Style._onPropertyChanged', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/styling/style.js', line: 978, column: 45
Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 302, column: 18
Frame: function:'DependencyObservable._setValue', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/dependency-observable.js', line: 136, column: 14
Frame: function:'Page.onLoaded', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/page/page-common.js', line: 40, column: 20
Frame: function:'View._addViewCore', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view-common.js', line: 1082, column: 18
Frame: function:'View._addViewCore', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view.js', line: 127, column: 39
Frame: function:'View._addView', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/core/view-common.js', line: 1072, column: 14
Frame: function:'onFragmentShown', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
Frame: function:'FragmentClass.onCreateView', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
at com.tns.Runtime.callJSMethod(Runtime.java:716)
at com.tns.Runtime.callJSMethod(Runtime.java:697)
at com.tns.Runtime.callJSMethod(Runtime.java:687)
at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
at android.app.Fragment.performCreateView(Fragment.java:2112)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
at android.app.BackStackRecord.run(BackStackRecord.java:834)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1468)
at android.app.Activity.performResume(Activity.java:6315)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3398)
... 11 more
Caused by: java.lang.Exception: Failed resolving method refresh on class org.nativescript.widgets.BorderDrawable
at com.tns.Runtime.resolveMethodOverload(Runtime.java:816)
... 25 more
```

```
┌──────────────────┬───────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version       │ Latest version │ Information │
│ nativescript     │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.4.0-2016-09-20-4169 │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.3.0                 │ 2.3.0          │ Up to date  │
└──────────────────┴───────────────────────┴────────────────┴─────────────┘
```

**Comment by NickIliev** [comment]
Hi @3rror404 

You have most likely mismatched the versions of tns-core-modules and tns-core-modules-widgets.
To resolve this issue you can remove your **_node_modules_**, **_platforms_** and **_hooks_** folders and rebuild your app - at this very moment the tns-core-modules@next will match with the right version of the widgets and the issue should be resolved. 
Please let me know if you need further assistance on that matter.

**Comment by 3rror404** [comment]
Thanks @NickIliev. That worked a treat.

**Comment by NathanWalker** [comment]
Thanks @NickIliev that did solve the issue 👍

**Comment by irinadrozdova** [comment]
Thanks @NickIliev it helped for me.
