### ISSUE TITLE
Error installing nativescript through npm

### ISSUE THREAD

**Issue by LuisduardoLanfredi** [NativeScript/NativeScript#2991]
I'm executing the following command to install nativescript on my mac:
**npm install -g nativescript**

But it always gives me an error:

npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
/Users/Eduardo/.npm-global/bin/tns -> /Users/Eduardo/.npm-global/lib/node_modules/nativescript/bin/nativescript.js
/Users/Eduardo/.npm-global/bin/nativescript -> /Users/Eduardo/.npm-global/lib/node_modules/nativescript/bin/nativescript.js

> fibers@1.0.13 install /Users/Eduardo/.npm-global/lib/node_modules/nativescript/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:49:34: error: no template named 'WeakCallbackData' in namespace 'v8'; did you mean 'WeakCallbackInfo'?
        void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                    ~~~~^~~~~~~~~~~~~~~~
                                        WeakCallbackInfo
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:6874:16: note: 'WeakCallbackInfo' declared here
  friend class WeakCallbackInfo;
               ^
../src/fibers.cc:49:34: error: too many template arguments for class template 'WeakCallbackInfo'
        void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                        ^                   ~~
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:6874:16: note: template is declared here
  friend class WeakCallbackInfo;
               ^
../src/fibers.cc:102:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:2317:21: note: 'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
../src/fibers.cc:106:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:2317:21: note: 'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
../src/fibers.cc:423:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                           ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/fibers.cc:611:14: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
                                TryCatch try_catch;
                                         ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:7015:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
../src/fibers.cc:731:34: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
                        Coroutine::pool_size = value->ToNumber()->Value();
                                                      ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:8406:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/fibers.cc:785:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                            ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:786:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                            ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:787:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                            ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:55:10: error: no matching member function for call to 'SetWeak'
                handle.SetWeak(val, WeakCallbackShim<F>);
                ~~~~~~~^~~~~~~
../src/fibers.cc:341:9: note: in instantiation of function template specialization 'uni::MakeWeak<&Fiber::WeakCallback, v8::Object, void>' requested here
                        uni::MakeWeak<WeakCallback>(isolate, handle, (void*)this);
                             ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:545:18: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  V8_INLINE void SetWeak(P* parameter,
                 ^
/Users/Eduardo/.node-gyp/7.0.0/include/node/v8.h:556:18: note: candidate function not viable: requires 0 arguments, but 2 were provided
  V8_INLINE void SetWeak();
                 ^
8 warnings and 3 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/Eduardo/.npm-global/lib/node_modules/nativescript/node_modules/fibers
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
/Users/Eduardo/.npm-global/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nativescript"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Eduardo/npm-debug.log
npm ERR! code 1

--------

Node version 3.10.8

**Comment by LuisduardoLanfredi** [comment]
I just downgrade the node verson to v6.9.1 and it worged.
