### ISSUE TITLE
java.lang.NumberFormatException when applying clip-path with percentage values

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#3007]
When a component is off-screen and its width and height are zero, we get a java.lang.NumberFormatException when trying to calculate the percentage of the total, since the total is zero:

```
11-02 14:51:14.658 6351-6351/? W/System.err: java.lang.NumberFormatException: Invalid float: "3%"
11-02 14:51:14.658 6351-6351/? W/System.err:     at java.lang.StringToReal.invalidReal(StringToReal.java:63)
11-02 14:51:14.658 6351-6351/? W/System.err:     at java.lang.StringToReal.initialParse(StringToReal.java:164)
11-02 14:51:14.658 6351-6351/? W/System.err:     at java.lang.StringToReal.parseFloat(StringToReal.java:323)
11-02 14:51:14.658 6351-6351/? W/System.err:     at java.lang.Float.parseFloat(Float.java:306)
11-02 14:51:14.658 6351-6351/? W/System.err:     at org.nativescript.widgets.BorderDrawable.cssValueToDevicePixels(BorderDrawable.java:414)
11-02 14:51:14.658 6351-6351/? W/System.err:     at org.nativescript.widgets.BorderDrawable.drawClipPath(BorderDrawable.java:258)
11-02 14:51:14.658 6351-6351/? W/System.err:     at org.nativescript.widgets.BorderDrawable.draw(BorderDrawable.java:123)
```

main-page.xml:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Image width="100" height="100" class="elementStyle"  src="~/files/icon.png"/>
    <Button backgroundColor="blue" class="elementStyle"  text="TAP"  />
    <Label backgroundColor="red" class="elementStyle" text="sample label" textWrap="true"/>
    <TextField backgroundColor="green" class="elementStyle" hint="" text="Sample textfield" />-->
    <TextView  class="elementStyle" text="Sample text view" backgroundColor="yellow" editable="true" />
    <AbsoluteLayout class="container">
    </AbsoluteLayout>
  </StackLayout>
</Page>
```

app.css:
```
.container {
    width: 200;
    height: 200;
    clip-path: polygon(50% 2%, 3% 100%, 100% 100%);
    background-color: black;
}
.elementStyle{
    width: 200;
    height: 200;
   clip-path: polygon(50% 3%, 3% 100%, 100% 100%);
}
```

**Comment by hamorphis** [comment]
Link to tns-core-modules-widgets issue: https://github.com/NativeScript/tns-core-modules-widgets/issues/65
