### ISSUE TITLE
Unable to run android app with custom Application

### ISSUE THREAD

**Issue by syncro** [NativeScript/NativeScript#3018]
When I'm trying to run newly created application with changes made by the following doc:  https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity

It fails with the following error:
```
Successfully synced application org.nativescript.customapp on device emulator-5554.
11-04 13:28:02.383  2053  2474 W System.err: 	at org.chromium.base.BuildInfo.getPackageVersionCode(BuildInfo.java:74)
11-04 13:28:02.383  2053  2474 W System.err: 	at org.chromium.net.X509Util.nativeRecordCertVerifyCapabilitiesHistogram(Native Method)
11-04 13:28:02.383  2053  2474 W System.err: 	at org.chromium.net.X509Util.bns(X509Util.java:224)
11-04 13:28:02.383  2053  2474 W System.err: 	at org.chromium.net.X509Util.atX(X509Util.java:188)
11-04 13:28:02.383  2053  2474 W System.err: 	at org.chromium.net.X509Util.verifyServerCertificates(X509Util.java:453)
11-04 13:28:02.383  2053  2474 W System.err: 	at org.chromium.net.AndroidNetworkLibrary.verifyServerCertificates(AndroidNetworkLibrary.java:155)
11-04 13:28:04.647  2812  2812 W PackageManager: Unknown permission android.permission.RUN_INSTRUMENTATION in package org.chromium.webview_shell
11-04 13:28:04.926  2812  2853 W PackageManager: Unknown permission android.permission.RUN_INSTRUMENTATION in package org.chromium.webview_shell
11-04 13:28:05.629  2937  2937 V WebViewFactory: RelroFileCreator (64bit = false),  32-bit lib: /system/app/webview/webview.apk!/lib/x86/libwebviewchromium.so, 64-bit lib: /system/app/webview/webview.apk!/lib/x86_64/libwebviewchromium.so
11-04 13:28:05.666  2951  2951 V WebViewFactory: RelroFileCreator (64bit = true),  32-bit lib: /system/app/webview/webview.apk!/lib/x86/libwebviewchromium.so, 64-bit lib: /system/app/webview/webview.apk!/lib/x86_64/libwebviewchromium.so
```

Steps to reproduce:
1. create new app with tns create and add android platform
2. add app/application.android.js
```
var application = require("application");

var superProto = android.app.Application.prototype;
// the first parameter of the `extend` call defines the package and the name for the native *.JAVA file generated. 
var Application = android.app.Application.extend("org.myApp.Application", {
    onCreate: function() {
        superProto.onCreate.call(this);

        // initialize the modules with the custom application object
        application.android.init(this);

        // Enter custom initialization code here
    },
    attachBaseContext: function(base) {
        superProto.attachBaseContext.call(this, base);
        // This code enables MultiDex support for the application (if needed)
        // android.support.multidex.MultiDex.install(this);
    }
});
```
3. change app/App_Resources/Android/AndroidManifest.xml to have the following line:
	<application
		android:name="org.myApp.Application"
4. run with

tns livesync android --emulator --watch

**Comment by Pip3r4o** [comment]
This issue was moved to NativeScript/android-runtime#612
