### ISSUE TITLE
The sample Javascript app crashes after starting

### ISSUE THREAD

**Issue by michelkal** [NativeScript/NativeScript#3025]
Following the [tutorial here](http://docs.nativescript.org/tutorial/chapter-1) When I start the App with `tns run android` or `tns run android --emulator` it runs well but when I run `tns livesync android` the App crashes with the below error.

```
tns livesync android
Project successfully prepared (android)
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.sampleGroceries on device emulator-5554.
W/System.err( 2387):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 2387):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
W/System.err( 2387):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
W/System.err( 2387):    at com.tns.Runtime.callJSMethod(Runtime.java:716)
W/System.err( 2387):    at com.tns.Runtime.callJSMethod(Runtime.java:697)
W/System.err( 2387):    at com.tns.Runtime.callJSMethod(Runtime.java:687)
```
I'm running this on windows 10.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2192
