### ISSUE TITLE
View of TabViewItem at index 0 is undefined

### ISSUE THREAD

**Issue by pocesar** [NativeScript/NativeScript#3072]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0-2016-11-09-7088
- Cross-platform modules: next
- Runtime(s): 2.5.0-next-2016-11-10-1379
- Plugin(s): 

```json
    "nativescript-barcodescanner": "^2.1.3",
    "nativescript-geolocation": "0.0.14",
    "nativescript-googlemaps": "0.0.6",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-permissions": "^1.2.1",
    "nativescript-theme-core": "^0.1.4",
    "nativescript-unit-test-runner": "^0.3.3",
```

### Please tell us how to recreate the issue in as much detail as possible.

I'm not being able to use Tabview, doesn't matter how many times I remove `node_modules`, `platforms`, `hooks` folder, reinstall everything. 

I have this:

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="loaded" navigatingTo="navigatingTo"
    xmlns:alfa="views/logradouro-alfabetico"
    xmlns:gps="views/logradouro-gps"
    xmlns:cadastrar="views/logradouro-cadastrar">

    <TabView id="tabs" selectedIndex="{{selectedIndex}}">
        <TabView.items>
            <alfa:alfa/>
            <gps:gps/>
            <cadastrar:cadastrar/>
        </TabView.items>
    </TabView>
</Page>
```

when navigating to this page, crash with this:

```
W/System.err( 2289): Calling js method onCreateView failed
W/System.err( 2289): Error: View of TabViewItem at index 0 is undefined
W/System.err( 2289): File: "/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/tab-view/tab-view.js, line: 217, column: 20
W/System.err( 2289): StackTrace:
W/System.err( 2289):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/tab-view/tab-view.js', line: 217, column: 27
W/System.err( 2289):    Frame: function:'TabView._onItemsPropertyChangedSetNativeValue', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/tab-view/tab-view.js', line: 215, column: 19
W/System.err( 2289):    Frame: function:'itemsProperty.metadata.onSetNativeValue', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/tab-view/tab-view-common.js', line: 77, column: 13
W/System.err( 2289):    Frame: function:'ProxyObject._trySetNativeValue', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/proxy.js', line: 83, column: 27
W/System.err( 2289):    Frame: function:'eachPropertyCallback', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/proxy.js', line: 59, column: 18
W/System.err( 2289):    Frame: function:'DependencyObservable._eachSetProperty', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/dependency-observable.js', line: 241, column: 18
W/System.err( 2289):    Frame: function:'ProxyObject._syncNativeProperties', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/proxy.js', line: 62, column: 14
W/System.err( 2289):    Frame: function:'View._syncNativeProperties', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/view-common.js', line: 1230, column: 48
W/System.err( 2289):    Frame: function:'eachChild', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/view.js', line: 162, column: 23
W/System.err( 2289):    Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
W/System.err( 2289):    Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/page/page-common.js', line: 285, column: 41
W/System.err( 2289):    Frame: function:'View._onAttached', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/view.js', line: 165, column: 18
W/System.err( 2289):    Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/view.js', line: 126, column: 18
W/System.err( 2289):    Frame: function:'View._addView', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/core/view-common.js', line: 1163, column: 14
W/System.err( 2289):    Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
W/System.err( 2289):    Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
W/System.err( 2289):    Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38
W/System.err( 2289):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 2289):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err( 2289):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err( 2289):    at com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err( 2289):    at com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err( 2289):    at com.tns.Runtime.callJSMethod(Runtime.java:871)
W/System.err( 2289):    at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
W/System.err( 2289):    at android.app.Fragment.performCreateView(Fragment.java:1699)
W/System.err( 2289):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
W/System.err( 2289):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
W/System.err( 2289):    at android.app.BackStackRecord.run(BackStackRecord.java:682)
W/System.err( 2289):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
W/System.err( 2289):    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
W/System.err( 2289):    at android.os.Handler.handleCallback(Handler.java:725)
W/System.err( 2289):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 2289):    at android.os.Looper.loop(Looper.java:137)
W/System.err( 2289):    at android.app.ActivityThread.main(ActivityThread.java:5041)
W/System.err( 2289):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2289):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 2289):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
W/System.err( 2289):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
W/System.err( 2289):    at dalvik.system.NativeStart.main(Native Method)
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```ts
export function loaded(args: EventData) {


}

export function navigatingTo(args: NavigatedData) {
    let page = <Page>args.object

    page.bindingContext = tabsVm
    tabView = <TabView>page.getViewById('tabs')

    tabView.on(TabView.selectedIndexChangedEvent, (args: SelectedIndexChangedEventData) => {
        switch (args.newIndex) {
            case 0:
                page.bindingContext = {};
                break;
            case 1:
                page.bindingContext = {};
                break;
            case 2:
                page.bindingContext = {};
                break;
        }
    })
}
```

each tab xml is made of:

```xml
<TabViewItem title="sometitle" loaded="loaded" navigatingTo="navigatingTo">
  <TabViewItem.view>
    <GridLayout>/* ... */</GridLayout>
  </TabViewItem.view>
</TabViewItem>
```

not sure if related, but upon starting the app, the `adb logcat` gives:

```
I/dalvikvm( 2289): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm( 2289): VFY: unable to resolve virtual method 690: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm( 2289): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 2289): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
W/dalvikvm( 2289): VFY: unable to resolve virtual method 712: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm( 2289): VFY: replacing opcode 0x6e at 0x0002
W/dalvikvm( 2289): VFY: unable to resolve static field 107 (INTERSECT) in Landroid/graphics/Path$Op;
D/dalvikvm( 2289): VFY: replacing opcode 0x62 at 0x0000
I/dalvikvm( 2289): Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
W/dalvikvm( 2289): VFY: unable to resolve virtual method 653: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 2289): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 2289): Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
W/dalvikvm( 2289): VFY: unable to resolve virtual method 655: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 2289): VFY: replacing opcode 0x6e at 0x0002
D/d
```

**Comment by NickIliev** [comment]
Hey @pocesar 
Use your custom component inside your TabViewItem
e.g.
```
 <TabView>
   <TabView.items>
     <TabViewItem title="Tab 1">
       <TabViewItem.view>
          <!-- create custom component here -->
       </TabViewItem.view>
     </TabViewItem>
     <TabViewItem title="Tab 2">
       <TabViewItem.view>
          <!-- create custom component here -->
       </TabViewItem.view>
     </TabViewItem>
   </TabView.items>
 </TabView>
```

and respectivly you should also recreate your custom component so they won't contain tabViewItem but only the content components.

**Comment by pocesar** [comment]
didn't work as well (I was using a similar code before):

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="loaded" navigatingTo="navigatingTo"
    xmlns:alfa="views/logradouro-alfabetico"
    xmlns:gps="views/logradouro-gps"
    xmlns:cadastrar="views/logradouro-cadastrar">

    <TabView id="tabs" selectedIndex="{{selectedIndex}}">
        <TabView.items>
            <TabViewItem title="alfa">
              <TabViewItem.view>
                <alfa:alfa/>
              </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="gps">
              <TabViewItem.view>
                <gps:gps/>
              </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="cadastrar">
              <TabViewItem.view>
                <cadastrar:cadastrar/>
              </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
```

![screenshot_1478880079](https://cloud.githubusercontent.com/assets/461084/20221166/69bd18a0-a817-11e6-99ed-eb28473680c1.png)

**Comment by pocesar** [comment]
![screenshot_1478893872](https://cloud.githubusercontent.com/assets/461084/20228207/7aca3c34-a837-11e6-8dea-76c3d7b309f4.png)

**Comment by NickIliev** [comment]
Hey @pocesar 

I have recreated your project [here](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_3072/app) and you can use it as a reference.
In this project, I have tab view with two custom components and the selectedIndexChangedEvent is fired successfully.

**Comment by NickIliev** [comment]
related to [https://github.com/NativeScript/NativeScript/issues/3079](https://github.com/NativeScript/NativeScript/issues/3079)
