### ISSUE TITLE
Using node_module that uses Buffer or Crypto make the app not being able to load

### ISSUE THREAD

**Issue by pocesar** [NativeScript/NativeScript#3078]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: next
- Cross-platform modules: next
- Runtime(s): next

### Please tell us how to recreate the issue in as much detail as possible.

Using [`jsonwebtoken`](https://npmjs.com/package/jsonwebtoken) module makes the app not being able to start

```
W/System.err( 5552): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
W/System.err( 5552): Error calling module function
W/System.err( 5552): TypeError: app.start is not a function
W/System.err( 5552): File: "/data/data/org.nativescript.cadastramento/files/app/app.js, line: 2, column: 4
W/System.err( 5552): StackTrace:
W/System.err( 5552):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/app.js', line: 2, column: 5
W/System.err( 5552):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5552): TypeError: app.start is not a function
W/System.err( 5552): File: "<unknown>, line: 1, column: 265
W/System.err( 5552): StackTrace:
W/System.err( 5552):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/app.js', line: 2, column: 5
W/System.err( 5552):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5552):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
W/System.err( 5552):    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
W/System.err( 5552):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
W/System.err( 5552):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 5552):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 5552):    at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 5552):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5552):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 5552):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 5552):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/System.err( 5552): Caused by: com.tns.NativeScriptException:
W/System.err( 5552): Error calling module function
W/System.err( 5552): TypeError: app.start is not a function
W/System.err( 5552): File: "/data/data/org.nativescript.cadastramento/files/app/app.js, line: 2, column: 4
W/System.err( 5552): StackTrace:
W/System.err( 5552):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/app.js', line: 2, column: 5
W/System.err( 5552):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5552): TypeError: app.start is not a function
W/System.err( 5552): File: "<unknown>, line: 1, column: 265
W/System.err( 5552): StackTrace:
W/System.err( 5552):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/app.js', line: 2, column: 5
W/System.err( 5552):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5552):    at com.tns.Runtime.runModule(Native Method)
W/System.err( 5552):    at com.tns.Runtime.runModule(Runtime.java:514)
W/System.err( 5552):    at com.tns.Runtime.run(Runtime.java:509)
W/System.err( 5552):    at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
W/System.err( 5552):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
W/System.err( 5552):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
W/System.err( 5552):    ... 9 more
I/ActivityManager( 1483): START u0 {flg=0x14008000 cmp=org.nativescript.cadastramento/com.tns.ErrorReportActivity (has extras)} from uid 10055 on display 0
I/WindowManager( 1483): Screenshot max retries 4 of Token{8fef016 ActivityRecord{3569131 u0 org.nativescript.cadastramento/com.tns.NativeScriptActivity t38 f}} appWin=Window{36520f6d u0 Starting org.nativescript.cadastramento} drawState=4
E/ActivityManager( 1483): Invalid thumbnail dimensions: 384x384
I/Process ( 5552): Sending signal. PID: 5552 SIG: 9
W/libprocessgroup( 1483): failed to open /acct/uid_10055/pid_5552/cgroup.procs: No such file or directory
I/ActivityManager( 1483): Process org.nativescript.cadastramento (pid 5552) has died
```

```
W/System.err( 5989): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.cadastramento/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "buffer", relative to: app/tns_modules/
W/System.err( 5989):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
W/System.err( 5989):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
W/System.err( 5989):    at android.app.ActivityThread.access$800(ActivityThread.java:144)
W/System.err( 5989):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
W/System.err( 5989):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 5989):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 5989):    at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 5989):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5989):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 5989):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 5989):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/System.err( 5989): Caused by: com.tns.NativeScriptException: Failed to find module: "buffer", relative to: app/tns_modules/
W/System.err( 5989):    at com.tns.Module.resolvePathHelper(Module.java:159)
W/System.err( 5989):    at com.tns.Module.resolvePath(Module.java:60)
W/System.err( 5989):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 5989):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err( 5989):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err( 5989):    at com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err( 5989):    at com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err( 5989):    at com.tns.Runtime.callJSMethod(Runtime.java:871)
W/System.err( 5989):    at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
W/System.err( 5989):    at android.app.Activity.performCreate(Activity.java:5937)
W/System.err( 5989):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
W/System.err( 5989):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
W/System.err( 5989):    ... 10 more
```
![screenshot_1478951132](https://cloud.githubusercontent.com/assets/461084/20237546/ca0cd4de-a8bc-11e6-9323-cc0387cd94d8.png)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```ts
import { verify } from 'jsonwebtoken'

export function verify(token: string, cb: Function) {
  verify(token, 'secret', cb)
}
```

**Comment by tsonevn** [comment]
Hi @pocesar,
Thank you for your interest in NativeScript.
I reviewed your problem and it seems that `jsonwebtoken` plugin has been not been supported for NativeScript. However I found that you could use [crypto](https://www.npmjs.com/package/crypto) for the purposes of your app. I am attaching sample code. If this doesn't help could you provide some more info about your case. Regarding to that, I also found that there is an open issue for supporting Crypto in NativeScript [#195](https://github.com/NativeScript/NativeScript/issues/195#issuecomment-106844228), where you could also vote.

`main-page.xml`
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="onTap" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
  </StackLayout>
</Page>
```

`main-page.ts`


```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
var CryptoModule = require('crypto/md5');

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  page.bindingContext = new HelloWorldModel();
}

export function onTap(){
    var tmpvar = CryptoModule.hex_md5('abc');
    console.log("crypto test - " + tmpvar);
}
```


Hope this helps

**Comment by pocesar** [comment]
Since i'm having a lot of trouble trying to make node_modules work, I'm offloading most of the tasks that was once going to be locally executed in the device to a virtual queue on the cloud... the support for node_modules is really limited, unless it has only vanilla javascript

**Comment by tsonevn** [comment]
Hi @pocesar,

Not every **npm** plugins have been supported in NativeScript due to some limitations of iOS and Android platforms. On that point you could create [plugin](http://docs.nativescript.org/plugins/plugins), which provides same functionality as [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken). As I suggested above you could also comment and vote in issue #195 for supporting **Crypto** and some other **Node.js APIs**.

Let me know whether this helps
