### ISSUE TITLE
Can't use xmlns namespace with TabView

### ISSUE THREAD

**Issue by pocesar** [NativeScript/NativeScript#3079]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: next
- Cross-platform modules: next
- Runtime(s): next
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.

According to https://www.nativescript.org/blog/guest-post-getting-cozy-with-nativescript's-tabview you should be able to have a subfolder with a xml + js files and create a xmlns so you can decouple the components logic to outside files. On nativescript@next this is simply not possible:

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd">

    <Page.actionBar>
        <ActionBar title="Logradouros">
            <NavigationButton text="Voltar" android.systemIcon="ic_menu_back" tap="back" />
        </ActionBar>
    </Page.actionBar>

    <TabView>
        <TabView.items>
            <TabViewItem title="Alfabético" xmlns:alfa="partial-views/alfa">
              <TabViewItem.view>
                 <alfa:alfa />
              </TabViewItem.view>
            </TabViewItem >
          </TabView.items>
   </TabView>
</Page>
```

`partial-views/alfa/alfa.xml`:

```xml
<StackLayout loaded="loaded">
    <Label text="should be ok" />
</StackLayout>
```

`partial-views/alfa/alfa.ts`:

```js
export function loaded(){
   console.log('loaded')
}
```

Crashes with the following error when navigating to the view

![screenshot_1478971517](https://cloud.githubusercontent.com/assets/461084/20239659/708939b8-a8ec-11e6-937f-de8f38489b99.png)

 ```
W/System.err( 3423): com.tns.NativeScriptException:
W/System.err( 3423): Calling js method onClick failed
W/System.err( 3423): [object Object]
W/System.err( 3423): File: "/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/builder/builder.js, line: 167, column: 20
W/System.err( 3423): StackTrace:
W/System.err( 3423):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/builder/builder.js', line: 167, column: 21
W/System.err( 3423):    Frame: function:'', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/xml/xml.js', line: 148, column: 13
W/System.err( 3423):    Frame: function:'EasySAXParser.parse', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/js-libs/easysax/easysax.js', line: 751, column: 23
W/System.err( 3423):    Frame: function:'XmlParser.parse', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/xml/xml.js', line: 195, column: 22
W/System.err( 3423):    Frame: function:'XmlStringParser.parse', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/builder/builder.js', line: 173, column: 27
W/System.err( 3423):    Frame: function:'parseInternal', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/builder/builder.js', line: 48, column: 11
W/System.err( 3423):    Frame: function:'loadInternal', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/builder/builder.js', line: 125, column: 27
W/System.err( 3423):    Frame: function:'load', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/builder/builder.js', line: 109, column: 27
W/System.err( 3423):    Frame: function:'pageFromBuilder', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/frame/frame-common.js', line: 111, column: 27
W/System.err( 3423):    Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/frame/frame-common.js', line: 89, column: 20
W/System.err( 3423):    Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/frame/frame-common.js', line: 165, column: 20
W/System.err( 3423):    Frame: function:'cadastrar', file:'/data/data/org.nativescript.cadastramento/files/app/views/actions.js', line: 28, column: 21
W/System.err( 3423):    Frame: function:'Observable.notify', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/data/observable/observable.js', line: 149, column: 23
W/System.err( 3423):    Frame: function:'Observable._emit', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/data/observable/observable.js', line: 168, column: 18
W/System.err( 3423):    Frame: function:'onClick', file:'/data/data/org.nativescript.cadastramento/files/app/tns_modules/ui/button/button.js', line: 33, column: 32
W/System.err( 3423):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3423):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err( 3423):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err( 3423):    at com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err( 3423):    at com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err( 3423):    at com.tns.Runtime.callJSMethod(Runtime.java:871)
W/System.err( 3423):    at com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
W/System.err( 3423):    at android.view.View.performClick(View.java:4756)
W/System.err( 3423):    at android.view.View$PerformClick.run(View.java:19749)
W/System.err( 3423):    at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 3423):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 3423):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 3423):    at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 3423):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3423):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3423):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 3423):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

```
W/System.err( 3423):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3423):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err( 3423):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err( 3423):    at com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err( 3423):    at com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err( 3423):    at com.tns.Runtime.callJSMethod(Runtime.java:871)
```

and yes, I lost count how many times I deleted platforms, node_modules and hooks folder and reinstalled them

**Comment by tsonevn** [comment]
Hi @pocesar,
Thank you for your interest in NativeScript.
I review your problem and found that the problem has been related to mistake in the name of xmlns namespace and to be able to fix this you should change the `alfa` to be with first capital letter `Alfa` in your main XML file. 

Example:
```
<TabView>
        <TabView.items>
            <TabViewItem title="Alfabético" xmlns:Alfa="partial-views/alfa">
              <TabViewItem.view>
                 <alfa:alfa />
              </TabViewItem.view>
            </TabViewItem >
          </TabView.items>
   </TabView>
```
Let me know whether this helps or if I could assist you further.

**Comment by pocesar** [comment]
turns out it's caused by node_modules that aren't supported by NativeScript. the error is really opaque, and made me waste a lot of time seeing that `process` and `Buffer ` globals aren't supported and not even shimmed, node native libraries like `crypto`, `https`, `url`, all make the views crash, but it doesn't tell you what is wrong, it just crash

related to #3078 #3080 #3059  https://github.com/NativeScript/android-runtime/issues/623 #

**Comment by tsonevn** [comment]
Hi @pocesar,

I am sorry to hear that you still have problems while using NativeScript. 
In NativeScript the right way to add external plugin is while using `tns plugin add <plugin_name>`, which will provide a warning, if the plugin is not created and supported in the platform. Regarding to the topic of this issue, Did you still expire problems, while using `TabView` with nested components.

Hope this helps.
@tsonevn
