### ISSUE TITLE
Fail to run application on Android

### ISSUE THREAD

**Issue by af-fess** [NativeScript/NativeScript#3092]
I created project `demo` and added package ` "id": "com.appsflyer.nts.demo",`

but I fail to run it. for iOS everything works fine

Flow:

```
tns platform add android
tns platform deploy android
```

The output:

```
...
BUILD SUCCESSFUL

Total time: 49.936 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
Project successfully built
The system failed to delete the package for an unspecified reason.
Successfully deployed on device with identifier '012dafd17dc7c503'.
```

I open application on Nexus5x (Android 7)

The output:

```
.11-14 18:27:55.347 15683 15683 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
11-14 18:27:55.347 15683 15683 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
11-14 18:27:55.347 15683 15683 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
11-14 18:27:55.347 15683 15683 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:716)
11-14 18:27:55.347 15683 15683 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:697)
11-14 18:27:55.347 15683 15683 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:687)

```

On device I get an error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appsflyer.nts.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Failed to load Page from entry.moduleName: main-page
File: "/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame-common.js, line: 92, column: 12

StackTrace: 
Frame: function:'resolvePageFromEntry', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame-common.js', line: 92, column: 19
Frame: function:'Frame.navigate', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame-common.js', line: 165, column: 20
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame.js', line: 690, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/activity.js', line: 12, column: 25

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Failed to load Page from entry.moduleName: main-page
File: "/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame-common.js, line: 92, column: 12

StackTrace: 
Frame: function:'resolvePageFromEntry', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame-common.js', line: 92, column: 19
Frame: function:'Frame.navigate', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame-common.js', line: 165, column: 20
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/frame.js', line: 690, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.appsflyer.nts.demo/files/app/tns_modules/ui/frame/activity.js', line: 12, column: 25

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
at com.tns.Runtime.callJSMethod(Runtime.java:716)
at com.tns.Runtime.callJSMethod(Runtime.java:697)
at com.tns.Runtime.callJSMethod(Runtime.java:687)
at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
at android.app.Activity.performCreate(Activity.java:6664)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
... 9 more
```

```
tns --version
2.3.0
```

my application `package.json`:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.appsflyer.nts.demo",
    "tns-ios": {
      "version": "2.3.0"
    },
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "nativescript-plugin-appsflyer": "file:..",
    "tns-core-modules": "2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.6"
  }
}
```

**The full output from CLI:**

```
Maxims-MacBook-Pro:demo maxim$ tns platform remove android
Platform android successfully removed.
Maxims-MacBook-Pro:demo maxim$ tns platform add android
Copying template files...
Project successfully created.
Maxims-MacBook-Pro:demo maxim$ tns deploy android
Executing before-prepare hook from /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.6

:config phase:  createDefaultIncludeFiles

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:deleteMetadata
:deleteFlavors
:clean

BUILD SUCCESSFUL

Total time: 11.531 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
Successfully prepared plugin nativescript-plugin-appsflyer for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)

:config phase:  createDefaultIncludeFiles
	+found plugins: tns-core-modules-widgets
	 + creating include.gradle file for /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations/tns-core-modules-widgets
Renaming plugin directory to flavor name: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/src/tns-core-modules-widgets -> /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/src/F0

:config phase:  createPluginsConfigFile
	 Creating product flavors include.gradle file in /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2421Library
:prepareComAndroidSupportAppcompatV72421Library
:prepareComAndroidSupportSupportCompat2421Library
:prepareComAndroidSupportSupportCoreUi2421Library
:prepareComAndroidSupportSupportCoreUtils2421Library
:prepareComAndroidSupportSupportFragment2421Library
:prepareComAndroidSupportSupportMediaCompat2421Library
:prepareComAndroidSupportSupportV42421Library
:prepareComAndroidSupportSupportVectorDrawable2421Library
:prepareNtsRuntimeUnspecifiedLibrary
:prepareWidgetsReleaseLibrary
:prepareF0DebugDependencies
:compileF0DebugAidl
:compileF0DebugRenderscript
:generateF0DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser
inputDir: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/src/main/assets/app
outFile: ../bindings.txt
:asbg:generateBindings
:mergeF0DebugShaders
:compileF0DebugShaders
:generateF0DebugAssets
:mergeF0DebugAssets
:generateF0DebugResValues
:generateF0DebugResources
:mergeF0DebugResources
:processF0DebugManifest
:processF0DebugResources
:generateF0DebugSources
:incrementalF0DebugJavaCompilationSafeguard
:compileF0DebugJavaWithJavac
:compileF0DebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/src/main/java/com/tns/RuntimeHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:compileF0DebugNdk UP-TO-DATE
:compileF0DebugSources
:buildMetadata
 'assets/metadata/treeNodeStream.dat' NOT FOUND
 'assets/metadata/treeStringsStream.dat' NOT FOUND
 'assets/metadata/treeValueStream.dat' NOT FOUND
 'assets/metadata/treeNodeStream.dat'...
 'assets/metadata/treeStringsStream.dat'...
 'assets/metadata/treeValueStream.dat'...
:prePackageMarkerForF0Debug
:transformClassesWithDexForF0Debug
Merged dex #1 (205 defs/310.9KiB)
Merged dex #2 (5 defs/15.1KiB)
Merged dex #3 (348 defs/566.3KiB)
Merged dex #4 (434 defs/465.5KiB)
Merged dex #5 (130 defs/242.7KiB)
Merged dex #6 (53 defs/75.9KiB)
Merged dex #7 (56 defs/147.0KiB)
Merged dex #8 (141 defs/172.0KiB)
Merged dex #9 (1 defs/0.7KiB)
Merged dex #10 (15 defs/47.5KiB)
Merged dex #11 (51 defs/123.5KiB)
Merged dex #12 (51 defs/84.9KiB)
Merged dex #13 (249 defs/186.4KiB)
Merged dex #14 (17 defs/28.5KiB)
Merged dex #15 (73 defs/58.2KiB)
Merged dex #16 (8 defs/8.3KiB)
Merged dex #17 (10 defs/15.2KiB)
Merged dex #18 (58 defs/88.1KiB)
Merged dex #19 (46 defs/7.4KiB)
Result is 1951 defs/3189.4KiB. Took 0.4s
:myMergeDex
Result compacted from 4059.8KiB to 2401.3KiB to save 1658.5KiB
Merged dex #1 (1 defs/1.6KiB)
Merged dex #2 (1 defs/1.4KiB)
Merged dex #3 (1 defs/1.9KiB)
Merged dex #4 (1 defs/1.7KiB)
Merged dex #5 (1 defs/1.4KiB)
Merged dex #6 (1 defs/1.6KiB)
Merged dex #7 (1 defs/1.4KiB)
Merged dex #8 (1 defs/1.3KiB)
Merged dex #9 (1 defs/1.5KiB)
Merged dex #10 (1 defs/1.7KiB)
Merged dex #11 (1 defs/1.3KiB)
Merged dex #12 (1 defs/2.7KiB)
Merged dex #13 (1 defs/1.5KiB)
Merged dex #14 (1 defs/1.4KiB)
Merged dex #15 (1 defs/1.6KiB)
Merged dex #16 (1 defs/1.6KiB)
Merged dex #17 (1 defs/1.7KiB)
Merged dex #18 (1 defs/1.3KiB)
Merged dex #19 (1 defs/1.4KiB)
Merged dex #20 (1 defs/1.7KiB)
Merged dex #21 (1 defs/1.8KiB)
Merged dex #22 (1 defs/1.7KiB)
Merged dex #23 (1 defs/1.4KiB)
Merged dex #24 (1 defs/1.3KiB)
Merged dex #25 (1 defs/1.4KiB)
Merged dex #26 (1 defs/1.4KiB)
Merged dex #27 (1 defs/2.0KiB)
Merged dex #28 (1 defs/1.3KiB)
Merged dex #29 (1 defs/2.3KiB)
Merged dex #30 (1 defs/1.5KiB)
Merged dex #31 (1 defs/2.1KiB)
Merged dex #32 (1 defs/1.4KiB)
Merged dex #33 (1 defs/1.5KiB)
Merged dex #34 (1 defs/1.3KiB)
Merged dex #35 (1 defs/1.4KiB)
Merged dex #36 (1 defs/1.3KiB)
Merged dex #37 (1 defs/1.4KiB)
Merged dex #38 (1 defs/1.7KiB)
Merged dex #39 (1 defs/1.6KiB)
Merged dex #40 (1 defs/1.3KiB)
Merged dex #41 (1 defs/1.3KiB)
Merged dex #42 (1 defs/1.5KiB)
Merged dex #43 (1 defs/1.4KiB)
Merged dex #44 (1 defs/2.5KiB)
Merged dex #45 (1 defs/2.6KiB)
Merged dex #46 (1 defs/1.2KiB)
Merged dex #47 (1 defs/1.3KiB)
Merged dex #48 (1951 defs/3189.4KiB)
Result is 1998 defs/2401.3KiB. Took 0.4s
:mergeF0DebugJniLibFolders
:transformNative_libsWithMergeJniLibsForF0Debug
:processF0DebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForF0Debug
:validateDebugSigning
:packageF0Debug
:zipalignF0Debug
:assembleF0Debug
:assembleDebug
:buildapk

BUILD SUCCESSFUL

Total time: 52.429 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
Project successfully built
Successfully deployed on device with identifier '012dafd17dc7c503'.
^CMaxims-MacBook-Pro:demo maxim$ tns run android
Executing before-prepare hook from /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.6
Project successfully prepared (android)

:config phase:  createDefaultIncludeFiles
	+found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
	 Creating product flavors include.gradle file in /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demo/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2421Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72421Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2421Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2421Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2421Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2421Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2421Library UP-TO-DATE
:prepareComAndroidSupportSupportV42421Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2421Library UP-TO-DATE
:prepareNtsRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0DebugDependencies
:compileF0DebugAidl UP-TO-DATE
:compileF0DebugRenderscript UP-TO-DATE
:generateF0DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:mergeF0DebugShaders UP-TO-DATE
:compileF0DebugShaders UP-TO-DATE
:generateF0DebugAssets UP-TO-DATE
:mergeF0DebugAssets
:generateF0DebugResValues UP-TO-DATE
:generateF0DebugResources UP-TO-DATE
:mergeF0DebugResources UP-TO-DATE
:processF0DebugManifest UP-TO-DATE
:processF0DebugResources
:generateF0DebugSources
:incrementalF0DebugJavaCompilationSafeguard UP-TO-DATE
:compileF0DebugJavaWithJavac UP-TO-DATE
:compileF0DebugNdk UP-TO-DATE
:compileF0DebugSources UP-TO-DATE
:buildMetadata UP-TO-DATE
:prePackageMarkerForF0Debug
:transformClassesWithDexForF0Debug
Merged dex #1 (205 defs/310.9KiB)
Merged dex #2 (5 defs/15.1KiB)
Merged dex #3 (348 defs/566.3KiB)
Merged dex #4 (434 defs/465.5KiB)
Merged dex #5 (130 defs/242.7KiB)
Merged dex #6 (53 defs/75.9KiB)
Merged dex #7 (56 defs/147.0KiB)
Merged dex #8 (141 defs/172.0KiB)
Merged dex #9 (1 defs/0.7KiB)
Merged dex #10 (15 defs/47.5KiB)
Merged dex #11 (51 defs/123.5KiB)
Merged dex #12 (51 defs/84.9KiB)
Merged dex #13 (249 defs/186.4KiB)
Merged dex #14 (17 defs/28.5KiB)
Merged dex #15 (73 defs/58.2KiB)
Merged dex #16 (8 defs/8.3KiB)
Merged dex #17 (10 defs/15.2KiB)
Merged dex #18 (58 defs/88.1KiB)
Merged dex #19 (46 defs/7.4KiB)
Result is 1951 defs/3189.4KiB. Took 0.4s
:myMergeDex
Result compacted from 4059.8KiB to 2401.3KiB to save 1658.5KiB
Merged dex #1 (1 defs/1.6KiB)
Merged dex #2 (1 defs/1.4KiB)
Merged dex #3 (1 defs/1.9KiB)
Merged dex #4 (1 defs/1.7KiB)
Merged dex #5 (1 defs/1.4KiB)
Merged dex #6 (1 defs/1.6KiB)
Merged dex #7 (1 defs/1.4KiB)
Merged dex #8 (1 defs/1.3KiB)
Merged dex #9 (1 defs/1.5KiB)
Merged dex #10 (1 defs/1.7KiB)
Merged dex #11 (1 defs/1.3KiB)
Merged dex #12 (1 defs/2.7KiB)
Merged dex #13 (1 defs/1.5KiB)
Merged dex #14 (1 defs/1.4KiB)
Merged dex #15 (1 defs/1.6KiB)
Merged dex #16 (1 defs/1.6KiB)
Merged dex #17 (1 defs/1.7KiB)
Merged dex #18 (1 defs/1.3KiB)
Merged dex #19 (1 defs/1.4KiB)
Merged dex #20 (1 defs/1.7KiB)
Merged dex #21 (1 defs/1.8KiB)
Merged dex #22 (1 defs/1.7KiB)
Merged dex #23 (1 defs/1.4KiB)
Merged dex #24 (1 defs/1.3KiB)
Merged dex #25 (1 defs/1.4KiB)
Merged dex #26 (1 defs/1.4KiB)
Merged dex #27 (1 defs/2.0KiB)
Merged dex #28 (1 defs/1.3KiB)
Merged dex #29 (1 defs/2.3KiB)
Merged dex #30 (1 defs/1.5KiB)
Merged dex #31 (1 defs/2.1KiB)
Merged dex #32 (1 defs/1.4KiB)
Merged dex #33 (1 defs/1.5KiB)
Merged dex #34 (1 defs/1.3KiB)
Merged dex #35 (1 defs/1.4KiB)
Merged dex #36 (1 defs/1.3KiB)
Merged dex #37 (1 defs/1.4KiB)
Merged dex #38 (1 defs/1.7KiB)
Merged dex #39 (1 defs/1.6KiB)
Merged dex #40 (1 defs/1.3KiB)
Merged dex #41 (1 defs/1.3KiB)
Merged dex #42 (1 defs/1.5KiB)
Merged dex #43 (1 defs/1.4KiB)
Merged dex #44 (1 defs/2.5KiB)
Merged dex #45 (1 defs/2.6KiB)
Merged dex #46 (1 defs/1.2KiB)
Merged dex #47 (1 defs/1.3KiB)
Merged dex #48 (1951 defs/3189.4KiB)
Result is 1998 defs/2401.3KiB. Took 0.4s
:mergeF0DebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForF0Debug UP-TO-DATE
:processF0DebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForF0Debug UP-TO-DATE
:validateDebugSigning
:packageF0Debug
:zipalignF0Debug
:assembleF0Debug
:assembleDebug
:buildapk

BUILD SUCCESSFUL

Total time: 31.17 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
Project successfully built
The system failed to delete the package for an unspecified reason.
Successfully deployed on device with identifier '012dafd17dc7c503'.
11-15 09:49:53.309  8280  8280 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
11-15 09:49:53.309  8280  8280 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
11-15 09:49:53.309  8280  8280 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
11-15 09:49:53.309  8280  8280 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:716)
11-15 09:49:53.309  8280  8280 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:697)
11-15 09:49:53.309  8280  8280 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:687)

```

**Comment by NickIliev** [comment]
Hey @af-fess 

To change your package id in 2.3.0 you have to take one additional step for Android apart from updating your package.json. Go to **_app/App_Resources/Android/app.gradle_** and change the **applicationId** there as well with your new id. Now remove platforms folder and rebuild your application and the new build will have the desired id.
```
rm -rf platforms
tns run android
```

The NativeScript team is currently working on better workflow for this case [here](https://github.com/NativeScript/nativescript-cli/issues/2089)

Closing as related to [https://github.com/NativeScript/nativescript-cli/issues/2089](https://github.com/NativeScript/nativescript-cli/issues/2089)

**Comment by af-fess** [comment]
@NickIliev thank you for quick response, unfortunately your solution doesn't work.

I removed all platform with `rm`, created android with `tns run android`, get the same error output.

I even created new project, get the same issue

**Comment by NickIliev** [comment]
@af-fess when saying you created new project and it throws the same error does that means that you are also changing the package ID for your new project or just creating a basic new project!?

In other words, can you create a simple base project and verify that it runs without changing the package name.
```
tns create testApplication
tns run android
```
Now if your new application starts successfully, you can change the id for Android by modifying the following.

- the package id in **package.json**
- the **applicationId** in **_app/App_Resources/Android/app.gradle_**

remove platforms folder and rebuild your application.
The rebuilt app will have the new package id set for Android.

The process for iOS requires only one change in the package.json but the extra step is needed for Android. We are currently working on the better solution (as mentioned in my previous thread).
