### ISSUE TITLE
Out of memory on http.getFile and big files on Android

### ISSUE THREAD

**Issue by PolCPP** [NativeScript/NativeScript#3314]
While testing on a device i found that sometimes i fired an out of memory error + crash while downloading big files (40mb). 

From what i can figure out the issue comes from using httpRequest for it since it stores everything in memory before writing it into the file. 

I'm pretty much doing the following:

```    
        http.getFile(url).then((r) => {            
            // Do stuff with saved file
        }).catch((err) => {
            // Handle error
        });   
```

Also, apparently old request data doesn't seem to be cleared out. As i can trigger this by downloading the file twice if i adjust the memory for it.

This is the exception that fires once it crashes.

```
An uncaught Exception occurred on "AsyncTask #1" thread.
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 87347554 byte allocation with 4194304 free bytes and 50MB until OOM
    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
    at java.io.ByteArrayOutputStream.toString(ByteArrayOutputStream.java:137)
    at org.nativescript.widgets.Async$Http$RequestResult.readResponseStream(Async.java:363)
    at org.nativescript.widgets.Async$Http$HttpRequestTask.doInBackground(Async.java:431)
    at org.nativescript.widgets.Async$Http$HttpRequestTask.doInBackground(Async.java:379)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 3 more
```

**Comment by tsonevn** [comment]
Hi @PolCPP ,
Thank you for your interest of NativeScript.

I reviewed your case, however HTTP Module and its ` getFile(url)` method has been created for download files with small size. Actually if you try to download file with size for example 40mb, the app will crash with the above-given `OutOfMemoryError` exception, because the allocated heap size will be filled. 

Regards,
@tsonevn

**Comment by PolCPP** [comment]
I ended building a workaround via DownloadManager on Android, which i just packed up as a [plugin.](github.com/PolCPP/nativescript-downloadmanager) while it needs more testing...and actual tests, it should work.

In any case i think that docs on GetFile should be updated to reflect this limitation.

Best regards

**Comment by tsonevn** [comment]
Hi @PolCPP, 
Thank you for your cooperation,

Indeed we will include the information in docs and will include note, that `getFile` should be used only for small files. Regarding to the plugin, I tried to review the plugin, however I do not have rights to the repo. I also would like to know, whether the plugin is only for `Android` or it is for both platforms.

Regards,
@tsonevn

**Comment by PolCPP** [comment]
Oh it seems i linked it incorrectly https://github.com/PolCPP/nativescript-downloadmanager

For it only supports android only at least for now since it was my use case for this app, it's using [this](https://developer.android.com/reference/android/app/DownloadManager.html) since it gives a few goodies and allows parallel background downloads easily.

This is how it looks while running.

 ![](https://dl.dropboxusercontent.com/u/3115520/Captura%20de%20pantalla%202016-12-20%20a%20las%2010.33.31.png)

**Comment by tsonevn** [comment]
Greate plugin, 
I test it. Regarding to that you could also publish it in NPM and make it available for the other users.

Regards,
@tsonevn
