### ISSUE TITLE
How to display sdcard image with ng2?

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3336]
Hi,  i want to create a image picker component, and  i got the image path from sdcard like 

> /storage/sdcard0/DCIM/Camera/IMG_20150116_181719.jpg

but now i met a little problem, the image didn't show.

```
<RadListView [items]="imageList" multipleSelection="true" selectionBehavior="Press" (itemSelected)="itemSelected($event)"  (itemDeselected)="itemDeselected($event)">
            <template tkListItemTemplate let-item="item" class="m-t-20">
                <GridLayout class="gridLayoutStyle" rows="*,20" columns="*">
                    <Image width="94" height="94" [src]="item.fileUri"></Image>
                    <Label row="1" [text]="item.text"></Label>
                </GridLayout>
            </template>
            <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" spanCount="3"></ListViewGridLayout>
        </RadListView>
```

I have tried to use the imagesource method to do， But that there is a mistake

```
            let imgFile = new java.io.File(img.uri);
            console.log('onTap =>',imgFile);
            if(imgFile){
                img.imageSource = imagesource.fromFile(imgFile);
            }
            templateList.push(img);
```

and image was used 

```
<Image width="94" height="94" [src]="item.imageSource"></Image>
```

it's appear the error 

> **calling js method onBindViewHolder failed.**

so  how should i change the code to display image ?

best wishes ~

**Comment by tsonevn** [comment]
Hi @Leo-lay,
I reviewed your case and for your scenario you could set the image path,  instead of creating new `File` and transform it to `ImageSource`. I am attaching a sample code, where I get an image path from device `Download` folder and push it to the `imageList` array.

app.component.html

```
<GridLayout rows="100 *">
    <Button row="0" text="ReadFile" (tap)="onTap()"></Button>
    <RadListView row="1" [items]="imageList" multipleSelection="true" selectionBehavior="Press">
            <template tkListItemTemplate let-item="item" class="m-t-20">
                <GridLayout class="gridLayoutStyle" rows="*,20" columns="*">
                    <Image width="94" height="94" [src]="item.fileUri"></Image>
                    <Label row="1" [text]="item.text"></Label>
                </GridLayout>
            </template>
            <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" spanCount="3"></ListViewGridLayout>
        </RadListView>
</GridLayout>
```

app.component.ts
```
import { Component } from "@angular/core";
import {knownFolders, path, Folder} from "file-system"
declare var android :any;
@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public imageList:Array<any>=[];

   constructor(){}

   onTap(){
       var downloads = android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS).toString();
       let imagepath = path.join(downloads, "test.jpeg");
       console.log(downloads);
       this.imageList.push({fileUri:imagepath, text:"image test"})
   }
}
```

Let me know whether this helps, or if I could assist you further.

**Comment by Leo-lay** [comment]
@tsonevn thank you for your reply, I was through the  android cursor to get all the pictures on the phone, and use your way to deal data ,but some of the pictures can not be displayed, I feel strange Why is this?

follow the method do scan the phone storage

```
 getGalleryPhotos() {
        let MediaStore = android.provider.MediaStore;
        console.log('getGalleryPhotos')
        let photoList: Array<any> = [];
        let cursor = null;
        // query columns
        try {
            // let columns = [android.provider.MediaStore.Images.Media.DATA,
            // android.provider.MediaStore.Images.Media._ID];
            let columns = [MediaStore.MediaColumns.DATA];
            // sort by _id
            let order_by = MediaStore.Images.Media._ID;
            let uri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
            // get android cursor
            cursor = this.getContentResolver().query(uri, columns, null, null, null);
            if (cursor && cursor.getCount() > 0) {
                while (cursor.moveToNext()) {
                    // let imagePicker = new ImagePicker();
                    let column_index = cursor.getColumnIndex(MediaStore.MediaColumns.DATA);
                    let imageUri = cursor.getString(column_index) + '';
                    let name = imageUri.substring(imageUri.lastIndexOf('.'));
                    let image  = {fileUri:imageUri, text:name};
                    photoList.push(image);
                }
            }
            return photoList;
        } catch (error) {
            console.log('getGalleryPhotos=>', JSON.stringify(error));
            return undefined;
        }
    }
```

and then i get the all image path ,but now some images were showing correct, other not.

I was thinking is not because of the size of the picture? then i scale the image ,I detected that this code
```
application.android.nativeApp.getContentResolver().openInputStream(uri);
```
 is causing another error


error=> 
```W/System.err(  916): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err(  916): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err(  916): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err(  916): 	at com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err(  916): 	at com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err(  916): 	at com.tns.Runtime.callJSMethod(Runtime.java:871)
```

thanks a lot ~

**Comment by tsonevn** [comment]
Hi @Leo-lay,
Thank you for writing us back.
I reviewed your project and the given code snippet, however was unable to reproduce this behavior. In my test project all images has been shown as expected. For your convenience I am attaching my sample code. 

app.component.html
```
<GridLayout rows="100 *">
    <Button row="0" text="ReadFile" (tap)="onTap()"></Button>
    <RadListView id="listID" row="1" [items]="imageList" multipleSelection="true" selectionBehavior="Press">
            <template tkListItemTemplate let-item="item" class="m-t-20">
                <GridLayout class="gridLayoutStyle" rows="*,20" columns="*">
                    <Image width="94" height="94" [src]="item.fileUri"></Image>
                    <Label row="1" [text]="item.text"></Label>
                </GridLayout>
            </template>
            <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" spanCount="3"></ListViewGridLayout>
        </RadListView>
</GridLayout>
```
app.component.ts
```
import { Component } from "@angular/core";
import {knownFolders, path, Folder} from "file-system";
import {RadListView} from "nativescript-telerik-ui/listview";
import { Page } from "ui/page";
var app = require("application");
declare var android :any;
@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public imageList:Array<any>=[];

   constructor(private page: Page){
       
   }

   onTap(){
   
   }
   ngAfterViewInit(){
       this.getGalleryPhotos();
   }


    getGalleryPhotos() {
        let MediaStore = android.provider.MediaStore;
        console.log('getGalleryPhotos')
        let photoList: Array<any> = [];
        let cursor = null;
        try {
            var context = app.android.context;
            let columns = [MediaStore.MediaColumns.DATA];
            let order_by = MediaStore.Images.Media._ID;
            let uri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;

            cursor = context.getContentResolver().query(uri, columns, null, null, null);
            
            if (cursor && cursor.getCount() > 0) {
                while (cursor.moveToNext()) {
                    let column_index = cursor.getColumnIndex(MediaStore.MediaColumns.DATA);
                    let imageUri = cursor.getString(column_index) + '';
                    let name = imageUri.substring(imageUri.lastIndexOf('.'));
                    // console.log(imageUri)
                    let image  = {fileUri:imageUri, text:name};
                    this.imageList.push(image);
                }
            }
            console.log("items counter");
           
            console.log(cursor.getCount());
            var  that = this;
            setTimeout(function(){
                 var listview:RadListView = <RadListView> that.page.getViewById("listID");
                console.log(listview.items.length);
            }, 2000)
        } catch (error) {
            console.log(error);
            console.log('getGalleryPhotos=>', JSON.stringify(error));
        }
    }

}
```

This problem could be related with the image format or with some broken images. 
It would help, if you could provide sample project, which could be debugged locally and info about the device, which you are using for testing.

**Comment by Leo-lay** [comment]
Hi @tsonevn  i push a demo on[ github ](https://github.com/Leo-lay/gpm-imagepicker) ,you can download debugging it, I tested the three devices (Samsung, nubia z5s, huawei) are the same problem, some pictures show not.
I am not sure where is the problem still not able to find out the reasons, all the pictures in the system album is displayed normal, the other app is also displayed normal. 
thanks ~

**Comment by tsonevn** [comment]
Hi @Leo-lay,

Thank you for the demo app.

I reviewed it and found that this is something related with `nativescript-fresco` plugin and perhaps  the way it is caching the image in the memory. I tested it also with the `Image` component and all images has been displayed as expected. Regarding to that you could try to increase the heap by setting `android:largeHeap="true"` in your project `AndroidManifest.xml` file. Example:
```
<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme"
		android:largeHeap="true" >

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
```

Hope this information helps.

**Comment by Leo-lay** [comment]
hi,@tsonevn  i tested use your way,but it still not show, I tested the test device to delete all the pictures, re-took two pictures or show up in the testing process, I found that because the picture size (3120 × 4208) Big reasons can not be shown。so i will try to find the some way to compress the image . do you have some good idea ?

thanks, and  **Merry christmas**～😊

**Comment by Leo-lay** [comment]
fix with [nativescript-image-cache-it](https://github.com/triniwiz/nativescript-image-cache-it).
close.
