### ISSUE TITLE
Problem when calling a page on modal view

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/NativeScript#3440]
_From @dgmaar on January 6, 2017 17:21_

### Tell us about the problem
Hi guys, I'm having a problem calling a modal page on Android, on iOS runs without problems. This the exception...

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onTouch failed

TypeError: Cannot read property 'android' of undefined
File: "/data/data/package_name/files/app/tns_modules/ui/gestures/gestures.js, line: 97, column: 40

StackTrace: 
	Frame: function:'Page._showNativeModalView', file:'/data/data/package_name/files/app/tns_modules/ui/page/page.js', line: 138, column: 47
	Frame: function:'Page.showModal', file:'/data/data/package_name/files/app/tns_modules/ui/page/page-common.js', line: 222, column: 18
	Frame: function:'buscarCliente', file:'/data/data/package_name/files/app/views/abrir/ver-cotizacion/clonar/clonar.js', line: 99, column: 14
	Frame: function:'_executeCallback', file:'/data/data/package_name/files/app/tns_modules/ui/gestures/gestures.js', line: 151, column: 27
	Frame: function:'TapAndDoubleTapGestureListener.onSingleTapUp', file:'/data/data/package_name/files/app/tns_modules/ui/gestures/gestures.js', line: 171, column: 17
	Frame: function:'GesturesObserver.androidOnTouchEvent', file:'/data/data/package_name/files/app/tns_modules/ui/gestures/gestures.js', line: 97, column: 41
	Frame: function:'onTouch', file:'/data/data/package_name/files/app/tns_modules/ui/core/view.js', line: 113, column: 37

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.gen.android.view.View_OnTouchListener.onTouch(android.view.View$OnTouchListener.java)
	at android.view.View.dispatchTouchEvent(View.java:8802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2607)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1779)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:765)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2568)
	at android.view.View.dispatchPointerEvent(View.java:9003)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4209)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4072)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3763)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3820)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5910)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5884)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5855)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6000)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5910)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.2
- Runtime(s): 2.4.1

### Did the error happen while the app was executing?
Yes

[Log-2017-01-06-11-06-48.zip](https://github.com/NativeScript/android-runtime/files/690422/Log-2017-01-06-11-06-48.zip)

_Copied from original issue: NativeScript/android-runtime#676_

**Comment by tsonevn** [comment]
Hi @dgmaar,
Thank you for reporting this issue.

I reviewed your scenario, however was unable to reproduce this behavior, while using Modal View in a project and build it for Android with latest NativeScript. 

For your convinience I am attching [sample project](https://github.com/tsonevn/modalViewListView) for NativeScript core and link to NativeScript Angular 2 [sample](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page/sample-modal-page-module-example). 

It would help if you could provide sample project, where the problem could be reproduced and more info about your environment (node, CLI, tns-core-modules versions).

Regards,
@tsonevn

**Comment by dgmaar** [comment]
Thanks for responding me, here is a small project with the issue https://github.com/dgmaar/modal, hope can help
Steps for issue:
1. First tap on button tap
2. Then tap on last texfield and the issue is raised

**Comment by tsonevn** [comment]
Hi @dgmaar, 
Thank you for your sample project. 

I reviewed your code and found that this problem has been caused due to the fact that in your project, you are opening second `ModalPage` from the first one. This will not work properly and will cause issues in both `Android` and `iOS`. 

The right way is first to close the first `ModalPage` and then to open the second one. You could review the sample code related with your project.

clonar.js
```
....
function buscarCliente()
{
    closeCallback(-1); 

}
exports.buscarCliente = buscarCliente;
....
```

main-page.js
```
var createViewModel = require("./main-view-model").createViewModel;
var page;
function onNavigatingTo(args) {
    page = args.object;   
}

exports.onNavigatingTo = onNavigatingTo;

function ver()
{
    var modalPageModule = "views/abrir/ver-cotizacion/clonar/clonar";
        var context;
        var fullscreen = true;

        page.showModal(modalPageModule, context, function(args) 
        {
            console.log(args);
            if(args == -1){
                setTimeout(function() {
                        var modalPageModule2 = "./views/buscar-cliente-modal/buscar-cliente-modal";
                        var context;
                        var fullscreen = true;
                        page.showModal(modalPageModule2, '', function(cliId, nombre) 
                        {
                            console.log("en ver-cotizacion **** buscarclientemodal: "+cliId, nombre);
                            if(cliId != undefined)
                            {
                                idCliente = cliId;
                                txtNewClient.text = nombre
                            }
                            ocupado.set("valOcupado", false);
                        }, fullscreen);
                }, 100);
            }

        }, fullscreen);
}
exports.ver = ver;
```



Hope this information helps

**Comment by dgmaar** [comment]
Thank you very much @tsonevn that was the problem, now runs without problems :D
