### ISSUE TITLE
[Android][Emulator] Unable to compile application

### ISSUE THREAD

**Issue by echap** [NativeScript/NativeScript#3455]
Hello, I'm facing an issue with an error that looks like issue #2178 :

```
eric [10:15 AM] 
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{fr.hubup.ivy.dev/com.tns.NativeScriptActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/fr.hubup.ivy.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/fr.hubup.ivy.dev-1/lib/arm, /system/fake-libs, /data/app/fr.hubup.ivy.dev-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2567)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/fr.hubup.ivy.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/fr.hubup.ivy.dev-1/lib/arm, /system/fake-libs, /data/app/fr.hubup.ivy.dev-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
    ... 9 more
```

This is very wierd, because a colleague of mine is able to compile the application (same npm/node version, same tns version).

Versions :

```
node --version
v6.9.4
npm --v
3.10.10
tns --version
2.4.2
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Your components are up-to-date.

No issues were detected.
```

and here's my `package.json` :

```
{
  "name": "--",
  "version": "2",
  "description": "--",
  "keywords": [
    "--",
    "--"
  ],
  "author": "Us",
  "license": "Proprietary",
  "nativescript": {
    "id": "my.company.app",
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "nativescript-angular": "1.2.0",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.4.3",
    "moment": "^2.15.1",
    "nativescript-audio": "^2.0.6",
    "nativescript-background-http": "^2.3.0",
    "nativescript-geolocation": "0.0.13",
    "nativescript-google-maps-sdk": "git+https://github.com/hubupfr/nativescript-google-maps-sdk.git",
    "nativescript-google-maps-utils": "git+https://github.com/hubupfr/nativescript-google-maps-utils.git",
    "nativescript-pdf-view": "^1.2.0",
    "nativescript-permissions": "^1.2.0",
    "nativescript-phone": "^1.2.0",
    "nativescript-plugin-firebase": "^3.8.4",
    "nativescript-ripple": "^1.0.1",
    "nativescript-snackbar": "^1.1.4",
    "nativescript-swiss-army-knife": "1.0.7",
    "nativescript-telerik-ui": "^1.4.1",
    "nativescript-cardview": "~1.0.1"
  },
  "devDependencies": {
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "~2.0.10",
    "zone.js": "~0.6.21"
  }
}
```

I've tried to clear everything with `rm -rf platforms/ node_modules/ hooks/` and removing the app from my devices.

Cherry on the cake, making a new project `tns create test --ng` and then `tns run android` is working. I'm stuck.

**Comment by tsonevn** [comment]
Hi @echap, 

Could you try to upgrade your project `package.json` file, while following the below-attached one? 
You should again delete `platforms`, `node_modules`, `hooks` folders and to delete npm cache using `npm cache clear`. 
Then try to rebuild your project using `tns run android`.


package.json

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.testAngular"
  },
  "dependencies": {
    "@angular/common": "2.3.1",
    "@angular/compiler": "2.3.1",
    "@angular/core": "2.3.1",
    "@angular/forms": "2.3.1",
    "@angular/http": "2.3.1",
    "@angular/platform-browser": "2.3.1",
    "@angular/platform-browser-dynamic": "2.3.1",
    "@angular/router": "3.3.1",
    "nativescript-angular": "1.3.0",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-rc.4",
    "tns-core-modules": "2.4.4"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "~2.0.10",
    "zone.js": "~0.7.2"
  }
}
```

Hope this information helps.

**Comment by echap** [comment]
Thanks @tsonevn, few hours or research later, I finally found out it came from my nativescript-snackbar dependancy.


This stacktrace is not very verbose !
