### ISSUE TITLE
error adding .jar lib for Android

### ISSUE THREAD

**Issue by scottmeng** [NativeScript/NativeScript#347]
This is what I got when I tried to add a .jar file as Android library.

```
Warning: File /path_to_lib/gson-2.3.1.jar/project.properties does not exist
```

**Comment by bfattori** [comment]
I get the same thing. It _does_ add the `.jar` file to my project, but when I try to refer to it it complains "Class not found". Here is the stacktrace I clipped:

```
D/TNS_NATIVE(20999): com.tns.gen.org.java_websocket.client.WebSocketClient_f____
_lib_websocket_l18_c40__
W/dalvikvm(20999): JNI WARNING: JNI function GetStaticMethodID called with exception pending
W/dalvikvm(20999):              in Lcom/tns/Platform;.callJSMethodNative:(ILjava/lang/String;Z[Ljava/lang/Object;)Ljava/lang/Object; (GetStaticMethodID)
W/dalvikvm(20999): Pending exception is:
I/dalvikvm(20999): java.lang.ClassNotFoundException: Didn't find class "com.tns.gen.org.java_websocket.client.WebSocketClient_f_____lib_websocket_l18_c40__" on
path: DexPathList[[zip file "/data/app/org.nativescript.SampleApp-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.SampleApp-1, /vendor/lib, /system/lib]]
I/dalvikvm(20999):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
I/dalvikvm(20999):      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)

I/dalvikvm(20999):      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)

I/dalvikvm(20999):      at com.tns.DexFactory.findClass(DexFactory.java:146)
I/dalvikvm(20999):      at com.tns.Platform.findClass(Platform.java:831)
I/dalvikvm(20999):      at com.tns.Platform.callJSMethodNative(Native Method)
I/dalvikvm(20999):      at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:753)
I/dalvikvm(20999):      at com.tns.Platform.callJSMethod(Platform.java:598)
I/dalvikvm(20999):      at com.tns.Platform.callJSMethod(Platform.java:582)
I/dalvikvm(20999):      at com.tns.Platform.callJSMethod(Platform.java:572)
I/dalvikvm(20999):      at com.tns.gen.android.view.GestureDetector_SimpleOnGestureListener_f_data_data_org_nativescript_SampleApp_files_internal_prepareExtend_js_l60_c37__TapAndDoubleTapGestureListener.onSingleTapConfirmed(android.view.GestureDetector$SimpleOnGestureListener.java:-1)
I/dalvikvm(20999):      at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:273)
I/dalvikvm(20999):      at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm(20999):      at android.os.Looper.loop(Looper.java:136)
I/dalvikvm(20999):      at android.app.ActivityThread.main(ActivityThread.java:5097)
I/dalvikvm(20999):      at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(20999):      at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm(20999):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
I/dalvikvm(20999):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
I/dalvikvm(20999):      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bfattori** [comment]
*Figured it out...*

What needs to be done is to specify the _entire package name_ for the class being extended. It _cannot_ be a JavaScript redirection to the package. The old, non working code is directly above. The _new_ (partially) working code is:
```Javascript
var WSClient = org.java_websocket.client.WebSocketClient.extend({
    onOpen: function(handshakeData) {
        var httpFields = {};
        this.proxy.emit('open', httpFields);
    },
    onClose: function(code, reason, remote) {
        this.proxy.emit('close', code, reason, remote);
    },
    onMessage: function(message) {
        this.proxy.emit('message', message);
    },
    onError: function(exception) {
        this.proxy.emit('error', exception);
    }
});

WSClient.prototype.setProxy = function(proxy) {
    if (proxy === undefined || proxy === null) {
        throw new Error("Proxy undefined in WSClient!");
    }
    this.proxy = proxy;
};

exports.get = function(url) {
   return new WSClient(url, new org.java_websocket.drafts.Draft_17);
};
```
The difference is seen on line 1. I refer to `org.java_websocket.client.WebSocketClient`. If I use a variable to hold a reference to the package, e.g `var pkg = org.java_websocket.client;` and then try to do `pkg.WebSocketClient.extend({` then I get a failure.

Can you either clarify in the documentation that it is _required_ to provide the _full package name_ or make it work as a variable reference?

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#176
