### ISSUE TITLE
Installation Troubles "Unexpected Token"

### ISSUE THREAD

**Issue by Zaldor** [NativeScript/NativeScript#3571]
I tried to follow the installation guide:
http://docs.nativescript.org/start/ns-setup-win
without luck.
I have a Windows10 Machine (Lenovo Y50) when I finish and try "tns doctor" command, this is what I get:
`SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Zaldor\AppData\Roaming\npm\node_modules\nativescript\bin\tns:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

C:\WINDOWS\system32>`

Thanks in advance for your help.

**Comment by tsonevn** [comment]
Hi @Zaldor,

You could try to run the described setup script [here](http://docs.nativescript.org/start/quick-setup#windows), which will make the needed configurations.

Hope this helps.

**Comment by Zaldor** [comment]
Not working, but
I tried to run node -v to see the installed version and found that another installation exist very old like 0.10.17. any idea how i can totally clean previous installation of node js?

**Comment by Zaldor** [comment]
SOLVED:
the problem was caused by Emscripten, uninstalled that, reinstalled node.js now "tns" and "tns Doctor" work fine installation seams ok.
