### ISSUE TITLE
Nativescript/Angular app not working after publishing to Amazon AppStore

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/NativeScript#3711]
I'm trying to deploy my application built with nativescript and angular to amazon appstore, but when I submit the application there and test it on my kindle fire the application exits to home screen right after showing the splash screen. I've managed to reproduce the same behavior with the groceries sample app, so you can find bellow the adb log from the app:

```
--------- beginning of system

I/ActivityManager(  975): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=org.nativescript.groceries/com.tns.NativeScriptActivity} from uid 32063 on display 0

W/ActivityManager(  975): Input dispatching paused for current ActivityRecord: ActivityRecord{fa8a940 u0 org.nativescript.groceries/com.tns.NativeScriptActivity t99}

V/WindowManager(  975): addAppToken: AppWindowToken{105a01be token=Token{35e1c079 ActivityRecord{fa8a940 u0 org.nativescript.groceries/com.tns.NativeScriptActivity t99}}} to stack=1 task=99 at 0

D/BatteryStatsExtension.VitalEmitterBatteryAndTime(  975): VitalEmitterBatteryAndTime.start(-): not runnable

V/WindowManager(  975): Adding window Window{255605b1 u0 Starting org.nativescript.groceries} at 9 of 15 (after Window{2e723b5c u0 com.android.settings/com.android.settings.SubSettings})

I/F_C.ItemClickOperation( 1599): Launched  [...]  with intent  [...] 

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/amazon.fluid.widget.StateTransactionManager( 1599): Tried to remove state that wasn't applied: State{mStateId='2131689556', mContentDescription='null', mContentDescriptionResourceId=null, mPropertyBag=0 {}}

I/F_C.Launcher( 1599): onPause

W/art     (  284): PreZygoteFork called when we already have a zygote space.

I/Kernel  ( 1256): [  866.871838] (2)[1256:tx_thread][wlan]Rssi=-59, NewRssi=-59

I/art     (13410): Late-enabling -Xcheck:jni

I/ActivityManager(  975): Start proc 13410:org.nativescript.groceries/u0a49 for activity org.nativescript.groceries/com.tns.NativeScriptActivity

--------- beginning of metrics

I/LoggerMetricsFactoryImpl(  975): PhoneWindowManager:ActivityChanged:org.nativescript.groceries=1.0;CT;1:NR

I/Vlog    (  975): ScreenTime:PackageScreenTime:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Timer=0.02014;TI;1,unit=hours;DV;1:HI

I/LoggerMetricsFactoryImpl(  975): PhoneWindowManager:ScreenTime:endTimeMs=1.488195788276E12;TI;1,startTimeMs=1.488195715772E12;TI;1,com.amazon.firelauncher=72504.0;TI;1:NR

I/LoggerMetricsFactoryImpl(  975): ScreenTime:updateLRUListLocked:page-type=KindleFramework;CK;1,hitType=deviceAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=fgEnd;CK;1,sub-page-type=com.amazon.firelauncher;CK;1,RequestId=AC4F07A7149DA4478D4B;DV;1:NA

I/LoggerMetricsFactoryImpl(  975): ScreenTime:updateLRUListLocked:page-type=KindleFramework;CK;1,hitType=deviceAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=fgStart;CK;1,sub-page-type=org.nativescript.groceries;CK;1,RequestId=9E9E4491815C62565EBB;DV;1:NR

D/ActivityManager(13410): default service binder = android.os.BinderProxy@1b942b2a

D/ActivityManager(13410): default service = android.app.ActivityManagerProxy@2fb95d1b

I/Vlog    ( 1599): performance:SkippedVsyncsBucket1:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Counter=2.0;CT;1,unit=count;DV;1:HI

I/performance( 1599): SkippedVsyncsBucket1: package=com.amazon.firelauncher count=2

I/Vlog    ( 1599): performance:SkippedVsyncsBucket3:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Counter=1.0;CT;1,unit=count;DV;1:HI

I/performance( 1599): SkippedVsyncsBucket3: package=com.amazon.firelauncher count=1

I/Vlog    ( 1599): performance:FrameDropTotal:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Counter=8.0;CT;1,unit=count;DV;1:HI

I/performance( 1599): FrameDropTotal: package=com.amazon.firelauncher count=8

I/Vlog    ( 1599): performance:FramesTotal:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Counter=57.0;CT;1,unit=count;DV;1:HI

I/performance( 1599): FramesTotal: package=com.amazon.firelauncher count=57

I/Vlog    ( 1599): performance:DelayedFirstFrames:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Counter=5.0;CT;1,unit=count;DV;1:HI

I/performance( 1599): DelayedFirstFrames: package=com.amazon.firelauncher count=5

I/Vlog    ( 1599): performance:FirstFramesTotal:fgtracking=false;DV;1,key=com.amazon.firelauncher;DV;1,Counter=5.0;CT;1,unit=count;DV;1:HI

I/performance( 1599): FirstFramesTotal: package=com.amazon.firelauncher count=0

I/PackageRecencyCallback(  975): Queuing notifcation to package: ComponentInfo{com.amazon.kindle.cms/com.amazon.kindle.cms.MaintenanceService$PackageRecencyListener}

D/VendorDisplayManagerGlobalCallback(13410): callGetInstance: nil

D/OpenGLRenderer( 1599): endAllStagingAnimators on 0xb9262888 (LayerDrawable) with handle 0xb8c8de18

I/ContextImpl(13410): com.amazon.client.metrics.api registered service at i = 68

D/ProfileManager(13410): Create ProfileManager instance

W/linker  (13410): libNativeScript.so: unused DT entry: type 0x6ffffffe arg 0x2938

W/linker  (13410): libNativeScript.so: unused DT entry: type 0x6fffffff arg 0x3

I/TNS.Native(13410): NativeScript Runtime Version 2.5.0, commit 95dd12d69eba88755158987d8c4666a9c5aa5e07

D/TNS.Native(13410): JNI_ONLoad

D/TNS.Native(13410): JNI_ONLoad END

W/getprop (13429): type=1400 audit(0.0:380): avc: denied { module_request } for kmod="personality-8" scontext=u:r:untrusted_app:s0 tcontext=u:r:kernel:s0 tclass=system permissive=0

D/TNS.Native(13410): Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found

D/KeyguardUpdateMonitor( 1106): handleBatteryUpdate

W/System.err(12429): android.content.pm.PackageManager$NameNotFoundException: com.fw.appshare

W/System.err(12429): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:115)

W/System.err(12429): 	at amazon.content.pm.AmazonPackageManagerImpl.getPackageInfo(AmazonPackageManagerImpl.java:273)

W/System.err(12429): 	at me.onemobile.utility.bh.w(Utility.java:3552)

W/System.err(12429): 	at me.onemobile.android.service.a.onReceive(ChargingAdService.java:40)

W/System.err(12429): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:902)

W/System.err(12429): 	at android.os.Handler.handleCallback(Handler.java:739)

W/System.err(12429): 	at android.os.Handler.dispatchMessage(Handler.java:95)

W/System.err(12429): 	at android.os.Looper.loop(Looper.java:135)

W/System.err(12429): 	at android.app.ActivityThread.main(ActivityThread.java:5466)

I/Kernel  (  170): [  867.150521] (1)[170:healthd]healthd: battery l=68 v=3912 t=23.0 h=2 st=2 chg=u

W/System.err(12429): 	at java.lang.reflect.Method.invoke(Native Method)

W/System.err(12429): 	at java.lang.reflect.Method.invoke(Method.java:372)

W/System.err(12429): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)

W/System.err(12429): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

D/TNS.Native(13410): V8 version 5.5.372.32

--------- beginning of crash
```

**Comment by hypery2k** [comment]
any news on that?
