### ISSUE TITLE
Android: Can't build AOT version, getting Error: spawn tns ENOENT

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3715]
Getting the following error when trying to build an AOT version of an app:

```
D:\www\test>npm run start-android-bundle

> @ start-android-bundle D:\www\test
> npm run ns-bundle --android --start-app


> @ ns-bundle D:\www\test
> ns-bundle

Running webpack for android...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn tns ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ns-bundle" "--android" "--start-app"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ns-bundle script 'ns-bundle'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ns-bundle
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\test\AppData\Roaming\npm-cache\_logs\2017-02-27T14_48_20_488Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-android-bundle"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start-android-bundle: `npm run ns-bundle --android --start-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start-android-bundle script 'npm run ns-bundle --android --start-app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ns-bundle --android --start-app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\test\AppData\Roaming\npm-cache\_logs\2017-02-27T14_48_20_551Z-debug.log
```

package.json:
```
{
  "description": "Test Mobile Application",
  "license": "",
  "readme": "",
  "repository": "",
  "nativescript": {
    "id": "com.test.app",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/router": "3.4.8",
    "nativescript-angular": "1.4.1",
    "nativescript-angular-snapshot": "1.4.0-5.5.372.32-1",
    "nativescript-geolocation": "0.0.18",
    "nativescript-gif": "1.0.9",
    "nativescript-google-maps-sdk": "1.4.3",
    "nativescript-phone": "1.2.4",
    "nativescript-vibrate": "1.1.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.2.0",
    "tns-core-modules": "2.5.1",
    "tns-platform-declarations": "2.5.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.8",
    "@ngtools/webpack": "1.2.11",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "4.0.1",
    "extract-text-webpack-plugin": "2.0.0",
    "htmlparser2": "3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "0.26.1",
    "nativescript-dev-android-snapshot": "0.*.*",
    "nativescript-dev-typescript": "0.3.7",
    "nativescript-dev-webpack": "^0.3.3",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "2.0.0",
    "typescript": "2.1.6",
    "webpack": "2.2.1",
    "webpack-sources": "0.1.4",
    "zone.js": "0.7.7"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```

**Comment by tsonevn** [comment]
Hi @dxshindeo,

This problem could be caused due to some an issue with removing the old files from the `platforms/android` folder while webpacking the app
You could try do delete `node_modules`, `platforms` and `hooks` folders and remove the app from the device or emulator.
Then run again `npm install --save-dev nativescript-dev-webpack` and at the end, to build the project, run  `npm run start-android-bundle` .

Hope this helps.

**Comment by dxshindeo** [comment]
Unfortunately those steps were done before-hand and they make no difference

**Comment by dxshindeo** [comment]
This is also reproducable with empty project:
1. `tns create test --ng`
2. `cd test`
3. `npm install --save-dev nativescript-dev-webpack`
4. `npm run start-android-bundle`

Node: 6.9.4, 6.9.10, 7.6.0
Npm: 4.3.0
NS CLI: 2.5.2

**Comment by tsonevn** [comment]
Hi @dxshindeo, 
Thank you for the given steps.
I tested webpack on a clear NativeScript Angular 2 project, and unfortunately, I have to confirm that this is a real issue in `nativescript-dev-webpack` plugin. This behavior could be reproduced only on Windows.

You could keep track on the issue, we will provide an appropriate fix soon. Most probably by the end of the day.

Hope this info helps.

**Comment by dxshindeo** [comment]
Thank you, now it's fixed and working properly!
