### ISSUE TITLE
TypeError while using Webpack at startup

### ISSUE THREAD

**Issue by gund** [NativeScript/NativeScript#3822]
### Tell us about the problem
When project is setup with Webpack command `npm run start-android-bundle` results in error:
```
C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:14552
            var sourceFile = new SourceFileConstructor(261 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);
                                                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:14552:109)
    at parseSourceFileWorker (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:14484:26)
    at Object.parseSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:14433:26)
    at Object.createSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:14288:29)
    at WebpackCompilerHost.getSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\@ngtools\webpack\src\compiler
_host.js:209:27)
at findSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63453:29)
    at processSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63384:27)
    at C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63494:17
    at Object.forEach (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:1293:30)
    at processReferencedFiles (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63492:16)
    at findSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63477:21)
    at processSourceFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63384:27)
    at processRootFile (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:63271:13)
    at C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:62620:60
    at Object.forEach (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:1293:30)
    at Object.createProgram (C:\Users\malke\Projects\SimpleReader\node_modules\typescript\lib\typescript.js:62620:16)
```

### Which platform(s) does your issue occur on?
Android (Not able to test iOS but should be the same result)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): no `"tns-android"` or `"tns-ios"` are found in package.json
- Plugin(s): nativescript-dev-webpack@0.3.6

### Please tell us how to recreate the issue in as much detail as possible.
- `$ tns create test --ng`
- `$ cd test && tns platform add android`
- `$ npm install -D nativescript-dev-webpack`
- `$ npm run start-android-bundle` - And watch the error

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Just follow steps above no additional modifications required.

**Comment by sis0k0** [comment]
Try deleting the `platforms` folder and running the command again.

**Comment by gund** [comment]
@sis0k0 well that helped - thanks =)
