### ISSUE TITLE
Angular compiler-cli error

### ISSUE THREAD

**Issue by robcaa** [NativeScript/NativeScript#3851]
## Please, provide the details below:
Installed **nativescript-dev-webpack plugin** and run the following command:
**npm run start-android-bundle**
caused this error:
```
C:\wamp\www\nativescript\tilitoli\node_modules\@angular\compiler-cli\src\version.js:18
exports.VERSION = new core_1.Version('2.4.6');
                  ^

TypeError: core_1.Version is not a constructor
    at Object.<anonymous> (C:\wamp\www\nativescript\tilitoli\node_modules\@angular\compiler-cli\src\version.js:18:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp\www\nativescript\tilitoli\node_modules\@angular\compiler-cli\index.js:24:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
2.5.0

package.json:
```
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "nativescript-admob": "^1.3.0",
    "nativescript-angular": "1.2.0",
    "nativescript-audio": "^3.0.0",
    "nativescript-bitmap-factory": "^1.6.2",
    "nativescript-gif": "^1.0.8",
    "nativescript-social-share": "^1.3.2",
    "nativescript-sound": "^1.0.4",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.5.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~2.4.3",
    "@ngtools/webpack": "1.2.4",
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "babylon": "6.14.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "htmlparser2": "~3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "^0.3.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.0.10",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3",
    "zone.js": "~0.6.21"
  },
```

I found this angular problem:
https://github.com/angular/angular-cli/issues/3458

**Comment by sis0k0** [comment]
Hey @robcaa,

The problem is that you have mismatching versions of `@angular/compiler-cli` and the other angular packages. I would suggest upgrading your angular packages to ~2.4 and `nativescript-angular` to ~1.4.

**Comment by robcaa** [comment]
ok I check it
