### ISSUE TITLE
TimePicker: minMinute is not handled properly on Android

### ISSUE THREAD

**Issue by manojdcoder** [NativeScript/NativeScript#3877]
### Tell us about the problem
Setting `minMinute` throws run time exception while user scrolls through minutes.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.2 
- Runtime(s): 2.5.0

### Please tell us how to recreate the issue in as much detail as possible.
Let's consider the current time is `1:50 PM`. With code below, the minHour will be `13` and minMinute will be `50`. Scroll the minutes towards `00`, as soon it reaches `00` the app crashes.

### Expected behaviour:
The hour should automatically move to `2` so then the time will be `2:00 PM`. It works as expected on iOS, also on Android only when minHour / minMinute are not set.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

HTML
```
 <!-- >> creating-timepicker-html -->
    <timePicker class="m-15" #timePicker (loaded)="configure(timePicker)" verticalAlignment="center"></timePicker>
    <!-- << creating-timepicker-html -->
```

TypeScript
```
configure(timePicker: TimePicker) {
        let today: Date = new Date();
        timePicker.minHour = timePicker.hour = today.getHours();
        timePicker.minMinute = timePicker.minute = today.getMinutes();
    }
```

### Error:
An uncaught Exception occurred on "main" thread. com.tns.NativeScriptException: 
Calling js method onTimeChanged failed

Error: Minute property value (00:00) is not valid. Min time: (13:43), max time: (23:59).
File: "file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/time-picker/time-picker-common.js, line: 90, column: 8

### StackTrace: 
```
	Frame: function:'onMinutePropertyChanged', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/time-picker/time-picker-common.js', line: 90, column: 15
	Frame: function:'DependencyObservable._onPropertyChanged', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js', line: 213, column: 13
	Frame: function:'Bindable._onPropertyChanged', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/core/bindable.js', line: 73, column: 45
	Frame: function:'ProxyObject._onPropertyChanged', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/core/proxy.js', line: 45, column: 45
	Frame: function:'View._onPropertyChanged', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/core/view-common.js', line: 772, column: 45
	Frame: function:'DependencyObservable._setValueInternal', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js', line: 307, column: 18
	Frame: function:'DependencyObservable._setValue', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js', line: 133, column: 14
	Frame: function:'set', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/time-picker/time-picker-common.js', line: 165, column: 18
	Frame: function:'TimePicker._setNativeValueSilently', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/time-picker/time-picker.js', line: 46, column: 25
	Frame: function:'onTimeChanged', file:'file:///data/data/com.ns.first/files/app/tns_modules/tns-core-modules/ui/time-picker/time-picker.js', line: 25, column: 32


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.gen.android.widget.TimePicker_OnTimeChangedListener.onTimeChanged(android.widget.TimePicker$OnTimeChangedListener.java)
	at android.widget.TimePickerSpinnerDelegate.onTimeChanged(TimePickerSpinnerDelegate.java:483)
	at android.widget.TimePickerSpinnerDelegate.access$300(TimePickerSpinnerDelegate.java:46)
	at android.widget.TimePickerSpinnerDelegate$2.onValueChange(TimePickerSpinnerDelegate.java:140)
	at android.widget.NumberPicker.notifyChange(NumberPicker.java:1936)
	at android.widget.NumberPicker.setValueInternal(NumberPicker.java:1722)
	at android.widget.NumberPicker.scrollBy(NumberPicker.java:1143)
	at android.widget.NumberPicker.computeScroll(NumberPicker.java:1097)
	at android.view.View.updateDisplayListIfDirty(View.java:15185)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
	at android.view.View.updateDisplayListIfDirty(View.java:15158)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by NickIliev** [comment]
@manojdcoder there are few things to consider when working with TimePicker in Android.
- when you scroll your minutes from 59 to 00 you are also changing the **hour** value (incrementing with one).
- the getHours() JavaScript method will return a value from 0 to 23  (24-hour format) while your default Android TimePicker is using AM/PM with possible hours from 0 to 11.

This said modify your code the following way and it should work as expected.
```
    configure(timePicker: TimePicker) {
        var today = new Date();
        
        // if Android
        timePicker.minHour = today.getHours() - 12;
        timePicker.minMinute = today.getMinutes();
    }
```

**Comment by manojdcoder** [comment]
@NickIliev I tried your code, but it doesn't restrict time after 12 hours. For example if current time is 4:30 PM (16:30), time picker allows time between 4:30 AM to 11:59 PM which doesn't meet the expectation of `minHour` / `minMinute`.

So I ended up implementing a similar logic that is internally used in NativeScript

```
configure(timePicker: TimePicker) {
        timePicker.on('propertyChange', function () {
            let today = new Date(),
                hour = today.getHours(),
                minute = today.getMinutes();

            if (timePicker.hour < hour) {
                timePicker.hour = hour;
            }

            if (timePicker.hour <= hour && timePicker.minute < minute) {
                timePicker.minute = minute;
            }
        }, this);
    }
```

So I think definitely TimePicker needs a fix in Android.

**Comment by manojdcoder** [comment]
@NickIliev Can you please confirm this as issue, at least I expect the app to not crash as user moves the spinner.

**Comment by NickIliev** [comment]
@manojdcoder indeed the time=-picker is throwing after the user reverts the hours outside the already set minHour. Marking this one as a bug.
Steps to reproduce:
- open demos from nativescript-sdk-examples-ng.
- navigate to time-picker
- set minHour (e.g. 6)
- revert the minutes so the time-picker will go from 6:00 to 5:59
Result app crashes
