### ISSUE TITLE
Nativescript 3.0 "tns run android"

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#3930]
whenever i try to run the app ("nativescript 3.0") it giving this gradles error {
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1
}

**Comment by NickIliev** [comment]
Hi @harriscreativity 

Please provide more information about your case (like **package.json** of the application you are trying to execute) and if possible provide a sample application that demonstrates your problem. Also clarify what you mean by "the app" (is it a new application created with `tns create` or an old one you are trying to migrate to 3.0)

Here is the least amont of info needed so taht our community can investigate your problem and suggest solutions: 

> ## Please, provide the details below:

> ### Tell us about the problem
> Please, ensure your title is less than 63 characters long and starts with a capital
> letter.
> 
> ### Which platform(s) does your issue occur on?
> iOS/Android/Both
> 
> ### Please provide the following version numbers that your issue occurs with:
> - CLI: (run `tns --version` to fetch it)
> - Cross-platform modules: (check the 'version' attribute in the
> `node_modules/tns-core-modules/package.json` file in your project)
> - Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
> `package.json` file of your project)
> - Plugin(s): (look for the version number in the `package.json` file of your
> project)
> 
> ### Please tell us how to recreate the issue in as much detail as possible.
> 
> ### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

**Comment by harriscreativity** [comment]
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1

**Comment by harriscreativity** [comment]
ns --version
3.0.0-rc.1

**Comment by dtopuzov** [comment]
@harriscreativity 
Please provide exact steps to reproduce (isolate with hello-world app if possible) and post `package.json` of your project.

**Comment by harriscreativity** [comment]
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-android": {
      "version": "3.0.0-rc.1"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "nativescript-angular": "rc",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "rc",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}

**Comment by NickIliev** [comment]
@harriscreativity I've created a brand new project with the content of your package.json and it works as expected on my side. The only thing that I had to change was the version of nativescript-dev-android-snapshot as the one you are using is not a valid version. Here are the exact steps I've followed:
- `tns create myApp --tsc`
- `rm -rf node_modules` and `rm -rf platforms` (take this steps at your side to make sure that your project is clean)
- `tns run android`

You can also try[ the test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3930) I;ve created and used trying to reproduce your behavior

You can also run `tns doctor` to verify that your environment settings are all set. If the doctor prints an error please post it here to investigate further

**Comment by Pip3r4o** [comment]
@harriscreativity it would help us greatly if you posted your build output - the console output printed after you type in `tns run android` up to the point the console is released.

**Comment by harriscreativity** [comment]
W
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessMana
ger.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1

**Comment by harriscreativity** [comment]
Ally-Razas-iMac:What2Wear nick$ tns run android --emulator
Executing before-prepare hook from /Users/nick/Desktop/nativescript/What2Wear/hooks/bef
ore-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Users/nick/Desktop/nativescript/What2Wear/hooks/bef
ore-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Unzipping /Users/nick/.gradle/wrapper/dists/gradle-3.3-bin/64bhckfm0iuu9gap9hg3r7ev2/gr
adle-3.3-bin.zip to /Users/nick/.gradle/wrapper/dists/gradle-3.3-bin/64bhckfm0iuu9gap9h
g3r7ev2
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessMana
ger.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1

**Comment by Pip3r4o** [comment]
@harriscreativity this appears to be due to a corrupted downloaded gradle wrapper package. 

Please navigate to your user directory -> `.gradle/wrapper/dists/gradle-3.3-bin` and remove all of its contents. This will allow you to download the zip again.

**Comment by harriscreativity** [comment]
yeah it did work

**Comment by ramintagizade** [comment]
same problem

**Comment by Pip3r4o** [comment]
@ramintagizade please follow the suggested solutions above. This isn't under our control, so it's something that a user must address for themselves.
