### ISSUE TITLE
AndroidManifest.xml changes not copied in platforms/android directories

### ISSUE THREAD

**Issue by ickata** [NativeScript/NativeScript#3950]
Hi,

I want to define default icon for tray messages in Android. I'm using FCM data messages. [According to the instructions](https://firebase.google.com/docs/cloud-messaging/android/receive) I am placing these meta tags immediately after the opening `<application>` tag:

```
      <meta-data
         android:name="com.google.firebase.messaging.default_notification_icon"
         android:resource="@drawable/icon_notify" />
      <meta-data
         android:name="com.google.firebase.messaging.default_notification_color"
         android:resource="@color/colorAccent" />
```

Then I run `tns build android`, however after the build I cannot see these meta tags in the AndroidManifest.xml files located in `platforms/android` directories. 

What do I do wrong?

tns version 2.5.3
tns core modules 2.5.2

**Comment by tsonevn** [comment]
Hi @ickata,
This could be related to some issue with syncing the newly file changes to the platform. 
Regarding that, could you try to remove `platforms` folder and to clear npm cache with `npm cache clear`. Then rebuild again the project with `tns run android`.

If you still have the same issue, please provide some sample project, which could be debugged locally.

**Comment by ickata** [comment]
Hi @tsonevn ,

Many thanks for the quick reply. I followed your instructions and now I can confirm that I see the meta-data tags in the platforms/android directories:

```
$ find platforms/ -name "*.xml" | xargs grep -F "com.google.firebase.messaging.default_notification_icon" --color
platforms//android/build/intermediates/manifests/full/F0F1F2F3F4/debug/AndroidManifest.xml:            android:name="com.google.firebase.messaging.default_notification_icon"
platforms//android/src/main/AndroidManifest.xml:         android:name="com.google.firebase.messaging.default_notification_icon"
platforms//android/src/main/res/AndroidManifest.xml:         android:name="com.google.firebase.messaging.default_notification_icon"
```

Unfortunately I cannot test it neither in emulator nor in real device, so I cannot confirm that tray messages will now have the icon. But they should have.

**Comment by ickata** [comment]
@tsonevn ,

I confirm that the issue with AndroidManifest.xml syncing is resolved. However, after removing platforms directory, now I cannot deploy on my test iPhone. `tns run ios` fails:

```
** BUILD SUCCEEDED **

Project successfully built.
Installing...
Successfully installed on device with identifier 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX'.
Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239
# run ios

┌───────────────────────┬──────────────────────────────────┐
│ Usage                 │ Synopsis                         │
│ Run on all connected  │ $ tns run ios [--release] [-     │
│ devices               │ -justlaunch]                     │
│ Run on a selected     │ $ tns run ios [--device <Device  │
│ connected device      │ ID>] [--release] [--justlaunch]  │
│ Start an emulator and │ $ tns run ios --emulator [       │
│ run the app inside it │ <Emulator Options>] [--release]  │
└───────────────────────┴──────────────────────────────────┘

Runs your project on a connected iOS device or in the iOS Simulator, if configured. This is shorthand for prepare, build and deploy. While your app is running, prints the output from the application in the console and watches for changes in your code. Once a change is detected, it synchronizes the change with all selected devices and restarts/refreshes the application.

IMPORTANT: Before building for iOS device, verify that you have configured a valid pair of certificate and provisioning profile on your OS X system.

### Options

    * --no-watch - If set, changes in your code will not be reflected during the execution of this command.
    * --device - Specifies a connected device on which to run the app.
    * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate ios. You cannot use --device and --emulator simultaneously.
    * --release - If set, produces a release build. Otherwise, produces a debug build.
    * --justlaunch - If set, does not print the application output in the console.
    * --clean - If set, forces rebuilding the native application.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns device ios
    * <Emulator Options> is any valid combination of options as listed by $ tns help emulate ios
```

Second try to run `tns run ios` results in:

```
Skipping prepare.
Searching for devices...
Skipping package build. No changes detected on the native side. This will be fast!
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
{ Error
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:8:18)
    at Module._compile (module.js:570:32)
  name: 'Exception',
  message: 'Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239',
  errorCode: 3892314239,
  suppressCommandHelp: undefined }
```

This used to work before applying your instructions. 

Can you please help? Thanks!

**Comment by tsonevn** [comment]
Hi @ickata,
This seems to be an issue with killing the old app from the device.
You can try to delete the app from the device and to build it again -> `tns run ios`.

If you still have this problem, could you give us some more info about the Xcode version and the iOS version of the device?

In the meantime, you could also verify, whether the issue is reproduced after you delete again the `platforms` folder and rebuild the project.

**Comment by ickata** [comment]
@tsonevn ,

I just solved the issue following the instruction from issue #152 . Disabling the w-fi on the device and running `tns run ios` solved it. It's a strange workaround, though. I tried deleting the app and deploying again, but w/o success.
