### ISSUE TITLE
Getting exception with animations in v3.0 RC

### ISSUE THREAD

**Issue by alixandru** [NativeScript/NativeScript#3969]
In the v3.0 RC, I'm getting exception with an app that uses animations.

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onAnimationEnd failed

TypeError: Cannot read property '_onAndroidAnimationEnd' of null
File: "file:///data/data/ro.bvb.arenaxt.core/files/app/tns_modules/tns-core-modules/ui/animation/animation.js, line: 99, column: 26

StackTrace: 
 Frame: function:'onAnimationEnd', file:'file:///data/data/ro.bvb.arenaxt.core/files/app/tns_modules/tns-core-modules/ui/animation/animation.js', line: 99, column: 27


 at com.tns.Runtime.callJSMethodNative(Native Method)
 at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
 at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
 at com.tns.Runtime.callJSMethod(Runtime.java:890)
 at com.tns.Runtime.callJSMethod(Runtime.java:874)
 at com.tns.Runtime.callJSMethod(Runtime.java:866)
 at com.tns.gen.android.animation.Animator_AnimatorListener.onAnimationEnd(Animator_AnimatorListener.java:17)
 at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:829)
 at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
 at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
 at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:829)
 at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
 at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
 at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
 at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
 at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
 at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
 at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
 at android.view.Choreographer.doCallbacks(Choreographer.java:702)
 at android.view.Choreographer.doFrame(Choreographer.java:635)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6682)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

### Did you verify this is a real problem?
Yes, nothing found

### Tell us about the problem
In Nativescript 3.0 RC, animations fail with an exception, apparently after the last animation completes.

### Which platform(s) does your issue occur on?
Android. I have not tested yet on iOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0-rc.1
- Cross-platform modules: ^3.0.0-rc.2
- Runtime(s): 3.0.0-rc.1 (iOS not tested yet)
- Plugin(s): see extract from `package.json`
````
  "dependencies": {
    "moment": "^2.17.1",
    "nativescript-email": "^1.4.0",
    "nativescript-secure-storage": "^2.1.0",
    "nativescript-swiper": "^0.1.0",
    "nativescript-telerik-ui": "^1.7.0-2017.4.4.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.5",
    "nativescript-websockets": "^1.3.1",
    "numeral": "^2.0.4",
    "rxjs": "^5.2.0",
    "tns-core-modules": "^3.0.0-rc.2",
    "zlibjs": "^0.2.0"
  },
  "devDependencies": {
    "awesome-typescript-loader": "~3.0.8",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.4.2",
    "nativescript-dev-webpack": "^0.3.4",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "tns-platform-declarations": "^2.5.0",
    "typescript": "^2.2.2",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3"
  },
````

### Please tell us how to recreate the issue in as much detail as possible.

I have a rather complex setup which involves custom components loaded programmatically (for improving the perceived load time of the app, since the app displays a large list of elements).

Basically, the page starts with a ScrollView containing an empty StackLayout. 

````
  <ScrollView>
    <StackLayout className="table-lines" loaded="onLoad">
    </StackLayout>
  </ScrollView>
````
On page load the StackLayout is populated asynchronously with a number of child elements. The definition of these child elements is specified in an external XML file and is loaded as a custom component. The XML definition itself only contains a GridLayout with 1 row and 3 cols of standard elements (StackLayouts, Labels, etc).

The code which loads the child elements is below:
````
let options = ... // defines custom component paths, etc. it also contains the list of items which will be loaded in the UI
export function onLoad(args) {
  getListItems(args.object, options, 0);
}

// build one item at a time, with a timeout of 10ms between each step
function getListItems(holder: layout.LayoutBase, options, start) {
  timer.setTimeout(() => {

    let src = options.items;
    if (src.length > start) {
      buildItem(holder, options, src[start]);
      getListItems(holder, options, start + 1);
    }

  }, 10);
}

function buildItem(holder: layout.LayoutBase, options, it) {
  if (!holder.isLoaded) {
    return; // view unloaded
  }

  // create line
  let item = <view.View>builder.load({
    path: options.loadPath,
    name: options.loadModule
  });
  item.bindingContext = it;
  item.className = 'line ';

  // add item to parent holder
  holder.addChild(item);

  if (Config.animations.list) {
    // try some animations. first zoom out
    item.scaleX = 0;
    item.scaleY = 0;

    // animate the scales back to one over time to make a zoom in effect
    item.animate({
      scale: { x: 1, y: 1 },
      duration: 100
    });
  }
}
````

This used to work just fine in v2.5.x

**Comment by NickIliev** [comment]
@alixandru  are you still experiencing this issue with NativeScript 3.4.x

**Comment by alixandru** [comment]
Unfortunatelly I am unable to test right now. You can close the issue for
now and I will come back if this is still happening.

Thanks, Alex.
