### ISSUE TITLE
Can't handle onReceivedSslError in Android WebView

### ISSUE THREAD

**Issue by kimberlysiva** [NativeScript/NativeScript#3998]
Currently a user receives no feedback when attempting to load a webpage with a bad certificate. Developers need to handle the `onReceivedSslError` callback in WebViewClient, but there is no obvious way to override this.

I've tried adding the handler in web-view.android.js directly:

```
var WebViewClientClassInner = (function (_super) {
...
    WebViewClientClassInner.prototype.onReceivedSslError = function (view, handler, error) {
        console.log("WebViewClientClass.onReceivedSslError");
        _super.prototype.onReceivedSslError.call(this, view, handler, error);
    };
```

But this is never fired.

Ideally this handler would become a part of the nativescript code base, otherwise we need a clear way to override it.

To test:

Navigate to "https://badssl.com" in an Android WebView and click on any of the bad certificate links (expired, wrong.host, etc.) The `onPageFinished` event is fired without providing any feedback. There is no way to catch the `onReceivedSslError` event.

Platform: Android
CLI: 2.5.0
Cross-platform modules: 2.5.2
Runtime: 2.5.0

**Comment by tsonevn** [comment]
Hi @kimberlysiva 
Thank you for reporting this issue.
I tested this case on my side and have to confirm that `onReceivedSslError` will not be fired properly on Android. 
We will research wath is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by blairmacintyre** [comment]
Hi @tsonevn any progress on this?  We're going through our backlog and this is a "very visible issue" in our app, especially for webdev's trying to develop for Argon4 (our app)

**Comment by tsonevn** [comment]
Hi @blairmacintyre,
This problem is still under review and unfortunately, I could not commit to the exact date when we will start working on this issue.

However, any PR, which provides a fix for this problem, will be highly appreciated. You could also review our [contributing guide](https://www.nativescript.org/contribute)

**Comment by surdu** [comment]
It appears that at some point the [WebViewClient class from NS was exported](https://github.com/NativeScript/NativeScript/issues/1196), but not anymore.

I see the [client is exposed as a property](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/web-view/web-view.android.ts#L99) on the native component, but adding the function onto it doesn't work.

Would exporting the WebViewClient class again be a proper solution ?

**Comment by surdu** [comment]
I've created a PR to export again the WebViewClientImp which should allow developers to extend the class in with their own methods.

That being said, I'm having a small problem figuring out how to use this from JS though 😞 . I'm trying this:

```js
const {WebViewClientImpl} = require("tns-core-modules/ui/web-view");

WebViewClientImpl.prototype.onReceivedSslError = function (view, handler) {
	handler.proceed();
};

webview.android.setWebViewClient(new WebViewClientImpl(webview));
```

But the onReceivedSslError is not called when it should.

**Comment by RnbWd** [comment]
any progress on this issue?

**Comment by surdu** [comment]
@RnbWd Not more than what I mentioned in the PR: https://github.com/NativeScript/NativeScript/pull/5192#issuecomment-359366697

**Comment by cybaj** [comment]
@surdu could you drop some link about what you called "limitations of NS"? URL link that you mention in [#5192](https://github.com/NativeScript/NativeScript/pull/5192#issuecomment-359366697) is broken.

I got some experience about this issue, and results I can't understand.  
1. I use `WebClientSSLImplementation` which extends `WebClient`, overwriting `onReceivedSslError`. [repos](https://github.com/cybaj/test_webview_extend)
```
export class WebViewClientSslImpl extends android.webkit.WebViewClient {
    
    constructor(public owner: any) {
        super();
        return global.__native(this);
    }
    // ...
    public onReceivedSslError(view: any, handler: any, error: any) {
        handler.proceed();
        console.log('ssl error')
    }
};
```
```
export function onWebViewLoaded(args: EventData) {
    let wv = <WebView>args.object;
    const clientWithSsl = new WebViewClientSslImpl(wv);
    const androidWebView = <android.webkit.WebView>wv.android;
    androidWebView.setWebViewClient(clientWithSsl);
}
```

2. With my android device (Android 8.0.0), I have `preview` it. mostly `onReceivedSslError` was not fired. but, I don't know why this happening, after I added log line in `onReceivedSslError`, it was fired. and the handler `proceed`ed.
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
LOG from device Galaxy A8 Star: HMR: Hot Module Replacement Enabled. Waiting for signal.
LOG from device Galaxy A8 Star: https://192.168.0.6:50468
LOG from device Galaxy A8 Star: ssl error
LOG from device Galaxy A8 Star: https://192.168.0.6:9999
LOG from device Galaxy A8 Star: ssl error
LOG from device Galaxy A8 Star: ssl error
```
but it was only once. after then it doesn't fire. 
```
Preparing project...
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
LOG from device Galaxy A8 Star: HMR: Hot Module Replacement Enabled. Waiting for signal.
LOG from device Galaxy A8 Star: https://192.168.0.8:9999
LOG from device Galaxy A8 Star: https://192.168.0.8:50468
```
3. I built it remotely with `nativescript-remote-builds`. Installation was fine in same device. But this time, an error occurs, after I run the app.
```
An uncaught Exception occurred on "main" thread.
Calling js method onReceivedError failed
Error: JNI Exception occurred (SIGABRT).
=======
Check the 'adb logcat' for additional information about the error.
=======


StackTrace:
module.exports.push../web-view.ts.WebViewClientSslImpl.onReceivedError(file:///data/data/org.nativescript.remoteextendswebviewclient/files/app/bundle.js:334:46)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.android.webkit.WebViewClient_bundle_297_28_WebViewClientSslImpl.onReceivedError(WebViewClient_bundle_297_28_WebViewClientSslImpl.java:72)
	at Ox0.handleMessage(chromium-Monochrome.aab-stable-410410173:134)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
4. I can't not even assume where this is coming from. but maybe it is issue about **marking mode** I think. I don't know what is exactly `markingMode=none` safe code, but have some try.
```
import { WebViewClientSslImpl } from "./web-view";

export class HelloWorldModel extends Observable {
    public webviewclient: WebViewClientSslImpl;
    // ...
```
```
export function onWebViewLoaded(args: EventData) {
    let wv = <WebView>args.object;
    const context = wv.page.bindingContext
    const clientWithSsl = new WebViewClientSslImpl(wv);
    context.set('webviewclient', clientWithSsl)

    const androidWebView = <android.webkit.WebView>wv.android;
    androidWebView.setWebViewClient(context.webviewclient);
}
```
I `preview` it,  and it works only once, just like before.
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
LOG from device Galaxy A8 Star: https://www.naver.com
LOG from device Galaxy A8 Star: https://192.168.0.6:50468
LOG from device Galaxy A8 Star: ssl error
```
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-33b010505c29).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-33b010505c29).
LOG from device Galaxy A8 Star: https://www.naver.com
LOG from device Galaxy A8 Star: https://192.168.0.8:50468
```
what should I have to do to figure this out?

**Comment by surdu** [comment]
@cybaj [Found a cached version](https://webcache.googleusercontent.com/search?q=cache:kDjuFYIEIFoJ:https://discourse.nativescript.org/t/extend-nativescripts-default-webviewclient-implementation/4077/5+&cd=1&hl=en&ct=clnk&gl=ro&client=firefox-b-d)
