### ISSUE TITLE
Repro: Module build failed: TypeError: Cannot read property 'text' of undefined (with symlink)

### ISSUE THREAD

**Issue by DanielKucal** [NativeScript/NativeScript#4040]
## Please, provide the details below:
I have existing Angular2/4 app that isn't much AoT-compatible so for now I want to use merely some of its code to prototype NativeScript mobile app. I don't want to make changes in two places so symlinks are the best approach for me to achieve what I want... At least I thought so.

### Tell us about the problem
The problem is NativeScript compilation breaks when I use symlink to project's parent directory with error that says nothing yet the file name:
```
ERROR in /Users/danielkucal/Applications/Angular2/config.service.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/typescript/lib/typescript.js:6641:71)
    at IdentifierObject.TokenOrIdentifierObject.getStart (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/typescript/lib/typescript.js:78689:23)
    at IdentifierObject.TokenOrIdentifierObject.getText (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/typescript/lib/typescript.js:78710:77)
    at refactor.findAstNodes.filter (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/@ngtools/webpack/src/loader.js:138:44)
    at Array.filter (native)
    at refactor.findAstNodes.forEach.node (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/@ngtools/webpack/src/loader.js:137:14)
    at Array.forEach (native)
    at _removeDecorators (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/@ngtools/webpack/src/loader.js:128:10)
    at Promise.resolve.then (/Users/danielkucal/Applications/Angular2/sample-Groceries/node_modules/@ngtools/webpack/src/loader.js:304:33)
 @ ./app.module.ngfactory.ts 32:0-55
 @ ./main.aot.ts
```
What is also interesting, when I link to file from other project I see very different error (that also says nothing - there is one consistent thing 🤣):
```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/danielkucal/Applications/Angular2/other-project/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/danielkucal/Applications/Angular2/other-project/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/danielkucal/Applications/Angular2/other-project/node_modules/@angular/core/src/di/opaque_token.d.ts

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/danielkucal/Applications/Angular2/sample-Groceries/app'
 @ ./main.aot.ts 3:0-60
```

### Which platform(s) does your issue occur on?
iOS for sure, Android with great probability too
Developing platform has to support symlinks.

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 2.5.4
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 2.5.2
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 2.5.0
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
I've made a reproduction of this issue in my fork of sample-Groceries: https://github.com/DanielKucal/sample-Groceries/tree/cannot-read-text-of-undefined-repro
To reproduce please run the following commands:
```
git clone https://github.com/DanielKucal/sample-Groceries
cd sample-Groceries
npm install
git checkout cannot-read-text-of-undefined-repro
npm run repro-undefined
npm run start-ios-bundle
```

### Please share the minimal amount of code needed to recreate the problem.
The code added is just simple service:
```
import { Injectable } from "@angular/core";

@Injectable()
export class ConfigService {

    constructor() {
    }

}
```
defined in AppModule:
```
@NgModule({
    providers: [
        // ...
        ConfigService
        // ...
    ] // ...
})
export class AppModule {
}
```

I look forward to hearing from you. Thanks in advance

**Comment by DanielKucal** [comment]
For anyone that also faces this issue and need a solution for today, I've developed a simple tool called [symlink-resolver](https://github.com/DanielKucal/symlink-resolver). You can find all the information you need (including configuration for nativescript) in the README.
