### ISSUE TITLE
App crashes at runtime while trying to use Telerik UI RadSideDrawer

### ISSUE THREAD

**Issue by paschaldev** [NativeScript/NativeScript#4050]
After installing native cript telerik ui. When I try to use the RadSideDrawer, app crashes with this output 

```
com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'android' of undefined
File: "/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js, line: 91, column: 39

StackTrace: 
	Frame: function:'RadSideDrawer.initOldDrawer', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js', line: 91, column: 40
	Frame: function:'RadSideDrawer._createUI', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js', line: 147, column: 18
	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/core/view.js', line: 191, column: 14
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/core/view.js', line: 143, column: 14
	Frame: function:'eachChild', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/core/view.js', line: 148, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/page/page-common.js', line: 265, column: 41
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/core/view.js', line: 154, column: 18
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/core/view.js', line: 119, column: 18
	Frame: function:'View._addView', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/core/view-common.js', line: 921, column: 14
	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
	at com.tns.Runtime.callJSMethod(Runtime.java:716)
	at com.tns.Runtime.callJSMethod(Runtime.java:697)
	at com.tns.Runtime.callJSMethod(Runtime.java:687)
	at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:2069)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
	at android.app.BackStackRecord.run(BackStackRecord.java:852)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:452)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

This is the xml code for the side drawer

```
<Page class="page" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:drawer="nativescript-telerik-ui/sidedrawer" loaded="pageLoaded">

    <ActionBar title="RadSideDrawer Demo" class="action-bar" />

    <drawer:RadSideDrawer id="sideDrawer">

        <!-- side drawer content -->
        <drawer:RadSideDrawer.drawerContent>
            <StackLayout class="sidedrawer-left">
                <StackLayout class="sidedrawer-header">
                    <Label text="Hello RadSideDrawer!" class="sidedrawer-header-brand" />
                </StackLayout>
                <StackLayout class="sidedrawer-content">
                    <Label text="Home" class="sidedrawer-list-item-text" />
                    <Label text="Basics" class="sidedrawer-list-item-text" />
                    <Label text="Options" class="sidedrawer-list-item-text" />
                    <Label text="Help" class="sidedrawer-list-item-text" />
                    <Label text="Advanced" class="sidedrawer-list-item-text" />
                </StackLayout>
            </StackLayout>
        </drawer:RadSideDrawer.drawerContent>

        <!-- The main content -->
        <drawer:RadSideDrawer.mainContent>
            <StackLayout>
                <Button text="Toggle Drawer" class="btn btn-primary" tap="toggleDrawer" />
            </StackLayout>
        </drawer:RadSideDrawer.mainContent>

    </drawer:RadSideDrawer>

</Page>
```

I checked line 91 of where the supposed error happened ( File: "/data/data/org.nativescript.sampleGroceries/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js, line: 91, column: 39 ) and this is the line of code

`this._android = new com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer(this._context);`

Nativescript version: 2.4.2 
Android Device: 5.1 ( Lollipop )

**Comment by paschaldev** [comment]
Found the solution although this wasnt specified in Telerik's homepage.

> Big Note: If you are building the application from the previous tutorial or If you already have android folder inside platforms folder first remove it and then run tns platform add android command to add the android platform again so that all java files for nativescript-telerik-ui will get build.

Source: http://www.techumber.com/navigation-drawer-side-drawer-for-nativescript/
