### ISSUE TITLE
JSON Error When Running App

### ISSUE THREAD

**Issue by cevarief** [NativeScript/NativeScript#4059]
Running app on IOS emulator using `tns run ios` works good. 
When i try to run on android emulator, it shows _app has stopped_ and console.log does not show any informative message where file that causing error, except the following. Can anyone give a clue ? Thank you very much.

`tns 2.5.4, tsc 2.1.6, angular 4.`

> Found peer TypeScript 2.1.6
> 04-25 14:32:01.754  6538  6538 W System.err: org.json.JSONException: End of input at character 0 of
> 04-25 14:32:01.754  6538  6538 W System.err: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
> 04-25 14:32:01.754  6538  6538 W System.err: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
> 04-25 14:32:01.754  6538  6538 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:156)
> 04-25 14:32:01.754  6538  6538 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:173)
> 04-25 14:32:01.754  6538  6538 W System.err: 	at com.tns.FileSystem.readJSONFile(FileSystem.java:100)
> 2:32:08 PM - Compilation complete. Watching for file changes.
>

**Comment by cevarief** [comment]
I've clean up the platform/android using ./gradelw build -S and rerun using --trace log. The error displayed is now informative.
