### ISSUE TITLE
demo app doesn't start on android 

### ISSUE THREAD

**Issue by dc39** [NativeScript/NativeScript#41]
I ran the demo app out of the box
ios runs ok, but android version gives problems on both android+simulator

```
➜  blox  tns run android           
shell.js: internal error
Error: ENOENT, no such file or directory '/Users/dc/dev/shumi/blox/platforms/android/assets/app'
    at Object.fs.mkdirSync (fs.js:642:18)
    at /usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:174:14
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:122:19
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:158:45
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)


```

**Comment by dtopuzov** [comment]
Can you give some more details:
Nativescript CLI version (tns --version)
tns-android version (you can get it from .tnsproject file)

**Comment by dcsan** [comment]
$ tns --version
0.10.0

```
	"tns-android": {
		"version": "0.10.0"
	}

$ tns run android
Project successfully prepared
Project successfully prepared
Buildfile: /Users/dc/dev/ref/ns-test/blox/platforms/android/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.1.2
 [checkenv] Installed at /usr/local/Cellar/android-sdk/23.0.2

-setup:
     [echo] Project Name: blox
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 22.0.1
     [echo] Resolving Build Target for blox...
[gettarget] Project Target:   Android 4.2.2
[gettarget] API level:        17
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/dc/dev/ref/ns-test/blox/platforms/android/bin/rsObj
    [mkdir] Created dir: /Users/dc/dev/ref/ns-test/blox/platforms/android/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for blox...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] No changes in the AndroidManifest files.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] No changed resources. R.java and Manifest.java untouched.
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 1 source file to /Users/dc/dev/ref/ns-test/blox/platforms/android/bin/classes

create_project_lib:
     [echo] make lib/android folder

copy_default_sdk:

retrieve_min_version_from_manifest:

does_min_sdk_jar_exist:

replace_default_sdk_if_possible:
   [delete] Deleting: /Users/dc/dev/ref/ns-test/blox/lib/Android/android.jar
     [copy] Copying 1 file to /Users/dc/dev/ref/ns-test/blox/lib/Android

copy_project_jars:

delete_old_metadata:

generate_metadata_from_given_jars:
     [java] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/telerik/metadata/Generator : Unsupported major.minor version 51.0
     [java] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [java] 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
     [java] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
     [java] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
     [java] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
     [java] 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

BUILD FAILED
/Users/dc/dev/ref/ns-test/blox/platforms/android/custom_rules.xml:85: Java returned: 1

Total time: 1 second
Command ant failed with exit code 1
# run android
┌───────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                             │ Synopsis                                                                                                       │
│ Run on all connected devices and  │ $ tns run android [--keyStorePath <File Path> --keyStorePassword <Password> --keyStoreAlias <Name> -           │
│ running emulators                 │ -keyStoreAliasPassword <Password>] [--release]                                                                 │
│ Run on a selected connected       │ $ tns run android --device <Device ID> [--keyStorePath <File Path> --keyStorePassword <Password> -             │
│ device or running emulator        │ -keyStoreAlias <Name> --keyStoreAliasPassword <Password>] [--release]                                          │
│ Start an emulator and run the app │ $ tns run android --emulator [<Emulator Options>] [--keyStorePath <File Path> --keyStorePassword <Password> -  │
│ inside it                         │ -keyStoreAlias <Name> --keyStoreAliasPassword <Password>] [--release]                                          │
└───────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Runs your project on a connected Android device or in a native Android emulator, if configured. This is shorthand for prepare, build and deploy.

### Options

    * --device - Specifies a connected device on which to run the app. 
    * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate android. 
    * --release - If set, produces a release build. Otherwise, produces a debug build. When the --keyStore* options are specified, produces a signed release build.
    * --keyStorePath - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --keyStore* options along with --release to produce a signed release build. You need to specify all --keyStore* options.
    * --keyStorePassword - Provides the password for the keystore file specified with --keyStorePath. You can use the --keyStore* options along with --release to produce a signed release build. You need to specify all --keyStore* options.
    * --keyStoreAlias - Provides the alias for the keystore file specified with --keyStorePath. You can use the --keyStore* options along with --release to produce a signed release build. You need to specify all --keyStore* options.
    * --keyStoreAliasPassword - Provides the password for the alias specified with --keStoreAliasPassword. You can use the --keyStore* options along with --release to produce a signed release build. You need to specify all --keyStore* options.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns device android
    * <Emulator Options> is any valid combination of options as listed by $ tns help emulate android

```

android SDK v17 is installed

![image](https://cloud.githubusercontent.com/assets/514002/7300530/7afa3ce2-e991-11e4-9868-62b305bb0ce9.png)

**Comment by dcsan** [comment]
android manifest:

```xml
 <uses-sdk
        android:minSdkVersion="17"
        android:targetSdkVersion="17" />
  ```

**Comment by dcsan** [comment]
so not sure where the version 51.0 came from:

```
generate_metadata_from_given_jars:
     [java] Exception in thread "main" java.lang.UnsupportedClassVersionError: 
com/telerik/metadata/Generator : Unsupported major.minor version 51.0
```

**Comment by dcsan** [comment]
i made a public repo with the code for reference, but it really is just the basics from your demo site
also runs fine on ios, so its the android build process..
https://github.com/dcsan/ns-test

**Comment by khadorkin** [comment]
@dcsan please, look at https://github.com/dcsan/ns-test/pull/1 . I didn't test it, but think, that it works.

**Comment by dcsan** [comment]
nope, exactly the same error. I [noticed you changed the models](https://github.com/khadorkin/ns-test/commit/1cb3d98c35fb473cea6915eaba97274de67fd6ca) - is there something different about android builds that would need that?

As i mentioned before this app does run fine in the ios simulator, the only problem is android.
so it would seem to be related to the build process per platform. 

I'm guessing that like reactnative, your android port is behind ios, but how far behind? 
It seems odd the demo apps don't run. Or maybe it's something to do with my android build config...

is this important?

    Unsupported major.minor version 51.0

**Comment by slavchev** [comment]
According to http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error you may have older Java version. If that is the case, I would suggest to update it. Please let us know if that solves the issue.

**Comment by dcsan** [comment]
hmm, interesting:

![image](https://cloud.githubusercontent.com/assets/514002/7313633/e6044cc4-ea10-11e4-975e-6a9bf0c516a2.png)

**Comment by dcsan** [comment]
yay, fixed it! (but i can't close the issue)

**Comment by slavchev** [comment]
Good news. Was it the Java version or something else?

**Comment by dcsan** [comment]
updating java fixed it. 
and the v51 i guess refers to a javac version # so that would seem to be the reason.

**Comment by slavchev** [comment]
Thanks, we will document it and update our documentation/requirements.
