### ISSUE TITLE
Error on android build after update to tns 3.0

### ISSUE THREAD

**Issue by NNieto** [NativeScript/NativeScript#4114]
I upgraded from 2.5 to 3.0, and when I try to build my project, this happens
```
Running full build
finished with reading lines with js files
Warning: there already is an extend called com.tns.FragmentClass.
Warning: there already is an extend called com.tns.NativeScriptActivity.
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
/home/alejandro/Escritorio/work/wosevents/platforms/android/src/main/java/com/tns/gen/android/content/BroadcastReceiver_frnal_ts_helpers_l58_c38__BroadcastReceiver.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:60)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED
```

```javascript
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.highlevel.wos.events",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "nativescript-background-http": "^2.5.1",
    "nativescript-cardview": "^1.3.2",
    "nativescript-effects": "^0.3.0",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-geolocation": "0.0.19",
    "nativescript-google-maps-sdk": "^1.4.3",
    "nativescript-google-places": "0.0.3",
    "nativescript-image-cache-media": "^1.0.6",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-platform-css": "^1.4.0",
    "nativescript-plugin-firebase": "^3.11.4",
    "nativescript-slides": "^2.2.8",
    "nativescript-social-share": "^1.3.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-timedatepicker": "^1.1.1",
    "tns-core-modules": "^3.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}
```

**Comment by NickIliev** [comment]
@NNieto apart from updating your tns-core-modules and a tns-android you will also need to bump the versions of your third party plugins to the ones that are compatible with NativeScript 3.0.0.
In your package.json for example the version of **nativescript-geolocation** is hard coded to 0.0.19 while the compatible version is 3.0.0. That should be done to all plugins that have released 3.0.0 compatible versions.

**Comment by NickIliev** [comment]
@NNieto I was able to build with succsess using your package.json without nativescript-google-maps-sdk and nativescript-plugin-firebase which are in conflict at my side. Apart from this all the other versions must be as wfollows:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.issue4114",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "nativescript-background-http": "^3.0.0",
    "nativescript-cardview": "^2.0.0-rc.0",
    "nativescript-effects": "^0.5.0",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-geolocation": "3.0.0",
    "nativescript-google-places": "0.0.3",
    "nativescript-image-cache-media": "^1.0.6",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-platform-css": "^1.4.0",
    "nativescript-slides": "^2.2.8",
    "nativescript-social-share": "^1.3.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-timedatepicker": "^1.1.1",
    "tns-core-modules": "^3.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}

```

**Comment by NNieto** [comment]
Thanks @NickIliev, I will downgrade to 2.5 because I need to use that plugins. Thanks for the quick reply.
