### ISSUE TITLE
Installer-Error on Windows since 3.0

### ISSUE THREAD

**Issue by BenGermany** [NativeScript/NativeScript#4178]
After testing {N} 2.5 i thought i had to wait for 3.0, but since 3.0 is out, the GUI Installer dont work.

This is third time with a CLEAN Windows 10 Creators with ONLY node 6.10.3 AND JDK 8_131 and use of Windows Installer. Nothing else like SDK is installed at this time. I thought, it might be a temporarily problem, but nothing changes. Before 3.0 the Installer works on a clean installed windows.

Here is the log:

[1028:0E00][2017-05-12T17:05:18]i001: Burn v3.8.1128.0, Windows v6.3 (Build 9600: Service Pack 0), path: D:\Downloads\nativescript-cli-setup-wix.exe, cmdline: ''
[1028:0E00][2017-05-12T17:05:18]i000: Initializing version variable 'RequiredJdkVersion' to value '1.8'
[1028:0E00][2017-05-12T17:05:18]i000: Initializing version variable 'RequiredNodeJsVersion' to value '6.0.0'
[1028:0E00][2017-05-12T17:05:20]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\Ben\AppData\Local\Temp\NativeScript_CLI_Setup_20170512170520.log'
[1028:0E00][2017-05-12T17:05:20]i000: Setting string variable 'WixBundleOriginalSource' to value 'D:\Downloads\nativescript-cli-setup-wix.exe'
[1028:0E00][2017-05-12T17:05:20]i000: Setting string variable 'WixBundleName' to value 'NativeScript CLI Setup'
[1028:0E00][2017-05-12T17:05:20]i000: Loading managed bootstrapper application.
[1028:0E00][2017-05-12T17:05:20]i000: Creating BA thread to run asynchronously.
[1028:2264][2017-05-12T17:05:20]i052: Condition 'VersionNT > v6.1 OR (VersionNT = v6.1 AND ServicePackLevel >= 1)' evaluates to true.
[1028:0E00][2017-05-12T17:05:23]i100: Detect begin, 5 packages
[1028:0E00][2017-05-12T17:05:23]i000: Registry key not found. Key = 'SOFTWARE\Android SDK Tools'
[1028:0E00][2017-05-12T17:05:23]i000: Setting numeric variable 'AndroidSdkPath' to value 0
[1028:0E00][2017-05-12T17:05:23]i000: Registry key not found. Key = 'SOFTWARE\JavaSoft\Java Development Kit'
[1028:0E00][2017-05-12T17:05:23]i000: Setting string variable 'NodeJsVersionx64' to value '6.10.3'
[1028:0E00][2017-05-12T17:05:23]i000: Registry key not found. Key = 'SOFTWARE\Android Studio'
[1028:0E00][2017-05-12T17:05:23]i000: Setting numeric variable 'AndroidStudioSdkPathx64' to value 0
[1028:0E00][2017-05-12T17:05:23]i000: Registry key not found. Key = 'SOFTWARE\Android Studio'
[1028:0E00][2017-05-12T17:05:23]i000: Setting numeric variable 'AndroidStudioSdkPath' to value 0
[1028:0E00][2017-05-12T17:05:23]i000: Registry key not found. Key = 'SOFTWARE\Node.js'
[1028:0E00][2017-05-12T17:05:23]i000: Setting string variable 'Netfx4x64FullVersion' to value '4.7.02046'
[1028:0E00][2017-05-12T17:05:23]i000: Setting string variable 'JdkVersionx64' to value '1.8'
[1028:0E00][2017-05-12T17:05:23]i000: Setting string variable 'Netfx4FullVersion' to value '4.7.02046'
[1028:0E00][2017-05-12T17:05:23]i052: Condition 'Netfx4FullVersion AND (NOT VersionNT64 OR Netfx4x64FullVersion)' evaluates to true.
[1028:0E00][2017-05-12T17:05:23]i052: Condition 'JdkVersion >= RequiredJdkVersion OR (VersionNT64 AND JdkVersionx64 >= RequiredJdkVersion)' evaluates to true.
[1028:0E00][2017-05-12T17:05:23]i052: Condition '(AndroidSdkPath OR AndroidStudioSdkPath) OR (VersionNT64 AND AndroidStudioSdkPathx64)' evaluates to false.
[1028:0E00][2017-05-12T17:05:23]i103: Detected related package: {2F9DD870-93DA-48D2-BEA5-A58D7C673EA5}, scope: PerMachine, version: 6.10.3.0, language: 0 operation: Downgrade
[1028:0E00][2017-05-12T17:05:23]i103: Detected related package: {2F9DD870-93DA-48D2-BEA5-A58D7C673EA5}, scope: PerMachine, version: 6.10.3.0, language: 0 operation: Downgrade
[1028:0E00][2017-05-12T17:05:23]i101: Detected package: Netfx4Full, state: Present, cached: None
[1028:0E00][2017-05-12T17:05:23]i101: Detected package: Jdk8, state: Present, cached: None
[1028:0E00][2017-05-12T17:05:23]i101: Detected package: AndroidSdk, state: Absent, cached: None
[1028:0E00][2017-05-12T17:05:23]i101: Detected package: NodeJs, state: Obsolete, cached: None
[1028:0E00][2017-05-12T17:05:23]i101: Detected package: NodeJsx64, state: Obsolete, cached: None
[1028:0E00][2017-05-12T17:05:23]i199: Detect complete, result: 0x0
[1028:0E00][2017-05-12T17:05:23]i200: Plan begin, 5 packages, action: Install
[1028:0E00][2017-05-12T17:05:23]w321: Skipping dependency registration on package with no dependency providers: Netfx4Full
[1028:0E00][2017-05-12T17:05:23]i052: Condition 'False' evaluates to false.
[1028:0E00][2017-05-12T17:05:23]w321: Skipping dependency registration on package with no dependency providers: Jdk8
[1028:0E00][2017-05-12T17:05:23]w321: Skipping dependency registration on package with no dependency providers: AndroidSdk
[1028:0E00][2017-05-12T17:05:23]i000: Setting string variable 'WixBundleLog_AndroidSdk' to value 'C:\Users\Ben\AppData\Local\Temp\NativeScript_CLI_Setup_20170512170520_0_AndroidSdk.log'
[1028:0E00][2017-05-12T17:05:23]i201: Planned package: Netfx4Full, state: Present, default requested: Present, ba requested: Present, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[1028:0E00][2017-05-12T17:05:23]i201: Planned package: Jdk8, state: Present, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[1028:0E00][2017-05-12T17:05:23]i201: Planned package: AndroidSdk, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
[1028:0E00][2017-05-12T17:05:23]i201: Planned package: NodeJs, state: Obsolete, default requested: None, ba requested: None, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[1028:0E00][2017-05-12T17:05:23]i201: Planned package: NodeJsx64, state: Obsolete, default requested: None, ba requested: None, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[1028:0E00][2017-05-12T17:05:28]i299: Plan complete, result: 0x0
[1028:0E00][2017-05-12T17:05:39]i300: Apply begin
[1A74:1F90][2017-05-12T17:05:39]i360: Creating a system restore point.
[1A74:1F90][2017-05-12T17:05:39]w363: Could not create system restore point, error: 0x80070422. Continuing...
[1A74:1F90][2017-05-12T17:05:40]i000: Caching bundle from: 'C:\Users\Ben\AppData\Local\Temp\{62077766-c609-4248-80d3-eec5636c3d7d}\.be\NativeScript.Cli.Setup.Wix.exe' to: 'C:\ProgramData\Package Cache\{62077766-c609-4248-80d3-eec5636c3d7d}\NativeScript.Cli.Setup.Wix.exe'
[1A74:1F90][2017-05-12T17:05:40]i320: Registering bundle dependency provider: {62077766-c609-4248-80d3-eec5636c3d7d}, version: 1.0.0.0
[1028:17CC][2017-05-12T17:05:40]w343: Prompt for source of package: AndroidSdk, payload: AndroidSdk, path: D:\Downloads\Android Software Development Kit
[1028:17CC][2017-05-12T17:05:40]i338: Acquiring package: AndroidSdk, payload: AndroidSdk, download from: https://dl.google.com/android/installer_r24.4.1-windows.exe
[1A74:0380][2017-05-12T17:08:46]i305: Verified acquired payload: AndroidSdk at path: C:\ProgramData\Package Cache\.unverified\AndroidSdk, moving to: C:\ProgramData\Package Cache\F9B59D72413649D31E633207E31F456443E7EA0B\Android Software Development Kit.
[1A74:1F90][2017-05-12T17:08:46]i301: Applying execute package: AndroidSdk, action: Install, path: C:\ProgramData\Package Cache\F9B59D72413649D31E633207E31F456443E7EA0B\Android Software Development Kit, arguments: '"C:\ProgramData\Package Cache\F9B59D72413649D31E633207E31F456443E7EA0B\Android Software Development Kit" /S'
[1028:0E00][2017-05-12T17:09:10]i000: Applying package AndroidSdk completed successfuly.
[1028:0E00][2017-05-12T17:09:10]i319: Applied execute package: AndroidSdk, result: 0x0, restart: None
[1028:0E00][2017-05-12T17:09:10]i000: Executing operation: AndroidHome.
[1028:0E00][2017-05-12T17:09:10]i000: Executing operation AndroidHome completed successfully.
[1028:0E00][2017-05-12T17:09:10]i000: Executing operation: AndroidSdkUpdate.
[1028:0E00][2017-05-12T17:09:17]i000: Executing command echo Y | "C:\Users\Ben\AppData\Local\Android\android-sdk\tools\android" update sdk --filter platform-tools --all --no-ui
[1028:0E00][2017-05-12T17:09:46]i000: Executing command echo Y | "C:\Users\Ben\AppData\Local\Android\android-sdk\tools\android" update sdk --filter tools --all --no-ui
[1028:0E00][2017-05-12T17:16:26]i000: Executing command echo Y | "C:\Users\Ben\AppData\Local\Android\android-sdk\tools\android" update sdk --filter android-23 --all --no-ui
[1028:0E00][2017-05-12T17:18:07]i000: Executing command echo Y | "C:\Users\Ben\AppData\Local\Android\android-sdk\tools\android" update sdk --filter build-tools-25.0.2 --all --no-ui
[1028:0E00][2017-05-12T17:19:13]i000: Executing command echo Y | "C:\Users\Ben\AppData\Local\Android\android-sdk\tools\android" update sdk --filter extra-android-m2repository --all --no-ui
[1028:0E00][2017-05-12T17:27:09]i000: Executing command echo Y | "C:\Users\Ben\AppData\Local\Android\android-sdk\tools\android" update sdk --filter extra-google-m2repository --all --no-ui
[1028:0E00][2017-05-12T17:31:04]i000: Executing operation AndroidSdkUpdate completed successfully.
[1028:0E00][2017-05-12T17:31:04]i000: Executing operation: InstallNativeScript.
[1028:0E00][2017-05-12T17:32:12]e000: Executing operation InstallNativeScript failed. 
Error: [31;1mPath must be a string. Received undefined[0m
Failed to display command help { Error
    at Object.<anonymous> (C:\Users\Ben\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Ben\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:14:18)
    at Module._compile (module.js:570:32)
  name: 'Exception',
  message: 'Unknown command \'post-install-cli\'. Try \'$ tns help\' for a full list of supported commands.',
  errorCode: 127,
  suppressCommandHelp: true }
[1028:0E00][2017-05-12T17:32:12]i399: Apply complete, result: 0x0, restart: None, ba requested restart:  No

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#2812
