### ISSUE TITLE
Issue with closing the keyboard on SearchBar onClear event - iOS

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#4223]
if we call `dismissSoftInput`  on `SearchBar` `onClear` event the keyboard will not hide on iOS.
For example:
XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <GridLayout rows="auto *" columns="*" class="p-20">
        <SearchBar row="0" col="0" id="searchBar" hint="Search" text="" clear="onClear" submit="onSubmit" />
    </GridLayout>
</Page>

```
Typescript
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {SearchBar} from "ui/search-bar";
import {TextField} from "ui/text-field"

export function navigatingTo(args: EventData) {

    let page = <Page>args.object;

    page.bindingContext = new HelloWorldModel();
}

export function onClear(args){
    var search:SearchBar = <SearchBar>args.object;
        search.dismissSoftInput();
}
```

An possible workaround is to setup `setTimeuot` with 0 miliseconds, which will trigger keyboard hiding.

```
export function onClear(args){
    var search:SearchBar = <SearchBar>args.object;
    setTimeout(()=>{
        search.dismissSoftInput();
    }, 0)
}
```
- CLI: 3.0.1
- Cross-platform modules:3.0.0
- Runtime(s):tns-ios - 3.0.0

**Comment by iMarwan-k** [comment]
Hi, any update on this

**Comment by tsonevn** [comment]
Hi @iMarwan-k,
This issue is still under review. Also, any PR, which provides a fix for this problem will be highly appreciated. You can check our contributing [guidelines](https://www.nativescript.org/contribute).

**Comment by fthuin** [comment]
Hi @tsonevn,

I used your solution with the setTimeout, but I now have an issue people should be aware of:

If you use this solution for Android, and you allow people to navigate when the searchBar is focused, the searchBar will be sometimes destroyed before the `.dismissSoftInput()` is called, resulting in:

```
System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.inputmethod.InputConnection.closeConnection()' on a null object reference
System.err: 	at android.view.inputmethod.InputConnectionWrapper.closeConnection(InputConnectionWrapper.java:270)
System.err: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
System.err: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
System.err: 	at android.os.Looper.loop(Looper.java:251)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6589)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Solution is to make the fix iOS specific using `isIOS` from platform or to catch the error, otherwise you'll have the nativescript error activity popping up.

**Comment by janoshrubos** [comment]
Tried to reproduce this issue, but it seems to be resolved now.
If this error is still relevant, feel free to open a new issue!
