### ISSUE TITLE
APK fails on device

### ISSUE THREAD

**Issue by benlooi** [NativeScript/NativeScript#4303]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by benlooi** [comment]
Hi. I have an issue with the debug APK. It runs in my emulator, but when i copy the APK to my test device it fails.
I have updated tns and core modules as per instructions on the website.
The splash screen loads, but after that it throws errors as follows.
Any help is appreciated.
I couldn't do tns deploy android as my adb does not detect the devices attached.

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.MyApp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: extras.getInt is not a function
File: "file:///data/data/org.nativescript.MyApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 652, column: 29

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.MyApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 652, column: 30
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.MyApp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2366)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
	at android.app.ActivityThread.access$800(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5328)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: extras.getInt is not a function
File: "file:///data/data/org.nativescript.MyApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 652, column: 29

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.MyApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 652, column: 30
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.MyApp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
	at com.tns.Runtime.callJSMethod(Runtime.java:890)
	at com.tns.Runtime.callJSMethod(Runtime.java:874)
	at com.tns.Runtime.callJSMethod(Runtime.java:866)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:5354)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
	... 11 more

**Comment by Pip3r4o** [comment]
Hey @benlooi from what I can tell, your test device has a custom Android version, akin to that of MIUI ROMs. is it by chance a Redmi 

Unfortunately at this point it is not something that we can address since metadata is built against the standard Android SDK, and not the one on target devices, which can apparently differ a lot class structure-wise. I'd suggest you test the APK on a Redmi with android 21+, an emulator, or an altogether different standard Android device.

Please refer to the tracking issue https://github.com/NativeScript/android-runtime/issues/404. I'll let you know if there's an update.
