### ISSUE TITLE
Getting desperate with Geolocation 3.0.0

### ISSUE THREAD

**Issue by d3mac123** [NativeScript/NativeScript#4316]
My app (a GPS dashboard) was running fine on both Android (device) and iOS Simulator until I had the "great" idea of updating everything to 3.0.x. The moment I did it, nothing else is working anymore due issues with the geolocation plugin.

My package file:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.asouza.buddyFinder",
    "tns-ios": {
      "version": "3.0.1"
    },
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "nativescript-dom": "^1.1.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-mapbox": "^3.0.0",
    "nativescript-orientation": "^1.6.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-platform-css": "^1.4.0",
    "nativescript-plugin-firebase": "^3.12.0",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "^3.0.1"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.2",
    "lazy": "1.0.11"
  }
}
```

Fact is, it is not updating the coordinates on Android (or even worse, crashing). See the sample below:
page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" class="page" loaded="pageLoaded">
    <StackLayout class="p-20">
    <Label text="Coordinates" class="h2 text-center" textWrap="true"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true" id="messageText"/>
    </StackLayout>
</Page>
```

page.js
```
var observable = require("data/observable");
var pageModule = require("ui/page");
var viewModel = new observable.Observable();
var geolocation = require("nativescript-geolocation");


var messageText
var loca
exports.pageLoaded = function(args) {
    page = args.object;
    messageText = page.getViewById("messageText");

    page.bindingContext = { message:loca};
}



if (!geolocation.isEnabled()) {
        geolocation.enableLocationRequest();
}


watchId = geolocation.watchLocation(
    function (loc) {
        if (loc) {
            console.log("Received location: " + loc);
            loca = loc
            messageText.text = loca.latitude+", "+loca.longitude
        }
    }, 
    function(e){
        console.log("Error: " + e.message);
    }, 
    {desiredAccuracy: 3, updateDistance: 10, minimumUpdateTime : 1000 * 1});
```
It is working fine on the iOS Simulator and crashing on Android:
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.geoLocationTest/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js, line: 149, column: 13

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/main-page.js', line: 23, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/main-page.js', line: 23, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js, line: 149, column: 13

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/main-page.js', line: 23, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/main-page.js', line: 23, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.geoLocationTest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
	at com.tns.Runtime.callJSMethod(Runtime.java:890)
	at com.tns.Runtime.callJSMethod(Runtime.java:874)
	at com.tns.Runtime.callJSMethod(Runtime.java:866)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
	at android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
	... 19 more

```

**Comment by NickIliev** [comment]
@d3mac123 as far as I see the code that handles the location permissions is located outside of any application and/or component lifecycle and is not explicitly called. In the same time, the error log indicates that the app is crashing due to permissions problems. Try to nest `geolocation.enableLocationRequest();` inside and explicit event or in a lifecycle event (e.g. in `pageLoaded`) where it would makes sense for the application logic.

You can also use [this demo application ](https://github.com/NativeScript/nativescript-geolocation-demo)as a reference to check if everything is set as expected. The demo application is migrated to NativeScript 3.x.x so it also demonstrates that all the functionalities are working.

**Comment by d3mac123** [comment]
Thanks NickIliev! Moving the geolocation.enableLocationRequest() to the pageLoaded stopped the crash. I am learning how to code and it is still strange to me how something can work fine on iOS and not on Android (unfortunately same code does not mean same results in both platforms).

I've also downloaded and ran your demo (although I cannot read/write in TS). Everything worked fine (again on iOS) but on my Android device, I keep getting "undefined" for lat/long/altitude. It seems (like in my app), the watchLocation is not capturing/updating the coordinates. Can you please double check if from your side?

Thanks again!

**Comment by NickIliev** [comment]
@d3mac123 what is the device on which you are testing?

I am testing with Nexus 5x and on my side, everything works as expected. Notice that to have results from [this code](https://github.com/NativeScript/nativescript-geolocation-demo/blob/release/demo/app/views/main-page.ts#L66-L77) (where **watchLocation** is used) you will need first to allow the application to use your location by pressing "Enable Location" button. If the permissions are not explicitly given by the user - the other buttons won't work.

**Comment by d3mac123** [comment]
I am testing on a BLU R1 HD. This device had my app working fine until I migrated to TNS 3.0.x.

Regarding my testing, I got the geolocation sample app and installed it. It didn't work (I pressed the Enable Location and Start Monitoring buttons, in that order, to guarantee all the permissions were set). Everything worked perfectly on iOS, but on Android, Google Maps keeps showing undefined for latitude, longitude, and altitude.

This is EXACTLY the same issue my own app is having.

Are you compiling your app with this same setting I have?
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.0.3           │ 3.0.3          │ Up to date  │
│ tns-core-modules │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-android      │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-ios          │ 3.0.1           │ 3.0.1          │ Up to date  │

**Comment by NickIliev** [comment]
@d3mac123 I have updated the demo app to use 3.0.a modules and overall I am using exactly the same setting as yours.

Here is the package.json dependencies for the demo project on my side
```
  "nativescript": {
    "id": "org.nativescript.nativescriptgeolocationdemo",
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "nativescript-geolocation": "^3.0.0",
    "nativescript-googlemaps": "^3.0.1",
    "tns-core-modules": "^3.0.1",
    "tns-platform-declarations": "^3.0.1"
  },
  "devDependencies": {
    "babel-traverse": "6.10.4",
    "babel-types": "6.11.1",
    "babylon": "6.8.3",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^2.2.2"
  }
```
My Google Play Services is updated to the last version (ver.41) in the SDK manager.

Perhaps, you can test on another Android device so we can see if the error is consistent on your side or if it is related to the specific device.

**Comment by d3mac123** [comment]
What a nightmare! After rebooting my phone several times, the app(s) went back alive. I think something "locked" the location services. All good now but I will never know the real reason for this issue.

Thanks for your help. You are the best!
