### ISSUE TITLE
Error: make build for crashlytics (fabric.io)

### ISSUE THREAD

**Issue by mikraus94** [NativeScript/NativeScript#4364]
Hello,

I have issue while uploading android app to Crashlytics.

`Crashlytics halted compilation because it can't extract Crashlytics build info from the APK`

Is any way to implement crashlytics to nativescript application? Can you help me?

Thank you

**Comment by tsonevn** [comment]
Hi @mikraus94,
For this scenario, you could use [nativescript-fabric](https://www.npmjs.com/package/nativescript-fabric) plugin, which provides a support for `fabric.io` in NativeScript application. 

In case you already using this plugin, could you provide some more info about the problem and your environment(CLI, node, modules versions)? It would also help if you provide some code samples.

**Comment by mikraus94** [comment]
I tried using nativescript-fabric.

I have nativescript 2.5.4, tns-core-modules 2.5.2 and nativescript-fabric 1.0.0

I've added meta data to android manifest, created fabric.json in project root and add import to modules and init fabric in main.ts.

While I'm trying to upload apk to crashlytics by fastlane, I'll get this error

WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/kraus/PhpstormProjects/bavic-buildserver/Exports/zlepsito.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/kraus/PhpstormProjects/bavic-buildserver/Exports/zlepsito.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

**Comment by tsonevn** [comment]
Hi @mikraus94,
Something that could be related to this problem. In case you are uploading APK from production, the above-mentioned error could be shown. Make sure that you are building the app in release mode while signing it and try to upload the signed APK file. More about building for release could be found [here](https://docs.nativescript.org/publishing/publishing-android-apps#build-signed-release-apk).
