### ISSUE TITLE
Request: migrate Switch component to use SwitchCompat on Android

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4438]
Please.

https://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html

**Comment by sserdyuk** [comment]
I am trying to get an interim solution for this by creating a custom component that extends standard Switch component and overrides the createNativeView method. It works, meaning that the app displays proper "material" switch on the screen, but I get a cryptic message in the console. It's unclear what else besides the message is not right. Any help with solving this would be appreciated.

```
import { Switch as BaseSwitch } from "ui/switch"; 
import { checkedProperty } from "ui/switch/switch-common"; 

// Have to redefine these as Switch module doesn't export these internal details

interface CheckedChangeListener {
    new (owner: Switch): android.widget.CompoundButton.OnCheckedChangeListener;
}

let CheckedChangeListener: CheckedChangeListener;

function initializeCheckedChangeListener(): void {
    if (CheckedChangeListener) {
        return;
    }

    @Interfaces([android.widget.CompoundButton.OnCheckedChangeListener])
    class CheckedChangeListenerImpl extends java.lang.Object implements android.widget.CompoundButton.OnCheckedChangeListener {
        constructor(private owner: Switch) {
            super();
            return global.__native(this);
        }

        onCheckedChanged(buttonView: android.widget.CompoundButton, isChecked: boolean): void {
            const owner = this.owner;
            checkedProperty.nativeValueChange(owner, isChecked);
        }
    }

    CheckedChangeListener = CheckedChangeListenerImpl;
}

// the override, no super needs to be called, as the method is completely replaced

export class Switch extends BaseSwitch {
    public createNativeView() {
        initializeCheckedChangeListener();
        // const nativeView = new android.widget.Switch(this._context);
        const nativeView = new android.support.v7.widget.SwitchCompat(this._context);
        const listener = new CheckedChangeListener(this);
        nativeView.setOnCheckedChangeListener(listener);
        (<any>nativeView).listener = listener;
        return nativeView;
    }
} 
```

```
W/System.err( 3678): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3678): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethod(Runtime.java:890)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethod(Runtime.java:874)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethod(Runtime.java:866)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3678): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethod(Runtime.java:890)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethod(Runtime.java:874)
W/System.err( 3678): 	at com.tns.Runtime.callJSMethod(Runtime.java:866)

```

**Comment by tsonevn** [comment]
Hi @sserdyuk,
This issue could be related to the way, how the `CheckedChangeListener` is extended in the code. 
To be able to extend properly the listener you could use `extend` method and create a new instance of it while setting it to the nativeView with `setOnCheckedChangeListener`. For example:
```
var listener = android.widget.CompoundButton.OnCheckedChangeListener.extend("a.b.testclass",{
        onCheckedChanged:function(buttonView, isChecked){
            console.log("onCheckedChanged");
            console.log("isChecked "+isChecked)
        }
    })
```

Something that I could suggest is to use the `Placehonder` component and on its `creatingView` method to initialize the newly created nativeView and its listener.

XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" class="btn btn-primary btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
        <Placeholder creatingView="creatingView"/>
    </StackLayout>
</Page>

```
TypeScript 
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import { CreateViewEventData } from "ui/placeholder";
// Event handler for Page "navigatingTo" event attached in main-page.xml
declare var android:any;
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;


    page.bindingContext = new HelloWorldModel();
}

export function creatingView(args: CreateViewEventData) {
    let nativeView = new android.support.v7.widget.SwitchCompat(args.context);
    
    var listener = android.widget.CompoundButton.OnCheckedChangeListener.extend("a.b.testclass",{
        onCheckedChanged:function(buttonView, isChecked){
            console.log("onCheckedChanged");
            console.log("isChecked "+isChecked)
        }
    })
    nativeView.setOnCheckedChangeListener(new listener());

    args.view = nativeView;
}
```

Regarding the request, I found that `SwitchCompat` requires API level 24 or higher and in my opinion this change will not be applicable for the users, which use some lower Androids API levels

**Comment by sserdyuk** [comment]
@tsonevn Thank you for the suggestion, I will try it. As for the API level required, you aren't correct. `SwitchCompat` is a part of the `android.support.v7` library that you're already using for things like ActionBar, and it's 7+ API compatible. It's a drop in replacement for the standard Switch component in the pre-21 APIs. See the link: https://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html

**Comment by tsonevn** [comment]
Hi @sserdyuk,
Yes, you are right the `SwitchCompat` is part of the `android.support.v7`. Regarding that, I will log this as a feature request and if it is applicable this change will be available for some of the next NativeScriptm versions.
