### ISSUE TITLE
Cryptic W/System.err error if calling a specific native Android API

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4471]
I am getting a cryptic error from the runtime, even though everything works as expected. The device is on API 19. I am using the compat library to get a better looking "material" widget on the screen. I have reduced this from a real application to a simple Placeholder component just to demonstrate the problem on a smallest possible setup. Note that even the error is shown in the logs, the function does return the drawable, and I can color it. I get the same message when I call getTrackDrawable(), but not when I call getTextOn(). Also, the issue is not present if I use android.widget.Switch instead (the commented out line in the code) Possibly connected with the type of result? The issue is present in both 3.0 and 3.1 versions.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>
    <StackLayout>
        <Placeholder loaded="loaded" creatingView="creatingView"/>
    </StackLayout>
</Page>

```

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { Color } from 'color';

import { CreateViewEventData } from "ui/placeholder";

export function creatingView(args: CreateViewEventData) {
    console.log("Creating view");
    const nativeView = new android.support.v7.widget.SwitchCompat(args.context);
    // const nativeView = new android.widget.Switch(args.context);
    args.view = nativeView;
}

export function loaded(args) {
    console.log("Loaded");
    let color = new Color("#FF0000");
    args.object.nativeView.getThumbDrawable().setColorFilter(color.android, android.graphics.PorterDuff.Mode.SRC_IN);
}
```

```
Successfully synced application org.nativescript.ThumbDrawable on device LGVS450PP3a1a880.
JS: Creating view
JS: Loaded
W/System.err( 9576): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 9576): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethod(Runtime.java:912)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethod(Runtime.java:896)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethod(Runtime.java:888)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 9576): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethod(Runtime.java:912)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethod(Runtime.java:896)
W/System.err( 9576): 	at com.tns.Runtime.callJSMethod(Runtime.java:888)
```

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.1.1           │ 3.1.1          │ Up to date    │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date    │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date    │
│ tns-ios          │                 │ 3.1.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by sserdyuk** [comment]
The test app is available at https://github.com/sserdyuk/ns-bug-4471

**Comment by NickIliev** [comment]
@sserdyuk the reason for your issue is problems with your references.d.ts file (it was misspelled.

So make the following changes and you application will work as expected.
- rename the file to `references.d.ts`
- the content of the above file should be as follows:
```
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" /> 
```
- in your `tsconfig.json` you should have the following content
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

Full application demonstrating the working project can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4471)

**Comment by sserdyuk** [comment]
Sorry @NickIliev , this all still doesn't cure the problem with the errors in the terminal. The updated test app is available at https://github.com/sserdyuk/ns-bug-4471

```
JS: Creating view
JS: Loaded
W/System.err(16260): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err(16260): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
W/System.err(16260): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
W/System.err(16260): 	at com.tns.Runtime.callJSMethod(Runtime.java:912)
W/System.err(16260): 	at com.tns.Runtime.callJSMethod(Runtime.java:896)
W/System.err(16260): 	at com.tns.Runtime.callJSMethod(Runtime.java:888)
W/System.err(16260): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err(16260): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
W/System.err(16260): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
W/System.err(16260): 	at com.tns.Runtime.callJSMethod(Runtime.java:912)
W/System.err(16260): 	at com.tns.Runtime.callJSMethod(Runtime.java:896)
W/System.err(16260): 	at com.tns.Runtime.callJSMethod(Runtime.java:888)

```

**Comment by NickIliev** [comment]
@sserdyuk I have tested your application and it runs fine on my side - however, I have tested on API25 as [this widget requires high API level](https://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html) and is not supported by the previous API levels.

**Comment by sserdyuk** [comment]
@NickIliev From that link:

> SwitchCompat is a version of the Switch widget which on devices back to API v7

 This widget only requires API level 7. You need to test it on the API < 21, in my case it's API 19.
