### ISSUE TITLE
callJSMethodNative error on launch after tns upgrade 

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/NativeScript#4502]
_From @marco-gagliardi on July 1, 2017 15:52_

After upgrading  to the latest tns stack version (3.1.1) I get the following error right after the application  is launched on my real device (Nexus 5x, Android 7.1.2, API 25):

```
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:912)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:896)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:888)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:912)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:896)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:888)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:912)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:896)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:888)

```

If I run the application on the Android emulator (Nexus 5x, API 26) I don't get any error

_Copied from original issue: NativeScript/nativescript-cli#2939_

**Comment by dtopuzov** [comment]
Hi @marco-gagliardi 

May be your Nexus5x use `arm` cpu, while usually emulators use `x86` cpu architecture.
Can you create `arm` based emulator and run your app there?

Can you also add some more details for your app:
- What plugins you have (or better post `pacakge.json` of the app)
- Do you use `webpack`, `snapshots`, `abi splits` or some other technique to optimize the app.
- Does it happens with both `debug` and `release` builds?
- Can you reproduce the same issue with hello-world application?

**Comment by dtopuzov** [comment]
_From @marco-gagliardi on July 3, 2017 21:48_

Hi @dtopuzov , 
I don't use anything that is not included and shipped along with NativeScript platform, except a couple of plugins as you can see in my  `package.json:`

```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.EstateRomana2017",
		"tns-android": {
			"version": "3.1.1"
		},
		"tns-ios": {
			"version": "3.1.0"
		}
	},
	"dependencies": {
		"@angular/animations": "~4.1.0",
		"@angular/common": "~4.1.0",
		"@angular/compiler": "~4.1.0",
		"@angular/core": "~4.1.0",
		"@angular/forms": "~4.1.0",
		"@angular/http": "~4.1.0",
		"@angular/platform-browser": "~4.1.0",
		"@angular/router": "~4.1.0",
		"nativescript-angular": "~3.0.0",
		"nativescript-geolocation": "^3.0.0",
		"nativescript-google-maps-sdk": "^2.3.0",
		"nativescript-theme-core": "~1.0.2",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.3.0",
		"tns-core-modules": "^3.1.0",
		"zone.js": "~0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "6.25.0",
		"babel-types": "6.25.0",
		"babylon": "6.17.4",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.4.0",
		"typescript": "~2.2.1"
	}
}

```
Quick update: the app actually doesn't crash anymore, it works properly both on the emulator and on my real device, but in the second case (only in the second case) the console still logs such sort of error when the phone is plugged to my computer. Some page use advanced components, such as TabView or Maps, but - can't be 100% sure about what I'm saying - that output apparently is only streamed when I navigate to one specific page: the homepage. So this happens the first time when the app is started and then everytime I navigated back to it. The homepage  is a really simple page though: 

```
<ActionBar title="Estate Romana 2017" class="action-bar myactionbar" android.icon="~/images/logo-roma.png" android.iconVisibility="always">
</ActionBar>
<GridLayout rows="*, auto" class="page">
    <StackLayout row="0">
        <ListView [items]="menu" class="list-group">
            <ng-template let-item="item">
                <StackLayout orientation="horizontal" class="list-group-item" [nsRouterLink]="['/'+item.link]" >
                    <GridLayout columns="50, *, auto" rows="auto" >
                        <Label text="{{ getIcon(item.icon) }}" class="icon" row="0" col="0"></Label>
                        <Label [text]="item.name" row="0" col="1"></Label>
                        <Label text="{{ getIcon('0xf105') }}" class="icon" row="0" col="2"></Label>
                    </GridLayout>
                </StackLayout>
            </ng-template>
        </ListView>
    </StackLayout>
    <GridLayout row="1">
        <Image src="~/images/footer-app_ER.jpg" stretch="aspectFill"></Image>
    </GridLayout>

</GridLayout>


```

**Comment by dtopuzov** [comment]
Hi @marco-gagliardi it looks like this issue is not related with CLI, so I'll move it to main repo (where we log issues related to tns-core-modules).

**Comment by NickIliev** [comment]
@marco-gagliardi from what method your logs are initialized?
Check if you are expecting them in a specific lifecycle method which is not triggered on some of the user actions. If possible please share the code-behind file where the logs are executed

**Comment by tsonevn** [comment]
closing due to inactivity

**Comment by deepak4u2006** [comment]
@tsonevn Its quite late but thought of sharing my experience
this below code gave me the same error in Tabview
`<StackLayout *tabItem="{title: 'Email',` iconSource: '~/icon.png'`}">
        <transferMail></transferMail>
    </StackLayout>`

I tried removing the ` iconSource: '~/icon.png'` and it worked, don't know the issue

**Comment by tsonevn** [comment]
Hi @deepak4u2006,
Make sure that you have provided the correct path to the Image for the `iconSource` property. IF the path is not valid the View could crash, when it tries to load the Image.

**Comment by RoyiNamir** [comment]
@tsonevn Hi yes

**Comment by tsonevn** [comment]
Hi @RoyiNamir,
I tested this scenario in the sample project, however, I am unable to recreate the issue. For your convenience, I am attaching the sample project, please review it and make the needed changes, which will allow us to recreate the problem.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1914995/Archive.zip)

Do you reproduce this issue in a newly created project or only on one that you have upgraded from 3.4 to 4.0?

**Comment by RoyiNamir** [comment]
@tsonevn I have an already project( (small one) which produce this along other messages ( which I referenced in another issue).: 


![image](https://user-images.githubusercontent.com/2842123/38809372-eae1c836-418b-11e8-8222-2ceb69314b8a.png)


However , I can't put it here in public. can you send an email so I can send it ?
namir dot 78 at gmail
