### ISSUE TITLE
HTTP and binary data - Response type of 'arraybuffer' not supported

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#4508]
_From @NickIliev on July 5, 2017 11:26_

When creating HTTP request that requres the response content type to be array buffer the request is not send and the application is throwing with
```
JS: ERROR Error: Uncaught (in promise): Error: Response type of 'arraybuffer' not supported.
JS: Error: Response type of 'arraybuffer' not supported.
JS:     at XMLHttpRequest.set [as responseType] (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/tns-core-modules/xhr/xhr.js:200:23) [angular]
JS:     at Observable._subscribe (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/http/bundles/http.umd.js:1269:43) [angular]
JS:     at Observable._trySubscribe (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/rxjs/Observable.js:57:25) [angular]
JS:     at Observable.subscribe (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/rxjs/Observable.js:45:27) [angular]
JS:     at ItemService.binaryRequest (file:///data/data/org.nativescript.t1117556ng/files/app/item/item.service.js:15:14) [angular]
JS:     at ItemsComponent.ngOnInit (file:///data/data/org.nativescript.t1117556ng/files/app/item/items.component.js:14:45) [angular]
JS:     at checkAndUpdateDirectiveInline (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/core/bundles/core.umd.js:10822:19) [angular]
JS:     at checkAndUpdateNodeInline (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/core/bundles/core.umd.js:12245:17) [angular]
JS:     at checkAndUpdateNode (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/core/bundles/core.umd.js:12184:16) [angular]
JS:     at debugCheckAndUpdateNode (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/core/bundles/core.umd.js:12887:59) [angular]
JS:     at debugCheckDirectivesFn (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/core/bundles/core.umd.js:12828:13) [angular]
JS:     at Object.eval [as updateDirectives] (ng:///AppModule/ItemsComponent_Host.ngfactory.js:10:5) [angular]
JS:     at Object.debugUpdateDirectives [as updateDirectives] (file:///data/data/org.nativescript.t1117556ng/files/app/tns_modules/@angular/core/bundles/core.umd.js:12813:21) [angular]
```

Use [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/others/t_1117556_ng) to reproduce (in Angular application) or the snippets below
```
binaryRequest() {
    let options = this.createOptionssAB();

    return this.http.get("https://httpbin.org/stream-bytes/55", options)
        .subscribe((res: Response) => {
            console.log("status: " + res.status);
            console.log("arrayBuffer: " + res.arrayBuffer);
            return res.arrayBuffer;
        })
}

private createOptionssAB() {
    let requestOptions = new RequestOptions();

    requestOptions.responseType = ResponseContentType.ArrayBuffer; // wiil work if this is set to ResponseContentType.Json

    return requestOptions;
}
```

Reported via t.1117556

_Copied from original issue: NativeScript/nativescript-angular#882_

**Comment by NickIliev** [comment]
Closing this as duplicate to [https://github.com/NativeScript/NativeScript/issues/570](https://github.com/NativeScript/NativeScript/issues/570)

**Comment by rynop** [comment]
Hi @NickIliev - is there a workaround for this?  I keep going down rabbit holes of https://github.com/NativeScript/NativeScript/issues/570 and can't seem to figure out if there is one.

Is using the native http lib like so one way to get around this?

`const httpModule = require("http");`

I'm trying to get protobuf working via protobufjs.  I'm using the Angular flavor of NS. I don't care which http lib I use really..
