### ISSUE TITLE
Error during tns run android in emulator

### ISSUE THREAD

**Issue by gtzinos** [NativeScript/NativeScript#4515]
Hi,
i am trying to run my app into an emulator but after the install the app runs correctly inside the emulator the console returns this error message:

Error: watch /home/geotzinos/myapp/app/README.md ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:473:21)

**Comment by gtzinos** [comment]
I restarted the ubuntu machine and now it working again.. I thought that the restart was a feature of windows.

**Comment by gtzinos** [comment]
A new error message

Error: watch /home/geotzinos/myapp/app/App_Resources/iOS/build.xcconfig ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by gtzinos** [comment]
A different error message after each tns run android

Error: watch /home/geotzinos/myapp/app/App_Resources/Android/drawable-mdpi ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/geotzinos/.nvm/versions/node/v6.11.0/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by gtzinos** [comment]
Solution: https://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc
