### ISSUE TITLE
tns run android Error

### ISSUE THREAD

**Issue by zhyilong** [NativeScript/NativeScript#4528]
D:\NSCalculator>tns run android --emulator

Support for Node.js 8.1.2 is not verified. This CLI might not install or run properly.

Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
Executing before-liveSync hook from D:\NSCalculator\hooks\before-liveSync\nativescript-angular-sync.
js
Executing before-prepare hook from D:\NSCalculator\hooks\before-prepare\nativescript-dev-typescript.
js
Found peer TypeScript 2.2.2
Preparing project...
Downloading https://services.gradle.org/distributions/gradle-3.3-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDe
legateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHtt
psURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.j
ava:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
        at org.gradle.wrapper.Download.download(Download.java:45)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Unable to apply changes on device: emulator-5554. Error is: Processing node_modules failed. Error: C
ommand gradlew.bat failed with exit code 1.

**Comment by dtopuzov** [comment]
Hi @zhyilong 

From what I see you have `node8` on you machine, which is not yet officially supported.

Can you please add steps to reproduce the problem, for example:
```
tns create TestApp
<some other steps>
tns run android --path TestApp
```
Please also post CLI version and package.json of your project.

From what I see it fails when it downloads gradlew from internet.

**Comment by Pip3r4o** [comment]
@zhyilong by the looks of it, your connection timed out. This can be caused by poor connection, or if you are behind a proxy that restricts the network access.

There is a workaround for the latter, let me know if that's the case.

**Comment by zhyilong** [comment]
hello ，
		I want to know how to pick up the native third party SDK；
		How does iOS call Objective-C; how does Android call Java?

**Comment by zhyilong** [comment]
hello.

I run on MAC computer

this is my bash_profile

#mysql
export PATH=${PATH}:/usr/local/mysql/bin

#java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home 
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/zhangyilong/.sdkman"
[[ -s "/Users/zhangyilong/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/zhangyilong/.sdkman/bin/sdkman-init.sh"

#android
export ANDROID_HOME=/Users/zhangyilong/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

#gradle
export GRADLE_HOME=/Users/zhangyilong/Library/Android/gradle-2.4
export PATH=${PATH}:${GRADLE_HOME}/bin
export ANDROID_HOME=/usr/local/Caskroom/android-sdk/3859397
export JAVA_HOME=/Library/Java/Home


tns run android --emulator

Support for Node.js 8.1.3 is not verified. This CLI might not install or run properly.

Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.

**Comment by Pip3r4o** [comment]
Hey @zhyilong, could you be more specific? Which third party native SDK do you want to use in your code? Normally adding a dependency to one in your `app/App_Resources/Android/app.gradle` is sufficient to start consuming it through JavaScript/TypeScript. 

There are several articles on our official documentation site that you may find helpful. Here are just a few:
https://docs.nativescript.org/runtimes/android/marshalling/java-to-js
https://docs.nativescript.org/tutorial/chapter-6#62-deleting-from-a-list---android
https://docs.nativescript.org/runtimes/android/metadata/accessing-packages
https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries

**Comment by zhyilong** [comment]
hello,
		We want to access some picture processing SDK; third party push SDK.
                These SDK are platform native implementation. thank you.

**Comment by zhyilong** [comment]
hello,
		For example, how do you call UIViewController on iOS, and how to call Activity on Android?
		thank you.

**Comment by zhyilong** [comment]
hello.

		We want to access some picture processing SDK; third party push SDK.
                These SDK are platform native implementation. 

		For example, how do you call UIViewController on iOS, and how to call Activity on Android?
		thank you.

**Comment by PetyaSotirova** [comment]
Hi @zhyilong,
As we try to keep the GitHub issues section strictly for features and issues, please direct questions about how you can use the framework to one of the community channels like the forums: https://discourse.nativescript.org/. Additionally to the resources @Pip3r4o recommended above, I'd suggest taking a look at this article: https://docs.nativescript.org/runtimes/ios/types/ObjC-Classes.   

Could you let us know whether you resolved the original issue reported here?

**Comment by NickIliev** [comment]
Hey, @zhyilong we haven't heard from you for a while - closing the issue due to inactivity but please do let us know if you need further assistance!

**Comment by King-Ran** [comment]
@zhyilong  me too ,i have the error . l see the issues , but l don`t find Solution . can you tell why? i should to do ?  email : 924007244@qq.com

**Comment by zhyilong** [comment]
最终没有用NativeScript，用了react-native

发自我的 iPhone

**Comment by Pip3r4o** [comment]
@King-Ran could you be more specific, and describe in detail what you are doing, and what the end result is? 

Best open a new issue, fill out the template, which should give us enough information to start somewhere, so that we can help you.

Thank you!
