### ISSUE TITLE
Error while parsing debug 'response' object

### ISSUE THREAD

**Issue by nmandyam** [NativeScript/NativeScript#4559]
Hello, debugger.js is failing as below when running on Windows 10, nativescript 3.1.2, tns-core-modules 3.1.0, tns-android 3.1.1. I can't seem to pinpoint the exact location where the crash happens, unfortunately.
Here's the fragment of error-display I could  get from my emulator:
-------------------------------
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onComplete failed

Error: Error while parsing debug `response` object. mimeType: string value expected
File: "file:///data/data/com.dftly.v4skiosk/files/app/tns_modules/tns-core-modules/debugger/debugger.js, line: 30, column: 27

StackTrace: 
	Frame: function:'responseReceived', file:'', line: 30, column: 28
	Frame: function:'onRequestComplete', file:'', line: 60, column: 33
	Frame: function:'onComplete', file:'', line: 37, column: 13

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
	at com.tns.Runtime.callJSMethod(Runtime.java:912)
	at com.tns.Runtime.callJSMethod(Runtime.java:896)
	at com.tns.Runtime.callJSMethod(Runtime.java:888)
	at com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
	at org.nativescript.widgets.Async$Http$HttpRequ
-------------------------------
I am  running a local node server, so I tried Josh Comley's suggestion [here](https://github.com/NativeScript/NativeScript/issues/4419) to no avail - still crashes in the same manner. Of course, app works OK if I'm not connected to the debugger.

### Which platform(s) does your issue occur on?

Windows running a Genymotion Android emulator

### Please provide the following version numbers that your issue occurs with:

Windows 10, nativescript 3.1.2, tns-core-modules 3.1.0, tns-android 3.1.1

I could provide a code-extract,  if that's needed.

**Comment by NickIliev** [comment]
@nmandyam keep in mind that if you are using VSCode extension for debugging or iOS Chrome DevTOols you won't be able to debug network related operations (as stated [here](http://docs.nativescript.org/tooling/chrome-devtools#chrome-devtools-debugging))

**Comment by nmandyam** [comment]
@NickIliev No, I'm not using the VSCode extension and I'm running on Windows.

**Comment by NickIliev** [comment]
@nmandyam is it possible to provide sample project demonstrating the issue?

**Comment by tsonevn** [comment]
closing due to inactivity, if the problem still persists, please provide a sample project and I will reopen the issue.

**Comment by nmandyam** [comment]
Sorry, I should have responded: Josh Comley's suggestion DID work. Thanks!
