### ISSUE TITLE
Error message during http request

### ISSUE THREAD

**Issue by gtzinos** [NativeScript/NativeScript#4570]
### Tell us about the problem
Hi, i am using nativescript and when i try to send an http request it returns a strange error message.

### Which platform(s) does your issue occur on?
Both

### Stacktrace ###
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onComplete failed

Error: Error while parsing debug `response` object. mimeType: string value expected
File: "file:///data/data/org.nativescript.LookAndFind/files/app/tns_modules/tns-core-modules/debugger/debugger.js, line: 30, column: 27

StackTrace: 
	Frame: function:'responseReceived', file:'', line: 30, column: 28
	Frame: function:'onRequestComplete', file:'', line: 60, column: 33
	Frame: function:'onComplete', file:'', line: 37, column: 13

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
	at com.tns.Runtime.callJSMethod(Runtime.java:912)
	at com.tns.Runtime.callJSMethod(Runtime.java:896)
	at com.tns.Runtime.callJSMethod(Runtime.java:888)
	at com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
	at org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
	at org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by NickIliev** [comment]
@gtzinos can you provide the code that you are using to make the HTTP request?

**Comment by tsonevn** [comment]
closing due to inactivity. If the problem still exists please provide a sample project and if it is a real problem in the modules I will reopen it.

**Comment by gtzinos** [comment]
I am facing this error message when the response doesn't return (cause the server is down).

**Comment by NickIliev** [comment]
@gtzinos when the server is down you should receive different status code (not 2xx but 5xx) - can you please provide the code snippet used to send the request, Also keep in mind that you can not debug HTTP requests (this is limitation of the debug workflow)

**Comment by Nogostradamus** [comment]
Hi, I have the same issue here. I tested my post endpoint with postman and it's working fine. Not from nativescript. I got an error instead. When using debug I see the same error as in this issue.
I'm debugging on windows chrome.
My code is like that:
`create(){
        console.log(this.input.name, this.input.dob, this.input.user, this.input.relation);
        this.babyService.createBaby(this.input).subscribe(
            baby => {
                (new SnackBar()).simple("Baby Created");
                this.goBack();
            },
            error => {
                (new SnackBar()).simple("Error. Please try again.");
            });
    }`
and service:
`createBaby(input) {
        let body = {
            name: input.name,
            dob: input.dob,
            owner: input.user,
            relation: input.relation
        };
        this.getAuthHeaders();
        return this.http.post(this.base_url + "babies/create_baby/", body, this.authOptions)
            .map(this.extractData)
            .catch(this.handleError);
    }
private getAuthHeaders() {
        this.token = ApplicationSettings.getString("bjToken", '');
        this.authHeaders = new Headers({'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Token '+ this.token});
        this.authOptions = new RequestOptions({headers: this.authHeaders});
    }
    private extractData(res: Response) {
        return res.json() || {};
    }
    private handleError(error: any) {
        return Observable.throw(error);
    }
`
