### ISSUE TITLE
Error during deploying the simple app on android 

### ISSUE THREAD

**Issue by SubhaPrince** [NativeScript/NativeScript#4605]
subha@subha-ubuntu:~/projects/HelloWorld$  tns run android
Searching for devices...
Skipping prepare.
Installing...
Successfully installed on device with identifier '57da5186'.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.HelloWorld on device 57da5186.
Executing before-watch hook from /home/subha/projects/HelloWorld/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
fs.js:1373
    throw error;
    ^

Error: watch /home/subha/projects/HelloWorld ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1371:19)
    at Object.fs.watch (fs.js:1397:11)
    at Object.watchDirectory (/home/subha/projects/HelloWorld/node_modules/typescript/lib/tsc.js:2377:32)
    at Object.executeCommandLine (/home/subha/projects/HelloWorld/node_modules/typescript/lib/tsc.js:53355:43)
    at Object.<anonymous> (/home/subha/projects/HelloWorld/node_modules/typescript/lib/tsc.js:53712:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

TypeScript compiler failed with exit code 1

**Comment by tsonevn** [comment]
Hi @SubhaPrince,
Please provide some more info about your problem and your environment(CLI, node, modules versions). Also, you could send us sample project, where this issue could be debugged locally on our side?

**Comment by tsonevn** [comment]
closing due to inactivity.
