### ISSUE TITLE
can't update project

### ISSUE THREAD

**Issue by runbb** [NativeScript/NativeScript#4623]
on `tns update` or `tns install`

`tns` version = `3.1.3`
`tns-core-modules` version = `3.1.0`
`node` version = `6.11.1` `LTS`
```
> nativescript-angular@3.0.0 postinstall /home/xlmnxp/Documents/Nativescript/nproject/node_modules/nativescript-angular
> node postinstall.js

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/xlmnxp/Documents/Nativescript/nproject/hooks/before-livesync/nativescript-angular-sync.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at Object.<anonymous> (/home/xlmnxp/Documents/Nativescript/nproject/node_modules/nativescript-angular/postinstall.js:16:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by runbb** [comment]
FIXED
im remove hooks folder and problem fixed
```sh
rm -rf hooks/
```
