### ISSUE TITLE
Genymotion and linux

### ISSUE THREAD

**Issue by Rombersoft** [NativeScript/NativeScript#4692]
Hi guys! I've decide to try your masterpiece. I like genymotion android emulator and Linux OS.
So I've installed latest version genymotion and tried run application by next command:

destructor@Toshiba-Satellite-C660:/media/destructor/Documents/Projects/Android/HelloWorld$ tns run android --emulator

And got error:

Searching for devices...
Copying template files...
  ◝ Installing tns-androidInstalling  tns-android
/media/destructor/Documents/Projects/Android/HelloWorld
└── tns-android@3.1.1 

  ◞ Installing tns-android/media/destructor/Documents/Projects/Android/HelloWorld
└─┬ babel-traverse@6.25.0 
  ├─┬ babel-code-frame@6.22.0 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.1.1 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├── esutils@2.0.2 
  │ └── js-tokens@3.0.2 
  ├── babel-messages@6.23.0 
  ├─┬ babel-runtime@6.25.0 
  │ ├── core-js@2.5.0 
  │ └── regenerator-runtime@0.10.5 
  ├─┬ babel-types@6.25.0 
  │ └── to-fast-properties@1.0.3 
  ├── babylon@6.17.4 
  ├─┬ debug@2.6.8 
  │ └── ms@2.0.0 
  ├── globals@9.18.0 
  ├─┬ invariant@2.2.2 
  │ └── loose-envify@1.3.1 
  └── lodash@4.17.4 

/media/destructor/Documents/Projects/Android/HelloWorld
└── babel-types@6.25.0 

/media/destructor/Documents/Projects/Android/HelloWorld
└── babylon@6.17.4 

/media/destructor/Documents/Projects/Android/HelloWorld
└── lazy@1.0.11 

Project successfully created.
Preparing project...
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Downloading https://services.gradle.org/distributions/gradle-3.3-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 20 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 26 more
Unable to apply changes on device: 192.168.57.101:5555. Error is: Command ./gradlew failed with exit code 1.
destructor@Toshiba-Satellite-C660:/media/destructor/Documents/Projects/Android/HelloWorld$ 

Can you explain me where I've done mistake and how to run application into genymotion emulator?

**Comment by dtopuzov** [comment]
Hi @Rombersoft

I think the problem is not related to Genymotion, it sounds like [this](https://stackoverflow.com/questions/29584328/gradlew-bat-and-gradlew-sslhandshakeexception).

Do you have some proxy?
Can you please also specify your java version?

**Comment by Rombersoft** [comment]
Thanks it has really helped me!
