### ISSUE TITLE
Unexpected token   in JSON at position 0 in npm i -g nativeScript

### ISSUE THREAD

**Issue by VentsislavDinev** [NativeScript/NativeScript#4878]
Hello, i try to install NativeScript but i have this problem: 
"C:\>tns
Unexpected token   in JSON at position 0
Failed to display command help SyntaxError: Unexpected token   in JSON at position 0
    at Object.parse (native)
    at FileSystem.readJson (C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:171:25)
    at UserSettingsService.<anonymous> (C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:92:46)
    at next (native)
    at C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:7:71
    at __awaiter (C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:3:12)
    at UserSettingsService.loadUserSettingsData (C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:82:16)
    at UserSettingsService.<anonymous> (C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\services\user-settings-service.js:20:24)
    at next (native)
    at C:\Users\**\AppData\Roaming\npm\node_modules\nativescript\lib\services\user-settings-service.js:7:71
Error while reporting exception: SyntaxError: Unexpected token   in JSON at position 0" 
Please help for fix this problem.

**Comment by paceair** [comment]
probably due to empty content in user-settings.json at 
c:\Users\xxxxxxx\AppData\Roaming\.nativescript-cli

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3131
