### ISSUE TITLE
Android tns debug, crashing when there is a response from server

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#4996]
```System.err: com.tns.NativeScriptException:
System.err: Calling js method onComplete failed
System.err:
System.err: Error: Response not found for requestId = 2
System.err: File: "file:///data/data/com.anygofitness.anygopartner/files/app/tns_modules/tns-core-modules/debugger/debugger.js, line: 71, column: 27
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'responseReceived', file:'', line: 71, column: 28
System.err: 	Frame: function:'onRequestComplete', file:'', line: 60, column: 33
System.err: 	Frame: function:'onComplete', file:'', line: 37, column: 13
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
System.err: 	at org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
System.err: 	at org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
ActivityManager: Process com.anygofitness.anygopartner (pid 5414) has died
ActivityManager: cleanUpApplicationRecord -- 5414
^CExecuting after-watch hook from /Users/shiv19/Work/AnyGo/apps/partner/hooks/after-watch/nativescript-dev-sass.js
Stopping sass watch
```

This part of the app works totally fine when not running in debug mode.
This could be an issue with the debugger

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3187
