### ISSUE TITLE
Don't compile with 'angular2-token' package

### ISSUE THREAD

**Issue by betosalvador** [NativeScript/NativeScript#5056]
## Please, provide the details below:
Hello, I'm trying to use the 'Angular2-Token' package in my nativescript app, but its doesn't compile.

I'm getting this error bellow:

```
Preparing project...
Project successfully prepared (Android)
Successfully transferred app.routing.ts.
Successfully transferred app.routing.js.
Refreshing application...
Successfully synced application org.nativescript.testeangular2token on device 192.168.128.101:5555.
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err: Error calling module function
System.err: Error calling module function
System.err: Error calling module function
System.err: Error calling module function
System.err: Cannot compile /data/data/org.nativescript.testeangular2token/files/app/tns_modules/angular2-token/lib/angular2-token.service.js
System.err: SyntaxError: Unexpected token import
System.err: File: "file:///data/data/org.nativescript.testeangular2token/files/app/tns_modules/angular2-token/lib/angular2-token.service.js, line: 1, column: 60
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/tns_modules/angular2-token/angular2-token.js', line: 5, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/app.routing.js', line: 7, column: 24
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/app.module.js', line: 5, column: 21
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:530)
System.err:     at com.tns.Runtime.run(Runtime.java:522)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
System.err:     ... 9 more

```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: (package.json)
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.testeangular2token",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "angular2-token": "^0.2.0-beta.12",
    "nativescript-angular": "~4.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.2.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.4.2"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
1- Generate a new tns app with ng template
2- Install angular2-token package (npm install angular2-token --save)
3- Add 'Angular2TokenService' to AppModule providers arrary
4- Run app (tns run android)

THanks in advance

**Comment by jogboms** [comment]
@betosalvador It appears the plugin still contains ES6 code.

**Comment by betosalvador** [comment]
Hello, @jogboms 

thanks for response.

Can you give a tip how to fix this?

thanks in advance

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1084
