### ISSUE TITLE
Application crash when users switch applications on navigation

### ISSUE THREAD

**Issue by abnervr** [NativeScript/NativeScript#5066]
# Please, provide the details below:

### Tell us about the problem
During navigation if the user interrupts the loading by  switching to another applications, the app crash on resumeActivity.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): 3.2.0
<details closed>
<summary> Calling js method onStart failed. TypeError: Cannot read property 'getVisibility' of undefined </summary>

```
System.err: java.lang.RuntimeException: Unable to resume activity {me.tegra.xxxx/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onStart failed
System.err: TypeError: Cannot read property 'getVisibility' of undefined
System.err: File: "file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 259, column: 55
System.err: StackTrace: 
System.err: 	Frame: function:'View.(anonymous function)', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 259, column: 56
System.err: 	Frame: function:'applyAllNativeSetters', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 969, column: 95
System.err: 	Frame: function:'initNativeView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 899, column: 9
System.err: 	Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 539, column: 22
System.err: 	Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 207, column: 18
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 184, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'Page.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 105, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'FrameBase.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 385, column: 13
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 640, column: 22
System.err: 	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 26, column: 25
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3121)
System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onStart failed
System.err: TypeError: Cannot read property 'getVisibility' of undefined
System.err: File: "file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 259, column: 55
System.err: StackTrace: 
System.err: 	Frame: function:'View.(anonymous function)', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 259, column: 56
System.err: 	Frame: function:'applyAllNativeSetters', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 969, column: 95
System.err: 	Frame: function:'initNativeView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 899, column: 9
System.err: 	Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 539, column: 22
System.err: 	Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 207, column: 18
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 184, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'Page.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 105, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 190, column: 19
System.err: 	Frame: function:'FrameBase.eachChildView', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 385, column: 13
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
System.err: 	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 189, column: 14
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 185, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err: 	Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 640, column: 22
System.err: 	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/me.tegra.xxxx/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 26, column: 25
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err: 	at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
System.err: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1260)
System.err: 	at android.app.Activity.performStart(Activity.java:6261)
System.err: 	at android.app.Activity.performRestart(Activity.java:6307)
System.err: 	at android.app.Activity.performResume(Activity.java:6312)
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
System.err: 	... 8 more
ActivityManager: Process (pid 27275) has died
ActivityManager: cleanUpApplicationRecord -- 27275
```

</details>

### Please tell us how to recreate the issue in as much detail as possible.
Switch to another application during back navigation.

**Comment by tsonevn** [comment]
Hi @abnervr,
I tested your scenario on my side on the sample project, however, was unable to recreate this behavior, while using latest NativeScript 3.3.
For your convenience, I am attaching sample project, please review it and make the needed changes, which will help us to recreate the problem.

Thank you in advance for your cooperation
![screencast 2017-11-13 at 5 53 35 pm](https://user-images.githubusercontent.com/17448734/32735012-49e815c4-c89c-11e7-97f9-de81619741cc.gif)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1467509/Archive.zip)

**Comment by NickIliev** [comment]
@abnervr let us know if you have a sample project to reproduce the issue locally so we could investigate your specific case. Closing this one but if you are still experiencing trouble do let me know.
