### ISSUE TITLE
getting  Invalid provider - only instances of Provider and Type are allowed, got: [object Object]

### ISSUE THREAD

**Issue by chauhan-saurabh** [NativeScript/NativeScript#5083]
```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]
System.err: File: "file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 2118, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
System.err:     Frame: function:'invalidProviderError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 1317, column: 12
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2118, column: 19
System.err:     Frame: function:'_normalizeProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2107, column: 15
System.err:     Frame: function:'resolveReflectiveProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2058, column: 39
System.err:     Frame: function:'ReflectiveInjector.resolve', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2287, column: 16
System.err:     Frame: function:'ReflectiveInjector.resolveAndCreate', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2319, column: 79
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4357, column: 51
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'platformNativeScriptDynamic', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/platform.js', line: 41, column: 62
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/main.js', line: 44, column: 12
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
System.err:     Frame: function:'invalidProviderError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 1317, column: 12
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2118, column: 19
System.err:     Frame: function:'_normalizeProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2107, column: 15
System.err:     Frame: function:'resolveReflectiveProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2058, column: 39
System.err:     Frame: function:'ReflectiveInjector.resolve', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2287, column: 16
System.err:     Frame: function:'ReflectiveInjector.resolveAndCreate', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2319, column: 79
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4357, column: 51
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'platformNativeScriptDynamic', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/platform.js', line: 41, column: 62
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/main.js', line: 44, column: 12
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]
System.err: File: "file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 2118, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
System.err:     Frame: function:'invalidProviderError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 1317, column: 12
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2118, column: 19
System.err:     Frame: function:'_normalizeProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2107, column: 15
System.err:     Frame: function:'resolveReflectiveProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2058, column: 39
System.err:     Frame: function:'ReflectiveInjector.resolve', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2287, column: 16
System.err:     Frame: function:'ReflectiveInjector.resolveAndCreate', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2319, column: 79
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4357, column: 51
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'platformNativeScriptDynamic', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/platform.js', line: 41, column: 62
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/main.js', line: 44, column: 12
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
System.err:     Frame: function:'invalidProviderError', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 1317, column: 12
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2118, column: 19
System.err:     Frame: function:'_normalizeProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2107, column: 15
System.err:     Frame: function:'resolveReflectiveProviders', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2058, column: 39
System.err:     Frame: function:'ReflectiveInjector.resolve', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2287, column: 16
System.err:     Frame: function:'ReflectiveInjector.resolveAndCreate', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 2319, column: 79
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4357, column: 51
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4354, column: 17
System.err:     Frame: function:'platformNativeScriptDynamic', file:'file:///data/data/org.nativescript.shyft/files/app/tns_modules/nativescript-angular/platform.js', line: 41, column: 62
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.shyft/files/app/main.js', line: 44, column: 12
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:530)
System.err:     at com.tns.Runtime.run(Runtime.java:522)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
System.err:     ... 8 more
ActivityManager: Process org.nativescript.shyft (pid 8400) has died: fore TOP
```

**Comment by NickIliev** [comment]
@chauhan-saurabh please provide a detailed explanation of how you are hitting this error including the code involved. The error is most likely related to the way you are using the Angular providers and services - make sure you are following the guidelines [here ](https://docs.nativescript.org/angular/core-concepts/angular-bootstrap#advanced-bootstrap)and [here](https://angular.io/guide/testing#the-overridecomponent-method). If you are still experiencing this issue please provide a sample project that reproduces the issue and also step-by-step explanation on how to reproduce the whole case.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1094
