### ISSUE TITLE
 Could not locate the Gradle launcher

### ISSUE THREAD

**Issue by Hesamp** [NativeScript/NativeScript#5188]
I got into a new problem

```

$ tns run android
Searching for devices...
Skipping prepare.
Building project...
Gradle build...
Exception in thread "main" java.lang.RuntimeException: Could not locate the Gradle launcher JAR in Gradle distribution 'C:\Users\Hesam-D\.gradle\wrapper\dists\gradle-3.3-bin\64bhckfm0iuu9gap9hg3r7ev2\gradle-3.3'.
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:43)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

Project dir from hooksArgs is: 
Hooks directories: [ 'C:\\Users\\Hesam-D\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\hooks',
  'C:\\Users\\Hesam-D\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\hooks',
  'D:\\By me\\mobile-app\\hooks' ]
AfterHookName for command watch is after-watch
Project dir from hooksArgs is: D:\mobile-app.
Hooks directories: [ 'C:\\Users\\Hesam-D\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\hooks',
  'C:\\Users\\Hesam-D\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\hooks',
  'D:\\By me\\mobile-app\\hooks' ]
AfterHookName for command liveSync is after-liveSync
```

**Comment by Pip3r4o** [comment]
@Hesamp delete the `C:\Users\Hesam-D\.gradle\wrapper\` directory, and give it another try.

**Comment by Pip3r4o** [comment]
@Hesamp were you able to run an android project successfully on the workstation?

**Comment by Hesamp** [comment]
@Pip3r4o 
yes , I downloaded the zipped file version 3.3 earlier.
And run without problems
