### ISSUE TITLE
Bundling with Webpack error 

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5299]
### Tell us about the problem
Hello guys I tried bundling my app with webpack to minify it, and to reduce it size
I followed this tutorial:
[Webpack tutorial](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)
But when I run 
`tns run android --bundle`
I get a lot of errors 
but when I run it normaly with 
`tns run android`
app is working fine what could be the problem
when running it with webpack I posted
output from console bellow????

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1

### Is there code involved? 
```

ActivityManager: Start proc 4329:com.hello.marko/u0a200 for activity at.banet.alarmbot/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: global.registerWebpackModules is not a function
System.err: File: "file:///data/data/com.hello.marko/files/app/vendor.js, line: 31349, column: 7
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'module.exports.map../app.css', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 31349, column: 8
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/com.hello.marko/app/vendor.js', line: 53, column: 30
System.err: 	Frame: function:'module.exports.Object.defineProperty.value', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 108, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 111, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/starter.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: global.registerWebpackModules is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'module.exports.map../app.css', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 31349, column: 8
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 53, column: 30
System.err: 	Frame: function:'module.exports.Object.defineProperty.value', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 108, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 111, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/at.banet.alarmbot/files/app/starter.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: global.registerWebpackModules is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'module.exports.map../app.css', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 31349, column: 8
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 53, column: 30
System.err: 	Frame: function:'module.exports.Object.defineProperty.value', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 108, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 111, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/starter.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
System.err: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: global.registerWebpackModules is not a function
System.err: File: "file:///data/data/com.hello.marko/files/app/vendor.js, line: 31349, column: 7
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'module.exports.map../app.css', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 31349, column: 8
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 53, column: 30
System.err: 	Frame: function:'module.exports.Object.defineProperty.value', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 108, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 111, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/starter.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: global.registerWebpackModules is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'module.exports.map../app.css', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 31349, column: 8
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/at.banet.alarmbot/files/app/vendor.js', line: 53, column: 30
System.err: 	Frame: function:'module.exports.Object.defineProperty.value', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 108, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 111, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/starter.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: global.registerWebpackModules is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'module.exports.map../app.css', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 31349, column: 8
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 53, column: 30
System.err: 	Frame: function:'module.exports.Object.defineProperty.value', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 108, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/vendor.js', line: 111, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.hello.marko/files/app/starter.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:530)
System.err: 	at com.tns.Runtime.run(Runtime.java:522)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
System.err: 	... 8 more
ActivityManager:   Force finishing activity at.banet.alarmbot/com.tns.NativeScriptActivity
ActivityManager: Activity pause timeout for ActivityRecord{a9bbd02 u0 at.banet.alarmbot/com.tns.NativeScriptActivity t1735 f}
ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity} from uid 0 on display 0
ActivityManager:   Force finishing activity com.hello.marko/com.tns.NativeScriptActivity
ActivityManager: Killing 4329:com.hello.marko/u0a200 (adj 900): crash
ActivityManager: cleanUpApplicationRecord -- 4329
ActivityManager: Displayed com.google.android.apps.nexuslauncher/.NexusLauncherActivity: +2s13ms
ActivityManager: Killing 3580:com.android.mtp/u0a11 (adj 906): empty #17
ActivityManager: cleanUpApplicationRecord -- 3580
ActivityManager:   Force finishing activity com.google.android.apps.nexuslauncher/.NexusLauncherActivity
ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity} from uid 0 on display 0
ActivityManager: Killing 2068:com.google.android.apps.nexuslauncher/u0a20 (adj 0): crash
ActivityManager: cleanUpApplicationRecord -- 2068
ActivityManager: Start proc 4756:com.google.android.apps.nexuslauncher/u0a20 for activity com.google.android.apps.nexuslauncher/.NexusLauncherActivity
ActivityManager: Spurious death for ProcessRecord{de1189c 0:com.google.android.apps.nexuslauncher/u0a20}, curProc for 2068: null
ActivityManager: Killing 3341:com.google.android.talk:matchstick/u0a56 (adj 906): empty #17
ActivityManager: cleanUpApplicationRecord -- 3341
ActivityManager: Displayed com.google.android.apps.nexuslauncher/.NexusLauncherActivity: +1s424ms
```

**Comment by NickIliev** [comment]
@markomiljkovic what is the version of nativescript-dev-webpack in your project?
make sure you are using the latest and comply the requirements described [in the migration guide](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) - make sure that you have `webpack-config.js` file.

If needed save your custom settings delete the `webpack.config.js` and `vendor.ts` (should look like [this one](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/vendor.ts#L1-L6)) and install nativescript-dev-webpack with `npm i nativescript-dev-webpack@latest --save-dev` which will generate new webpack and vendor files..

If you are still experiencing troubles with bundling the code you can contact me at the community slack channels (username: **niliev**) and send me the project to invastigate the issue locally.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#412
