### ISSUE TITLE
Calling js method onStart failed

### ISSUE THREAD

**Issue by tanmayparmar** [NativeScript/NativeScript#5409]
## Please, provide the details below:
I tried different things but after updating my project to the latest packages i am getting lots of the errors. 
### Tell us about the problem
I tried different things but after updating my project to the latest packages i am getting lots of the errors. 
### Which platform(s) does your issue occur on?
Android/

my tns version is 3.4.2.
Below is the error message I am getting. 
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.DemoAPL/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onStart failed
System.err:
System.err: Error: Could not resolve most-wickets-list.component.html. Looked for: /data/data/org.nativescript.DemoAPL/files/app/most-wickets-list.component.html.
System.err: File: "file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/resource-loader.js, line: 33, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 994, column: 33
System.err:     Frame: function:'FileSystemResourceLoader.resolve', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/resource-loader.js', line: 33, column: 19
System.err:     Frame: function:'FileSystemResourceLoader.get', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/resource-loader.js', line: 19, column: 33
System.err:     Frame: function:'DirectiveNormalizer._fetch', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 3186, column: 43
System.err:     Frame: function:'DirectiveNormalizer._preParseTemplate', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 3241, column: 29
System.err:     Frame: function:'DirectiveNormalizer.normalizeTemplate', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 3221, column: 36
System.err:     Frame: function:'CompileMetadataResolver.loadDirectiveMetadata', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 14950, column: 75
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34454, column: 72
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34453, column: 72
System.err:     Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34450, column: 75
System.err:     Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34408, column: 36
System.err:     Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34302, column: 37
System.err:     Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 270, column: 49
System.err:     Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 5601, column: 25
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/platform-common.js', line: 71, column: 66
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/platform-common.js', line: 144, column: 21
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err:     Frame: function:'PageBase.onNavigatingTo', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 118, column: 14
System.err:     Frame: function:'FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 357, column: 37
System.err:     Frame: function:'FrameBase.performNavigation', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 329, column: 14
System.err:     Frame: function:'FrameBase._processNextNavigationEntry', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 322, column: 22
System.err:     Frame: function:'Frame._processNextNavigationEntry', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 86, column: 58
System.err:     Frame: function:'FrameBase.onLoaded', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 137, column: 14
System.err:     Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 640, column: 22
System.err:     Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 26, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
System.err:     at android.app.ActivityThread.-wrap14(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6823)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onStart failed
System.err:
System.err: Error: Could not resolve most-wickets-list.component.html. Looked for: /data/data/org.nativescript.DemoAPL/files/app/most-wickets-list.component.html.
System.err: File: "file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/resource-loader.js, line: 33, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 994, column: 33
System.err:     Frame: function:'FileSystemResourceLoader.resolve', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/resource-loader.js', line: 33, column: 19
System.err:     Frame: function:'FileSystemResourceLoader.get', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/resource-loader.js', line: 19, column: 33
System.err:     Frame: function:'DirectiveNormalizer._fetch', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 3186, column: 43
System.err:     Frame: function:'DirectiveNormalizer._preParseTemplate', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 3241, column: 29
System.err:     Frame: function:'DirectiveNormalizer.normalizeTemplate', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 3221, column: 36
System.err:     Frame: function:'CompileMetadataResolver.loadDirectiveMetadata', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 14950, column: 75
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34454, column: 72
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34453, column: 72
System.err:     Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34450, column: 75
System.err:     Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34408, column: 36
System.err:     Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 34302, column: 37
System.err:     Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 270, column: 49
System.err:     Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 5601, column: 25
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/platform-common.js', line: 71, column: 66
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/nativescript-angular/platform-common.js', line: 144, column: 21
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err:     Frame: function:'PageBase.onNavigatingTo', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 118, column: 14
System.err:     Frame: function:'FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 357, column: 37
System.err:     Frame: function:'FrameBase.performNavigation', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 329, column: 14
System.err:     Frame: function:'FrameBase._processNextNavigationEntry', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 322, column: 22
System.err:     Frame: function:'Frame._processNextNavigationEntry', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 86, column: 58
System.err:     Frame: function:'FrameBase.onLoaded', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 137, column: 14
System.err:     Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 640, column: 22
System.err:     Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/org.nativescript.DemoAPL/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 26, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
System.err:     at android.app.Activity.performStart(Activity.java:6994)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
System.err:     ... 9 more
ActivityManager: Process org.nativescript.DemoAPL (pid 28807) has died(136,736)
ActivityManager: cleanUpApplicationRecord -- 28807
```

**Comment by tsonevn** [comment]
Hi @tanmayparmar,
Thank you for contacting us,
We reviewed the case; however, we were unable to recreate similar issue after updating to latest NAtiveScript CLI 3.4.2.

It would help if you could provide more info about your project and the exact steps, which you used to build it.  Also, you could send us the project or at least its package.json file, which will help us to investigate further the issue.


Something more, please follow the template, when you opening a new issue. ->

## Please, provide the details below:

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

**Comment by tsonevn** [comment]
Hi @tanmayparmar,
Please provide sample project or code snippets, which could be used for reproducing the problem. Also, send us the project package.json file.

**Comment by Amead24** [comment]
I'm getting the same error on android, first I created a blank template
`tns create ArcadeApp --template tns-template-blank-ng`

And then I updated my code on the playground to recreate my problem: https://play.nativescript.org/?template=play-ng&id=8VCpyj

And my package.json:
```
 {
   "android": {
     "v8Flags": "--expose_gc"
   },
   "main": "main.js",
   "name": "tns-template-blank-ng",
   "version": "3.4.3"
 }
```

And then ran `tns build android`

**Comment by tsonevn** [comment]
Hi @tanmayparmar ,
Thank you for the sample project,
I reviewed your case and found that in the app.component.ts file you define the page-router-outlet while using `templateUrl` instead of `template`. While defining the page router directly in the ts file, you should use `template` tag. For example:
app.component.ts
```
import { Component } from "@angular/core";

@Component({
    selector: "App",

    // telling app we use a routing file, app.routing.ts
    template: "<page-router-outlet></page-router-outlet>"
})
export class AppComponent { }

```
More about the usage of template/templateUrl could be found in this [thread](https://lishman.io/angular-2-templates).

Another issue is that the default path in app.routing.ts file was defined with `/`. The correct way is as follow:
app.routing.ts
```
import { LoginComponent } from "./components/login.component/login.component"

// route mapping
export const routes = [
    { path: "", component: LoginComponent }
];

// exort the mapping to main.ts
export const navigatableComponents = [
    LoginComponent
];

```
