### ISSUE TITLE
error at add a headerItemTemplate to my radlistview

### ISSUE THREAD

**Issue by mauriciosouza** [NativeScript/NativeScript#5415]
https://play.nativescript.org/?template=play-js&id=i5TBDG
CLI: 3.4.2

I want to add a headerItemTemplate to my radlistview. In this example i created in nativescript playgroung does not work. I commented the part of the code that does not work (headerItemTemplate), uncomment to test.

error:
`An uncaught Exception occurred on "main" thread.
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.telerik.widget.list.RadListView.behaviors()' on a null object reference
at com.telerik.widget.list.ListViewWrapperAdapter.getItemViewType(ListViewWrapperAdapter.java:344)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5549)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
at com.telerik.widget.list.RadListView.onLayout(RadListView.java:596)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:934)
at android.view.View.layout(View.java:18878)
at android.view.ViewGroup.layout(ViewGroup.java:5953)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2684)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2400)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
at android.view.Choreographer.doCallbacks(Choreographer.java:734)
at android.view.Choreographer.doFrame(Choreographer.java:670)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#526
