### ISSUE TITLE
Cloud Build error: "no space left on device"

### ISSUE THREAD

**Issue by rogertthat** [NativeScript/NativeScript#5431]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
All cloud build attempts (whether clean or not) fail with "no space left on device" error message.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1
- Plugin(s): 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.
N/A -- It simply says no space left on device.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No.

ERROR FROM CONSOLE:
[18-02-17 22:30:18.094] (Info) NativeScript Sidekick version: 1.5.0-v.2018.2.15.3
[18-02-17 22:30:18.239] (Info) Checking for updates...
[18-02-17 22:30:18.945] (Info) No updates available.
[18-02-17 22:30:21.149] (Info) Dependencies versions: NodeJS: 6.11.1, npm: 3.10.10, NativeScript CLI: 3.4.2.
[18-02-17 22:30:22.822] (Info) Loaded CLI extension nativescript-cloud, version 1.3.1.
[18-02-17 22:30:22.826] (Info) Loaded CLI extension nativescript-starter-kits, version 0.3.4.
[18-02-17 22:30:23.512] (Info) Devices service initialized.
[18-02-17 22:30:41.118] (Info) App with path: [path] was opened.
[18-02-17 22:30:52.077] (Info) Build started.
[18-02-17 22:30:53.277] (Info) Prepare step started.
[18-02-17 22:30:54.268] (Info) Prepare step completed.
[18-02-17 22:30:54.787] (Info) Upload step started.
[18-02-17 22:30:57.464] (Info) Upload step completed.
[18-02-17 22:30:57.856] (Info) Build step started.
[18-02-17 22:31:00.222] (Info) fs.js:923
[18-02-17 22:31:00.223] (Info) return binding.mkdir(pathModule._makeLong(path),
[18-02-17 22:31:00.229] (Info) ^
[18-02-17 22:31:00.230] (Info) Error: ENOSPC: no space left on device, mkdir '/var/folders/xy/l3qb9d5d1bv0jsmt1mfl2gk40000gq/T/1518924658611.538'
[18-02-17 22:31:00.231] (Info) at Error (native)
[18-02-17 22:31:00.233] (Info) at Object.fs.mkdirSync (fs.js:923:18)
[18-02-17 22:31:00.235] (Info) at Dir.create (/Users/builderdaemon/node_modules/temporary/lib/dir.js:37:13)
[18-02-17 22:31:00.236] (Info) at Dir.Base.init (/Users/builderdaemon/node_modules/temporary/lib/base.js:32:8)
[18-02-17 22:31:00.238] (Info) at new Dir (/Users/builderdaemon/node_modules/temporary/lib/dir.js:23:8)
[18-02-17 22:31:00.240] (Info) at Object.<anonymous> (/Users/builderdaemon/node_modules/ipa-metadata/index.js:13:14)
[18-02-17 22:31:00.241] (Info) at Module._compile (module.js:570:32)
[18-02-17 22:31:00.243] (Info) at Object.Module._extensions..js (module.js:579:10)
[18-02-17 22:31:00.244] (Info) at Module.load (module.js:487:32)
[18-02-17 22:31:00.246] (Info) at tryModuleLoad (module.js:446:12)
[18-02-17 22:31:00.249] (Error) Error detected during LiveSync on d95e8476d36c91945e694aae70e83ed9a5a556e7 for [path]. Error: Build failed.
[18-02-17 22:31:00.251] (Info) Stopped LiveSync on d95e8476d36c91945e694aae70e83ed9a5a556e7 for [path].

**Comment by tsonevn** [comment]
Hi @rogertthat 
Thank you for contacting us,
This issue seems to be related to the fact that for some reason there is no free space on the device, on which you try to deploy the app.
Try to free some space on on it and try again to build the project.

Let me know if I could help you further.

**Comment by diego-lipinski-de-castro** [comment]
Please tell me you atleast checked the storage left on your device before issuing

**Comment by rogertthat** [comment]
@tsonevn Hi, thanks for the quick reply. I'll highlight the line from the cloud build that shows the problem:

`Error: ENOSPC: no space left on device, mkdir '/var/folders/xy/l3qb9d5d1bv0jsmt1mfl2gk40000gq/T/1518924658611.538'`

I'm not building on my local machine (hence cloud build). The problem is that the nativescript cloud servers ran out of free space to actually perform the iOS build. If you read the order of process in the log I posted in the OP, you can see that the error happens prior to the build succeeding and attempting to download to my local computer and then into my actual iPhone device. So the "device" the error mentions is not my iPhone, it is the cloud server. Also, the iPhone has 58GB free (not that this matters).

@diego-lipinski-de-castro Did you not read the title of this issue and the log I included?

**Comment by rogertthat** [comment]
@tsonevn Another update. I just ran the exact same process and this time the nativescript cloud servers succeeded (had enough space) to complete the build. So, for now, this is no longer an issue, but hopefully this issue remains open until the root cause for the lack of free space on the cloud servers is fixed.

**Comment by tsonevn** [comment]
Hi @rogertthat,
We discussed the problem with our developers. We were able to isolate the case and to provide the needed fix. The issue should no longer appear.

**Comment by gaoning777** [comment]
How can I configure the device space for the cloud build?
