### ISSUE TITLE
Error: java.lang.OutOfMemoryError on load an image by "fromFile" from ImageSource

### ISSUE THREAD

**Issue by vasyliv** [NativeScript/NativeScript#5491]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
https://github.com/NativeScript/NativeScript/issues/3153 (might be the same, however, it is closed)

### Tell us about the problem
After taking an image (7 times, each image has size ~1.2MB, 3120x4160px) by "nativescript-camera" and convert the result (ImageAsset) to ImageSource (by method "fromFile") get the error:  Error: java.lang.OutOfMemoryError

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
the repository with the reproductive bug (have to click on the button "TAKE PICTURE" 7 times in a real android mobile device (emulators have low sizes of images))
https://github.com/vasyliv/nativescript-image-bug

### Please tell us how to recreate the issue in as much detail as possible.
tns isntall
tns build android
tns run android (on a real android device)
have to click on the button "TAKE PICTURE" 7 times

### Full  error
```
ERROR Error: Uncaught (in promise): Error: java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 16773120 free bytes and 29MB un
OOM
    dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
    android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:650)
    android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:626)
    android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:75)
    android.app.Activity.dispatchActivityResult(Activity.java:7111)
    android.app.ActivityThread.deliverResults(ActivityThread.java:4169)
    android.app.ActivityThread.handleSendResult(ActivityThread.java:4216)
    android.app.ActivityThread.-wrap20(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:163)
    android.app.ActivityThread.main(ActivityThread.java:6342)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Error: java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 16773120 free bytes and 29MB until OOM
    dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
    android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:650)
    android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:626)
    android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:75)
    android.app.Activity.dispatchActivityResult(Activity.java:7111)
    android.app.ActivityThread.deliverResults(ActivityThread.java:4169)
    android.app.ActivityThread.handleSendResult(ActivityThread.java:4216)
    android.app.ActivityThread.-wrap20(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:163)
    android.app.ActivityThread.main(ActivityThread.java:6342)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
    at ImageSource.loadFromFile (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/tns-core-modules/image-source/image-source.js:86:55)
    at file:///data/data/org.nativescript.imagebug/files/app/tns_modules/tns-core-modules/image-source/image-source.js:92:27
    at new ZoneAwarePromise (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777

    at ImageSource.fromFile (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/tns-core-modules/image-source/image-source.js:91:16)
    at file:///data/data/org.nativescript.imagebug/files/app/home/home.component.js:15:32
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativ
escript-angular/zone-js/dist/zone-nativescript.js:365:26)
    at Object.onInvoke (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/@angular/core/bundles/core.umd.js:4787:33)
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:364:

    at Zone.run (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:125:43)
    at file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:761:57
    at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:
31)
    at Object.onInvokeTask (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/@angular/core/bundles/core.umd.js:4778:33)
    at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:
36)
    at Zone.runTask (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:165:47)
    at drainMicroTaskQueue (file:///data/data/org.nativescript.imagebug/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:593:
```

**Comment by vasyliv** [comment]
might be close, the bug fixed by https://developer.android.com/reference/android/graphics/Bitmap.html#recycle(), 
however, will great create some logic to clean memory for all ImageSource.

**Comment by NickIliev** [comment]
@vasyliv consider using the `src` property instead of creating multiple `ImageSource` objects. This will prevent the OOM error as described [here](https://docs.nativescript.org/best-practices/images-optimisations)
