### ISSUE TITLE
Production build, an error "Could not initialize class com.android.build.gradle.tasks.Lint$LintGradleIssueRegistry"

### ISSUE THREAD

**Issue by vasyliv** [NativeScript/NativeScript#5500]
## Please, provide the details below:
While was running the production script, got an error. The error gets only with production build.

### Tell us about the problem
while was running the production script, got an error
```
tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password> 
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Photolog",
    "tns-android": {
      "version": "3.4.2"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\"",
    "clean:js": "rm -rf ./app/*.js && rm -rf ./app/**/*.js && rm -rf ./app/**/**/*.js && rm -rf ./app/**/**/**/*.js"
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-background-http": "~3.2.1",
    "nativescript-camera": "~3.2.1",
    "nativescript-ngx-fonticon": "~4.0.0",
    "nativescript-pro-ui": "~3.3.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.3.5",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "~2.9.1",
    "webpack-sources": "~1.1.0"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
while was running the production script, got an error
```
tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password> 
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
````
Running full build
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalF0F1F2Release'.
> Could not initialize class com.android.build.gradle.tasks.Lint$LintGradleIssueRegistry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
````

with "--log trace"
```
...
22:00:16.985 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 15: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
22:00:16.986 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.i
nternal.exceptions.LocationAwareException: Execution failed for task ':app:lintVitalF0F1F2Release'.] from daemon DaemonInfo{pid=14532, address=[6f6f0292-3370
-42b9-9c69-ccb983b5549d port:54903, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1520366334195, context=DefaultDaemonContext[uid=9be6b862-
8360-41eb-b5cd-17c298781def,javaHome=C:\Program Files\Java\jdk1.8.0_151,daemonRegistryDir=C:\Users\Michael\.gradle\daemon,pid=14532,idleTimeout=10800000,daem
onOpts=-Xmx16384M,-Dfile.encoding=windows-1251,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
22:00:16.986 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
22:00:16.987 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
Error: Command gradlew.bat failed with exit code 1
    at ChildProcess.childProcess.on (C:\Users\Michael\AppData\Roaming\npm\node_modules\nativescript\lib\common\child-process.js:113:36)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
List of registered commands: /?, accept, accept|eula, account, account|usage, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|ena
ble, autocomplete|status, build, build|android, build|cloud, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|build, cloud|clean|workspac
e, cloud|codesign, cloud|lib|version, cloud|publish|android, cloud|publish|ios, codesign, codesign|cloud, config, config|apply, config|reset, config|set, cre
ate, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-login, dev-post-install, dev-preuninstall, dev-test, dev-test|and
roid, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files,
device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, inf
o, init, install, kill-server, login, logout, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|install, p
lugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, run, run|android, run|ios, test, test|android, t
est|init, test|ios, update, usage-reporting, user
Reading help for command 'build|android'. FileName is 'build-android.md'.
# build android
```

**Comment by vasyliv** [comment]
solved by reinstall android tools
