### ISSUE TITLE
Command gradlew.bat failed with exit code 1

### ISSUE THREAD

**Issue by webinger** [NativeScript/NativeScript#5512]
Hello there NativeScripters, 
After a long time not using Nativescript I can not get any app to run with the usual tns run android command. Whether it is a newly created one or an older existing one I always get this:

```
...
Building project...
Gradle build...
         + applying user-defined configuration from C:\#code\MyApp\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: C:\#code\MyApp\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
false
Exception in thread "main" java.net.MalformedURLException: no !/ in spec
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.ig.GetInterfaceNames.getClassLoader(GetInterfaceNames.java:94)
        at com.ig.GetInterfaceNames.generateInterfaceNames(GetInterfaceNames.java:51)
        at com.ig.GetInterfaceNames.main(GetInterfaceNames.java:35)
Caused by: java.lang.NullPointerException: no !/ in spec
        at sun.net.www.protocol.jar.Handler.parseAbsoluteSpec(Handler.java:171)
        at sun.net.www.protocol.jar.Handler.parseURL(Handler.java:151)
        at java.net.URL.<init>(URL.java:622)
        ... 5 more

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\#code\MyApp\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 72

* What went wrong:
Execution failed for task ':asbg:generateInterfaceNamesList'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_162\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

```

```
tns doctor
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Your components are up-to-date:
nativescript,tns-core-modules,tns-android,tns-ios
```

I already reinstalled: JDK, SDK, Android Studio, Nativescript. 

system: 
tns --version 3.4.3
windows 10

Thank you for any help!

**Comment by khyynld** [comment]
hey bro, u can talk to me how to fix it ?

**Comment by webinger** [comment]
I solved the problem by changing my directory name. It contained a hashtag like that:   \#Code to make it appear on top in some folder. too bad nativescript did not like.

But I think this error can have other causes as well.

**Comment by khyynld** [comment]
oh tks. i'm fixed it ! i'm run tns platform remove android and i run my prj again

**Comment by khyynld** [comment]
My English is poor, I hope you understand! <3

**Comment by tieuquy1995** [comment]
yeah welcome!

2018-05-04 16:21 GMT+07:00 webinger <notifications@github.com>:

**Comment by khyynld** [comment]
@tieuquy1995 vietnam????

**Comment by krishna949** [comment]
me also facing in below issue, please any one suggest me.........
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\ivds\krish\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:45: AAPT: error: resource string/nativescript_google_maps_api_key (aka org.nativescript.krish:string/nativescript_google_maps_api_key) not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Command gradlew.bat failed with exit code 1

**Comment by medhak16** [comment]
D8: Cannot fit requested classes in a single dex file (# methods: 71795 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:55)
        at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
        at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.t.a(:55)
        at com.android.tools.r8.D8.run(:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
        ... 30 more
Caused by: com.android.tools.r8.utils.AbortException: Error: null, Cannot fit requested classes in a single dex file (# methods: 71795 > 65536)
        at com.android.tools.r8.utils.Reporter.a(:21)
        at com.android.tools.r8.utils.Reporter.a(:7)
        at com.android.tools.r8.dex.VirtualFile.a(:33)
        at com.android.tools.r8.dex.VirtualFile$h.a(:5)
        at com.android.tools.r8.dex.ApplicationWriter.a(:13)
        at com.android.tools.r8.dex.ApplicationWriter.write(:35)
        at com.android.tools.r8.D8.d(:44)
        at com.android.tools.r8.D8.b(:1)
        at com.android.tools.r8.utils.t.a(:23)
        ... 32 more


Execution failed for task ':app:mergeDexDebug'.
Error: null, Cannot fit requested classes in a single dex file (# methods: 71795 > 65536)

Unable to apply changes on device: S5D3Y18818009157. Error is: Command gradlew.bat failed with exit code 1.

I am getting this error while building my native-script app. I am new to this and can't figure out why. This is my first attempt on connecting my app to backend.
