### ISSUE TITLE
Android startup crashing due toUpperCase

### ISSUE THREAD

**Issue by arcovoltaico** [NativeScript/NativeScript#5576]
Here's the error. The funny thing is I can't find the toUpperCase  function inside my /app folder.
I was thinking on     "nativescript-localize": "^2.3.0", dependency as the source of the problem, but it's not mentioned anywhere:

Problem: Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38

FATAL EXCEPTION: main
Process: com.uvox.selector, PID: 8643
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uvox.selector/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed
**TypeError: Cannot read property 'toUpperCase' of null**
File: "file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js, line: 116, column: 33
StackTrace: 
	Frame: function:'getTransformedText', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js', line: 274, column: 24
	Frame: function:'TextTransformationImpl.getTransformation', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js', line: 27, column: 24
	Frame: function:'TextBase.(anonymous function)', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js', line: 116, column: 34
	Frame: function:'applyAllNativeSetters', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 978, column: 37
	Frame: function:'initNativeView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 905, column: 9
	Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 555, column: 22
	Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 223, column: 18
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 200, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'ScrollViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/scroll-view/scroll-view-common.js', line: 30, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'RadSideDrawer.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/nativescript-pro-ui/sidedrawer/sidedrawer-common.js', line: 152, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'RadSideDrawer.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/nativescript-pro-ui/sidedrawer/sidedrawer.js', line: 23, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'Page.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 105, column: 35
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 360, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed
TypeError: Cannot read property 'toUpperCase' of null
File: "file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js, line: 116, column: 33
StackTrace: 
	Frame: function:'getTransformedText', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js', line: 274, column: 24
	Frame: function:'TextTransformationImpl.getTransformation', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js', line: 27, column: 24
	Frame: function:'TextBase.(anonymous function)', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/text-base/text-base.js', line: 116, column: 34
	Frame: function:'applyAllNativeSetters', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 978, column: 37
	Frame: function:'initNativeView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 905, column: 9
	Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 555, column: 22
	Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 223, column: 18
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 200, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'ScrollViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/scroll-view/scroll-view-common.js', line: 30, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'RadSideDrawer.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/nativescript-pro-ui/sidedrawer/sidedrawer-common.js', line: 152, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'RadSideDrawer.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/nativescript-pro-ui/sidedrawer/sidedrawer.js', line: 23, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'Page.onLoaded', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 105, column: 35
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 360, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.uvox.selector/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
	at android.app.Fragment.performCreateView(Fragment.java:2611)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1276)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2415)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2194)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3044)
	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2996)
	at android.app.FragmentController.dispatchStart(FragmentController.java:189)
	at android.app.Activity.performStart(Activity.java:6998)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
	... 9 more

**Comment by arcovoltaico** [comment]
[logcat.txt](https://github.com/NativeScript/NativeScript/files/1838913/logcat.txt)

**Comment by arcovoltaico** [comment]
My problem was caused because the 
**tbs-core-modules/ui/text-base/text-base.android.js**
L271 function getTransformedText(text, textTransform) {
along with others, expects always a non-null value on Label text attribute.
Although iOS {N} treats null safety, I got to change some parts of my views in order to play fine with Android.

So:

**AVOID** 
[text]="item.city">
or
[text]="item.city? item.city:null”>

**DO :**

 [visibility]="item.music?'visible':'collapse'">

or  
[text]="item.city? item.city:' '">
