### ISSUE TITLE
webView variable becomes null after the app resumes.

### ISSUE THREAD

**Issue by Xsmael** [NativeScript/NativeScript#5603]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
YES

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
Am using a webview and  I needed to link the android back button to the webview navigation, so that when the back button is pressed, the webview goes to the previous page if available and if not, it quits.
Everything works fine except when the app is resumed, in that case pressing the back button makes it crash because the webView is null.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.1
- Cross-platform modules: 3.3.0
- Runtime(s): tns-android
- Plugin(s): 3.3.1

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

https://play.nativescript.org/?template=play-js&id=DmXTJn

You just have to add the nativescript-webview-interface plugin.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

here is the portion of code where the problem occurs
```
application.android.on(application.AndroidApplication.activityBackPressedEvent, (data) => {
        let webView = page.getViewById('webView');
            if (webView.canGoBack) {
                data.cancel = true; // prevents default back button behavior
                webView.goBack();
            } 
    });

```
and i get this error:
```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onBackPressed failed
System.err:
System.err: TypeError: Cannot read property 'canGoBack' of null
System.err: File: "file:///data/data/org.nativescript.ferapark/files/app/tns_modules/tns-core-modules/ui/web-view/web-view.js, line: 122, column: 43
System.err:
System.err: StackTrace:
System.err:     Frame: function:'get', file:'file:///data/data/org.nativescript.ferapark/files/app/tns_modules/tns-core-modules/ui/web-view/web-view.js', line: 122, column: 44
System.err:     Frame: function:'application.android.on', file:'file:///data/data/org.nativescript.ferapark/files/app/main-page.js', line: 69, column: 24
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.ferapark/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err:     Frame: function:'ActivityCallbacksImplementation.onBackPressed', file:'file:///data/data/org.nativescript.ferapark/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 44
System.err:     Frame: function:'NativeScriptActivity.onBackPressed', file:'file:///data/data/org.nativescript.ferapark/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 35, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onBackPressed(NativeScriptActivity.java:53)
System.err:     at android.app.Activity.onKeyUp(Activity.java:2807)
System.err:     at android.view.KeyEvent.dispatch(KeyEvent.java:2715)
System.err:     at android.app.Activity.dispatchKeyEvent(Activity.java:3115)
System.err:     at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:323)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4391)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4362)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4052)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4109)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4085)
System.err:     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4253)
System.err:     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2437)
System.err:     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2001)
System.err:     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1992)
System.err:     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2414)
System.err:     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
System.err:     at android.os.MessageQueue.next(MessageQueue.java:323)
System.err:     at android.os.Looper.loop(Looper.java:142)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6205)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
ActivityManager: Process org.nativescript.ferapark (pid 28544) has died
ActivityManager: cleanUpApplicationRecord -- 28544
```

**Comment by tsonevn** [comment]
Hi @Xsmael,
Thank you for contacting us.
In your scenario, you should remove the removeEventListener event listener, when the app will be suspended and add it again when the WebView is loaded. Then the correct instance of the WebView will be taken on each app resume. For example:
```
function webViewLoaded(args) {
  var webview = args.object;
  webview.android.getSettings().setDisplayZoomControls(false);
  webview.android.setVerticalScrollBarEnabled(false);
  let page = webview.page;
  application.android.on(application.AndroidApplication.activityBackPressedEvent, (data) => {
    let webView = page.getViewById('webView');
    console.log(page);
    console.log(page.getViewById('webView'));
    console.log(webView);
    if (webView) 
      if (webView.canGoBack) {
        data.cancel = true; 
        webView.goBack();
      }
      else{
        // -> remove the event listener
        application.android.off(application.AndroidApplication.activityBackPressedEvent);

      }
  });
}


```
I am attaching sample project as well.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1867280/Archive.zip)
