### ISSUE TITLE
Resources$NotFoundException On Google Robo Test

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5657]
_From @NickIliev on March 16, 2018 6:34_

_From @rakeshgirase on March 15, 2018 21:42_

### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes
### Tell us about the problem
One out of 10 devices which were under test encountered following exception and I felt like not leaving it this time as I got a logs of the same. 
[logcat.txt](https://github.com/NativeScript/NativeScript/files/1817140/logcat.txt)
Though there is nothing specific, I have attached the video of the test which gave this exception:
Video: https://drive.google.com/open?id=1uiGHhPdT8LhQ83HMlczgrY-w5FRFkn5n 
Following is stacktrace:
```
03-14 23:11:59.425: I/Robo(14384): android.content.res.Resources$NotFoundException: Resource ID #0xffffffec
03-14 23:11:59.425: I/Robo(14384): 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:255)
03-14 23:11:59.425: I/Robo(14384): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2187)
03-14 23:11:59.425: I/Robo(14384): 	at android.content.res.Resources.getAnimation(Resources.java:1202)
03-14 23:11:59.425: I/Robo(14384): 	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:127)
03-14 23:11:59.425: I/Robo(14384): 	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:108)
03-14 23:11:59.425: I/Robo(14384): 	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:93)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.loadAnimator(FragmentManager.java:828)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1283)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.BackStackRecord.run(BackStackRecord.java:766)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1585)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:484)
03-14 23:11:59.425: I/Robo(14384): 	at android.os.Handler.handleCallback(Handler.java:755)
03-14 23:11:59.425: I/Robo(14384): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-14 23:11:59.425: I/Robo(14384): 	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
03-14 23:11:59.425: I/Robo(14384): 	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:465)
```

### Which platform(s) does your issue occur on?
Android
![image](https://user-images.githubusercontent.com/16098644/37492565-bb8e533e-2899-11e8-8653-3407a89c7065.png)

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)
The complete project can be found at https://github.com/rakeshgirase/QSB.

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
I understand that it is an issue which is difficult to pin point and fix.. Its strange that code works just fine on 9 out of 10 devices. However, if at all code is required then you can find it https://github.com/rakeshgirase/QSB

_Copied from original issue: NativeScript/NativeScript#5549_

_Copied from original issue: NativeScript/android-runtime#974_

**Comment by NickIliev** [comment]
_From @sserdyuk on March 22, 2018 18:48_

@NickIliev I'd like to add my two cents here. 

First, I do have the same reports from the pre-launch testing in  Firebase Test Lab. I get these consistently since Google implemented "more comprehensive pre-launch report" that "now explores your app even more deeply and may find more crashes". All quoted text is Google's. 

I get 2-3 reports for each build. Here's a graph of issues since January 18th 2018. See graphs and screenshots below.

Second, more importantly, this is not only happening during robo testing in the lab, I also have a similar crash report from the real production use. 

From what I can see in the videos, it seems to be related to user action during or right after navigating back. I use `topmost().goBack();` to return from the list of categories, and that's about where it's crashing.

I can actually recreate it on my phone by tapping while transitions are happening, similar to how the robo testers do it in the videos.

I think this deserves a high priority ticket, and I'd be happy to help solve the issue. 

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.4.3           │ 3.4.3          │ Up to date  │
│ tns-core-modules │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-android      │ 3.4.2           │ 3.4.2          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

```

Please note the logcat files and videos from the Test Lab below:

[logcat (2).txt](https://github.com/NativeScript/android-runtime/files/1838794/logcat.2.txt)
[screen video (2)](https://youtu.be/aoYyrOYM51k)

[logcat (1).txt](https://github.com/NativeScript/android-runtime/files/1838795/logcat.1.txt)
[screen video (1)](https://youtu.be/BjgHGMYYHh0)

[logcat.txt](https://github.com/NativeScript/android-runtime/files/1838796/logcat.txt)
[screen video](https://youtu.be/sXUP7PK6on0)

Firebase Crash Reporting for production app:

![image](https://user-images.githubusercontent.com/395998/37788939-11f6ed14-2dd9-11e8-8098-17693b40256d.png)

Pre-launch testing in  Firebase Test Lab:

![image](https://user-images.githubusercontent.com/395998/37788555-16ba047c-2dd8-11e8-921b-2b419d828982.png)

![image](https://user-images.githubusercontent.com/395998/37788694-795c5b70-2dd8-11e8-9c2b-c608aeb33ef5.png)

![image](https://user-images.githubusercontent.com/395998/37788699-80e6715a-2dd8-11e8-8936-48a051b83678.png)

![image](https://user-images.githubusercontent.com/395998/37788715-8a6c00a0-2dd8-11e8-9446-60de41392b52.png)

![image](https://user-images.githubusercontent.com/395998/37788744-9b491804-2dd8-11e8-9792-96d2588c4d53.png)

**Comment by NickIliev** [comment]
_From @sserdyuk on April 2, 2018 21:14_

@NickIliev Did you see my comment that it is also happening in production? Is that not a concern? It's been 11 days and there's no activity here.

**Comment by NickIliev** [comment]
_From @Plamen5kov on April 3, 2018 7:3_

Hi @sserdyuk 
I tried to reproduce the issues you're facing but without steps to reproduce, It's going to be really difficult to help you.
Can you provide us with some sample repo that has better odds of crashing?

**Comment by NickIliev** [comment]
_From @sserdyuk on April 3, 2018 15:26_

@Plamen5kov Here's logcat from a real device I just recreated it on. I added verbose logging per your instructions in the other issue. 

[log1.txt](https://github.com/NativeScript/android-runtime/files/1872141/log1.txt)


```
declare function __enableVerboseLogging()
__enableVerboseLogging()
```

**Comment by NickIliev** [comment]
_From @etabakov on April 10, 2018 13:39_

@sserdyuk I was able to reproduce the issue using your project and we are currently looking for the reason. I will get back when we have any update.

**Comment by NickIliev** [comment]
_From @sserdyuk on April 10, 2018 13:59_

@etabakov Terrific. Thank you!

**Comment by NickIliev** [comment]
_From @etabakov on April 11, 2018 13:9_

After some investigation it looks like the problem is related to multiple slide transitions trying to be executed simultaneously and asynchronously.

**Comment by NickIliev** [comment]
The issue might be possibly reproduced [via this action](https://github.com/NativeScript/NativeScript/issues/1569#issuecomment-388404422)
