### ISSUE TITLE
Error with zone-nativescript when running unit tests

### ISSUE THREAD

**Issue by GandalfDaGreat** [NativeScript/NativeScript#5751]
### Did you verify this is a real problem by searching the [NativeScript Forum]
yes

### Tell us about the problem
My application builds and runs well on both Android and iOS, however when I run the unit tests I get an error that causes the application to crash before the tests complete. I get an error related to zone.js. The stack trace that appears is included below: 

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: document.getElementById is not a function
File: "file:///data/data/com.enernoc.eis.mobile.eismanual/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 142, column: 24

StackTrace: 
	Frame: function:'', file:'', line: 163, column: 30
	Frame: function:'done', file:'', line: 1806, column: 13
	Frame: function:'', file:'', line: 5357, column: 5
	Frame: function:'EventEmitter.emit', file:'', line: 389, column: 20
	Frame: function:'', file:'', line: 5338, column: 12
	Frame: function:'', file:'', line: 5186, column: 9
	Frame: function:'next', file:'', line: 4821, column: 14
	Frame: function:'', file:'', line: 4865, column: 5
	Frame: function:'timeslice', file:'', line: 82, column: 27
	Frame: function:'invoke', file:'file:///data/data/com.enernoc.eis.mobile.eismanual/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/com.enernoc.eis.mobile.eismanual/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26
	Frame: function:'Zone.runGuarded', file:'file:///data/data/com.enernoc.eis.mobile.eismanual/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 138, column: 47
	Frame: function:'', file:'file:///data/data/com.enernoc.eis.mobile.eismanual/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 116, column: 29
	Frame: function:'run', file:'file:///data/data/com.enernoc.eis.mobile.eismanual/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): Android: 4.0.1; iOS 4.0.1
- Plugin(s):
 ```
"nativescript-angular": "5.2.0",
    "nativescript-disable-bitcode": "^1.0.0",
    "nativescript-email": "^1.4.0",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-ngx-fonticon": "2.0.0",
    "nativescript-secure-storage": "^2.1.0",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "1.0.2",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-webview-interface": "^1.4.0",
```

### Please tell us how to recreate the issue in as much detail as possible.
my full list of dependencies from the package.json is here:
```
  "dependencies": {
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/router": "5.2.9",
    "camelcase-keys-deep": "^0.1.0",
    "locale-search": "git+http://git@github.bdap.enernoc.net/CommonPrezComponents/locale-search.git#1.0.1",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "nativescript-angular": "5.2.0",
    "nativescript-disable-bitcode": "^1.0.0",
    "nativescript-email": "^1.4.0",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-ngx-fonticon": "2.0.0",
    "nativescript-secure-storage": "^2.1.0",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "1.0.2",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-webview-interface": "^1.4.0",
    "ng2-translate": "^5.0.0",
    "pseudolocalize": "git+http://github.bdap.enernoc.net/CommonPrezComponents/pseudolocalize.git#v1.0.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.5.8",
    "sinon": "^1.17.7",
    "tns-core-modules": "^4.0.0",
    "tns-platform-declarations": "^3.0.1"
  },
  "devDependencies": {
    "appium": "1.7.1",
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "babylon": "6.15.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^5.3.0",
    "chimp": "0.49.1",
    "chromedriver": "2.32.3",
    "colors": "^1.1.2",
    "cucumber": "^2.3.1",
    "deep-extend": "^0.5.0",
    "karma": "^1.4.1",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^3.2.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-dev-typescript": "^0.3.2",
    "picture-tube": "^1.0.0",
    "plist": "^2.0.1",
    "term-img": "^1.0.0",
    "typescript": "~2",
    "webdriverio": "4.6.2",
    "xcode": "^1.0.0",
    "zone.js": "0.8.4"
  }
```

**Comment by BenAtkinson-ss** [comment]
@GandalfDaGreat Did you resolve your issue? I'm facing the same errors now
