### ISSUE TITLE
View already has a parent. 

### ISSUE THREAD

**Issue by xeroxstar** [NativeScript/NativeScript#5795]
Hello, i am getting an error each time i open the app, the first time i open it i get an error but if i close it and open the second time it's working, what can be wrong here?

```
System.err: Error: View already has a parent. View: Page(4) Parent: Frame(3)
System.err: File: "file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js, line: 343, column: 12
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 343, column: 19
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err: 
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreateView failed
```

**Comment by tsonevn** [comment]
closing due to inactivity

**Comment by tony2u** [comment]
Sir, I met the same problem with you.  and reported the details to other place:
[https://github.com/NativeScript/tns-core-modules-widgets/issues/133](url)

is there any one solved it?

**Comment by NickIliev** [comment]
@tony2u the example posted as a link in the linked issue is outdated - please use the latest version of nativescript and nativescript-vue,native - details [here](https://nativescript-vue.org/)
