### ISSUE TITLE
Using Image throws an error on some devices

### ISSUE THREAD

**Issue by anaszgh** [NativeScript/NativeScript#5814]
Hello,

Using NativeScript version 3.4.1
And NativeScript with angular template.

I have an Image tag with srouce from server
While it works correctly on some Android devices, on other devices it thrwos the following error

```
An uncaught Exception occurred on "main" thread.
java.lang.IllegalArgumentException: Problem decoding into existing bitmap
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:651)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:600)
	at org.nativescript.widgets.image.Fetcher.decodeSampledBitmapFromResource(Fetcher.java:372)
	at org.nativescript.widgets.image.Fetcher.processBitmap(Fetcher.java:261)
	at org.nativescript.widgets.image.Worker.loadImage(Worker.java:114)
	at org.nativescript.widgets.ImageView.loadImage(ImageView.java:191)
	at org.nativescript.widgets.ImageView.onAttachedToWindow(ImageView.java:57)
	at android.view.View.dispatchAttachedToWindow(View.java:17558)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5016)
	at android.view.ViewGroup.addView(ViewGroup.java:4807)
	at android.view.ViewGroup.addView(ViewGroup.java:4747)
	at android.view.ViewGroup.addView(ViewGroup.java:4720)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1284)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2422)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2155)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7415)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```
This error is on main screen, it happens if navigated to, from other page (login)
after successful login, if you close the app and open it again it shows the images correctly.

Navigate to ther view and press Back, the same error shows again.

Thanks.

**Comment by tsonevn** [comment]
Hi @anaszgh,
Can you check if the issue will be reproduced while using latest NativeScpirt 4.0? You can review [this ](https://docs.nativescript.org/releases/upgrade-instructions) article, where it is described, how you can upgrade to the most recent product version.

If the problem is reproducible with NS 4.0, please send a sample project, which could be used for debugging and provide more info about the devices, which you used for testing.

**Comment by anaszgh** [comment]
Hello @tsonevn 
Thanks for your quick response, Unfortunately i cannot upgrade to TNS@4
Because i'm using two plugins (social-login & social-share) that doesn't work with TNS@4

**Comment by anaszgh** [comment]
Btw the error can be reproduces ALWAYS on Huawei P10, on other devices like Nexus for example, you can't reproduce the issue.

**Comment by NickIliev** [comment]
@anaszgh just FYI I am using [nativescript-social-share with NativeScript 4.0.0](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/package.json#L28) without any issues.

Apart from that can you please post the link to the image that is causing this error to occur.

**Comment by anaszgh** [comment]
@NickIliev here is link for the image that's causing the issue
[Image](http://www.splashscore.com/wp-content/uploads/Buku-Music-Festival-2013-Review.jpg)

Regarding the Social-Share plugin

I can't really confirm that the error is related to the Social-Share plugin, but when i remove the plugin the build succeeds

Here is the build error
```

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
        ... 48 more
Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Command ./gradlew failed with exit code 1
# tns build android
```

**Comment by NickIliev** [comment]
@anaszgh we are not able to reproduce the issue while using this [Playground demo](https://play.nativescript.org/?template=play-tsc&id=Mov3qv) on Nexus 5 device. Try setting a predefined size (or use [`decodeWidth` & `decodeHeight` properties](https://docs.nativescript.org/best-practices/images-optimisations#using-decodeheight-and-decodewidth-properties)) for your image as suggested [here](https://stackoverflow.com/a/18603084/4936697).

Let me know if you have a sample project that can reproduce the issue so we could investigate further.

**Comment by anaszgh** [comment]
@NickIliev the Playground demo you've provided uses TNS version 4?

After successfully upgrading to version 4, i can confirm that the issue got resolved.

Thank you.
