### ISSUE TITLE
tns test ios fails

### ISSUE THREAD

**Issue by benradock** [NativeScript/NativeScript#5818]
Trying to get mocha to work, whenever I do `tns test ios` I get the following:

tns test ios
Searching for devices...
module.js:549
    throw err;
    ^

Error: Cannot find module 'mocha'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at initMocha (/Users/unu-cs/Desktop/victim-id-frontend/node_modules/karma-mocha/lib/index.js:10:40)
    at Array.invoke (/Users/unu-cs/Desktop/victim-id-frontend/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/unu-cs/Desktop/victim-id-frontend/node_modules/di/lib/injector.js:48:43)
    at /Users/unu-cs/Desktop/victim-id-frontend/node_modules/karma/lib/server.js:169:20
    at Array.forEach (<anonymous>)
    at Server._start (/Users/unu-cs/Desktop/victim-id-frontend/node_modules/karma/lib/server.js:168:21)
    at Injector.invoke (/Users/unu-cs/Desktop/victim-id-frontend/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/unu-cs/Desktop/victim-id-frontend/node_modules/karma/lib/server.js:129:18)
    at process.on (/usr/local/lib/node_modules/nativescript/lib/services/karma-execution.js:9:15)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Test run failed.

**Comment by NickIliev** [comment]
Closing as a duplicate to [https://github.com/NativeScript/nativescript-cli/issues/2283](https://github.com/NativeScript/nativescript-cli/issues/2283)

Temporary solution - install `mocha` devDependency manually.
