### ISSUE TITLE
App crashing on breakpoint resume in Chrome

### ISSUE THREAD

**Issue by waszqba** [NativeScript/NativeScript#5878]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
Hard to tell if it will be easily replicable, but:
1. Open app and attach chrome debugger to it
2. set a breakpoint anywhere in the code
3. make app stop on that breakpoint
4. resume action or request a step forward
The problem is that there are times that everything works like a charm, but sometimes I can't debug my app for a long time, because any attempt to 'unpause' script execution results in app crashing in random ways, be it a `cannot convert undefined or null to object` or just a system information that app has stopped.

**Comment by NickIliev** [comment]
@waszqba can you provide more details on your environment (OS and the type of NativeScript project created) and any possible specifics in the code you are debugging. I've used [this test application ](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue_5878)and I was able to debug in Chrome without any issues (following your exact steps)

**Comment by Burgov** [comment]
I'm having the same issue.  Here is my stack trace:

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: Cannot convert undefined or null to object
File: "file:///data/data/io.neocles.dev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 142, column: 24

StackTrace: 


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Doesn't always happen which makes it stranger. 

Windows, all NS components at the latest version

**Comment by Burgov** [comment]
This is lines 140-144 of `zone-nativescript.js` if that helps:

```
                catch (error) {
                    if (this._zoneDelegate.handleError(this, error)) {
                        throw error;
                    }
                }
```

**Comment by waszqba** [comment]
Hi, @tsonevn 
I'm using macOS Sierra 10.12.6
The project was based on sidekick's template of tabs application with angular 5 and no specific mechanic was changed, only logic in components is being worked on.
The issue occurred regardless of what plugins/addons/packages were added to the project, and, as mentioned in the first post, is not consistent, however when I try to handle urls, the app works well without debugger, but crashes, when I try to step forward in debugger, and it crashes without teh debug info, the process is just killed off (`ActivityManager: Process eu.neoteric.skillhunt (pid 16600) has died(124,801)`)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3857
