### ISSUE TITLE
App Crash: android.widget.ImageView cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by sgornostal** [NativeScript/NativeScript#5897]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
I've installed plugin `nativescript-google-maps-sdk`. My home page contains tabview and a button to navigate to the page with map. If I navigating to the map page, application fails with error: 
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method finishUpdate failed

Error: java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
    android.app.FragmentTransition.configureTransitionsReordered(FragmentTransition.java:197)
    android.app.FragmentTransition.startTransitions(FragmentTransition.java:116)
    android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2202)
    android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
    android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2019)
    android.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:662)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
    com.tns.Runtime.callJSMethod(Runtime.java:969)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:945)
    com.tns.gen.android.support.v4.view.PagerAdapter_view_69_32_FragmentPagerAdapter.finishUpdate(PagerAdapter_view_69_32_FragmentPagerAdapter.java:92)
    android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1062)
    android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3089)
    android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
    com.tns.Runtime.callJSMethod(Runtime.java:969)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:945)
    com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
    android.os.Handler.handleCallback(Handler.java:789)
    android.os.Handler.dispatchMessage(Handler.java:98)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js, line: 158, column: 41

StackTrace: 
	Frame: function:'FragmentPagerAdapter.finishUpdate', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 158, column: 42
	Frame: function:'TabView.setAdapterItems', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 448, column: 36
	Frame: function:'TabView.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 401, column: 14
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'ViewBase.unloadView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 444, column: 18
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 246, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 245, column: 14
	Frame: function:'View.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 218, column: 37
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'ViewBase.unloadView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 444, column: 18
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 246, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 245, column: 14
	Frame: function:'View.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 218, column: 37
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'ViewBase.unloadView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 444, column: 18
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 246, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 245, column: 14
	Frame: function:'View.onUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 218, column: 37
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'FrameBase.raiseCurrentPageNavigatedEvents', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 172, column: 22
	Frame: function:'FrameBase._updateBackstack', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 148, column: 14
	Frame: function:'Frame.setCurrent', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 186, column: 18
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 578, column: 53
	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 421, column: 31
	Frame: function:'Zone.runTask', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 188, column: 47
	Frame: function:'ZoneTask.invokeTask', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 496, column: 34
	Frame: function:'ZoneTask.invoke', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 485, column: 48
	Frame: function:'timer', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1561, column: 29
	Frame: function:'invoke', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 388, column: 26
	Frame: function:'Zone.runGuarded', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 151, column: 47
	Frame: function:'', file:'file:///data/data/org.taxioma/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 129, column: 29
	Frame: function:'run', file:'file:///data/data/org.taxioma/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
	at com.tns.Runtime.callJSMethod(Runtime.java:969)
	at com.tns.Runtime.callJSMethod(Runtime.java:953)
	at com.tns.Runtime.callJSMethod(Runtime.java:945)
	at com.tns.gen.android.support.v4.view.PagerAdapter_view_69_32_FragmentPagerAdapter.finishUpdate(PagerAdapter_view_69_32_FragmentPagerAdapter.java:92)
	at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1062)
	at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3089)
	at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
	at com.tns.Runtime.callJSMethod(Runtime.java:969)
	at com.tns.Runtime.callJSMethod(Runtime.java:953)
	at com.tns.Runtime.callJSMethod(Runtime.java:945)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
	at android.app.FragmentTransition.configureTransitionsReordered(FragmentTransition.java:197)
	at android.app.FragmentTransition.startTransitions(FragmentTransition.java:116)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2202)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
	at android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2019)
	at android.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:662)
	... 24 more
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.1
- Plugin(s): nativescript-google-maps-sdk@2.6.0 (https://github.com/dapriett/nativescript-google-maps-sdk)

### Please tell us how to recreate the issue in as much detail as possible.
Create one page with a tabview, second page with a map. Try to navigate from the first page to the second.

**Comment by NickIliev** [comment]
@sgornostal can you give more details on your application architecture - is the tabview a root application element with `Frame` (NativeScript ^4.0.0 feature) or part of a `Page`? A sample application demonstrating the issue would be great but if not possible please share as many details as possible about your code base.

**Comment by sgornostal** [comment]
It's an angular application.

First page:
```
<ActionBar title="Title" class="action-bar">
</ActionBar>

<StackLayout>
    <TabView class="tab-view">
        <StackLayout *tabItem="{title: 'Tab1'}">
        </StackLayout>
        <StackLayout *tabItem="{title: 'Tab2'}">
        </StackLayout>
    </TabView>
</StackLayout>
```

Second page: 
```
<ActionBar title="Map" class="action-bar">
</ActionBar>

<GridLayout>
    <MapView #mapView zoom="13" latitude="-33.86" longitude="151.20" (mapReady)="onMapReady($event)"></MapView>
</GridLayout>
```

Angular dependencies:
```
"@angular/animations": "~6.0.0",
"@angular/common": "~6.0.0",
"@angular/compiler": "~6.0.0",
"@angular/core": "~6.0.0",
"@angular/forms": "~6.0.0",
"@angular/http": "~6.0.0",
"@angular/platform-browser": "~6.0.0",
"@angular/platform-browser-dynamic": "~6.0.0",
"@angular/router": "~6.0.0",
"nativescript-angular": "~6.0.0",
```

**Comment by NickIliev** [comment]
Confirmed as a bug [here](https://github.com/dapriett/nativescript-google-maps-sdk/issues/286#issuecomment-395018089) - the issue happens only when navigatiing from a page with a `TabView`

**Comment by NickIliev** [comment]
@sgornostal  the issue can be solved by using the `TabView`as root in NativeScript 4.2.x

Here is [a demonstration application ](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-5897).

The `app.component,html` hold the root tab view
```HTML
<TabView class="tab-view">
    <StackLayout *tabItem="{title: 'Tab1'}">
        <page-router-outlet></page-router-outlet>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Tab2'}">
        <Label text="Some PAGE"   textWrap="true" class="h1"></Label>
    </StackLayout>
</TabView>
```

The routing table is a simple as (used lazily laoded map but you can use a component as well)
```JS
const routes: Routes = [
    { path: "", redirectTo: "/items", pathMatch: "full" },
    { path: "items", component: ItemsComponent },
    {
        path: "map",
        loadChildren: "./map/map.module#MapModule",
    },
];
```

The initial tab page (`items`)
```JS
import { Component } from "@angular/core";
import { RouterExtensions } from "nativescript-angular/router";
import { Page} from "tns-core-modules/ui/page";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {

    constructor(private _routerExtensions: RouterExtensions, private _page: Page) {
        this._page.actionBarHidden = true;
     }

    navigate() {
        this._routerExtensions.navigate(['/map']);
    }
}
```

and the Map page (in  this case lazily laoded via map.module)
```JS
<GridLayout rows="400" >
    <MapView row="0" (mapReady)="onMapReady($event)" backgroundColor="lightgray"></MapView>
</GridLayout>
```
