### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by momoling** [NativeScript/NativeScript#5959]
i am an newer
when i use tns-core-modules 4.0.0
the plugin nativescript-modal-datetimepicker is okay
but today i turn to tns-core-modules 4.2.0

Failed to build plugin nativescript-modal-datetimepicker :
Error: Command gradlew.bat failed with exit code 1 Error output:
 Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by NickIliev** [comment]
@momoling try removing the `platforms` and `node_ modules` folder and then rebuild the project.
Test project working as expected with the above plugin can be found [here](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-5959). Btw the latest official version of tns-core-modules is ``4.1.0
