### ISSUE TITLE
Tns run android leads to Exception in thread "main" java.io.IOException: File already exists

### ISSUE THREAD

**Issue by essadek** [NativeScript/NativeScript#5962]
I'm not able to run my project after ugrading from NS from 3.4.0 to 4.1.0 :  

```
Warning: there already is an extend called com.tns.NativeScriptActivity.
Warning: there already is an extend called com.tns.FragmentClass.
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/home/adminuser/fastmail/pardeltrack/Parcelcheck/platforms/android/app/src/main/java/com/tns/gen/java/lang/Object_picker_16_32_TimeChangedListenerImpl.java Class:
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:78)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:48)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runSbg'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
After upgrading nativescript to 4.1.1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 34s
Unable to apply changes on device: 192.168.1.7:5555. Error is: Command ./gradlew failed with exit code 1.
Executing after-watch hook from /home/adminuser/fastmail/pardeltrack/Parcelcheck/hooks/after-watch/nativescript-dev-sass.js
Stopping sass watch
Executing after-watch hook from /home/adminuser/fastmail/pardeltrack/Parcelcheck/hooks/after-watch/nativescript-dev-sass.js
```

here tns doctor  : 
```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.0 version and is up to date.
✔ Component tns-core-modules has 4.1.0 version and is up to date.
✔ Component tns-android has 4.1.3 version and is up to date.
```

**Comment by vakrilov** [comment]
Hey @essadek,
Few more questions:

1. Are you using the `nativescript-dev-webpack` plugin to bundle you app.
2. Do you have workers in your code?

You might want to check out https://github.com/NativeScript/android-runtime/issues/778. It looks like a similar problem especially if the answer of 1. is 2. is "yes".

**Comment by essadek** [comment]
hi @vakrilov 

> Are you using the nativescript-dev-webpack plugin to bundle you app.

check my package.json

>  Do you have workers in your code?
No I don't use workers at least for now

**Comment by NickIliev** [comment]
@essadek please try resetting your project by removing`node_modules`, `platforms` and `hooks` folders and then rebuild the project. If that does not solve the issue can you please share the entire content of `dependencies` and `devDependencies` of your project.

**Comment by bogdanim36** [comment]
I solved the same issue with a rebuild.

**Comment by sarfraznawaz2005** [comment]
I was getting the same error and issue was that I was using this bit of code `android.webkit.WebViewClient.extend({...}):` and more than one places. So seems like this error comes up when extending a class with same name or in the above fashion with `.extend({})`.

I didn't know how do I rename class in the case of  `.extend({})` so  I removed this from other place to fix the issue.

**Comment by lettertoamit** [comment]
I am facing same similar issue kindly help me ( I have deleted hooks + node_modules + android platform )  and installed again but things not working.

**Comment by lettertoamit** [comment]
> I am facing same similar issue kindly help me ( I have deleted hooks + node_modules + android platform ) and installed again but things not working.

done by "tns build android --bundle"

**Comment by Oscarato** [comment]
If you deployed the application before, maybe you can uninstall it and run again.
