### ISSUE TITLE
Exceptions on Android which look to occur from the HTTP component

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#598]
I really have no idea on this one. I can't seem to figure out where it's coming from or what code is causing this. Anyone seen this before or know the likely culprit?

```
W/System.err( 8208): java.io.IOException: BufferedInputStream is closed
W/System.err( 8208): 	at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:125)
W/System.err( 8208): 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
W/System.err( 8208): 	at com.tns.Async$Http$RequestResult.readResponseStream(Async.java:168)
W/System.err( 8208): 	at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:295)
W/System.err( 8208): 	at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:245)
W/System.err( 8208): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err( 8208): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err( 8208): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 8208): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 8208): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#194
