### ISSUE TITLE
Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptActivity'

### ISSUE THREAD

**Issue by momoling** [NativeScript/NativeScript#5994]
i use tns build android --bundle --env.uglify --env.aot to create a apk
some mobiles are normal
but some mobiles have problem

{
  "description": "software description",
  "license": "software license",
  "readme": "software readme",
  "repository": "software repository",
  "nativescript": {
    "id": "org.nativescript.microsoft",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.0.0",
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "nativescript-angular": "^6.0.0",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-exit": "1.0.1",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-sqlite": "^2.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toasts": "^1.0.3",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "4.2.0-2018-06-15-01",
    "validator": "^10.3.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.6.3",
    "@angular/compiler-cli": "~6.0.0",
    "@ngtools/webpack": "~6.0.3",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.5.1",
    "css-loader": "~0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.12.0",
    "nativescript-worker-loader": "~0.9.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "webpack": "~4.6.0",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0"
  },
  "author": "software author"
}

problem is
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.nativescript.microsoft/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptActivity'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2900)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1615)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6394)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1000)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:890)
Caused by: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptActivity'
	at com.tns.Runtime.createJSInstanceNative(Native Method)
	at com.tns.Runtime.createJSInstance(Runtime.java:643)
	at com.tns.Runtime.initInstance(Runtime.java:618)
	at com.tns.NativeScriptActivity.<init>(NativeScriptActivity.java:12)
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1082)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	... 9 more

**Comment by chuckmitchell** [comment]
I have this error as well, causing my app to crash. Did you find a solution? Why did you close this?

**Comment by jmihelcic** [comment]
@chuckmitchell I don't know if you're still having this issue, but we solved it by increasing the app version. 

-   Try increasing the `app version` in:
    -   "nativescript/package.json"
        ```
        "version": "0.0.0",
        ```
    -   "nativescript/app/App_Resources/Android/src/main/AndroidManifest.xml"
        ```
        android:versionCode="1"
        android:versionName="1.0"
