### ISSUE TITLE
Getting Error "Could not merge source set folders:"

### ISSUE THREAD

**Issue by lovstuf** [NativeScript/NativeScript#6088]
I'm getting error "Could not merge source set folders:"

Searching for devices...
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from D:\Projects\NativeApp\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: D:\Projects\NativeApp\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Could not merge source set folders:
[app/tns_modules/ng2-table/bundles/ng2-table.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.js     [app/tns_modules/ng2-table/bundles/ng2-table.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.js.gz: Error: Duplicate resources
[app/tns_modules/ng2-table/bundles/ng2-table.min.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.min.js     [app/tns_modules/ng2-table/bundles/ng2-table.min.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.min.js.gz: Error: Duplicate resources
        at com.android.ide.common.res2.DataSet.checkItems(DataSet.java:473)
        at com.android.ide.common.res2.DataSet.loadFromFiles(DataSet.java:261)
        at com.android.ide.common.res2.AssetSet.loadFromFiles(AssetSet.java:30)
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> [app/tns_modules/ng2-table/bundles/ng2-table.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.js   [app/tns_modules/ng2-table/bundles/ng2-table.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.js.gz: Error: Duplicate resources
  [app/tns_modules/ng2-table/bundles/ng2-table.min.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.min.js   [app/tns_modules/ng2-table/bundles/ng2-table.min.js] D:\Projects\NativeApp\platforms\android\app\src\main\assets\app\tns_modules\ng2-table\bundles\ng2-table.min.js.gz: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

**Comment by tsonevn** [comment]
Hi @lovstuf,
Can you provide more info about your environment(`tns-core-modules`, runtime and cli versions)? It will help if you send us sample project, where the issue can be reproduced.

Also, from the provided log it seems that `ng2-table` plugin might cause the issue. Regarding that, I would suggest to remove the plugin from the project, delete `node_modules`, `platforms`, `hooks` folders, remove the app from the simulator. Then, rebuild the project again via `tns run <platform_name>`.

**Comment by tsonevn** [comment]
Hi @itsmeneartou,
Can you send us the project? MeanwhileI would suggest to clear up the project following the below-attached steps and to rebuild the project:
1. delete `node_modules`, `hooks`, `platforms` folders and `package-lock.json` file 
2. run `npm i`
3. rebuild the project via `tns run android`

**Comment by itsmeneartou** [comment]
I am afraid I couldn't send the project as the source is something which I can't share. Although if there are any other subset of folders from project I will be happy to share it with you. I tried 1),2) and 3) as you said above but it didn't helped and the same errors occured again. These are the errors now.

```
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Copying template files...
Platform android successfully added. v5.1.0
Preparing project...
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\Users\karti\WebApps\abc\App_Resources\Android\app.gradle
Using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\Users\karti\WebApps\abc\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
(node:12228) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Could not merge source set folders:
[app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js    [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js.gz: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js      [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js.gz: Error: Duplicate resources
[app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js      [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js      [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js  [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js.gz: Error: Duplicate resources
        at com.android.ide.common.resources.DataSet.checkItems(DataSet.java:486)
        at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:256)
        at com.android.ide.common.resources.AssetSet.loadFromFiles(AssetSet.java:28)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.java:127)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js.gz: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js    [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js.gz: Error: Duplicate resources
  [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js    [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js    [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js        [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js.gz: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 26s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

```

**Comment by tsonevn** [comment]
HI @itsmeneartou,
Can you create a new emulator and try to deploy the app on it? Also, can you recreate the problem with a newly created project?

**Comment by itsmeneartou** [comment]
@tsonevn Thank you for your time. I used `tns run android --bundle` instead of `tns run android` and everything was working fine as mentioned in [this](https://github.com/NativeScript/nativescript-cli/issues/4316#issuecomment-458237458) comment.
