### ISSUE TITLE
Java.lang.IllegalStateException: Recursive entry to executePendingTransactions

### ISSUE THREAD

**Issue by ematechno** [NativeScript/NativeScript#6134]
### Tell us about the problem
The issue causes the crash of the APP. 

I'm not able to reproduce the issue on my IDE - I tested my APP with a real device and I didn't see any issue - Then, I uploaded the APP on Google Play Store and pre-launch test reports highlighted this issue on 6 devices out of 10 devices - I launched a ROBO test in firebase on 15 devices (real and virtual) and I faced the issue for 11 devices out of 15.

As per attached screenshot (generated by firebase ROBO Test), the issue seems to be related to "Map Page" of my APP. 

![screen](https://user-images.githubusercontent.com/40922256/43367902-c890a494-9354-11e8-86c3-0b493b8cf717.png)

Below the error message tracked by log file:

> _java.lang.IllegalStateException:

 Recursive entry to executePendingTransactions
FATAL EXCEPTION: ControllerMessenger
Process: com.ematechno.LAGECUST, PID: 9362
java.lang.IllegalStateException: Recursive entry to executePendingTransactions
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1424)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:142)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:134)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:74)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:52)
	at androidx.test.espresso.action.Tap.c(Tap.java:9)
	at androidx.test.espresso.action.Tap.a(Tap.java:19)
	at androidx.test.espresso.action.Tap$1.b(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:78)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:94)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5321)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)_ 

I attach also LOGCAT.txt with the log

[logcat.txt](https://github.com/NativeScript/NativeScript/files/2238900/logcat.txt)

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: see below
- Runtime(s): see below
- Plugin(s): see below

 "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@types/jspdf": "^1.1.31",
    "base-64": "^0.1.0",
    "jspdf": "^1.4.1",
    "nativescript-angular": "~6.0.0",
    "nativescript-appversion": "^1.4.1",
    "nativescript-camera": "^4.0.2",
    "nativescript-contacts": "^1.5.4",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-email": "^1.5.3",
    "nativescript-geolocation": "^4.3.0",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-i18n": "^0.2.4",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "^6.4.0",
    "nativescript-purchase": "^2.0.2",
    "nativescript-share-file": "^1.0.4",
    "nativescript-social-share": "^1.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-autocomplete": "^3.7.1",
    "nativescript-ui-dataform": "^3.6.1",
    "nativescript-ui-listview": "^3.5.10",
    "nativescript-ui-sidedrawer": "~4.1.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "^4.1.1",
    "zone.js": "~0.8.18"
  },

**Comment by tsonevn** [comment]
Hi @ematechno,
Can you try just for the test to remove the map from the project and to check if you will be able to recreate the problem?  If the issue persists, please send us sample project, which can be used for reproducing the issue.
If the problem is related with the `nativescript-google-maps-sdk` plugin, you can log a new issue in the [plugins repo](https://github.com/dapriett/nativescript-google-maps-sdk).
