### ISSUE TITLE
Installing NativeScript has error: error: no such option: --no-parallel

### ISSUE THREAD

**Issue by cleberjsantos** [NativeScript/NativeScript#617]
Output Eg.

```bash
  $ sudo npm install nativescript -g --unsafe-perm
  npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0
  npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
  > utf-8-validate@1.0.1 install /usr/lib/node_modules/nativescript/node_modules/utf-8-validate
  > node ./build.js

  child_process: customFds option is deprecated, use stdio instead.
  Usage: gyp_main.py [options ...] [build_file ...]

  gyp_main.py: error: no such option: --no-parallel
  gyp ERR! configure error 
  gyp ERR! stack Error: `gyp` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
  gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
  gyp ERR! System Linux 3.13.0-62-generic
  gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /usr/lib/node_modules/nativescript/node_modules/utf-8-validate
  gyp ERR! node -v v0.12.7
  gyp ERR! node-gyp -v v2.0.1
  gyp ERR! not ok 
  Build failed
  npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
  > bufferutil@1.0.1 install /usr/lib/node_modules/nativescript/node_modules/bufferutil
  > node ./build.js
```

The problem's related to the version of **node-gyp**, on the versions prior to v2.0.2, see https://github.com/nodejs/node-gyp/issues/426.

The solution is add the bellow line on the package.json  https://docs.npmjs.com/files/package.json#engines :

```json
  ...
  "engines": {
    "node-gyp" : ">=2.0.2"
  },
 ...
```

**Comment by Fatme** [comment]
This issue was moved to NativeScript/nativescript-cli#812
