### ISSUE TITLE
NativeScript 4.2: Debugging with Webpack is not working

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#6175]
Hi. When I run the app with `bundle` flag, it gives me the following errors:

```
Running webpack for Android...
C:\Users\vahidnajafi\NativeScript\tnsTab\webpack.config.js:155
            new nsWebpack.NativeScriptAngularCompilerPlugin(
            ^

TypeError: nsWebpack.NativeScriptAngularCompilerPlugin is not a constructor
    at module.exports.env (C:\Users\vahidnajafi\NativeScript\tnsTab\webpack.config.js:155:13)
    at handleFunction (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\lib\prepareOptions.js:26:13)
    at prepareOptions (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\lib\prepareOptions.js:11:13)
    at requireConfig (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\bin\convert-argv.js:98:14)
    at C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\bin\convert-argv.js:102:15)
    at yargs.parse (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\Users\vahidnajafi\NativeScript\tnsTab\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
Executing webpack failed with exit code 1.
```

**Note:** I updated all the stuffs mentioned in the blog [post](https://www.nativescript.org/blog/nativescript-4.2-is-here).

**Comment by sis0k0** [comment]
Hey @vahidvdn, you need to update your webpack configurations. We started using the `AngularCompilerPlugin` instead of the `nsWebpack.NativeScriptAngularCompilerPlugin` a few versions ago. Here's how the newest webpack config looks like - https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.angular.js. Also, if you haven't modified your webpack config, you can update to the most recent one by running that command:
```
./node_modules/.bin/update-ns-webpack --configs
```

**Comment by vahidvdn** [comment]
Thanks @sis0k0 for the reply.
I updated my webpack configuration, and now I get some other errors:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'optimization'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           optimization: ...
         }
       })
     ]
 - configuration.output has an unknown property 'globalObject'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, crossOriginLoading?, chunkLoadTimeout?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, library?, libraryTarget?, libraryExport?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
Executing webpack failed with exit code 1.
```

**Comment by sis0k0** [comment]
This is probably because you are using an old version of webpack. You need 4+. Can you share your package.json?

**Comment by vahidvdn** [comment]
@sis0k0 Yes, I only updated `nativescript-dev-webpack` to 0.15.1. Here is my webpack version:
```
"webpack": "~3.10.0",
```

Is it ok to change it to 4.0.0 and run `npm install` ?

**Comment by sis0k0** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#632
