### ISSUE TITLE
Cannot set property 'socket' of null

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#6180]
After upgrading our project to 4.2 , we've experiencing socket connections problems to a real device  when `tns run android`

Worth to mention that `tns run android` **does** work with emulators ( both Geny & AVD) , but it doesn't work with real devices.

```
C:\projects-web-storm\digital\dsapp1>tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 4.2.1 version and is up to date.
√ Component tns-core-modules has 4.2.0 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.
× Component tns-ios is not installed.
```

When `tns run android` : 

we get : 

```
Unable to apply changes on device: ce031713a8d0149e0d. Error is: Socket connection timeouted..
Executing after-watch hook from C:\projects-web-storm\digital\dsapp1\hooks\after-watch\nativescript-dev-sass.js
Executing after-watch hook from C:\projects-web-storm\digital\dsapp1\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from C:\projects-web-storm\digital\dsapp1\hooks\after-watch\nativescript-dev-webpack.js
TypeError: Cannot set property 'socket' of null
    at Timeout.tryConnect [as _onTimeout] (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\android-livesync-tool.js:298:51)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

The app IS installed but not invoked. ( it used to work) before upgrade.
We have to tap the launch icon in order to see the app running
PackageID is the **same** in all files ( manifest / packagejson)

BTW - if you want a real project that produces it , I can send privately. 

-----------

Windows machine , Android , Antivirus is disabled , uninstalled App from device.

**Comment by iguissouma** [comment]
I'm also getting same error after updating to nativescript 4.2 and just running a new created project.

**Comment by dtopuzov** [comment]
Hi @iguissouma,

Can you please specify device model and Android version of the device?

**Comment by iguissouma** [comment]
Hello @dtopuzov ,

I'm facing the problem on device and emulator.
Emulator:  Nexus 5X API 27
Device: Asus Zenfone 2 - Android version 6.0.1

**Comment by opsional** [comment]
I'm to, on Android 4.4.2 (real device), but after re-run app works.

**Comment by tsonevn** [comment]
Hi @RoyiNamir,
Can you try to clear the npm cache via `npm cache clear` delete `platforms`, `node_modules`, `hooks` folders and `package-lock.json` file? Uninstall the app from the device and rebuild it with `tns run android` command.

**Comment by RoyiNamir** [comment]
Hi @tsonevn 
Sure.

Here is the folder after  delete ( created a new folder named tsonevn): 

 
![image](https://user-images.githubusercontent.com/2842123/44019810-907f2e5a-9ee8-11e8-8041-71e039eb517d.png)


![image](https://user-images.githubusercontent.com/2842123/44019802-86e3957a-9ee8-11e8-84fa-989c1cd7a141.png)

run `npm i`

`tns run android` : 

```
C:\projects-web-storm\digital\r\tsonevn>tns run android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.       Searching for devices...
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-sass@4.9.3 install C:\projects-web-storm\digital\r\tsonevn\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-57_binding.node
Download complete  ] - :
Binary saved to C:\projects-web-storm\digital\r\tsonevn\node_modules\node-sass\vendor\win32-x64-57\binding.node
Caching binary to C:\Users\royin\AppData\Roaming\npm-cache\node-sass\4.9.3\win32-x64-57_binding.node

> node-sass@4.9.3 postinstall C:\projects-web-storm\digital\r\tsonevn\node_modules\node-sass
> node scripts/build.js
p
Binary found at C:\projects-web-storm\digital\r\tsonevn\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
s
> nativescript-angular@6.2.0-2018-08-06-03 postinstall C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-angular
> node postinstall.js
s:
/r
> nativescript-dev-sass@1.6.0 postinstall C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-dev-sass
> node postinstall.js
pmjs
org
> nativescript-dev-typescript@0.7.2 postinstall C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-dev-typescript
> node postinstall.js
/co
Adding 'es6' lib to tsconfig.json...
Adding 'dom' lib to tsconfig.json...
Adding 'es2015.iterable' lib to tsconfig.json...
Adding tns-core-modules path mappings lib to tsconfig.json...
Project already targets TypeScript ~2.7.2
z
> nativescript-dev-webpack@0.14.4 postinstall C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-dev-webpack
> node postinstall.js

The current project contains a webpack.config.js file located at C:\projects-web-storm\digital\r\tsonevn\webpack.config.js that differs from the one in the new version of the nativescript-dev-webpack plugin located at C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-dev-webpack\templates\webpack.angular.js. Some of the plugin features may not work as expected until you manually update the webpack.config.js file or automatically update it using "./node_modules/.bin/update-ns-webpack --configs" command.
Dev dependency: @angular/compiler-cli already added. Leaving version: ~6.1.0-beta.1
retr
NativeScript Webpack plugin was successfully added.
You can now bundle your project by passing --bundle flag to NativeScript CLI commands:
    - tns build android --bundle
    - tns build ios --bundle
    - tns run android --bundle
    - tns run ios --bundle
You can also pass the "--env.uglify" flag to use UglifyJS for minification.
For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.

Some dependencies have already been added. If you want to force update them, please run "node_modules/.bin/update-ns-webpack".


> nativescript-plugin-firebase@5.1.8 postinstall C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-plugin-firebase
> node postinstall-hooks.js && node scripts/postinstall.js

NativeScript Firebase Plugin Installation
Config file exists (firebase.nativescript.json)
Successfully created iOS (Pod) file.
Successfully created Android (include.gradle) file.
Install google-service.json copy hook.
Install firebase-build-gradle hook.
Writing 'firebase-build-gradle.js' to ../..//hooks/after-prepare
Firebase post install completed. To re-run this script, navigate to the root directory of `nativescript-plugin-firebase` in your `node_modules` folder and run: `npm run config`.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1472 packages in 71.011s
Executing before-liveSync hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-watchPatterns hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-watchPatterns\nativescript-dev-sass.js
Executing before-watchPatterns hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-watchPatterns\nativescript-dev-typescript.js
Executing before-watchPatterns hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-watch\nativescript-dev-sass.js
Found peer node-sass
Executing before-watch hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
Executing before-watch hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-watch\nativescript-dev-webpack.js
Copying template files...
Platform android successfully added. v4.2.0
Executing before-shouldPrepare hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Executing before-prepare hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-prepare\nativescript-dev-sass.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-prepare\nativescript-dev-typescript.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-prepare\nativescript-plugin-firebase.js
Preparing project...
Executing before-prepareJSApp hook from C:\projects-web-storm\digital\r\tsonevn\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Successfully prepared plugin @teammaestro/nativescript-svg for android.
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-appavailability for android.
Successfully prepared plugin nativescript-calendar for android.
Successfully prepared plugin nativescript-camera for android.
Successfully prepared plugin nativescript-fingerprint-auth for android.
Successfully prepared plugin nativescript-geolocation for android.
Successfully prepared plugin nativescript-imagepicker for android.
Successfully prepared plugin nativescript-iqkeyboardmanager for android.
Successfully prepared plugin nativescript-loading-indicator for android.
Successfully prepared plugin nativescript-ng-shadow for android.
Successfully prepared plugin nativescript-pdf-view for android.
Successfully prepared plugin nativescript-phone for android.
Successfully prepared plugin nativescript-plugin-firebase for android.
Successfully prepared plugin nativescript-screen-orientation for android.
nativescript-swift-3.0 is not supported for android.
Successfully prepared plugin nativescript-swift-3.0 for android.
Successfully prepared plugin nativescript-textinputlayout for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-toast for android.
Successfully prepared plugin nativescript-tslib for android.
Successfully prepared plugin nativescript-ui-listview for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin nativescript-permissions for android.
Successfully prepared plugin nativescript-ui-core for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Built aar for nativescript-calendar
Built aar for nativescript-ng-shadow
Built aar for nativescript-phone
Project successfully prepared (Android)
Executing after-prepare hook from C:\projects-web-storm\digital\r\tsonevn\hooks\after-prepare\firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from C:\projects-web-storm\digital\r\tsonevn\hooks\after-prepare\firebase-copy-google-services.js
Copy C:\projects-web-storm\digital\r\tsonevn\app\App_Resources\Android\google-services.json to C:\projects-web-storm\digital\r\tsonevn\platforms\android\google-services.json.
Note: Some input files use or override a deprecated API.digital\r\tsonevn\hooks\after-prepare\nativescript-dev-sass.js
Note: Recompile with -Xlint:deprecation for details.

Project successfully built.
Installing...
Successfully installed on device with identifier 'ce031713a8d0149e0d'.
Unable to apply changes on device: ce031713a8d0149e0d. Error is: Socket connection timeouted..
Executing after-watch hook from C:\projects-web-storm\digital\r\tsonevn\hooks\after-watch\nativescript-dev-sass.jstion\platforms\android\
Executing after-watch hook from C:\projects-web-storm\digital\r\tsonevn\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watchxArchiveWithDexMergerForDebugfects-web-storm\digital\r\tsonevn\node_modules\nativescript-ng-shadow\platforms\android\na
Executing after-watch hook from C:\projects-web-storm\digital\r\tsonevn\hooks\after-watch\nativescript-dev-webpack.js
TypeError: Cannot set property 'socket' of null
    at Timeout.tryConnect [as _onTimeout] (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\android-livesync-tool.js:298:51)XECUTING [7s]dency: C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-plugin-firebase\platforms\andr
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)cy: C:\projects-web-storm\digital\r\tsonevn\node_modules\nativescript-ui-listview\platforms\android\
    at Timer.listOnTimeout (timers.js:277:5)
```
