### ISSUE TITLE
Nativescript videoplayer not showing when using webpack (iOS)

### ISSUE THREAD

**Issue by jannotabamo** [NativeScript/NativeScript#6250]
### Tell us about the problem
I used `nativescript-videoplayer` to show videos in the app. I load videos using url. When I run the app using `tns build/run ios` the video shows up and working fine. But when I integrated the webpack `tns build/ios --bundle` the video now doesn't shows up. I replicated the issue by creating a new app and installing the `nativescript-videoplayer` and integrated with the latest nativescript-webpack version and the problem shows up. Hope you could help me with some workaround cause I can't proceed because of this issue.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s): `nativescript-videoplayer v4.2.0`

### Please tell us how to recreate the issue in as much detail as possible.
- create new tns angular app `tns create appName --template angular`
- install the videoplayer plugin `tns plugin add nativescript-videoplayer`
- register the nativescript-videoplayer element.
- use the plugin and use a remote video url
- and run it with webpack.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
<VideoPlayer
        src="sourceUrl"
    	autoplay="false"
    	width="100%"
    	height="80%"
    	horizontalAlignment="center"></VideoPlayer>
```

**Comment by NickIliev** [comment]
@jannotabamo where is your `sourrceUrl` pointing to? If the video is located in a folder within the application then you should explicitly add it to your `webpack.comfig.js` file (e.g. as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/webpack.config.js#L213) for the `fonts` folder).

For example, if your video files ar located in `app/movies` folder then add

```JS
new CopyWebpackPlugin([
                { from: "movies/**" },
                // more code follows here
```

Closing this issue as duplicate to [https://github.com/nstudio/nativescript-videoplayer/issues/121](https://github.com/nstudio/nativescript-videoplayer/issues/121)

**Comment by jannotabamo** [comment]
@NickIliev its not located within the application. It is hosted from the cloud, and I'm just getting its url to display video. I use `cloudinary` to store videos there and just getting its url and show it on the app using VideoPlayer plugin.

**Comment by NickIliev** [comment]
@jannotabamo  is it possible to share a link for a video file from Cloudinary? (so I could test it on my side)

**Comment by jannotabamo** [comment]
@NickIliev [here is the sample project I created](https://github.com/jannotabamo/NS-VideoPlayer-Issue) with `nativescript-videoplayer` on it and a sample cloudinary link.

**Comment by NickIliev** [comment]
@jannotabamo I am able to successfully build the application and run the video using Webpack.

Few changes made:
- pass the source without space at the end of the string
```XML
src="https://res.cloudinary.com/dhbxjkfbn/video/upload/v1535091529/yudabands/resources/Short_insta_video_by_lauren.mp4"
```

- Using the following versions  in package.json

```JSON
{
  "nativescript": {
    "id": "org.nativescript.videoPlayerTest",
    "tns-ios": {
      "version": "4.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-videoplayer": "^4.2.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.0.0",
    "tns-core-modules": "~4.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.1.0",
    "nativescript-dev-typescript": "~0.7.3",
    "nativescript-dev-webpack": "^0.16.0",
    "typescript": "~2.7.2"
  },
  "readme": "NativeScript Application"
}
```

Then performing a clean rebuild of the project
```
rm -rf node_modules platforms hooks webpack.config.js
npm i 
tns platform add ios
tns build ios
tns run ios --bundle
```

**Comment by jannotabamo** [comment]
@NickIliev it is now working now. But I got a little problem running it together with `--env.aot`. There is an error shows up when bundling together with `--env.aot`.

`ERROR in : TypeError: Cannot read property 'getSymbolAtLocation' of undefined
    at visit (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/transformers/elide_imports.js:39:40)
    at visitNode (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:13430:24)
    at visit (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/transformers/elide_imports.js:54:12)
    at visitNode (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:13488:24)
    at visit (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/transformers/elide_imports.js:54:12)
    at visitNodes (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:13272:30)
    at Object.forEachChild (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:13479:24)
    at Object.elideImports (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/transformers/elide_imports.js:28:8)
    at transformer (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/transformers/make_transform.js:34:51)
    at /Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:2892:86
    at reduceLeft (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:2585:30)
    at /Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:2892:42
    at transformRoot (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:67846:82)
    at Object.map (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:1883:29)
    at Object.transformNodes (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:67834:30)
    at Object.emitFiles (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:70664:28)
    at emitWorker (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:74509:33)
    at /Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:74469:66
    at runWithCancellationToken (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:74560:24)
    at Object.emit (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/typescript/lib/typescript.js:74469:20)
    at defaultEmitCallback (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@angular/compiler-cli/src/transformers/program.js:91:24)
    at AngularCompilerProgram._emitRender2 (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@angular/compiler-cli/src/transformers/program.js:415:34)
    at AngularCompilerProgram.emit (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@angular/compiler-cli/src/transformers/program.js:236:22)
    at AngularCompilerPlugin._emit (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:846:49)
    at Promise.resolve.then.then.then (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-VideoPlayer-Issue/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:672:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by jannotabamo** [comment]
@NickIliev Also, I can't upgrade to the latest version of webpack because of this error created by this plugin `nativescript-ios-uuid`. I need this plugin to get the device UUID of ios devices. I can't uninstall this plugin. Are there any workaround for this plugin to work with latest version of webpack? badly need it.

```
ERROR in ../node_modules/nativescript-ios-uuid/index.ts
Module build failed: Error: /Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-iOS-uuid-Issue/node_modules/nativescript-ios-uuid/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-iOS-uuid-Issue/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:753:23)
    at plugin.done.then (/Users/hyperstacks-002/Desktop/philipwhiting/ios/NS-iOS-uuid-Issue/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./item/items.component.ts 8:21-53
 @ ./app.module.ts
 @ ./main.ts
```
