### ISSUE TITLE
[BUG] Reopen app by clicking on app's icon crashes on Android

### ISSUE THREAD

**Issue by tdhman** [NativeScript/NativeScript#6251]
Hello,

I'am using NativeScript Vue to develop my application. My application has only 1 main view containing a web view. When testing on Android simulator, reopening the application by clicking on the app's icon causes the app crashes with error `Error: View already has a parent` .
However, the application can be reopened by clicking on the snapshot of the Recent open app: Click on button (recent app) or double tap on Home, then Recent open app list appears, click on the application snapshot --> works.

The bug trace as following:

```
09-10 11:28:54.017 16920 16920 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
09-10 11:28:54.017 16920 16920 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
09-10 11:28:54.017 16920 16920 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
09-10 11:28:54.017 16920 16920 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
09-10 11:28:54.017 16920 16920 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
09-10 11:28:54.017 16920 16920 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreateView failed
System.err: 
System.err: Error: View already has a parent. View: Page(5) Parent: Frame(13)
System.err: File: "file:///data/data/xxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js, line: 417, column: 12
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/xxx/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 417, column: 19
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/xxx/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 590, column: 24
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/xxx/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err: 	at android.app.Fragment.performCreateView(Fragment.java:2508)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
System.err: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
System.err: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
System.err: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
System.err: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Which platform(s) does your issue occur on?
Android

### Code

My view template is a Page which contains a GridLayout. There are only 2 components: TopBar (my custom ActionBar) and Webview

```
<template>
  <Page :class="pageClasses" actionBarHidden="true" @loaded="pageLoaded" @unloaded="pageUnloaded" backgroundSpanUnderStatusBar="true" backgroundColor="#005686">
    <GridLayout class="container" columns="*" rows="auto, *" backgroundColor="transparent">
      <topbar row="0" col="0"
        @profil="onProfile"
        @logout="doLogout"
        @notification="onNotification"
        brand="ABC" 
        application="My App" />
      <WebView ref="webview" row="1" col="0" id="wv" height="100%"/>
    </GridLayout>
  </Page>
</template>
```

Thank you for any help.

**Comment by NickIliev** [comment]
This issue was moved to nativescript-vue/nativescript-vue#320
