### ISSUE TITLE
Breakpoint not hit with launch options in OSX but attach

### ISSUE THREAD

**Issue by DavoBR** [NativeScript/NativeScript#6265]
**tns doctor result:**

DAVID-MAC:~ davo$ tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.2.3 version and is up to date.

VSCode version: 1.27.2

**Symptoms:**

1.  Breakpoint not hit when a i choose "Launch on iOS" options to start debug but work when i choose "Attach on iOS" 

2. I get this when start debug in VSCode

Traceback (most recent call last):

  File "<input>", line 1, in <module>

  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref

  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (

ImportError: cannot import name _remove_dead_weakref

TypeError: Cannot set property 'deviceIdentifier' of undefined
    at SocketProxyFactory.<anonymous> (/Users/davo/.nvm/versions/node/v10.10.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:88:46)
    at Generator.throw (<anonymous>)
    at rejected (/Users/davo/.nvm/versions/node/v10.10.0/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-vscode-extension#207
