### ISSUE TITLE
Android crashes: getChildDrawingOrder() returned invalid index 1

### ISSUE THREAD

**Issue by dbenninger** [NativeScript/NativeScript#6267]
We get many crash reports like that:
````
java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
	at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:1802)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3751)
	at android.view.View.draw(View.java:18401)
	at android.view.View.updateDisplayListIfDirty(View.java:17376)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3778)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.draw(View.java:18401)
	at android.view.View.updateDisplayListIfDirty(View.java:17376)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.updateDisplayListIfDirty(View.java:17371)
	at android.view.View.draw(View.java:18160)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
	at android.view.View.draw(View.java:18401)
	at com.android.internal.policy.DecorView.draw(DecorView.java:966)
	at android.view.View.updateDisplayListIfDirty(View.java:17376)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:722)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:728)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:836)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3168)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2964)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2552)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
	at android.view.Choreographer.doCallbacks(Choreographer.java:734)
	at android.view.Choreographer.doFrame(Choreographer.java:670)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
````

I have no clue which component might cause this. 

### Which platform(s) does your issue occur on?
Android only

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.1
- Runtime(s): 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.
I don't know how to reproduce

**Comment by NickIliev** [comment]
@dbenninger try to isolate the case locally in a sample app or Playground. If this error is received via Crashlytics or similar reporting service please post as much information as possible about the type of devices that are hitting the issue (API level/ model). Let us know if you are using some specific UI plugin (post the content of `package.json` file). 

You could also update the application to the latest version of runtimes and tns-core0-modules and retest the scenario.

The method is part of [android's ViewGroup](https://developer.android.com/reference/android/view/ViewGroup) so check if you are using ListView and trying to access invalid item index at some point. Also, check if any third-party UI plugin is using ViewGroup in its own logic.

**Comment by dbenninger** [comment]
@NickIliev thank you, I will do that.

**Comment by quantumpotato** [comment]
@dbenninger any update?

**Comment by dbenninger** [comment]
I never found out what caused the crash. We updated tns-core-modules, nativescript, webpack and angular to the latest versions and it disappeared. Back then the versions were:
@angular ~6.1.0
"nativescript-angular": "^6.1.0",
"@ngtools/webpack": "~6.2.0",
"nativescript": "^4.2.3",
"tns-core-modules": "^4.2.0",
