### ISSUE TITLE
Setting string value to `width` or `height` of ImageAssetOptions results in an error on android

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/NativeScript#6289]
### Tell us about the problem
Setting string value to `width` or `height` of ImageAssetOptions results on the following error on android API level 22:
```
System.err: java.lang.RuntimeException: Unable to resume activity {org.nativescript.preview/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: bitmap size exceeds 32 bits
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.IllegalArgumentException: bitmap size exceeds 32 bits
```

### Which platform(s) does your issue occur on?
Android, older API levels, works on API 27

### Please tell us how to recreate the issue in as much detail as possible.
Can be easily reproduced with the nativescript-imagepicker demo, by returning string("300") from [this method](https://github.com/NativeScript/nativescript-imagepicker/blob/4992d660bcfb3d33ad0f96d4e45170d79bea1fc0/demo/app/main-view-model.ts#L20) and then picking single image

**Comment by Dheeraj12121** [comment]
guide me to reproduce the steps.

**Comment by ravin00** [comment]
can you be more specific with the error.

**Comment by azizur-rahaman** [comment]
is this issue still open? Can I give it a try
