### ISSUE TITLE
Error thrown when calling method getEntities() on Folder

### ISSUE THREAD

**Issue by digitalhurricane-io** [NativeScript/NativeScript#6333]
This issue occurs on Android. I have not tested on iOS.

I am using angular but I am posting the issue here because the file system code is in this repo.

Here are the devices I've run the code on:

emulator: Pixel 2 API 22           Android 5.1
emulator: Pixel 2 API 27           Android 8.1
real device: Huawei Honor 6x   Android 7.0

The Folder.getEntities method works as expected on android 5.1 but fails on 8.1 and 7.0

The code to reproduce is:

  let folderPath=android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS).toString();
    let folder = fs.Folder.fromPath(folderPath);

    console.log(folder.path);
    console.log(fs.Folder.exists(folder.path));
    console.log(folder.contains('collegeDrop.mp3'));
    
    folder.getEntities()
    .then(entities => {
        // entities is array with the document's files and folders.
        entities.forEach(entity => {
            // console.log(entity.name);
            // console.log(entity.path);
            // console.log(entity.lastModified);
            console.log(entity);
        });
    }).catch(err => {
        // Failed to obtain folder's contents.
        console.log(err.stack);
    });
---------------------------------------------------------------------------
The error message is this:

TypeError: Cannot read property 'length' of null
    at FileSystemAccess.enumEntities (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/tns-core-modules/file-system/file-system-access.js:329:36)
    at FileSystemAccess.getEntities (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/tns-core-modules/file-system/file-system-access.js:66:14)
    at Folder.getEntitiesSync (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/tns-core-modules/file-system/file-system.js:385:41)
    at file:///data/data/org.nativescript.musicapp/files/app/tns_modules/tns-core-modules/file-system/file-system.js:378:34
    at new ZoneAwarePromise (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)
    at Folder.getEntities (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/tns-core-modules/file-system/file-system.js:372:16)
    at FileSystemService.getFolders (file:///data/data/org.nativescript.musicapp/files/app/app/shared/services/file-system.service.js:14:16)
    at Object.eval [as handleEvent] (ng:///HomeModule/SongsComponent.ngfactory.js:15:34)
    at handleEvent (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/@angular/core/bundles/core.umd.js:10282:45)
    at callWithDebugContext (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11375:29)
    at Object.debugHandleEvent [as handleEvent] (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11078:16)
    at dispatchEvent (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/@angular/core/bundles/core.umd.js:7741:29)
    at file:///data/data/org.nativescript.musicapp/files/app/tns_modules/@angular/core/bundles/core.umd.js:8185:42
    at file:///data/data/org.nativescript.musicapp/files/app/tns_modules/nativescript-angular/renderer.js:185:26
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.musicapp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:26)

--------------------------------------------------------------------------

CLI version : 4.2.4
Cross-platofrom modules: version: 4.2.1
Android runtime: 4.2.0
Plugins: 

Plugin                            │ Version │
│ @angular/animations               │ ~6.1.0  │
│ @angular/common                   │ ~6.1.0  │
│ @angular/compiler                 │ ~6.1.0  │
│ @angular/core                     │ ~6.1.0  │
│ @angular/forms                    │ ~6.1.0  │
│ @angular/http                     │ ~6.1.0  │
│ @angular/platform-browser         │ ~6.1.0  │
│ @angular/platform-browser-dynamic │ ~6.1.0  │
│ @angular/router                   │ ~6.1.0  │
│ nativescript-angular              │ ~6.1.0  │
│ nativescript-sqlite               │ ^2.2.3  │
│ nativescript-theme-core           │ ~1.0.4  │
│ nativescript-ui-sidedrawer        │ ~4.2.0  │
│ reflect-metadata                  │ ~0.1.10 │
│ rxjs                              │ ~6.2.0  │
│ tns-core-modules                  │ ~4.2.0  │
│ zone.js                           │ ~0.8.18 │
└───────────────────────────────────┴─────────┘
Dev Dependencies:
┌─────────────────────────────┬─────────┐
│ Plugin                      │ Version │
│ @angular/compiler-cli       │ ~6.1.0  │
│ @nativescript/schematics    │ ~0.2.5  │
│ @ngtools/webpack            │ ~6.2.0  │
│ codelyzer                   │ ~4.3.0  │
│ nativescript-dev-sass       │ ~1.6.0  │
│ nativescript-dev-typescript │ ~0.7.0  │
│ nativescript-dev-webpack    │ ~0.16.0 │
│ tns-platform-declarations   │ ^4.2.1  │
│ tslint                      │ ~5.11.0 │
│ typescript                  │ ~2.7.2

**Comment by digitalhurricane-io** [comment]
Needed to ask for storage permissions. It's working after granting storage permissions. My bad.
