### ISSUE TITLE
Attempt to invoke method on a null object reference

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6479]
Errors coming from Crashlytics (relatively rarely seen). All the errors are related to calling a method on a native object.

The errors below are happening on an application that is using the experimental feature `markingMode` set to `none` and might be related to GC.

The below errors does not have stable ways and detailed steps to reproduce so any additional information that can help to reproduce a similar crash can be logged here.

Reported via t.1348839  t.1348832, t.1348831, and t.1348830 

**_Error logs as follows (the two of them directly related to `RadListView` moved to nativescript-ui-feedback repository):_** 

**Error 3** (firebase plugin)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke direct method 'java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[])' on a null object reference
       at com.tns.Runtime.callJSMethod(Runtime.java:983)
       at com.tns.Runtime.callJSMethod(Runtime.java:967)
       at com.tns.Runtime.callJSMethod(Runtime.java:959)
       at com.tns.gen.org.nativescript.plugins.firebase.FirebasePluginListener.success(FirebasePluginListener.java:16)
       at org.nativescript.plugins.firebase.FirebasePlugin$2.run(FirebasePlugin.java:34)
```

**Error 4** (possibly TabView or another UI control/plugin)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.tns.gen.android.support.v4.view.PagerAdapter_script_37_1249387_r.isViewFromObject(PagerAdapter_script_37_1249387_r.java:105)
       at android.support.v4.view.ViewPager.infoForChild(ViewPager.java:1514)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1255)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:17637)
       at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
       at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
       at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
       at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
       at android.view.View.measure(View.java:17637)
       at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
       at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
       at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
       at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
       at android.view.View.measure(View.java:17637)
       at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
       at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
       at android.view.View.measure(View.java:17637)
       at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
       at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
       at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
       at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
       at android.view.View.measure(View.java:17637)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2019)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1177)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1383)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)
```

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#911

**Comment by NickIliev** [comment]
Update from @DickSmith regarding **_Error 4_** 

> 
>... I call it that because it references com.tns.gen.* which means it's one of the Java classes generated by ASBG. These only started to arise after enabling the discardUncaughtJsExceptions flag, since they all, of course, call the dispatchCallJSMethodNative and without that flag were crashing in that method rather than the ASBG method on return as they are now. They are still a valid issue though, since many users will enable that to reduce crashes in release, like we have.
> 
> Until now these had been lower priority crashes, so I hadn't emphasized them much, although they can be a bit deceptive, as the name of that class is dictated by the INTERFACE_FILE_LINE_COLUMN_CLASSNAME of the JS that caused it to be generated, and since even the slightest change of the JS will cause this to be different, it will be reported by Crashlytics as a new crash for each version and not aggregated over multiple versions like other crashes are. In fact, since we released a new version yesterday, it now manifests as:
> 
> PagerAdapter_script_37_1250195_r.java line 105
> com.tns.gen.android.support.v4.view.PagerAdapter_script_37_1250195_r.isViewFromObject
> As you can see, the column has changed. (Since we use webpack/uglify, this does get obfuscated a bit, but I can usually open that APK, search for that file and column i the JS code, and then from there find something identifiable nearby to allow me to figure out where it originated from.)
> 
> Like mentioned before, these "ASBG" crashes have gone on to small extant for a while, in various places (and I believe have probably been reported by other users who have enabled this flag at this point). This one is a bit more common now, since the prominence and complexity of using the tabs for bottom navigation makes it a more frequent possibility.
> 
> The further complication of these crashes, if you notice, comes from the fact that the failed method is Boolean.booleanValue() which isn't actually generated by ASBG:
> 
> public boolean isViewFromObject(android.view.View param_0, java.lang.Object param_1)  {
>     java.lang.Object[] args = new java.lang.Object[2];
>     args[0] = param_0;
>     args[1] = param_1;
>     return (boolean)com.tns.Runtime.callJSMethod(this, "isViewFromObject", boolean.class, args);
> }
> This is because once compiled (and decompiled) the actual representation of this class is:
> 
> public boolean isViewFromObject(View view, Object obj) {
>     return ((Boolean) Runtime.callJSMethod((Object) this, "isViewFromObject", Boolean.TYPE, view, obj)).booleanValue();
> }
> Where we can see, among other differences, that a cast of (boolean)thing becomes instead a cast of ((Boolean)thing).booleanValue().
> 
> The other, smaller, crash that I have mentioned that also suffers from this situation is:
> 
> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
> com.tns.gen.java.lang.Object_script_37_634402_n.onTouch (Object_script_37_634402_n.java:18)
> and with some further searching I found a single occurrence for:
> 
> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
> com.tns.gen.android.widget.Spinner_script_37_1312098_n.performClick (Spinner_script_37_1312098_n.java:46)
> In some searching of the older Object/onClick one and identifying the JS that produced it, there doesn't seem to be a way to guard these in the JS code. As such, the guarding likely needs to be done in the Android runtime somewhere. Since it appears that this situation only arises when dealing with Boolean types, the solution, either in the ASBG generation for Boolean types, or in the dispatchCallJSMethodNative method when the type is Boolean.
> 
> Since putting the guard in the ASBG would require a lot of extra boilerplate to get generated with these (and thus not being very DRY) the best solution might be to set fall back here to be "false" if the returnType is boolean, since this is the case with "null" in JS truthiness evaluation. Even though callJSMethod doesn't appear in that stack, it must be still being call there and returning null for it to reach the booleanValue() method. If  that still doesn't seem to guard it, then instead the ASBG generation for Booleans in particular may need to be adjusted, but this would be non-deal, of course.

**Comment by NathanaelA** [comment]
I want to chime in I've seen "error 4" (the boolean / null crash) before many many times.   Most the time people don't realize it as being a major error;  because it changes locations based on the line number that the JS code is on and that will change its signature.

**Comment by NickIliev** [comment]
Closing this one as it appears related to a variety of different issues (most likely occurring when an object is cleared and try to invoke a method that belongs to that very same object). As discussed with @DickSmith and @vtrifonov the issue can be approached globally by providing a flag to suspend the rare cases where a similar scenario would happen.

Closing via  [https://github.com/NativeScript/android-runtime/pull/1207](https://github.com/NativeScript/android-runtime/pull/1207)
