### ISSUE TITLE
Error end of file

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6492]
Running VS on Windows 10 for android I get an end of file error.
 I assume the file concerns  @file:///app/home-page/parts/part/elaboration/elaboration.xml:28:15. 
I have added this file below. The file is included as a component in the main xml. What might be wrong ?

```
[NativeScriptCli] execute: tns --analyticsClient VSCode --versionC:\Users\Jokro\Software\NativeScript\mappi\app\home-page\parts\part\elaboration\elaboration.xml
Version: 0.8.3
Build version: v.2018.10.19.1
Commit id: 3d1f5eb4413af34503e018fe35ccf21831c4b1d9
NativeScript CLI: 4.2.4
[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NSDebugAdapter] Using tns CLI v4.2.4 on path 'tns'

[NSDebugAdapter] Running tns command...

[NativeScriptCli] execute: tns --analyticsClient VSCode debug android --watch 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token

Searching for devices...

Starting Android emulator with image Emulator-Api25-Default-haxm

Waiting for emulator device initialization...


Skipping prepare.

Successfully transferred elaboration-edit.xml.

Successfully transferred elaboration.xml.
Successfully transferred name-edit.js.
Successfully transferred name-edit.xml.
Successfully transferred name.xml.
Successfully transferred parts.xml.

Using  C:\Users\Jokro\Software\NativeScript\mappi\platforms\android\app\build\outputs\apk\debug\app-debug.apk

device: emulator-5554 debug port: 40000


# NativeScript Debugger started #

JS: finish map.constructor.........

To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000


11-02 07:57:48.168 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethodNative(Native Method)

11-02 07:57:48.168 27275 27275 W ExifInterface: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
11-02 07:57:48.168 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
11-02 07:57:48.168 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
11-02 07:57:48.168 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
11-02 07:57:48.168 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)

JS:  onLoaded HOME page ......

11-02 07:57:48.197 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethodNative(Native Method)

11-02 07:57:48.197 27275 27275 W ExifInterface: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
11-02 07:57:48.197 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)

11-02 07:57:48.197 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
11-02 07:57:48.197 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
11-02 07:57:48.197 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)

11-02 07:57:48.199 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethodNative(Native Method)

11-02 07:57:48.199 27275 27275 W ExifInterface: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
11-02 07:57:48.199 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
11-02 07:57:48.199 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
11-02 07:57:48.199 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
11-02 07:57:48.199 27275 27275 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)

System.err: com.tns.NativeScriptException: 

System.err: Calling js method getView failed
System.err: 
System.err: Error: Building UI from XML. @file:///app/home-page/home-page.xml:35:25
System.err:  > Building UI from XML. @file:///app/home-page/parts/parts.xml:36:9
System.err:    > Building UI from XML. @file:///app/home-page/parts/part/elaboration/elaboration.xml:28:15

System.err:    > end file
System.err: File: "file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 331, column: 20
System.err: 

System.err: StackTrace: 
System.err: 	Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
System.err: 	Frame: function:'SourceError', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23

System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 331, column: 33

System.err: 	Frame: function:'XmlArgsReplay.replay', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 326, column: 23
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 411, column: 23

System.err: 	Frame: function:'parse', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 21, column: 16
System.err: 	Frame: function:'createView', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/list-view/list-view-common.js', line: 30, column: 38

System.err: 	Frame: function:'ListViewAdapter.getView', file:'file:///data/data/org.nativescript.mappi/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 251, column: 33
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)

System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.android.widget.BaseAdapter_view_201_32_ListViewAdapter.getView(BaseAdapter_view_201_32_ListViewAdapter.java:52)
System.err: 	at android.widget.AbsListView.obtainView(AbsListView.java:2363)
System.err: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
System.err: 	at android.widget.ListView.onMeasure(ListView.java:1233)

System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.AbsoluteLayout.onMeasure(AbsoluteLayout.java:33)
System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)

System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)

System.err: 	at android.view.View.measure(View.java:19857)
System.err: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
System.err: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)

System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)

System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:621)

System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

[NSDebugAdapter] Ready to attach to application on 40000

```

The file contains:

```
<!-- home-page/parts/part/elaboration/elaboration.xml-->

 <StackLayout xmlns:edit="home-page/parts/part/elaboration/elaboration-edit">
 
    <StackLayout  visibility="{{elaboration.isVisible, elaboration.isVisible ? 'visible':'collapse'}}"
                class="{{name.type, name.type==='title' ? 'center' : 'left'}}"  
    >
        <!-- elaboration view -->
        <StackLayout visibility="{{elaboration.isEditable, elaboration.isEditable ? 'collapse' : 'visible'}}"
                        orientation="horizontal"
                        class="{{elaboration.class}}" 
        >
            <!--Image src="{{ image }}" class="thumb img-circle" /-->
            <!--longPress="on_part_elaboration_startEdit"-->
            <Label  text="{{elaboration.text}}" 
                    class="elaboration text-center" 
                    textWrap="true"
            />
        </StackLayout>

    </StackLayout> 

    <!--edit-->
    <StackLayout visibility="{{elaboration.isEditable,elaboration.isEditable ? 'visible' : 'collapse'}}">
        <edit:elaboration-edit/>
    <StackLayout>

</StackLayout>
```

N.B. if I remove <edit:elaboration-edit/> the problems stays.

**Comment by jokro** [comment]
The first lines of elaboration.xml are not shown above. They are:

 ```
<!-- home-page/parts/part/elaboration/elaboration.xml-->

 <StackLayout xmlns:edit="home-page/parts/part/elaboration/elaboration-edit">
 
    <StackLayout  visibility="{{elaboration.isVisible, elaboration.isVisible ? 'visible':'collapse'}}"
                class="{{name.type, name.type==='title' ? 'center' : 'left'}}"  
    >
        <!-- elaboration view -->

```  etc

**Comment by jokro** [comment]
I provided an example of the bug in [playgroun](https://play.nativescript.org/?template=play-tsc&id=MSdKXN&v=10)

**Comment by jokro** [comment]
Problem solved. A slash was missing in tagname. The compiler did not report this, which is a bug,
