### ISSUE TITLE
Resources$NotFoundException on app suspend/resume after navigation with long Slide transition

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#6510]
1. Create new app with root frame
2. From default page navigate to a second page via button tap like this:
``` ts
export function onTap(args) {
    const navigationEntry = {
        moduleName: "home/second-page",
        animated: true,
        transition: {
            name: "slide",
            duration: 2000,
            curve: "easeIn"
        }
    };

    args.object.page.frame.navigate(navigationEntry);
}
```
3. Suspend the app
4. Resume the app -- slide animation erroneously starts executing and mid-way crashes the app with the following exception:
```
An uncaught Exception occurred on "main" thread.
android.content.res.Resources$NotFoundException: Unable to find resource ID #0xfffffff6
	at android.content.res.ResourcesImpl.getResourceTypeName(ResourcesImpl.java:271)
	at android.content.res.Resources.getResourceTypeName(Resources.java:1986)
	at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1172)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1808)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Egor3f** [comment]
Here is another example of this bug, with shorter transition duration, but existing nested frames: https://github.com/NativeScript/android-runtime/issues/1218
Error does not happen, if I just copy-paste https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/transition/slide-transition.android.ts class into my project and use transition: {instance: }}

**Comment by manoldonev** [comment]
@Egor3f the exception is the same but as far as I can tell this one and [the one](https://github.com/NativeScript/NativeScript/issues/6698) you logged are two separate issues. https://github.com/NativeScript/NativeScript/issues/6698 (nested fragments case) should be addressed with https://github.com/NativeScript/NativeScript/pull/6677 while this one is still open and under investigation.

**Comment by manoldonev** [comment]
@Egor3f we are planning to include https://github.com/NativeScript/NativeScript/pull/6677 in tns-core-modules@5.1.1 patch release before Christmas but the fix is already available in tns-core-modules@next so you can test it if necessary.
