### ISSUE TITLE
Resources$NotFoundException with nested frame Slide navigation and app suspend/resume

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#6633]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1
 - Cross-platform modules: 5.0.5
 - Android Runtime: 5.0.0

**Describe the bug**
```
An uncaught Exception occurred on "main" thread.
android.content.res.Resources$NotFoundException: Unable to find resource ID #0xfffffff6
	at android.content.res.Resources.getResourceTypeName(Resources.java:2273)
	at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1172)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1543)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
```
After a specific set of navigation actions in a nested frame scenario with Slide transition and app suspend/resume.

**To Reproduce**
1. Tap "navigate to some page" (parent frame navigation)
2. Go back via hardware button (parent frame back navigation)
3. Tap "Player Two" (nested frame navigation)
4. Suspend and resume the app
5. Tap "navigate to some page" -- app crashes with exception above 

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=BZfk8A&v=3 NOTE: playground sample crashes with a different exception as it is not using the latest binaries -- use just the source files for reference!

Use the attached zip to debug:  [NSPlayground.zip](https://github.com/NativeScript/NativeScript/files/2624212/NSPlayground.zip)

**Comment by manoldonev** [comment]
Fixed with https://github.com/NativeScript/NativeScript/pull/6677
