### ISSUE TITLE
Crash on master-detail template when navigate back and open same items again

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/NativeScript#6746]
**Environment**
 - CLI: latest
 - Other version listed in package.json bellow.

**Describe the bug**
App crash when navigate back and open same item.
It happens on both JS and TS templates and it is fine in NG template.

**To Reproduce**
```
tns create TestApp --template https://github.com/NativeScript/template-master-detail
tns run android
click on BMW 5 Series
navigate back
open BMW 5 Series again -> app crash
```

**Expected behavior**
No crashes.

**Sample project**
```
{
    "nativescript": {
        "id": "org.nativescript.MDApp",
        "tns-android": {
            "version": "5.1.0"
        },
        "tns-ios": {
            "version": "5.1.0"
        }
    },
    "description": "NativeScript Application",
    "scripts": {
        "lint": "eslint \"app/**/*.js\""
    },
    "dependencies": {
        "nativescript-imagepicker": "~6.0.0",
        "nativescript-plugin-firebase": "~7.4.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-listview": "~5.0.0",
        "tns-core-modules": "~5.1.0",
        "rxjs": "~6.3.0"
    },
    "devDependencies": {
        "eslint": "~5.8.0",
        "nativescript-dev-sass": "~1.6.0",
        "nativescript-dev-webpack": "~0.18.0"
    },
    "readme": "NativeScript Application"
}

```

**Crash logs**
```
01-01 23:56:49.203  5804  5804 I art     : Not late-enabling -Xcheck:jni (already on)
01-01 23:56:49.208  1573  2094 I ActivityManager: Start proc 5804:org.nativescript.MDApp/u0a64 for activity org.nativescript.MDApp/com.tns.NativeScriptActivity
01-01 23:56:49.212  1262  1643 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1536000
01-01 23:56:49.231  1680  2067 D EGL_emulation: eglMakeCurrent: 0xadd69100: ver 3 0 (tinfo 0xab588bd0)
01-01 23:56:49.233  1923  2084 D EGL_emulation: eglMakeCurrent: 0xaf0144e0: ver 3 0 (tinfo 0xaf012370)
01-01 23:56:49.236  1923  2084 E Surface : getSlotFromBufferLocked: unknown buffer: 0xa3b963c0
01-01 23:56:49.249  5804  5818 E ActivityThread: Failed to find provider info for com.google.android.gms.phenotype
01-01 23:56:49.259  5804  5821 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
01-01 23:56:49.268  5804  5804 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-01 23:56:49.268  5804  5804 I FirebaseInitProvider: FirebaseApp initialization successful
01-01 23:56:49.281  5804  5804 I TNS.Native: NativeScript Runtime Version 5.1.0, commit 4497f43b69cb57ce65ece2aac5b98b2010f85857
01-01 23:56:49.281  5804  5804 D TNS.Native: JNI_ONLoad
01-01 23:56:49.281  5804  5804 D TNS.Native: JNI_ONLoad END
01-01 23:56:49.290  5804  5825 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
01-01 23:56:49.294  5804  5818 I FA      : App measurement is starting up, version: 13001
01-01 23:56:49.294  5804  5818 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
01-01 23:56:49.294  5804  5818 I FA      : To enable faster debug mode event logging run:
01-01 23:56:49.294  5804  5818 I FA      :   adb shell setprop debug.firebase.analytics.app org.nativescript.MDApp
01-01 23:56:49.296  5804  5825 W GooglePlayServicesUtil: Google Play Store is missing.
01-01 23:56:49.320  5804  5830 E FirebaseInstanceId: Google Play services missing or without correct permission.
01-01 23:56:49.331  5804  5804 D TNS.Native: V8 version 6.9.427.23
01-01 23:56:49.333  5804  5818 W GooglePlayServicesUtil: Google Play Store is missing.
01-01 23:56:49.333  5804  5818 W FA      : Service invalid
01-01 23:56:49.340  5804  5804 D TNS.Native: lenNodes=100896, lenNames=963280, lenValues=1224608
01-01 23:56:49.341  5804  5804 D TNS.Native: time=1
01-01 23:56:49.353  5804  5830 E FirebaseInstanceId: Google Play services missing or without correct permission.
01-01 23:56:49.599  5804  5804 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-01 23:56:49.651  5804  5830 E FirebaseInstanceId: Google Play services missing or without correct permission.
01-01 23:56:49.802  5283  5294 E QueryController: Got null root node from accessibility - Retrying...
01-01 23:56:49.938  5804  5804 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
01-01 23:56:49.939  5804  5804 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
01-01 23:56:49.943  5804  5804 I JS      : firebase.init done
01-01 23:56:49.961  5804  5818 I FA      : Tag Manager is not found and thus will not be used
01-01 23:56:49.967  1262  1295 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
01-01 23:56:49.967  5804  5839 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-01 23:56:49.974  5804  5830 E FirebaseInstanceId: Google Play services missing or without correct permission.
01-01 23:56:49.979  5804  5804 D         : HostConnection::get() New Host Connection established 0xa03aa340, tid 5804
01-01 23:56:50.034  5804  5839 D         : HostConnection::get() New Host Connection established 0xa02600c0, tid 5839
01-01 23:56:50.035  5804  5839 I OpenGLRenderer: Initialized EGL, version 1.4
01-01 23:56:50.039  5804  5839 D EGL_emulation: eglCreateContext: 0xaf015560: maj 3 min 0 rcv 3
01-01 23:56:50.040  5804  5839 D EGL_emulation: eglMakeCurrent: 0xaf015560: ver 3 0 (tinfo 0xa02f0250)
01-01 23:56:50.042  5804  5839 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
01-01 23:56:50.042  5804  5839 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
01-01 23:56:50.047  5804  5839 D EGL_emulation: eglMakeCurrent: 0xaf015560: ver 3 0 (tinfo 0xa02f0250)
01-01 23:56:50.053  5283  5294 E QueryController: Got null root node from accessibility - Retrying...
01-01 23:56:50.055  5804  5818 I FA      : This instance being marked as an uploader
01-01 23:56:50.702  1573  1592 I ActivityManager: Displayed org.nativescript.MDApp/com.tns.NativeScriptActivity: +1s505ms
01-01 23:56:50.703  5804  5804 I Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
01-01 23:56:50.713  5283  5293 W art     : Long monitor contention event with owner method=android.view.accessibility.AccessibilityNodeInfo com.android.uiautomator.core.QueryController.findAccessibilityNodeInfo(com.android.uiautomator.core.UiSelector, boolean) from QueryController.java:149 waiters=0 for 556ms
01-01 23:56:52.326  1270  1637 W audio_hw_generic: Not supplying enough data to HAL, expected position 5349026 , only wrote 5120767
01-01 23:56:56.958  5804  5804 E InputEventReceiver: Exception dispatching input event.
01-01 23:56:56.958  5804  5804 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: com.tns.NativeScriptException: 
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: Calling js method onItemClick failed
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: TypeError: Cannot read property 'bindingContext' of undefined
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: File: "file:///data/data/org.nativescript.MDApp/files/app/cars/cars-list-page.js, line: 26, column: 36
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: StackTrace: 
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	Frame: function:'onCarItemTap', file:'file:///data/data/org.nativescript.MDApp/files/app/cars/cars-list-page.js', line: 26, column: 37
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.MDApp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	Frame: function:'onItemClick', file:'file:///data/data/org.nativescript.MDApp/files/app/tns_modules/nativescript-ui-listview/ui-listview.js', line: 583, column: 32
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:987)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.tns.gen.com.telerik.widget.list.RadListView_ItemClickListener.onItemClick(RadListView_ItemClickListener.java:17)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.telerik.widget.list.RadListView.notifyOnTapUp(RadListView.java:723)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.telerik.widget.list.ListViewGestureListener.onTapUp(ListViewGestureListener.java:175)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.telerik.widget.list.ListViewGestureListener.onSingleTapUp(ListViewGestureListener.java:274)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.telerik.widget.list.ListViewGestureListener.onTouchEvent(ListViewGestureListener.java:149)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at com.telerik.widget.list.RadListView.onTouchEvent(RadListView.java:544)
01-01 23:56:56.959  5804  5804 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:9294)
```

**Comment by manoldonev** [comment]
Caused by https://github.com/telerik/nativescript-ui-feedback/issues/976
