### ISSUE TITLE
NullPointerException with mixed parent / nested frame navigation with Flip on API 19

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#6798]
**Environment**
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.1
 - Android Runtime: 5.1.0

**Describe the bug**
App crashes in nested frame scenario with mixed parent frame / nested frame navigation with Flip transition.

**To Reproduce**
1. Tap "Player Two" and then go back to Players list (via arrow or hardware button) (nested frame navigation and back)
2. Tap "navigate to some page" and then go back (via arrow or hardrware button) (parent frame navigation and back)
3. Try to tap "Player Two" again (nested frame navigation) -- app crashes with:
```
An uncaught Exception occurred on "main" thread.
java.lang.NullPointerException
	at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:797)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
	at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
```

**Expected behavior**
App should not crash with nested frame navigation scenarios with Flip transition.

**Sample project**
Playground project: https://play.nativescript.org/?template=play-tsc&id=BZfk8A&v=11

**Additional context**
**NOTE: Reproducible only on Android API level 19**

**Comment by SvetoslavTsenov** [comment]
See also #8053
https://github.com/NativeScript/NativeScript/pull/8035
