### ISSUE TITLE
Unable to install NativeScript CLI - Cannot find module 'hawk'

### ISSUE THREAD

**Issue by kayveedw** [NativeScript/NativeScript#6836]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - npm: 6.7.0
 - node: v10.15.0

**Describe the bug**
Unable to install NativeScript CLI via npm. It gives an error:

Cannot find module 'hawk'

I've also tried npm i -g nativescript@5.0 which installs nativescript@5.0.4. This has the same error.

**To Reproduce**
npm i -g nativescript

**Expected behavior**

**Additional context**
C:\Users\micro>npm i -g nativescript
C:\Users\micro\AppData\Roaming\npm\tns -> C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\bin\tns
C:\Users\micro\AppData\Roaming\npm\nativescript -> C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\bin\tns

> nativescript@5.1.1 postinstall C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript
> node postinstall.js

Cannot find module 'hawk'
Failed to display command help { Error: Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.
    at Errors.fail (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
    at Errors.failWithoutHelp (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:135:21)
    at HelpService.<anonymous> (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\help-service.js:178:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\help-service.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'Exception',
  message:
   'Unknown command \'post-install-cli\'. Try \'$ tns help\' for a full list of supported commands.',
  stack:
   'Error: Unknown command \'post-install-cli\'. Try \'$ tns help\' for a full list of supported commands.\n    at Errors.fail (C:\\Users\\micro\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\errors.js:125:28)\n    at Errors.failWithoutHelp (C:\\Users\\micro\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\errors.js:135:21)\n    at HelpService.<anonymous> (C:\\Users\\micro\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\services\\help-service.js:178:26)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\micro\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\services\\help-service.js:4:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  errorCode: 127,
  suppressCommandHelp: true,
  proxyAuthenticationRequired: false,
  printOnStdout: undefined }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\nativescript\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ nativescript@5.1.1
added 912 packages from 1345 contributors in 36.94s

**Comment by kayveedw** [comment]
closing here as realise it should have been an issue on the CLI repro. New issue at: https://github.com/NativeScript/nativescript-cli/issues/4315
