### ISSUE TITLE
Brand new shared app preview error on iOS could not find module './' 

### ISSUE THREAD

**Issue by sebastianbats** [NativeScript/NativeScript#6911]
Just created the app using ng new with @nativescript/schematics and scsss styling as a shared project. Ng serve runs fine and I can access the app but previewing the app on an iPhone 7 using the preview app throws this error. I've also tried it on a Pixel XL2 using the playground app and got a different error .

When I've created a non-shared project before using nativescript cli, everything ran well without a problem, using the same machine, devices and global configuration.

I'm running Angular 7 with the latest version of CLI and the latest stable node version.

### ERROR on IOS
`Successfully sent initial files for platform ios.
LOG from device iPhone: 2019-02-16 17:20:06.952 nsplaydev[631:183189] ***** Fatal JavaScript exception - application has been terminated. *****
2019-02-16 17:20:06.952 nsplaydev[631:183189] Native stack trace:
1   0x104e67370 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x104ea3c20 -[TNSRuntime executeModule:referredBy:]
3   0x105da73c8 -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4   0x1048073f0
5   0x1f4c70b94 <redacted>
2019-02-16 17:20:06.954 nsplaydev[631:183189] JavaScript stack trace:
2019-02-16 17:20:06.955 nsplaydev[631:183189] 1   resolve@[native code]
2   loadModule@[native code]
3   loadAndEvaluateModule@[native code]
2019-02-16 17:20:06.955 nsplaydev[631:183189] JavaScript error:
[native code]: JS ERROR Error: Could not find module './'. Computed path '/var/mobile/Containers/Data/Application/9F232236-ED62-4084-A364-A66B82906DBE/Documents/Playground/LiveSync/app'.
2019-02-16 17:20:06.955 nsplaydev[631:183189] PlayLiveSync: Uncaught Exception
2019-02-16 17:20:06.955 nsplaydev[631:183189] *** JavaScript call stack:
(

)
2019-02-16 17:20:06.955 nsplaydev[631:183189] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Could not find module './'. Computed path '/var/mobile/Containers/Data/Application/9F232236-ED62-4084-A364-A66B82906DBE/Documents/Playground/LiveSync/app'.
 at
1   resolve@[native code]
2   loadModule@[native code]
3   loadAndEvaluateModule@[native code]
', reason: '(null)'
*** First throw call stack:
(0x1f5227ef8 0x1f43f5a40 0x104e677b4 0x104ea3c20 0x105da73c8 0x1048073f0 0x1f4c70b94)
libc++abi.dylib: terminating with uncaught exception of type NSException
2019-02-16 17:20:06.955 nsplaydev[631:183189] PlayLiveSync: Uncaught Exception`

### ERROR ON ANDROID

`Successfully sent initial files for platform android.
LOG from device Pixel 2 XL: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
        at com.tns.Module.bootstrapApp(Module.java:311)
        at com.tns.Runtime.run(Runtime.java:615)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
        at com.tns.Module.resolvePathHelper(Module.java:146)
        at com.tns.Module.bootstrapApp(Module.java:309)
        ... 12 more`

### Package.json:

`{
    "name": "ishango-timesheet-nativescript",
    "nativescript": {
        "id": "org.nativescript.ishangotimesheetnativescript"
    },
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "android": "tns run android --bundle",
        "ios": "tns run ios --bundle"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~7.1.0",
        "@angular/common": "~7.1.0",
        "@angular/compiler": "~7.1.0",
        "@angular/core": "~7.1.0",
        "@angular/forms": "~7.1.0",
        "@angular/http": "~7.1.0",
        "@angular/platform-browser": "~7.1.0",
        "@angular/platform-browser-dynamic": "~7.1.0",
        "@angular/router": "~7.1.0",
        "core-js": "^2.5.4",
        "nativescript-angular": "~7.1.0",
        "nativescript-theme-core": "~1.0.4",
        "reflect-metadata": "~0.1.8",
        "rxjs": "~6.3.3",
        "tns-core-modules": "~5.1.1",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.13.1",
        "@angular/cli": "^7.1.0",
        "@angular/compiler-cli": "^7.2.5",
        "@nativescript/schematics": "~0.4.0",
        "@types/jasmine": "2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "nativescript-dev-sass": "~1.6.0",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "^0.18.0",
        "protractor": "^5.4.2",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~3.1.1"
    }
}
`

### TSCONFIG
`{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom",
            "es6",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "**/*.tns.ts",
        "**/*.android.ts",
        "**/*.ios.ts",
        "**/*.spec.ts"
    ]
}`

**Comment by sebastianbats** [comment]
Upon going into sidekick to run the build for iOS and preview on my connected phone, I notice a red blaring warning in the 'preview' tab where it tells me to install nativescript-dev-webpack as a dev dependency.

Upon installing that manually it seems to work.

**Comment by mickyinba** [comment]
I found out that all I needed to solve this is to update the actual phone app "NativeScript Preview" on  my phone.
