### ISSUE TITLE
HostListener for keyboard events returns error

### ISSUE THREAD

**Issue by danu165** [NativeScript/NativeScript#6948]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.1.2
 - Cross-platform modules: 4.1.1
 - Android Runtime: 4.1.3
 - iOS Runtime: 4.1.1
 - Plugin(s):

**Describe the bug**
I get a runtime error when I try to add a HostListener to a component. I've listed my example code with the error I get. I get this on Android, I have not tried on iOS. I have also tried specifying the type for event as KeyboardEvent and that does not work.

```
import { Component, OnInit, HostListener  } from '@angular/core';
@Component({
  moduleId: module.id,
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent implement OnInit {
  @HostListener('document:keydown', ['$event'])
  onKeyboardEvent(event: any) {
    console.log(event.key)
  }
}


JS: ERROR Error: Uncaught (in promise): TypeError: renderElement.on is not a function
JS: TypeError: renderElement.on is not a function
JS:     at NativeScriptRenderer.listen (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/nativescript-angular/renderer.js:188:23)
JS:     at DebugRenderer2.listen (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11321:34)
JS:     at listenToElementOutputs (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:7956:52)
JS:     at createViewNodes (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:10173:21)
JS:     at createRootView (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:10120:9)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11151:29)
JS:     at Object.debugCreateRootView [as create...```

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1747](https://github.com/NativeScript/nativescript-angular/issues/1747) via [**ZenHub**](https://www.zenhub.com/)
