### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.widget.chart.visualization.behaviors.ChartSelectionChangeListener

### ISSUE THREAD

**Issue by theunreal** [NativeScript/NativeScript#7015]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
√ Getting NativeScript components versions information...
√ Component nativescript has 5.2.2 version and is up to date.
√ Component tns-core-modules has 5.2.2 version and is up to date.
√ Component tns-android has 5.2.1 version and is up to date.
√ Component tns-ios has 5.2.0 version and is up to date.

**Describe the bug**
When I am trying to `tns build android`, I get the following error:

```
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\xampp\htdocs\reporterNative\App_Resources\Android\app.gradle
         + using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\@nativescript-rtl\ui\platforms\android\nativescript_gridlayout.aar
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\@nativescript-rtl\ui\platforms\android\nativescript_grid_layout.aar
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\@nativescript-rtl\ui\platforms\android\ui.aar
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\nativescript-ui-chart\platforms\android\TNSChart-release.aar
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\nativescript-ui-listview\platforms\android\TNSListView-release.aar
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
         + adding aar plugin dependency: C:\xampp\htdocs\reporterNative\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.widget.chart.visualization.behaviors.ChartSelectionChangeListener
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:785)
        at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:710)
        at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:228)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:342)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:134)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:173)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:91)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:67)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:47)
```

**To Reproduce**
Not sure, I'm just running tns build android.

**Expected behavior**
App should build.

**Sample project**
Will add if there is no easy way to understand what is the issue.

**Additional context**
None

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#1046
