### ISSUE TITLE
Crash on app resume: The specified child already has a parent

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#7105]
**Environment**
```
tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.1 version and is up to date.
✔ Component tns-core-modules has 5.3.1 version and is up to date.
✔ Component tns-android has 5.3.0 version and is up to date.
✔ Component tns-ios has 5.3.1 version and is up to date.
```

**Describe the bug**
Application crashes on resume. Error is shown on screen when running in development mode. I unfortunately have no specific steps to reproduce it, but this happened twice already, and I wanted to provide you with the information I have in case it aids in troubleshooting. Below please find the error message and the logcat. May be related to #6201

The app is built around [this blog post](https://www.nativescript.org/blog/implementing-a-login-for-nativescript-apps-with-tab-based-navigation), so it has page-router-outlet in app.component.html and TabView with a page-router-outlet in each of 5 tabs in the tabs.component.html.

```
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR TypeError: Cannot read property 'getChildAt' of null
System.err: java.lang.RuntimeException: Unable to resume activity {org.nativescript.nextrade360/com.tns.NativeScriptActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5034)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4865)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4805)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4778)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1466)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err: 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:391)
System.err: 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:517)
System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
System.err: 	at android.app.Activity.performResume(Activity.java:7300)
System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
System.err: 	... 11 more
```

```
--------- beginning of crash
04-03 12:25:53.147 24437 24437 E AndroidRuntime: FATAL EXCEPTION: main
04-03 12:25:53.147 24437 24437 E AndroidRuntime: Process: org.nativescript.nextrade360, PID: 24437
04-03 12:25:53.147 24437 24437 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.nativescript.nextrade360/com.tns.NativeScriptActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5034)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4865)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4805)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4778)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1466)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:391)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:517)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7300)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
04-03 12:25:53.147 24437 24437 E AndroidRuntime: 	... 11 more
04-03 12:25:53.150 24437 24437 W System.err: java.lang.RuntimeException: Unable to resume activity {org.nativescript.nextrade360/com.tns.NativeScriptActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
04-03 12:25:53.150 24437 24437 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-03 12:25:53.150 24437 24437 W System.err: 	at android.os.Looper.loop(Looper.java:193)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-03 12:25:53.151 24437 24437 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 12:25:53.151 24437 24437 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-03 12:25:53.151 24437 24437 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-03 12:25:53.151 24437 24437 W System.err: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
04-03 12:25:53.151 24437 24437 W System.err: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5034)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4865)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4805)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:4778)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1466)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:391)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:517)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.app.Activity.performResume(Activity.java:7300)
04-03 12:25:53.151 24437 24437 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
04-03 12:25:53.151 24437 24437 W System.err: 	... 11 more
```

**Comment by tsonevn** [comment]
Hi @sserdyuk,
Can you provide some more info about the steps, you are using while building the app and about the device/emulator, you are using for testing? Have you made some change in the code(HTML/CSS /Code-behind), before appearing of this error?  It will help if you can share your project with us.
Meanwhile, I tested the [demo project](https://github.com/NativeScript/login-tab-navigation-ng) attached in the blog-post with the latest NativeScript version, however, was unable to recreate the problem.

**Comment by sserdyuk** [comment]
@tsonevn It only happened twice over a two week period. Once on v5.2 with a development build running on an untethered  phone, second time on a tethered phone under `tns run android --hmr` on v5.3. The stack I included is from the second incident. I don't have the exact sequence of events to reproduce the issue even with the code I have, it's just not happening often enough to make the determination.

**Comment by tsonevn** [comment]
Hi @sserdyuk,
I've investigated further the issue, however, we are still unable to recreate the problem while using our [NS Angular](https://github.com/NativeScript/login-tab-navigation-ng) and [non-Angular](https://github.com/ADjenkov/login-tabs) apps. On that matter, we can not identify, what exactly is causing the reported issue on your side. 
Regarding that, it will help if you can check again if there are a specific sequence of steps, that leads more regularly to this crash. Also, can you send us your project and the info about the device API levels, that you are using for testing? 

Thank you in advance for your cooperation.

**Comment by sserdyuk** [comment]
@tsonevn It crashed on Pixel 3 running Pie both times. It may not mean a lot, as it is my personal phone, which I handle most of the time and suspend/resume a lot. My other development phones are mostly stay tethered and never suspend while connected. Both of times I woke up the phone with the fingerprint and it opened to the last running app, which happened to be the app in development.

What's your Bitbucket handle? I'll give you access to the repo.

**Comment by tsonevn** [comment]
Hi @sserdyuk, 
My username in  Bitbucket is again `tsonevn`.

**Comment by sserdyuk** [comment]
@tsonevn  I shared NexTrade360-Mobile-Angular-NS and gave you write privileges in case you want to create your own branch.

**Comment by sserdyuk** [comment]
@tsonevn Like I previously said, the problem doesn't happen all the time, and I don't have the steps for it to be reproduced. I still chose to report it because I wanted to provide a piece of puzzle that hopefully will add up to the full picture some day.

**Comment by NickIliev** [comment]
Closing due to not enough information provided to investigate the case, but if anyone has steps to encounter this issue please let us know by providing a sample app or snippet here.
