### ISSUE TITLE
Drawer Navigation template (https://market.nativescript.org/plugins/tns-template-drawer-navigation-ts) crashes after Android phone "overview" button is pressed

### ISSUE THREAD

**Issue by cwjacobs** [NativeScript/NativeScript#7122]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: N/A
 - Cross-platform modules:
 - Android Runtime: 5.3.1 
 - iOS Runtime: N/A
 - Plugin(s): N/A

package.json:
{
  "nativescript": {
    "id": "org.nativescript.mydrawerts",
    "tns-android": {
      "version": "5.3.1"
    },
    "tns-ios": {
      "version": "5.3.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~6.0.0",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~5.3.0"
  },
  "devDependencies": {
    "nativescript-dev-sass": "~1.7.0",
    "nativescript-dev-typescript": "~0.9.0",
    "nativescript-dev-webpack": "~0.21.0",
    "tslint": "~5.11.0"
  },
  "gitHead": "803cec054c44c99eaa59cdc267993e6346f6cb3a",
  "readme": "NativeScript Application"
}

**Describe the bug**
When the app is running in foreground and I press the "overview" button on my phone, then select a different app (like "WhatsApp" or my contacts) , then go back to "mydrawerts" (my-drawer-ts)  and select any navigation page from from the drawer's list of pages, the app crashes. It looks like the frame stack is empty and the default home screen (frame?) is not being returned, instead, undefined is being returned.

**To Reproduce**
Install the (typescript) version of the Drawer Navigation template by tns-bot (tns create my-app-name --template tns-template-drawer-navigation-ts". Run "tns build android" from the app root folder, then run "tns run --device "xxx (your device id here) to install the app on your android phone, launch the app, use the overview button to switch to another app, return to the drawer navigation app (mydrawerts) and select a new page listed on the drawer nav component. Crashes immediately.

**Expected behavior**
Expect to navigate to selected page.

**Sample project**
https://github.com/cwjacobs/my-drawer-ts.git

**Additional context**
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onTouch failed

TypeError: Cannot read property 'navigate' of undefined
File: "file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js, line: 228, column: 40

StackTrace: 
Frame: function:'onNavigationItemTap', file:'file:///data/data/org.nativescript.mydrawerts/files/app/app-root/app-root.js', line: 17, column: 22
Frame: function:'_executeCallback', file:'file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js', line: 282, column: 27
Frame: function:'TapAndDoubleTapGestureListenerImpl.onSingleTapUp', file:'file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js', line: 25, column: 17
Frame: function:'GesturesObserver.androidOnTouchEvent', file:'file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js', line: 228, column: 41
Frame: function:'', file:'file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 259, column: 25
Frame: function:'View.handleGestureTouch', file:'file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 258, column: 18
Frame: function:'TouchListenerImpl.onTouch', file:'file:///data/data/org.nativescript.mydrawerts/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 33, column: 19

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
at com.tns.Runtime.callJSMethod(Runtime.java:1070)
at com.tns.Runtime.callJSMethod(Runtime.java:1050)
at com.tns.Runtime.callJSMethod(Runtime.java:1042)
at com.tns.gen.java.lang.Object_view_24_32_TouchListenerImpl.onTouch(Object_view_24_32_TouchListenerImpl.java:19)
at android.view.View.dispatchTouchEvent(View.java:11755)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3029)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2707)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2721)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:464)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1867)
at android.app.Activity.dispatchTouchEvent(Activity.java:3299)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:426)
at android.view.View.dispatchPointerEvent(View.java:11998)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5176)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4990)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4299)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4352)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4318)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4326)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4299)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4352)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4318)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4461)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4326)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4518)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4299)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4352)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4318)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4326)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4299)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7072)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7046)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7007)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7206)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7154)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
at android.view.Choreographer.doCallbacks(Choreographer.java:791)
at android.view.Choreographer.doFrame(Choreographer.java:720)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6710)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by tsonevn** [comment]
Hi @cwjacobs,
Make sure that the `Don't keep activities option` is disabled inside the Developer options menu. If it is active disable it, rebuild the project and check if the problem can be reproduced.

**Comment by cwjacobs** [comment]
Fixed! Thank you Nikolay. That's a huge help to me as I learn this technology.
