### ISSUE TITLE
Update documentation for unsubscribing application listeners

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#7154]
@KkevinLi commented on [Thu Feb 28 2019](https://github.com/NativeScript/android-runtime/issues/1292)

I'm running an issue where my app will crash when I have a foreground service which I did not stop (maybe app suddenly crashed ) and when I relaunch the app it will crash. I made a sample project and noticed it was the call of `off` from `tns-core-modules/application` which causes the crash. 

Not sure if this belonged here or Nativescript-Angular repo.

**Environment**
```✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.2.0 version and is up to date.
✔ Component tns-core-modules has 5.2.1 version and is up to date.
⚠ Update available for component tns-android. Your current version is 5.2.0 and the latest available version is 5.2.1.
✔ Component tns-ios has 5.2.0 version and is up to date.
```
**Describe the bug**
I create a foreground service which shows a notification and kill the app (Intentionally I do not stop service) -> Relaunch and app crashes. The lifecycle hook `off` seems to be the cause? 

**To Reproduce**
Open the sample project -> Close -> relaunch app. (Can use emulator or device)

**Sample project**
https://github.com/KkevinLi/Nativescript-Crash

**Logs**
```System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.sample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: TypeError: Cannot read property 'create' of undefined
System.err: File: "file:///data/data/org.nativescript.sample/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 75, column: 14
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.sample/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 75, column: 15
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.sample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 931, column: 50
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.sample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 768, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.sample/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err: 
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed```

**Comment by NickIliev** [comment]
@KkevinLi you need to pass the listener you want to "turn off" (e.g. [here](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/app/ns-framework-modules-category/application/application-events/application-events-ts-page.ts#L83-L90)). Not sure why you want to off all NativeScript's application events in ngOnInit  - are you sure you don't want to off [an Android activity event](https://docs.nativescript.org/core-concepts/application-lifecycle#android-activity-events) (e.g. as done [here](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/3672a54311d1681041a2f28ba45a380abc6257ee/src/barcodescanner.android.ts#L211-L214))? 

Anyway, in the case of Angular app, you could off the wanted listener in `ngOnDestroy`
```TSC
  ngOnDestroy(): void {
      // This causes the error after I relaunch the app...
      this.unsubscribeAll();
  }

```

**Comment by KkevinLi** [comment]
@NickIliev From the documentation of `off` I assumed there was no need to pass in a specific listener since the callback is optional. Even with the passed in listener  I get the same error. 

I placed the `unsubscribeAll()` in the ngOnInit just for testing purposes, but originally I have it in an onExit lifecycle hook in my service. I have updated the repo to show the changes ^.

**Comment by NickIliev** [comment]
@KkevinLi thank you for bringing this issue to my attention. After some additional investigation, it seems that we have introduced misleading examples in our SDK apps as the current implementation of the  `on` method of `application` is **NOT** returning the callback instance. So to overcome the issue you store the callback in a variable and then explicitly remove the wanted listener. Providing a non-existing listener is identical to `appOn(launchEvent)` which would remove all listeners including the one we are setting and using for bootstrapping the Angular app.

Here is the modified `app.service.ts` file with the change discussed above.

```TypeScript
import {
  on as appOn,
  off as appOff,
  suspendEvent,
  resumeEvent,
  launchEvent,
  lowMemoryEvent,
  exitEvent,
  ApplicationEventData,
  AndroidApplication,
  android as appAndroid
} from "tns-core-modules/application";
import { Injectable } from "@angular/core";
import { isAndroid, isIOS } from "tns-core-modules/platform";

declare var com: any;
declare var android: any;

let launchListenerCB; // HERE using CD postfix for all variable 
let suspendListenerCB;
let resumeListenerCB;
let exitListenerCB;
let lowMemoryListenerCB;

@Injectable({ providedIn: "root" })
export class AppService {

  static startNotificationInForegroundService(context, notification, notificationId) {
    const startForegroundIntent = new android.content.Intent(context, com.tns.ForegroundNotificationPlugin.class);
    startForegroundIntent.putExtra("notification", notification);
    startForegroundIntent.putExtra("notificationId", notificationId);
    startForegroundIntent.setAction("startForeground");
    context.startService(startForegroundIntent);
  }

  constructor() {
    console.log("Starting app service");
    this.subscribeHooks();
    this.buildNotifiction();
  }

  private subscribeHooks() {
    console.log("---------------------> AppService.subscribeHooks")

    // HERE storing the CB in a variable which we will later use to remove only this specific listener
    launchListenerCB = (args) => {
      console.log(">>>>>>> Launch Event");
      if (args.android) {
        // For Android applications, args.android is an android.content.Intent class.
        console.log("Launched Android application with the following intent: " + args.android + ".");
      } else if (args.ios !== undefined) {
        // For iOS applications, args.ios is NSDictionary (launchOptions).
        console.log("Launched iOS application with options: " + args.ios);
      }
    };

    appOn(launchEvent, launchListenerCB); // HERE

    suspendListenerCB = (eventData: ApplicationEventData) => {
      if (eventData.android) {
        // For Android applications, eventData.android is an android activity class.
      } else if (eventData.ios) {
        // For iOS applications, eventData.ios is UIApplication.
      }
    };
    appOn(suspendEvent, suspendListenerCB);

    resumeListenerCB = (eventData: ApplicationEventData) => {
      if (eventData.android) {
        // For Android applications, eventData.android is an android activity class.
      } else if (eventData.ios) {
        // For iOS applications, eventData.ios is UIApplication.
      }
    }
    appOn(resumeEvent, resumeListenerCB);

    lowMemoryListenerCB = (eventData: ApplicationEventData) => {
      if (eventData.android) {
        // For Android applications, eventData.android is an android activity class.
      } else if (eventData.ios) {
        // For iOS applications, eventData.ios is UIApplication.

      }
    }
    appOn(lowMemoryEvent, lowMemoryListenerCB);

    exitListenerCB = (eventData: any) => {

      if (eventData.android) {
        const intent = new android.content.Intent(appAndroid.context, com.tns.ForegroundNotificationPlugin.class);
        appAndroid.context.stopService(intent);
      } else if (eventData.ios) {
      }
      this.unsubscribeAll();
    }
    appOn(exitEvent, exitListenerCB);
  }
  private unsubscribeAll(): void {
    console.log("unsubscribeAll launchListenerCB:", !!launchListenerCB)

    appOff(launchEvent, launchListenerCB); // HERE
    appOff(suspendEvent, suspendListenerCB);
    appOff(resumeEvent, resumeListenerCB);
    appOff(lowMemoryEvent, lowMemoryListenerCB);
    appOff(exitEvent, exitListenerCB);
  }

  private buildNotifiction() {
    const intent = new android.content.Intent(appAndroid.context, com.tns.NativeScriptActivity.class);
    const resources = appAndroid.context.getResources();
    const pIntent = android.app.PendingIntent.getActivity(appAndroid.context, 0, intent, android.app.PendingIntent.FLAG_UPDATE_CURRENT);
    const smallIcon = resources.getIdentifier(
      "ic_stat_notify", "drawable", appAndroid.context.getApplicationInfo().packageName
    );
    // Build a notification.
    const builder = new android.app.Notification.Builder(appAndroid.context)
      .setContentTitle("TEST")
      .setContentText("TestConect")
      .setSmallIcon(smallIcon)
      .setOngoing(true) // cannot be cleared
      .setContentIntent(pIntent); // open the application when the notification is tapped

    if (android.os.Build.VERSION.SDK_INT >= 26 /* Oreo */) {
      const a: any = android;
      const b: any = builder;
      const channelId = "CHANNEL";
      const nm: any = appAndroid.context.getSystemService(android.content.Context.NOTIFICATION_SERVICE);
      const notificationChannel: any = nm.getNotificationChannel(channelId);
      if (notificationChannel === null) {
        const channel26: any = new a.app.NotificationChannel(
          channelId,
          "DUMMYVALUE",
          a.app.NotificationManager.IMPORTANCE_LOW
        );
        nm.createNotificationChannel(channel26);
      }
      b.setChannelId(channelId);
    } else {
      builder.setPriority(android.app.Notification.PRIORITY_DEFAULT);
    }
    const notification = builder.build();
    notification.flags |= android.app.Notification.FLAG_NO_CLEAR | android.app.Notification.FLAG_ONGOING_EVENT;
    AppService.startNotificationInForegroundService(appAndroid.context, notification, 1111);
  }
}

```

Once again thank you for your observation - I will create a PR to change [these examples ](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/app/ns-framework-modules-category/application/application-events/application-events-ts-page.ts#L41-L91)to use the proper logic for the `on` method.

**Comment by NickIliev** [comment]
Documentation update via [https://github.com/NativeScript/nativescript-sdk-examples-js/pull/125](https://github.com/NativeScript/nativescript-sdk-examples-js/pull/125)
