### ISSUE TITLE
The AngularCompilerPlugin was not found.

### ISSUE THREAD

**Issue by mandar-bhong** [NativeScript/NativeScript#7201]
While compiling on windows 8.1
Application have UI and background worker along with sqlite database

√ Getting NativeScript components versions information...
√ Component nativescript has 5.3.4 version and is up to date.
√ Component tns-core-modules has 5.3.1 version and is up to date.
√ Component tns-android has 5.3.1 version and is up to date.

```
**Content of package.json as below**

{
  "nativescript": {
    "id": "<app name>",
    "tns-ios": {
      "version": "5.0.0"
    },
    "tns-android": {
      "version": "5.3.1"
    }
  },
  "scripts": {
    "androiddebug": "node --max_old_space_size=4096 tns debug android --bundle"
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "mime-types": "^2.1.22",
    "moment": "^2.24.0",
    "nativescript-angular": "^7.2.3",
    "nativescript-background-http": "^3.4.0",
    "nativescript-camera": "^4.1.1",
    "nativescript-cardview": "^3.1.1",
    "nativescript-cfalert-dialog": "^1.0.14",
    "nativescript-drawingpad": "^3.0.4",
    "nativescript-fancyalert": "^3.0.6",
    "nativescript-imagepicker": "^6.0.4",
    "nativescript-local-notifications": "^3.1.0",
    "nativescript-ripple": "^2.1.0",
    "nativescript-snackbar": "^4.0.0",
    "nativescript-sqlite": "^2.2.3",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^3.11.0",
    "nativescript-ui-chart": "^3.10.0",
    "nativescript-ui-listview": "^5.0.0",
    "nativescript-ui-sidedrawer": "^6.0.0",
    "nativescript-websockets": "^1.5.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.3.1",
    "tns-platform-declarations": "^5.1.1",
    "typescript": "~3.1.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.2.0",
    "@nativescript/schematics": "~0.4.0",
    "@ngtools/webpack": "~7.2.0",
    "nativescript-dev-typescript": "^0.9.0",
    "nativescript-dev-webpack": "^0.21.2",
    "ts-loader": "^5.3.1"
  },
  "readme": "NativeScript Application"
}

```

**Compilation Error**
```
JS: worker error {

JS:   "message": "Uncaught Error: Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):\nError: The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin.\n    at Object.ngcLoader (<localpath>\\node_modules\\@ngtools\\webpack\\src\\loader.js:27:15)",
JS:   "stackTrace": "Error: Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):\nError: The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin.\n    at Object.ngcLoader (<localpath>\\node_modules\\@ngtools\\webpack\\src\\loader.js:27:15)\n    at Object.../node_modules/nativescript-dev-webpack/moduleid-compat-loader.js!../node_modules/nativescript-dev-webpack/lazy-ngmodule-hot-loader.js!../node_modules/@ngtools/webpack/src/index.js!./app/workers/server-data-processor.worker.ts (file:///data/data/<proj_name>/files/app/d7eea7215f87b22abb3...

```

It seems that whenever application have background worker then with --bundle (webpack) application fails to compile with error message "**The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin**"

**Comment by tsonevn** [comment]
Hi @mandar-bhong,
Can you provide more detailed info about the problem, you are facing and the project? Also, it will help, if you can send us sample application, that can be used for recreating the issue.

Meanwhile, make sure that you have defined the worker in the required way for a project with webpack. Check out [this section](https://docs.nativescript.org/core-concepts/multithreading-model#usage-with-webpack) from NativeScript docs.

**Comment by NickIliev** [comment]
@mandar-bhong try updating your `webpack.config.js`. Stoe any custom entries, then delete the file and node_modules and update it by running `npm i` (then, if any, add any custom entry previously used in the config)

**Comment by mandar-bhong** [comment]
@NickIliev thank you for your response, updating webpack.config.js (with custom entries) and reinstalling node_modules works for me

**Comment by mandar-bhong** [comment]
@NickIliev thank you for your response, updating webpack.config.js and reinstalling node_modules works for me
