### ISSUE TITLE
Error: Can't resolve all parameters for PageRouterOutlet

### ISSUE THREAD

**Issue by ohralathe** [NativeScript/NativeScript#7258]
**Environment**
`tns info`
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 5.4.0 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.0 version and is up to date.

**Describe the bug**

Hi bro, I wanna to use RouteReuseStrategy to solve some cases but I got an error `Can't resolve all parameters for PageRouterOutlet` occur when the application is starting when I use `RouteReuseStrategy`
Is there any idea to solve this one?

```
# app.module.ts
providers: [
  {provide: RouteReuseStrategy, useClass: NSRouteReuseStrategy}
]
```

However, I can use `RouteReuseStrategy` in android platform version 5.0.0 and angular 6 and tns cli <=5.1

Log
```
tns run android                                ✔  10006  21:26:57
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Starting Android emulator with image test
Waiting for emulator device initialization....
Found peer TypeScript 3.1.6
Copying template files...
Platform android successfully added. v5.3.1
Preparing project...
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-ui-sidedrawer for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin nativescript-ui-core for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/hoanvx/workspace/ns-test/App_Resources/Android/app.gradle
         + using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/hoanvx/workspace/ns-test/node_modules/nativescript-ui-sidedrawer/platforms/android/TNSSideDrawer-release.aar
         + adding aar plugin dependency: /Users/hoanvx/workspace/ns-test/node_modules/nativescript-ui-core/platforms/android/TNSCore-release.aar
         + adding aar plugin dependency: /Users/hoanvx/workspace/ns-test/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
Task: traverseDirectory: Folder will be traversed completely: /Users/hoanvx/workspace/ns-test/platforms/android/app/src/main/assets/app/tns_modules/tns-core-modules/ui
(node:1406) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.nstest on device emulator-5554.
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.nstest/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Can't resolve all parameters for PageRouterOutlet: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?, [object Object]).
System.err: File: "file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 19228, column: 16
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 2500, column: 21
System.err: 	Frame: function:'CompileMetadataResolver._getDependenciesMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 19040, column: 39
System.err: 	Frame: function:'CompileMetadataResolver._getTypeMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 18933, column: 30
System.err: 	Frame: function:'CompileMetadataResolver.getNonNormalizedDirectiveMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 18552, column: 28
System.err: 	Frame: function:'CompileMetadataResolver.loadDirectiveMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 18414, column: 27
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26092, column: 59
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26091, column: 76
System.err: 	Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26088, column: 79
System.err: 	Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26066, column: 40
System.err: 	Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26026, column: 41
System.err: 	Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 202, column: 35
System.err: 	Frame: function:'compileNgModuleFactory__PRE_R3__', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 17664, column: 25
System.err: 	Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 17847, column: 20
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/nativescript-angular/platform-common.js', line: 88, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/nativescript-angular/platform-common.js', line: 151, column: 19
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 984, column: 17
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 909, column: 28
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 768, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
System.err: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Can't resolve all parameters for PageRouterOutlet: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?, [object Object]).
System.err: File: "file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 19228, column: 16
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 2500, column: 21
System.err: 	Frame: function:'CompileMetadataResolver._getDependenciesMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 19040, column: 39
System.err: 	Frame: function:'CompileMetadataResolver._getTypeMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 18933, column: 30
System.err: 	Frame: function:'CompileMetadataResolver.getNonNormalizedDirectiveMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 18552, column: 28
System.err: 	Frame: function:'CompileMetadataResolver.loadDirectiveMetadata', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 18414, column: 27
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26092, column: 59
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26091, column: 76
System.err: 	Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26088, column: 79
System.err: 	Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26066, column: 40
System.err: 	Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 26026, column: 41
System.err: 	Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 202, column: 35
System.err: 	Frame: function:'compileNgModuleFactory__PRE_R3__', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 17664, column: 25
System.err: 	Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 17847, column: 20
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/nativescript-angular/platform-common.js', line: 88, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/nativescript-angular/platform-common.js', line: 151, column: 19
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 984, column: 17
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 909, column: 28
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 768, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.nstest/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
System.err: 	at android.app.Activity.performCreate(Activity.java:6679)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
System.err: 	... 9 more
Preparing project...
Project successfully prepared (Android)
Successfully transferred app.module.js on device emulator-5554.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.nstest on device emulator-5554.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

**To Reproduce**
run below command

```
 tns create ns-test
# select the angular project
tns run android
```

**Expected behavior**

**Sample project**
https://github.com/ohralathe/ns-test

Thanks

**Comment by danielgek** [comment]
try to import NativeScriptModule before AppRoutingModule (wild guess)

**Comment by ohralathe** [comment]
> try to import NativeScriptModule before AppRoutingModule (wild guess)

Not solve yet

**Comment by ohralathe** [comment]
I solved by creating a new custom class extends from `RouteReuseStrategy` instead of `NS RouteReuseStrategy`. So I think the problem comes from NSRouteReuseStrategy.
I will leave this issue here if this is a bug of NS if this is not please help me close it.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-angular #1829](https://github.com/NativeScript/nativescript-angular/issues/1829) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vahidvdn** [comment]
@ohralathe Would you please share your custom class called `MyRouteReuseStrategy`? Thanks.

**Comment by ohralathe** [comment]
> @ohralathe Would you please share your custom class called `MyRouteReuseStrategy`? Thanks.

@vahidvdn In my case, I just want it to reload every time navigating, so the MyRouteReuseStrategy is so simple as below

```
import { Injectable } from '@angular/core';
import { ActivatedRouteSnapshot, DetachedRouteHandle, RouteReuseStrategy } from '@angular/router';

@Injectable()
export class MyRouteReuseStrategy extends RouteReuseStrategy {

  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
    return undefined;
  }

  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }

  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }

  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle | null): void {
  }

  shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    return false;
  }
}


```
