### ISSUE TITLE
ActionBar crashes when we try to setup icon-font for the ActionItem

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#7520]
**Environment**

 - CLI: 6.0.0
 - Cross-platform modules:6.0.1
 - Android Runtime:6.0.0
 

**Describe the bug**
The ActionBar will crash when we try to setup icon-font for the ActionItem with the following error:
```
System.err: Error: java.lang.IllegalArgumentException: width and height must be > 0
System.err:     android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
System.err:     android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
System.err:     android.graphics.Bitmap.createBitmap(Bitmap.java:950)
System.err:     android.graphics.Bitmap.createBitmap(Bitmap.java:911)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     android.os.Handler.handleCallback(Handler.java:873)
System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     android.os.Looper.loop(Looper.java:201)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6806)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
System.err: 
System.err: StackTrace:
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/image-source/image-source.js.ImageSource.loadFromFontIconCode', file:'file:///node_modules/tns-core-modules/image-source/image-source.js:134:0
System.err: 	Frame: function:'fromFontIconCode', file:'file:///node_modules/tns-core-modules/image-source/image-source.js:234:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/action-bar/action-bar.js.ActionBar._addActionItems', file:'file:///node_modules/tns-core-modules/ui/action-bar/action-bar.js:281:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/action-bar/action-bar.js.ActionBar.update', file:'file:///node_modules/tns-core-modules/ui/action-bar/action-bar.js:168:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/action-bar/action-bar.js.ActionBar.onLoaded', file:'file:///node_modules/tns-core-modules/ui/action-bar/action-bar.js:156:0
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:311:75
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:304:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:311:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.loadView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:439:0
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/page/page-common.js.PageBase.eachChildView', file:'file:///node_modules/tns-core-modules/ui/page/page-common.js:128:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules/tns-core-modules/ui/core/view/view-common.js:992:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.onLoaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:232:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onLoaded', file:'file:///node_modules/tns-core-modules/ui/core/view/view.js:240:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/page/page.js.Page.onLoaded', file:'file:///node_modules/tns-core-modules/ui/page/page.js:43:0
System.err: 	Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:311:75
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:304:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:311:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.loadView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:439:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addViewCore', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:434:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:420:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView', file:'file:///node_modules/tns-core-modules/ui/frame/frame.js:684:0
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/fragment.js.FragmentClass.onCreateView', file:'file:///node_modules/tns-core-modules/ui/frame/fragment.js:26:0
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err: 	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:201)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6806)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
System.err: Caused by: java.lang.IllegalArgumentException: width and height must be > 0
System.err: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
System.err: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
System.err: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
System.err: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
System.err: 	... 24 more
```
The app will crash even if we setup the width and height inline or via CSS on ActionBar and ActionItem. This error is reproducable only on Android.

**Sample**

```XML
<Page.actionBar>
		<ActionBar width="48" height="48">
            <!-- >> (hide) -->
            <NavigationButton text="Back" visibility="collapsed" />
            <!-- << (hide) -->
            <ActionBar.actionItems>
                 
                <ActionItem icon="font://&#xF359;" width="48" height="48" class="font-awesome font-size color" ios.position="left" tap="navigateBack"/>
                
                <ActionItem icon="font://&#xF141;" width="48" height="48" class="font-awesome font-size color" ios.position="right"/>
            </ActionBar.actionItems>
        </ActionBar>
	</Page.actionBar>
```
```CSS
Label {
    background-color: orangered;
    color: white;
    margin:8;
    padding: 16;
}
ActionBar{
    width: 48;
    height: 48;
}
/* >> action-bar-icon-fonts-css */
.font-awesome {
    font-family: "Font Awesome 5 Free", "fa-regular-400";
}
/* << action-bar-icon-fonts-css */
.font-size {
    font-size: 48;
    width: 48;
    height: 48;
}

.color {
    color: blue;
}
```

**Comment by marcelomiranda90** [comment]
Hello, I get this error mainly on samsung devices such as S8 + with Android 9. The error does not happen on most devices which makes the detection and understanding of the error more difficult.

Two days to understand that this is the problem.

Now I'm going back to my ActionBar icons for images for now.

The advances of NS are great and it is normal for some problems to happen.

Looking forward to the solution.

Galaxy S8+ Android 9

```
Fatal Exception: com.tns.NativeScriptException: Calling js method onCreateView failed
Error: java.lang.IllegalArgumentException: width and height must be > 0
    android.graphics.Bitmap.createBitmap(Bitmap.java:1074)
    android.graphics.Bitmap.createBitmap(Bitmap.java:1041)
    android.graphics.Bitmap.createBitmap(Bitmap.java:991)
    android.graphics.Bitmap.createBitmap(Bitmap.java:952)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
    com.tns.Runtime.callJSMethod(Runtime.java:1109)
    com.tns.Runtime.callJSMethod(Runtime.java:1089)
    com.tns.Runtime.callJSMethod(Runtime.java:1081)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
    androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
    androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
    androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
    androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
    androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
    androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
    androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
    androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
    androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
    androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
    android.os.Handler.handleCallback(Handler.java:873)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:214)
    android.app.ActivityThread.main(ActivityThread.java:7045)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
       at com.tns.Runtime.callJSMethodNative(Runtime.java)
       at com.tns.Runtime.dispatchCallJSMethodNative + 1242(Runtime.java:1242)
       at com.tns.Runtime.callJSMethodImpl + 1122(Runtime.java:1122)
       at com.tns.Runtime.callJSMethod + 1109(Runtime.java:1109)
       at com.tns.Runtime.callJSMethod + 1089(Runtime.java:1089)
       at com.tns.Runtime.callJSMethod + 1081(Runtime.java:1081)
       at com.tns.FragmentClass.onCreateView + 53(FragmentClass.java:53)
       at androidx.fragment.app.Fragment.performCreateView + 2439(Fragment.java:2439)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1460(FragmentManager.java:1460)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1852(FragmentManager.java:1852)
       at androidx.fragment.app.BackStackRecord.executeOps + 802(BackStackRecord.java:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps + 2625(FragmentManager.java:2625)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether + 2411(FragmentManager.java:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2366(FragmentManager.java:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions + 2273(FragmentManager.java:2273)
       at androidx.fragment.app.FragmentManagerImpl$1.run + 733(FragmentManager.java:733)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7045(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 964(ZygoteInit.java:964)
```

**Comment by manoldonev** [comment]
Crash should be addressed by https://github.com/NativeScript/NativeScript/commit/8039c2c1dd14d1a9b027729c118b733d21f155ea but I think there is something wrong with your font family configuration that triggers the issue.
