### ISSUE TITLE
Sidekick errors with {N} 6.0

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#7546]
Hi,

I just upgraded to Nativescript 6 (looks really promising!!) but when opening Sidekick I get the following errors and cannot run apps.

```
[19-07-17 23:01:14.528] (CLI) (node:13572) Error: Missing API. - tns.debugService
    at Object.get (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/cli-provider.js:165:39)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-debug-service.js:88:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[19-07-17 23:01:14.531] (CLI) (node:13572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
(node:13572) Error: Missing API. - tns.liveSyncService
    at Object.get (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/cli-provider.js:165:39)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-livesync-service.js:285:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
(node:13572) Error: Missing API. - tns.liveSyncService
    at Object.get (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/cli-provider.js:165:39)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-previewapp-livesync-service.js:103:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[19-07-18 21:16:18.364] Missing API. - tns.liveSyncService, Error: Missing API. - tns.liveSyncService
    at Object.get (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/cli-provider.js:165:39)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-livesync-service.js:66:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[19-07-18 21:22:52.354] Missing API. - tns.liveSyncService, Error: Missing API. - tns.liveSyncService
    at Object.get (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/cli-provider.js:165:39)
    at requireCLI.then (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar.unpacked/cli/services/cli-livesync-service.js:66:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[19-07-18 21:23:07.236] Build failed. Missing API. - tns.liveSyncService
[19-07-18 21:23:09.271] Build failed. Missing API. - tns.liveSyncService
```

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/sidekick-feedback #399](https://github.com/NativeScript/sidekick-feedback/issues/399) via [**ZenHub**](https://www.zenhub.com/)
