### ISSUE TITLE
FAILED BUILD AFTER TNS MIGRATE

### ISSUE THREAD

**Issue by TryAnt23** [NativeScript/NativeScript#7577]
hello @EddyVerbruggen & team, i have a problem with my project after tns migrate.
my project start from nativescript cli version old <4.. and I want to migrate to a new nativescript with get webpack. before i do, my plan is just run android in a new nativescript version 6.0.
and i get this failed build, can you help me pls.

MY PACKAGE.JSON : 
{
  "nativescript": {
    "id": "com.xxx.app",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "tns-core-modules": "6.0.1",
    "email-validator": "^1.1.1",
    "md5": "^2.2.1",
    "moment": "^2.22.2",
    "nativescript-audio": "^4.3.5",
    "nativescript-background-http": "^3.3.0",
    "nativescript-carousel": "^4.0.2",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-imagepicker": "^6.0.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-modal-datetimepicker": "^1.0.3",
    "nativescript-open-app": "^0.2.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-photo-editor": "^1.0.3",
    "nativescript-photoviewer": "^1.4.0",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-pulltorefresh": "^2.1.1",
    "nativescript-sentry": "^1.9.1",
    "nativescript-textinputlayout": "^2.0.3",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-autocomplete": "5.0.0",
    "nativescript-ui-calendar": "5.0.0",
    "nativescript-ui-chart": "5.0.0",
    "nativescript-ui-listview": "7.0.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "^1.0.1"
  }
}

LOG CONSOLE:
$ tns run android
Searching for devices...
Copying template files...
Platform android successfully added. v6.0.0
Preparing project...
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 
Version: webpack 4.27.1
Time: 5097ms
Built at: 07/25/2019 9:19:24 AM
                  Asset      Size   Chunks             Chunk Names
              bundle.js    12 MiB   bundle  [emitted]  bundle

...
Webpack compilation complete. Watching for file changes.
Webpack build done!
nativescript-plugin-firebase: C:\ns-new\yams-ns\platforms\android\.pluginfirebaseinfo not found, forcing prepare!
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!
Built aar for nativescript-audio
Built aar for nativescript-photoviewer
Chokidar raised event change for C:\ns-new\yams-ns\node_modules\nativescript-photoviewer\platforms\android\include.gradle.
Built aar for nativescript-plugin-firebase
nativescript-plugin-firebase: C:\ns-new\yams-ns\platforms\android\.pluginfirebaseinfo not found, forcing prepare!
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!
Project successfully prepared (android)
Configure firebase
Copy C:\ns-new\yams-ns\app\App_Resources\Android\google-services.json to C:\ns-new\yams-ns\platforms\android\app\google-services.json.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\ns-new\yams-ns\app\App_Resources\Android\app.gradle
         + using andorid X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-audio\platforms\android\nativescript_audio.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-background-http\platforms\android\nativescript_background_httpr
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-imagepicker\platforms\android\nativescript_imagepicker.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-loading-indicator\platforms\android\nativescript_loading_indicr.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-photo-editor\platforms\android\photoeditor-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-photo-editor\platforms\android\photoeditorsdk-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-photoviewer\platforms\android\nativescript_photoviewer.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-plugin-firebase\platforms\android\nativescript_plugin_firebaser
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-sentry\platforms\android\nativescript_sentry.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-ui-autocomplete\platforms\android\TNSAutoComplete-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-ui-calendar\platforms\android\TNSCalendar-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-ui-chart\platforms\android\TNSChart-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-ui-listview\platforms\android\TNSListView-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
         + adding aar plugin dependency: C:\ns-new\yams-ns\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Exception in thread "main" java.lang.RuntimeException: Class not found android.support.v4.widget.SwipeRefreshLayout.OnRefreshListener
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549)
        at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:50)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runSbg'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk8u192-b12\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 31s
Unable to apply changes on device: db45de8b7d13. Error is: Command gradlew.bat failed with exit code 1.

I try to remove package : "tns-core-modules": "6.0.1",
and build run normaly but my apps not usable without it.

**Comment by TryAnt23** [comment]
I Have solve my problem with eliminate 1by1 plugin on package.json version deprecated
