### ISSUE TITLE
Install nativescript v1.3.0 on windows problem

### ISSUE THREAD

**Issue by weilitao** [NativeScript/NativeScript#784]
When I follow the instruction to install nativescript v1.3.0 on windows,  There is an error during the instillation process: 

```
WARNING: You can work with iOS only on Mac OS X systems.                                                       
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.                        
                                                                                                               
Version strings are not in the same format                                                                     
Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.             
    at Errors.fail (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:85:28)   
    at Errors.failWithoutHelp (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.j
s:96:14)                                                                                                       
    at HtmlHelpService.convertCommandNameToFileName (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescri
pt\lib\common\services\html-help-service.js:100:30)                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\html-help-service.js:12
0:36                                                                                                           
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\html-help-service.js:13
2:68                                                                                                           
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\commands\help.js:26:87          
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\commands-service.js:55:
55                                                                                                             
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:109:40                
nativescript@1.3.0 C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript        
```

This is what the command 'tns doctor' show:
```
λ tns doctor
WARNING: You can work with iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Version strings are not in the same format
# doctor
┌─────────┬──────────────┐
│ Usage   │ Synopsis     │
│ General │ $ tns doctor │
└─────────┴──────────────┘

Checks your system for configuration problems which might prevent the NativeScript CLI from working properly.
```

Does it mean my installation is OK or not? 

Thanks.

**Comment by NathanaelA** [comment]
Are you by any chance running Node v4.x?   If so, downgrade to v0.12.x then do the install of nativescript.

**Comment by weilitao** [comment]
No, I already use node v0.12.7. It only show `Error: Unknown command 'dev-post-install'`, other looks ok.

**Comment by dtopuzov** [comment]
Try to clean your npm cache with "npm cache clean"

**Comment by weilitao** [comment]
@dtopuzov  I have tried as you said, the error doesn't change.

**Comment by NathanaelA** [comment]
@weilitao, just to make sure the instructions from @dtopuzov are clear you need to do a

1. npm remove nativescript -g
2. npm cache clean
3. npm install nativescript -g

The cache cleaning won't have any affect until you re-install it.  And you should de-install it first, then clean, then install.

**Comment by weilitao** [comment]
I have tried these steps, but the error `Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.` is still here. And I try to execute `tns help`, it is true no command `dev-post-install` listed here.

BTW, I try to compile the tutorial on android, everything looks ok.

**Comment by emmanuelbuah** [comment]
I had the same problem and removing, cleaning cache and installed worked for me. I also installed the last version of node v0.12.x.

**Comment by weilitao** [comment]
@emmanuelbuah I don't know why it doesn't work for me. 
Does anyone know what the command 'dev-post-install' do? I have already compiled some sample projects and no problem during compilation and execution.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#953
