### ISSUE TITLE
Release apk crashing at runtime

### ISSUE THREAD

**Issue by felixelgato92** [NativeScript/NativeScript#7863]
**Environment**
`tns info:`
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.1.2 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
✔ Component tns-android has 6.1.1 version and is up to date.
✔ Component tns-ios has 6.1.1 version and is up to date.

**Describe the bug**
The debug version runs as expected. However, whenever I run `tns run android --release (plus all --key-store*)`  fails at runtime. The command finishes with no error or warnings, but at runtime I get this, using "adb logcat":

```
09-24 14:24:50.884 19944 19944 D AndroidRuntime: Shutting down VM
09-24 14:24:50.885 19944 19944 E AndroidRuntime: FATAL EXCEPTION: main
09-24 14:24:50.885 19944 19944 E AndroidRuntime: Process: com.xactware.remodel, PID: 19944
09-24 14:24:50.885 19944 19944 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
09-24 14:24:50.885 19944 19944 E AndroidRuntime: ReferenceError: setTimeout is not defined
09-24 14:24:50.885 19944 19944 E AndroidRuntime: File: (file:///data/data/com.xactware.remodel/files/app/vendor.js:3323:8)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 

09-24 14:24:50.885 19944 19944 E AndroidRuntime: StackTrace: 
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	ɵ0$2(file:///data/data/com.xactware.remodel/files/app/vendor.js:3323:9)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/vendor.js:3326:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/vendor.js:31062:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.xactware.remodel/files/app/runtime.js:75:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/bundle.js:2402:12)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.xactware.remodel/files/app/runtime.js:75:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/bundle.js:17896:12)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.xactware.remodel/files/app/runtime.js:75:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/bundle.js:17156:70)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/bundle.js:17190:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.xactware.remodel/files/app/runtime.js:75:30)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at checkDeferredModules(file:///data/data/com.xactware.remodel/files/app/runtime.js:44:23)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at webpackJsonpCallback(file:///data/data/com.xactware.remodel/files/app/runtime.js:31:19)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at (file:///data/data/com.xactware.remodel/files/app/bundle.js:2:57)
09-24 14:24:50.885 19944 19944 E AndroidRuntime: 	at require(:1:266)
```
I think the important line is: `"E AndroidRuntime: ReferenceError: setTimeout is not defined"`

**To Reproduce**
`tns run android --release` (plus appropriate --key-store files). Also `Tns build android` also fails regardless of if it's debug or release mode. The error is the same in both cases
 **Expected behavior**
Launch with no runtime errors. 

**Additional context**
I recently upgraded my project from N5 to N6, and this hasn't worked ever since. I just noticed now because tns run android is working on debug mode.

**Comment by tsonevn** [comment]
Hi @felixelgato92,
Try to clear up the project by deleting `platforms`, `node_modules`, `hooks` folders and `package-lock.json`, `web-ack.config.js` files. Then rebuild the project with `tns build android` and check if the same problem will be reproduced.

**Comment by felixelgato92** [comment]
@tsonevn I got the same result. The `webpack-config.js` file has some custom changes, so I rebuilt it using `./node_modules/.bin/update-ns-webpack --deps --configs` and then added the changes again (otherwise it doesn't compile).

Mainly I added some rules to the file. I don't think they're relevant, but here they are just in case:

```
       // Weird mjs files from graphql
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto",
        },

       {
          test: /.generator.ts$|.atl.ts$/,
          use: "awesome-typescript-loader",
        },

        // Compile Worker files with ts-loader
        {
          test: /\.worker.ts$/,
          loader: ["nativescript-worker-loader", "awesome-typescript-loader"],
        },
        
        // This rule has already there, I just added the exclude parameters
        {
          test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
          exclude: /.worker.ts$|.generator.ts$|.atl.ts$/, // <-- I added this
          use: [
            "nativescript-dev-webpack/moduleid-compat-loader",
            "nativescript-dev-webpack/lazy-ngmodule-hot-loader",
            "@ngtools/webpack",
          ],
        },

```

**Comment by felixelgato92** [comment]
Just to verify if the `webpack.config.js` file had anything to do with it, I created a new project and copied my current file. It works just as expected on the new empty project. I'll try to narrow down what exactly is that `tns build android` doesn't like about my project.

**Comment by felixelgato92** [comment]
I compared the vendor.js files generated by `tns run android` and `tns build android` and except for the hmr section everything seems to be the same. Even the breaking line is on both vendor.js files. I'm still unsure as of what causes it to break. Maybe something with the migration process?

 In the mean time I found a workaround. Adding the --env.aot to `tns build android --env.aot` seems to resolve the problem.

**Comment by wpatter6** [comment]
I seem to be having a similar issue.  It'd really be helpful to know the way to troubleshoot issues like this where the app runs fine in debug mode but crashes immediately in release mode.  I'm able to pull logcat information but it doesn't tell anything useful.

I do notice that if I include the `--env.snapshot` flag on the android build, I get an error at build time -- could that be related?

**Comment by wpatter6** [comment]
After some searching I found this command flag that outputs a lot more than logcat: `--log trace > out.txt`

Almost too much to determine what to look for, but could be helpful.  

I'm going to attach mine if anyone out there can tell anything from it I'd be grateful:
[out.txt](https://github.com/NativeScript/NativeScript/files/3660332/out.txt)

**Comment by NickIliev** [comment]
@felixelgato92 you could see where in the code the app is crashing by opening the vendir.js file and searching for the specific part pointed in the error log (**_app/vendor.js:3323:8_**)

The output **vendor.js** file is located in **_<project>/platforms/android/app/src/assets/app/vendor.js_**

Please do let us know if the issue is coming from code within the `tns-core-modules`
