### ISSUE TITLE
tns-core-modules + nativescript-advanced-webview + navigation is crashing the app

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#7901]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.1.2
 - Cross-platform modules: 6.1.1
 - Android Runtime: 6.1.x
 - Plugin(s): nativescript-advaced-webview@4.0.1

**Describe the bug**
Navigating to a page that contains `BottomNavigation` (or `Tabs`) + having [nativescript-advanced-webview](https://github.com/bradmartin/nativescript-advanced-webview) as a **dependency** (not even explicitly used/initialized) is crashing the app with:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:
System.err: StackTrace:
System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:     at android.view.ViewGroup.addViewInner(ViewGroup.java:5034)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4865)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4805)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4778)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2656)
System.err:     at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2610)
System.err:     at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2076)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1821)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**To Reproduce**

 Use [this branch](https://github.com/NativeScript/login-tab-navigation-ng/tree/niliev/bottom-nav-scenario) of the test app.
- Navigate to the tabs page
- press the second navigation button
- return back to the tabs page

**Result:** the app will crash.
If you uninstall the nativescript-advanced-webview and make clean rebuild the issue will be gone.

**Sample project**
https://github.com/NativeScript/login-tab-navigation-ng/tree/niliev/bottom-nav-scenario

**Comment by oneWaveAdrian** [comment]
I have a similiar error coming up after trying to migrate. iOS Version runs just fine, only Android will produce the following bug on regular Tab switch (as described by poster above) when vuex store command has been used before.

I feel this is connected to this Issue #7901, if not please feel free to correct me.

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method setPrimaryItem failed
System.err: TypeError: Cannot read property 'unit' of undefined
System.err: 
System.err: StackTrace:
System.err: 	View.<computed>(file:///node_modules/tns-core-modules/ui/core/view/view.js:874:28)
System.err: 	at applyPendingNativeSetters(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:1025:28)
System.err: 	at initNativeView(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:987:8)
System.err: 	at ViewBase.onResumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:628:21)
System.err: 	at ViewBase._resumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:273:17)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:232:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:18)
System.err: 	at LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25)
System.err: 	at ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:13)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:18)
System.err: 	at LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25)
System.err: 	at ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:13)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:18)
System.err: 	at LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25)
System.err: 	at ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:13)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at TabViewItemBase.loadView(file:///node_modules/tns-core-modules/ui/tab-view/tab-view-common.js:82:42)
System.err: 	at (file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:429:21)
System.err: 	at TabView._loadUnloadTabItems(file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:426:15)
System.err: 	at FragmentPagerAdapter.setPrimaryItem(file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:149:24)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err: 	at com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_68979_26_FragmentPagerAdapter.setPrimaryItem(PagerAdapter_vendor_68979_26_FragmentPagerAdapter.java:54)
System.err: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1234)
System.err: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
System.err: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:992)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3301)
System.err: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2028)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2330)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8511)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7050)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by manoldonev** [comment]
[nativescript-advanced-webview](https://github.com/bradmartin/nativescript-advanced-webview) internally depends on [fancy-advanced-webview](https://github.com/triniwiz/fancy-advanced-webview) and the latter has a dependency on `androidx.appcompat:appcompat:1.1.0-rc01` in its build.gradle that is causing the problem. Currently this scenario works only with `androidx.appcompat:appcompat:1.0.0`.

**Comment by mitchdries** [comment]
Hello, I have the same issue in an app with [nativescript-material-components](https://github.com/Akylas/nativescript-material-components) when routing from a page with BottomNavigation to another page and then back.

This plugin is using androidx.appcompat:appcompat:1.1.0

Is there any workaround aside from downgrading the appcompat dependency?
