### ISSUE TITLE
Android Upgrade Bug `Calling js method setPrimaryItem failed`

### ISSUE THREAD

**Issue by oneWaveAdrian** [NativeScript/NativeScript#7904]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
```
✔ Component nativescript has 6.1.2 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
```
 - Cross-platform modules:
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.1
 - Plugin(s):
```
        "nativescript-barcodescanner": "^3.4.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-vibrate": "^2.1.3",
        "nativescript-vue": "2.3.0",
        "nativescript-zxing-compat": "^1.5.3",
        "tns-core-modules": "^6.1.1",
        "vuex": "^3.1.0"
```
**Describe the bug**

I have a similiar error as described in #7901 coming up after trying to migrate. iOS Version runs just fine, only Android will produce the following bug on regular Tab switch (as described by poster in mentioned Issue) when vuex store command has been used before.

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method setPrimaryItem failed
System.err: TypeError: Cannot read property 'unit' of undefined
System.err: 
System.err: StackTrace:
System.err: 	View.<computed>(file:///node_modules/tns-core-modules/ui/core/view/view.js:874:28)
System.err: 	at applyPendingNativeSetters(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:1025:28)
System.err: 	at initNativeView(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:987:8)
System.err: 	at ViewBase.onResumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:628:21)
System.err: 	at ViewBase._resumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:273:17)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:232:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:18)
System.err: 	at LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25)
System.err: 	at ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:13)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:18)
System.err: 	at LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25)
System.err: 	at ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:13)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:18)
System.err: 	at LayoutBaseCommon.eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:25)
System.err: 	at ViewCommon.eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:13)
System.err: 	at ViewBase.onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:13)
System.err: 	at View.onLoaded(file:///node_modules/tns-core-modules/ui/core/view/view.js:246:34)
System.err: 	at (file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:89)
System.err: 	at ViewBase.callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:8)
System.err: 	at ViewBase.callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:13)
System.err: 	at ViewBase.loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:17)
System.err: 	at TabViewItemBase.loadView(file:///node_modules/tns-core-modules/ui/tab-view/tab-view-common.js:82:42)
System.err: 	at (file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:429:21)
System.err: 	at TabView._loadUnloadTabItems(file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:426:15)
System.err: 	at FragmentPagerAdapter.setPrimaryItem(file:///node_modules/tns-core-modules/ui/tab-view/tab-view.js:149:24)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err: 	at com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_68979_26_FragmentPagerAdapter.setPrimaryItem(PagerAdapter_vendor_68979_26_FragmentPagerAdapter.java:54)
System.err: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1234)
System.err: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
System.err: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:992)
System.err: 	at android.view.View.measure(View.java:24966)
System.err: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3301)
System.err: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2028)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2330)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8511)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7050)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**To Reproduce**

`tns run android --bundle`

**Expected behavior**
Working app as it does when compiling for iOS.

**Sample project**

Not possible at the moment.

**Additional context**

**Comment by tsonevn** [comment]
HI @oneWaveAdrian,
I tested your case in a sample project, however, was unable to recreate the problem. For your convenience, I am attaching the project that I used for testing. Please review it and make the needed changes, that will allow us to reproduce the issue.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3689011/Archive.zip)

**Comment by oneWaveAdrian** [comment]
@tsonevn thanks for getting back to me so quickly.
I fail to reproduce the error with your example file as well so it seems not to be connected directly to vuex's `store` function what I suspected initially.

I traced the error message back to one of those files, all located in `tns-core-moudles/ui/`:

- `bottom-navigation.android.js`
- `tab-view.android.js`
- `tabs.android.js`

However none of these have a `unit` property that's why I am confused and seem to have reached a dead end on this. Do you have any clue, what exactly fails on this? I could be connected to a different method or component we use but as of now I am searching the literal pin in the haystack. It definitely has something to do with a call to `setPrimaryItem` on in of these files as iOS does not have that function call and thus works flawless. However I do not understand what exactly happens with these functions, any clues there?

**Comment by oneWaveAdrian** [comment]
@tsonevn Any clue that would be helpful for further exploration on my end? I am getting a bit frustrated since the iOS App is in stores already and Android is stuck right now. The only thing that was changed from our side apart from NS Upgrade was to exchange assets and URLs, so I don't think we broke it. I am willing to help figuring this out but have no idea where to look or start...

**Comment by tsonevn** [comment]
HI @oneWaveAdrian 
Excuse me for the delay in reply.
Without a way to reproduce the issue is hard to tell what can cause this error. Can you share with us the project?  You can do that in a private message on our [community slack](https://nativescriptcommunity.slack.com). My nickname is `nikts`. If this is not an option for you. You can share here at least the project full package.json and the files, where the Tabs or BottomNavigation are used.

**Comment by oneWaveAdrian** [comment]
Hi @tsonevn,
Thanks for the offer, but since I do not have a @telerik.com Email address I feel I can't log in to the community slack.

Hence please find the requested files below:

### Package.json
```
{
    "nativescript": {
        "id": "com.onewavestudios.XXXXXXXXXX",
        "tns-android": {
            "version": "6.1.2"
        },
        "tns-ios": {
            "version": "6.1.1"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "nativescript-barcodescanner": "^3.4.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-vibrate": "^2.1.3",
        "nativescript-vue": "2.3.0",
        "nativescript-zxing-compat": "^1.5.3",
        "tns-core-modules": "^6.1.1",
        "vuex": "^3.1.0"
    },
    "devDependencies": {
        "@babel/core": "~7.1.0",
        "@babel/preset-env": "~7.1.0",
        "@babel/register": "^7.0.0",
        "babel-loader": "~8.0.0",
        "chai": "^4.2.0",
        "mocha": "^6.2.1",
        "nativescript-dev-webpack": "^1.2.0",
        "nativescript-vue-template-compiler": "2.3.0",
        "node-sass": "^4.12.0",
        "proxyquire": "^2.1.3",
        "vue-loader": "~15.4.0"
    },
    "gitHead": "9b6565a4513375a33a59c44262dfc1d818a8205e",
    "readme": "NativeScript Application"
}
```

### Scanner Vue file

```
<template>
  <Page
    @navigatedFrom="clearAll"
    @loaded="loaded"
    @unloaded="unloaded"
    :class="{'primary-bgr':showBlueBackground}"
  >
    <ActionBar :title="title" flat="true">
      <ActionItem
        :visibility="visibilityCloseItem"
        @tap="closeList"
        ios.position="left"
        icon="res://arrow_left"
      />
      <NavigationButton
        :visibility="visibilityNagivationButton"
        :icon="nagivationButtonIcon"
        @tap="backPressed"
      />
      <bilogo/>
      <ActionItem @tap="openMenu" ios.position="right" text="···"/>
    </ActionBar>
    <GridLayout>
      <TabView
        :selectedIndex="selectedIndex"
        @selectedIndexChanged="changeTab"
        iosIconRenderingMode="alwaysOriginal"
        androidTabsPosition="bottom"
        class="first-content"
        tabBackgroundColor="#ffffff"
        tabTextColor="#1e1e1e"
        selectedTabTextColor="#7595fa"
      >
        <TabViewItem title="Klasse" iconSource="res://tab_klasse_icon" v-if="showClassTab">
          <FlexboxLayout class="p-10" flexDirection="column">
            <FlexboxLayout flexDirection="row" class="zero-grow-shrink">
              <Label
                text="Klassenfoto"
                class="white-bgr bold rounded-t uppercase zero-grow"
                padding="10"
              />
            </FlexboxLayout>
            <StackLayout class="white-bgr rounded-tr p-10" flexGrow="1">
              <ClassList v-if="!currentClass" height="100%" @selected="selectClass"/>
              <FlexboxLayout v-else flexDirection="column" height="100%">
                <FlexboxLayout
                  flexDirection="row"
                  class="border-bottom zero-grow-shrink"
                  margin="1% 20 2%"
                  paddingBottom="4"
                  @tap="promptClass"
                  height="30"
                >
                  <Image
                    src="res://klasse_icon"
                    margin="0 10 0 5"
                    height="22"
                    width="22"
                    stretch="aspectFit"
                  />
                  <Label :text="currentClass" class="bold" flexGrow="1"/>
                  <Image
                    src="res://checkmark_green_icon"
                    class="zero-grow-shrink"
                    margin="0 5 0 15"
                    height="22"
                    width="22"
                    stretch="aspectFit"
                  />
                </FlexboxLayout>
                <Gap flexShrink="1" flexGrow="1"/>
                <ShootNow :highlighted="currentClass" addition="die Klasse " flexGrow="0"/>
                <Gap flexShrink="1" flexGrow="1"/>
                <Button
                  class="btn btn-primary btn-rounded-lg zero-grow-shrink"
                  text="Nächste Klasse"
                  @tap="newClass"
                  margin="5 20 5"
                />
                <Button
                  class="btn btn-secondary btn-rounded-lg zero-grow-shrink"
                  text="Portrait"
                  @tap="gotoPortrait"
                  margin="5 20 5"
                />
              </FlexboxLayout>
            </StackLayout>
          </FlexboxLayout>
        </TabViewItem>
        <TabViewItem title="Portrait" iconSource="res://tab_profile_icon">
          <FlexboxLayout class="p-10" flexDirection="column">
            <FlexboxLayout flexDirection="row" class="zero-grow-shrink">
              <Label
                text="Portraitfoto"
                class="white-bgr bold rounded-t uppercase zero-grow"
                padding="10"
              />
            </FlexboxLayout>
            <StackLayout class="white-bgr rounded-tr p-10" flexGrow="1">
              <ClassList v-if="isPromptingClass" height="100%" @selected="selectClass"/>
              <NameList v-else-if="isPromptingName" height="100%" @selected="selectName"/>
              <template v-else>
                <FlexboxLayout flexDirection="column" height="100%">
                  <FlexboxLayout
                    v-if="currentEmployer.type !== 'event'"
                    flexDirection="row"
                    class="border-bottom zero-grow-shrink"
                    margin="1% 20 2%"
                    paddingBottom="4"
                    @tap="promptClass"
                    height="30"
                  >
                    <Image
                      src="res://klasse_icon"
                      margin="0 10 0 5"
                      height="22"
                      width="22"
                      stretch="aspectFit"
                    />
                    <Label :class="{'bold':currentClass}" flexGrow="1">
                      <FormattedString>
                        <span v-if="currentClass" :text="currentClass"/>
                        <span v-else text="Klasse auswählen"/>
                      </FormattedString>
                    </Label>
                    <Image
                      v-if="currentClass"
                      src="res://checkmark_green_icon"
                      class="zero-grow-shrink"
                      margin="0 5 0 15"
                      height="22"
                      width="22"
                      stretch="aspectFit"
                    />
                  </FlexboxLayout>

                  <FlexboxLayout
                    flexDirection="row"
                    class="border-bottom zero-grow-shrink"
                    margin="1% 20 2%"
                    paddingBottom="4"
                    @tap="promptName"
                    height="30"
                  >
                    <Image
                      src="res://profile_icon"
                      class="zero-grow-shrink"
                      margin="0 10 0 5"
                      height="22"
                      width="22"
                      stretch="aspectFit"
                    />
                    <Label :class="{'bold':currentName}" flexGrow="1">
                      <FormattedString>
                        <span v-if="currentName" :text="currentName"/>
                        <span v-else text="Name auswählen"/>
                      </FormattedString>
                    </Label>
                    <Image
                      v-if="currentName"
                      src="res://checkmark_green_icon"
                      class="zero-grow-shrink"
                      margin="0 5 0 15"
                      height="22"
                      width="22"
                      stretch="aspectFit"
                    />
                  </FlexboxLayout>

                  <FlexboxLayout
                    flexDirection="row"
                    class="border-bottom zero-grow-shrink"
                    margin="1% 20 2%"
                    paddingBottom="4"
                    @tap="singleScan"
                    height="30"
                  >
                    <Image
                      src="res://qr_code_icon"
                      margin="0 10 0 5"
                      height="22"
                      width="22"
                      stretch="aspectFit"
                    />
                    <Label :class="{'bold':hasCodes}" flexGrow="1">
                      <FormattedString>
                        <span v-if="hasCodes" :text="formatCode(currentCodes[0])"/>
                        <span v-else text="QR-Karte scannen"/>
                      </FormattedString>
                    </Label>
                    <Image
                      v-if="hasCodes"
                      src="res://checkmark_green_icon"
                      class="zero-grow-shrink"
                      margin="0 5 0 15"
                      height="22"
                      width="22"
                      stretch="aspectFit"
                    />
                  </FlexboxLayout>

                  <template v-if="hasCodes">
                    <Gap flexShrink="1" flexGrow="1"/>
                    <ShootNow :highlighted="currentName" flexGrow="0"/>
                    <Gap flexShrink="1" flexGrow="1"/>
                    <Button
                      class="btn btn-secondary btn-rounded-lg zero-grow-shrink"
                      text="Nächstes Portait"
                      @tap="nextPortrait"
                      margin="5 20 5"
                    />
                    <Button
                      class="btn btn-primary btn-rounded-lg zero-grow-shrink"
                      text="Nächste Klasse"
                      @tap="gotoClass"
                      margin="5 20 5"
                    />
                  </template>
                  <FlexboxLayout
                    v-else
                    flexGrow="1"
                    flexDirection="column"
                    justifyContent="center"
                    padding="10"
                  >
                    <FlexboxLayout flexDirection="row" justifyContent="center">
                      <Label
                        text="Wichtig!"
                        class="h1 text-primary bold center border-bottom uppercase"
                        paddingBottom="5"
                        marginBottom="10"
                        textWrap="true"
                      />
                    </FlexboxLayout>
                    <Label text="1. Klasse auswählen." textWrap="true"/>
                    <Label text="2. Name eingeben." textWrap="true"/>
                    <Label text="3. QR-Karten scannen." textWrap="true"/>
                    <Label text="4. Fotografieren." textWrap="true"/>
                    <Label text="5. QR-Karte aushändigen." textWrap="true"/>
                  </FlexboxLayout>
                </FlexboxLayout>
              </template>
            </StackLayout>
          </FlexboxLayout>
        </TabViewItem>
        <TabViewItem title="Gruppe" iconSource="res://tab_group_icon">
          <FlexboxLayout class="p-10" flexDirection="column">
            <FlexboxLayout flexDirection="row" class="zero-grow-shrink">
              <Label
                text="Gruppenfoto"
                class="white-bgr bold rounded-t uppercase zero-grow"
                padding="10"
              />
            </FlexboxLayout>
            <FlexboxLayout flexDirection="column" class="white-bgr rounded-tr p-10" flexGrow="1">
              <template v-if="hasCodes">
                <FlexboxLayout
                  flexGrow="1"
                  flexDirection="column"
                  justifyContent="flex-start"
                  margin="0"
                >
                  <Label
                    :text="'Anzahl gescannter QR-Karten: ' + currentCodes.length"
                    class="zero-grow-shrink center bold border-bottom"
                    margin="0 15 3%"
                    textWrap="true"
                  />
                  <ScrollView height="40%" class="zero-grow-shrink">
                    <StackLayout margin="-7 0">
                      <Label
                        v-for="(code, index) in currentCodes"
                        :key="index"
                        :text="formatCode(code)"
                        class="bold center"
                        margin="7 15"
                      />
                    </StackLayout>
                  </ScrollView>
                  <Gap flexShrink="1" flexGrow="1"/>
                  <ShootNow highlighted="die Gruppe" class="zero-grow" flexShrink="1"/>
                  <Gap flexShrink="1" flexGrow="1"/>
                </FlexboxLayout>
                <Button
                  class="btn btn-secondary btn-rounded-lg zero-grow-shrink"
                  text="Nächste Gruppe"
                  @tap="multiScan"
                  margin="0 20 5"
                />
              </template>
              <template v-else>
                <FlexboxLayout
                  flexDirection="column"
                  margin="10"
                  justifyContent="center"
                  flexGrow="1"
                >
                  <Label
                    text="Wichtig!"
                    class="h1 text-primary bold center uppercase"
                    marginBottom="15"
                    textWrap="true"
                  />
                  <Label text="1. QR-Karten scannen." textWrap="true"/>
                  <Label
                    text="2. Wenn alle Teilnehmer gescannt wurden, 'zurück' klicken."
                    textWrap="true"
                  />
                  <Label text="3. Fotografieren." textWrap="true"/>
                  <Label text="4. QR-Karten aushändigen." textWrap="true"/>
                </FlexboxLayout>
                <Button
                  class="btn btn-primary btn-rounded-lg zero-grow"
                  text="QR-Karten scannen"
                  @tap="multiScan"
                  margin="0 20 5"
                />
              </template>
            </FlexboxLayout>
          </FlexboxLayout>
        </TabViewItem>
      </TabView>
    </GridLayout>
  </Page>
</template>

<script>
import { mapGetters, mapActions } from 'vuex'

import { action } from './action'
import { android, AndroidApplication } from 'tns-core-modules/application'
import { isIOS } from 'tns-core-modules/platform'

import ShootNow from './_ShootNow'
import ClassList from './_ClassList'
import NameList from './_NameList'
import bilogo from './_bi-logo'
import Gap from './_Gap'

export default {
    components: {
        ShootNow,
        ClassList,
        NameList,
        bilogo,
        Gap,
    },
    data() {
        return {
            selectedIndex: 0,
            isPromptingClass: false,
            isPromptingName: false,
        }
    },
    computed: {
        ...mapGetters([
            'useFrontCamera',
            'currentClass',
            'currentName',
            'currentCodes',
            'currentEmployer',
        ]),
        hasCodes() {
            return this.currentCodes && this.currentCodes.length > 0
        },

        title() {
            return ['Klasse', 'Portrait', 'Gruppe'][this.selectedIndex]
        },
        isListOpen() {
            return this.isPromptingClass || this.isPromptingName
        },
        nagivationButtonIcon() {
            if (this.isListOpen) {
                return 'res://arrow_left'
            } else {
                return 'res://actionbar_home_icon'
            }
        },
        visibilityNagivationButton() {
            if (isIOS && this.isListOpen) {
                return 'collapse'
            } else {
                return 'visible'
            }
        },
        visibilityCloseItem() {
            if (isIOS && this.isListOpen) {
                return 'visible'
            } else {
                return 'collapse'
            }
        },
        showBlueBackground() {
            return (
                (this.showClassTab &&
                    this.selectedIndex == 0 &&
                    this.currentClass) ||
                this.hasCodes
            )
        },
        showClassTab() {
            return this.currentEmployer.type !== 'event'
        },
    },
    methods: {
        ...mapActions(['singleScan', 'multiScan']),
        formatCode(code) {
            return code.replace(/(.{3})/g, '$1 ') // insert space
        },
        promptClass() {
            if (!this.currentClass || !this.hasCodes) {
                this.isPromptingClass = true
            }
        },
        promptName() {
            if (!this.currentName || !this.hasCodes) {
                this.isPromptingName = true
            }
        },
        selectClass(class_) {
            this.isPromptingClass = false
            this.$store.commit('setClass', class_)
        },
        newClass() {
            this.$store.commit('clearClass')
        },
        selectName(name) {
            this.isPromptingName = false
            this.$store.commit('setName', { name, class_: this.currentClass })
            this.singleScan()
        },
        nextPortrait() {
            this.isPromptingName = !!this.currentName
            this.$store.commit('clearCodes')
            this.$store.commit('clearName')
        },
        gotoPortrait() {
            this.selectedIndex = 1
        },
        gotoClass() {
            this.selectedIndex = 0
        },
        changeTab({ newIndex, oldIndex }) {
            if (
                this.showClassTab &&
                oldIndex === 0 &&
                newIndex === 1 &&
                this.currentClass
            ) {
                this.keepClass = true
                this.isPromptingName = true
            }

            this.selectedIndex = newIndex

            if (!this.keepClass) {
                this.$store.commit('clearAll')
                this.isPromptingName = false
            }
            this.keepClass = false
        },
        clearAll() {
            this.$store.commit('clearAll')
        },
        openMenu() {
            action('Menü', 'Abbrechen', {
                [this.useFrontCamera
                    ? 'Zur Rückkamera wechseln'
                    : 'Zur Frontkamera wechseln']: () => {
                    this.$store.commit('useFrontCamera', !this.useFrontCamera)
                },
                Zeitstempel: () => {
                    this.$store.commit('showQRCode', true)
                    this.$navigateBack()
                },
            })
        },
        closeList() {
            this.isPromptingClass = false
            this.isPromptingName = false
        },
        loaded() {
            if (android) {
                android.on(
                    AndroidApplication.activityBackPressedEvent,
                    args => {
                        if (this.isListOpen) {
                            args.cancel = true
                            this.closeList()
                        }
                    }
                )
            }
        },
        unloaded() {
            if (android) {
                android.off(AndroidApplication.activityBackPressedEvent)
            }
        },
        backPressed() {
            if (this.isListOpen) {
                this.closeList()
            } else {
                this.$navigateBack()
            }
        },
    },
}
</script>
```

The app crashes once the user returns from any of the scanner views back to this file. But not all the time and only on Android, as described above.

**Comment by oneWaveAdrian** [comment]
Hey @NickIliev did the code up there help solve the issue in any ways? Is there anything else I could try?
Thanks!
Adrian

**Comment by kanayo** [comment]
Don't know if this will help, but I started getting the same stack trace when I accidentally added a reference to a non-existent variable in one of the components in a TabView:

`<StackLayout  [width]="notARealVariable" >`

Maybe not related, since, for me, this happened every time the page was opened.
