### ISSUE TITLE
Apk --release mode only HttpClient get request crash

### ISSUE THREAD

**Issue by jeffswitzer** [NativeScript/NativeScript#7933]
Upon migrating an angular Nativescript project from 5.4. to 6.1.2 discovered I needed to use
import { HttpClient, HttpHeaders } from "@angular/common/http";
instead of 
import { Http } from "@angular/http";

This seemed to go well using tns run android, but when switching to tns run android --release the app locks upon the first http get request. Below is the code block where this happens. To help debug I added 3 alerts and only the first ever shows.

 ```
async getPersonFromServer(accessToken, consumerKey) {
        const serviceRequest = `${this.serviceName}?access_token=${accessToken}&consumer_key=${consumerKey}`;
        const getUrl = this.baseUrl + serviceRequest;
        alert('gets here');
        let people = await this.http.get<Person[]>(getUrl)
        .catch(err => {
            alert('doesnt get here');
            this._databaseService.logSyncError(err);
            return of([]);
        }).toPromise();
        alert('doesnt get here');
        return people;
    }
```

This is what the call looks like
```
...
this._zone.run(() => this._router.navigate(["/syncing"]));
let people = await this._peopleService.getPersonFromServer(jsonResult.oauth_token, this._oauthService.consumerKey);
if(people.length > 0) {
...
```

I don't see any errors in the console, but running adb log I think this happens at about the time the http.get kicks off. Seems unrelated as I'm not really doing anything with an image at this point.
```
10-09 09:35:51.964  3954  3954 I ExifInterface_JNI: Raw image not detected
10-09 09:35:51.973  3954  3954 W ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
10-09 09:35:51.973  3954  3954 W ExifInterface: java.io.IOException: Invalid marker: 89
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.media.ExifInterface.<init>(ExifInterface.java:1112)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.image.Fetcher.getExifInterface(Fetcher.java:435)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.image.Fetcher.decodeSampledBitmapFromFile(Fetcher.java:472)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.image.Fetcher.processBitmap(Fetcher.java:263)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.image.Worker.loadImage(Worker.java:119)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.BorderDrawable.refresh(BorderDrawable.java:272)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.Runtime.callJSMethodNative(Native Method)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:20)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:574)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at org.nativescript.widgets.Async$Http$1$1.run(Async.java:304)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.os.Handler.handleCallback(Handler.java:751)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.os.Looper.loop(Looper.java:154)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at android.app.ActivityThread.main(ActivityThread.java:6154)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
10-09 09:35:51.973  3954  3954 W ExifInterface: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

Any ideas? Maybe I could get more info if I can figure out how to get vscode to debug using --release mode so I can have breakpoints.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-angular #2006](https://github.com/NativeScript/nativescript-angular/issues/2006) via [**ZenHub**](https://www.zenhub.com/)
