### ISSUE TITLE
IOS Fails to run on device:  Error is: Cannot read property 'Type' of null.

### ISSUE THREAD

**Issue by bellalMohamed** [NativeScript/NativeScript#8010]
Error is: Cannot read property 'Type' of null.

The trace:
```
Will emit event runOnDeviceError with data {
  projectDir: '/Users/Hidden/path',
  deviceIdentifier: 'Hidden',
  applicationIdentifier: 'com.package.dev',
  error: TypeError: Cannot read property 'Type' of null
      at ExportOptionsPlistService.getExportOptionsMethod (/usr/local/lib/node_modules/nativescript/lib/services/ios/export-options-plist-service.js:85:21)
      at ExportOptionsPlistService.createDevelopmentExportOptionsPlist (/usr/local/lib/node_modules/nativescript/lib/services/ios/export-options-plist-service.js:11:42)
      at XcodebuildService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-service.js:43:60)
      at Generator.next (<anonymous>)
      at /usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-service.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-service.js:3:12)
      at XcodebuildService.createDevelopmentArchive (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-service.js:41:16)
      at XcodebuildService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-service.js:22:44)
      at Generator.next (<anonymous>)
      at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-service.js:4:58)
      at processTicksAndRejections (internal/process/task_queues.js:82:5)
}
```

**Comment by tsonevn** [comment]
Hi @bellalMohamed,
The given information is not enough to investigate further the case. On that matter, follow up the template and provide the requested info. Thank you in advance. ->
```
 **Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```
