### ISSUE TITLE
NullPointerException with mixed parent / nested frame None navigation on API 19

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/NativeScript#8053]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules: 6.2.0
 - Android Runtime: 6.2.0

**Describe the bug**
App crashes in nested frame scenario with mixed parent frame / nested frame navigation with Flip transition.

**To Reproduce**
1. Navigate to "Page w/ bottom navigation"
2. Navigate to "Player Two (no transition)"
3. Send the app to the background.
4. Navigate back with hardware button.
5. Send the app to the background.
6. Navigate to "Player Two (no transition)  

`An uncaught Exception occurred on "main" thread.
java.lang.NullPointerException
	at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:797)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
	at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)`

**Sample project**
[nested-frame-navigation](https://github.com/NativeScript/NativeScript/tree/master/e2e/nested-frame-navigation)

**Additional context**
Reproducible only on Android with API Level 19.

**Comment by SvetoslavTsenov** [comment]
Related to #6798 
https://github.com/NativeScript/NativeScript/pull/8035
