### ISSUE TITLE
"Cannot read property 'replace' of undefined" after upgrade

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#8119]
After upgrading system I get error Cannot read property 'replace' of undefined, see below.
tns doctor all is ok (see below)
I tried removing platform android and restarting computer and Windows 10. The following is the trace. I have no clue what might be wrong. 

`[NativeScriptCli] execute: tns --analyticsClient VSCode --version
Version: 0.11.0
Build version: v.2019.10.17.1
Commit id: ff2e91fd92d5d9562dcb4a6592aa1e9ae934eb1f
NativeScript CLI: 6.2.1
[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NSDebugAdapter] Using tns CLI v6.2.1 on path 'tns'

[NSDebugAdapter] Running tns command...

[NativeScriptCli] execute: tns --analyticsClient VSCode debug android --watch 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token

Searching for devices...

Copying template files...

Platform android successfully added. v6.2.0

Preparing project...

File change detected. Starting incremental webpack compilation...

Starting type checking service...

Using 1 worker with 4096MB memory limit

webpack is watching the files…

Hash: ee0e01bd61f48201091e
Version: webpack 4.27.1
Time: 12491ms
Built at: 2019-11-19 3:10:47 PM
                                             Asset       Size   Chunks             Chunk Names
                  App-vm/data/images/add_below.png   1.85 KiB           [emitted]  
          App-vm/data/images/arrow_down_unfold.png   1.11 KiB           [emitted]  
  App-vm/data/images/arrow_left_gettable_child.png  993 bytes           [emitted]  
App-vm/data/images/arrow_right_gettable_parent.png   1.14 KiB           [emitted]  
              App-vm/data/images/arrow_up_fold.png   1.12 KiB           [emitted]  
                   App-vm/data/images/camera.1.png  846 bytes           [emitted]  
                     App-vm/data/images/camera.png  846 bytes           [emitted]  
                  App-vm/data/images/child_get.png  956 bytes           [emitted]  
                      App-vm/data/images/close.png   1.61 KiB           [emitted]  
                   App-vm/data/images/edit_off.png   2.92 KiB           [emitted]  
                    App-vm/data/images/edit_on.png   2.05 KiB           [emitted]  
                App-vm/data/images/folder_open.png   1.52 KiB           [emitted]  
                      App-vm/data/images/mappi.png   2.76 KiB           [emitted]  
                       App-vm/data/images/menu.png  263 bytes           [emitted]  
                 App-vm/data/images/parent_get.png  920 bytes           [emitted]  
                   App-vm/data/images/part_add.png   1.22 KiB           [emitted]  
                      App-vm/data/images/trash.png   2.13 KiB           [emitted]  
                                         bundle.js   10.3 MiB   bundle  [emitted]  bundle
                                      package.json  112 bytes           [emitted]  
                                        runtime.js   71.4 KiB  runtime  [emitted]  runtime
                               tns-java-classes.js    0 bytes           [emitted]  
                                         vendor.js   4.99 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 174 bytes {bundle} [built]
[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 12.8 KiB {bundle} [built]
[./App-vd/bs.js] 40.2 KiB {bundle} [optional] [built]
[./App-vd/bs.ts] 40.3 KiB {bundle} [optional] [built]
[./App-vd/data/export.js] 1.74 KiB {bundle} [optional] [built]
[./App-vd/data/export.ts] 1.88 KiB {bundle} [built]
[./App-vd/data/files.js] 5.72 KiB {bundle} [optional] [built]
[./App-vd/data/files.ts] 5.58 KiB {bundle} [built]
[./App-vd/data/guide.js] 143 KiB {bundle} [optional] [built]
[./App-vd/data/guide.ts] 143 KiB {bundle} [built]
[./App-vd/data/import.js] 2.18 KiB {bundle} [optional] [built]
[./App-vd/data/import.ts] 2.36 KiB {bundle} [built]
[./App-vd/data/mindmap.js] 17.9 KiB {bundle} [optional] [built]
[./App-vm/core/backButton.ts] 1.22 KiB {bundle} [built]
[./app.ts] 2.45 KiB {bundle} [built]
    + 619 hidden modules

Webpack compilation complete. Watching for file changes.

Webpack build done!

Project successfully prepared (android)

Building project...

Gradle build...

	 + setting applicationId

	 + applying user-defined configuration from C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\app\App_Resources\Android\app.gradle

	 + using android X library androidx.legacy:legacy-support-v4:1.0.0

	 + adding nativescript runtime package dependency: nativescript-optimized-with-inspector

	 + adding aar plugin dependency: C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\node_modules\nativescript-audio\platforms\android\nativescript_audio.aar

	 + adding aar plugin dependency: C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\node_modules\nativescript-speech-recognition\platforms\android\nativescript_speech_recognition.aar

	 + adding aar plugin dependency: C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\node_modules\nativescript-vibrate\platforms\android\nativescript_vibrate.aar

	 + adding aar plugin dependency: C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar

Project successfully built.

The build result is located at: C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\platforms\android\app\build\outputs\apk\debug\app-debug.apk

Installing on device ZL5225ZJ9R...

Successfully installed on device with identifier 'ZL5225ZJ9R'.

Restarting application on device ZL5225ZJ9R...

JS: HMR: Hot Module Replacement Enabled. Waiting for signal.

device: ZL5225ZJ9R debug port: 40000

To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000

Successfully synced application org.nativescript.MemoTalks001 on device ZL5225ZJ9R.

System.err: An uncaught Exception occurred on "main" thread.

System.err: Unable to start activity ComponentInfo{org.nativescript.MemoTalks001/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed

System.err: Error: Building UI from XML. @app-root.xml:11:1

System.err:  > Cannot read property 'replace' of undefined

System.err: 

System.err: StackTrace:

System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.MemoTalks001/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed

System.err: Error: Building UI from XML. @app-root.xml:11:1

System.err:  > Cannot read property 'replace' of undefined

System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)

System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)

System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)

System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)

System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)

System.err: 	at android.os.Looper.loop(Looper.java:193)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6923)

System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:11:1

System.err:  > Cannot read property 'replace' of undefined

System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)

System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)

System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1160)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1138)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1134)

System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)

System.err: 	at android.app.Activity.performCreate(Activity.java:7148)

System.err: 	at android.app.Activity.performCreate(Activity.java:7139)

System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)

System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)

System.err: 	... 11 more

[NSDebugAdapter] Ready to attach to application on 40000`

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

System: Windows 10, Visual Studio Code, 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1>
PS C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1> tns doctor
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 6.2.1 version and is up to date.
√ Component tns-core-modules has 6.2.1 version and is up to date.
√ Component tns-android has 6.2.0 version and is up to date.
√ Component tns-ios has 6.2.0 version and is up to date.
PS C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1>

Errorl log:

**Comment by jokro** [comment]
The issue is solved. Visual studio did not provide the proper location of the problem, and that is why it is diffucult to trace. This is a bug in the VS system, I think. After a day of digging I found a second bug. It turned out that a line of code I removed in the ts-file, did not disappear in the js-file. When I removed the js-file, the line reappeared ! Possibly the file wasn't recompiled but regenerated from the webpack ?
