### ISSUE TITLE
IOS: JS ERROR ReferenceError: Can't find variable: GMSMapViewDelegate

### ISSUE THREAD

**Issue by mansurov1024** [NativeScript/NativeScript#8154]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 10.1.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.2.2 version and is up to date.
✔ Component tns-core-modules has 6.2.3 version and is up to date.
✔ Component tns-android has 6.2.0 version and is up to date.
✔ Component tns-ios has 6.2.0 version and is up to date.

**Describe the bug**
 
Successfully synced application **** on device 796263C9-44D9-461D-AA9A-4F6B1CAA6B8A.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1 0x10acfa0ee NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2 0x10ad44398 -[TNSRuntime executeModule:referredBy:]
3 0x10a6db973 main
4 0x10e742575 start
5 0x1
JavaScript stack trace:
file:///node_modules/nativescript-google-maps-sdk/map-view.js:178:0
at ../node_modules/nativescript-google-maps-sdk/map-view.js(file:///node_modules/nativescript-google-maps-sdk/map-view.js:180:1)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ./pages/list/map/map.component.ts(file:///app/pages/list/map/map.component.ts:1:0)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ./app.module.ts(file:///app/app.module.ts:1:0)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at file:///app/bundle.js:3751:88
at ./main.ts(file:///app/bundle.js:3813:34)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
JavaScript error:
file:///node_modules/nativescript-google-maps-sdk/map-view.js:178:0: JS ERROR ReferenceError: Can't find variable: GMSMapViewDelegate
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: GMSMapViewDelegate
at
file:///node_modules/nativescript-google-maps-sdk/map-view.js:178:0
at ../node_modules/nativescript-google-maps-sdk/map-view.js(file:///node_modules/nativescript-google-maps-sdk/map-view.js:180:1)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ./pages/list/map/map.component.ts(file:///app/pages/list/map/map.component.ts:1:0)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ./app.module.ts(file:///app/app.module.ts:1:0)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at file:///app/bundle.js:3751:88
at ./main.ts(file:///app/bundle.js:3813:34)
at webpack_require(file:///app/webpack/bootstrap:750:0)
at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promis<…>
NativeScript caught signal 6.
Native Stack:
1 0x10ad42ff1 sig_handler(int)
2 0x10eaa6f5a _sigtramp
3 0x10ac6b270
4 0x10e82ec45 abort
5 0x10e5bb5b1 __cxa_bad_cast
6 0x10e5bb74d default_unexpected_handler()
7 0x10cf88a9d _objc_terminate()
8 0x10e5c765e std::__terminate(void ()())
9 0x10e5c7102 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception)
10 0x10cf8886a _objc_exception_destructor(void*)
11 0x10acfa572 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
12 0x10ad44398 -[TNSRuntime executeModule:referredBy:]
13 0x10a6db973 main
14 0x10e742575 start
15 0x1
JS Stack:

**Comment by NickIliev** [comment]
@mansurov1024 it seems that the issue is caused by a plugin called [nativescript-google-maps-sdk](https://github.com/dapriett/nativescript-google-maps-sdk#readme). Please post an issue in the plugin's repository as the error is related to its codebase.

**Comment by mansurov1024** [comment]
I resolved it with adding ../App_Resources/iOS/Podfile to my app

```
platform :ios, '9.0'

use_frameworks!
pod 'GoogleMaps'
```

**Comment by thubamamba** [comment]
I included all that but still I have the error. Anyone know how to fix this? Please.
