### ISSUE TITLE
Updated to latest IOS, won't build

### ISSUE THREAD

**Issue by curtiscarlson** [NativeScript/NativeScript#8239]
This is getting old real quick!!  Not the first time and I am realizing it wont be the last.  I have tried updating nativescript, updating my project, updating my ios, updating xcode, updating everything.  It will not build.  (it build just fine like, a week ago) . It says "user has not accepted the pairing request".  I have.  On both devices, multiple times.  I keep blowing out the settings and resetting and it doesn't matter.  It thinks that the device has not responded to the pairing request, no matter what I do.  

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: updated to latest
 - Cross-platform modules:  ??
 - Android Runtime:
 - iOS Runtime:  13.3
 - Plugin(s):  firebase

**Describe the bug**
Won't build.  It claims "the user has not responded to the pairing request".  This is untrue.  I blew out all of the phone settings and when I plug it into the macbook, it asks me to trust it which I do, on both devices.  Yet it claims The user has not responded.  

**To Reproduce**
tns run ios
 
**Expected behavior**
app builds 

**Sample project**

**Additional context**
DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fa7cd6922b0:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/DeviceSupport/6.1/DeveloperDiskImage.dmg'>', error=-402653034: Error Domain=com.apple.dtdevicekit Code=-402653034 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=The user has not yet responded to the pairing request., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000110f626e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x0000000110f62de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000110fa0780 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
	3   DTDeviceKitBase                     0x0000000110fa129d __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 699
	4   libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	5   libdispatch.dylib                   0x00007fff5cc82129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	6   DTDeviceKitBase                     0x0000000110fa0f80 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
	7   IDEiOSSupportCore                   0x0000000110b5c107 __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
	8   DVTFoundation                       0x00000001012fbe8a __DVT_CALLING_CLIENT_BLOCK__ + 7
	9   DVTFoundation                       0x00000001012fd562 __DVTDispatchAsync_block_invoke + 809
	10  libdispatch.dylib                   0x00007fff5cc755f8 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff5cc78de6 _dispatch_continuation_pop + 414
	13  libdispatch.dylib                   0x00007fff5cc784a3 _dispatch_async_redirect_invoke + 703
	14  libdispatch.dylib                   0x00007fff5cc843bc _dispatch_root_queue_drain + 324
	15  libdispatch.dylib                   0x00007fff5cc84b46 _dispatch_worker_thread2 + 90
	16  libsystem_pthread.dylib             0x00007fff5ceb66b3 _pthread_wqthread + 583
	17  libsystem_pthread.dylib             0x00007fff5ceb63fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
2020-01-10 20:43:26.176 xcodebuild[628:7703]  iPhoneSupport: 📱<DVTiOSDevice (0x7fa7cd60bda0), iPhone, iPhone, 13.3 (17C54), ce4ada5943169eabdead45103bfd40c686a97e62> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit Code=-402653034 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=The user has not yet responded to the pairing request., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000110f626e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x0000000110f62de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000110fa0780 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
	3   DTDeviceKitBase                     0x0000000110fa129d __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 699
	4   libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	5   libdispatch.dylib                   0x00007fff5cc82129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	6   DTDeviceKitBase                     0x0000000110fa0f80 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
	7   IDEiOSSupportCore                   0x0000000110b5c107 __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
	8   DVTFoundation                       0x00000001012fbe8a __DVT_CALLING_CLIENT_BLOCK__ + 7
	9   DVTFoundation                       0x00000001012fd562 __DVTDispatchAsync_block_invoke + 809
	10  libdispatch.dylib                   0x00007fff5cc755f8 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff5cc78de6 _dispatch_continuation_pop + 414
	13  libdispatch.dylib                   0x00007fff5cc784a3 _dispatch_async_redirect_invoke + 703
	14  libdispatch.dylib                   0x00007fff5cc843bc _dispatch_root_queue_drain + 324
	15  libdispatch.dylib                   0x00007fff5cc84b46 _dispatch_worker_thread2 + 90
	16  libsystem_pthread.dylib             0x00007fff5ceb66b3 _pthread_wqthread + 583
	17  libsystem_pthread.dylib             0x00007fff5ceb63fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error})
2020-01-10 20:43:29.456 xcodebuild[628:7700]  DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fa7cd6922b0:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/DeviceSupport/6.1/DeveloperDiskImage.dmg'>', error=-402653034: Error Domain=com.apple.dtdevicekit Code=-402653034 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=The user has not yet responded to the pairing request., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000110f626e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x0000000110f62de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000110fa0780 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
	3   DTDeviceKitBase                     0x0000000110fa129d __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 699
	4   libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	5   libdispatch.dylib                   0x00007fff5cc82478 _dispatch_sync_invoke_and_complete_recurse + 65
	6   libdispatch.dylib                   0x00007fff5cc81fe6 _dispatch_sync_f_slow + 195
	7   DTDeviceKitBase                     0x0000000110fa0f80 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
	8   IDEiOSSupportCore                   0x0000000110b5c107 __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
	9   DVTFoundation                       0x00000001012fbe8a __DVT_CALLING_CLIENT_BLOCK__ + 7
	10  DVTFoundation                       0x00000001012fd562 __DVTDispatchAsync_block_invoke + 809
	11  libdispatch.dylib                   0x00007fff5cc755f8 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00007fff5cc78de6 _dispatch_continuation_pop + 414
	14  libdispatch.dylib                   0x00007fff5cc784a3 _dispatch_async_redirect_invoke + 703
	15  libdispatch.dylib                   0x00007fff5cc843bc _dispatch_root_queue_drain + 324
	16  libdispatch.dylib                   0x00007fff5cc84b46 _dispatch_worker_thread2 + 90
	17  libsystem_pthread.dylib             0x00007fff5ceb66b3 _pthread_wqthread + 583
	18  libsystem_pthread.dylib             0x00007fff5ceb63fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
2020-01-10 20:43:29.456 xcodebuild[628:7700]  iPhoneSupport: 📱<DVTiOSDevice (0x7fa7cd60bda0), iPhone, iPhone, 13.3 (17C54), ce4ada5943169eabdead45103bfd40c686a97e62> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit Code=-402653034 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=The user has not yet responded to the pairing request., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000110f626e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x0000000110f62de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000110fa0780 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
	3   DTDeviceKitBase                     0x0000000110fa129d __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 699
	4   libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	5   libdispatch.dylib                   0x00007fff5cc82478 _dispatch_sync_invoke_and_complete_recurse + 65
	6   libdispatch.dylib                   0x00007fff5cc81fe6 _dispatch_sync_f_slow + 195
	7   DTDeviceKitBase                     0x0000000110fa0f80 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
	8   IDEiOSSupportCore                   0x0000000110b5c107 __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
	9   DVTFoundation                       0x00000001012fbe8a __DVT_CALLING_CLIENT_BLOCK__ + 7
	10  DVTFoundation                       0x00000001012fd562 __DVTDispatchAsync_block_invoke + 809
	11  libdispatch.dylib                   0x00007fff5cc755f8 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x00007fff5cc7663d _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00007fff5cc78de6 _dispatch_continuation_pop + 414
	14  libdispatch.dylib                   0x00007fff5cc784a3 _dispatch_async_redirect_invoke + 703
	15  libdispatch.dylib                   0x00007fff5cc843bc _dispatch_root_queue_drain + 324
	16  libdispatch.dylib                   0x00007fff5cc84b46 _dispatch_worker_thread2 + 90
	17  libsystem_pthread.dylib             0x00007fff5ceb66b3 _pthread_wqthread + 583
	18  libsystem_pthread.dylib             0x00007fff5ceb63fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error})
In file included from /Users/curt/github/vue-nativescript-notices/platforms/ios/internal/main.m:5:
In file included from /Users/curt/github/vue-nativescript-notices/platforms/ios/internal/TNSExceptionHandler.h:13:
In file included from /Users/curt/github/vue-nativescript-notices/platforms/ios/internal/NativeScript.framework/Headers/NativeScript.h:12:

**Comment by curtiscarlson** [comment]
OK.  Immediately after posting I realized that it is trying to build to my watch instead of my phone.  I don't know why or how.  It has never done this before.  I accepted the request on the watch, and it got further but a different error code:  

Saving metadata generation's stderr stream to: /Users/curt/github/vue-nativescript-notices/platforms/ios/build/Debug-iphoneos/metadata-generation-stderr-arm64.txt
~/github/vue-nativescript-notices/platforms/ios
ld: framework not found TNSCrashlyticsLogger
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "./build-step-metadata-generator.py", line 128, in <module>
    generate_metadata(arch)
  File "./build-step-metadata-generator.py", line 109, in generate_metadata
    error_stream_content = child_process.communicate()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 794, in communicate
    stderr = _eintr_retry_call(self.stderr.read)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Command Ld failed with a nonzero exit code
note: Using new build system
note: Planning build
note: Constructing build description
** ARCHIVE FAILED **

Unable to apply changes on device: ce4ada5943169eabdead45103bfd40c686a97e62. Error is: Command xcodebuild failed with exit code 65.

no idea how to debug that one!!  I am thinking I need to make tns run ios try to install to the phone not the watch but I'm at a loss of how to proceed.

**Comment by NathanaelA** [comment]
A couple things I would try:
1. `tns devices` to see what devices NativeScript sees; if all it sees is the watch, then you might need to make sure xcode can see your phone.

2. I would also do a `tns clean ios` to cleanup the build before you try to build again.

3. Your info above is incorrect; you need to do `tns info` to get the versions of things.   To help we really need to know the different NativeScript versions; i.e. the CLI, runtimes and core modules.  :)

**Comment by SylannBin** [comment]
I often have problems detecting devices. Sometimes, just unplugging/plugging the device would solve the problem, but sometimes I would have to rely on "rituals" and see the problem fixed randomly.
I know it doesn't help. It's just to say that undetected devices can be a source of many headaches if we don't pay attention.
