### ISSUE TITLE
Nativescript 1.3.0 installation issue in linux (Debian)

### ISSUE THREAD

**Issue by paragasu** [NativeScript/NativeScript#824]
I been following the instruction http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-linux.html
It failed on both my laptop and desktop computer.

Here is the output of npm install -g nativescript --unsafe-perm

```
make: Entering directory '/usr/local/lib/node_modules/nativescript/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
In file included from ../src/callback_info.cc:8:0:
../src/callback_info.cc: In static member function ‘static v8::Handle<v8::Value> CallbackInfo::Callback(const v8::Arguments&)’:
../src/ffi.h:25:72: warning: ‘v8::Local<v8::Value> NanThrowError(const char*, int)’ is deprecated [-Wdeprecated-declarations]
 #define THROW_ERROR_EXCEPTION_WITH_STATUS_CODE(x, y) NanThrowError(x, y)
                                                                        ^
../src/callback_info.cc:139:12: note: in expansion of macro ‘THROW_ERROR_EXCEPTION_WITH_STATUS_CODE’
     return THROW_ERROR_EXCEPTION_WITH_STATUS_CODE("ffi_prep_closure() Returned Error", status);
            ^
In file included from ../src/ffi.h:18:0,
                 from ../src/callback_info.cc:8:
../node_modules/nan/nan.h:1290:50: note: declared here
   NAN_DEPRECATED NAN_INLINE v8::Local<v8::Value> NanThrowError(
                                                  ^
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory '/usr/local/lib/node_modules/nativescript/node_modules/ffi/build'
Installed in `/usr/local/lib/node_modules/nativescript/node_modules/ffi/bin/linux-x64-v8-3.14/ffi_bindings.node`
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> ref@1.1.0 install /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref
> node ./build.js

make: Entering directory '/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:8:0:
../node_modules/nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
binding.target.mk:88: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
Build failed
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
 
> nativescript@1.3.0 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

Trying to kill adb server. Some running Android related operations may fail.
npm ERR! ref@1.1.0 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.1.0 install script.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nativescript" "--unsafe-perm"
npm ERR! cwd /etc/profile.d
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css

> ffi@1.3.2 install /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ffi
> node ./build.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ffi/build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /etc/profile.d/npm-debug.log
npm ERR! not ok code 0
```
```
root@debian:/usr/bin# npm owner ls ref
tootallnate <nathan@tootallnate.net>
```

Installed package
gradle 2.5
node v0.10.38
java version "1.8.0_60"

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#963
