### ISSUE TITLE
undefined is not an object (evaluating 'this._owner.get')

### ISSUE THREAD

**Issue by ivandejesus** [NativeScript/NativeScript#8244]
Hi,
Having issue when running to XCode, terminating the app. Every time I click back button of application and navigate to different route.

Here's the code:
```
if (this.routerExtensions.canGoBack()) {
this.routerExtensions.back();
} else {
this.routerExtensions.navigate(['/nav/default'], { clearHistory: true });
}
```

```
CONSOLE LOG file:///app/bundle.js:1226:24: WS Open
2020-01-13 22:06:32.959931+0800 amspwanative[11614:632042] ***** Fatal JavaScript exception - application has been terminated. *****
2020-01-13 22:06:32.960157+0800 amspwanative[11614:632042] Native stack trace:
2020-01-13 22:06:32.961158+0800 amspwanative[11614:632042] 1 0x100d29d50 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
1 0x100d29d50 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2020-01-13 22:06:32.961418+0800 amspwanative[11614:632042] 2 0x100d61e8c NativeScript::FFICallbackNativeScript::ObjCMethodCallback::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2 0x100d61e8c NativeScript::FFICallbackNativeScript::ObjCMethodCallback::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2020-01-13 22:06:32.961729+0800 amspwanative[11614:632042] 3 0x1018ce9b8 ffi_closure_SYSV_inner
3 0x1018ce9b8 ffi_closure_SYSV_inner
2020-01-13 22:06:32.961954+0800 amspwanative[11614:632042] 4 0x1018d01b4 .Ldo_closure
4 0x1018d01b4 .Ldo_closure
2020-01-13 22:06:32.962350+0800 amspwanative[11614:632042] 5 0x1c5e47cd4
5 0x1c5e47cd4
2020-01-13 22:06:32.963111+0800 amspwanative[11614:632042] 6 0x1c5e487b0
6 0x1c5e487b0
2020-01-13 22:06:32.964307+0800 amspwanative[11614:632042] 7 0x1c5e4a178
7 0x1c5e4a178
2020-01-13 22:06:32.965123+0800 amspwanative[11614:632042] 8 0x1c5e48f04
8 0x1c5e48f04
2020-01-13 22:06:32.966106+0800 amspwanative[11614:632042] 9 0x1c6466324
9 0x1c6466324
2020-01-13 22:06:32.967472+0800 amspwanative[11614:632042] 10 0x1c6455d68
10 0x1c6455d68
2020-01-13 22:06:32.968285+0800 amspwanative[11614:632042] 11 0x1c6485bb0
11 0x1c6485bb0
2020-01-13 22:06:32.968847+0800 amspwanative[11614:632042] 12 0x1c2372e68
12 0x1c2372e68
2020-01-13 22:06:32.969211+0800 amspwanative[11614:632042] 13 0x1c236dd54
13 0x1c236dd54
2020-01-13 22:06:32.969609+0800 amspwanative[11614:632042] 14 0x1c236e320
14 0x1c236e320
2020-01-13 22:06:32.970010+0800 amspwanative[11614:632042] 15 0x1c236dadc CFRunLoopRunSpecific
15 0x1c236dadc CFRunLoopRunSpecific
2020-01-13 22:06:32.970459+0800 amspwanative[11614:632042] 16 0x1cc7d7328 GSEventRunModal
16 0x1cc7d7328 GSEventRunModal
2020-01-13 22:06:32.971241+0800 amspwanative[11614:632042] 17 0x1c645cbd0 UIApplicationMain
17 0x1c645cbd0 UIApplicationMain
2020-01-13 22:06:32.971660+0800 amspwanative[11614:632042] 18 0x1018d0044 ffi_call_SYSV
18 0x1018d0044 ffi_call_SYSV
2020-01-13 22:06:32.972259+0800 amspwanative[11614:632042] 19 0x1018ce0dc ffi_call_int
19 0x1018ce0dc ffi_call_int
2020-01-13 22:06:32.972976+0800 amspwanative[11614:632042] 20 0x1018cdbd8 ffi_call
20 0x1018cdbd8 ffi_call
2020-01-13 22:06:32.973362+0800 amspwanative[11614:632042] 21 0x100cecfe4 NativeScript::FunctionWrapper::call(JSC::ExecState*)
21 0x100cecfe4 NativeScript::FunctionWrapper::call(JSC::ExecState*)
2020-01-13 22:06:32.973643+0800 amspwanative[11614:632042] 22 0x10189aeb0 llint_entry
22 0x10189aeb0 llint_entry
2020-01-13 22:06:32.974041+0800 amspwanative[11614:632042] 23 0x1018982c8 llint_entry
23 0x1018982c8 llint_entry
2020-01-13 22:06:32.974567+0800 amspwanative[11614:632042] 24 0x1018982c8 llint_entry
24 0x1018982c8 llint_entry
2020-01-13 22:06:32.974977+0800 amspwanative[11614:632042] 25 0x1018982c8 llint_entry
25 0x1018982c8 llint_entry
2020-01-13 22:06:32.975395+0800 amspwanative[11614:632042] 26 0x1018982c8 llint_entry
26 0x1018982c8 llint_entry
2020-01-13 22:06:32.975857+0800 amspwanative[11614:632042] 27 0x1018982c8 llint_entry
27 0x1018982c8 llint_entry
2020-01-13 22:06:32.976175+0800 amspwanative[11614:632042] 28 0x1018982c8 llint_entry
28 0x1018982c8 llint_entry
2020-01-13 22:06:32.976779+0800 amspwanative[11614:632042] 29 0x1018982c8 llint_entry
29 0x1018982c8 llint_entry
2020-01-13 22:06:32.977056+0800 amspwanative[11614:632042] 30 0x101898220 llint_entry
30 0x101898220 llint_entry
2020-01-13 22:06:32.977491+0800 amspwanative[11614:632042] 31 0x1018982c8 llint_entry
31 0x1018982c8 llint_entry
2020-01-13 22:06:32.977679+0800 amspwanative[11614:632042] JavaScript stack trace:
2020-01-13 22:06:32.978182+0800 amspwanative[11614:632042] file:///app/vendor.js:127661:32
at UIApplicationMain([native code])
at run(file:///app/vendor.js:147829:26)
at file:///app/vendor.js:145127:26
at file:///app/vendor.js:145028:38
at file:///app/vendor.js:145008:26
at file:///app/bundle.js:10771:66
at webpack_require(file:///app/runtime.js:75:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2020-01-13 22:06:32.978279+0800 amspwanative[11614:632042] JavaScript error:
2020-01-13 22:06:32.978458+0800 amspwanative[11614:632042] file:///app/vendor.js:127661:32: JS ERROR TypeError: undefined is not an object (evaluating 'this._owner.get')

file:///app/vendor.js:127661:32: JS ERROR TypeError: undefined is not an object (evaluating 'this._owner.get')
2020-01-13 22:06:32.980606+0800 amspwanative[11614:632042] *** JavaScript call stack:
(
0 UIApplicationMain@[native code]
1 run@file:///app/vendor.js:147829:26
2 @file:///app/vendor.js:145127:26
3 @file:///app/vendor.js:145028:38
4 @file:///app/vendor.js:145008:26
5 @file:///app/bundle.js:10771:66
6 webpack_require@file:///app/runtime.js:75:34
7 checkDeferredModules@file:///app/runtime.js:44:42
8 webpackJsonpCallback@file:///app/runtime.js:31:39
9 anonymous@file:///app/bundle.js:2:61
10 evaluate@[native code]
11 moduleEvaluation@:1:11
12 @:2:1
13 asyncFunctionResume@:1:11
14 @:24:9
15 promiseReactionJob@:1:11
)
2020-01-13 22:06:32.980771+0800 amspwanative[11614:632042] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'this._owner.get')
at
file:///app/vendor.js:127661:32
at UIApplicationMain([native code])
at run(file:///app/vendor.js:147829:26)
at file:///app/vendor.js:145127:26
at file:///app/vendor.js:145028:38
at file:///app/vendor.js:145008:26
at file:///app/bundle.js:10771:66
at webpack_require(file:///app/runtime.js:75:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x1c23f5a48 0x1c211dfa4 0x100d2a21c 0x100d61e8c 0x1018ce9b8 0x1018d01b4 0x1c5e47cd4 0x1c5e487b0 0x1c5e4a178 0x1c5e48f04 0x1c6466324 0x1c6455d68 0x1c6485bb0 0x1c2372e68 0x1c236dd54 0x1c236e320 0x1c236dadc 0x1cc7d7328 0x1c645cbd0 0x1018d0044 0x1018ce0dc 0x1018cdbd8 0x100cecfe4 0x10189aeb0 0x1018982c8 0x1018982c8 0x1018982c8 0x1018982c8 0x1018982c8 0x1018982c8 0x1018982c8 0x101898220 0x1018982c8 0x101879988 0x100e25c6c 0x1016cae98 0x100d05550 0x1015987e0 0x10189ab6c 0x1018982c8 0x1018982c8 0x1018982c8 0x101898220 0x1018982c8 0x101879988 0x100e25c6c 0x1016cb050 0x101591b08 0x100cfae90 0x100d712d8 0x1002555c8 0x1c21f8360)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@ivandejesus the provided info is not enough to make any conclusions. Consider providing a sample application. You could also see what is causing the issue in `file:///app/vendor.js:127661:32:`

**Comment by ivandejesus** [comment]
Hi @NickIliev,
Already check and found out that the issue is related to the code using clearHistory: true when navigating to different routes using this.routerExtensions.navigate. Do you have fix for this? Thanks

**Comment by NickIliev** [comment]
@ivandejesus we have tests for `clearHistory` and it is working on my side - again it would be great if you share a test project that reproduces the issue.

**Comment by two-bridges** [comment]
I experienced this same error message today and found a solution (that worked in my case at least)

The error message I received:
`file:///node_modules/@nativescript/core/ui/frame/frame.js:337:0: JS ERROR TypeError: undefined is not an object (evaluating 'this._owner.get')`

Steps to reproduce;
* Start the nativescript in debug mode (in my case it was nativescript-angular, ios simulator, NS6.4)
* save any simple code change
* the error would occur and the debugger ceased to function from then on.  bummer.  

I tracked the cause down to having nested `page-router-outlet` directives.   

Solution: I replaced the inner `page-router-outlet` with a `router-outlet` and the error has completely gone away.  

I tested this several times to confirm that it was only the nested `page-router-outlet` and it was definitely the cause in my case.

**Comment by prajilshresthaiw** [comment]
Any more info?

**Comment by diegovincent** [comment]
@NickIliev do your test pass with nested `page-router-outlet`?

**Comment by rseigel** [comment]
I can confirm that @two-bridges 's solution worked for me. Changing page-router-outlet to router-outlet in a nested navigation situation fixed this exact error.
