### ISSUE TITLE
Android - Release version crashes on start

### ISSUE THREAD

**Issue by draggie** [NativeScript/NativeScript#8261]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - Cross-platform modules: 6.3.2
 - Android Runtime: 6.3.1
 - iOS Runtime: 6.3.0
 - Plugin(s):
```
    "@auth0/angular-jwt": "3.0.1",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "@nstudio/nativescript-loading-indicator": "^2.0.4",
    "byline": "5.0.0",
    "hammerjs": "^2.0.8",
    "libphonenumber-js": "1.7.14",
    "lodash": "^4.17.15",
    "nativescript-angular": "^8.20.4",
    "nativescript-background-fetch": "^1.2.1",
    "nativescript-background-http": "^4.2.1",
    "nativescript-bugsnag": "^1.0.14",
    "nativescript-camera": "^4.5.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-email": "^1.5.5",
    "nativescript-feedback": "^1.3.12",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-local-notifications": "^4.1.5",
    "nativescript-phone": "^1.4.1",
    "nativescript-photo-editor": "^1.1.0",
    "nativescript-photoviewer": "^2.1.5",
    "nativescript-ripple": "^2.2.1",
    "nativescript-social-share": "^1.6.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-autocomplete": "^6.0.0",
    "nativescript-ui-dataform": "^6.0.0",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-ui-sidedrawer": "^8.0.0",
    "nativescript-worker-loader": "0.9.5",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.5.2",
    "timers": "0.1.1",
    "tns-core-modules": "^6.3.2",
    "ts-loader": "6.0.4",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "zone.js": "^0.9.1"
```

**Describe the bug**
Application works perfectly fine in the debug mode. No significant erros messages are present.
Application built in release mode for Android using the NativeScript's Sidekick (however this happens also with CLI command build) is exiting on startup with this message in logcat:

```
01-20 12:45:57.691 23669-23669/alltm.mobile I/TNS.Runtime: NativeScript Runtime Version 0.0.0.0, commit RUNTIME_COMMIT_SHA_PLACEHOLDER
01-20 12:45:58.181 23669-23669/alltm.mobile D/TNS.Runtime: V8 version 7.8.279.19
01-20 12:49:32.561 23669-23669/alltm.mobile D/AndroidRuntime: Shutting down VM
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err: An uncaught Exception occurred on "main" thread.
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err: Unable to instantiate activity ComponentInfo{alltm.mobile/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptActivity'
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err: StackTrace:
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{alltm.mobile/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptActivity'
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.os.Looper.loop(Looper.java:158)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7230)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err: Caused by: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptActivity'
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at com.tns.Runtime.createJSInstanceNative(Native Method)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at com.tns.Runtime.createJSInstance(Runtime.java:820)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at com.tns.Runtime.initInstance(Runtime.java:793)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at com.tns.NativeScriptActivity.<init>(NativeScriptActivity.java:13)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at java.lang.Class.newInstance(Native Method)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.Instrumentation.newActivity(Instrumentation.java:1096)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3085)
01-20 12:49:32.561 23669-23669/alltm.mobile W/System.err: 	... 9 more
01-20 12:49:32.921 23669-23669/alltm.mobile I/Process: Sending signal. PID: 23669 SIG: 9
```

Tried even debugging Java code in Android Studio but I have not found anything more clear than this error message.

**To Reproduce**
Build application with this plugins in release mode I guess.
What is more application works perfectly fine for iOS in both modes - release and debug.
Found earlier some solution that adding version to `package.json` should help, also that changing version in `AndroidManifest.xml` should help but this is not changing anything.

**Expected behavior**
Release for Android version should work properly or throw more descriptive error.

**Sample project**
I can share my project with someone from the NS team if needed

**Comment by NickIliev** [comment]
@draggie yes providing the project would help us a lot more to identify the issue. ou could find me in the NativeScript community slack (username: **niliev**)

You could also try to eliminate any additional flags that you might be passing during the release build (snapshot, aot, etc.) and see if the issue is still present.

**Comment by NickIliev** [comment]
It looks like the case is related to a **snaspshot** build
