### ISSUE TITLE
App crashed after updating tns update.

### ISSUE THREAD

**Issue by Rajdeo-Das** [NativeScript/NativeScript#8295]
Restarting application on device 3BA2C43B-493B-402E-8718-66E37ED4183B...
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x11137fbce NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1113ce824 -[TNSRuntime executeModule:referredBy:]
3   0x10f3ef8a3 main
4   0x7fff5227ec25 start
JavaScript stack trace:
../node_modules/pbkdf2/lib/default-encoding.js(file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/pbkdf2/lib/sync.js(file:///node_modules/pbkdf2/lib/sync.js:14:30)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/pbkdf2/index.js(file:///node_modules/pbkdf2/index.js:24:31)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/crypto-browserify/index.js(file:///node_modules/crypto-browserify/index.js:14:16)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/typeorm/browser/util/StringUtils.js(file:///node_modules/typeorm/browser/util/StringUtils.js:1:0)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/typeorm/browser/naming-strategy/DefaultNamingStrategy.js(file:///node_modules/typeorm/browser/naming-strategy/DefaultNamingStrategy.js:1:0)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:<…>
JavaScript error:
file:///node_modules/pbkdf2/lib/default-encoding.js:3:11: JS ERROR TypeError: undefined is not an object (evaluating 'global.process.browser')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'global.process.browser')
at
../node_modules/pbkdf2/lib/default-encoding.js(file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/pbkdf2/lib/sync.js(file:///node_modules/pbkdf2/lib/sync.js:14:30)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/pbkdf2/index.js(file:///node_modules/pbkdf2/index.js:24:31)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/crypto-browserify/index.js(file:///node_modules/crypto-browserify/index.js:14:16)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../node_modules/typeorm/browser/util/StringUtils.js(file:///node_modules/typeorm/browser/util/StringUtils.js:1:0)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at fn(file:///src/webpack/bootstrap:120:0)
at ../<…>
NativeScript caught signal 6.
Native Stack:
1   0x1113cd481 sig_handler(int)
2   0x7fff5245b42d _sigtramp
3   0x1
4   0x7fff5234ba5c abort
5   0x7fff502497f8 __cxa_bad_cast
6   0x7fff502499c7 demangling_unexpected_handler()
7   0x7fff513fbd7c _objc_terminate()
8   0x7fff50256e97 std::__terminate(void (*)())
9   0x7fff502568fe __cxa_get_exception_ptr
10  0x7fff502568c5 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff513fbc44 _objc_exception_destructor(void*)
12  0x1113800fd NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x1113ce824 -[TNSRuntime executeModule:referredBy:]
14  0x10f3ef8a3 main
15  0x7fff5227ec25 start
JS Stack:

If I remove
"process": "global.process", from the webpack.config.js
from bellow 
 new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
                "process": "global.process",
            }),

Things works but Translation service stops working  @ngx-translate/core.

I am using typeorm  nativescript plugin.

**Comment by NickIliev** [comment]
@Rajdeo-Das can you post the content of the package.json before & after the update command?
