### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'global.process.browser')

### ISSUE THREAD

**Issue by gultyaev** [NativeScript/NativeScript#8322]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.3.3 version and is up to date.
✔ Component tns-core-modules has 6.3.2 version and is up to date.
✖ Component tns-android is not installed.
✔ Component tns-ios has 6.3.0 version and is up to date.
```

**Describe the bug**

When trying to `npm run preview` I'm getting an error

```
LOG from device Sergey’s iPhone: 2020-02-06 16:25:30.406 nsplaydev[42224:17024161] ***** Fatal JavaScript exception - application has been terminated. *****
2020-02-06 16:25:30.406 nsplaydev[42224:17024161] Native stack trace:
1   0x102e71d50 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x102eb93b0 -[TNSRuntime executeModule:referredBy:]
3   0x103fda25c -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4   0x102507524
5   0x1a3eace18 <redacted>
2020-02-06 16:25:30.407 nsplaydev[42224:17024161] JavaScript stack trace:
2020-02-06 16:25:30.407 nsplaydev[42224:17024161] ../node_modules/pbkdf2/lib/default-encoding.js(file:///app/vendor.js:92842:19)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/pbkdf2/lib/sync.js(file:///app/vendor.js:92906:42)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/pbkdf2/index.js(file:///app/vendor.js:92717:43)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/crypto-browserify/index.js(file:///app/vendor.js:71469:28)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/uuid/lib/rng.js(file:///app/vendor.js:97343:33)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/uuid/v1.js(file:///app/vendor.js:97355:30)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/uuid/index.js(file:///app/vendor.js:97292:29)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ./app/login/login.service.ts(file:///app/bundle.js:1243:81)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ./app/login/login.component.ts(file:///app/bundle.js:1176:105)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ./app/app.module.tns.ts(file:///app/bundle.js:129:107)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at file:///app/bundle.js:2636:96
at ./main.tns.ts(file:///app/bundle.js:2694:34)
at __webpack_require__(file:///app/runtime.js:754:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2020-02-06 16:25:30.407 nsplaydev[42224:17024161] JavaScript error:
file:///app/vendor.js:92842:19: JS ERROR TypeError: undefined is not an object (evaluating 'global.process.browser')
2020-02-06 16:25:30.408 nsplaydev[42224:17024161] PlayLiveSync: Uncaught Exception
2020-02-06 16:25:30.408 nsplaydev[42224:17024161] *** JavaScript call stack:
(

)
2020-02-06 16:25:30.408 nsplaydev[42224:17024161] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'global.process.browser')
 at 
../node_modules/pbkdf2/lib/default-encoding.js(file:///app/vendor.js:92842:19)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/pbkdf2/lib/sync.js(file:///app/vendor.js:92906:42)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/pbkdf2/index.js(file:///app/vendor.js:92717:43)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/crypto-browserify/index.js(file:///app/vendor.js:71469:28)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/uuid/lib/rng.js(file:///app/vendor.js:97343:33)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/uuid/v1.js(file:///app/vendor.js:97355:30)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ../node_modules/uuid/index.js(file:///app/vendor.js:97292:29)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ./app/login/login.service.ts(file:///app/bundle.js:1243:81)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ./app/login/login.component.ts(file:///app/bundle.js:1176:105)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at ./app/app.module.tns.ts(file:///app/bundle.js:129:107)
at __webpack_require__(file:///app/runtime.js:754:34)
at fn(file:///app/runtime.js:121:39)
at file:///app/bundle.js:2636:96
at ./main.tns.ts(file:///app/bundle.js:2694:34)
at __webpack_require__(file:///app/runtime.js:754:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x1a40b896c 0x1a3dd1028 0x102e7221c 0x102eb93b0 0x103fda25c 0x102507524 0x1a3eace18)
libc++abi.dylib: terminating with uncaught exception of type NSException
2020-02-06 16:25:30.408 nsplaydev[42224:17024161] PlayLiveSync: Uncaught Exception
```

Form which I followed to vendor.js line 92842

![image](https://user-images.githubusercontent.com/22374911/73946023-e985b080-48fd-11ea-82a7-11eb630f65a5.png)

**To Reproduce**

Run `npm run preview` in project

**Expected behavior**
Project should run

**Sample project**

**Additional context**

**Comment by gultyaev** [comment]
commenting `import uuid from 'uuid'` somehow helped to encounter next error
