### ISSUE TITLE
FormattedString Span Animation Crash

### ISSUE THREAD

**Issue by alexgritton** [NativeScript/NativeScript#8359]
**Environment**
nativescript. Your current version is 6.2.2
tns-core-modules. Your current version is 6.3.2
tns-android. Your current version is 6.2.0
tns-ios. Your current version is 6.3.0

**Describe the bug**
Adding an animated class to a span inside of a FormattedString causes the application to crash ios.  On Android it doesn't crash and shows the icon but also doesn't animate it.

> ***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x100a6a2bc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x100aa0578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x101558ea4 ffi_closure_SYSV_inner
4   0x10155c1b4 .Ldo_closure
5   0x19ac8eab4 __NSFireTimer
6   0x19a81477c <redacted>
7   0x19a8144b4 <redacted>
8   0x19a813b28 <redacted>
9   0x19a80e9d0 <redacted>
10  0x19a80df40 CFRunLoopRunSpecific
11  0x1a4a9e534 GSEventRunModal
12  0x19e999580 UIApplicationMain
13  0x10155c044 ffi_call_SYSV
14  0x1015585c8 ffi_call_int
15  0x1015580c4 ffi_call
16  0x100a2ceb0 NativeScript::FunctionWrapper::call(JSC::ExecState*)
17  0x1015572c8 llint_entry
18  0x101555644 llint_entry
19  0x101555644 llint_entry
20  0x101555644 llint_entry
21  0x101555644 llint_entry
22  0x101555644 llint_entry
23  0x101555644 llint_entry
24  0x101555644 llint_entry
25  0x101555644 llint_entry
26  0x1015555a4 llint_entry
27  0x101555644 llint_entry
28  0x1015410ec vmEntryToJavaScript
29  0x1011dc14c JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
30  0x1013aa7a8 JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&)
31  0x100a454c0 NativeScript::GlobalObject::moduleLoaderEvaluate(JSC::JSGlobalObject*, JSC::ExecState*, JSC::JSModuleLoader*, JSC::JSValue, JSC::JSValue, JSC::JSValue)
JavaScript stack trace:
_getNativeAnimationArguments(file:///node_modules/@nativescript/core/ui/animation/animation.js:285:0)
at file:///node_modules/@nativescript/core/ui/animation/animation.js:204:0
at play(file:///node_modules/@nativescript/core/ui/animation/animation.js:173:0)
at animate(file:///node_modules/@nativescript/core/ui/animation/keyframe-animation.js:208:0)
at file:///node_modules/@nativescript/core/ui/animation/keyframe-animation.js:180:36
at runTask(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:188:0)
at invokeTask(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:496:0)
at timer(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:1561:0)
at invoke(file:///node_modules/@nativescript/core/timer/timer.js:54:30)
at runGuarded(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:151:0)
at tick(file:///node_modules/@nativescript/core/timer/timer.js:18:0)
at UIApplicationMain([native code])
at run(file:///node_modules/@nativescript/core/application/application.js:312:0)
at bootstrapNativeScriptApp(file:///node_modules/@nativescript/angular/platform-common.js:210:0)
at bootstrapApp(file:///node_modules/@nativescript/angular/platform-common.js:111:0)
at bootstrapModule(file:///node_modules/@nativescript/angular/platform-common.js:91:0)
at file:///app/bundle.js:5163:175
at ./main.tns.ts(file:///app/bundle.js:5168:34)
at __webpack_require__(file:///src/webpack/bootstrap:753:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native<\M-b\M^@\M-&>
JavaScript error:
file:///node_modules/@nativescript/core/ui/animation/animation.js:285:0: JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   run@file:///node_modules/@nativescript/core/application/application.js:312:0
2   bootstrapNativeScriptApp@file:///node_modules/@nativescript/angular/platform-common.js:210:0
3   bootstrapApp@file:///node_modules/@nativescript/angular/platform-common.js:111:0
4   bootstrapModule@file:///node_modules/@nativescript/angular/platform-common.js:91:0
5   @file:///app/bundle.js:5163:175
6   ./main.tns.ts@file:///app/bundle.js:5168:34
7   __webpack_require__@file:///src/webpack/bootstrap:753:0
8   checkDeferredModules@file:///src/webpack/bootstrap:43:0
9   webpackJsonpCallback@file:///src/webpack/bootstrap:30:0
10  anonymous@file:///app/bundle.js:2:61
11  evaluate@[native code]
12  moduleEvaluation@:1:11
13  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'nativeView.layer')
at
_getNativeAnimationArguments(file:///node_modules/@nativescript/core/ui/animation/animation.js:285:0)
at file:///node_modules/@nativescript/core/ui/animation/animation.js:204:0
at play(file:///node_modules/@nativescript/core/ui/animation/animation.js:173:0)
at animate(file:///node_modules/@nativescript/core/ui/animation/keyframe-animation.js:208:0)
at file:///node_modules/@nativescript/core/ui/animation/keyframe-animation.js:180:36
at runTask(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:188:0)
at invokeTask(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:496:0)
at timer(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:1561:0)
at invoke(file:///node_modules/@nativescript/core/timer/timer.js:54:30)
at runGuarded(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:151:0)
at tick(file:///node_modules/@nativescript/core/timer/timer.js:18:0)
at UIApplicationMain([native code])
at run(file:///node_modules/@nativescript/core/application/application.js:312:0)
at bootstrapNativeScriptApp(file:///node_modules/@nativescript/angular/platform-common.js:210:0)
at bootstrapApp(file:///node_modules/@nativescript/angular/platform-common.js:111:0)
at bootstrapModule(file:///node_modules/@nativescript/angular/platform-common.js:91:0)
at file:///app/bundle.js:5163:175
at ./main.tns.ts(file:///app/bundle.js:5168:34)
at __webpack_require__(file:///src/webpack/bootstrap:753:0)
at che<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x100aad4e4 sig_handler(int)
2   0x19a59f424 <redacted>
3   0x19a5a28b8 pthread_kill
4   0x19a532a74 abort
5   0x19a64a3c8 __cxa_bad_cast
6   0x19a64a5c0 <redacted>
7   0x19a5b1308 <redacted>
8   0x19a657634 <redacted>
9   0x19a656f58 __cxa_get_exception_ptr
10  0x19a656f10 <redacted>
11  0x19a5b1158 <redacted>
12  0x100a6a738 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x100aa0578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x101558ea4 ffi_closure_SYSV_inner
15  0x10155c1b4 .Ldo_closure
16  0x19ac8eab4 __NSFireTimer
17  0x19a81477c <redacted>
18  0x19a8144b4 <redacted>
19  0x19a813b28 <redacted>
20  0x19a80e9d0 <redacted>
21  0x19a80df40 CFRunLoopRunSpecific
22  0x1a4a9e534 GSEventRunModal
23  0x19e999580 UIApplicationMain
24  0x10155c044 ffi_call_SYSV
25  0x1015585c8 ffi_call_int
26  0x1015580c4 ffi_call
27  0x100a2ceb0 NativeScript::FunctionWrapper::call(JSC::ExecState*)
28  0x1015572c8 llint_entry
29  0x101555644 llint_entry
30  0x101555644 llint_entry
31  0x101555644 llint_entry
JS Stack:
UIApplicationMain([native code])
at run(file:///node_modules/@nativescript/core/application/application.js:312:0)
at bootstrapNativeScriptApp(file:///node_modules/@nativescript/angular/platform-common.js:210:0)
at bootstrapApp(file:///node_modules/@nativescript/angular/platform-common.js:111:0)
at bootstrapModule(file:///node_modules/@nativescript/angular/platform-common.js:91:0)
at file:///app/bundle.js:5163:175
at ./main.tns.ts(file:///app/bundle.js:5168:34)
at __webpack_require__(file:///src/webpack/bootstrap:753:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at promiseReactionJob

**To Reproduce**
Here is a link to a playground I've setup to display the crash. https://play.nativescript.org/?template=play-ng&id=KSPzTJ

**Expected behavior**
I would expect the span to animate.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=KSPzTJ

**Comment by NickIliev** [comment]
@alexgritton this is a limitation of the `Span`. The thing is that the `Span` is not extending `View`  but `ViewBase` (meaning that it is not UIVIew or similar UI class that can be animated). So when using spans those are not exactly UI elements. That said you can't animate them.

**Comment by tillsanders** [comment]
I just had the same problem and created a PR to document this: https://github.com/NativeScript/docs/pull/1876
