### ISSUE TITLE
View not added to this instance error after the first HMR

### ISSUE THREAD

**Issue by ArkasDev** [NativeScript/NativeScript#8367]
**Environment**
 - CLI: 6.4.0
 - Android Runtime: 6.1.2 
```
{
  "version": "0.0.0",
  "nativescript": {
    "id": "app.project.de",
    "tns-android": {
      "version": "6.1.2"
    }
  },
  "scripts": {
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@ngrx/effects": "^8.5.2",
    "@ngrx/store": "^8.4.0",
    "@ngx-translate/core": "^12.1.1",
    "angular-auth-oidc-client": "^10.0.10",
    "base-64": "^0.1.0",
    "bootstrap": "^4.4.1",
    "core-js": "^2.5.4",
    "mathjs": "^6.2.3",
    "nativescript-angular": "~8.0.1",
    "nativescript-oauth2": "latest",
    "nativescript-ui-listview": "^8.0.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "utf8": "^3.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "^1.4.0",
    "node-sass": "^4.7.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

```

**Describe the bug**
When I run my android app for the first time, there are no errors at all. If I now make any changes so that the HMR is triggered, the android build starts. After a short time I get the following exception.
I have already checked if a tns.html file is empty, but it is not.

```
JS: HMR: Checking for updates to the bundle with hmr hash c136d0fac55b1816905d.
JS: HMR: The following modules were updated:
JS: HMR:          ↻ ../node_modules/mathjs/main/esm/index.js
JS: HMR:          ↻ ./app/shared/service/math/impl/math-js.impl.service.ts
JS: HMR:          ↻ ./app/container/di.container.ts
JS: HMR:          ↻ ./app/app.module.tns.ts
JS: HMR:          ↻ ./app/modules/dashboard/pages/dashboard/dashboard.page.html
JS: HMR:          ↻ ./app/modules/dashboard/pages/dashboard/dashboard.page.ts
JS: HMR:          ↻ ./app/modules/dashboard/dashboard.routes.ts
JS: HMR:          ↻ ./app/modules/dashboard/dashboard.module.tns.ts
JS: HMR:          ↻ ./app/core/module/routing/root.routes.tns.ts
JS: HMR:          ↻ ./app/core/module/routing/root-routing.module.tns.ts
JS: HMR:          ↻ ./app/core/core.module.tns.ts
JS: HMR: Successfully applied update with hmr hash c136d0fac55b1816905d. App is up to date.
Refreshing application on device 520003cffa22743d...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method run failed
System.err: Error: View not added to this instance. View: ProxyViewContainer(2) CurrentParent: GridLayout(3) ExpectedParent: AppHostView(1)
System.err:
System.err: StackTrace:
System.err:     ZoneAwareError(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:1298:0)
System.err:     at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._removeView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:452:0)
System.err:     at push.../node_modules/nativescript-angular/view-util.js.ViewUtil.removeFromVisualTree(file:///node_modules\nativescript-angular\view-util.js:191:0)
System.err:     at push.../node_modules/nativescript-angular/view-util.js.ViewUtil.removeChild(file:///node_modules\nativescript-angular\view-util.js:119:0)
System.err:     at push.../node_modules/nativescript-angular/renderer.js.NativeScriptRendererFactory.ngOnDestroy(file:///node_modules\nativescript-angular\renderer.js:58:0)
System.err:     at callNgModuleLifecycle(file:///node_modules\@angular\core\fesm5\core.js:18547:0)
System.err:     at push.../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.destroy(file:///node_modules\@angular\core\fesm5\core.js:19166:0)
System.err:     at push.../node_modules/nativescript-angular/platform-common.js.NativeScriptPlatformRef._livesync(file:///node_modules\nativescript-angular\platform-common.js:215:0)
System.err:     at (file:///node_modules\nativescript-angular\platform-common.js:97:74)
System.err:     at push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invokeTask(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:421:0)
System.err:     at push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.Zone.runTask(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:188:0)
System.err:     at push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneTask.invokeTask(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:496:0)
System.err:     at ZoneTask.invoke(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:485:0)
System.err:     at timer(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:1561:0)
System.err:     at invoke(file:///node_modules\tns-core-modules\timer\timer.js:19:30)
System.err:     at push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:388:0)
System.err:     at push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.Zone.runGuarded(file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:151:0)
System.err:     at (file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:129:0)
System.err:     at run(file:///node_modules\tns-core-modules\timer\timer.js:23:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7156)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Successfully synced application app.project.de on device 520003cffa22743d.
```

**Comment by mihernandez6** [comment]
Hi! Did you fix this? If so, how?
Thnx!

**Comment by mihernandez6** [comment]
Damn, I see :( thank you for your response. Have a great day :)
