### ISSUE TITLE
Bug on ios device - tns run ios  not working on IOS 13

### ISSUE THREAD

**Issue by vforv** [NativeScript/NativeScript#8371]
I am using xCode 11.3.0
After I run `tns run ios --bundle --provision...` never finish process and app not compile on phone

```
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `emenumobile.xcworkspace` for this project from now on.
Pod installation complete! There are 8 dependencies from the Podfile and 24 total pods installed.
Project successfully prepared (ios)
Configure firebase
Building project...
Xcode build...
Chokidar raised event change for /node_modules/@nativescript/core/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/@nstudio/nativescript-checkbox/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-angular/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-barcodescanner/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-appversion/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-vibrate/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-unit-test-runner/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-ui-sidedrawer/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-ui-listview/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/@nativescript/angular/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Chokidar raised event change for /node_modules/nativescript-ui-core/package.json.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
2020-02-23 15:52:46.930 xcodebuild[2117:38219]  DTDeviceKit: deviceType from 7eca246271dc3629811633838720fd8e91a1cb35 was NULL
2020-02-23 15:52:47.035 xcodebuild[2117:41167]  DTDeviceKit: deviceType from 7eca246271dc3629811633838720fd8e91a1cb35 was NULL
Chokidar raised event change for /node_modules/nativescript-plugin-firebase/platforms/ios/Podfile.
nativescript-plugin-firebase: building for same environment, not forcing prepare.
```

**Comment by NickIliev** [comment]
@vforv there is not enough information and also it seems the log is incomplete. Try providing more verbose log (you could also use `--log trace`). Also, make sure that your devices are recognized by the CLI (does it appear in `tns devices` output?)

**Comment by vforv** [comment]
@NickIliev I found this error on beginning of build:

```
Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal.
The stackTrace of the location trying to handle SIGINT is:
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:24:28)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:122:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:120:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:35:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:296:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
spawn: /usr/local/Cellar/node@10/10.16.0/bin/node "/usr/local/lib/node_modules/nativescript/lib/detached-processes/cleanup-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Shasum of file /package.json is a1fa451feeb46b392abb90c13885e1885e4a474a
```
