### ISSUE TITLE
I am unable to install on Ubuntu 14.04 with node 4.1.1 with all dependencies installed

### ISSUE THREAD

**Issue by ansarizafar** [NativeScript/NativeScript#838]
Here is the error

````
/root/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/binding.cc:8:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/binding.cc: In function ‘v8::Local<v8::Object> {anonymous}::WrapNullPointer()’:
../src/binding.cc:154:81: error: no matching function for call to ‘NanNewBufferHandle(char*&, size_t&, void (&)(char*, void*), void*&)’
   Local<Object> buf = NanNewBufferHandle(ptr, buf_size, unref_null_cb, user_data);
                                                                                 ^
../src/binding.cc:154:81: note: candidates are:
In file included from ../src/binding.cc:8:0:
../node_modules/nan/nan.h:658:36: note: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:658:36: note:   candidate expects 3 arguments, 4 provided
../node_modules/nan/nan.h:668:36: note: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:668:36: note:   candidate expects 2 arguments, 4 provided
../node_modules/nan/nan.h:675:36: note: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:675:36: note:   candidate expects 1 argument, 4 provided
../src/binding.cc: In function ‘void {anonymous}::ReadPointer(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:271:83: error: no matching function for call to ‘NanNewBufferHandle(char*&, size_t&, void (&)(char*, void*), void*&)’
   Local<Object> rtn_buf = NanNewBufferHandle(val, size, read_pointer_cb, user_data);
                                                                                   ^
../src/binding.cc:271:83: note: candidates are:
In file included from ../src/binding.cc:8:0:
../node_modules/nan/nan.h:658:36: note: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:658:36: note:   candidate expects 3 arguments, 4 provided
../node_modules/nan/nan.h:668:36: note: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:668:36: note:   candidate expects 2 arguments, 4 provided
../node_modules/nan/nan.h:675:36: note: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:675:36: note:   candidate expects 1 argument, 4 provided
../src/binding.cc: In function ‘void {anonymous}::ReinterpretBuffer(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:518:74: error: no matching function for call to ‘NanNewBufferHandle(char*&, size_t&, void (&)(char*, void*), NULL)’
   Local<Object> rtn = NanNewBufferHandle(ptr, size, read_pointer_cb, NULL);
                                                                          ^
../src/binding.cc:518:74: note: candidates are:
In file included from ../src/binding.cc:8:0:
../node_modules/nan/nan.h:658:36: note: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:658:36: note:   candidate expects 3 arguments, 4 provided
../node_modules/nan/nan.h:668:36: note: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:668:36: note:   candidate expects 2 arguments, 4 provided
../node_modules/nan/nan.h:675:36: note: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:675:36: note:   candidate expects 1 argument, 4 provided
../src/binding.cc: In function ‘void {anonymous}::ReinterpretBufferUntilZeros(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:565:74: error: no matching function for call to ‘NanNewBufferHandle(char*&, size_t&, void (&)(char*, void*), NULL)’
   Local<Object> rtn = NanNewBufferHandle(ptr, size, read_pointer_cb, NULL);
                                                                          ^
../src/binding.cc:565:74: note: candidates are:
In file included from ../src/binding.cc:8:0:
../node_modules/nan/nan.h:658:36: note: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:658:36: note:   candidate expects 3 arguments, 4 provided
../node_modules/nan/nan.h:668:36: note: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:668:36: note:   candidate expects 2 arguments, 4 provided
../node_modules/nan/nan.h:675:36: note: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:675:36: note:   candidate expects 1 argument, 4 provided
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ref/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "/home/zafar/softwares/node-v4.1.1-linux-x64/bin/node" "/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ref
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> ws@0.4.32 install /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws/build'
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> ref@1.1.0 install /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref/build'
Installed in `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ref/bin/linux-x64-v8-4.5/binding.node`
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> ffi@1.2.7 install /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ffi
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
../deps/libffi/src/closures.c:433:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.cc:3:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined [enabled by default]
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /root/.node-gyp/4.1.1/include/node/v8.h:19:0,
                 from /root/.node-gyp/4.1.1/include/node/node.h:42,
                 from ../src/ffi.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
In file included from ../src/ffi.h:18:0,
                 from ../src/ffi.cc:3:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../src/ffi.cc:2:0:
/root/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/root/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/ffi.h:18:0,
                 from ../src/ffi.cc:3:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/ffi.cc: In function ‘v8::Handle<v8::Value> WrapPointer(char*, size_t)’:
../src/ffi.cc:25:63: error: no matching function for call to ‘NanNewBufferHandle(char*&, size_t&, void (&)(char*, void*), void*&)’
     NanNewBufferHandle(ptr, length, wrap_pointer_cb, user_data)
                                                               ^
../node_modules/nan/nan.h:483:68: note: in definition of macro ‘NanEscapeScope’
 # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                                                                    ^
../src/ffi.cc:25:63: note: candidates are:
     NanNewBufferHandle(ptr, length, wrap_pointer_cb, user_data)
                                                               ^
../node_modules/nan/nan.h:483:68: note: in definition of macro ‘NanEscapeScope’
 # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                                                                    ^
../node_modules/nan/nan.h:754:36: note: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:754:36: note:   candidate expects 3 arguments, 4 provided
../node_modules/nan/nan.h:764:36: note: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:764:36: note:   candidate expects 2 arguments, 4 provided
../node_modules/nan/nan.h:771:36: note: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:771:36: note:   candidate expects 1 argument, 4 provided
../src/ffi.cc: In static member function ‘static void FFI::FinishAsyncFFICall(uv_work_t*)’:
../src/ffi.cc:387:29: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /root/.node-gyp/4.1.1/include/node/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     FatalException(try_catch);
                             ^
../src/ffi.cc: In function ‘v8::Handle<v8::Value> WrapPointer(char*, size_t)’:
../src/ffi.cc:27:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "/home/zafar/softwares/node-v4.1.1-linux-x64/bin/node" "/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ffi
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css

> ffi@1.3.2 install /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ffi
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
../deps/libffi/src/closures.c:433:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ffi/build'
Installed in `/home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/NodObjC/node_modules/ffi/bin/linux-x64-v8-4.5/ffi_bindings.node`
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/zafar/softwares/node-v4.1.1-linux-x64/bin/node" "/home/zafar/softwares/node-v4.1.1-linux-x64/bin/npm" "install" "nativescript" "-g" "--unsafe-perm"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! utf-8-validate@1.0.1 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@1.0.1 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

> nativescript@1.3.0 preuninstall /home/zafar/softwares/node-v4.1.1-linux-x64/lib/node_modules/nativescript
> node preuninstall.js

Trying to kill adb server. Some running Android related operations may fail.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zafar/npm-debug.log
````

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#980
