### ISSUE TITLE
grid-layout.ios.js:351:0: JS ERROR TypeError: undefined is not an object (evaluating 'this.rows[measureSpec.getRowIndex()].children')

### ISSUE THREAD

**Issue by jalberto-ghub** [NativeScript/NativeScript#8387]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
   nativescript has 6.4.1
 - Cross-platform modules: 
   tns-core-modules has 6.4.1
   "nativescript-angular": "^8.21.0"
 - Android Runtime: tns-android has 6.4.1
 - iOS Runtime: tns-ios has 6.4.2
 - Plugin(s):

**Describe the bug**

On iOS the application crashes when trying to render a `<GridLayout>`

```
JavaScript error:
file: node_modules/@nativescript/core/ui/layouts/grid-layout/grid-layout.ios.js:351:0: JS ERROR TypeError: undefined is not an object (evaluating 'this.rows[measureSpec.getRowIndex()].children')
NativeScript caught signal 11.
Native Stack:
1   0x1090e53e1 sig_handler(int)
2   0x10bd7642d _sigtramp
3   0x0
4   0x10bcb4b4d libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x10bcb8e4c _Unwind_RaiseException
6   0x10b8934aa __cxa_throw
7   0x10a2aabfa _objc_exception_destructor(void*)
8   0x109094d4f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
9   0x1090d5748 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
10  0x109ad63b2 ffi_closure_unix64_inner
11  0x109ad6dda ffi_closure_unix64
12  0x1078bad22 -[CALayer layoutSublayers]
13  0x1078bf9fc CA::Layer::layout_if_needed(CA::Transaction*)
14  0x1078cbd58 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
15  0x10783b24a CA::Context::commit_transaction(CA::Transaction*)
16  0x107872606 CA::Transaction::commit()
17  0x107872eb2 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
18  0x10b3bd2c7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
19  0x10b3b778e __CFRunLoopDoObservers
20  0x10b3b7e01 __CFRunLoopRun
21  0x10b3b74d2 CFRunLoopRunSpecific
22  0x10bfc52fe GSEventRunModal
23  0x1189f9fc2 UIApplicationMain
24  0x109ad6c1d ffi_call_unix64
25  0x1310f48e0
JS Stack:
UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:8080:144
at ./main.tns.ts(file:///app/bundle.js:8085:34)
at __webpack_require__(file: src/webpack/bootstrap:753:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)

```
This simple component template seems to fail:
```
<GridLayout columns="*, auto, *" rows="*, auto, *" backgroundImage="res://background">
   <Image src="res://logo" row="1" col="1"></Image>
   <ActivityIndicator [busy]="true" class="activity-indicator" row="1" col="1"></ActivityIndicator>
</GridLayout>

```
If I set `"discardUncaughtJsExceptions": true,` I get uncaught exception on almost every page:

```
Restarting application on device AB827170-F3B0-45AE-ADBD-B13355B3119D...
CONSOLE INFO file: node_modules/nativescript-dev-webpack/hot.js:3:0: HMR: Hot Module Replacement Enabled. Waiting for signal.
CONSOLE LOG file: src/app/app.module.tns.ts:59:20: firebase.init done
CONSOLE WARN file: src/app/core-services/config.service.ts:59:25: Application is using the testing app-id: com.cellectivity.whitelabel
CONSOLE LOG file: node_modules/@angular/core/fesm5/core.js:25638:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file: src/app/pages/loading-page/loading-page.component.tns.ts:19:16: Loading...
NativeScript debugger has opened inspector socket on port 18183 for com.cellectivity.b2gwhitelabel.
CONSOLE LOG file: src/app/core-services/config.service.ts:81:28: Configuration loaded
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: node_modules/@nativescript/core/inspector_modules.ios.js:1:0: Loading inspector modules...
CONSOLE LOG file: node_modules/@nativescript/core/inspector_modules.ios.js:6:0: Finished loading inspector modules.
NativeScript debugger attached.
CONSOLE LOG file: src/app/angular-material/b2g-carousel/b2g-carousel.component.ts:100:20: Starting carousel
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
Successfully synced application com.cellectivity.b2gwhitelabel on device AB827170-F3B0-45AE-ADBD-B13355B3119D.
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/pages/page-frame/page-frame.component.ts:20:20: ActiveSport: 'football'
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/angular-material/b2g-carousel/b2g-carousel.component.ts:112:20: Stopped carousel
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/pages/page-frame/page-frame.component.ts:20:20: ActiveSport: 'football'
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/angular-material/b2g-carousel/b2g-carousel.component.ts:100:20: Starting carousel
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/pages/page-frame/page-frame.component.ts:20:20: ActiveSport: 'football'
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/angular-material/b2g-carousel/b2g-carousel.component.ts:112:20: Stopped carousel
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/pages/page-frame/page-frame.component.ts:20:20: ActiveSport: 'football'
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
NativeScript discarding uncaught JS exception!
CONSOLE LOG file: src/app/angular-material/b2g-carousel/b2g-carousel.component.ts:100:20: Starting carousel
NativeScript discarding uncaught JS exception!

```
This occurs while navigating to different pages of the app.

**To Reproduce**

Notice the above Grid does not associate elements on every row or column.

**Expected behavior**

To behave like tns-ios 6.3.x versions or ALL android versions and to not throw an exception.

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@jalberto-ghub I am not able to reproduce the issue on iOS (using[ this test app](https://github.com/NickIliev/NS-Issues-2020/tree/master/NativeScript/issue-8387)). Could you check if you have all the resource files in your iOS resource directory and if the issue persists then please create a sample project that we can use for furthe4r investigation?

**Comment by jalberto-ghub** [comment]
This is happening when testing on an emulator iPhone 6 using iOS 12.4.
Is 6.4.2 compatible with iOS 12.4?

**Comment by NickIliev** [comment]
@jalberto-ghub yes it is - I will test on my side with iOS 12.4 and post back.

**Comment by jalberto-ghub** [comment]
@NickIliev we found the issue, we had an `<Image>` passing `[row]="undefined"` into the grid. On android this was treated as `[row]="0"` but on ios it does not an therefore it explodes. So we only saw the problem on ios. I guess the ios implementation needs a little bit of more defensive code.

**Comment by delaneyb** [comment]
Hi @NickIliev,

I have been experiencing issues with GridLayout on iOS when element rendering is toggled by  asynchronous activities and elements in the tree dont have row or col defined. I haven't been able to work out exactly what's causing this but here is a fairly simply playground that causes the crash:

[https://play.nativescript.org/?template=play-vue&id=y3UESy&v=1](https://play.nativescript.org/?template=play-vue&id=y3UESy&v=1)

In GridLayout.prototype.getRowIndex() (grid-layout.js), the views row property is undefined, where it should have been set to a default of 0 somewhere I assume.

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10377e928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1037b902c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x1043267f8 ffi_closure_SYSV_inner
4   0x1043281b4 .Ldo_closure
5   0x192e4b7dc <redacted>
6   0x19539978c <redacted>
7   0x19539f908 <redacted>
8   0x1953aa528 <redacted>
9   0x1952f2ed0 <redacted>
10  0x19531cbbc <redacted>
11  0x19531d5b0 <redacted>
12  0x18e8cac2c <redacted>
13  0x18e8c5b18 <redacted>
14  0x18e8c60e4 <redacted>
15  0x18e8c58a0 CFRunLoopRunSpecific
16  0x19881d328 GSEventRunModal
17  0x1929b6740 UIApplicationMain
18  0x104328044 ffi_call_SYSV
19  0x104325f1c ffi_call_int
20  0x104325a18 ffi_call
21  0x10374146c NativeScript::FunctionWrapper::call(JSC::ExecState*)
22  0x1042f2cf0 llint_entry
23  0x1042f0108 llint_entry
24  0x1042f0108 llint_entry
25  0x1042f0108 llint_entry
26  0x1042f0108 llint_entry
27  0x1042f0108 llint_entry
28  0x1042f0108 llint_entry
29  0x1042f0108 llint_entry
30  0x1042f0108 llint_entry
31  0x1042d17c8 vmEntryToJavaScript
JavaScript stack trace:
grid-layout.ios.js:351
at grid-layout.ios.js:113
at layout-base-common.js:136
at view-common.js:933
at layout-base-common.js:134
at layout-base-common.js:125
at layout-base-common.js:133
at grid-layout.ios.js:107
at view.ios.js:58
at view-helper-common.js:26
at view-common.js:903
at page.ios.js:302
at view.ios.js:58
at view-helper-common.js:26
at layoutView(view-helper.ios.js:64
at page.ios.js:195
at UIApplicationMain([native code])
at run(application.ios.js:312
at index.js:12644
at bundle.js:8529
at ./app.js(bundle.js:8533
at __webpack_require__(file: app/webpack/bootstrap:74:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at anonymous(bundle.js:2
at evaluate([native code])
at moduleEvaluation([native code])
at [native cod<\M-b\M^@\M-&>
JavaScript error:
grid-layout.ios.js:351 JS ERROR TypeError: undefined is not an object (evaluating 'this.rows[measureSpec.getRowIndex()].children')
```
