### ISSUE TITLE
Error: The new package couldn\'t be installed because the verification did not succeed

### ISSUE THREAD

**Issue by vforv** [NativeScript/NativeScript#8436]
After installing Open GApps in Genymotion I'm getting an error when I try to start the app:
Error: The new package couldn\'t be installed because the verification did not succeed

at Errors.failWithOptions (.nvm/versions/node/v10.16.3/lib/node_modules/nativescript/lib/common/errors.js:147:28

**Comment by NickIliev** [comment]
@vforv what is GApps - is this an app written in NativeScript?

If so - I guess the best place to post this question is in the app repository.

**Comment by farfromrefug** [comment]
Open GApps means Google apps. It is used to install Google play services. It   is integrated on most phone but not all emulator. 
The error might be related to safety net. But I think a logcatnis necessary here

**Comment by vforv** [comment]
Just install Genymotion then GApps and try to build app.

**Comment by FJALCode** [comment]
I have the same Issue @farfromrefug @NickIliev with the last version of genymotion 3.0.4
The console show
```bash
Installing on device xxx.xxx.xx.xxx:5555...
Unable to apply changes on device: xxx.xxx.xx.xxx:5555. Error is: The new package couldn't be installed because the verification did not succeed..
```

The code works before add the Open GApps, so maybe could be the genymotion version, I have the same Code in another PC with a different genymotion version (lower) and it work it with Open GApps. Try it with a different version of genymotion.

**Comment by farfromrefug** [comment]
@FJALCode  again please try and post a Logcat. It will give much more information.

**Comment by FJALCode** [comment]
@farfromrefug Al ejecutar un `tns run android --log trace`, esto es lo que arroja

```bash
Error name: INSTALL_FAILED_VERIFICATION_FAILURE result code: -22
The new package couldn't be installed because the verification did not succeed.
Unable to apply changes on device: xxx.xxx.xx.xxx:5555. Error is: The new package couldn't be installed because the verification did not succeed..
Will emit event liveSyncError with data { error:
   { Error: The new package couldn't be installed because the verification did not succeed.
       at Errors.fail (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/errors.js:126:28)
       at Errors.failWithoutHelp (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/errors.js:136:21)
       at AndroidDebugBridgeResultHandler.handleErrors (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge-result-handler.js:41:26)
       at DeviceAndroidDebugBridge.<anonymous> (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge.js:53:55)
       at Generator.next (<anonymous>)
       at fulfilled (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge.js:10:58)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'Exception',
     message:
      'The new package couldn\'t be installed because the verification did not succeed.',
     stack:
      'Error: The new package couldn\'t be installed because the verification did not succeed.\n    at Errors.fail (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/errors.js:126:28)\n    at Errors.failWithoutHelp (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/errors.js:136:21)\n    at AndroidDebugBridgeResultHandler.handleErrors (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge-result-handler.js:41:26)\n    at DeviceAndroidDebugBridge.<anonymous> (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge.js:53:55)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/fer/.npm-global/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge.js:10:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     errorCode: 127,
     suppressCommandHelp: true,
     proxyAuthenticationRequired: false,
     printOnStdout: undefined },
  deviceIdentifier: 'xxx.xxx.xx.xxx:5555',
  projectDir: '/home/fer/Escritorio/Trabajo/name/test-nativescript',
  applicationIdentifier: 've.com.sigis.nametest' }
Project dir from hooksArgs is: /home/fer/Escritorio/Trabajo/name/test-nativescript.
Hooks directories: [ '/home/fer/Escritorio/Trabajo/name/test-nativescript/hooks' ]
AfterHookName for command watch is after-watch
Executing after-watch hook at location /home/fer/Escritorio/Trabajo/name/test-nativescript/hooks/after-watch/nativescript-dev-sass.js in-process
Validating after-watch arguments.
Executing after-watch hook at location /home/fer/Escritorio/Trabajo/name/test-nativescript/hooks/after-watch/nativescript-dev-typescript.js in-process
Validating after-watch arguments.
Stopping tsc watch
Executing after-watch hook at location /home/fer/Escritorio/Trabajo/name/test-nativescript/hooks/after-watch/nativescript-dev-webpack.js in-process
Validating after-watch arguments.
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'after-watch__nativescript-dev-sass.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 1 }
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'after-watch__nativescript-dev-typescript.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 0 }
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'after-watch__nativescript-dev-webpack.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 0 }
Will emit event liveSyncStopped with data { projectDir: '/home/fer/Escritorio/Trabajo/name/test-nativescript',
  deviceIdentifier: 'xxx.xxx.xx.xxx:5555' }
```

**Comment by NickIliev** [comment]
@vforv  try to disable the USB verification (from the Developers Settings) as suggested [here](https://stackoverflow.com/a/42745369/4936697)

**Comment by FJALCode** [comment]
@NickIliev . Your recommendation works in my computer thnks you!.

@vforv I proved in a Samsung Galaxy S4 device with android 9.0. You can proved it!

**Comment by vforv** [comment]
It's working thank you!

**Comment by ignacio68** [comment]
It's working for me too. Thanks a lot!!
