### ISSUE TITLE
Failed to find module: "main-page.xml", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by cybaj** [NativeScript/NativeScript#8481]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules: NS javascript
 - Android Runtime: Android 8.0.0 Samsung A8*
 - iOS Runtime:
 - Plugin(s): nativescript-audio  5.0.5

**Describe the bug**

```tns preview```
and counted the error below.
```
Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > com.tns.NativeScriptException: Failed to find module: "main-page.xml", relative to: app/tns_modules/

StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > com.tns.NativeScriptException: Failed to find module: "main-page.xml", relative to: app/tns_modules/
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Building UI from XML. @app-root.xml:1:1
 > com.tns.NativeScriptException: Failed to find module: "main-page.xml", relative to: app/tns_modules/
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
	... 9 more
```

**To Reproduce**
 
1. clone this [project repo](https://github.com/cybaj/ns_js_audio).
2. `npm i`
3. `tns platform add android`
4. `tns preview`
5. counter the error.

**Expected behavior**

`tns preview` this project works on my iOS device.
This error occurs with android preview.
And so hard to find the reason, because I think the XML file located right directory obviously.
`main-page.xml` file located in the directory with `main-page.js`, `app-root.xml` and others.

I have tried `rm -rf node_modules platform hooks`, but it didn't works.

**Sample project**

[project repo](https://github.com/cybaj/ns_js_audio).

**Additional context**

I initiated this javascript NS project with `tns create something` and 
remotely build with `nativescript-remote-build` plugin.
so I thought that base project is fine.

so I added my code, and the error occurred on android preview only, not iOS device.
the log points out `main-page.xml` but, directory hierarchy is obviously fair, I think.

```
app
├── app.css
├── app.js
├── App_Resources
├── app-root.xml
├── main-page.js
├── main-page.xml
├── main-view-model.js
├── package.json
├── player-model.js
└── references.d.ts
```

Please help.

**Comment by cybaj** [comment]
I found additional information about this issue.

1. I build this project with `nativescript-remote-build` plugin, and the app opens successfully with `apk` file.
2. but the layout of the main page is little awkward.
- I insert the korean characters in the button, but doesn't show up.
- the characters shows up at iOS device
- but in iOS device, vertically, 1/3 part of the button view was hidden, and there are no border line at the button.
- the styling of this button is so weird.

this is the part of XML file covering the button.
```
                <StackLayout orientation="vertical">
                    <ScrollView orientation="horizontal">
                        <FlexboxLayout id="table" height="120" flexDirection="row"
                            backgroundColor="skyblue"
                            justifyContent="space-around"
                            alignContent="space-around">
                        </FlexboxLayout>
                    </ScrollView>
                    <StackLayout class="home-panel">
                        <StackLayout class="home-panel">
                            <Progress value="{{ progress }}" />
                        </StackLayout>
                    </StackLayout>
                    <Button class="button" text="{{ isPlaying ? '...' : '말하기' }}"
                        tap="onPlayButton" />
                </StackLayout>
```

**Comment by cybaj** [comment]
I found additional information.
I am sure about that this issue occurs between the `preview` and` nativescript-audio` plugins.
The error occurs even only with just importing `nativescript-audio` module by `const audio = require('nativescript-audio');`.
And not like `preview` of this project, it's builds works just fine.

- Plugin(s): nativescript-audio 5.0.5
- CLI: 6.5.0 and 6.4.1

**Comment by CatchABus** [comment]
Closing as the problem was related to old preview app.
