### ISSUE TITLE
update makes my application d'un on Android 8 ans higher

### ISSUE THREAD

**Issue by Fabiyo-90** [NativeScript/NativeScript#8506]
Hello !
Please excuse me, here I have a problem.
I use nativescript 6.5 and everything is up to date. But my application only works on android 8 and higher. On android 5, 6 and 7 my applicattion returns the error. I would like a solution track

![IMG-20200404-WA0018](https://user-images.githubusercontent.com/26508533/78569372-6d371d00-781b-11ea-9a78-ece0bca7e88a.jpg)

**Comment by ElecTreeFrying** [comment]
up

**Comment by Fabiyo-90** [comment]
Hello !
Please excuse me, here I have a problem.
I use nativescript 6.5 and everything is up to date. But my application only works on android 8 and higher. On android 5, 6 and 7 my applicattion returns the error. I would like a solution track

**Comment by triniwiz** [comment]
I'm going to assume you are using plugins an since you updated everything there might of been a breaking change in one of those said plugins

**Comment by NickIliev** [comment]
@Fabiyo-90 there is not much anyone can be said from the error on the screenshot. Please consider providing more details on your application as requested in the report a bug template.

Will reopen the issue if enough information for reproduction is provided.

```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```

**Comment by Fabiyo-90** [comment]
Hello triniwiz !
there is my package.json
{
  "nativescript": {
    "id": "cd.fabiyo.infocovid19",
    "tns-ios": {
      "version": "6.5.0"
    },
    "tns-android": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/theme": "~2.3.3",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-vue": "^2.5.1",
    "tns-core-modules": "~6.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "babel-loader": "^8.0.0",
    "nativescript-dev-webpack": "^1.5.1",
    "nativescript-vue-template-compiler": "^2.5.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.9.0"
  },
  "gitHead": "2250137db8c1e0bd0eb543e8e4563cb71480c00d",
  "readme": "NativeScript Application"
}

**Comment by Fabiyo-90** [comment]
Hello NickIliev !

there is details of my bug

An uncaught Exception occurred on "main" thread.
Failed to allocate a 269470572 byte allocation with 4501968 free bytes and 4MB until OOM

StackTrace:
java.lang.OutOfMemoryError: Failed to allocate a 269470572 byte allocation with 4501968 free bytes and 4MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
	at org.nativescript.widgets.image.Fetcher.decodeSampledBitmapFromFile(Fetcher.java:471)
	at org.nativescript.widgets.image.Fetcher.processBitmap(Fetcher.java:263)
	at org.nativescript.widgets.image.Worker.loadImage(Worker.java:119)
	at org.nativescript.widgets.ImageView.loadImage(ImageView.java:197)
	at org.nativescript.widgets.ImageView.onAttachedToWindow(ImageView.java:58)
	at android.view.View.dispatchAttachedToWindow(View.java:15509)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4456)
	at android.view.ViewGroup.addView(ViewGroup.java:4258)
	at android.view.ViewGroup.addView(ViewGroup.java:4198)
	at android.view.ViewGroup.addView(ViewGroup.java:4171)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1466)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by triniwiz** [comment]
Looks like you are loading a large image or several images with a decent size which seem to cause the OOM feel free to try any of the image plugins available
