### ISSUE TITLE
Cannot read property 'equals' of undefined on core\ui\styling\style-properties.js:

### ISSUE THREAD

**Issue by lucasschirm** [NativeScript/NativeScript#8558]
System.err: TypeError: Cannot read property 'equals' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'equals' of undefined
System.err: File: (file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)

**Environment**
I`m running NativeScript on Windows 10 Pro 64bits, the ns info:

√ Getting NativeScript components versions information...
√ Component nativescript has 6.5.0 version and is up to date.
√ Component tns-core-modules has 6.5.1 version and is up to date.
‼ Update available for component tns-android. Your current version is 6.3.1 and the latest available version is 6.5.0.
‼ Update available for component tns-ios. Your current version is 6.3.0 and the latest available version is 6.5.0.

**Describe the bug**
I run "tns debug android --emulator  --env.sourceMap --env.uglify --env.envtype=dev" and after the message bellow the error described popup

`Searching for devices...
Preparing project...
File change detected. Starting incremental webpack compilation...
webpack is watching the files…`

**To Reproduce**

`rm -rf node_modules/ platforms/ sourceMap/ package-lock.json hooks && npm i && tns install
tns debug android --emulator  --env.sourceMap --env.uglify --env.envtype=dev`

**Expected behavior**

**Additional context**

Webpack compilation complete. Watching for file changes.
Webpack build done!
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Project successfully prepared (android)
Configure firebase
Copy D:\intellective\marvel\mywork-mobile-app\App_Resources\Android\google-services.json to D:\intellective\marvel\mywork-mobile-app\platforms\android\app\google-services.json.
Successfully transferred runtime.js on device emulator-5554.
Restarting application on device emulator-5554...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'equals' of undefined
System.err: File: (file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)
System.err: 
System.err: StackTrace:
System.err: ../node_modules/@nativescript/core/ui/styling/style-properties.js(file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/core/view-base/view-base.js(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:14:25)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/core/view/view-common.js(file: node_modules\@nativescript\core\ui\core\view\view-common.js:5:18)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view\view.android.js:5:20)
System.err:     at ../node_modules/@nativescript/core/ui/core/view/view.js(file: node_modules\@nativescript\core\ui\core\view\view.android.js:953:21)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/frame/frame-common.js(file: node_modules\@nativescript\core\ui\frame\frame-common.js:6:13)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\frame.android.js:6:21)
System.err:     at ../node_modules/@nativescript/core/ui/frame/frame.js(file: node_modules\@nativescript\core\ui\frame\frame.android.js:1085:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/angular/platform-providers.js(file: node_modules\@nativescript\angular\platform-providers.js:3:14)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\angular\platform-common.js:15:27)
System.err:     at ../node_modules/@nativescript/angular/platform-common.js(file: node_modules\@nativescript\angular\platform-common.js:322:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\angular\platform.js:6:24)
System.err:     at ../node_modules/@nativescript/angular/platform.js(file: node_modules\@nativescript\angular\platform.js:44:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/co.intellective.apps.marvel/files/app/bundle.js:1819:27)
System.err:     at ./main.ts(file:///data/data/co.intellective.apps.marvel/files/app/bundle.js:1838:108)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:43:0)
System.err:     at r(file: src\webpack\bootstrap:30:0)
System.err:     at (file: src\$_lazy_route_resource lazy namespace object:4:0)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Cannot read property 'equals' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'equals' of undefined
System.err: File: (file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)
System.err:
System.err: StackTrace:
System.err: ../node_modules/@nativescript/core/ui/styling/style-properties.js(file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/core/view-base/view-base.js(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:14:25)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/core/view/view-common.js(file: node_modules\@nativescript\core\ui\core\view\view-common.js:5:18)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view\view.android.js:5:20)
System.err:     at ../node_modules/@nativescript/core/ui/core/view/view.js(file: node_modules\@nativescript\core\ui\core\view\view.android.js:953:21)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/frame/frame-common.js(file: node_modules\@nativescript\core\ui\frame\frame-common.js:6:13)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\frame.android.js:6:21)
System.err:     at ../node_modules/@nativescript/core/ui/frame/frame.js(file: node_modules\@nativescript\core\ui\frame\frame.android.js:1085:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/angular/platform-providers.js(file: node_modules\@nativescript\angular\platform-providers.js:3:14)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\angular\platform-common.js:15:27)
System.err:     at ../node_modules/@nativescript/angular/platform-common.js(file: node_modules\@nativescript\angular\platform-common.js:322:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\angular\platform.js:6:24)
System.err:     at ../node_modules/@nativescript/angular/platform.js(file: node_modules\@nativescript\angular\platform.js:44:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/co.intellective.apps.marvel/files/app/bundle.js:1819:27)
System.err:     at ./main.ts(file:///data/data/co.intellective.apps.marvel/files/app/bundle.js:1838:108)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:43:0)
System.err:     at r(file: src\webpack\bootstrap:30:0)
System.err:     at (file: src\$_lazy_route_resource lazy namespace object:4:0)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'equals' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'equals' of undefined
System.err: File: (file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)
System.err:
System.err: StackTrace:
System.err: ../node_modules/@nativescript/core/ui/styling/style-properties.js(file: node_modules\@nativescript\core\ui\styling\style-properties.js:613:5)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/core/view-base/view-base.js(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:14:25)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/core/view/view-common.js(file: node_modules\@nativescript\core\ui\core\view\view-common.js:5:18)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view\view.android.js:5:20)
System.err:     at ../node_modules/@nativescript/core/ui/core/view/view.js(file: node_modules\@nativescript\core\ui\core\view\view.android.js:953:21)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/core/ui/frame/frame-common.js(file: node_modules\@nativescript\core\ui\frame\frame-common.js:6:13)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\frame.android.js:6:21)
System.err:     at ../node_modules/@nativescript/core/ui/frame/frame.js(file: node_modules\@nativescript\core\ui\frame\frame.android.js:1085:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/@nativescript/angular/platform-providers.js(file: node_modules\@nativescript\angular\platform-providers.js:3:14)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\angular\platform-common.js:15:27)
System.err:     at ../node_modules/@nativescript/angular/platform-common.js(file: node_modules\@nativescript\angular\platform-common.js:322:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\@nativescript\angular\platform.js:6:24)
System.err:     at ../node_modules/@nativescript/angular/platform.js(file: node_modules\@nativescript\angular\platform.js:44:0)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/co.intellective.apps.marvel/files/app/bundle.js:1819:27)
System.err:     at ./main.ts(file:///data/data/co.intellective.apps.marvel/files/app/bundle.js:1838:108)
System.err:     at k(file: src\webpack\bootstrap:750:0)
System.err:     at n(file: src\webpack\bootstrap:43:0)
System.err:     at r(file: src\webpack\bootstrap:30:0)
System.err:     at (file: src\$_lazy_route_resource lazy namespace object:4:0)
System.err:     at require(:1:266)
System.err:
System.err: 
System.err: TypeError: Cannot read property 'equals' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
System.err:     ... 8 more

**Comment by crowmagnumb** [comment]
Yes seconded. I am getting this same error in core/ui/html-view/html-view-common.js. It seems that the export of Color in core/color/color.android.js and color.ios.js is getting messed up from the export in color-common.js. That Color object is fine but then after passing through color.android and color.ios it is screwed up and not coming out as expected.

**Comment by crowmagnumb** [comment]
UPDATE: I found this can be super easily recreated. Make the most bare-bones app possible and simply add the following code:
```
import { HtmlView } from "@nativescript/core";
console.log(HtmlView);
```
I have a repo [here](https://github.com/animalus/testns-app) that demonstrates that. Checkout the branch `color-problem` and run it.

**Comment by bradmartin** [comment]
I've seen this... several months ago... I don't remember how I got past it 🤔 - it may have been a bug fix in core-modules or I may have just downgraded for the time being to a previous version.

**Comment by crowmagnumb** [comment]
My problem ended up being a path entry in my tsconfig.json file. I had ...
```
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/*"
            ]
        }
```

... and if I remove the node_modules one it works, my working tsconfig.json file has paths ...

```
        "paths": {
            "~/*": ["src/*"]
        }
```

**Comment by limyandi** [comment]
hi @crowmagnumb, that fixed my issue a well, can you please elaborate a little bit on how that fixed the issue?

**Comment by crowmagnumb** [comment]
@limyandi  Well, I don't really know. If I remember right was comparing my test repo to others I found online and trying every little difference I saw and came upon this fix that way.  And since that paths entry did not seem to negatively affect anything (for me) I just made the change and moved on. Sorry I can't be of more help.
