### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.parent.requestLayout')

### ISSUE THREAD

**Issue by Rav-Naz** [NativeScript/NativeScript#8599]
**Environment**
 - CLI: 6.5.0
 - Cross-platform modules: 6.5.0
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s):
"nativescript-angular": "^8.21.0",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-email": "^1.5.5",
    "nativescript-feedback": "^1.3.12",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-permissions": "^1.3.7",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "^6.1.0",
    "nativescript-ui-listview": "^8.2.0",
    "nativescript-windowed-modal": "^6.2.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^6.4.0",
    "serialize-javascript": ">=2.1.1",
    "tns-core-modules": "^6.5.1",
    "zone.js": "^0.9.1"

**Describe the bug**
I'm using Tabs component to navigate between 3 screens and also bottom navigation. From third Tab I can go to other screen. When I try to close it using router.back() from _RouterExtension_ I'm getting this error:
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10312e928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10316902c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x103cd67f8 ffi_closure_SYSV_inner
4   0x103cd81b4 .Ldo_closure
5   0x19ae88944 __NSFireTimer
6   0x19aa1c1c0 <redacted>
7   0x19aa1bedc <redacted>
8   0x19aa1b5b8 <redacted>
9   0x19aa165c8 <redacted>
10  0x19aa15c34 CFRunLoopRunSpecific
11  0x1a4b5f38c GSEventRunModal
12  0x19eb4822c UIApplicationMain
13  0x103cd8044 ffi_call_SYSV
14  0x103cd5f1c ffi_call_int
15  0x103cd5a18 ffi_call
16  0x1030f146c NativeScript::FunctionWrapper::call(JSC::ExecState*)
17  0x103ca2cf0 llint_entry
18  0x103ca0108 llint_entry
19  0x103ca0108 llint_entry
20  0x103ca0108 llint_entry
21  0x103ca0108 llint_entry
22  0x103ca0108 llint_entry
23  0x103ca0108 llint_entry
24  0x103ca0108 llint_entry
25  0x103ca0108 llint_entry
26  0x103ca0060 llint_entry
27  0x103ca0108 llint_entry
28  0x103c817c8 vmEntryToJavaScript
29  0x10322daf0 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
30  0x103ad2cd8 JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&)
31  0x103109c40 NativeScript::GlobalObject::moduleLoaderEvaluate(JSC::JSGlobalObject*, JSC::ExecState*, JSC::JSModuleLoader*, JSC::JSValue, JSC::JSValue, JSC::JSValue)
JavaScript stack trace:
file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:412:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:408:36
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:188:0
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:496:0
at timer(file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:1561:0)
at invoke(file: node_modules/@nativescript/core/timer/timer.ios.js:54:30)
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:151:0
at file: node_modules/@nativescript/core/timer/timer.ios.js:18:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7991:144
at ./main.ts(file:///app/bundle.js:7996:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
**JavaScript error:
file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:412:0: JS ERROR TypeError: undefined is not an object (evaluating 'this.parent.requestLayout')**
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10312e928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x103176b68 -[TNSRuntimeInspector reportFatalError:]
3   0x1024e3ae0
4   0x19aa9d8f8 <redacted>
5   0x19a7bfe74 <redacted>
6   0x19a86614c <redacted>
7   0x19a868bd8 __cxa_get_exception_ptr
8   0x19a868b98 <redacted>
9   0x19a7bfcf8 <redacted>
10  0x10312ee00 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10316902c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
12  0x103cd67f8 ffi_closure_SYSV_inner
13  0x103cd81b4 .Ldo_closure
14  0x19ae88944 __NSFireTimer
15  0x19aa1c1c0 <redacted>
16  0x19aa1bedc <redacted>
17  0x19aa1b5b8 <redacted>
18  0x19aa165c8 <redacted>
19  0x19aa15c34 CFRunLoopRunSpecific
20  0x1a4b5f38c GSEventRunModal
21  0x19eb4822c UIApplicationMain
22  0x103cd8044 ffi_call_SYSV
23  0x103cd5f1c ffi_call_int
24  0x103cd5a18 ffi_call
25  0x1030f146c NativeScript::FunctionWrapper::call(JSC::ExecState*)
26  0x103ca2cf0 llint_entry
27  0x103ca0108 llint_entry
28  0x103ca0108 llint_entry
29  0x103ca0108 llint_entry
30  0x103ca0108 llint_entry
31  0x103ca0108 llint_entry
JavaScript stack trace:
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7991:144
at ./main.ts(file:///app/bundle.js:7996:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
**JavaScript error:
file: node_modules/@nativescript/core/application/application.ios.js:312:0: JS ERROR Error: NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'this.parent.requestLayout')**
at
file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:412:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:408:36
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:188:0
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:496:0
at timer(file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:1561:0)
at invoke(file: node_modules/@nativescript/core/timer/timer.ios.js:54:30)
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:151:0
at file: node_modules/@nativescript/core/timer/timer.ios.js:18:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7991:144
at ./main.ts(file:///app/bundle.js:7996:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionRe<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x103177c7c sig_handler(int)
2   0x19a7a6884 <redacted>
3   0x19a7ab1e8 <redacted>
4   0x19a6fe644 abort
5   0x19a866cc0 <redacted>
6   0x19a86616c <redacted>
7   0x19a868bd8 __cxa_get_exception_ptr
8   0x19a868b98 <redacted>
9   0x19a7bfcf8 <redacted>
10  0x10312ee00 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10316902c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
12  0x103cd67f8 ffi_closure_SYSV_inner
13  0x103cd81b4 .Ldo_closure
14  0x19ae88944 __NSFireTimer
15  0x19aa1c1c0 <redacted>
16  0x19aa1bedc <redacted>
17  0x19aa1b5b8 <redacted>
18  0x19aa165c8 <redacted>
19  0x19aa15c34 CFRunLoopRunSpecific
20  0x1a4b5f38c GSEventRunModal
21  0x19eb4822c UIApplicationMain
22  0x103cd8044 ffi_call_SYSV
23  0x103cd5f1c ffi_call_int
24  0x103cd5a18 ffi_call
25  0x1030f146c NativeScript::FunctionWrapper::call(JSC::ExecState*)
26  0x103ca2cf0 llint_entry
27  0x103ca0108 llint_entry
28  0x103ca0108 llint_entry
29  0x103ca0108 llint_entry
30  0x103ca0108 llint_entry
31  0x103ca0108 llint_entry
JS Stack:
UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7991:144
at ./main.ts(file:///app/bundle.js:7996:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob

When I'm using ONLY bottom navigation everything works as expected.

**Expected behavior**
As using only bottom navigation

**Sample project**
[My repository](https://github.com/Rav-Naz/LSOApp/tree/master/LSOApp/LSOApp/src/app/ministrant)

**Comment by Ross-Olivares** [comment]
Hi @Rav-Naz 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by lilfelix** [comment]
I am facing exactly the same issue.
I'm using Nativescript 6.7.8 and testing on an iPhone 8 emulator (Software version 13.5).
I have a Tab in which I display the Angular component,
 CardList, and when I tap an item in the list i enter a detail-page, CardDetail. 
If i press on the native "back" button in the ActionBar, the app crashes invariably.

Could it have to do with the fact that I'm lazy-loading the card.module, and CardList and CardDetail are siblings?
I have tried fiddling with various alternatives, but I can't get it to work. I'll attach the relevant code below.

**card-routing.module.ts:**
```
const routes: Routes = [
    { path: "", redirectTo: "/card-list", pathMatch: "full" },
    {
        path: "card-list",
        component: CardListComponent,
        children: [
            { path: "modal-view", component: ModalAddCardComponent }
        ]
    },
    { path: "card-detail/:id", component: CardDetailComponent }
];

@NgModule({
    imports: [NativeScriptRouterModule.forChild(routes)],
    exports: [NativeScriptRouterModule]
})
```

**card-list.component.html:**
```
<ActionBar>
    <Label text="Cards"></Label>
</ActionBar>

<StackLayout>
    <GridLayout>
        <ListView class="list-group" [items]="cards">
            <ng-template let-item="item">
                <FlexboxLayout [nsRouterLink]="['../card-detail', item.id]">
                    <Label class="list-group-item text-left" fontSize="20" [text]="item.name"  height="60"></Label>
                </FlexboxLayout>
            </ng-template>
        </ListView>
    </GridLayout>
</StackLayout>
```

I have omitted the following files, as I don't think they're relevant to the issue (since I'm using native back-navigation):
**card-list.component.ts**
**card-detail.component.html**
**card-detail.component.ts**

**The stacktrace:**
```
NativeScript debugger attached.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x106c6160e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x106ca2548 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x1076a3222 ffi_closure_unix64_inner
4   0x1076a3c4a ffi_closure_unix64
5   0x7fff23da14b4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
6   0x7fff23da114e __CFRunLoopDoTimer
7   0x7fff23da07aa __CFRunLoopDoTimers
8   0x7fff23d9b3fe __CFRunLoopRun
9   0x7fff23d9a944 CFRunLoopRunSpecific
10  0x7fff38ba6c1a GSEventRunModal
11  0x7fff48c8b9ec UIApplicationMain
12  0x1076a3a8d ffi_call_unix64
13  0x10e69a2c0
JavaScript stack trace:
file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:412:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:408:36
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:188:0
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:496:0
at timer(file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:1561:0)
at invoke(file: node_modules/@nativescript/core/timer/timer.ios.js:54:30)
at file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:151:0
at file: node_modules/@nativescript/core/timer/timer.ios.js:18:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:490:144
at ./main.ts(file:///app/bundle.js:495:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:412:0: JS ERROR TypeError: undefined is not an object (evaluating 'this.parent.requestLayout')
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x106c6160e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x106cb35f4 -[TNSRuntime executeModule:referredBy:]
3   0x10653fdc3 main
4   0x7fff51a231fd start
JavaScript stack trace:
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:490:144
at ./main.ts(file:///app/bundle.js:495:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/application/application.ios.js:312:0: JS ERROR Error
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x106c6160e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x106cb0f76 -[TNSRuntimeInspector reportFatalError:]
3   0x10654224b TNSInspectorUncaughtExceptionHandler
4   0x7fff23e3d36d __handleUncaughtException
5   0x7fff50ba8c05 _objc_terminate()
6   0x7fff4f9f6c87 std::__terminate(void (*)())
7   0x7fff4f9f940b __cxa_get_exception_ptr
8   0x7fff4f9f93d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
9   0x7fff50ba8ad6 _objc_exception_destructor(void*)
10  0x106c61b4f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x106cb35f4 -[TNSRuntime executeModule:referredBy:]
12  0x10653fdc3 main
13  0x7fff51a231fd start
JavaScript stack trace:
JavaScript error:
JS ERROR Error: NativeScript encountered a fatal error: Error
at
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:490:144
at ./main.ts(file:///app/bundle.js:495:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
NativeScript caught signal 6.
Native Stack:
1   0x106cb2251 sig_handler(int)
2   0x7fff51c005fd _sigtramp
3   0x7fff51af4f39 itoa64
4   0x7fff51af0b7c abort
5   0x7fff4f9f7858 abort_message
6   0x7fff4f9f6cad std::__terminate(void (*)())
7   0x7fff4f9f940b __cxa_get_exception_ptr
8   0x7fff4f9f93d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
9   0x7fff50ba8ad6 _objc_exception_destructor(void*)
10  0x106c61b4f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x106cb35f4 -[TNSRuntime executeModule:referredBy:]
12  0x10653fdc3 main
13  0x7fff51a231fd start
JS Stack:
```

Appreciate any help on the issue!
/Felix
