### ISSUE TITLE
onReceivedSslError in Android WebView doesn't works

### ISSUE THREAD

**Issue by cybaj** [NativeScript/NativeScript#8632]
### Environment
- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Android Runtime: 6.5.0
- iOS Runtime: 6.5.0
- Plugin(s): nativescript-webview-interface
- Node.js: v12.16.1

### Describe the bug
`onReceivedSslError` on `WebClient` implementation was not fired.

I got some experience about this issue, and results I can't understand.  
1. I use `WebClientSSLImplementation` which extends `WebClient`, overwriting `onReceivedSslError`. [repos](https://github.com/cybaj/test_webview_extend)
```
export class WebViewClientSslImpl extends android.webkit.WebViewClient {
    
    constructor(public owner: any) {
        super();
        return global.__native(this);
    }
    // ...
    public onReceivedSslError(view: any, handler: any, error: any) {
        handler.proceed();
        console.log('ssl error')
    }
};
```
```
export function onWebViewLoaded(args: EventData) {
    let wv = <WebView>args.object;
    const clientWithSsl = new WebViewClientSslImpl(wv);
    const androidWebView = <android.webkit.WebView>wv.android;
    androidWebView.setWebViewClient(clientWithSsl);
}
```

2. With my android device (Android 8.0.0), I have `preview` it. mostly `onReceivedSslError` was not fired. but, I don't know why this happening, after I added log line in `onReceivedSslError`, it was fired. and the handler `proceed`ed.
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
LOG from device Galaxy A8 Star: HMR: Hot Module Replacement Enabled. Waiting for signal.
LOG from device Galaxy A8 Star: https://192.168.0.6:50468
LOG from device Galaxy A8 Star: ssl error
LOG from device Galaxy A8 Star: https://192.168.0.6:9999
LOG from device Galaxy A8 Star: ssl error
LOG from device Galaxy A8 Star: ssl error
```
but it was only once. after then it doesn't fire. 
```
Preparing project...
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
LOG from device Galaxy A8 Star: HMR: Hot Module Replacement Enabled. Waiting for signal.
LOG from device Galaxy A8 Star: https://192.168.0.8:9999
LOG from device Galaxy A8 Star: https://192.168.0.8:50468
```
3. I built it remotely with `nativescript-remote-builds`. Installation was fine in same device. But this time, an error occurs, after I run the app.
```
An uncaught Exception occurred on "main" thread.
Calling js method onReceivedError failed
Error: JNI Exception occurred (SIGABRT).
=======
Check the 'adb logcat' for additional information about the error.
=======


StackTrace:
module.exports.push../web-view.ts.WebViewClientSslImpl.onReceivedError(file:///data/data/org.nativescript.remoteextendswebviewclient/files/app/bundle.js:334:46)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.android.webkit.WebViewClient_bundle_297_28_WebViewClientSslImpl.onReceivedError(WebViewClient_bundle_297_28_WebViewClientSslImpl.java:72)
	at Ox0.handleMessage(chromium-Monochrome.aab-stable-410410173:134)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
4. I can't not even assume where this is coming from. but maybe it is issue about **marking mode** I think. I don't know what is exactly `markingMode=none` safe code, but have some try.
```
import { WebViewClientSslImpl } from "./web-view";

export class HelloWorldModel extends Observable {
    public webviewclient: WebViewClientSslImpl;
    // ...
```
```
export function onWebViewLoaded(args: EventData) {
    let wv = <WebView>args.object;
    const context = wv.page.bindingContext
    const clientWithSsl = new WebViewClientSslImpl(wv);
    context.set('webviewclient', clientWithSsl)

    const androidWebView = <android.webkit.WebView>wv.android;
    androidWebView.setWebViewClient(context.webviewclient);
}
```
I `preview` it,  and it works only once, just like before.
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-....).
LOG from device Galaxy A8 Star: https://www.naver.com
LOG from device Galaxy A8 Star: https://192.168.0.6:50468
LOG from device Galaxy A8 Star: ssl error
```
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-33b010505c29).
Successfully sent initial files for device Galaxy A8 Star (7e85afcb-....-463a-b991-33b010505c29).
LOG from device Galaxy A8 Star: https://www.naver.com
LOG from device Galaxy A8 Star: https://192.168.0.8:50468
```
what should I have to do to figure this out?

### To Reproduce
`tns preview` or
`tns build android`

### Expected behavior
`onReceivedSslError` should be fired.

### Sample project
[repos](https://github.com/cybaj/test_webview_extend)

### Additional context
I build with `nativescript-remote-builds`.

_Originally posted by @cybaj in https://github.com/NativeScript/NativeScript/issues/3998#issuecomment-643160476_

**Comment by Ross-Olivares** [comment]
Hi @cybaj 
Thank you for reporting this issue.
I am going to try and replicate this case on my end and will confirm if onReceivedSslError in Android WebView doesn't works.
We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by diegovincent** [comment]
Is this related to not being able to open `notion.so` on Android?

**Comment by cybaj** [comment]
@diegovincent I don't know.
1. not being able to open `notion.so` on Android Webview
2. but I think there must be some valid certificate at `notion.so` 
... is anyone who guess what's going on?

**Comment by diegovincent** [comment]
My best guess was that, due to marketing purposes, they put an `iframe` in their page that gets information from another domain, and they send some HTTP headers that do not like that behavior.

I had some information stored, ironically, in Notion. I can post it here in a few days.

**Comment by diegovincent** [comment]
We managed to fix the `Notion` "bug" on Android. Our solution is based on using the`loaded` event.

```html
<WebView (loaded)="onLoaded($event)"></WebView>
```

```typescript
function onLoaded($event): void {
  const webview: WebView = <WebView>$event.object;
  if(isAndroid){
    WebSettings settings = webView.getSettings();
    settings.setDomStorageEnabled(true);
  }
}
```

See:
- https://github.com/NativeScript/NativeScript/issues/4819
- https://stackoverflow.com/questions/33079762/android-webview-uncaught-typeerror-cannot-read-property-getitem-of-null
CC @cybaj @NathanWalker

**Comment by cybaj** [comment]
@diegovincent That seems very useful. Thank you!
about `onReceivedSslError`, maybe I need to create _Implemented Webview_ more _natively_.

**Comment by stravi** [comment]
@cybaj were you able to fix this problem?
