### ISSUE TITLE
Angular: View already has a parent

### ISSUE THREAD

**Issue by crowmagnumb** [NativeScript/NativeScript#8674]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

```
Angular CLI --> 9.1.6
@angular 9.1.4

$ tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.7.4 and the latest available version is 6.7.6.
⚠ Update available for component @nativescript/core. Your current version is 6.5.1 and the latest available version is 6.5.8.
⚠ Update available for component tns-android. Your current version is 6.5.0 and the latest available version is 6.5.1.
⚠ Update available for component tns-ios. Your current version is 6.5.0 and the latest available version is 6.5.1.
```

**Describe the bug**

I'm getting the following error now and I think I get it through various paths (I'll post other paths as I find them).

```
View already has a parent. View: SegmentedBarItem(1453) Parent: SegmentedBar(1484)::Error: View already has a parent. View: SegmentedBarItem(1453) Parent: SegmentedBar(1484)
    at new ZoneAwareError (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:124291:33)
    at SegmentedBar.push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addView (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:142345:19)
    at SegmentedBar.push.../node_modules/@nativescript/core/ui/segmented-bar/segmented-bar-common.js.SegmentedBarBase.onItemsChanged (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:154211:22)
    at valueChanged (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:154257:16)
    at SegmentedBar.Property.set [as items] (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:140852:25)
    at ViewUtil.push.../node_modules/@nativescript/angular/view-util.js.ViewUtil.setPropertyInternal (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:122934:32)
    at ViewUtil.push.../node_modules/@nativescript/angular/view-util.js.ViewUtil.setProperty (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:122911:18)
    at NativeScriptRenderer.push.../node_modules/@nativescript/angular/renderer.js.NativeScriptRenderer.setProperty (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:119989:30)
    at elementPropertyInternal (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:53248:22)
    at ɵɵproperty (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:59548:9)
    at HomePageComponent_ng_container_1_ng_container_1_Template (file:///data/data/com.animalus.scidir.dev/files/app/bundle.js:1914:95)
    at executeTemplate (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:52841:9)
    at refreshView (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:52710:13)
    at refreshDynamicEmbeddedViews (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:53806:17)
    at refreshView (file:///data/data/com.animalus.scidir.dev/files/app/vendor.js:52734:9)
```

**To Reproduce**

In the above case I have a screen that shows  a login button only if not logged in, then after logging in the *ngIf switches the contents of the View to something that contains a SegmentedBar and I get this error and the page does not continue rendering. If I navigate off to another page and then back to this page (still logged in so the ngIf kicks in right away) it then displays correctly.

Here is my page view in pug format ...

```
au-action-bar
ng-container(*ngIf="authCheckComplete; else awaitingAuthCheck")
    ng-container(*ngIf="account; else notLoggedIn")
        GridLayout(rows="auto, *, auto" margin="8")
            ActivityIndicator(row="0" rowSpan="1" [busy]="busy")
            FlexBoxLayout(row="0" flexDirection="row" justifyContent="space-between")
                Label.bigger-font.primary(text="Voyages")

                //- action-button((action)="toggleShowPast()" [text]="showPast ? 'Upcoming' : 'Past'")
                action-icon(*ngIf="!gpsEnabled" icon="gps_fixed", (action)="requestGpsEnable()")
                action-icon(icon="refresh", (action)="refresh()")
            GridLayout(row="1" rows="auto, *")
                SegmentedBar.primary(row="0" #sb
                                     [selectedIndex]="tabIndex"
                                     [items]="tabs",
                                     (selectedIndexChange)="tabChange(sb.selectedIndex)"
                                     marginBottom="8")
                ng-container([ngSwitch]="tabIndex")
                    ng-container(*ngSwitchCase="0")
                        ListView(row="1" [items]="upcomingSurveys", (itemTap)="onSelectUpcomingSurvey($event)")
                            ng-template(let-survey="item")
                                FlexBoxLayout(margin="8" flexDirection="row" alignItems="center")
                                    survey-info([survey]="survey")
                                    au-icon.warn(*ngIf="surveyDataManager.isSurveyChanged(survey)" icon="warning")
                    ng-container(*ngSwitchCase="1")
                        ListView(row="1" [items]="pastSurveys", (itemTap)="onSelectPastSurvey($event)")
                            ng-template(let-survey="item")
                                FlexBoxLayout(margin="8" flexDirection="row" alignItems="center")
                                    survey-info([survey]="survey")
                                    au-icon.warn(*ngIf="surveyDataManager.isSurveyChanged(survey)" icon="warning")
            GridLayout(row="2" columns="*, auto" backgroundColor="rgba(0,0,0,.25)")
                au-label(col="0" text="Is your upcoming voyage not listed? If so, send us details of your upcoming voyage(s) including company, vessel, and start + end dates by pressing the email icon." padding="4" color="black")
                action-icon(col="1" icon="email", (action)="onEmail()" margin="4")
    ng-template(#notLoggedIn)
        GridLayout(rows="*, auto, auto" [backgroundImage]="landingImage" backgroundRepeat="no-repeat" backgroundPosition="center" backgroundSize="contain")
            au-label(row="1" text="Are you a citizen scientist interested in polar realms? This is the place for you! Log in / create account with your Happywhale credentials and begin a fun and rewarding journey into science." backgroundColor="rgba(254,254,254,.5)" padding="8")
            au-flexbox(row="2" align="space-between")
                action-button((action)="showLoginModal()" text="Log in" margin="8")
                action-button((action)="showLoginModal(2)" text="Create account" margin="8")
ng-template(#awaitingAuthCheck)
    GridLayout(rows="*")
        au-label.bigger-font.primary(row="0" text="Checking login status...")
```

**Comment by crowmagnumb** [comment]
I resubmitted this in the nativescript-angular repo
