### ISSUE TITLE
RadListView: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by dosomder** [NativeScript/NativeScript#8680]
**Environment**
```
[administrator@4616 demo % tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.5.1 and the latest available version is 6.7.8.
✔ Component tns-core-modules has 6.5.8 version and is up to date.
⚠ Update available for component tns-android. Your current version is 6.4.1 and the latest available version is 6.5.1.
⚠ Update available for component tns-ios. Your current version is 6.4.0 and the latest available version is 6.5.1.
```

`"nativescript-ui-listview": "^8.2.0"`

**Describe the bug**
I am working on a NativeScript plugin to provide the Marquee effect for labels. On Android it uses native api and works fine. On iOS I use a custom library. When I use the component in a RadListView I always get an exception. I'm not sure if this a bug of RadListView. Because out of the RadListView it works fine. E.g. in the example project I also use it inside the ActionBar.

When I want to set padding on the custom label it also seems to crash.

**To Reproduce**
Open demo of https://github.com/dosomder/nativescript-marqueelabel on iOS. After 5 seconds (when items are loaded to RadListView) exception will occur.

**Expected behavior**
Labels show fine in list view without exception.

**Sample project**
https://github.com/dosomder/nativescript-marqueelabel/tree/master/demo

**Additional context**
<details>
  <summary>Full exception (click to open)</summary>

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10e7cc83e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10e80d6b8 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10f20e3c2 ffi_closure_unix64_inner
4   0x10f20edea ffi_closure_unix64
5   0x7fff23da14b4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
6   0x7fff23da114e __CFRunLoopDoTimer
7   0x7fff23da07aa __CFRunLoopDoTimers
8   0x7fff23d9b3fe __CFRunLoopRun
9   0x7fff23d9a944 CFRunLoopRunSpecific
10  0x7fff38ba6c1a GSEventRunModal
11  0x7fff48c8b9ec UIApplicationMain
12  0x10f20ec2d ffi_call_unix64
13  0x113d92e90
JavaScript stack trace:
insertItemsAtIndexPaths(file: node_modules/nativescript-ui-listview/ui-listview.ios.js:1648:0)
at file: node_modules/nativescript-ui-listview/ui-listview.ios.js:1648:0
at file: node_modules/nativescript-ui-listview/ui-listview.common.js:755:0
at handler(file: node_modules/@nativescript/core/ui/core/weak-event-listener/weak-event-listener.js:32:0)
at file: node_modules/@nativescript/core/data/observable/observable.js:124:0
at file: node_modules/@nativescript/core/data/observable-array/observable-array.js:101:0
at file: app/home/home-view-model.ts:12:20
at invoke(file: node_modules/@nativescript/core/timer/timer.ios.js:54:30)
at file: node_modules/@nativescript/core/timer/timer.ios.js:18:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file:///app/bundle.js:144:65
at ./app.ts(file:///app/bundle.js:160:34)
at __webpack_require__(file: app/webpack/bootstrap:750:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/nativescript-ui-listview/ui-listview.ios.js:1648:0: JS ERROR Error: -[TKListView setOwnerListView:]: unrecognized selector sent to instance 0x7fadd26129b0
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10e7cc83e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10e81e6c4 -[TNSRuntime executeModule:referredBy:]
3   0x10e0ea1c3 main
4   0x7fff51a231fd start
5   0x1
JavaScript stack trace:
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file:///app/bundle.js:144:65
at ./app.ts(file:///app/bundle.js:160:34)
at __webpack_require__(file: app/webpack/bootstrap:750:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/application/application.ios.js:312:0: JS ERROR Error
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10e7cc83e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10e81c046 -[TNSRuntimeInspector reportFatalError:]
3   0x10e0ec64b TNSInspectorUncaughtExceptionHandler
4   0x7fff23e3d36d __handleUncaughtException
5   0x7fff50ba8c05 _objc_terminate()
6   0x7fff4f9f6c87 std::__terminate(void (*)())
7   0x7fff4f9f940b __cxa_get_exception_ptr
8   0x7fff4f9f93d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
9   0x7fff50ba8ad6 _objc_exception_destructor(void*)
10  0x10e7ccd7f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10e81e6c4 -[TNSRuntime executeModule:referredBy:]
12  0x10e0ea1c3 main
13  0x7fff51a231fd start
14  0x1
JavaScript stack trace:
JavaScript error:
JS ERROR Error: NativeScript encountered a fatal error: Error
at
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file:///app/bundle.js:144:65
at ./app.ts(file:///app/bundle.js:160:34)
at __webpack_require__(file: app/webpack/bootstrap:750:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
NativeScript caught signal 6.
Native Stack:
1   0x10e81d321 sig_handler(int)
2   0x7fff51c005fd _sigtramp
3   0x7fff51af4f39 itoa64
4   0x7fff51af0b7c abort
5   0x7fff4f9f7858 abort_message
6   0x7fff4f9f6cad std::__terminate(void (*)())
7   0x7fff4f9f940b __cxa_get_exception_ptr
8   0x7fff4f9f93d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
9   0x7fff50ba8ad6 _objc_exception_destructor(void*)
10  0x10e7ccd7f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10e81e6c4 -[TNSRuntime executeModule:referredBy:]
12  0x10e0ea1c3 main
13  0x7fff51a231fd start
14  0x1
```
</details>

**Comment by dosomder** [comment]
Just tried it with normal ListView (not RadListView). It also works fine there. So I assume it's definitely a RadListView bug.

**Comment by dosomder** [comment]
Looks like I have to create a custom override of the `MarqueeLabel` to support padidng, as done with TNSLabel. I see I can add custom code in a project in App_Platforms folder: https://docs.nativescript.org/guides/ios-source-code

Is this also possible in a plugin?
