### ISSUE TITLE
Cannot use LinearLayout or ImageView in the splash_screen.xml file on android

### ISSUE THREAD

**Issue by NicoTune** [NativeScript/NativeScript#8740]
Hello, 
when trying to make a splash screen that uses anything other than <layer-list> and <bitmap> the app app crashes at runtime.

splash_screen.xml:
```
<LinearLayout  xmlns:android="http://schemas.android.com/apk/res/android" android:gravity="fill" android:background="@drawable/background">
  <ImageView
    android:scaleType="center"
    android:src="@drawable/logo"
    android:adjustViewBounds="true"
  />
</LinearLayout>
```
Could someone either point me to what I should be doing to make it work, or clarify whether this is a bug? I understand in regular android, you would extend the activity to use the layout. 

I also just dont quite get why layer-list would work out of the box when LinearLayout doesnt.

Here's the error log I'm getting:

```

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{dk.myapp.fr.things/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: android.content.res.Resources$NotFoundException: Drawable dk.myapp.fr.things:drawable/splash_screen with resource ID #0x7f08009b
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.myapp.fr.things/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: android.content.res.Resources$NotFoundException: Drawable dk.myapp.fr.things:drawable/splash_screen with resource ID #0x7f08009b
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6863)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: android.content.res.Resources$NotFoundException: Drawable dk.myapp.fr.things:drawable/splash_screen with resource ID #0x7f08009b
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7149)
System.err:     at android.app.Activity.performCreate(Activity.java:7140)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
System.err:     ... 11 more
System.err: Caused by: android.content.res.Resources$NotFoundException: Drawable dk.myapp.fr.things:drawable/splash_screen with resource ID #0x7f08009b
System.err: Caused by: android.content.res.Resources$NotFoundException: File res/drawable-nodpi-v4/splash_screen.xml from drawable resource ID #0x7f08009b
System.err:     at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:859)
System.err:     at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:643)
System.err:     at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
System.err:     at android.content.res.Resources.getDrawable(Resources.java:827)
System.err:     at android.content.Context.getDrawable(Context.java:626)
System.err:     at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
System.err:     at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
System.err:     at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:260)
System.err:     at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
System.err:     at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
System.err:     at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7149)
System.err:     at android.app.Activity.performCreate(Activity.java:7140)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6863)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: android.view.InflateException: Class not found LinearLayout
System.err:     at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:222)
System.err:     at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:139)
System.err:     at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
System.err:     at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
System.err:     at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:845)
System.err:     ... 33 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "LinearLayout" on path: DexPathList[[zip file "/data/app/dk.myapp.fr.things-Fw4HgYj4IP7WbX2-tnQ4yw==/base.apk"],nativeLibraryDirectories=[/data/app/dk.myapp.fr.things-Fw4HgYj4IP7Wb
X2-tnQ4yw==/lib/arm64, /data/app/dk.myapp.fr.things-Fw4HgYj4IP7WbX2-tnQ4yw==/base.apk!/lib/arm64-v8a, /system/lib64]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:203)
System.err:     ... 37 more

```

**Comment by Ross-Olivares** [comment]
Hi @NicoTune 
Thank you for reporting this issue.
We are going to try replicate this case on our end. Let me know if you can send us a sample project that can reproduce the issue.

**Comment by NicoTune** [comment]
Unfortunatly I am out of time as I'm going on vacation for a month, so i will only be able to reply at the start of September. Hopefully we can continue this issue then :)

**Comment by mdckiller** [comment]
Any update?

**Comment by anaitslimane** [comment]
I have exactly the same issue, for the same purpose 'splashscreen'

I've tried with a simple text 'TextView', same error
