### ISSUE TITLE
Xcode 12 beta 3: JS ERROR ReferenceError: Can't find variable: NSString on @nativescript/core

### ISSUE THREAD

**Issue by tdhman** [NativeScript/NativeScript#8741]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.4
 - Cross-platform modules: 6.5.12
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.2
 - Plugin(s): @nativescript/core/utils

**Describe the bug**

NativeScript iOS application built by XCode 12 beta 3 for device has exception error that `NSString` cannot be found. With the same project, if build and run on iOS simulator, there is no issue.

```
file:///app/vendor.js:50656:30: JS ERROR ReferenceError: Can't find variable: NSString
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: NSString
 at 
file:///app/vendor.js:50656:30
at ../node_modules/@nativescript/core/utils/native-helper.js(file:///app/vendor.js:50760:3)
at __webpack_require__(file:///app/runtime.js:75:34)
at ../node_modules/@nativescript/core/utils/utils.js(file:///app/vendor.js:51171:42)
at __webpack_require__(file:///app/runtime.js:75:34)
at ../node_modules/@nativescript/core/file-system/file-system-access.js(file:///app/vendor.js:7464:34)
at __webpack_require__(file:///app/runtime.js:75:34)
at ../node_modules/@nativescript/core/file-system/file-system.js(file:///app/vendor.js:7924:47)
at __webpack_require__(file:///app/runtime.js:75:34)
at ../node_modules/@nativescript/core/utils/debug.js(file:///app/vendor.js:50310:40)
at __webpack_require__(file:///app/runtime.js:75:34)
at file:///app/vendor.js:18469:34
at ../node_modules/@nativescript/core/ui/builder/builder.js(file:///app/vendor.js:19160:34)
at __webpack_require__(file:///app/runtime.js:75:34)
at file:///app/vendor.js:467:36
at ../node_modules/@nativescript/core/application/application.js(file:///app/vendor.js:1025:34)
at __webpack_require__(file:///app/runtime.js:75:34)
at file:///app/bundle.js:8702:105
at ./main.js(file:///app/bundle.js:9751:34)
```

**To Reproduce**
Create a nativescript-vue template project, then import the module "@nativescript/core/utils" in the project. 
Build and run the project on iOS device, when the application started, it throws the above error.
Build and run the project on simulator, there is no issue.

**Expected behavior**
When build and run on iOS device, there should be no issue as on iOS simulator

Thanks a lot for help.

**Comment by Ross-Olivares** [comment]
Hi @tdhman 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by tdhman** [comment]
@Ross-Olivares Thanks a lot.
FYI, I also tested on Xcode 11/Xcode 12 beta 1 and everything works fine. Only on Xcode 12 beta 3 that I have encountered this issue when built and run the application for iOS device.

**Comment by triniwiz** [comment]
@tdhman can you try it with the `beta-v8` runtime ?

**Comment by nickykln** [comment]
Hello guys, 
I am facing the same issue 👍, even if I'm using the Angular and not Vue.

@tdhman, did you finally find a solution ? 

Thanks a lot for your help

**Comment by nickykln** [comment]
Hello @triniwiz 
Thank you for the quick answer.
I have change the tns-version to 7.0.0-beta.3-v8-2020-07-01-222820-05 (tns platform add ios@beta-v8)

But I have the same behaviour, working on the emulator and not on a real device 

I have the following error (On the real device)
'NativeScript encountered a fatal error: Uncaught ReferenceError: UIDevice is not defined

I guess it is related to a plugin i am using but it looks strange because this object still exists on IOS 14 and has not changed. 

Let me know if you need additional information. 

Thank you very much.

Nicolas

**Comment by tdhman** [comment]
@nickykln I have resolved the issue by adding header search path for tns-core-modules and tns widget framework into the project config, for example:

```
FRAMEWORK_SEARCH_PATHS = $(inherited) $(PODS_FRAMEWORK_SEARCH_PATHS) "$(SRCROOT)/../../node_modules/tns-core-modules-widgets/platforms/ios"
HEADER_SEARCH_PATHS = $(inherited) $(PODS_HEADER_SEARCH_PATHS) "$SRCROOT/internal/Swift-Modules" "$(SRCROOT)/internal" "$(SRCROOT)/../../app/App_Resources/iOS/src" "$(SRCROOT)/../../node_modules/@nativescript/core/platforms/ios/src" "$(SRCROOT)/../../node_modules/tns-core-modules-widgets/platforms/ios/src"
```

**Comment by kl4n4** [comment]
hello, is anyone still running into this issue? 
We now got the same error and for me it seems to be related to #8867 and #8665
and unfortunately (at least for us) the suggested workaround suggested by @tdhman did not work

**Comment by darkyelox** [comment]
Having the same problem only when running on device, using latest nativescript 7.0.10 and ios runtinme 7.0.1:

 ```
NativeScript encountered a fatal error: Uncaught ReferenceError: NSString is not defined
 at 
	(file:///app/vendor.js:145190:36)
	at ../node_modules/@nativescript/core/utils/native-helper.js(file:///app/vendor.js:145278:3)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/utils/index.js(file:///app/vendor.js:144875:72)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/file-system/file-system-access.js(file:///app/vendor.js:106536:64)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/file-system/index.js(file:///app/vendor.js:106956:77)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/utils/debug.js(file:///app/vendor.js:144799:70)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:116669:70)
	at ../node_modules/@nativescript/core/ui/builder/index.js(file:///app/vendor.js:117242:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:100192:69)
	at ../node_modules/@nativescript/core/application/index.js(file:///app/vendor.js:100650:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/index.js(file:///app/vendor.js:108809:70)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:94556:76)
	at ../node_modules/@nativescript/angular/__ivy_ngcc__/fesm2015/nativescript-angular.js(file:///app/vendor.js:99796:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ./main.ts(file:///app/bundle.js:6563:79)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at checkDeferredModules(file:///app/runtime.js:44:23)
	at webpackJsonpCallback(file:///app/runtime.js:31:19)
	at (file:///app/bundle.js:2:57)
	at require(:1:137)
2020-10-05 13:39:26.125291-0500 ondago[476:13278] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: NSString is not defined
 at 
	(file:///app/vendor.js:145190:36)
	at ../node_modules/@nativescript/core/utils/native-helper.js(file:///app/vendor.js:145278:3)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/utils/index.js(file:///app/vendor.js:144875:72)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/file-system/file-system-access.js(file:///app/vendor.js:106536:64)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/file-system/index.js(file:///app/vendor.js:106956:77)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/utils/debug.js(file:///app/vendor.js:144799:70)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:116669:70)
	at ../node_modules/@nativescript/core/ui/builder/index.js(file:///app/vendor.js:117242:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:100192:69)
	at ../node_modules/@nativescript/core/application/index.js(file:///app/vendor.js:100650:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/index.js(file:///app/vendor.js:108809:70)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:94556:76)
	at ../node_modules/@nativescript/angular/__ivy_ngcc__/fesm2015/nativescript-angular.js(file:///app/vendor.js:99796:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ./main.ts(file:///app/bundle.js:6563:79)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at checkDeferredModules(file:///app/runtime.js:44:23)
	at webpackJsonpCallback(file:///app/runtime.js:31:19)
	at (file:///app/bundle.js:2:57)
	at require(:1:137)
', reason: '(null)'
*** First throw call stack:
(0x1d0d0f180 0x1cfee79f8 0x101d4d428 0x1020fe4f0 0x1020fe354 0x10201308c 0x101f48828 0x101f47e60 0x101dc2e18 0x101d01df0 0x101cfcab0 0x101d42508 0x100fbbe5c 0x1d075e8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: NSString is not defined
 at 
	(file:///app/vendor.js:145190:36)
	at ../node_modules/@nativescript/core/utils/native-helper.js(file:///app/vendor.js:145278:3)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/utils/index.js(file:///app/vendor.js:144875:72)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/file-system/file-system-access.js(file:///app/vendor.js:106536:64)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/file-system/index.js(file:///app/vendor.js:106956:77)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/utils/debug.js(file:///app/vendor.js:144799:70)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:116669:70)
	at ../node_modules/@nativescript/core/ui/builder/index.js(file:///app/vendor.js:117242:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:100192:69)
	at ../node_modules/@nativescript/core/application/index.js(file:///app/vendor.js:100650:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/@nativescript/core/index.js(file:///app/vendor.js:108809:70)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at (file:///app/vendor.js:94556:76)
	at ../node_modules/@nativescript/angular/__ivy_ngcc__/fesm2015/nativescript-angular.js(file:///app/vendor.js:99796:30)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ./main.ts(file:///app/bundle.js:6563:79)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at checkDeferredModules(file:///app/runtime.js:44:23)
	at webpackJsonpCallback(file:///app/runtime.js:31:19)
	at (file:///app/bundle.js:2:57)
	at require(:1:137)
', reason: '(null)'
```

**Comment by mat1th** [comment]
HI @NathanWalker, I do have the same issue as described here. And while debugging I've found the direction of the issue. 

When building for a simulator (`x86_64`) It all works fine for me. But when building for a real device it does not work. 
For a simulator It creates a `2mb` `metadata-*.bin` file but for a real device it is only `127kb`. And I can also not find `NSString` when I run `strings` on the `metadata-*.bin`. So the generation of the metadata is failing for `arm64`.

In the `metadata-generation-*-logs.txt` It gives the following error:
```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:11:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found
#import <Foundation/NSURLHandle.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

It does not exist in `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/`. But why is it searching for it? It does include it for the MacOS target. When I comment out  everything in `Foundation.framework/Headers/Foundation.h` between `#if TARGET_OS_OSX` and `#endif` the metadata generator does generate more metadata. It is now `1mb`. It does now fail on the next module that is including macos headers. 

When I start the app, it does not fail on `NSString` but on `UIDevice`.

**Possible solution:** 
- Filter out imports between macos macro's.

**Context:** 
- Xcode 12.2 beta + - Xcode 12.1.
- Real Iphone

**Comment by mat1th** [comment]
It goes wrong when you set `CLANG_ENABLE_MODULES` in the `build.xcconfig`. When you disable it. (And also do not have other frameworks enabling it. The metadata is generated correctly;

**Comment by noordw** [comment]
We had the same problem, because we were using blacklists. 

AppResources/ios/nativescript-api-usage.json
ie.
{
    "whitelist-plugins-usages": true,
    
    "blacklist": [
      "HealthKit.*:*",
      "HomeKit.*:*"
   ]
}

We had to add a whitelist to it
{
    "whitelist-plugins-usages": true,
    "whitelist" :["*:*"],
    "blacklist": [
      "HealthKit.*:*",
      "HomeKit.*:*"
   ]
}
