### ISSUE TITLE
iOS crash after a few page changes

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8745]
**Environment**
 - CLI: 6.8.0
 - Cross-platform modules: 6.1.2
 - iOS Runtime: 6.1.0
 - Plugin(s):

**Describe the bug**
I have built an app based on side bar template. After a few time of page changes, app get crashed (running on emulator) with the following errors:

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x106a6124e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x106a9d878 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x1074443d6 ffi_closure_unix64_inner
4   0x107444dfa ffi_closure_unix64
5   0x7fff23da2414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
6   0x7fff23da20ae __CFRunLoopDoTimer
7   0x7fff23da170a __CFRunLoopDoTimers
8   0x7fff23d9c35e __CFRunLoopRun
9   0x7fff23d9b8a4 CFRunLoopRunSpecific
10  0x7fff38c39bbe GSEventRunModal
11  0x7fff49325968 UIApplicationMain
12  0x107444c3d ffi_call_unix64
13  0x10d72ee90
JavaScript stack trace:
_getNativeAnimationArguments(file: node_modules/tns-core-modules/ui/animation/animation.ios.js:240:0)
at file: node_modules/tns-core-modules/ui/animation/animation.ios.js:204:0
at play(file: node_modules/tns-core-modules/ui/animation/animation.ios.js:173:0)
at animate(file: node_modules/tns-core-modules/ui/animation/keyframe-animation.js:208:0)
at file: node_modules/tns-core-modules/ui/animation/keyframe-animation.js:180:36
at runTask(file: node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:188:0)
at invokeTask(file: node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:496:0)
at timer(file: node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:1561:0)
at invoke(file: node_modules/tns-core-modules/timer/timer.ios.js:54:30)
at runGuarded(file: node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:151:0)
at tick(file: node_modules/tns-core-modules/timer/timer.ios.js:18:0)
at UIApplicationMain([native code])
at _start(file: node_modules/tns-core-modules/application/application.ios.js:295:0)
at run(file: node_modules/tns-core-modules/application/application.ios.js:323:0)
at bootstrapNativeScriptApp(file: node_modules/nativescript-angular/platform-common.js:210:0)
at bootstrapApp(file: node_modules/nativescript-angular/platform-common.js:111:0)
at bootstrapModule(file: node_modules/nativescript-angular/platform-common.js:91:0)
at file:///app/bundle.js:508:144
at ./main.ts(file:///app/bundle.js:513:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///a<…>
JavaScript error:
file: node_modules/tns-core-modules/ui/animation/animation.ios.js:240:0: JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x106a6124e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x106aad08c -[TNSRuntime executeModule:referredBy:]
3   0x106375303 main
4   0x7fff520ce1fd start
JavaScript stack trace:
UIApplicationMain(file: node_modules/tns-core-modules/application/application.ios.js:295:0)
at _start(file: node_modules/tns-core-modules/application/application.ios.js:295:0)
at run(file: node_modules/tns-core-modules/application/application.ios.js:323:0)
at bootstrapNativeScriptApp(file: node_modules/nativescript-angular/platform-common.js:210:0)
at bootstrapApp(file: node_modules/nativescript-angular/platform-common.js:111:0)
at bootstrapModule(file: node_modules/nativescript-angular/platform-common.js:91:0)
at file:///app/bundle.js:508:144
at ./main.ts(file:///app/bundle.js:513:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/tns-core-modules/application/application.ios.js:295:0: JS ERROR Error
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error
at
UIApplicationMain(file: node_modules/tns-core-modules/application/application.ios.js:295:0)
at _start(file: node_modules/tns-core-modules/application/application.ios.js:295:0)
at run(file: node_modules/tns-core-modules/application/application.ios.js:323:0)
at bootstrapNativeScriptApp(file: node_modules/nativescript-angular/platform-common.js:210:0)
at bootstrapApp(file: node_modules/nativescript-angular/platform-common.js:111:0)
at bootstrapModule(file: node_modules/nativescript-angular/platform-common.js:91:0)
at file:///app/bundle.js:508:144
at ./main.ts(file:///app/bundle.js:513:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
2   NativeScript     <…>
NativeScript caught signal 6.
Native Stack:
1   0x106aabba1 sig_handler(int)
2   0x7fff522ab5fd _sigtramp
3   0x7fff5219ff39 itoa64
4   0x7fff5219bb7c abort
5   0x7fff500a2858 abort_message
6   0x7fff50093cbf demangling_unexpected_handler()
7   0x7fff51253c0b _objc_terminate()
8   0x7fff500a1c87 std::__terminate(void (*)())
9   0x7fff500a440b __cxa_get_exception_ptr
10  0x7fff500a43d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff51253ad6 _objc_exception_destructor(void*)
12  0x106a616cf NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x106aad08c -[TNSRuntime executeModule:referredBy:]
14  0x106375303 main
15  0x7fff520ce1fd start
JS Stack:
```

**Comment by vahidvdn** [comment]
It seems the issue happens due to animations. I removed all animations and there is no crash anymore. Any idea?

**Comment by NathanWalker** [comment]
Yes that error is typical of an animation executing against a view that has been destroyed which can happen if not properly managed internally in the app while user is navigating. Using css animations or manual? And can provide a sample of the animation code wise and how/when you’re triggering it?

**Comment by vahidvdn** [comment]
@NathanWalker 
I'm using animations as following:

```xml
<StackLayout [@scale-in] class="login-container">
```

And in component.ts:

```typescript
@Component({
    selector: "Search",
    templateUrl: "./login.component.html",
    animations: [
        trigger("scale-in", [
            transition(':enter', [
              style({transform: 'scale(0.85)', opacity: 0}),
              animate('800ms', style({transform: 'scale(1)', opacity: 1}))
            ]),
            transition(':leave', [
              style({transform: 'scale(1)', opacity: 1}),
              animate('800ms', style({transform: 'scale(0.85)', opacity: 0}))
            ])
        ])
    ]
})
```
