### ISSUE TITLE
Navigation in Tabs view broken when setting css class (font-family) to Label in TabStripItem

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#8768]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

nativescript has 6.8.0 version and is up to date.
tns-core-modules has 6.5.15 version and is up to date.
tns-android has 6.5.3 version and is up to date.
tns-ios has 6.5.2 version and is up to date.
"nativescript-angular": "^8.21.0",

**Describe the bug**
I have three pages. Pages  /main, /tabs, and /diary. I have a page-router-outlet in main for standard forward navigation. On the Tabs page I have a tabs control. I try to use forward navigation from main -> tabs ->diary.
When I navigate away from the tabs page via 

this.router.navigate(['/diary'], { transition: { name: 'flipRight' }, clearHistory: true });

the app breaks on IOS. It prints the attached error message. Please note, there seems to be two things broken. If I use clearHistory=false, or I do not set the transition explicitely, the navigation does not break the app ios. Hence it seems like the broken navigation results from the combination of setting the transition explicetly and using clear history.

Second bug: In case I set clear history to false, I observe, that the applied transition does not work correctly. The situation is the same on ios and android.
 

''''
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10d31162e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10d3523a8 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10dd4dc90 ffi_closure_unix64_inner
4   0x10dd4e6b2 ffi_closure_unix64
5   0x7fff2b4e9260 -[CALayer layoutSublayers]
6   0x7fff2b4ef3eb CA::Layer::layout_if_needed(CA::Transaction*)
7   0x7fff2b4faa8a CA::Layer::layout_and_display_if_needed(CA::Transaction*)
8   0x7fff2b443a7c CA::Context::commit_transaction(CA::Transaction*, double)
9   0x7fff2b477467 CA::Transaction::commit()
10  0x7fff2b3a4305 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
11  0x7fff2b47b768 display_timer_callback(__CFMachPort*, void*, long, void*)
12  0x7fff23d627dd __CFMachPortPerform
13  0x7fff23da2449 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
14  0x7fff23da1a48 __CFRunLoopDoSource1
15  0x7fff23d9c474 __CFRunLoopRun
16  0x7fff23d9b8a4 CFRunLoopRunSpecific
17  0x7fff38c39bbe GSEventRunModal
18  0x7fff49325968 UIApplicationMain
19  0x10dd4e4f5 ffi_call_unix64
20  0x11ede55d0
JavaScript stack trace:
file: node_modules/@nativescript/core/ui/tabs/tabs.ios.js:139:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:17205:175
at ./main.ts(file:///app/bundle.js:17210:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/ui/tabs/tabs.ios.js:139:0: JS ERROR TypeError: null is not an object (evaluating 'this.tabBar.frame')
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10d31162e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10d363524 -[TNSRuntime executeModule:referredBy:]
3   0x10bf7b4d3 main
4   0x7fff520ce1fd start
JavaScript stack trace:
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:17205:175
at ./main.ts(file:///app/bundle.js:17210:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/application/application.ios.js:312:0: JS ERROR Error
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10d31162e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10d360e66 -[TNSRuntimeInspector reportFatalError:]
3   0x10bf7d95b TNSInspectorUncaughtExceptionHandler
4   0x7fff23e3e2cd __handleUncaughtException
5   0x7fff51253c05 _objc_terminate()
6   0x10e6065f6 CLSTerminateHandler()
7   0x7fff500a1c87 std::__terminate(void (*)())
8   0x7fff500a440b __cxa_get_exception_ptr
9   0x7fff500a43d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
10  0x7fff51253ad6 _objc_exception_destructor(void*)
11  0x10d311b6f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
12  0x10d363524 -[TNSRuntime executeModule:referredBy:]
13  0x10bf7b4d3 main
14  0x7fff520ce1fd start
JavaScript stack trace:
JavaScript error:
JS ERROR Error: NativeScript encountered a fatal error: Error
at
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:17205:175
at ./main.ts(file:///app/bundle.js:17210:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
'''

**Comment by cjohn001** [comment]
I would like to mention, that I found a workaround that at least works on the ios simulator ( testing on devices and android I will do tomorrow and will post an update)

When using the following code the app does not crash. Hence when using setTimeout. Before the workaround I directly called the navigate event from inside a tap handler on a button control. I do not understand why the tab crashes in case I call navigate directly. But I hope that this workaround also does the job on real devices.

setTimeout(() => {this.router.navigate(['/diary'], { transition: { name: 'flipRight' }, clearHistory: true });}, 10);

**Comment by cjohn001** [comment]
I finally found my problem. Unfortunately, I were not able to replicate the issue on NS Playground. I will therefore close the issue.
My problem was the following.  I used a custom font on the TabStripItem label

 <TabStripItem>
                <Label text="Tab B" class="tabStripLabel"></Label>
  </TabStripItem>


.tabStripLabel {
	font-family: '72', '72-Regular';
}

This was leading to the broken navigation.
