### ISSUE TITLE
Error on language change on android

### ISSUE THREAD

**Issue by benco8186** [NativeScript/NativeScript#8784]
Environment : 
"dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@nativescript/angular": "~10.0.0",
    "@nativescript/core": "rc",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "core-js": "^2.6.9",
    "nativescript-feedback": "^1.5.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.5",
    "tslib": "1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.6",
    "@angular/cli": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/webpack": "~2.0.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-sass": "^4.7.1",
    "protractor": "~5.4.3",
    "tns-platform-declarations": "^6.5.15",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.0"
  }

When I change a language on android (with tns run android) this error happens 👍 

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.gameswitch/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Could not find a page for fragment0[0].
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.gameswitch/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Could not find a page for fragment0[0].
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2977)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114)
System.err:     at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4888)
System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4797)
System.err:     at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:201)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6831)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Could not find a page for fragment0[0].
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:21)
System.err:     at android.app.Activity.performCreate(Activity.java:7224)
System.err:     at android.app.Activity.performCreate(Activity.java:7213)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
System.err:     ... 13 more

**Comment by Ross-Olivares** [comment]
Hi @benco8186 
Thank you for reporting this issue.
We are going to try replicate this case on our end. Let me know if you can send us a sample project or playground link so we can reproduce the issue.

**Comment by benco8186** [comment]
> Hi @benco8186
> Thank you for reporting this issue.
> We are going to try replicate this case on our end. Let me know if you can send us a sample project or playground link so we can reproduce the issue.

I don't know if you have changed anything, but it works now (I have changed my computer recently also maybe it is that). I have a question, is it possible to change dynamically the language in the app when the user change the language in the device settings ? I have tried with the resumeEvent and it doesn't work :(

**Comment by luiguild** [comment]
I'm facing exactly the same problem, the application runs perfectly, you can resume and suspend normally, but when you go to the Android settings, change the language and get back to the app, the nativeView reference was lost and the app crash firing the 'uncaughtErrorEvent'. 

You can reproduce this error in a clean installation.

**Comment by farfromrefug** [comment]
@luiguild this could be fixed in `@nativescript/core` 8.2 alpha versions. Can you try with it?

**Comment by luiguild** [comment]
@farfromrefug according to my package-lock, I'm using:

`"@nativescript/core": {
      "version": "8.1.5",
       ...
`

8.2 still in alpha, right?
