### ISSUE TITLE
 Navigation from Tabs Page with nested page-router-outlets to page with RadListView leads to app crashing on IOS devices (not on simulator)

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#8789]
**Environment**
nativescript has 6.8.0 version.
tns-core-modules has 6.5.15 version
tns-android has 6.5.3
tns-ios 6.5.0 and  6.5.2 tried
"nativescript-ui-listview": "8.2.0" and "8.0.1" tried

**Describe the bug**
Hello together,
I am encountering a bug when navigating from a Tabs view to a page which holds a RadListView, and the navigation transition is of type flipLeft or flipRight. All conditions have to be met at once, and the app in addition has to run on a real IOS device. On emulator things work. Hence, summing up the conditions:

**To Reproduce**
- navigate from Tabs View -> Page with RadListView
- use flipLeft or flipRight transition in navigation
- real IOS device ( note: it might not break on the first transition but after a few tries the crash will appear)

**Expected behavior**
Navigation should work without crashing the app

**Sample project**
Attached I provide a playground example, unfortunately the share button in playground seems to be missing, hence I attached the project as archive to the bug report. If someone tells me how I can share the project via playground I could provide the project there as well.

[NSPlayground.zip](https://github.com/NativeScript/NativeScript/files/5126007/NSPlayground.zip)

How to use the example:
Home screen has two buttons to show working navigation and the bug:

1. Working variant: Button(Navigate to Extern) and on next page use back button on ActionBar, -> Navigation is working as expected

2. Bug variant: On Home screen use Button (Navigate to Tabs) -> On TabA use Button (Navigate to External Page)  -> On External Page use Button (Navigate Back Clear History) to switch back to tabs page. Now repeat switching between TabA page and external page till app crashes. Typically happens after a few tries.

Observations:
The bug seems to be related to the Tabs navigation when using nested page-router-outlets. If I do not use page-router-outlet in the TabContentItems but use the views directly in the tabs page, than the navigation is working. However, this is no solution for me as I than run into a different bug (#8775) with my app that I already have reported.

Final observation, would be great if someone could update nativescript playground to include nativescript-ui-listview 8.2.0.

It would be great if someone could come up and document a workaround for the issue till the bug is solved. The issue messes up the whole navigation logic in my app therfore I consider it quite urgent. The flipLeft, flipRight is quite important for me. Let me know if further explanation is required and if I can help with testing.

**Additional context**
@NathanWalker : I referenced you here as it might be related to #8730

Crash Log:

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105f9a928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105fd502c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x106b427f8 ffi_closure_SYSV_inner
4   0x106b441b4 .Ldo_closure
5   0x1c176b638 <redacted>
6   0x1c176c110 <redacted>
7   0x1c176dafc <redacted>
8   0x1c176c854 <redacted>
9   0x1c1db2c10 <redacted>
10  0x1c1da24ac <redacted>
11  0x1c1dd2990 <redacted>
12  0x1bdc72f2c <redacted>
13  0x1bdc6de20 <redacted>
14  0x1bdc6e29c <redacted>
15  0x1bdc6dba8 CFRunLoopRunSpecific
16  0x1c7ddd344 GSEventRunModal
17  0x1c1da93e4 UIApplicationMain
18  0x106b44044 ffi_call_SYSV
19  0x106b41f1c ffi_call_int
20  0x106b41a18 ffi_call
21  0x105f5d46c NativeScript::FunctionWrapper::call(JSC::ExecState*)
22  0x106b0ecf0 llint_entry
23  0x106b0c108 llint_entry
24  0x106b0c108 llint_entry
25  0x106b0c108 llint_entry
26  0x106b0c108 llint_entry
27  0x106b0c108 llint_entry
28  0x106b0c108 llint_entry
29  0x106b0c108 llint_entry
30  0x106b0c108 llint_entry
31  0x106b0c060 llint_entry
JavaScript stack trace:
file: node_modules/@nativescript/core/ui/frame/frame.ios.js:341:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:18567:175
at ./main.ts(file:///app/bundle.js:18572:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/ui/frame/frame.ios.js:341:0: JS ERROR TypeError: undefined is not an object (evaluating 'this._owner.get')
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105f9a928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105fe2b68 -[TNSRuntimeInspector reportFatalError:]
3   0x1049b2408
4   0x1bdcf595c <redacted>
5   0x1bda17e74 <redacted>
6   0x10720dcb8 CLSTerminateHandler()
7   0x1bdabe14c <redacted>
8   0x1bdac0bd8 __cxa_get_exception_ptr
9   0x1bdac0b98 <redacted>
10  0x1bda17cf8 <redacted>
11  0x105f9ae00 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
12  0x105fd502c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
13  0x106b427f8 ffi_closure_SYSV_inner
14  0x106b441b4 .Ldo_closure
15  0x1c176b638 <redacted>
16  0x1c176c110 <redacted>
17  0x1c176dafc <redacted>
18  0x1c176c854 <redacted>
19  0x1c1db2c10 <redacted>
20  0x1c1da24ac <redacted>
21  0x1c1dd2990 <redacted>
22  0x1bdc72f2c <redacted>
23  0x1bdc6de20 <redacted>
24  0x1bdc6e29c <redacted>
25  0x1bdc6dba8 CFRunLoopRunSpecific
26  0x1c7ddd344 GSEventRunModal
27  0x1c1da93e4 UIApplicationMain
28  0x106b44044 ffi_call_SYSV
29  0x106b41f1c ffi_call_int
30  0x106b41a18 ffi_call
31  0x105f5d46c NativeScript::FunctionWrapper::call(JSC::ExecState*)
JavaScript stack trace:
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:18567:175
at ./main.ts(file:///app/bundle.js:18572:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/application/application.ios.js:312:0: JS ERROR Error: NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'this._owner.get')
at
file: node_modules/@nativescript/core/ui/frame/frame.ios.js:341:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:18567:175
at ./main.ts(file:///app/bundle.js:18572:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
```

**Comment by NathanWalker** [comment]
@cjohn001 try setting animationEnabled=false on your Tabs - see these for more:
https://github.com/NativeScript/NativeScript/pull/8704
https://github.com/NativeScript/NativeScript/issues/8553

**Comment by cjohn001** [comment]
@NathanWalker, I have already set animationEnabled=false. It is also already set in the example project I provided. This helped with the rendering of the radlistview when transitioning to a tabs page with on on it, but it is not related to the navigation bug I am reporting here. From my provided example project :

```
    <Tabs #idTabsView selectedIndex="0" animationEnabled="false"
        iosOverflowSafeArea="false">
```
