### ISSUE TITLE
crypto broken?

### ISSUE THREAD

**Issue by ray007** [NativeScript/NativeScript#8806]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.8.0
 - Cross-platform modules: 6.5.15
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.2
 - Plugin(s):

**Describe the bug**
Trying to use the `http-client-auth` module for digest authentication brought me an error for missing function `crypto.getHash`.
Adding a require for `crypto` or `crypto-browserify` to my code results in a long exception stacktrace at the require point:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'split' of undefined
System.err: File: (file: node_modules\pbkdf2\lib\default-encoding.js:6:47)
System.err:
System.err: StackTrace:
System.err: ../node_modules/pbkdf2/lib/default-encoding.js(file: node_modules\pbkdf2\lib\default-encoding.js:6:47)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/lib/sync.js(file: node_modules\pbkdf2\lib\sync.js:14:22)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/index.js(file: node_modules\pbkdf2\index.js:24:23)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/crypto-browserify/index.js(file: node_modules\crypto-browserify\index.js:14:8)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ./lib/tnsSrvConn.js(file: app\lib\tnsSrvConn.js:4:15)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/MyComponent.vue?vue&type=script&lang=js&(file:///data/data/com.loytec.lweb804/files/app/bundle.js:1352:73)
...
```

**Comment by tarunama** [comment]
@ray007 
You could try to remove node_modules folder for resolving npm package dependency.

**Comment by ray007** [comment]
I removed the `node_modules` folder and reinstalled with `npm install`, I even did a `tns platform clean android`, the problem persists.

**Comment by tarunama** [comment]
@ray007 
Thank you for your try !

You did try below solution ?
https://stackoverflow.com/questions/59424475/problem-migrating-to-a-newer-nativescript

**Comment by ray007** [comment]
@tarunama thanks for helping

About your linked article:
* `tns doctor` didn't show any troubles, but it did tell me about N7.
* The core modules shouldn't be the problem, since the exception only comes with the `crypto` module, right?
* Not sure how to recreate a `webpack.config.js`.
* Already did try the `node_modules` and platform clean
* Don't want to change files from required modules, but adding a `require` for `process` to my own source file did not help

**Comment by ineiti** [comment]
I have the same problem:

- Create a new project with `tns create test`, choosing `typescript` and `hello world`
- Add 
```
import {createHash} from "crypto"; // or "crypto-browserify" - same result
const h = createHash("sha256");
```
to `src/main.ts`
- Run `tns run android`

And I get the same error.

```
$ tns doctor

✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 11.6.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.0 version and is up to date.
```

**Comment by ineiti** [comment]
For what it's worth: nativescript 6.5.0 has the same behaviour - except that you need `crypto-browserify`...

**Comment by ineiti** [comment]
Any update on this? I tried many hours, tried to understand webpack.config.js, but I cannot get my head wrapped around this...

**Comment by ineiti** [comment]
Trying out the above link, I added the following to `node_modules/crypto-browserify/index.js`:
```
process = require('process');
```

But then I get a new error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Object(...) is not a function
System.err: File: (file:///data/data/org.nativescript.mobile/files/app/bundle.js:276:67)
System.err: 
System.err: StackTrace: 
System.err: (file:///data/data/org.nativescript.mobile/files/app/bundle.js:276:68)
System.err: 	at ./main.ts(file:///data/data/org.nativescript.mobile/files/app/bundle.js:299:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err: 	at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err: 	at (file:///data/data/org.nativescript.mobile/files/app/bundle.js:2:57)
System.err: 	at require(:1:266)
System.err: 
```

**Comment by SergeyMell** [comment]
I can confirm that it works.
The integration workflow is as follows
1. Install the package
```
npm i -S crypto
```
2. Broserify it
```
npx browserify -r crypto -s crypto -o src/libs/crypto.js
```
3. Use
```
import {createHash} from '~/libs/crypto';

const h = createHash("sha256");
console.log(h.digest('hex'));
```
Console output:
```
JS: WARNING: Missing strong random number source; using weak randomBytes
JS: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Please, make sure that you browserify and require the browserified library correctly. Please, let me know if this didn't help. In this case, I'd ask you to provide some minimal reproducible example because I used the same environment as yours for the testing.

**Comment by ineiti** [comment]
Hmm - will this work if I import packages that use crypto or crypto-browserify? I currently rely on the following changes to `webpack.config.js`:

```diff
diff --git a/mobile/webpack.config.js b/mobile/webpack.config.js
index bde3a35..6999cb0 100644
--- a/mobile/webpack.config.js
+++ b/mobile/webpack.config.js
@@ -72,6 +72,7 @@ module.exports = env => {
     const alias = env.alias || {};
     alias['~/package.json'] = resolve(projectRoot, 'package.json');
     alias['~'] = appFullPath;
+    alias['randombytes'] = resolve(projectRoot, 'node_modules', 'nativescript-randombytes');
 
     if (hasRootLevelScopedModules) {
         coreModulesPackageName = "@nativescript/core";
@@ -127,6 +128,8 @@ module.exports = env => {
             hashSalt
         },
         resolve: {
+            aliasFields: ["browser"],
+            mainFields: ['browser', 'module', 'main'],
             extensions: [".ts", ".js", ".scss", ".css"],
             // Resolve {N} system modules from @nativescript/core
             modules: [
@@ -265,7 +268,7 @@ module.exports = env => {
                 "global.TNS_WEBPACK": "true",
                 "global.isAndroid": platform === 'android',
                 "global.isIOS": platform === 'ios',
-                "process": "global.process",
+                "process": {browser: true, env: {}},
             }),
             // Remove all files from the out dir.
             new CleanWebpackPlugin({ 
```

**Comment by SergeyMell** [comment]
Very interesting solution. I need to research this because I'm not familiar with this approach.
In my case, you'll need to browserify each library you include which may lead to some dependencies duplication.

**Comment by ineiti** [comment]
> I'm not familiar with this approach.

I wasn't, either, 1 month ago ;)

`<rant>`But now it fails when I try to use iOS, so I think I had enough of it. I have a big application (big for me, anyways), but I took now longer to port nativescript-5 to nativescript-7 than it would take me to re-implement the basic functionality in a new framework like Flutter, even counting adding some library stuff. So I think I call it a day on nativescript / javascript for mobile development. After having invested 2 years of my life in it, I think it's time to go and see some other people ;)`</rant>`

**Comment by SergeyMell** [comment]
Sorry to hear that. I've implemented several crypto wallets on {N}5 and {N}6 versions using browserify approach and they successfully work in production. Moving to {N}7 may give some headache especially we have iOS14 updates at the same time but it's not too overcomplicated I think. In any case, good luck in your undertakings.

**Comment by SergeyMell** [comment]
Well then, finally I managed to investigate and prepare a correct (Hopefully, I think so) solution for `crypto` related libraries.
Inspired with [this StackOverflow answer](https://stackoverflow.com/questions/53172766/how-to-use-ripple-lib-with-nativescript) and some researches.

1. I use `crypto-browserify` npm package as a substitutor for the native node `crypto` module. However, firstly we need to browserify it as a standalone in order to eliminate browser dependencies. So, the first steps
   ```
   $ npm i -S crypto-browserify
   $ npx browserify -r crypto-browserify -s crypto-browserify -o src/shims/crypto-browserify.js
   ```
2. After that, adjust your `webpack.config.js` file to use this package instead of native one
   Add it to webpack.config.js in plugins configuration:
   ```
   plugins: [
     ..., // other plugins
     new webpack.ProvidePlugin({
           crypto: resolve(__dirname, 'src/shims/crypto-browserify.js')
       })
   ]
   ```
   Add resolve.alias for our version of `crypto` in `webpack.config.js`, so child dependencies require our `crypto` implementation:
   ```
   alias: {
     ..., // Other aliases
     'crypto': resolve(__dirname, 'src/shims/crypto-browserify.js'),
   }
   ```
3. Should work. However, I'd advise to clean your `node_modules`, `hooks`, and `platforms` and restart the application

**Comment by keithoys** [comment]
Hello @SergeyMell How does one use `crypto` from the solution you shared above? Do we do a require / import?

**Comment by ineiti** [comment]
There is some work on the old NativeScript6 described here - perhaps it's useful:

https://github.com/c4dt/crypto-ts

**Comment by ray007** [comment]
There's a module `crypto-browserify`, which of course still requires fallback registration in webpack config.

**Comment by keithoys** [comment]
Managed to get `crypto-js` v3.3.0 working in Nativescript-vue. Check this out: https://stackoverflow.com/questions/41038425/how-to-use-cryptojs-with-angular-2-and-typescript-in-webpack-build-environment#comment121305953_50443707

![2021-08-04 at 11 22 AM](https://user-images.githubusercontent.com/7553961/128117124-4da0ab70-b67d-457b-bf09-b1f26a8b2d3a.png)

**Comment by ineiti** [comment]
@keithoys But will this work with packages that depend on `crypto`? My problem was that I had a dependency on a package that uses `crypto`, and as such it was difficult to get running. Also, some parts will require a good random-number generator (which is not needed for DES). Is this the case with cryotp-js?

**Comment by anarnoli** [comment]
I'm trying to use `crypto` for `publicEncrypt` and `privateDecrypt` methods in NS 8. I followed @SergeyMell initial suggestion and it didn't worked for me.

@ineiti @SergeyMell - can you please guide on this?

Here is the simple snippet:

`public encryptStringWithRsaPublicKey(data: string, publicKey: string): string {
    const buffer = Buffer.from(data);
    var encrypted = publicEncrypt(publicKey, data);
    return encrypted.toString('Base64');
  }`

Here is the error

`
CONSOLE ERROR: ERROR Error: Uncaught (in promise): Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
at oldBrowser (file: src/webpack:/nativescript-samples/src/libs/crypto.js:24726:0)
at oaep (file: src/webpack:/nativescript-samples/src/libs/crypto.js:24651:0)
at publicEncrypt (file: src/webpack:/nativescript-samples/src/libs/crypto.js:24622:0)
`

**Comment by ineiti** [comment]
@anarnoli in my proposition you find how to set up ns so it uses the correct random-number generator for the project:

https://github.com/c4dt/crypto-ts/commit/b0242974fecda85a720d16e8c627fad3a896e76f#diff-69e8392bf726e5a547677aded8920fef111ed85ccdbb8f5b76f17a0c247728a5

But it only works for ns-6. I never ported it to ns-8, as the project has been deprecated.

**Comment by anarnoli** [comment]
Thanks @ineiti. I'm not sure if NS 8 has inbuilt Crypto support or not. If not then I think it should have.
