### ISSUE TITLE
tns preview ERROR in nativescript.config.ts:1:10 - error TS2305: Module '"HelloWorld/node_modules/@nativescript/core"' has no exported member 'NativeScriptConfig'.

### ISSUE THREAD

**Issue by Rafael-Anier** [NativeScript/NativeScript#8807]
**Environment**
Windows 10
Node v12.18.3
√ Component nativescript has 7.0.3 version and is up to date.
√ Component tns-core-modules has 6.5.16 version and is up to date.    
× Component @nativescript/ios is not installed.
√ Component @nativescript/android has 7.0.0 version and is up to date.

**Describe the bug**
tns preview produces this error:

ERROR in nativescript.config.ts:1:10 - error TS2305: Module '"HelloWorld/node_modules/@nativescript/core"' has no exported member 'NativeScriptConfig'.

**To Reproduce**
tns create HelloWorld --template tns-template-blank-ng
cd HelloWorld 
tns preview 
(scan code from phone)

**Comment by Ross-Olivares** [comment]
Hi @Rafael-Anier ,
Thank you for reporting this issue.
You could try to follow the below-attached steps and to verify, whether the problem will exist after the changes.

1) delete node_modules, platforms, hooks folders from the project.
2) clean npm cache with npm cache clean
3) delete the project from the simulator (if checking on simulator)
4) build it again with tns run android/ios
5) tns preview

If the problem persists please send us the whole project, which will allow us to debug it locally.
Let me know, how it goes.

**Comment by edsoft17** [comment]
Hello I have the same problem as Rafael-Anier :(

**Comment by rigor789** [comment]
If you can't upgrade your `tns-core-modules` or `@nativescript/core` remove the import from the config and remove the `as NativeScriptConfig` part - that should still work fine, but you will lose autocompletion for the configuration properties.

**Comment by Rafael-Anier** [comment]
Hi.
I Tried the Ross-Olivares method and the problem still remains.
I uploaded the code to:
https://github.com/Rafael-Anier/HellloWorld

Thanks a lot and kind regards.
Rafa

**Comment by rigor789** [comment]
@Rafael-Anier have you tried my suggestions?

**Comment by Rafael-Anier** [comment]
Hi @rigor789 
I don`t know how to do any of your suggestions. ¿can you guide me to do it?

Thanks a lot and kind regards.
Rafa

**Comment by rigor789** [comment]
@Rafael-Anier nothing more than removing the lines I mentioned:
```diff
-import { NativeScriptConfig } from '@nativescript/core'

-export default {
+module.exports = {
  id: 'org.nativescript.app',
  appPath: 'app',
  appResourcesPath: 'app_resources',
  android: {
    v8Flags: '--expose_gc',
    markingMode: 'none',
  },
-} as NativeScriptConfig
+}
```

**Comment by Rafael-Anier** [comment]
Hi Rigor, i tried and raise another error, thanks for your assistance, but i think that by the moment this platform is too avanced for my skills, i'm going to return to my old Android Platform and maybe try it in another moment.

Thanks a lot and kind regards.
Rafael Reina

**Comment by rigor789** [comment]
@Rafael-Anier no worries!

**Comment by KyleMoran138** [comment]
I'm also seeing this issue.
@rigor789 is there a commit to make those commented changes from the tns-template-blank-ng template?

**Comment by leblancmeneses** [comment]
There seems to be a dependency issue with the template.

```
npx tns create HelloWorld --template tns-template-blank-ng
cd HelloWorld
npm install --save-dev nativescript
npm install
npx tns run android --device Pixel_3_XL_API_30



Using tns-android v6.5.0 which requires nsconfig.json to be present.
Writing nsconfig.json based on the values set in nativescript.config.(js|ts).
You may add nsconfig.json to .gitignore as the CLI will regenerate it as necessary.

File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: f03c085e787ac44c3d02
Version: webpack 4.27.1
Time: 8586ms
Built at: 09/14/2020 11:50:48 AM
 3 assets
Entrypoint bundle = runtime.js vendor.js bundle.js
[./app.css] 1.18 KiB {bundle} [built]
[./main.ts] 1.16 KiB {bundle} [built]
[~/package.json] external "~/package.json" 42 bytes {bundle} [optional] [built]
    + 373 hidden modules

ERROR in nativescript.config.ts:1:10 - error TS2305: Module '"./node_modules/@nativescript/core"' has no exported member 'NativeScriptConfig'.

1 import { NativeScriptConfig } from '@nativescript/core';

```

I modified as mentioned in comment https://github.com/NativeScript/NativeScript/issues/8807#issuecomment-689050881

Results in
```
The current application is not compatible with NativeScript CLI 7.0.

Run 'ns migrate' to migrate your project to NativeScript 7.

Alternatively you may try running it with '--force' to skip this check.
```

after running

```
:~/repos/bitbucket/trash-nativescript/HelloWorld$ npx ns migrate --force
⚠ Not in Git repo, but using --force
✔ Pre-Migration verification complete
✔ Project files have been backed up
✔ Cleaned directory hooks
ℹ Skipping platforms because it doesn't exist.
✔ Cleaned directory node_modules
✔ Cleaned file webpack.config.js
✔ Cleaned file package-lock.json
✔ Cleaned file tsconfig.tns.json
✔ Project files have been cleaned up
✔ Cleaned old artifacts
⠙ Migrating project to use nativescript.config.tsFailed to update config.Error: Cannot find module './parser-typescript'
⠹ Migrating project to use nativescript.config.tsFailed to update config.Error: Cannot find module './parser-typescript'
Failed to update config.Error: Cannot find module './parser-typescript'
⠸ Migrating project to use nativescript.config.tsFailed to update config.Error: Cannot find module './parser-typescript'

Failed to update nativescript.config.ts.

Please manually update nativescript.config.ts and set appPath to src.

Failed to update config.Error: Cannot find module './parser-typescript'
Failed to migrate project to use nativescript.config.ts. One or more values could not be updated.

```

Seems the dependencies on the template or migration util is not working as expected.  I recommend this be opened again as it is blocking new users from following https://docs.nativescript.org/start/cli-basics

Thanks,

**Comment by rigor789** [comment]
`tns-template-blank-ng` is outdated, the right template for ns7 is `@nativescript/template-blank-ng`

**Comment by leblancmeneses** [comment]
Deleted folder and tried again. Now I see nativescript launch script followed with an exception.

```
npx tns create HelloWorld --template @nativescript/template-blank-ng
cd HelloWorld/
npm install --save-dev nativescript
npx tns run android --device Pixel_3_XL_API_30
```

```
WARNING in /home/leblanc/repos/bitbucket/trash-nativescript/HelloWorld/nativescript.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

......


Restarting application on device emulator-5554...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)

```


emulator shows the following stacktrace
```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at com.tns.Module.bootstrapApp(Module.java:316)
	at com.tns.Runtime.run(Runtime.java:680)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
	... 8 more
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
	at com.tns.Module.resolvePathHelper(Module.java:151)
	at com.tns.Module.bootstrapApp(Module.java:314)
	... 12 more

```

**Comment by leblancmeneses** [comment]
Running
```
npx tns preview --bundle
before
npx tns run android --device Pixel_3_XL_API_30
```
runs the app but without hot reloading  (making a change causes white blank page)

**Comment by leblancmeneses** [comment]
trying to use preview app instead of emulator ```npx tns preview --bundle``` results in this:
https://github.com/NativeScript/nativescript-schematics/issues/290

**Comment by leblancmeneses** [comment]
If you are in angular this template works completely with hot module reloading inside an android emulator:
```git clone --depth 1 https://github.com/NativeScript/nativescript-sdk-examples-ng.git```

uses angular 9.1.0

**Comment by rigor789** [comment]
You are using `npx tns run` - what version of the CLI does it resolve to?

**Comment by leblancmeneses** [comment]
>  what version of the CLI does it resolve to? 

the version i installed with ```npm install --save-dev nativescript```  currently that is nativescript@7.0.8

**Comment by rigor789** [comment]
@leblancmeneses some updates were just pushed to the templates. You may need to set `appPath: 'src'` in the config (will also be addressed in a cli update soon).

**Comment by iecoding** [comment]
> 
> ```diff
> -import { NativeScriptConfig } from '@nativescript/core'
> 
> export default {
>   id: 'org.nativescript.app',
>   appPath: 'app',
>   appResourcesPath: 'app_resources',
>   android: {
>     v8Flags: '--expose_gc',
>     markingMode: 'none',
>   },
> -} as NativeScriptConfig
> +}
> ```

Same issue trying with `--template tns-template-drawer-navigation-ng`. As @rigor789 said: removing lines from /nativescript.config.ts file will work.

**Comment by catherine-augustine** [comment]
I created template from this : 

`tns create my-blank-ng --template tns-template-blank-ng
`
removed the lines from nativescript.config.ts

`tns run android` gives me the following error :


```
Project successfully built.
The build result is located at: /Users/johnwesley/AndroidStudioProjects/github/template/my-blank-ng/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Application org.nativescript.myblankng is not running on device emulator-5554.
This issue may be caused by:
	* crash at startup (try `tns debug android --debug-brk` to check why it crashes)
	* different application identifier in your package.json and in your gradle files (check your identifier in `package.json` and in all *.gradle files in your App_Resources directory)
	* device is locked
	* manual closing of the application
Unable to apply changes on device: emulator-5554. Error is: Application org.nativescript.myblankng is not running.



```

**Comment by GSoaki** [comment]
> `tns-template-blank-ng` is outdated, the right template for ns7 is `@nativescript/template-blank-ng` - the docs need to be updated.

I think this is confusing a lot of people, i got stuck on this error until i see your comment.

**Comment by basickarl** [comment]
Hey guys I'm also having issues migrating:

```
karl@karl-Dell-Precision-M3800:~/dev/basickarl/passer-mobile$ npx ns migrate
✔ Pre-Migration verification complete
✔ Project files have been backed up
✔ Cleaned directory hooks
✔ Cleaned directory platforms
✔ Cleaned directory node_modules
✔ Cleaned file webpack.config.js
✔ Cleaned file package-lock.json
ℹ Skipping tsconfig.tns.json because it doesn't exist.
✔ Project files have been cleaned up
✔ Cleaned old artifacts
⠋ Migrating project to use nativescript.config.tsFailed to update config.Error: Cannot find module 'fs-extra'
Require stack:
- /home/karl/dev/basickarl/passer-mobile/node_modules/@ts-morph/common/dist/ts-morph-common.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/ts-morph/dist/ts-morph.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/tools/config-manipulation/config-transformer.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/services/project-config-service.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/common/yok.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/bootstrap.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/nativescript-cli.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/bin/tns
Failed to update config.Error: Cannot find module 'fs-extra'
Require stack:
- /home/karl/dev/basickarl/passer-mobile/node_modules/@ts-morph/common/dist/ts-morph-common.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/ts-morph/dist/ts-morph.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/tools/config-manipulation/config-transformer.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/services/project-config-service.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/common/yok.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/bootstrap.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/nativescript-cli.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/bin/tns
Failed to update config.Error: Cannot find module 'fs-extra'
Require stack:
- /home/karl/dev/basickarl/passer-mobile/node_modules/@ts-morph/common/dist/ts-morph-common.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/ts-morph/dist/ts-morph.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/tools/config-manipulation/config-transformer.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/services/project-config-service.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/common/yok.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/bootstrap.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/nativescript-cli.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/bin/tns

Failed to update nativescript.config.ts.

Please manually update nativescript.config.ts and set android.maxLogcatObjectSize to 5000.

Failed to update config.Error: Cannot find module 'fs-extra'
Require stack:
- /home/karl/dev/basickarl/passer-mobile/node_modules/@ts-morph/common/dist/ts-morph-common.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/ts-morph/dist/ts-morph.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/tools/config-manipulation/config-transformer.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/services/project-config-service.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/common/yok.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/bootstrap.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/nativescript-cli.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/bin/tns

Failed to update nativescript.config.ts.

Please manually update nativescript.config.ts and set id to io.basickarl.passer.

Failed to update config.Error: Cannot find module 'fs-extra'
Require stack:
- /home/karl/dev/basickarl/passer-mobile/node_modules/@ts-morph/common/dist/ts-morph-common.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/ts-morph/dist/ts-morph.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/tools/config-manipulation/config-transformer.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/services/project-config-service.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/common/yok.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/bootstrap.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/nativescript-cli.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/bin/tns

Failed to update nativescript.config.ts.

Please manually update nativescript.config.ts and set appPath to app.

Failed to update config.Error: Cannot find module 'fs-extra'
Require stack:
- /home/karl/dev/basickarl/passer-mobile/node_modules/@ts-morph/common/dist/ts-morph-common.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/ts-morph/dist/ts-morph.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/tools/config-manipulation/config-transformer.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/services/project-config-service.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/common/yok.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/bootstrap.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/lib/nativescript-cli.js
- /home/karl/dev/basickarl/passer-mobile/node_modules/nativescript/bin/tns

Failed to update nativescript.config.ts.

Please manually update nativescript.config.ts and set appResourcesPath to app/App_Resources.

✔ Cleaned file nativescript.config.ts
Failed to migrate project to use nativescript.config.ts. One or more values could not be updated.
```

**Comment by hrustbb2** [comment]
Очередная неработающая хуета

**Comment by justintoth** [comment]
It's February 2021, how do the docs STILL say tns-template-blank-ng???

**Comment by rigor789** [comment]
@justintoth thanks for the PR! With limited time, we try to focus on bugs&features first - docs pr's are very welcome to reduce the workload of all the maintainers!
