### ISSUE TITLE
Nativescript 7.0 upgrade issues

### ISSUE THREAD

**Issue by CoderAvudai** [NativeScript/NativeScript#8815]
I get the following error after migrating my Nativescript Vue application to NS 7.0. I am not sure whether the Nativescript 7.0 upgrade was recommended for vue based application. Could the below issues be resolved or how could I possibly revert my application back to Nativescript 6.0?

ISSUE 1:
Plugin Error:
nativescript-plugin-firebase/messaging/messaging.js
nativescript-ui-listview/ui-listview.js
nativescript-ui-listview/vue/component.js

ISSUE 2:
My application uses Firebase, yet I do not see node_modules/@nativescript/firebase after "ns update" command. How can I get this firebase folder created?

ISSUE 3:
I also get - Error from chokidar (C:\node_modules\@nativescript): Error: EBUSY: resource busy or locked

Please help me fix the above issues?

------------------------------------------------------
LOG from 'tns run android':

**ERROR in ../node_modules/nativescript-plugin-firebase/messaging/messaging.js**
Module not found: Error: Can't resolve 'tns-core-modules/application/application' in 'C:\learning\xxxx\yyyy\node_modules\nativescript-plugin-firebase\messaging'
@ ../node_modules/nativescript-plugin-firebase/messaging/messaging.js 11:18-69
@ ../node_modules/nativescript-plugin-firebase/firebase.js
@ ./main.js

**ERROR in ../node_modules/nativescript-ui-listview/ui-listview.js**
Module not found: Error: Can't resolve 'tns-core-modules/color/color' in 'C:\learning\xxxx\yyyy\node_modules\nativescript-ui-listview'
@ ../node_modules/nativescript-ui-listview/ui-listview.js 21:14-53
@ ../node_modules/nativescript-ui-listview/vue/index.js
@ ./main.js

**ERROR in ../node_modules/nativescript-ui-listview/vue/component.js**
Module not found: Error: Can't resolve 'tns-core-modules/ui/page/page' in 'C:\learning\xxxx\yyyy\node_modules\nativescript-ui-listview\vue'
@ ../node_modules/nativescript-ui-listview/vue/component.js 9:13-53
@ ../node_modules/nativescript-ui-listview/vue/index.js
@ ./main.js
**Error from chokidar (C:\):** Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
**Error from chokidar (C:\node_modules):** Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
**Error from chokidar (C:\node_modules\@nativescript):** Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules\@nativescript): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules\@nativescript): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
**Error from chokidar (C:\node_modules\@nativescript\core):** Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules\@nativescript\core): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules\@nativescript\core): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'

**Comment by rigor789** [comment]
Please post your `package.json`.

For firebase, you have to install `@nativescript/firebase` and remove `nativescript-plugin-firebase` (and update your imports to the new package).

For `nativescript-ui-listview`, you need to install the `9.0.2` version.

**Comment by CoderAvudai** [comment]
Hello,

Thanks for the quick response. I followed your recommendation, which fixed all the plugin related issues. Now I get a certificate issue, which I was not getting before upgrade to NS7.0

Below you will find package.json and error log. Could you please assist on the certificate issue? Checking this [stackoverflow discussion](https://stackoverflow.com/questions/36506539/how-do-i-get-visual-studio-code-to-trust-our-self-signed-proxy-certificate) I tried setting  `"http.proxyStrictSSL": false` in settings.json file, but that didn't help.

**Package.json
--------------**
```
{
  "name": "oms",
  "version": "1.0.0",
  "description": "Order tracking application",
  "author": "CoderAvudai",
  "license": "MIT",
  "dependencies": {
    "@nativescript/core": "7.0.0",
    "@nativescript/firebase": "^11.0.0-rc.0",
    "@nativescript/theme": "^2.2.1",
    "@vue/devtools": "^5.3.3",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-autocomplete": "^6.0.1",
    "nativescript-ui-dataform": "^6.1.0",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-vue": "^2.7.1",
    "nativescript-vue-devtools": "^1.4.0",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.11.0",
    "@nativescript/android": "7.0.0",
    "@nativescript/types": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "babel-loader": "^8.1.0",
    "nativescript-vue-template-compiler": "^2.6.0",
    "nativescript-worker-loader": "~0.11.0",
    "node-sass": "^4.13.1",
    "ts-patch": "^1.3.0",
    "vue-loader": "^15.9.1"
  },
  "scripts": {
    "setup": "npm i && ts-patch install"
  },
  "main": "main"
}
```

**Error Log:
----------**
After **tns build android --clean**

```
Webpack compilation complete. Watching for file changes.
Webpack build done!
nativescript-plugin-firebase: C:\learning\nsvue\oms\platforms\android\.pluginfirebaseinfo not found, forcing prepare!
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!  
Downloading https://services.gradle.org/distributions/gradle-6.4-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2729)      
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2641)       
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1824)      
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)       
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
        at org.gradle.wrapper.Download.download(Download.java:45)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)      
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
        at sun.security.validator.Validator.validate(Validator.java:262)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)       
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
        ... 22 more
**Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)    
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
        ... 28 more
**Failed to build plugin @nativescript/firebase :** 
Error: Command gradlew.bat failed with exit code 1
```

**Comment by NathanWalker** [comment]
Seems relevant perhaps: https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-error-779355358.html

**Comment by CoderAvudai** [comment]
Hi Nathan,

Thank you, I tried the SSLPoke to services.gradle.org which was successful

```
PS C:\learning\software> java SSLPoke services.gradle.org 443
Successfully connected
```

I assumed the target that is failing to be service.gradle.org as that was the message right before the SSL error. Is there any other way to confirm whether its failing only in gradle download step?

Meanwhile, I installed nativescript 6.5.0 and ran the copy of same application (without upgrade) and its working fine. This certainly seems to do something with Nativescript 7.0.

**Comment by bsantos11** [comment]
In your code

> **tns-core-modules**

 Should be replaces with 
(Project Folder) **/node_modules/@nativescript/core**

Example:
If **app.js** is in the **app** folder
`const application = require("tns-core-modules/application");`
**Is changed to**
`const application = require("../node_modules/@nativescript/core/application");`

**Comment by CoderAvudai** [comment]
This seems to be a firewall issue. I replicated my project with NS7.0 in another laptop with less firewall restrictions and it allowed gradle download. Just one strange thing that I do not have this firewall issue with NS6.0 build.
Thanks all for your support.
