### ISSUE TITLE
Unexpected crash - Going back is not enough

### ISSUE THREAD

**Issue by JakobJR** [NativeScript/NativeScript#8825]
**Environment**
‼ Update available for component nativescript. Your current version is 6.8.0 and the latest available version is 7.0.6.
‼ Update available for component tns-core-modules. Your current version is 6.3.2 and the latest available version is 6.5.18.
‼ Update available for component tns-android. Your current version is 6.3.1 and the latest available version is 6.5.3.
‼ Update available for component tns-ios. Your current version is 6.3.0 and the latest available version is 6.5.2.

**Describe the bug**
I've been playing around with NativeScript and I've encountered this crash multiple times. It just randomly happens and no matter how much I undo (to the point where to app was working) it won't work.

**To Reproduce**
Project successfully prepared (ios)
Start sending initial files for device Jakob - iPhone (DD946417-53D9-42DE-B8B8-6EE0B9DE77AD).
Successfully sent initial files for device Jakob - iPhone (DD946417-53D9-42DE-B8B8-6EE0B9DE77AD).
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./app.css
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./app.css
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./app.css
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./app.css
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: The following modules were updated:
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR: Successfully applied update with hmr hash c8af661a90cbb0b61488. App is up to date.   
LOG from device Jakob - iPhone: CONSOLE INFO file:///app/vendor.js:87:36: HMR:          ↻ ./views/products/products.xml
LOG from device Jakob - iPhone: The Preview app has terminated unexpectedly. Please run it again to get a detailed crash report.
The Preview app has terminated unexpectedly. Please run it again to get a detailed crash report.
LOG from device Jakob - iPhone: 2020-09-08 10:32:11.329 nsplaydev[7034:1941193] ***** Fatal JavaScript exception - application has been terminated. *****
2020-09-08 10:32:11.329 nsplaydev[7034:1941193] Native stack trace:
1   0x1057c2928 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1057fd02c NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10636a7f8 ffi_closure_SYSV_inner
4   0x10636c1b4 .Ldo_closure
5   0x1a8a8e72c <redacted>
6   0x1a849eed4 <redacted>
7   0x1a849f22c <redacted>
8   0x1a849e250 <redacted>
9   0x1a8ac849c <redacted>
10  0x1a8ac9c64 <redacted>
11  0x1a8aa58ec <redacted>
12  0x1a8b26970 <redacted>
13  0x1a8b294ec <redacted>
14  0x1a8b21168 <redacted>
15  0x1a4957ad8 <redacted>
16  0x1a4957a30 <redacted>
17  0x1a49571b8 <redacted>
18  0x1a49521e8 <redacted>
19  0x1a4951ba8 CFRunLoopRunSpecific
20  0x1aeac1344 GSEventRunModal
21  0x1a8a8d3e4 UIApplicationMain
22  0x10636c044 ffi_call_SYSV
23  0x106369f1c ffi_call_int
24  0x106369a18 ffi_call
25  0x10578546c NativeScript::FunctionWrapper::call(JSC::ExecState*)
26  0x106336cf0 llint_entry
27  0x106334108 llint_entry
28  0x106334108 llint_entry
29  0x106334108 llint_entry
30  0x106334108 llint_entry
31  0x106334108 llint_entry
2020-09-08 10:32:11.341 nsplaydev[7034:1941193] JavaScript stack trace:
2020-09-08 10:32:11.342 nsplaydev[7034:1941193] ./views/products/products.xml(file:///app/bundle.9457602e2f62dd574347.hot-update.js:6:724)
at __webpack_require__(file:///app/runtime.js:751:34)
at fn(file:///app/runtime.js:121:39)
at webpackContext(file:///app/bundle.js:52:28)
at loader(file:///app/tns_modules/@nativescript/core/globals/register-module-helpers.js:36:35)
at loadModule(file:///app/tns_modules/@nativescript/core/globals/register-module-helpers.js:77:39)
at loadInternal(file:///app/tns_modules/@nativescript/core/ui/builder/builder.js:96:37)
at file:///app/tns_modules/@nativescript/core/ui/builder/builder.js:37:51
at file:///app/tns_modules/@nativescript/core/ui/frame/frame-common.js:165:57
at onTap(file:///app/bundle.js:226:24)
at file:///app/tns_modules/@nativescript/core/data/observable/observable.js:110:31
at file:///app/tns_modules/@nativescript/core/data/observable/observable.js:127:24
at file:///app/tns_modules/@nativescript/core/ui/button/button.js:216:24
at UIApplicationMain([native code])
at run(file:///app/tns_modules/@nativescript/core/application/application.js:312:26)
at file:///app/bundle.js:150:16
at ./app.js(file:///app/bundle.js:167:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2020-09-08 10:32:11.342 nsplaydev[7034:1941193] JavaScript error:
file:///app/bundle.9457602e2f62dd574347.hot-update.js:6:724: JS ERROR Error: Module build failed (from ../node_modules/nativescript-dev-webpack/xml-namespace-loader.js):
Error: Unexpected close tag
Line: 12
Column: 14
Char: >
    at error (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:677:7)
    at closeTag (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:871:9)
    at SAXParser.write (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:1436:13)
    at Object.loader (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\nativescript-dev-webpack\xml-namespace-loader.js:94:15)
2020-09-08 10:32:11.343 nsplaydev[7034:1941193] PlayLiveSync: Uncaught Exception
2020-09-08 10:32:11.344 nsplaydev[7034:1941193] PlayLiveSync: Sending crash report
2020-09-08 10:32:15.346 nsplaydev[7034:1941193] *** JavaScript call stack:
(
        0   UIApplicationMain@[native code]
        1   run@file:///app/tns_modules/@nativescript/core/application/application.js:312:26
        2   @file:///app/bundle.js:150:16
        3   ./app.js@file:///app/bundle.js:167:34
        4   __webpack_require__@file:///app/runtime.js:751:34
        5   checkDeferredModules@file:///app/runtime.js:44:42
        6   webpackJsonpCallback@file:///app/runtime.js:31:39
        7   anonymous@file:///app/bundle.js:2:61
        8   evaluate@[native code]
        9   moduleEvaluation@:1:11
        10  @:2:1
        11  asyncFunctionResume@:1:11
        12  @:24:9
        13  promiseReactionJob@:1:11
)
2020-09-08 10:32:15.346 nsplaydev[7034:1941193] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Module build failed (from ../node_modules/nativescript-dev-webpack/xml-namespace-loader.js):
Error: Unexpected close tag
Line: 12
Column: 14
Char: >
    at error (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:677:7)
    at closeTag (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:871:9)
    at SAXParser.write (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\sax\lib\sax.js:1436:13)
    at Object.loader (C:\Users\Jakob\Downloads\Tekmo2\Tekmo2\node_modules\nativescript-dev-webpack\xml-namespace-loader.js:94:15)
 at
./views/products/products.xml(file:///app/bundle.9457602e2f62dd574347.hot-update.js:6:724)
at __webpack_require__(file:///app/runtime.js:751:34)
at fn(file:///app/runtime.js:121:39)
at webpackContext(file:///app/bundle.js:52:28)
at loader(file:///app/tns_modules/@nativescript/core/globals/register-module-helpers.js:36:35)
at loadModule(file:///app/tns_modules/@nativescript/core/globals/register-module-helpers.js:77:39)
at loadInternal(file:///app/tns_modules/@nativescript/core/ui/builder/builder.js:96:37)
at file:///app/tns_modules/@nativescript/core/ui/builder/builder.js:37:51
at file:///app/tns_modules/@nativescript/core/ui/frame/frame-common.js:165:57
at onTap(file:///app/bundle.js:226:24)
at file:///app/tns_modules/@nativescript/core/data/observable/observable.js:110:31
at file:///app/tns_modules/@nativescript/core/data/observable/observable.js:127:24
at file:///app/tns_modules/@nativescript/core/ui/button/button.js:216:24
at UIApplicationMain([native code])
at run(file:///app/tns_modules/@nativescript/core/application/application.js:312:26)
at file:///app/bundle.js:150:16
at ./app.js(file:///app/bundle.js:167:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x1a49d9654 0x1a46fbbcc 0x1057c2e00 0x1057fd02c 0x10636a7f8 0x10636c1b4 0x1a8a8e72c 0x1a849eed4 0x1a849f22c 0x1a849e250 0x1a8ac849c 0x1a8ac9c64 0x1a8aa58ec 0x1a8b26970 0x1a8b294ec 0x1a8b21168 0x1a4957ad8 0x1a4957a30 0x1a49571b8 0x1a49521e8 0x1a4951ba8 0x1aeac1344 0x1a8a8d3e4 0x10636c044 0x106369f1c 0x106369a18 0x10578546c 0x106336cf0 0x106334108 0x106334108 0x106334108 0x106334108 0x106334108 0x106334060 0x106334108 0x1063157c8 0x1058c1af0 0x106166cd8 0x10579dc40 0x106034620 0x1063369ac 0x106334108 0x106334108 0x106334108 0x106334060 0x106334108 0x1063157c8 0x1058c1af0 0x106166e90 0x10602d948 0x10579336c 0x10580cf80 0x1055f625c 0x104cb7524 0x1a47d98f0)
libc++abi.dylib: terminating with uncaught exception of type NSException
2020-09-08 10:32:15.347 nsplaydev[7034:1941193] PlayLiveSync: Uncaught Exception

**Expected behavior**

**Additional context**
I'm sure it's a minor thing that I need to do in order to fix it. Just doesn't make sense that even though I go back to an earlier version where it was working, it's still throwing me the same error.

**Comment by JakobJR** [comment]
Aaaaaand now it's randomly working again. Didn't change anything, just waiting fixed it. How can I combat this in the future, so I don't have to randomly wait 30 minutes in order for it to magically fix itself?

**Comment by JakobJR** [comment]
I guess there's some sort of cache for a while, so even undoing something, it's still cached. Is there a way to clear the cache from the preview?

**Comment by rigor789** [comment]
Try disabling HMR with `--no-hmr` and see if that makes a difference.
