### ISSUE TITLE
VSCode debugger crashes NS7 app on iOS 14

### ISSUE THREAD

**Issue by mreall** [NativeScript/NativeScript#8882]
**Environment**
 - CLI: 7.0.8
 - Cross-platform modules: 7.0.3
 - Android Runtime: 7.0.0
 - iOS Runtime: 7.0.0
 - Plugin(s): 
```
  "dependencies": {
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/background-http": "^5.0.0",
    "@nativescript/core": "^7.0.0",
    "@nativescript/fingerprint-auth": "^7.0.0",
    "@nativescript/firebase": "^11.0.0-rc",
    "@nativescript/imagepicker": "^1.0.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nstudio/nativescript-pulltorefresh": "^3.0.0",
    "axios": "^0.19.2",
    "nativescript-app-tour": "^2.0.2",
    "nativescript-carousel": "^7.0.0",
    "nativescript-contacts-lite": "^0.2.7",
    "nativescript-exoplayer": "^4.0.2",
    "nativescript-imagecropper": "^4.0.1",
    "nativescript-modal-datetimepicker": "^1.2.2",
    "nativescript-permissions": "^1.3.9",
    "nativescript-perms": "^2.0.11",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-videoplayer": "^5.0.0",
    "nativescript-videorecorder-x": "^1.0.3-android-x",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-navigator": "^1.2.0",
    "vue-moment": "^4.1.0",
    "vuelidate": "^0.7.5",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/webpack": "3.0.3",
    "babel-loader": "^8.1.0",
    "dotenv-webpack": "^2.0.0",
    "nativescript-vue-template-compiler": "^2.8.1",
    "net": "^1.0.2",
    "node-sass": "^4.14.1",
    "postcss-loader": "^4.0.2",
    "vue-loader": "^15.9.3"
  },
```

**Describe the bug**
Since upgrading to NS7, when I attempt to attach the VSCode debugger to my iOS app on an iPhone 8 emulator, the app frequently crashes after the Backend socket is created. Sometimes it works.  I don't get an error message and can't find a consistent pattern for the crashing.  The debugger worked reliably before upgrading to NS7.

**To Reproduce**
Launch iOS app on the emulator, then try to attach debugger.

**Expected behavior**
The debugger should attach without causing the app to crash.

**Comment by mreall** [comment]
I'm now on NS8 and still have the same issue.

**Comment by mreall** [comment]
Possibly related to #9233.

**Comment by s0l4r** [comment]
Same issue on NS8 and iOS 14.5 and VScode 1.60 debugger:

```
NativeScript debugger was not able to get inspector socket port on device XXX for application org.nativescript.cosmic.

Device socket port cannot be found.

Error: Device socket port cannot be found.
    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:157:27)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:130:21)
    at IOSSimulator.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/ios-device-base.js:66:30)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/ios-device-base.js:11:58) {
  name: 'Exception',
  errorCode: 127,
  suggestCommandHelp: false,
  proxyAuthenticationRequired: false,
  printOnStdout: undefined,
  deviceIdentifier: 'XXX'
}
```

The error is very random, sometimes it works and sometimes it does not. When using "stopOnEntry": true,  in launch.json, it crashes as well:

```
(lldb) process attach --pid 7503

[NSDebugAdapter] Ready to attach to application on 41000

Frontend client connected.

ATTACH_REQUEST {
  deviceId: '60391162-F121-4A67-BD22-F103572FD8EC',
  appId: 'org.nativescript.cosmic'
}

Process 7503 stopped
* thread #1, stop reason = signal SIGSTOP
    frame #0: 0x000000010fc95000 dyld`_dyld_start
dyld`_dyld_start:
->  0x10fc95000 <+0>: popq   %rdi
    0x10fc95001 <+1>: pushq  $0x0
    0x10fc95003 <+3>: movq   %rsp, %rbp
    0x10fc95006 <+6>: andq   $-0x10, %rsp
Target 0: (cosmic) stopped.

Executable module set to "/Users/s0l4r/Library/Developer/CoreSimulator/Devices/60391162-F121-4A67-BD22-F103572FD8EC/data/Containers/Bundle/Application/AE000F47-5E73-47B5-8840-080259C47FF1/cosmic.app/cosmic".
Architecture set to: x86_64h-apple-ios-simulator.

(lldb) process continue

Process 7503 resuming

CONSOLE LOG: Loading inspector modules...

CONSOLE LOG: Finished loading inspector modules.

NativeScript debugger has opened inspector socket on port 18183 for org.nativescript.cosmic.
NativeScript waiting for debugger.

DEBUGGER_PORT_FOUND {
  port: 18183,
  appId: 'org.nativescript.cosmic',
  deviceId: '60391162-F121-4A67-BD22-F103572FD8EC'
}

Backend socket created.

Process 7503 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001028fbb22 NativeScript`v8::base::OS::Abort() + 18
NativeScript`v8::base::OS::Abort:
->  0x1028fbb22 <+18>: ud2    
    0x1028fbb24 <+20>: nopw   %cs:(%rax,%rax)
    0x1028fbb2e <+30>: nop    

NativeScript`v8::base::OS::DebugBreak:
    0x1028fbb30 <+0>:  pushq  %rbp
Target 0: (cosmic) stopped.```
