### ISSUE TITLE
[NS7] --Release flag is not working in Android production build

### ISSUE THREAD

**Issue by kranthi-kiki** [NativeScript/NativeScript#8934]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

 dependencies:
 "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/theme": "~2.3.0",
    "@nativescript/webpack": "3.0.0",
    "@nstudio/nativescript-cardview": "^2.0.0",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "@nstudio/nativescript-snackbar": "^2.0.2",
    "nativescript-app-tour": "^2.0.2",
    "nativescript-appversion": "^1.4.2",
    "nativescript-exit": "^1.0.1",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-feedback": "^1.3.12",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-permissions": "^1.3.8",
    "nativescript-phone": "^1.4.1",
    "nativescript-social-share": "^1.6.0",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toasts": "^1.0.3",
    "nativescript-ui-sidedrawer": "~9.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "rxjs-compat": "^6.4.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "codelyzer": "~6.0.0",
    "node-sass": "^4.14.1",
    "tslint": "~6.1.3",
    "typescript": "~3.9.0"
  }

ns version: 7.0.9-rc.2
node version: 10.15.1
xcode version: 12

Describe the bug:

Getting below error if use --release flag for production build.

give build using below commond:
![image](https://user-images.githubusercontent.com/46471488/95068305-be6c8e80-0722-11eb-9f2c-a320aeb62c32.png)

Error:

Execution failed for task ':app:lintVitalRelease'.
Lint infrastructure error
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.android.tools.lint.gradle.api.ReflectiveLintRunner.runLint(ReflectiveLintRunner.kt:38)
        at com.android.build.gradle.tasks.LintBaseTask.runLint(LintBaseTask.java:114)
        at com.android.build.gradle.tasks.LintPerVariantTask.lint(LintPerVariantTask.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMetho

Caused by: com.android.builder.errors.EvalIssueException: Failed to parse XML in /Users/xavica0005/Documents/Xavica/qwipo-mobile/qwipo-b2b-revamp/platforms/android/app/src/main/AndroidManifest.xml
The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
        at com.android.builder.errors.EvalIssueReporter.reportError(EvalIssueReporter.kt:102)
        at com.android.builder.errors.EvalIssueReporter.reportError$default(EvalIssueReporter.kt:98)
        at com.android.builder.errors.EvalIssueReporter.reportError(EvalIssueReporter.kt)
        at com.android.build.gradle.internal.ide.ModelBuilder.createVariant(ModelBuilder.java:601)
        at com.android.build.gradle.internal.ide.ModelBuilder.buildAndroidProject(ModelBuilder.java:399)
        at com.android.build.gradle.internal.ide.ModelBuilder.buildAll(ModelBuilder.java:193)
        at com.android.build.gradle.internal.AppModelBuilder.buildAll(AppModelBuilder.kt:63)
        at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingToolingModelBuilder$1$1.create(DefaultToolingModelBuilderRegistry.java:104)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:134)
        at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingToolingModelBuilder$1.call(DefaultToolingModelBuilderRegistry.java:100)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingToolingModelBuilder.buildAll(DefaultToolingModelBuilderRegistry.java:97)
        at com.android.tools.lint.gradle.LintGradleExecution.createAndroidProject(LintGradleExecution.java:369)
        at com.android.tools.lint.gradle.LintGradleExecution.analyze(LintGradleExecution.java:88)
        ... 109 more

**Comment by rigor789** [comment]
From the error message you posted:
```
Caused by: com.android.builder.errors.EvalIssueException: Failed to parse XML in /Users/xavica0005/Documents/Xavica/qwipo-mobile/qwipo-b2b-revamp/platforms/android/app/src/main/AndroidManifest.xml
The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
```

Check your `AndroidManifest.xml`

**Comment by kranthi-kiki** [comment]
@rigor789 thanks for the info. issue fixed
