### ISSUE TITLE
Calling js method onStart failed Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by AnthonyLenglet** [NativeScript/NativeScript#8942]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules: 6.5.20
 - Android Runtime: 6.5.1
 - iOS Runtime: 6.5.2
 - Plugin(s):
```
    "@nativescript/theme": "2.3.3",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "nativescript-angular": "^8.21.0",
    "nativescript-app-sync": "^2.0.0",
    "nativescript-camera": "^4.5.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-datetimepicker": "^1.2.3",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-material-bottomnavigationbar": "^3.1.7",
    "nativescript-phone": "^1.4.0",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-sentry": "^1.9.1",
    "nativescript-unit-test-runner": "^0.7.0",
```

**Describe the bug**

upon tapping on a grid layout item with a tap event, the application crashes with this error:

```
java.lang.NullPointerException: null
    at com.tns.MethodResolver$MethodFinder.getMatchingMethodWithArguments(MethodResolver.java:582)
    at com.tns.MethodResolver.resolveMethodOverload(MethodResolver.java:125)
    at com.tns.Runtime.resolveMethodOverload(Runtime.java:1240)
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:34)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
    at android.app.Activity.performStart(Activity.java:5452)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)

com.tns.NativeScriptException: Calling js method onStart failed
Error: java.lang.NullPointerException
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:34)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
    at android.app.Activity.performStart(Activity.java:5452)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.idtroc.idkids/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onStart failed
Error: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)
```

**To Reproduce**
Not actually sure what could reproduce this, its seemingly random, with some users encountering this issue but not the rest.

**Comment by NathanaelA** [comment]
1. Use Android Runtime v6.5.3 -- several issues were fixed with Metadata in it.
2. Try Disabling App-Sync, it is something that ties into startup and could be causing the issue.
3. If you are using Snapshots, disable them.

In addition, can you find out which OS's it is crashing on; sometimes it is related to a specific android version

**Comment by CatchABus** [comment]
Closing due to inactivity.
