### ISSUE TITLE
NS7 error when running scss

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#8950]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.10
 - Cross-platform modules:
 - Android Runtime: "@nativescript/android": "7.0.0",
 - iOS Runtime: tns-ios 6.5.3 and also with new v8 runtime
 - Plugin(s):

```
	"dependencies": {
		"@angular/animations": "~10.1.3",
		"@angular/common": "~10.1.3",
		"@angular/compiler": "~10.1.3",
		"@angular/core": "~10.1.3",
		"@angular/forms": "~10.1.3",
		"@angular/platform-browser": "~10.1.3",
		"@angular/platform-browser-dynamic": "~10.1.3",
		"@angular/router": "~10.1.3",
		"@nativescript/angular": "~10.1.5",
		"@nativescript/core": "~7.0.0",
		"@nativescript/firebase": "rc",
		"@nativescript/iqkeyboardmanager": "~2.0.0",
		"@nativescript/localize": "~5.0.0",
		"@nativescript/secure-storage": "^3.0.0",
		"@nativescript/theme": "~2.3.3",
		"@nativescript/ui-charts": "~0.0.5",
		"apollo-angular-link-http": "^1.11.0",
		"apollo-cache-inmemory": "^1.6.5",
		"apollo-cache-persist": "^0.1.1",
		"apollo-link": "^1.2.14",
		"apollo-link-batch-http": "^1.2.14",
		"apollo-link-context": "^1.0.20",
		"apollo-link-error": "^1.1.13",
		"d3-ease": "^1.0.7",
		"graphql": "^15.3.0",
		"graphql-tag": "^2.11.0",
		"intl": "^1.2.5",
		"moment": "^2.27.0",
		"nativescript-oauth2-ext": "file:../mnd-custom-plugins/nativescript-oauth2-ext/publish/package/nativescript-oauth2-ext-3.0.0.tgz",
		"nativescript-sqlite": "^2.6.4",
		"nativescript-ui-autocomplete": "^7.0.2",
		"nativescript-ui-calendar": "^7.0.2",
		"nativescript-ui-chart": "^8.0.2",
		"nativescript-ui-gauge": "~7.0.2",
		"nativescript-ui-listview": "^9.0.2",
		"offix-angular": "^0.0.4",
		"offix-client": "^0.15.5",
		"reflect-metadata": "~0.1.12",
		"rxjs": "^6.5.5",
		"tslib": "1.10.0",
		"uuid": "^8.3.0",
		"zone.js": "~0.10.2"
	},
	"devDependencies": {
		"@angular/cli": "~10.1.3",
		"@angular/compiler-cli": "~10.1.3",
		"@graphql-codegen/cli": "^1.17.8",
		"@graphql-codegen/fragment-matcher": "^1.17.8",
		"@graphql-codegen/introspection": "^1.17.8",
		"@graphql-codegen/typescript": "^1.17.9",
		"@graphql-codegen/typescript-apollo-angular": "^1.17.7",
		"@graphql-codegen/typescript-operations": "^1.17.8",
		"@nativescript/android": "7.0.0",
		"@nativescript/types": "~7.0.3",
		"@nativescript/webpack": "~3.0.0",
		"@ngtools/webpack": "~10.1.3",
		"@types/d3-ease": "^1.0.9",
		"@types/intl": "^1.2.0",
		"@types/node": "^13.13.19",
		"@types/uuid": "^7.0.4",
		"codelyzer": "^6.0.1",
		"keycloak-request-token": "^0.1.0",
		"node-sass": "^4.14.1",
		"tns-ios": "6.5.3",
		"ts-node": "^8.10.2",
		"tslint": "^6.1.3",
		"typescript": "~3.9.2"
```
**Describe the bug**

/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:359
                finally { if (e_2) throw e_2.error; }
                                   ^

Error: HostResourceResolver: could not resolve ./scanner.scss in context of /Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/src/app/modules/main/pages/scanner/scanner.component.ts)
    at AdapterResourceLoader.resolve (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/resource/src/loader.js:56:23)
    at ComponentDecoratorHandler.analyze (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:239:63)
    at TraitCompiler.analyzeTrait (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:346:40)
    at analyze (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:298:58)
    at _loop_1 (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:320:21)
    at TraitCompiler.analyzeClass (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:326:35)
    at visit (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:108:27)
    at visitNodes (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/typescript/lib/typescript.js:18956:30)
    at Object.forEachChild (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/typescript/lib/typescript.js:19189:24)
    at visit (/Users/cjohn/Entwicklung/MND/my-nutri-diary/mnd/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:110:20)
Webpack compilation complete. Watching for file changes.

**To Reproduce**
angular project created with ns create rename css files into file.ios.scss file.android.scss which include _file-common.scss

**Expected behavior**
compiles without errors like under NS6

**Additional context**
We had several discussion on Slack and Nativescript Roadmap telcos. Seems like it results from a concurrency issue in the toolchain

**Comment by kislasi** [comment]
+1

**Comment by cjohn001** [comment]
Hello @kislasi ,
unfortunately I have not found a solution yet. In case I do I will post it here

**Comment by SergeyMell** [comment]
I've managed to make it run with scss files. So you should
1. As long as you're using Angular - add schematics to angular.json project
```
// angular.json
   ...
  "projects": {
    "hello-world": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "ns",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      }
    }
  },
```
2. Add loaders, required for the webpack to handle scss files
```
npm i -D node-sass@4.14.1 sass-loader
```
3. Restart your project. Should work now.

Please, let me know if this didn't help. A minimal reproducible example could be very helpful in this case

**Comment by kislasi** [comment]
@SergeyMell thank you for responding, 
but I tried and it didn't do any change...

**Comment by SergeyMell** [comment]
Did you try all the points from my message? I see that you have `node-sass` already installed, however, `sass-loader` seems to be missing. Can you provide me with some minimal reproducible example? This will allow me to help you in a more effective manner.

**Comment by cjohn001** [comment]
@SergeyMell  I also tried it, unfortunately it does not work for me either. I will try to look into an example over the weekend.

**Comment by SergeyMell** [comment]
Ok. Looking forward to looking into it

**Comment by SergeyMell** [comment]
Hey, @cjohn001, did you have a chance to prepare some minimal reproducible example so I could test it and help you with your issue?

**Comment by cjohn001** [comment]
Hello Sergey,
sorry, I have not had a chance yet to look into it in more detail, but I have the topic on the list. I had a short try but could not get the bug to appear. As soon as I find time I will look into it again. Currently, having to solve some issues that hinder a release of my app. I consider this issue not so urgent, because even though I get an error message on the command line, the build still works and the scss is processed correctly. @kislasi do you observe an erroneous build are also just an error messaage and the build is ok? Might you be able to provide an example?

**Comment by Jaroslav84** [comment]
I'm having the same "finally { if (e_2) throw e_2.error HostResourceResolver: could not resolve ./login.component.css" with CSS.

It happens only when I change code and app is already running (on emulator in my case).

**Comment by cjohn001** [comment]
Hello @SergeyMell sorry for the long waiting, but I have found the source of the problem now. I attach a demo showing the problem.
The scss issue is related to the use of scss on component level. And there it is not about using a scss standalone, but using scss together with a x.ios.ts and x.android.ts file. In order to see this issue, you need to start the demo app with 

 ns run ios --emulator --no-hmr --env.aot

and than you need to change a file and save it. The issue only appears when the app is running and is rebuild.

[scssbug.zip](https://github.com/NativeScript/NativeScript/files/5575265/scssbug.zip)

@Jaroslav84 : As your problem relates to css and I assume the issue I mentioned here is related to a runtime dependence between scss and another build step I assume you are seeing something different.

Thanks for looking into the issue @SergeyMell 

Best regards,
 Christoph

**Comment by SergeyMell** [comment]
Thank you for the example. I tested it and see that the issue takes place. However it is not stabile reproducible it happens often enough. I'll take a look and see if I can manage it

**Comment by cjohn001** [comment]
Hello @SergeyMell,
I see the situation on each rebuild when I store the component file. I assume the issue results from a concurrency. Might be that you do not see it each time as your computer is faster? Maybe add further classes to the scss processing? Nevertheless, thanks a lot for looking into it!

Best regards,
 Christoph

**Comment by SergeyMell** [comment]
Yeah, something like that. Even more, I see the same problem with the html templates if using `item-detail.component.ios.html` and `item-detail.component.android.html` instead of a single one `item-detail.component.html`.

**Comment by blasus** [comment]
Any news from this? It's affecting the version 7.3 too, angular 11. The only way to workaround is to stop the build and run it again, hmr will make the error appears, breaking some modules, e.g. @nativescript/theme

**Comment by abdallahmaali** [comment]
any news, I'm just trying to convert my project and I get this error, does this project still supported !!
