### ISSUE TITLE
Native script migration to 7.0 Build failed in iOS

### ISSUE THREAD

**Issue by ravindra-encoresky** [NativeScript/NativeScript#8973]
**Environment**
Native script version: 7.0.1
Node version: 10.16.0
Xcode version: 11.3.1

**Describe the bug**

**Here are the dependencies I'm using- my package.json file**

`{
  "name": "MyApp",
  "version": "1.4.11",
  "description": "My App",
  "author": "xyzzy",
  "license": "MIT",
  "dependencies": {
    "@nativescript/core": "7.0.0",
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/webpack": "3.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@nstudio/nativescript-snackbar": "1.0.0",
    "@vue/devtools": "^5.0.0-beta.3",
    "axios": "^0.19.0",
    "moment": "^2.24.0",
    "nativescript-app-tour": "^2.0.1",
    "nativescript-appversion": "^1.4.4",
    "nativescript-audio": "^5.0.4",
    "nativescript-barcodescanner": "^3.2.2",
    "nativescript-bottom-navigation": "^2.0.5",
    "nativescript-exit": "^1.0.1",
    "nativescript-insomnia": "^1.2.3",
    "nativescript-local-notifications": "^4.2.1",
    "nativescript-localize": "^4.2.2",
    "nativescript-orientation": "^2.2.4",
    "nativescript-platform-css": "^1.6.9",
    "nativescript-sentry": "^1.9.1",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-toasty": "^2.0.1",
    "nativescript-ui-chart": "^8.0.2",
    "nativescript-ui-listview": "^9.0.3",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-vue": "^2.4.0",
    "net": "^1.0.2",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.3",
    "@nativescript/types": "7.0.0",
    "babel-loader": "^8.0.6",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-vue-template-compiler": "^2.4.0",
    "node-sass": "4.12.0",
    "ts-patch": "^1.3.0",
    "vue-loader": "^15.6.4"
  },
  "main": "main"
}
`
thanks in advance.

**Comment by jessorlisa** [comment]
I recommend you take a look at the compatibility chart listed [here](https://nativescript.org/blog/nativescript-6-7-xcode-compatibility/).

**Comment by ravindra-encoresky** [comment]
@jessorlisa thanks for guiding me and now I've updated the Xcode version but unfortunately my builds still don't work

the new error is 

`*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: Class constructor Observable cannot be invoked without 'new'
 at 
	SharedNotificationDelegateCommon(file:///app/vendor.js:104217:38)
	at SharedNotificationDelegateImpl(file:///app/vendor.js:104268:24)
	at ../node_modules/nativescript-shared-notification-delegate/shared-notification-delegate.js(file:///app/vendor.js:104483:16)
	at __webpack_require__(file:///app/runtime.js:75:30)
	at ../node_modules/nativescript-local-notifications/local-notifications.js(file:///app/vendor.js:102210:51)
	at __webpack_require__(file:///app/runtime.js:75:30)`

thanks for the help.
