### ISSUE TITLE
Unable to start the application - An uncaught Exception occurred on "main" thread

### ISSUE THREAD

**Issue by agenuario** [NativeScript/NativeScript#9074]
**Environment**
tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 7.0.11 version and is up to date.
√ Component @nativescript/core has 7.0.13 version and is up to date.
× Component @nativescript/ios is not installed.
√ Component @nativescript/android has 7.0.1 version and is up to date.

node -v
v12.18.3

package.json:
{
  "name": "@nativescript/template-hello-world-ng",
  "main": "main.js",
  "version": "7.0.6",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~3.0.0",
    "nativescript-directions": "^1.4.0",
    "nativescript-oauth2": "^3.0.1",
    "nativescript-phone": "^2.0.0",
    "nativescript-ui-calendar": "^7.0.2",
    "nativescript-ui-listview": "^9.0.4",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

Both environmento IOS and Android

**Describe the bug**
Without any change on the project configuration after installing the LTS new version of Node.js the application failed to start on both development machine (MacOs and Windows).
I installed again the Node.js v12.8.3 without success.

The application build without errors and is installed on the device, then crashes with: 

`System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify 
the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4805)
System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:165)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:150)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at com.tns.Runtime.run(Runtime.java:680)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
System.err:     ... 8 more
System.err:     at com.tns.Module.resolvePathHelper(Module.java:151)
System.err:     at com.tns.Module.bootstrapApp(Module.java:314)
System.err:     ... 12 more
Successfully synced application org.nativescript.teamschedulemobile on device UBE0216121001237`

**Comment by maxlam79** [comment]
Encountered same error here with version 7.0.11

I'm running it on a real android phone (Android 10, not emulator).

Did a:
`ns create My-Blank-Ng --template @nativescript/template-blank-ng`

After which, `ns run android` and received the following:

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6867)
System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:245)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:237)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7817)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at com.tns.Module.bootstrapApp(Module.java:316)
System.err:     at com.tns.Runtime.run(Runtime.java:680)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6862)
System.err:     ... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
System.err:     at com.tns.Module.resolvePathHelper(Module.java:151)
System.err:     at com.tns.Module.bootstrapApp(Module.java:314)
System.err:     ... 12 more

**Comment by xuhcc** [comment]
I see the same error message when I run `tns debug android` for the first time after cleaning the project with `ns clean`. The second run succeeds. Though I'm not sure if it has the same root cause because this error message is very generic.

```
✔ Component nativescript has 7.0.11 version and is up to date.
✔ Component @nativescript/core has 7.0.13 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.1 version and is up to date.
@nativescript/angular": "~10.1.7"
```

**Comment by Robernator** [comment]
I also get the same error for iOS.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.

Someone has a answer for this?

**Comment by Robernator** [comment]
I have changed  "main": "main.tns.js", 
to "main": "main.tns.ts", 
in the package.json than it works for android
