### ISSUE TITLE
RadListView Groups Break Reordering

### ISSUE THREAD

**Issue by botchkin** [NativeScript/NativeScript#9123]
**Environment**
 - CLI: 7.1.1
 - Cross-platform modules: ?
 - Android Runtime: 7.0.1
 - iOS Runtime: N/A
 - XCode Version: ?
 - Plugin(s): nativescript-uil-istview 9.0.4

**Describe the bug**
Using multiple groups in RadList view with reorder enabled causes a crash. I was able to re-create the bug in the playground with a link below. It appears that if the radlistview is inside a scrollview then the software will not crash but my understanding is that you should not be using a scrollview. As soon as I change the scrollview to a stacklayout or gridlayout, then the software will crash on reorders.

**To Reproduce**
Use groups with a RadListView that has reordering enabled inside any layout other that a scrollview. I have re-ordering and grouping working separately but as soon as I use both at the same time, reordering will fail. I have occasionally seen the top item work for reordering but all subsequent items will crash with "TypeError: Cannot read property 'eachChildView' of undefine".

**Expected behavior**
Unless their is a container I am supposed to be using in place of a scroll view, I am not sure why the software is crashing

**Sample project**
https://play.nativescript.org/?template=play-js&id=xetrxL&v=2

**Additional context**

> [Pixel 2]: An uncaught Exception occurred on "main" thread.
> Calling js method getReorderHandleOverride failed
> TypeError: Cannot read property 'eachChildView' of undefined
> 
> StackTrace:
> ExtendedReorderWithHandlesBehavior.getReorderHandleOverride(file:///data/user/0/org.nativescript.preview/files/app/tns_modules/nativescript-ui-listview/ui-listview.js:61:27)
> at com.tns.Runtime.callJSMethodNative(Native Method)
> at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
> at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
> at com.tns.Runtime.callJSMethod(Runtime.java:1160)
> at com.tns.Runtime.callJSMethod(Runtime.java:1138)
> at com.tns.Runtime.callJSMethod(Runtime.java:1134)
> at com.tns.gen.com.telerik.widget.list.ReorderWithHandlesBehavior_listview_54_32_ExtendedReorderWithHandlesBehavior.getReorderHandleOverride(ReorderWithHandlesBehavior_listview_54_32_ExtendedReorderWithHandlesBehavior.java:20)
> at com.telerik.widget.list.ReorderWithHandlesBehavior.onShortPressDrag(ReorderWithHandlesBehavior.java:33)
> at com.telerik.widget.list.ListViewGestureListener.onShortPressDrag(ListViewGestureListener.java:220)
> at com.telerik.widget.list.ListViewGestureListener.onTouchEvent(ListViewGestureListener.java:103)
> at com.telerik.widget.list.RadListView.onTouchEvent(RadListView.java:555)
> at android.view.View.dispatchTouchEvent(View.java:14309)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
> at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
> at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
> at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
> at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
> at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
> at android.view.View.dispatchPointerEvent(View.java:14568)
> at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
> at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
> at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
> at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
> at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
> at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
> at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
> at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
> at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
> at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
> at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
> at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8160)
> at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8242)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
> at android.view.Choreographer.doCallbacks(Choreographer.java:796)
> at android.view.Choreographer.doFrame(Choreographer.java:724)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:223)
> at android.app.ActivityThread.main(ActivityThread.java:7656)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by botchkin** [comment]
[RadListViewGroup.zip](https://github.com/NativeScript/NativeScript/files/5756248/RadListViewGroup.zip)

Attachment containing code from the preview link
