### ISSUE TITLE
Calling js method onCreateView failed

### ISSUE THREAD

**Issue by wendt88** [NativeScript/NativeScript#9150]
**Environment**
nativescript: 7.1.2 
@nativescript/core: 7.1.0
@nativescript/ios: 7.0.6
@nativescript/android: 7.0.1

**Describe the bug**
since NS 7, the app crashes on one of our clients (Galaxy A40 Android 10) in 9 of 10 cases. I tested with an A50, Android 10, without problems, and also on all other devices the app works fine.
He tried already to reinstall, or clear data and cache, without success.
The app crashes immediately after the Launchscreen.
Inside the crashlytics console I have a lot of errors from the same device (Galaxy A4 Android 100):

```
Fatal Exception: com.tns.NativeScriptException: Calling js method onCreateView failed
Error: java.lang.NoSuchMethodError: no non-static method "Lorg/nativescript/widgets/GridLayout;.addView(Ljava/lang/String;)Ljava/io/File;"
       at com.tns.Runtime.callJSMethodNative(Runtime.java)
       at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
       at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
       at com.tns.Runtime.callJSMethod(Runtime.java:1175)
       at com.tns.Runtime.callJSMethod(Runtime.java:1153)
       at com.tns.Runtime.callJSMethod(Runtime.java:1149)
       at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

```
Caused by java.lang.NoSuchMethodError: no non-static method "Lorg/nativescript/widgets/GridLayout;.addView(Ljava/lang/String;)Ljava/io/File;"
       at com.tns.Runtime.callJSMethodNative(Runtime.java)
       at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
       at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
       at com.tns.Runtime.callJSMethod(Runtime.java:1175)
       at com.tns.Runtime.callJSMethod(Runtime.java:1153)
       at com.tns.Runtime.callJSMethod(Runtime.java:1149)
       at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

is there anything i can do?

**Comment by NathanaelA** [comment]
Can you do a `ns clean` and see if that fixes the issue?    We did have an issue with an earlier runtime, 7.0.1 should have fixed this issue; but it is possible that somehow you are running one of the older runtimes...

**Comment by wendt88** [comment]
the problem is, that it occures for an app from google play
so i should try to run `ns clean` and create a new version?

**Comment by NathanaelA** [comment]
Yes, or just create a new version and run it locally if you can duplicate the issue locally w/o having to upload it to google.

**Comment by wendt88** [comment]
the problem is, that I am not able to reproduce it... it occurs on one of our client who get the app from google play
so I try to create a new version, thx

**Comment by wendt88** [comment]
created a new version by running `ns clean` before, but still the same error inside crashlytics console

**Comment by wendt88** [comment]
@NathanaelA Any news on this? now I have the second device (galaxy A20) on which it occurs (always from crashlytics, because I'm not able to reproduce it locally).
created a new version twice, with `ns clean`, tried `ns update` and `npm update` before

**Comment by wendt88** [comment]
@NathanaelA now we bought our own Samsung Galaxy A40 to be able to debug that blocking issue.
 the error is:
  ```
Calling js method onCreateView failed
Error: java.lang.NoSuchMethodError: no non-static method "Lorg/nativescript/widgets/GridLayout;.addView(Ljava/lang/String;)Ljava/io/File;"
```

stack trace:
```
_addViewToNativeVisualTree(.../files/app/vendor.js:2:107747)
	at _addViewToNativeVisualTree(.../files/app/vendor.js:2:1250215)
	at _setupUI(.../files/app/vendor.js:2:132531)
	at (.../files/app/vendor.js:2:132625)
	at eachChildView(.../files/app/vendor.js:2:953214)
	at eachChildView(.../files/app/vendor.js:2:1007876)
	at eachChild(.../files/app/vendor.js:2:194234)
	at _setupUI(.../files/app/vendor.js:2:132608)
	at _addViewCore(.../files/app/vendor.js:2:130787)
	at _addView(.../files/app/vendor.js:2:130516)
	at onCreateView(.../files/app/vendor.js:2:602184)
	at onCreateView(.../files/app/vendor.js:2:2499941)
```

the error occurs in production mode ONLY and by getting a look in my `vendor.js` the error comes from `@nativescript\core\ui\core\view\index.android.js` -> method `_addViewToNativeVisualTree` -> `this.nativeViewProtected.addView(child.nativeViewProtected, atIndex)`

**Comment by NathanaelA** [comment]
Can you try:
1. ns platform remove android
2. ns platform add android@latest
3. ns clean
4. ns run android 

Does the issue still occur?

**Comment by wendt88** [comment]
I'm not allowed to share our repo and was not able to reproduce it quickly in an other repo, but I found the error after a few days of debug: in the root component, inside the [`mounted` hook](https://vuejs.org/v2/api/#mounted) I did some initializations, like firebase init, creating of sqlite tables and so on.
some of those things I outsourced in a [worker thread](https://docs.nativescript.org/core-concepts/multithreading-model) for performance.
I had to wrap the worker call inside a `setTimeout` with 0ms, otherwise the worker does not eaven started. but on samsung galaxy A40 and A20 caused the other error (above) wich crashed the app. a larger timeout (200ms) solved it, but to be secure I moved the code from the worker to the main thread.
maby with that information you are able to find something to make it robuster

**Comment by CatchABus** [comment]
> I'm not allowed to share our repo and was not able to reproduce it quickly in an other repo, but I found the error after a few days of debug: in the root component, inside the [`mounted` hook](https://vuejs.org/v2/api/#mounted) I did some initializations, like firebase init, creating of sqlite tables and so on. some of those things I outsourced in a [worker thread](https://docs.nativescript.org/core-concepts/multithreading-model) for performance. I had to wrap the worker call inside a `setTimeout` with 0ms, otherwise the worker does not eaven started. but on samsung galaxy A40 and A20 caused the other error (above) wich crashed the app. a larger timeout (200ms) solved it, but to be secure I moved the code from the worker to the main thread. maby with that information you are able to find something to make it robuster

Your detailed explanation helped track a multi-threading problem in metadata-generator.
A fix was added in `@nativescript/android@8.5.0`
