### ISSUE TITLE
[node 15]: cli - ns create issue

### ISSUE THREAD

**Issue by matafonoff** [NativeScript/NativeScript#9184]
**Environment**
 - Linux <removed> 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - CLI: 7.1.2

**Describe the bug**
Could not create project from cli via `ns create test-app --template @nativescript/template-blank-ng`

`ns create test-app --ng` Does not work as well

But `ng new test-app` works fine as well as `ns create test-app --vue` 

**To Reproduce**
- install Native script
- try to create NativeScript app with ng template `ns create test-app --ng`

could re reproduced on "clean" os, for instance - docker.

Dockerfile
```
FROM node:alpine
RUN  npm install nativescript -g
RUN ns create test-app --ng
```

**Expected behavior**
project created

**Additional context**
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @nativescript/template-hello-world-ng@7.0.9
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.11.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@11.0.9
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~11.0.0" from the root project
npm ERR!   peer @angular/core@"11.0.9" from @angular/animations@11.0.9
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"~11.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-30T10_37_26_797Z-debug.log
```

/root/.npm/_logs/2021-01-30T10_37_26_797Z-debug.log:

```
0 verbose cli [ '/usr/local/bin/nod0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
1 info using npm@7.4.3
2 info using node@v15.7.0
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/test-app/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session 0ea106d8da56f6e1
20 timing npm:load Completed in 21ms
21 timing arborist:ctor Completed in 1ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 21ms
24 timing idealTree:userRequests Completed in 0ms
25 silly idealTree buildDeps
26 silly fetch manifest @angular/animations@~11.0.0
27 http fetch GET 200 https://registry.npmjs.org/@angular%2fanimations 474ms
28 silly fetch manifest @angular/core@~11.0.0
29 http fetch GET 200 https://registry.npmjs.org/@angular%2fcore 141ms
30 silly fetch manifest rxjs@^6.6.0
31 http fetch GET 200 https://registry.npmjs.org/rxjs 85ms
32 silly fetch manifest zone.js@~0.11.1
33 http fetch GET 200 https://registry.npmjs.org/zone.js 82ms
34 timing idealTree Completed in 881ms
35 timing command:install Completed in 897ms
36 verbose stack Error: unable to resolve dependency tree
36 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:25)
36 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1041:36)
36 verbose stack     at async Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1031:11)
36 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:796:11)
36 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack     at async Promise.all (index 1)
36 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:124:5)
36 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
37 verbose cwd /test-app
38 verbose Linux 5.4.0-65-generic
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
40 verbose node v15.7.0
41 verbose npm  v7.4.3
42 error code ERESOLVE
43 error ERESOLVE unable to resolve dependency tree
44 error
45 error While resolving: @nativescript/template-hello-world-ng@7.0.9
45 error Found: zone.js@0.11.3
45 error node_modules/zone.js
45 error   zone.js@"~0.11.1" from the root project
45 error
45 error Could not resolve dependency:
45 error peer zone.js@"~0.10.3" from @angular/core@11.0.9
45 error node_modules/@angular/core
45 error   @angular/core@"~11.0.0" from the root project
45 error   peer @angular/core@"11.0.9" from @angular/animations@11.0.9
45 error   node_modules/@angular/animations
45 error     @angular/animations@"~11.0.0" from the root project
45 error
45 error Fix the upstream dependency conflict, or retry
45 error this command with --force, or --legacy-peer-deps
45 error to accept an incorrect (and potentially broken) dependency resolution.
45 error
45 error See /root/.npm/eresolve-report.txt for a full report.
46 verbose exit 1
```

 /root/.npm/eresolve-report.txt:

```
# npm resolution error report

2021-01-30T10:52:01.963Z

While resolving: @nativescript/template-hello-world-ng@7.0.9
Found: zone.js@0.11.3
node_modules/zone.js
  zone.js@"~0.11.1" from the root project

Could not resolve dependency:
peer zone.js@"~0.10.3" from @angular/core@11.0.9
node_modules/@angular/core
  @angular/core@"~11.0.0" from the root project
  peer @angular/core@"11.0.9" from @angular/animations@11.0.9
  node_modules/@angular/animations
    @angular/animations@"~11.0.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "zone.js",
    "version": "0.11.3",
    "whileInstalling": {
      "name": "@nativescript/template-hello-world-ng",
      "version": "7.0.9",
      "path": "/test-app"
    },
    "location": "node_modules/zone.js",
    "dependents": [
      {
        "type": "prod",
        "name": "zone.js",
        "spec": "~0.11.1",
        "from": {
          "location": "/test-app"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "zone.js",
    "spec": "~0.10.3",
    "error": "INVALID",
    "from": {
      "name": "@angular/core",
      "version": "11.0.9",
      "whileInstalling": {
        "name": "@nativescript/template-hello-world-ng",
        "version": "7.0.9",
        "path": "/test-app"
      },
      "location": "node_modules/@angular/core",
      "dependents": [
        {
          "type": "prod",
          "name": "@angular/core",
          "spec": "~11.0.0",
          "from": {
            "location": "/test-app"
          }
        },
        {
          "type": "peer",
          "name": "@angular/core",
          "spec": "11.0.9",
          "from": {
            "name": "@angular/animations",
            "version": "11.0.9",
            "whileInstalling": {
              "name": "@nativescript/template-hello-world-ng",
              "version": "7.0.9",
              "path": "/test-app"
            },
            "location": "node_modules/@angular/animations",
            "dependents": [
              {
                "type": "prod",
                "name": "@angular/animations",
                "spec": "~11.0.0",
                "from": {
                  "location": "/test-app"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

**Comment by rigor789** [comment]
See https://github.com/NativeScript/nativescript-cli/issues/5482#issuecomment-765526592
