### ISSUE TITLE
Nativescript module CSSutils undefined

### ISSUE THREAD

**Issue by PaulMabille** [NativeScript/NativeScript#9200]
Hello,
I've been droped on a nativescript project, when i run 'tns run ios' i can build project though the app crach just after it start.
The error is dropped in the compiled code (vendor.js) so I don't know how to find it's origin in the repository.

```
/* harmony import */ var _nativescript_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("../node_modules/@nativescript/core/index.js");

const removeClass = _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["CSSUtils"].removeFromRootViewCssClasses;
```

NativeScript encountered a fatal error: TypeError: undefined is not an object

[edit :] I forgot to mention i use
nativescript 6.8.0
tns-ios: 6.5.4
xcode: 12.3

If anyone can lead me to the origin of this error.
Thank you for helping me on this.

**Comment by rigor789** [comment]
Post your `package.json` - the info above is not enough to pinpoint what could be the cause.

**Comment by PaulMabille** [comment]
```
{
  "name": "",
  "license": "",
  "version": "0.0.0",
  "description": "NativeScript application helping young girls track their menstruations",
  "author": "",
  "nativescript": {
    "id": "org.nativescript.onaia",
    "tns-android": {
      "version": "6.5.3"
    },
    "tns-ios": {
      "version": "6.5.2"
    }
  },
  "scripts": {
    "lint": "tslint \"src/**/*.ts\"",
    "preview": "tns preview",
    "prepare:android": "tns prepare android",
    "prepare:ios": "tns prepare ios",
    "build:android:dev": "tns build android",
    "build:android:qualif": "tns build android --env.environment='qualif'",
    "build:android:prod": "tns build android --env.environment='prod'",
    "build:ios": "tns build ios",
    "build:ios:qualif": "tns build ios --env.environment='qualif'",
    "run:android:dev": "tns run android",
    "run:android:qualif": "tns run android --env.environment='qualif'",
    "debug:android": "tns debug android",
    "run:ios:dev": "tns run ios",
    "run:ios:qualif": "tns run ios --env.environment='qualif'",
    "debug:ios": "tns debug ios"
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@bdn/crypto": "^1.3.1",
    "@nativescript/theme": "^2.3.4",
    "@ngx-translate/core": "^12.1.2",
    "apollo-angular": "^1.10.0",
    "apollo-angular-link-http": "^1.11.0",
    "apollo-angular-link-persisted": "^1.3.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-http-common": "^0.2.16",
    "apollo-link-ws": "^1.0.20",
    "graphql": "^15.5.0",
    "graphql-tag": "^2.11.0",
    "lodash": "^4.17.20",
    "nativescript-angular": "~8.21.0",
    "nativescript-pdf-view": "^2.4.3",
    "nativescript-permissions": "^1.3.11",
    "nativescript-websockets": "^1.5.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.3",
    "subscriptions-transport-ws": "^0.9.18",
    "tns-core-modules": "^6.5.24",
    "tslib": "^1.14.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "^8.3.29",
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^9.0.0",
    "@ngtools/webpack": "8.2.0",
    "nativescript": "^6.8.0",
    "nativescript-dev-webpack": "~1.5.0",
    "node-sass": "^4.7.1",
    "tns-android": "6.5.3",
    "tns-ios": "6.5.4",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  }
}

```

**Comment by rigor789** [comment]
Thanks - the code snippet you posted doesn't seem related to the crash, can you post the stacktrace of the crash?

**Comment by PaulMabille** [comment]
Sure, thank you again for helping me.

```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (ios)
Successfully transferred all files on device BDC7AF03-5A6A-4D05-8101-F5046CCE1B85.
Restarting application on device BDC7AF03-5A6A-4D05-8101-F5046CCE1B85...
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.myapp>
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10cd0262e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10cd54524 -[TNSRuntime executeModule:referredBy:]
3   0x10c577163 main
4   0x7fff202593e9 start
5   0x1
JavaScript stack trace:
../node_modules/@nativescript/theme/index.js(file: node_modules/@nativescript/theme/index.js:3:28)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at fn(file: src/webpack/bootstrap:120:0)
at file:///app/bundle.js:5863:96
at ./main.ts(file:///app/bundle.js:5918:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/theme/index.js:3:28: JS ERROR TypeError: undefined is not an object (evaluating '_nativescript_core__WEBPACK_IMPORTED_MODULE_0__["CSSUtils"].removeFromRootViewCssClasses')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating '_nativescript_core__WEBPACK_IMPORTED_MODULE_0__["CSSUtils"].removeFromRootViewCssClasses')
at
../node_modules/@nativescript/theme/index.js(file: node_modules/@nativescript/theme/index.js:3:28)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at fn(file: src/webpack/bootstrap:120:0)
at file:///app/bundle.js:5863:96
at ./main.ts(file:///app/bundle.js:5918:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
1   libobjc.A.dylib   <…>
NativeScript caught signal 6.
Native Stack:
1   0x10cd53171 sig_handler(int)
2   0x7fff60c83d7d _sigtramp
3   0x1
4   0x7fff200fab94 abort
5   0x7fff20252818 abort_message
6   0x7fff20243e7d demangling_unexpected_handler()
7   0x7fff201780d1 _objc_terminate()
8   0x7fff20251c47 std::__terminate(void (*)())
9   0x7fff202543d0 __cxa_get_exception_ptr
10  0x7fff20254397 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff20177f9c _objc_exception_destructor(void*)
12  0x10cd02b6f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x10cd54524 -[TNSRuntime executeModule:referredBy:]
14  0x10c577163 main
15  0x7fff202593e9 start
16  0x1
JS Stack:
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.myapp>
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x108f7e62e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x108fd0524 -[TNSRuntime executeModule:referredBy:]
3   0x1087f3163 main
4   0x7fff202593e9 start
5   0x1
JavaScript stack trace:
../node_modules/@nativescript/theme/index.js(file: node_modules/@nativescript/theme/index.js:3:28)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at fn(file: src/webpack/bootstrap:120:0)
at file:///app/bundle.js:5863:96
at ./main.ts(file:///app/bundle.js:5918:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/theme/index.js:3:28: JS ERROR TypeError: undefined is not an object (evaluating '_nativescript_core__WEBPACK_IMPORTED_MODULE_0__["CSSUtils"].removeFromRootViewCssClasses')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating '_nativescript_core__WEBPACK_IMPORTED_MODULE_0__["CSSUtils"].removeFromRootViewCssClasses')
at
../node_modules/@nativescript/theme/index.js(file: node_modules/@nativescript/theme/index.js:3:28)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at fn(file: src/webpack/bootstrap:120:0)
at file:///app/bundle.js:5863:96
at ./main.ts(file:///app/bundle.js:5918:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
1   libobjc.A.dylib   <…>
NativeScript caught signal 6.
Native Stack:
1   0x108fcf171 sig_handler(int)
2   0x7fff60c83d7d _sigtramp
3   0x1
4   0x7fff200fab94 abort
5   0x7fff20252818 abort_message
6   0x7fff20243e7d demangling_unexpected_handler()
7   0x7fff201780d1 _objc_terminate()
8   0x7fff20251c47 std::__terminate(void (*)())
9   0x7fff202543d0 __cxa_get_exception_ptr
10  0x7fff20254397 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff20177f9c _objc_exception_destructor(void*)
12  0x108f7eb6f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x108fd0524 -[TNSRuntime executeModule:referredBy:]
14  0x1087f3163 main
15  0x7fff202593e9 start
16  0x1
```

**Comment by PaulMabille** [comment]
If i comment this line on vendor.js, the program run correctly :
`const removeClass = _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["CSSUtils"].removeFromRootViewCssClasses;`
This solution is not satisfying as i don't like to modify the output of tns build.

**Comment by lostation** [comment]
Same here... I was using Theme.setMode(Theme.Light); in app.component.tns.ts start file and I also got error like 

```
StackTrace: 
System.err: ../node_modules/@nativescript/theme/index.js(file: node_modules/@nativescript/theme/index.js:3:28)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err:     at ./app/app.component.ts(file:///data/data/com.myapp.mobileapp/files/app/bundle.js:4198:77)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err:     at ./app/app.module.ts(file:///data/data/com.myapp.mobileapp/files/app/bundle.js:4616:73)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err:     at (file:///data/data/com.myapp.mobileapp/files/app/bundle.js:33093:73)
System.err:     at ./main.tns.ts(file:///data/data/com.myapp.mobileapp/files/app/bundle.js:33148:30)
System.err:     at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err:     at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/com.myapp.mobileapp/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'removeFromRootViewCssClasses' of undefined
```

So from @nativescript/theme index.js file 

```
import { Application, **CSSUtils**, Device, isAndroid, Screen, View, Frame } from "@nativescript/core";  

const removeClass = CSSUtils.removeFromRootViewCssClasses;
```

CSSUtils is deprecated for NS6, check from @nativescript/core/css/system-classes if you have removeFromRootViewCssClasses or CSSUtils from @nativescript/core

Solution -> update to 

- @nativescript/theme@3.0.1
- tns-core-modules@6.5.27
- @nativescript/core@6.5.27

cheers

**Comment by PaulMabille** [comment]
It solved my problem, thank you a lot!
