### ISSUE TITLE
Nativescript Playground not working on iOS

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#9201]
**Environment**
Nativescript Playground
IOS: 14.4

**Describe the bug**
Nativescript playground for IOS does not work. I have tried this [example](https://play.nativescript.org/?template=play-ng&id=kIGdTE) for android and it works perfectly, then I have tried with iphone and when scanning the scanner closes and then it does nothing. I have also tried with an ipad and it doesn't work either.

**Comment by lukaszmojek** [comment]
Hi, I faced the same issue and managed to resolve it.
I needed to also install `NativeScript Preview` application too and everything started to work just fine.
I guess, there is a missing modal, because it is confusing indeed.
Hope that works for you as well.

**Comment by vallemar** [comment]
@lukaszmojek  it worked!!  but does this put it somewhere as a requirement?

**Comment by asharghi** [comment]
On Android I got a message saying that the Preview app is required, but not on iOS so I guess that message is missing

**Comment by danawoodman** [comment]
@NathanWalker @rigor789 were you guys aware that the iOS app has this issue? I've got the same issue as all docs say to use the Playground app but that app says nothing about the Preview app so it seems its broken (hence all the bad reviews on the app store)

**Comment by vallemar** [comment]
> hence all the bad reviews on the app store
I think the same.

In addition to indicating it, I think that if the user does not have NativeScript Preview installed, he should jump a warning again (So you can see it yes or yes)

**Comment by rigor789** [comment]
@danawoodman will need to check, I thought It should open the AppStore if not installed. Just haven't had time to deal with it yet, it's been very busy prepping for 8.0.

**Comment by danawoodman** [comment]
This is on a brand new install so not sure. A simple message would go a long way too I think in case it breaks again in the future 😄

**Comment by pvyUlterra** [comment]
I have both Nativescript Playground and Preview installed on iOS 14.4. Playground is always displays the No Internet Connection error. Tried un-installing both and then installing them again but it didn't help.

**Comment by cassandrafsmith** [comment]
> Hi, I faced the same issue and managed to resolve it.
> I needed to also install `NativeScript Preview` application too and everything started to work just fine.
> I guess, there is a missing modal, because it is confusing indeed.
> Hope that works for you as well.

Thank you!!

**Comment by chriswayg** [comment]
If not even the demo app advertised on the main page of Nativescript works, why should I explore this framework any further? I think this points to some foundational problems! No one has responded to this bug since February 2021.

https://play.nativescript.org/

I have both the Nativescript Playground and Preview apps installed on two devices: iOS 14.4 on an iPhone XS Max as well as on iOS 12.5 on an iPad. They both crash in the same way:

```
[Timothy 's iPad]: 2021-06-11 15:43:32.364 nsplaydev[682:58602] ***** Fatal JavaScript exception - application has been terminated. *****
2021-06-11 15:43:32.553 nsplaydev[682:58602] Native stack trace:
1 0x101a46348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2 0x101a90428 -[TNSRuntime executeModule:referredBy:]
3 0x10185a25c -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4 0x100f17524
5 0x1a6a018e0 <redacted>
2021-06-11 15:43:32.567 nsplaydev[682:58602] JavaScript stack trace:
2021-06-11 15:43:32.567 nsplaydev[682:58602] anonymous(file:///app/tns_modules/react-nativescript/dist/nativescript-vue-next/runtime/registry.js:61:14)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/client/HostConfig.js:18:25)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/index.js:7:27)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/app.js:6:32)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/__main.js:5:8)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2021-06-11 15:43:32.567 nsplaydev[682:58602] JavaScript error:
file:///app/tns_modules/react-nativescript/dist/nativescript-vue-next/runtime/registry.js:61:14: JS ERROR ReferenceError: Can't find variable: __TEST__
2021-06-11 15:43:32.574 nsplaydev[682:58602] PlayLiveSync: Uncaught Exception
2021-06-11 15:43:32.577 nsplaydev[682:58602] *** JavaScript call stack:
(

)
2021-06-11 15:43:32.578 nsplaydev[682:58602] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: __TEST__
at
anonymous(file:///app/tns_modules/react-nativescript/dist/nativescript-vue-next/runtime/registry.js:61:14)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/client/HostConfig.js:18:25)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/index.js:7:27)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/app.js:6:32)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/__main.js:5:8)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x1a6fb2180 0x1a618a9f8 0x101a46820 0x101a90428 0x10185a25c 0x100f17524 0x1a6a018e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
2021-06-11 15:43:32.579 nsplaydev[682:58602] PlayLiveSync: Uncaught Exception
```

**Comment by chriswayg** [comment]
@NathanWalker @rigor789, if not even the demo app promoted prominently on the main page of Nativescript works, this gives a very bad first impression of this interesting framework. I suspect that this points to some foundational problems. Apparently this bug has not been properly addressed or fixed since February 2021.

https://play.nativescript.org/

I have both the current Nativescript Playground and Preview apps installed on two devices: iOS 14.4 on an iPhone XS Max as well as on iOS 12.5 on an iPad. They both crash in the same way:

```
[Timothy 's iPad]: 2021-06-11 15:43:32.364 nsplaydev[682:58602] ***** Fatal JavaScript exception - application has been terminated. *****
2021-06-11 15:43:32.553 nsplaydev[682:58602] Native stack trace:
1 0x101a46348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2 0x101a90428 -[TNSRuntime executeModule:referredBy:]
3 0x10185a25c -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4 0x100f17524
5 0x1a6a018e0 <redacted>
2021-06-11 15:43:32.567 nsplaydev[682:58602] JavaScript stack trace:
2021-06-11 15:43:32.567 nsplaydev[682:58602] anonymous(file:///app/tns_modules/react-nativescript/dist/nativescript-vue-next/runtime/registry.js:61:14)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/client/HostConfig.js:18:25)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/index.js:7:27)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/app.js:6:32)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/__main.js:5:8)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2021-06-11 15:43:32.567 nsplaydev[682:58602] JavaScript error:
file:///app/tns_modules/react-nativescript/dist/nativescript-vue-next/runtime/registry.js:61:14: JS ERROR ReferenceError: Can't find variable: __TEST__
2021-06-11 15:43:32.574 nsplaydev[682:58602] PlayLiveSync: Uncaught Exception
2021-06-11 15:43:32.577 nsplaydev[682:58602] *** JavaScript call stack:
(

)
2021-06-11 15:43:32.578 nsplaydev[682:58602] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: __TEST__
at
anonymous(file:///app/tns_modules/react-nativescript/dist/nativescript-vue-next/runtime/registry.js:61:14)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/client/HostConfig.js:18:25)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/tns_modules/react-nativescript/dist/index.js:7:27)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/app.js:6:32)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
at require([native code])
at anonymous(file:///app/__main.js:5:8)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x1a6fb2180 0x1a618a9f8 0x101a46820 0x101a90428 0x10185a25c 0x100f17524 0x1a6a018e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
2021-06-11 15:43:32.579 nsplaydev[682:58602] PlayLiveSync: Uncaught Exception
```

**Comment by teejay3** [comment]
Any update on this problem?
Yesterday I installed ns on Windows and macOS and when I try to preview app with `ns preview` got error on iPhone (both Preview and Playground apps installed):
`2021-06-27 01:57:26.803 nsplaydev[327:24031] Internal error unloading bundle CFBundle 0x154e374d0 </System/Library/Frameworks/WebKit.framework> (loaded)
CONSOLE WARN file:///app/vendor.js:44678:14: Objective-C class name "UIScrollViewDelegateImpl" is already in use - using "UIScrollViewDelegateImpl1" instead.
2021-06-27 01:57:26.915 nsplaydev[327:24031] PlayLiveSync: applicationDidFinishLaunching
2021-06-27 01:57:26.922 nsplaydev[327:24031] Internal error unloading bundle CFBundle 0x154e5bfd0 </System/Library/Frameworks/QuartzCore.framework> (loaded)
2021-06-27 01:57:26.953 nsplaydev[327:24031] ***** Fatal JavaScript exception - application has been terminated. *****
2021-06-27 01:57:26.954 nsplaydev[327:24031] Native stack trace:
1   0x100786348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1007c0434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10132b388 ffi_closure_SYSV_inner
4   0x10132c1b4 .Ldo_closure
5   0x1837d0dfc <redacted>
6   0x1837d061c <redacted>
7   0x1837d039c <redacted>
8   0x183839414 <redacted>
9   0x18370e6c8 _CFXNotificationPost
10  0x18411680c <redacted>
11  0x188c3642c <redacted>
12  0x188c3a5f0 <redacted>
13  0x188c37764 <redacted>
14  0x1851cf7ac <redacted>
15  0x1851cf618 <redacted>
16  0x1851cf9c8 <redacted>
17  0x1837e509c <redacted>
18  0x1837e4b30 <redacted>
19  0x1837e2830 <redacted>
20  0x18370cc50 CFRunLoopRunSpecific
21  0x1889ff94c <redacted>
22  0x1889fa088 UIApplicationMain
23  0x10132c044 ffi_call_SYSV
24  0x10132aae8 ffi_call_int
25  0x10132a648 ffi_call
26  0x1007493d8 NativeScript::FunctionWrapper::call(JSC::ExecState*)
27  0x1012f7b10 llint_entry
28  0x1012f4f28 llint_entry
29  0x1012f4f28 llint_entry
30  0x1012f4f28 llint_entry
31  0x1012f4e80 llint_entry
2021-06-27 01:57:26.964 nsplaydev[327:24031] JavaScript stack trace:
2021-06-27 01:57:26.964 nsplaydev[327:24031] loadInternal(file:///app/vendor.js:17857:79)
at createViewFromEntry(file:///app/vendor.js:17789:53)
at createRootView(file:///app/vendor.js:1878:92)
at setWindowContent(file:///app/vendor.js:1819:40)
at notifyAppStarted(file:///app/vendor.js:1730:38)
at didFinishLaunchingWithOptions(file:///app/vendor.js:1713:30)
at didFinishLaunchingWithOptions([native code])
at file:///app/vendor.js:1603:32
at UIApplicationMain([native code])
at run(file:///app/vendor.js:1897:26)
at ./app/app.ts(file:///app/bundle.js:62:64)
at __webpack_require__(file:///app/runtime.js:28:37)
at __webpack_exec__(file:///app/bundle.js:280:58)
at file:///app/bundle.js:281:159
at file:///app/runtime.js:136:23
at file:///app/bundle.js:281:48
at anonymous(file:///app/bundle.js:286:3)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2021-06-27 01:57:26.965 nsplaydev[327:24031] JavaScript error:
file:///app/vendor.js:17857:79: JS ERROR Error: Failed to load component from module: app-root
2021-06-27 01:57:26.970 nsplaydev[327:24031] PlayLiveSync: Uncaught Exception
2021-06-27 01:57:26.971 nsplaydev[327:24031] *** JavaScript call stack:
(
	0   UIApplicationMain@[native code]
	1   run@file:///app/vendor.js:1897:26
	2   ./app/app.ts@file:///app/bundle.js:62:64
	3   __webpack_require__@file:///app/runtime.js:28:37
	4   __webpack_exec__@file:///app/bundle.js:280:58
	5   @file:///app/bundle.js:281:159
	6   @file:///app/runtime.js:136:23
	7   @file:///app/bundle.js:281:48
	8   anonymous@file:///app/bundle.js:286:3
	9   evaluate@[native code]
	10  moduleEvaluation@:1:11
	11  @:2:1
	12  asyncFunctionResume@:1:11
	13  @:24:9
	14  promiseReactionJob@:1:11
)
2021-06-27 01:57:26.971 nsplaydev[327:24031] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Failed to load component from module: app-root
 at 
loadInternal(file:///app/vendor.js:17857:79)
at createViewFromEntry(file:///app/vendor.js:17789:53)
at createRootView(file:///app/vendor.js:1878:92)
at setWindowContent(file:///app/vendor.js:1819:40)
at notifyAppStarted(file:///app/vendor.js:1730:38)
at didFinishLaunchingWithOptions(file:///app/vendor.js:1713:30)
at didFinishLaunchingWithOptions([native code])
at file:///app/vendor.js:1603:32
at UIApplicationMain([native code])
at run(file:///app/vendor.js:1897:26)
at ./app/app.ts(file:///app/bundle.js:62:64)
at __webpack_require__(file:///app/runtime.js:28:37)
at __webpack_exec__(file:///app/bundle.js:280:58)
at file:///app/bundle.js:281:159
at file:///app/runtime.js:136:23
at file:///app/bundle.js:281:48
at anonymous(file:///app/bundle.js:286:3)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x18382edb0 0x182e93f80 0x100786820 0x1007c0434 0x10132b388 0x10132c1b4 0x1837d0dfc 0x1837d061c 0x1837d039c 0x183839414 0x18370e6c8 0x18411680c 0x188c3642c 0x188c3a5f0 0x188c37764 0x1851cf7ac 0x1851cf618 0x1851cf9c8 0x1837e509c 0x1837e4b30 0x1837e2830 0x18370cc50 0x1889ff94c 0x1889fa088 0x10132c044 0x10132aae8 0x10132a648 0x1007493d8 0x1012f7b10 0x1012f4f28 0x1012f4f28 0x1012f4f28 0x1012f4e80 0x1012f4f28 0x1012f4f28 0x1012f4f28 0x1012f4f28 0x1012d65e8 0x100884e48 0x101128cb4 0x1007618f4 0x100ff99d0 0x1012f77cc 0x1012f4f28 0x1012f4f28 0x1012f4f28 0x1012f4e80 0x1012f4f28 0x1012d65e8 0x100884e48 0x101128e50 0x100ff2d9c 0x100757304 0x1007d0350 0x101b8e25c 0x1000d7524 0x1832aa8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
2021-06-27 01:57:26.972 nsplaydev[327:24031] PlayLiveSync: Uncaught Exception`

At the same time app works well with simulator and real device. And play.nativescript.org also works well.
Tested devices: iPhone 5S (iOS 9.3.5), iPhone SE (iOS 12.3.1), iPhone 7 (14.4)

**Comment by pvyUlterra** [comment]
I uninstalled then reinstalled both and it started working again.


Paul Vy | Manager, IT Application Development
ULTERRA Fort Worth
office: +1 (817) 551-9759 | mobile: +1 (817) 889-7732
ulterra.com | ***@***.***

**Comment by vallemar** [comment]
Close because this is for old preview and not apply with new preview
