### ISSUE TITLE
Error: com.tns.system.classes.loading.LookedUpClassNotFound

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/NativeScript#9228]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
```
  "dependencies": { 
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript-community/ui-pager": "^13.0.10",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "^7.2.1",
    "@nativescript/theme": "~3.0.0",
    "@nstudio/nativescript-cardview": "^2.0.1",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
    "@pscoped/ngx-pub-sub": "^3.0.2",
    "i": "^0.3.6",
    "moment": "^2.29.1",
    "nativescript-local-notifications": "^4.2.1",
    "nativescript-permissions": "^1.3.11",
    "nativescript-ripple": "^4.0.1",
    "nativescript-sqlite": "^2.6.6",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "npm": "^7.5.2",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~4.0.0",
    "@ngtools/webpack": "~11.0.0",
    "codelyzer": "~6.0.0",
    "node-sass": "^4.14.1",
    "tslint": "~6.1.3",
    "typescript": "~4.0.0"
  },
```

**Describe the bug**

I added custom receiver and i am getting error when application launch.

**To Reproduce**
Create a file in **src -> app -> sms-listener.android.ts** with the following content

```
import * as application from '@nativescript/core/application';
import * as utils from '@nativescript/core/utils/utils';

@JavaProxy("com.tns.broadcastreceivers.SmsListener")
class SmsListener extends android.content.BroadcastReceiver {
    constructor() {
        super();
        return global.__native(this);
    }
    
    onReceive(context, intent: android.content.Intent) {
        if (intent.getAction() != android.provider.Telephony.Sms.Intents.SMS_RECEIVED_ACTION) {
            return;
        }

        const pkg = utils.ad.getApplicationContext().getPackageName();
        application.android.notify({
            eventName: `${pkg}_SmsListener_onReceive`,
            object: application.android,
            data: intent
        });
    }
}
```
Add it to webpack
```
  const appComponents = [
    "@nativescript/core/ui/frame"
    , "@nativescript/core/ui/frame/activity"
    , resolve(__dirname, "src/app/sms-listener.android.ts")
  ];
```
AndroidManifiest.xml
```

	<application 
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">
		
		<receiver android:name="com.tns.broadcastreceivers.SmsListener">
			<intent-filter android:priority="999">
				<action android:name="android.provider.Telephony.SMS_RECEIVED" />
			</intent-filter>
		</receiver>

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout|locale|uiMode"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
```

But when run the app, getting following error:
```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.broadcastreceivers.SmsListener" not found.
File: (/data/data/org.nativescript.mawaqif/files/internal/ts_helpers.js:154:25)

StackTrace: 
(/data/data/org.nativescript.mawaqif/files/internal/ts_helpers.js:154:26)
	at __decorate(/data/data/org.nativescript.mawaqif/files/internal/ts_helpers.js:13:19)
	at (file:///data/data/org.nativescript.mawaqif/files/app/vendor.js:202483:15)
	at ./app/sms-listener.ts(file:///data/data/org.nativescript.mawaqif/files/app/vendor.js:202488:30)
	at __webpack_require__(file:///data/data/org.nativescript.mawaqif/files/app/runtime.js:75:30)
	at (file:///data/data/org.nativescript.mawaqif/files/app/bundle.js:1558:1)
	at ./main.ts(file:///data/data/org.nativescript.mawaqif/files/app/bundle.js:1639:30)
	at __webpack_require__(file:///data/data/org.nativescript.mawaqif/files/app/runtime.js:75:30)
	at checkDeferredModules(file:///data/data/org.nativescript.mawaqif/files/app/runtime.js:44:23)
	at webpackJsonpCallback(file:///data/data/org.nativescript.mawaqif/files/app/runtime.js:31:19)
	at (file:///data/data/org.nativescript.mawaqif/files/app/bundle.js:2:57)
	at require(:1:266)

Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.broadcastreceivers.SmsListener" not found.


```
**Expected behavior**
App should launch normally.

**Sample project**

Use the above code

**Additional context**

I inspected the generated code and i can see its added there...
<img width="1316" alt="Capture" src="https://user-images.githubusercontent.com/10280821/108479173-d4808300-72ae-11eb-99fa-106f0d3916aa.PNG">

**Comment by triniwiz** [comment]
In [v7](https://nativescript.org/blog/nativescript-7-announcement/) you need to decorate the native extended typescript classes with `@NativeClass()` or it will not generate the java class

```ts
@NativeClass()
@JavaProxy("com.tns.broadcastreceivers.SmsListener")
class SmsListener extends android.content.BroadcastReceiver {
```

**Comment by dotnetdreamer** [comment]
Oh...this worked :( I followed documentation [ here](https://docs.nativescript.org/angular/core-concepts/android-runtime/advanced-topics/extend-application-activity). This blog post i read before but my understanding was that it is only needed for iOS...My bad..

Thanks man. You saved my weekend. Already spent 5 hours continuously...

**Comment by triniwiz** [comment]
Don’t worry new docs coming soon 😇an always happy to help
