### ISSUE TITLE
IOS Runtime Error(App Crash)

### ISSUE THREAD

**Issue by Rmadhuprasanth** [NativeScript/NativeScript#9235]
Getting below error after xcode build successfull.
 "tns-ios": {
      "version": "6.5.4"
    }
```
Project successfully built.
The build result is located at: /Users/qolsoft/Desktop/Nativescript/tailors-fresh/mzyoon-tailor/platforms/ios/build/Debug-iphoneos/mzyoontailor.ipa
Installing on device 36ff86acc4b5ffe95563e5f02a68bc9d7ae9cfe6...
Successfully installed on device with identifier '36ff86acc4b5ffe95563e5f02a68bc9d7ae9cfe6'.
Restarting application on device 36ff86acc4b5ffe95563e5f02a68bc9d7ae9cfe6...
networkd_settings_read_from_file initialized networkd settings by reading plist directly
networkd_settings_read_from_file initialized networkd settings by reading plist directly
Unzipping LiveSync folder. This could take a while...
Unzipped 148 entries in 376.870990ms.
Cache loaded with 4644 pre-cached in CacheData and 46 items in CacheExtra.
Initializing connection
Removing all cached process handles
Sending handshake request attempt #1 to server
Creating connection to com.apple.runningboard
Handshake succeeded
Identity resolved as application<org.gbmportal.tailor>
CONSOLE INFO file: node_modules/nativescript-dev-webpack/hot.js:3:0: HMR: Hot Module Replacement Enabled. Waiting for signal.
FBSWorkspace connecting to endpoint : <private>
FBSWorkspace registering source: <private>
FBSWorkspace connected to endpoint : <private>
Added observer for process assertions expiration warning: <_RBSExpirationWarningClient: 0x2832d2060>
Registering for test daemon availability notify post.
notify_get_state check indicated test daemon not ready.
CONSOLE LOG file: src/app/app.component.ts:65:18: user undefined
CONSOLE LOG file: node_modules/@angular/core/fesm5/core.js:25638:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file: src/app/authentication/login/login.component.ts:73:16: user undefined
Task <804411F1-0BEA-4E27-B600-F750412D05A3>.<1> resuming, timeouts(60.0, 604800.0) QOS(0x21) Voucher (null)
[Telemetry]: Activity <nw_activity 12:2 [CABFF782-3E97-4BD0-8A34-1AD6060EEBFB] (reporting strategy default)> on Task <804411F1-0BEA-4E27-B600-F750412D05A3>.<1> was not selected for reporting
-[SOConfigurationClient init]  on <private>
<SOServiceConnection: 0x2832f8580>: new XPC connection
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1041a2348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1041dc434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x104d47388 ffi_closure_SYSV_inner
4   0x104d481b4 .Ldo_closure
5   0x1a4871a4c <redacted>
6   0x1a48721d0 <redacted>
7   0x1a47b3fc8 <redacted>
8   0x1a47b4c60 <redacted>
9   0x1a47b5fe0 <redacted>
10  0x1a4798e78 <redacted>
11  0x1a5437398 <redacted>
12  0x1a593cdf4 <redacted>
13  0x1a5943398 <redacted>
14  0x1a594e6e8 <redacted>
15  0x1a5899d7c <redacted>
16  0x1a58c3f40 <redacted>
17  0x1a4f4a984 <redacted>
18  0x1a2642950 <redacted>
19  0x1a2641bd8 <redacted>
20  0x1a263c3f4 <redacted>
21  0x1a263bba0 CFRunLoopRunSpecific
22  0x1b93a4598 GSEventRunModal
23  0x1a4f2d2f4 <redacted>
24  0x1a4f32874 UIApplicationMain
25  0x104d48044 ffi_call_SYSV
26  0x104d46ae8 ffi_call_int
27  0x104d46648 ffi_call
28  0x1041653d8 NativeScript::FunctionWrapper::call(JSC::ExecState*)
29  0x104d13b10 llint_entry
30  0x104d10f28 llint_entry
31  0x104d10f28 llint_entry
JavaScript stack trace:
file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:278:0
at file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:366:0
at applyAllNativeSetters(file: node_modules/@nativescript/core/ui/core/properties/properties.js:1065:0)
at initNativeView(file: node_modules/@nativescript/core/ui/core/properties/properties.js:992:0)
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:647:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:278:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/page/page-common.js:128:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0
at file: node_modules/@nativescript/core/ui/page/page.ios.js:268:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0<\M-b\M^@\M-&>
JavaScript error:
Faulting in NSHTTPCookieStorage singleton
Faulting in CFHTTPCookieStorage singleton
Creating default cookie storage with default identifier
Task <804411F1-0BEA-4E27-B600-F750412D05A3>.<1> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
Connection 1: enabling TLS
Connection 1: starting, TC(0x0)
[C1 395A8D0E-BE87-4EA8-9027-771F47F18F62 Hostname#c6e09b63:443 tcp, url hash: 1f9b1e5c, tls, context: com.apple.CFNetwork.NSURLSession.{5C868E1E-3DE8-4B4D-80B0-DEFF090003C0}{(null)}{Y}{2}, proc: 84EEDFB2-05AA-30D7-863F-43F9B1BAB2A7] start
[C1 Hostname#c6e09b63:443 initial path ((null))] event: path:start @0.000s
[C1 Hostname#c6e09b63:443 waiting path (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: path:satisfied @0.000s, uuid: D98E75F2-2A71-4867-912A-F6313E18E3B5
[C1 Hostname#c6e09b63:443 in_progress resolver (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: resolver:start_dns @0.000s
nw_connection_report_state_with_handler_on_nw_queue [C1] reporting state preparing
Task <804411F1-0BEA-4E27-B600-F750412D05A3>.<1> setting up Connection 1
file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:278:0: JS ERROR TypeError: undefined is not an object (evaluating 'navBar.titleTextAttributes = (_a = {}, _a[NSForegroundColorAttributeName] = color.ios, _a)')
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   run@file: node_modules/@nativescript/core/application/application.ios.js:312:0
2   @file: node_modules/@nativescript/angular/platform-common.js:210:0
3   @file: node_modules/@nativescript/angular/platform-common.js:111:0
4   @file: node_modules/@nativescript/angular/platform-common.js:91:0
5   @file:///app/bundle.js:15652:144
6   ./main.ts@file:///app/bundle.js:15657:34
7   __webpack_require__@file: src/webpack/bootstrap:750:0
8   checkDeferredModules@file: src/webpack/bootstrap:43:0
9   webpackJsonpCallback@file: src/webpack/bootstrap:30:0
10  anonymous@file:///app/bundle.js:2:61
11  evaluate@[native code]
12  moduleEvaluation@:1:11
13  @:2:1
14  asyncFunctionResume@:1:11
15  @:24:9
16  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'navBar.titleTextAttributes = (_a = {}, _a[NSForegroundColorAttributeName] = color.ios, _a)')
at
file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:278:0
at file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:366:0
at applyAllNativeSetters(file: node_modules/@nativescript/core/ui/core/properties/properties.js:1065:0)
at initNativeView(file: node_modules/@nativescript/core/ui/core/properties/properties.js:992:0)
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:647:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:278:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/page/page-common.js:128:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0
at file: node_modules/@nativescript/core/ui/page/page.ios.js:268:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file:<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x1041eb018 sig_handler(int)
2   0x1eaed9d90 <redacted>
3   0x1eaee89e8 pthread_kill
4   0x1ab3bd8f4 abort
5   0x1b6b44cc8 <redacted>
6   0x1b6b36ca0 <redacted>
7   0x1b6a48e04 <redacted>
8   0x1b6b44154 <redacted>
9   0x1b6b46bec __cxa_get_exception_ptr
10  0x1b6b46bac <redacted>
11  0x1b6a48c7c <redacted>
12  0x1041a2820 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x1041dc434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x104d47388 ffi_closure_SYSV_inner
15  0x104d481b4 .Ldo_closure
16  0x1a4871a4c <redacted>
17  0x1a48721d0 <redacted>
18  0x1a47b3fc8 <redacted>
19  0x1a47b4c60 <redacted>
20  0x1a47b5fe0 <redacted>
21  0x1a4798e78 <redacted>
22  0x1a5437398 <redacted>
23  0x1a593cdf4 <redacted>
24  0x1a5943398 <redacted>
25  0x1a594e6e8 <redacted>
26  0x1a5899d7c <redacted>
27  0x1a58c3f40 <redacted>
28  0x1a4f4a984 <redacted>
29  0x1a2642950 <redacted>
30  0x1a2641bd8 <redacted>
31  0x1a263c3f4 <redacted>
JS Stack:
UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:15652:144
at ./main.ts(file:///app/bundle.js:15657:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob
networkd_settings_read_from_file initialized networkd settings by reading plist directly
networkd_settings_read_from_file initialized networkd settings by reading plist directly
Cache loaded with 4644 pre-cached in CacheData and 46 items in CacheExtra.
Initializing connection
Removing all cached process handles
Sending handshake request attempt #1 to server
Creating connection to com.apple.runningboard
Handshake succeeded
Identity resolved as application<org.gbmportal.tailor>
CONSOLE INFO file: node_modules/nativescript-dev-webpack/hot.js:3:0: HMR: Hot Module Replacement Enabled. Waiting for signal.
FBSWorkspace connecting to endpoint : <private>
FBSWorkspace registering source: <private>
FBSWorkspace connected to endpoint : <private>
Added observer for process assertions expiration warning: <_RBSExpirationWarningClient: 0x280ff1d40>
Registering for test daemon availability notify post.
notify_get_state check indicated test daemon not ready.
CONSOLE LOG file: src/app/app.component.ts:65:18: user undefined
CONSOLE LOG file: node_modules/@angular/core/fesm5/core.js:25638:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file: src/app/authentication/login/login.component.ts:73:16: user undefined
Task <C7D33A65-03D9-437D-A8DC-9E809856BF90>.<1> resuming, timeouts(60.0, 604800.0) QOS(0x21) Voucher (null)
[Telemetry]: Activity <nw_activity 12:2 [D87FE7A6-FD9C-4011-9DD2-CFA6E07FCB51] (reporting strategy default)> on Task <C7D33A65-03D9-437D-A8DC-9E809856BF90>.<1> was not selected for reporting
-[SOConfigurationClient init]  on <private>
<SOServiceConnection: 0x280fc7ce0>: new XPC connection
Faulting in NSHTTPCookieStorage singleton
Faulting in CFHTTPCookieStorage singleton
Creating default cookie storage with default identifier
Task <C7D33A65-03D9-437D-A8DC-9E809856BF90>.<1> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
Connection 1: enabling TLS
Connection 1: starting, TC(0x0)
[C1 A0765BEA-60CE-401B-8105-B5C539769CC4 Hostname#04020bc6:443 tcp, url hash: f9df907b, tls, context: com.apple.CFNetwork.NSURLSession.{62C79E94-6FAF-4FE4-B645-CDD071E1E688}{(null)}{Y}{2}, proc: 84EEDFB2-05AA-30D7-863F-43F9B1BAB2A7] start
[C1 Hostname#04020bc6:443 initial path ((null))] event: path:start @0.000s
[C1 Hostname#04020bc6:443 waiting path (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: path:satisfied @0.000s, uuid: C54CD0CC-5021-4C9C-AD74-A7F021B9DED8
[C1 Hostname#04020bc6:443 in_progress resolver (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: resolver:start_dns @0.000s
nw_connection_report_state_with_handler_on_nw_queue [C1] reporting state preparing
Task <C7D33A65-03D9-437D-A8DC-9E809856BF90>.<1> setting up Connection 1
[C1 Hostname#04020bc6:443 in_progress resolver (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: resolver:receive_dns @0.002s
[C1.1 IPv4#b5a8c766:443 initial path ((null))] event: path:start @0.002s
[C1.1 IPv4#b5a8c766:443 waiting path (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: path:satisfied @0.002s, uuid: B409C3BF-DF47-4B23-B38C-4EFDF859EB62
[C1.1 IPv4#b5a8c766:443 in_progress channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: flow:start_nexus @0.002s
[C1.1 IPv4#b5a8c766:443 in_progress channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] event: flow:receive_nexus @0.003s
[C1.1 IPv4#b5a8c766:443 in_progress channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] event: flow:start_connect @0.003s
tcp_output [C1.1:3] flags=[S] seq=2860249485, ack=0, win=65535 state=SYN_SENT rcv_nxt=0, snd_una=2860249485
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x104096348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1040d0434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x104c3b388 ffi_closure_SYSV_inner
4   0x104c3c1b4 .Ldo_closure
5   0x1a4871a4c <redacted>
6   0x1a48721d0 <redacted>
7   0x1a47b3fc8 <redacted>
8   0x1a47b4c60 <redacted>
9   0x1a47b5fe0 <redacted>
10  0x1a4798e78 <redacted>
11  0x1a5437398 <redacted>
12  0x1a593cdf4 <redacted>
13  0x1a5943398 <redacted>
14  0x1a594e6e8 <redacted>
15  0x1a5899d7c <redacted>
16  0x1a58c3f40 <redacted>
17  0x1a4f4a984 <redacted>
18  0x1a2642950 <redacted>
19  0x1a2641bd8 <redacted>
20  0x1a263c3f4 <redacted>
21  0x1a263bba0 CFRunLoopRunSpecific
22  0x1b93a4598 GSEventRunModal
23  0x1a4f2d2f4 <redacted>
24  0x1a4f32874 UIApplicationMain
25  0x104c3c044 ffi_call_SYSV
26  0x104c3aae8 ffi_call_int
27  0x104c3a648 ffi_call
28  0x1040593d8 NativeScript::FunctionWrapper::call(JSC::ExecState*)
29  0x104c07b10 llint_entry
30  0x104c04f28 llint_entry
31  0x104c04f28 llint_entry
JavaScript stack trace:
file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:278:0
at file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:366:0
at applyAllNativeSetters(file: node_modules/@nativescript/core/ui/core/properties/properties.js:1065:0)
at initNativeView(file: node_modules/@nativescript/core/ui/core/properties/properties.js:992:0)
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:647:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:278:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/page/page-common.js:128:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0
at file: node_modules/@nativescript/core/ui/page/page.ios.js:268:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0<\M-b\M^@\M-&>
JavaScript error:
file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:278:0: JS ERROR TypeError: undefined is not an object (evaluating 'navBar.titleTextAttributes = (_a = {}, _a[NSForegroundColorAttributeName] = color.ios, _a)')
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   run@file: node_modules/@nativescript/core/application/application.ios.js:312:0
2   @file: node_modules/@nativescript/angular/platform-common.js:210:0
3   @file: node_modules/@nativescript/angular/platform-common.js:111:0
4   @file: node_modules/@nativescript/angular/platform-common.js:91:0
5   @file:///app/bundle.js:15652:144
6   ./main.ts@file:///app/bundle.js:15657:34
7   __webpack_require__@file: src/webpack/bootstrap:750:0
8   checkDeferredModules@file: src/webpack/bootstrap:43:0
9   webpackJsonpCallback@file: src/webpack/bootstrap:30:0
10  anonymous@file:///app/bundle.js:2:61
11  evaluate@[native code]
12  moduleEvaluation@:1:11
13  @:2:1
14  asyncFunctionResume@:1:11
15  @:24:9
16  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'navBar.titleTextAttributes = (_a = {}, _a[NSForegroundColorAttributeName] = color.ios, _a)')
at
file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:278:0
at file: node_modules/@nativescript/core/ui/action-bar/action-bar.ios.js:366:0
at applyAllNativeSetters(file: node_modules/@nativescript/core/ui/core/properties/properties.js:1065:0)
at initNativeView(file: node_modules/@nativescript/core/ui/core/properties/properties.js:992:0)
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:647:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:278:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file: node_modules/@nativescript/core/ui/page/page-common.js:128:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0
at file: node_modules/@nativescript/core/ui/page/page.ios.js:268:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:75
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:310:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:317:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:456:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0
at file:<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x1040df018 sig_handler(int)
2   0x1eaed9d90 <redacted>
3   0x1eaee89e8 pthread_kill
4   0x1ab3bd8f4 abort
5   0x1b6b44cc8 <redacted>
6   0x1b6b36ca0 <redacted>
7   0x1b6a48e04 <redacted>
8   0x1b6b44154 <redacted>
9   0x1b6b46bec __cxa_get_exception_ptr
10  0x1b6b46bac <redacted>
11  0x1b6a48c7c <redacted>
12  0x104096820 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x1040d0434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x104c3b388 ffi_closure_SYSV_inner
15  0x104c3c1b4 .Ldo_closure
16  0x1a4871a4c <redacted>
17  0x1a48721d0 <redacted>
18  0x1a47b3fc8 <redacted>
19  0x1a47b4c60 <redacted>
20  0x1a47b5fe0 <redacted>
21  0x1a4798e78 <redacted>
22  0x1a5437398 <redacted>
23  0x1a593cdf4 <redacted>
24  0x1a5943398 <redacted>
25  0x1a594e6e8 <redacted>
26  0x1a5899d7c <redacted>
27  0x1a58c3f40 <redacted>
28  0x1a4f4a984 <redacted>
29  0x1a2642950 <redacted>
30  0x1a2641bd8 <redacted>
31  0x1a263c3f4 <redacted>
JS Stack:
UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:15652:144
at ./main.ts(file:///app/bundle.js:15657:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob
```

**Comment by PatrickLohan** [comment]
Possibly something to do with this
```
CONSOLE LOG file: src/app/app.component.ts:65:18: user undefined
CONSOLE LOG file: node_modules/@angular/core/fesm5/core.js:25638:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file: src/app/authentication/login/login.component.ts:73:16: user undefined
```
part of the stacktrace? i.e. you have a variable called user, but whatever it's attached to is undefined when the app starts, possibly.

**Comment by Rmadhuprasanth** [comment]
Thanks for the response. Found the bug it's our plugins issue. For now am closing this bug.
