### ISSUE TITLE
[Android]: App gets crashed when it is running in background and Phone font size is changed

### ISSUE THREAD

**Issue by rmn81** [NativeScript/NativeScript#9255]
**Describe the bug**
App gets crashed when it is running in background and Phone font size is changed. It is happening only when selectedItemColor property is applied on TabStrip. It is happing on android not sure about iOS.

**Error:**
`[ba7898cd]: An uncaught Exception occurred on "main" thread.
Calling js method onStart failed
TypeError: Cannot read property 'setTextColor' of null

StackTrace:
Tabs._setItemColor(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:608:42)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:477:19)
at Tabs.setTabStripItems(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:474:15)
at Tabs.<computed>(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:680:14)
at applyAllNativeSetters(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/properties/properties.js:1048:28)
.............................................................
............................................................`

**Sample project**
 [Playground](https://play.nativescript.org/?template=play-ng&id=1El8Ii)

**Additional context**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/14125731/109960056-483e7900-7d0e-11eb-896c-07c0d24e8d57.gif)

**Comment by NathanWalker** [comment]
We've transferred this to community repo where it can be triaged better:
https://github.com/nativescript-community/ui-material-components/issues/260
