### ISSUE TITLE
Date-picker crash on iOS <= 13 on Nativescript 6.3.3

### ISSUE THREAD

**Issue by danouche93** [NativeScript/NativeScript#9269]
**Environment**
Nativescript: 6.3.3
tns-core-module: 6.3.2
tns-ios: 6.5.2

package.json:

  ```
"nativescript": {
    "id": {
      "android": "org.nativescript.TinaApp",
      "ios": "org.nativescript.TinaAppIos"
    },
    "tns-android": {
      "version": "6.3.1"
    },
    "tns-ios": {
      "version": "6.5.2"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "@nstudio/nativescript-pulltorefresh": "^2.0.0",
    "nativescript-angular": "~8.20.3",
    "nativescript-datetimepicker": "^1.2.3",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "platform": "^1.3.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.3.2",
    "tns-platform-declarations": "^6.5.15",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^0.5.2",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.4.0",
    "node-sass": "^4.7.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "fa98f785df3fba482e5e2a0c76f4be1fa6dc7a14",
  "readme": "NativeScript Application"
}
```

**Describe the bug**
I have created a component with a DatePickerField. When tapping on it with iOS <= 13, the app crashes with this error

```
JavaScript error:
JS ERROR Error: NativeScript encountered a fatal error: Error: -[TNSDictionaryAdapter set]: unrecognized selector sent to instance 0x600001ef7ba0
at
UIApplicationMain(file:///node_modules/@nativescript/core/application/application.js:312:0)
at run(file:///node_modules/@nativescript/core/application/application.js:312:0)
at file:///node_modules/@nativescript/angular/platform-common.js:210:0
at file:///node_modules/@nativescript/angular/platform-common.js:111:0
at file:///node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:4406:144
at ./main.ts(file:///app/bundle.js:4411:34)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
NativeScript caught signal 6.
Native Stack:
1   0x10b5bb171 sig_handler(int)
2   0x7fff522add7d _sigtramp
3   0x7fff5219ff39 itoa64
4   0x7fff5219bb7c abort
5   0x7fff500a2858 abort_message
6   0x7fff500a1cad std::__terminate(void (*)())
7   0x7fff500a440b __cxa_get_exception_ptr
8   0x7fff500a43d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
9   0x7fff51253ad6 _objc_exception_destructor(void*)
10  0x10b56ab6f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10b5bc524 -[TNSRuntime executeModule:referredBy:]
12  0x10a2dc353 main
13  0x7fff520ce1fd start
JS Stack:
```

I have looked all over the internet to see if someone has the same issue but I didn't find anything that fixes it.
When downgrading the plugin to the 1.2.2 version, it's iOS 14 that I have an issue and I also didn't find anything to fix it.

**To Reproduce**
Here is the Html code that produces the issue

```
<DatePickerField [ngStyle]="{'border-bottom-color': correctDate ? '#7D7D7D' : '#cc0000'}" row="3" col="1"
                (dateChange)="onDateChange($event)" class="h4" hint="Select Date" [minDate]="firstDayWeek"
                [(ngModel)]="newPreference.date" style="border-bottom-width: 1;padding-bottom: 5px">
            </DatePickerField>
```

TS code 

```
onDateChange(args) {
    const datePicker = args.object as DatePickerField;
    if (datePicker.date.getDay() == 5) {
      this.isWeekEnd = true;
      this.newPreference.dayPeriod = this.DayPeriod.Morning;
    } else if (datePicker.date.getDay() == 6) {
      this.isWeekEnd = true;
      this.newPreference.dayPeriod = this.DayPeriod.Afternoon;
    }
    else {
      this.isWeekEnd = false;
      this.newPreference.dayPeriod = this.DayPeriod.AllDay;
    }
  }
```

**Comment by NathanWalker** [comment]
Could you try bumping:
```
"tns-ios": {
    "version": "6.5.2"
  }
```
to:
```
"tns-ios": {
    "version": "6.5.4"
  }
```
Then do a:
```
npx rimraf node_modules package-lock.json hooks platforms
```
Also what XCode version are you using?

**Comment by danouche93** [comment]
@NathanWalker Hi thanks for your response. I try your solution but it doesn't work unfortunately. I use XCode 12.

**Comment by asharghi** [comment]
@danouche93 could you try updating tns-core-modules to 6.5.21?

**Comment by danouche93** [comment]
@asharghi It also doesn't work :(
