### ISSUE TITLE
"An uncaught Exception occurred on main thread" after idle

### ISSUE THREAD

**Issue by wendt88** [NativeScript/NativeScript#9271]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
√ Getting NativeScript components versions information...
√ Component nativescript has 7.2.1 version and is up to date.
√ Component @nativescript/core has 7.3.0 version and is up to date.
√ Component @nativescript/ios has 7.2.0 version and is up to date.
√ Component @nativescript/android has 7.0.1 version and is up to date.

**Describe the bug**
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onStart failed
System.err: TypeError: handler.apply is not a function
System.err: 
System.err: StackTrace:
System.err: invokeWithErrorHandling(file: node_modules\nativescript-vue\dist\index.js:1862:25)
System.err: 	at invoker(file: node_modules\nativescript-vue\dist\index.js:2519:13)
System.err: 	at _handleEvent(file: app\packages\core\data\observable\index.ts:296:10)
System.err: 	at notify(file: app\packages\core\data\observable\index.ts:278:14)
System.err: 	at _emit(file: app\packages\core\data\observable\index.ts:324:8)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view-base\index.ts:412:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view\index.android.ts:416:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:504:67)
System.err: 	at callFunctionWithSuper(file: app\packages\core\ui\core\view-base\index.ts:497:2)
System.err: 	at callLoaded(file: app\packages\core\ui\core\view-base\index.ts:504:7)
System.err: 	at loadView(file: app\packages\core\ui\core\view-base\index.ts:682:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:407:8)
System.err: 	at eachChildView(file: app\packages\core\ui\layouts\layout-base-common.ts:125:18)
System.err: 	at eachChild(file: app\packages\core\ui\core\view\view-common.ts:868:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view-base\index.ts:406:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view\index.android.ts:416:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:504:67)
System.err: 	at callFunctionWithSuper(file: app\packages\core\ui\core\view-base\index.ts:497:2)
System.err: 	at callLoaded(file: app\packages\core\ui\core\view-base\index.ts:504:7)
System.err: 	at loadView(file: app\packages\core\ui\core\view-base\index.ts:682:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:407:8)
System.err: 	at eachChildView(file: app\packages\core\ui\content-view\index.ts:77:3)
System.err: 	at eachChildView(file: app\packages\core\ui\page\page-common.ts:146:8)
System.err: 	at eachChild(file: app\packages\core\ui\core\view\view-common.ts:868:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view-base\index.ts:406:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view\index.android.ts:416:8)
System.err: 	at onLoaded(file: app\packages\core\ui\page\index.android.ts:48:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:504:67)
System.err: 	at callFunctionWithSuper(file: app\packages\core\ui\core\view-base\index.ts:497:2)
System.err: 	at callLoaded(file: app\packages\core\ui\core\view-base\index.ts:504:7)
System.err: 	at loadView(file: app\packages\core\ui\core\view-base\index.ts:682:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:407:8)
System.err: 	at eachChildView(file: app\packages\core\ui\frame\frame-common.ts:522:3)
System.err: 	at eachChild(file: app\packages\core\ui\core\view\view-common.ts:868:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view-base\index.ts:406:7)
System.err: 	at onLoaded(file: app\packages\core\ui\core\view\index.android.ts:416:8)
System.err: 	at onLoaded(file: app\packages\core\ui\frame\frame-common.ts:113:8)
System.err: 	at onLoaded(file: app\packages\core\ui\frame\index.android.ts:241:8)
System.err: 	at (file: app\packages\core\ui\core\view-base\index.ts:504:67)
System.err: 	at callFunctionWithSuper(file: app\packages\core\ui\core\view-base\index.ts:497:2)
System.err: 	at callLoaded(file: app\packages\core\ui\core\view-base\index.ts:504:7)
System.err: 	at onStart(file: app\packages\core\ui\frame\index.android.ts:1140:12)
System.err: 	at onStart(file: app\packages\core\ui\frame\activity.android.ts:37:18)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err: 	at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:39)
System.err: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
System.err: 	at android.app.Activity.performStart(Activity.java:7978)
System.err: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3580)
System.err: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
System.err: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
System.err: 	at android.os.Looper.loop(Looper.java:237)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7948)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**To Reproduce**
with the opened app, wait for device gets idle, then unlock it. sometimes this error occurs

**Additional context**
occurs in debug and release mode also with previous NS >= 7 versions

**Comment by NathanWalker** [comment]
When you can please share the package.json.

Also try updating to 8.0:
```
npm i -g nativescript
ns migrate
ns clean
ns debug android
```
