### ISSUE TITLE
ns device throws Error: ios-device-lib ENOENT

### ISSUE THREAD

**Issue by baermathias** [NativeScript/NativeScript#9272]
**Environment**
Provide version numbers and more (information retrieved by running `ns doctor`):

✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.2.1 version and is up to date.
✔ Component @nativescript/core has 7.3.0 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

**Describe the bug**
When running `ns device` I get the following error:
```
Connected devices & emulators
Searching for devices...
Error: spawn /home/username/.nvm/versions/node/v14.15.4/lib/node_modules/nativescript/node_modules/ios-device-lib/bin/linux/x64/ios-device-lib ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
I followed this docs to install ns on Ubuntu 20.04: https://docs.nativescript.org/start/ns-setup-linux
I had to install `@nativescript/android` afterwards via `npm i @nativescript/android` because `ns doctor` showed that it is not installed like it does with `@nativescript/ios` right now. 
Also I am using node v14.15.4 (using node version manager). 

**I have already tried:**
1. `tns platform remove android`
`tns platform add android`

2. `npm i @nativescript/ios` (has no effect in regard to ns doctor output)

**Comment by shirakaba** [comment]
Part of this is probably rooted in the fact that, as per the [Linux setup docs](https://docs.nativescript.org/start/ns-setup-linux), iOS development is not supported on Ubuntu:

> NOTE: On Linux systems you can only use the NativeScript CLI to develop Android apps. This is because the NativeScript CLI uses Xcode to build iOS apps, which is only available on the macOS operating system.

I'm guessing the CLI erroneously looks for iOS devices when `ns device is run`. Instead, it should probably avoid checking for iOS devices on all non-macOS systems, or at least safely handle the possibility of `ios-device-lib` being missing.

@baermathias Here are the instructions for `ns device`:

```
% ns device --help
# ns device

### Description

Lists all recognized connected Android or iOS devices with serial number and index, grouped by platform.

### Commands

┌─────────┬──────────────────────────┐
│ Usage   │ Synopsis                 │
│ General │ $ ns device [<Command>] │
└─────────┴──────────────────────────┘

### Arguments

<Command> extends the device command. You can set the following values for this argument:

    * android - Lists all recognized connected Android physical and running Android virtual devices.
    * ios - Lists all recognized connected iOS devices. 
    * log - Opens the device log stream for a selected connected device.
    * list-applications - Lists the installed applications on all connected Android or iOS devices.
    * run - Runs the selected application on a connected Android or iOS device.
```

To avoid looking up iOS devices, you should run:

```sh
ns device android
```

**Comment by rigor789** [comment]
It should not run the ios stuff on unsupported platforms, so definitely a bug somewhere - worked fine whenever I tried, so curious on conditions that make it fail.

**Comment by PatrickLohan** [comment]
Have you tried updating your node version as per my suggestions in the linked thread?

**Comment by Rob4226** [comment]
I get this error also on windows with NativeScript CLI v8.02:

```powershell
+ nativescript@8.0.2
added 622 packages from 443 contributors in 54.107s
PS C:\Users\ruser> ns devices

Connected devices & emulators
Searching for devices...
Error: spawn C:\Users\ruser\AppData\Roaming\npm\node_modules\nativescript\node_modules\ios-device-lib\bin\win32\x64ios-device-lib ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
If I add the android flag `ns devices android` then it runs ok but CLI v7.x.x used to run `ns devices` without any errors.  It would probably be a good idea to make v8 work like v7 where it won't run an iOS check on Windows or Linux so it won't produce an error.
