### ISSUE TITLE
Throwing error while generating android type declaration file

### ISSUE THREAD

**Issue by vignesh-web** [NativeScript/NativeScript#9276]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 10.0.2
 - Cross-platform modules: Nativescript 6.8.0
 - Android Runtime: Android Studio 4.0

**Describe the bug**

I am trying to generate type declaration files using dts-generator and I am getting below error:

```
Error executing Typescript Definitions Generator: Bad method signature: (Lcom/android/builder/model/DimensionAware;:Lorg/gradle/api/Named;)V
java.lang.IllegalArgumentException: Bad method signature: (Lcom/android/builder/model/DimensionAware;:Lorg/gradle/api/Named;)V
        at edu.umd.cs.findbugs.ba.generic.GenericSignatureParser.<init>(GenericSignatureParser.java:155)
        at edu.umd.cs.findbugs.ba.generic.GenericUtilities.getType(GenericUtilities.java:263)
        at com.telerik.dts.TypeDefinition.setTypeGenerics(TypeDefinition.java:101)
        at com.telerik.dts.TypeDefinition.checkSignature(TypeDefinition.java:70)
        at com.telerik.dts.TypeDefinition.<init>(TypeDefinition.java:47)
        at com.telerik.dts.DtsApi.generateDtsContent(DtsApi.java:99)
        at com.telerik.dts.Generator.generateDts(Generator.java:57)
        at com.telerik.dts.Generator.start(Generator.java:42)
        at com.telerik.Main.main(Main.java:38)
```

Could you please help me on this?

**Comment by rigor789** [comment]
How are you generating the typings? What are you generating the typings for? A library, or android sdk?

**Comment by vignesh-web** [comment]
I am using dts-generator for generating Typings for Android.
