### ISSUE TITLE
tns run android works on Mac and NativeScript Playground, but not on Windows 10

### ISSUE THREAD

**Issue by racio88** [NativeScript/NativeScript#9285]
**Environment**

This is my tns --doctor in Windows 10

✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.2.1 version and is up to date.
✔ Component @nativescript/core has 7.3.0 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

**Describe the bug**

Hello to all,
I am developing a small application that at the moment works correctly on the emulator present on the Mac and on NativeScript Playground but as soon as I work on a Windows computer the command "tns run android --emulator" crashes at EXECUTING 61%.
The emulator settings are exactly the same between the Mac case and the Windows case, and I also made an attempt by creating a simple helloWorld application (tns create NewApp --helloWorld) but I have the same problem.

Someone knows more about it.

**To Reproduce**

Below the error of the execution : 

**Command gradlew.bat failed with exit code 1
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
{ Error: Command gradlew.bat failed with exit code 1
    at Errors.failWithOptions (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\common\errors.js:157:27)
    at Errors.fail (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\common\errors.js:130:21)
    at GradleCommandService.<anonymous> (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\services\android\gradle-command-service.js:40:30)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\services\android\gradle-command-service.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'Exception',
  message: 'Command gradlew.bat failed with exit code 1',
  stack:
   'Error: Command gradlew.bat failed with exit code 1\n    at Errors.failWithOptions (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\common\\errors.js:157:27)\n    at Errors.fail (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\common\\errors.js:130:21)\n    at GradleCommandService.<anonymous> (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\services\\android\\gradle-command-service.js:40:30)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\services\\android\\gradle-command-service.js:6:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  errorCode: 127,
  suggestCommandHelp: false,
  proxyAuthenticationRequired: false,
  printOnStdout: undefined }
Will emit event runOnDeviceError with data { projectDir:
   'C:\\Users\\InnovatesApp\\Documents\\NativeScript\\Workspace\\NewApp',
  deviceIdentifier: 'emulator-5554',
  applicationIdentifier: 'org.nativescript.NewApp',
  error:
   { Error: Command gradlew.bat failed with exit code 1
       at Errors.failWithOptions (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\common\errors.js:157:27)
       at Errors.fail (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\common\errors.js:130:21)
       at GradleCommandService.<anonymous> (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\services\android\gradle-command-service.js:40:30)
       at Generator.throw (<anonymous>)
       at rejected (C:\Users\InnovatesApp\AppData\Roaming\nvm\v10.19.0\node_modules\nativescript\lib\services\android\gradle-command-service.js:6:65)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'Exception',
     message: 'Command gradlew.bat failed with exit code 1',
     stack:
      'Error: Command gradlew.bat failed with exit code 1\n    at Errors.failWithOptions (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\common\\errors.js:157:27)\n    at Errors.fail (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\common\\errors.js:130:21)\n    at GradleCommandService.<anonymous> (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\services\\android\\gradle-command-service.js:40:30)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\InnovatesApp\\AppData\\Roaming\\nvm\\v10.19.0\\node_modules\\nativescript\\lib\\services\\android\\gradle-command-service.js:6:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     errorCode: 127,
     suggestCommandHelp: false,
     proxyAuthenticationRequired: false,
     printOnStdout: undefined } }
Stopping webpack watch for platform android.
Project dir from hooksArgs is: C:\Users\InnovatesApp\Documents\NativeScript\Workspace\NewApp.
Hooks directories: [ 'C:\\Users\\InnovatesApp\\Documents\\NativeScript\\Workspace\\NewApp\\hooks' ]
AfterHookName for command watch is after-watch
Will emit event runOnDeviceStopped with data { projectDir:
   'C:\\Users\\InnovatesApp\\Documents\\NativeScript\\Workspace\\NewApp',
  deviceIdentifier: 'emulator-5554' }
Webpack process exited with code null when we expected it to be long living with watch.**

**Expected behavior**

Simple case of Hello World Project (but same behavior also on my project)

Thanks in advance

**Comment by CatchABus** [comment]
Closing as this is related to old preview app.
