### ISSUE TITLE
Webpack 5 tries to load .d.ts files and fails

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#9300]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules: 8.0.0
 - Android Runtime: 8.0
 - iOS Runtime: 8.0
 - XCode Version: 12.4
 - Plugin(s):

**Describe the bug**
Seems with Webpack 5 it tries to transpile/load `.d.ts` files and since those do not generate any output it fails:
```

ERROR in ./app/app.d.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. Output generation failed
    at Object.transpileModule (/Users/peter/Projects/SwyftCG/node_modules/typescript/lib/typescript.js:126956:29)
    at getTranspilationEmit (/Users/peter/Projects/SwyftCG/node_modules/ts-loader/dist/index.js:390:75)
    at successLoader (/Users/peter/Projects/SwyftCG/node_modules/ts-loader/dist/index.js:38:11)
    at Object.loader (/Users/peter/Projects/SwyftCG/node_modules/ts-loader/dist/index.js:23:5)
 @ ./app/ sync .(xml|js|ts|s?css)$ ./app.d.ts
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-92
```

**To Reproduce**
Add `app.d.ts` to your project at the level where `app.ts` is located. Run `ns prepare ios`

**Expected behavior**
`.d.ts` files should NOT be loaded/transpiled by webpack. 

**Sample project**

**Additional context**

**Comment by rigor789** [comment]
Fixed in `@nativescript/webpack@5.0.0-beta.4`
