### ISSUE TITLE
Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by asharghi** [NativeScript/NativeScript#9314]
**Environment**
package.json:
```
 "dependencies": {
    "@nativescript/core": "^8.0.1",
    "@nativescript/directions": "^2.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/local-notifications": "^5.0.2",
    "@nativescript/social-share": "^2.0.4",
    "@nativescript/theme": "~3.0.1",
    "@nativescript/types": "^8.0.0",
    "@triniwiz/nativescript-image-cache-it": "^7.0.5",
    "@triniwiz/nativescript-socketio": "^4.0.1",
    "@triniwiz/nativescript-stripe": "^7.0.0-alpha11",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "dayjs": "^1.9.8",
    "nativescript-carousel": "^7.0.1",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-vue": "^2.9.0",
    "rxjs": "^6.6.7",
    "tsconfig-paths-webpack-plugin": "^3.5.1",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@nativescript/android": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@types/node": "~14.6.2",
    "nativescript-vue-template-compiler": "~2.9.0",
    "typescript": "~4.0.0",
    "vue": "~2.6.12"
  },
```

**Describe the bug**
After updating my project from ns 6.5, fixing all the build errors, I'm now stuck with:
```
Successfully synced application no.okam.consumer on device cd320554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
System.err: File: (file: app/webpack:/okamconsumer/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: default(file:///data/data/no.okam.consumer/files/app/bundle.js:5430:42)
System.err:     at ./node_modules/ts-loader/index.js??clonedRuleSet-2[0].rules[0].use[0]!./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/pages/Order.vue?vue&type=script&lang=ts&(file: app/webpack:/okamconsumer/app/components/pages/Order.vue?bf48:357:13)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Order.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:6045:296)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Order.vue(file:///data/data/no.okam.consumer/files/app/bundle.js:5325:93)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./node_modules/ts-loader/index.js??clonedRuleSet-2[0].rules[0].use[0]!./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/pages/OrderList.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:3777:68)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/OrderList.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:6069:300)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/OrderList.vue(file:///data/data/no.okam.consumer/files/app/bundle.js:5433:97)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./node_modules/ts-loader/index.js??clonedRuleSet-2[0].rules[0].use[0]!./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/pages/Cart.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:2422:72)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Cart.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:5961:295)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Cart.vue(file:///data/data/no.okam.consumer/files/app/bundle.js:4948:92)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./node_modules/ts-loader/index.js??clonedRuleSet-2[0].rules[0].use[0]!./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/pages/Category.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:2672:84)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Category.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:5973:299)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Category.vue(file:///data/data/no.okam.consumer/files/app/bundle.js:5001:96)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./node_modules/ts-loader/index.js??clonedRuleSet-2[0].rules[0].use[0]!./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/pages/Store.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:4267:88)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Store.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:6117:296)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/Store.vue(file:///data/data/no.okam.consumer/files/app/bundle.js:5645:93)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./node_modules/ts-loader/index.js??clonedRuleSet-2[0].rules[0].use[0]!./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/pages/StoreList.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:4475:68)
System.err:     at __webpack_require__(file: app/webpack:/okamconsumer/webpack/bootstrap:24:0)
System.err:     at fn(file: app/webpack:/okamconsumer/webpack/runtime/hot module replacement:61:0)
System.err:     at ./app/components/pages/StoreList.vue?vue&type=script&lang=ts&(file:///data/data/no.okam.consumer/files/app/bundle.js:6129:300)
```

**To Reproduce**
I have not been able to reproduce in a blank template, but Silviustan from Discord also have this problem. Igor already have access to my repo.

**Comment by asharghi** [comment]
Just an update from the findings in Discord.

**To reproduce:**

`ns create demoapp --tempalte @nativescript/template-drawer-navigation-ts`

Adding `import Browse from "./Browse"` in Home component, and import `Home from "./Home"` in Browse component will reproduce it.

**Comment by asharghi** [comment]
For people stuck with this error. I recommend just migrating your app to using  https://github.com/nativescript-vue/nativescript-vue-navigator for navigation as a workaround. Just search for $navigateTo and replace $navigateTo(ComponentName, {...}) with $navigator.navigate("ComponentName", {...}) and set up the routes as explained in the readme of the plugin.
