### ISSUE TITLE
preview of a vue template with an editable TextField causes a crash

### ISSUE THREAD

**Issue by LaKing** [NativeScript/NativeScript#9330]
**Environment**
Version 8.0.1 with @nativescript/android 8.0.0 

**Describe the bug**
Adding a TextField to a Vue template crashes the application.
```
LOG from device Galaxy S8: An uncaught Exception occurred on "main" thread.
Calling js method finishUpdate failed
TypeError: Right-hand side of 'instanceof' is not an object

StackTrace:
onBackgroundOrBorderPropertyChanged(file:///data/data/org.nativescript.preview/files/app/vendor.js:37766:26)
    at _redrawNativeBackground(file:///data/data/org.nativescript.preview/files/app/vendor.js:24508:66)
    at [backgroundInternal:setNative](file:///data/data/org.nativescript.preview/files/app/vendor.js:24488:14)
    ...
```
**To Reproduce**
- Install a new myCoolApp project, from any vue template.
- add a TextField to one of the blank pages
- run tns preview

**Expected behavior**
An editable text field added.

**Sample project**
Starting with the blank vue template, add this to Home.vue
```
<template>
    <Page>
        <ActionBar>
            <Label text="Home"/>
        </ActionBar>

        <GridLayout>
            <Label class="info">
                <FormattedString>
                    <Span class="fas" text.decode="&#xf135; "/>
                    <Span :text="message"/>
                    <TextField v-model="textFieldValue" />
                </FormattedString>
            </Label>
        </GridLayout>
    </Page>
</template>

<script>
  export default {
    data() {
	return {
	    textFieldValue: ""
	}
    }, 
    computed: {
      message() {
        return "Blank {N}-Vue app";
      }
    }
  };
</script>
```

**Additional context**
@rigor789 pointed out that that the preview version is a bit outdated, stuck on NS6.5, and as a workaround, I should do a local install. 

I thought it should have at least a bug report, so that people can google this.

**Comment by CatchABus** [comment]
Closing as it's related to old preview app.
