### ISSUE TITLE
TimePicker vue has crashes when maxHour and minHour is set

### ISSUE THREAD

**Issue by nativeB** [NativeScript/NativeScript#9344]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  7.0.12
 - Cross-platform modules:
 - Android Runtime: 28
 - iOS Runtime: 14
 - XCode Version: 12.2.0
 - Plugin(s): None

**Describe the bug**
This is a run time error. it occurs when setting the time on the time picker with maxHour and minHour set. without these two props, it works as expected

**To Reproduce**
set the minHour and maxHour 
```
<TimePicker
        v-on:timeChange="handleTimeChange"
        :minuteInterval="15"
        :minHour="8"
        :maxHour="20"
        iosPreferredDatePickerStyle="1"
        v-if="role_type !== 'customer'"
      />
```

**Expected behavior**
TimePicker should work ok.and within the range of min and max hour set

**Additional context**

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onTimeChanged failed
System.err: Error: time property value (Sun Dec 31 1899 10:42:00 GMT+0000 (GMT):00) is not valid. Min time: (08:00), max time: (20:59).
System.err: 
System.err: StackTrace:
System.err: valueChanged(file: src/packages/core/ui/time-picker/time-picker-common.ts:200:9)
System.err:     at Property.nativeValueChange(file: src/packages/core/ui/core/properties/index.ts:307:5)
System.err:     at TimeChangedListenerImpl.onTimeChanged(file:///data/data/com.**********.app/files/app/vendor.js:52443:72)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.java.lang.Object_vendor_52429_26_TimeChangedListenerImpl.onTimeChanged(Object_vendor_52429_26_TimeChangedListenerImpl.java:21)
System.err:     at android.widget.TimePickerSpinnerDelegate.onTimeChanged(TimePickerSpinnerDelegate.java:512)
System.err:     at android.widget.TimePickerSpinnerDelegate.access$300(TimePickerSpinnerDelegate.java:45)
System.err:     at android.widget.TimePickerSpinnerDelegate$2.onValueChange(TimePickerSpinnerDelegate.java:139)
System.err:     at android.widget.NumberPicker.notifyChange(NumberPicker.java:1985)
System.err:     at android.widget.NumberPicker.setValueInternal(NumberPicker.java:1756)
System.err:     at android.widget.NumberPicker.scrollBy(NumberPicker.java:1155)
System.err:     at android.widget.NumberPicker.onTouchEvent(NumberPicker.java:936)
System.err:     at android.view.View.dispatchTouchEvent(View.java:12513)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
System.err:     at android.widget.NumberPicker.dispatchTouchEvent(NumberPicker.java:993)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
System.err:     at android.app.Dialog.dispatchTouchEvent(Dialog.java:847)
System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
System.err:     at android.view.View.dispatchPointerEvent(View.java:12752)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
System.err:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
System.err:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
System.err:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7166)
System.err:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7218)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:690)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by janoshrubos** [comment]
I'v tried to reproduce this issue on a vue project, but `:minHour="8"` and `:maxHour="20"` works as expected for me.

Could you please post your `handleTimeChange` function? 
The earliest valid date should be January 1, 1970, UTC, but in the error there is Sun Dec 31 1899 10:42:00 somehow.

**Comment by janoshrubos** [comment]
Closing this issue due to inactivity. 
If this error is still relevant, feel free to open a new issue!
