### ISSUE TITLE
Crashing on emulator Android API 30 "Expected Android API level 21+ but was 30"

### ISSUE THREAD

**Issue by agardes** [NativeScript/NativeScript#9356]
My environnement : 

- Nativescript version : 7.1.0
- Nativescript core : 7.0.3
- Nativescript Vue : 2.8.1

My app launches perfectly on my real device and on emulators (both Android 10 - API 29), but when I try to emulate on a Android 11 - api 30, it crashes after splash screen with this error :

```
An uncaught Exception occurred on "EventThread" thread.
null

StackTrace:
java.lang.ExceptionInInitializerError
	at okhttp3.internal.platform.Platform.get(Platform.java:85)
	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
	at io.socket.engineio.client.Socket.<init>(Socket.java:215)
	at io.socket.engineio.client.Socket.<init>(Socket.java:174)
	at io.socket.client.Manager$Engine.<init>(Manager.java:638)
	at io.socket.client.Manager$1.run(Manager.java:277)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.client.Manager.open(Manager.java:266)
	at io.socket.client.Manager.open(Manager.java:256)
	at io.socket.client.Socket$3.run(Socket.java:142)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
	at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
	at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
	at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
	... 16 more
```

Any idea why ?

I found [this article](https://publicobject.com/2020/02/25/okhttp-restricted-apis/) that says you should update okhttp3 but I don't know where/how to do this since it's java.

Thanks all for your help!

EDIT : Found a solution that seems to be working :
- Go to your App_Ressources / Android / app.gradle
- add this at the begining of the file : 
 `
dependencies {
  implementation 'com.squareup.okhttp3:okhttp:4.9.0'
}
`

**Comment by farfromrefug** [comment]
@agardes you should find which of your plugins uses okhttp and create that issue there. N does not use okhttp and it would be great for the plugin dev to upgrade okhttp version

**Comment by agardes** [comment]
@farfromrefug thanks for your answer, unfortunatly I have no idea which plug in uses okhttp, I thought it was from nativescript core. You can close the issue though, I managed to find a solution (see my edit) that seems to be working for now on. Thanks!

**Comment by farfromrefug** [comment]
@agardes please post the list for your plugins

**Comment by agardes** [comment]
@farfromrefug here you go :

```
"dependencies": {
    "@nativescript-community/tween": "0.0.14",
    "@nativescript-community/ui-canvas": "^4.0.49",
    "@nativescript-community/ui-svg": "0.0.8",
    "@nativescript/canvas-three": "^1.0.0-alpha6",
    "@nativescript/core": "^7.0.3",
    "@vue/devtools": "^5.3.3",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-devtools": "^1.4.0",
    "node-sass": "^4.14.1",
    "three": "^0.126.1",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "^3.0.4",
    "babel-loader": "^8.1.0",
    "bezier-js": "^4.0.3",
    "nativescript-vue-template-compiler": "^2.8.1",
    "nativescript-worker-loader": "~0.12.1",
    "sass": "^1.32.8",
    "sass-loader": "7.3.1",
    "vue-loader": "^15.9.3"
  }

```

**Comment by farfromrefug** [comment]
@agardes can you report it here https://github.com/NativeScript/canvas ? It is `@nativescript/canvas-three` which depends on it.

**Comment by agardes** [comment]
@farfromrefug Ok, will report it there. If you don't mind me asking, how did you manage to find which plug-in depends on it that quick ? Thanks

**Comment by farfromrefug** [comment]
@agardes i know a lot of plugins. And i knew `@nativescript/canvas-polyfill` depends on okhttp. Then i know `@nativescript/canvas-three` depends on `@nativescript/canvas-polyfill`
