### ISSUE TITLE
Crashes on Android: org.nativescript.widgets.image.Fetcher.decodeSampledBitmapFromByteArray

### ISSUE THREAD

**Issue by maxorlovsky** [NativeScript/NativeScript#9368]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.2.1
 - Cross-platform modules: 7.1.4
 - Android Runtime: 7.0.1
 - iOS Runtime: -
 - XCode Version: -
 - Plugin(s):
>     "nativescript-advanced-webview": "6.0.0",
>     "nativescript-app-settings": "1.0.0",
>     "nativescript-applozic-chat": "2.2.0",
>     "nativescript-bitmap-factory": "1.8.1",
>     "nativescript-carousel": "7.0.1",
>     "nativescript-clipboard": "2.0.0",
>     "nativescript-drop-down": "5.0.6",
>     "nativescript-facebook-7": "7.0.4",
>     "nativescript-feedback": "2.0.0",
>     "nativescript-google-maps-sdk": "file:build/libs/nativescript-google-maps-sdk",
>     "nativescript-imagecropper": "4.0.1",
>     "nativescript-intl": "4.0.2",
>     "nativescript-lottie": "5.0.2",
>     "nativescript-open-app": "0.3.0",
>     "nativescript-permissions": "1.3.11",
>     "nativescript-ripple": "4.0.1",
>     "nativescript-sentry": "2.0.0",
>     "nativescript-socketio": "3.3.1",
>     "nativescript-ui-chart": "8.0.2",
>     "nativescript-ui-listview": "9.1.0",
>     "nativescript-ui-sidedrawer": "9.0.3",
>     "nativescript-vue": "2.8.3",
>     "nativescript-vue-devtools": "1.4.0",
>     "nativescript-vue-shadow-ns-7": "10.1.0",
>     "nativescript-webview-interface": "1.4.4",
>     "nativescript-wikitude-sdk": "1.0.2",

**Describe the bug**
After the release of version of the new app on NS7 we started to receive tons of crashes from android users all related to bitmap image problem.

**To Reproduce**
Don't know how to reproduce, but we have close to 6k crashlytics events in 1 day.

**Expected behavior**
No crashes

**Sample project**
Not possible, project too big

**Additional context**

> Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
>        at org.nativescript.widgets.image.AsyncTask$3.done(AsyncTask.java:326)
>        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
>        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>        at java.lang.Thread.run(Thread.java:923)

> Caused by java.lang.IllegalArgumentException: Problem decoding into existing bitmap
>        at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:832)
>        at org.nativescript.widgets.image.Fetcher.decodeSampledBitmapFromByteArray(Fetcher.java:596)
>        at org.nativescript.widgets.image.Fetcher.processHttpNoCache(Fetcher.java:237)
>        at org.nativescript.widgets.image.Fetcher.processBitmap(Fetcher.java:278)
>        at org.nativescript.widgets.image.Worker$BitmapWorkerTask.doInBackground(Worker.java:330)
>        at org.nativescript.widgets.image.Worker$BitmapWorkerTask.doInBackground(Worker.java:278)
>        at org.nativescript.widgets.image.AsyncTask$2.call(AsyncTask.java:313)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>        at java.lang.Thread.run(Thread.java:923)

Here is a public sentry link that might help https://sentry.io/share/issue/8d0b085e1d744b88b5d48b69d5cb9334/
It is something that happens randomly. Before we were thinking it's something related to low end devices failing to fetch images and process them due to low end devices (7.1 android devices with 1gb RAM). While recently we saw that Android 10 devices experience same issue. So it's not that.

**Comment by maxorlovsky** [comment]
Logs don't provide particular link to the image. Unfortunately crash happens on a page where there's a lot of images in a list.
