### ISSUE TITLE
Error: Invalid visibility value: [object Object]. Valid values are: visible, hidden, collapse.

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#9380]
I have a NS 6.5 app that works fine when deployed to the test device (simulator or physical). The also works fine if I install the app via the APK directly to the device.  However, when I deploy the app to the PlayStore (internal testing) some users report crashes.  I have been trying to determine why this is happening on some devices and not on others.  To debug the issue, I use Sentry.io to record the crash.  Below is the recorded error:

```
java.lang.Exception: Calling js method onCreateView failed
Error: Invalid visibility value: [object Object]. Valid values are: visible, hidden, collapse.
    at com.tns.Runtime.passExceptionToJsNative(Runtime.java)
    at com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:82)
    at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:34)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
    at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
java.lang.Throwable: push.View.<computed>(file:///data/data/com.awl.awlmobile/files/app/vendor.js:7522:23)
	at applyAllNativeSetters(file:///data/data/com.awl.awlmobile/files/app/vendor.js:10741:37)
	at initNativeView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:10668:9)
	at push.ViewBase.onResumeNativeUpdates(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17795:22)
	at push.ViewBase._resumeNativeUpdates(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17426:18)
	at push.ViewBase.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17380:14)
	at push.View.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:7219:35)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:90)
	at push.ViewBase.callFunctionWithSuper(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17458:9)
	at push.ViewBase.callLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:14)
	at push.ViewBase.loadView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17604:18)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17382:19)
	at push.LayoutBaseCommon.eachChildView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:57079:26)
	at push.ViewCommon.eachChild(file:///data/data/com.awl.awlmobile/files/app/vendor.js:28467:14)
	at push.ViewBase.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17381:14)
	at push.View.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:7219:35)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:90)
	at push.ViewBase.callFunctionWithSuper(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17458:9)
	at push.ViewBase.callLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:14)
	at push.ViewBase.loadView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17604:18)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17382:19)
	at push.LayoutBaseCommon.eachChildView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:57079:26)
	at push.ViewCommon.eachChild(file:///data/data/com.awl.awlmobile/files/app/vendor.js:28467:14)
	at push.ViewBase.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17381:14)
	at push.View.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:7219:35)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:90)
	at push.ViewBase.callFunctionWithSuper(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17458:9)
	at push.ViewBase.callLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:14)
	at push.ViewBase.loadView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17604:18)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17382:19)
	at push.ContentView.eachChildView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:16936:13)
	at push.ViewCommon.eachChild(file:///data/data/com.awl.awlmobile/files/app/vendor.js:28467:14)
	at push.ViewBase.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17381:14)
	at push.View.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:7219:35)
	at push.ScrollViewBase.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:59666:35)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:90)
	at push.ViewBase.callFunctionWithSuper(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17458:9)
	at push.ViewBase.callLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:14)
	at push.ViewBase.loadView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17604:18)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17382:19)
	at push.ContentView.eachChildView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:16936:13)
	at push.PageBase.eachChildView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:59121:40)
	at push.ViewCommon.eachChild(file:///data/data/com.awl.awlmobile/files/app/vendor.js:28467:14)
	at push.ViewBase.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17381:14)
	at push.View.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:7219:35)
	at push.Page.onLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:15590:35)
	at (file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:90)
	at push.ViewBase.callFunctionWithSuper(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17458:9)
	at push.ViewBase.callLoaded(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17465:14)
	at push.ViewBase.loadView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17604:18)
	at push.ViewBase._addViewCore(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17599:18)
	at push.ViewBase._addView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:17585:14)
	at push.FragmentCallbacksImplementation.onCreateView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:9289:19)
	at push.FragmentClass.onCreateView(file:///data/data/com.awl.awlmobile/files/app/vendor.js:86196:38)

    at com.tns.Runtime.passExceptionToJsNative(Runtime.java)
    at com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:82)
    at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:34)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
    at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
```

If I use the same device to load the app via VS Code, the app works fine, but as soon as we load the app from the Internal Testing we experience this crash. 

Looking at the error message, I thought that this is related to the visibility setting being **collapsed** instead of **collapse** and I replaced it everywhere, but this did not help.

Has anyone experienced this kind of behavior?  What would be the solution for this?

**Comment by dpdragnev** [comment]
Yeah, it is weird that this error happens only when the app is downloaded from the PlayStore.  On the same device, the app does not crash if you load it from VS Code or from the APK directly.  Very bizarre.

**Comment by triniwiz** [comment]
So it happens in release mode you can try adding some logs in apk you sign for release also you will want to add `android:debuggable="true"` to the application tag in the AndroidManifest.xml then you can try installing that apk , to get the logs you will need to use logcat

**Comment by dpdragnev** [comment]
Thanks @triniwiz I had some partial success with tracking down all the visibility properties and making sure that the variables are properly initialized.  Now, I only experience the crash on one of our test devices: a Motorola G Power. I think I may just leave it at that and monitor the crash reports.

**Comment by dpdragnev** [comment]
Some additional information.  I looked in the generated bundle.js file and I am using visibility 115 times.  Each one of them in the form of: **visibility="{{ someCondition : 'visible' : 'collapse' }}"**

I am not plugging in a variable directly into the visibility parameter.  

So how is it possible to receive [object Object] if we should always have either 'visible' or 'collapse'.  It seems to me that some additional processing is taking place that changes the source code after it has been generated by the **tns build android ... --release command**

According to the latest crash reports I received, this is happening at random on Android only.  

Any ideas?

**Comment by dpdragnev** [comment]
I would love it if someone from the Nativescript team comments on this.

**Comment by CatchABus** [comment]
Binding context can still be undefined until the page is loaded so properties like `someCondition` can also be undefined.
As a precaution, using a boolean helps:
```
visibility="{{ someCondition ? 'visible' : 'collapse' }}"
```
