### ISSUE TITLE
Fresh app gives `TypeError: The 'compilation' argument must be an instance of Compilation`

### ISSUE THREAD

**Issue by Marooned-MB** [NativeScript/NativeScript#9401]
**Environment**
```
>tns info
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 8.0.1 and the latest available version is 8.0.2.
√ Component @nativescript/core has 8.0.5 version and is up to date.
× Component @nativescript/ios is not installed.
√ Component @nativescript/android has 8.0.0 version and is up to date.
```
- OS: Windows 10 Pro 64b
Fresh VCode and NS install

**Describe the bug**
I'm trying to create and run/preview fresh project on the fresh install of the whole ecosystem. Below please find the log and error. The error is the same no matter of picked template.

```
>ns doctor
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 8.0.1 and the latest available version is 8.0.2.
√ Component @nativescript/core has 8.0.5 version and is up to date.
× Component @nativescript/ios is not installed.
√ Component @nativescript/android has 8.0.0 version and is up to date.

>tns create
# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)
√ First, what will be the name of your app? ... FooBar
√ Next, which style of NativeScript project would you like to use: » Angular
√ Finally, which template would you like to start from: » Hello World
[...]

>cd FooBar
>ns preview
# here I scan QR code with NS Preview on my Android 9 (MIUI 12)

Copying template files...
# here some skipped info

added 1 package and audited 449 packages in 7.99s
/
40 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Platform android successfully added. v8.0.0
Preparing project...
Compiling @angular/core : module as esm2015
Compiling @angular/animations : module as esm2015
Compiling @angular/animations/browser : module as esm2015
Compiling @angular/common : module as esm2015
Compiling @angular/platform-browser : module as esm2015
Compiling @angular/router : module as esm2015
Compiling @angular/common/http : module as esm2015
Compiling @angular/platform-browser/animations : module as esm2015
Compiling @angular/forms : module as esm2015
Compiling @nativescript/angular : module as esm2015
webpack is watching the files...
FooBar\node_modules\webpack\lib\NormalModule.js:180
                        throw new TypeError(
                        ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (FooBar\node_modules\webpack\lib\NormalModule.js:180:10)
    at FooBar\node_modules\webpack\lib\HotModuleReplacementPlugin.js:756:18
    at Hook.eval [as call] (eval at create (FooBar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:102:1)
    at Hook.CALL_DELEGATE [as _call] (FooBar\node_modules\webpack\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (FooBar\node_modules\webpack\lib\Compiler.js:1017:26)
    at FooBar\node_modules\webpack\lib\Compiler.js:1059:29
    at Hook.eval [as callAsync] (eval at create (FooBar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (FooBar\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (FooBar\node_modules\webpack\lib\Compiler.js:1054:28)
    at FooBar\node_modules\webpack\lib\Watching.js:134:19
    at _next0 (eval at create (FooBar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (FooBar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at FooBar\node_modules\@nativescript\webpack\dist\plugins\WatchStatePlugin.js:22:13
    at Hook.eval [as callAsync] (eval at create (FooBar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (FooBar\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at run (FooBar\node_modules\webpack\lib\Watching.js:88:33)
```
**To Reproduce**
```
>tns create
>cd ProjectDir
>ns preview
```

**Expected behavior**
Properly compiled code.

**Comment by Marooned-MB** [comment]
Originally in package.json there is:
```    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~11.2.6",
```
I've tried to upgrade to the latest version:
```
    "@nativescript/webpack": "~4.1.0",
    "@ngtools/webpack": "~12.0.0",
```
but this gives me another error:
```
FooBar\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

TypeError: Class extends value undefined is not a constructor or null
    at getAngularCompilerPlugin (FooBar\node_modules\@nativescript\webpack\plugins\NativeScriptAngularCompilerPlugin.js:7:63)
    at module.exports (FooBar\webpack.config.js:26:32)
    at handleFunction (FooBar\node_modules\webpack-cli\bin\utils\prepareOptions.js:21:13)
    at prepareOptions (FooBar\node_modules\webpack-cli\bin\utils\prepareOptions.js:9:5)
    at requireConfig (FooBar\node_modules\webpack-cli\bin\utils\convert-argv.js:117:14)
    at FooBar\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (FooBar\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at FooBar\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (FooBar\node_modules\webpack-cli\node_modules\yargs\yargs.js:576:18)
    at FooBar\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (FooBar\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (FooBar\node_modules\import-local\index.js:16:66)
    at FooBar\node_modules\webpack-cli\bin\cli.js:15:6
    at Object.<anonymous> (FooBar\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (FooBar\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Executing webpack failed with exit code 1.
```

**Comment by rigor789** [comment]
`"@nativescript/webpack": "~4.1.0"` isn't compatible with the new `webpack.config.js` format if your project is using it (if the config is relatively short ~a few lines, it's the new config, otherwise the old one). The initial error usually comes from having multiple "instances" of webpack in the `node_modules` folder and it's related to webpack using `instanceof` checks since webpack5. While not ideal, can you try installing with a different package manager (like `yarn`) and see if that makes a difference? 

The structure of `node_modules` differs between package managers and can lead to this error - which IMO shouldn't be an error, but the webpack team considers it correct and wontfix. We'll be looking at possibly changing how we handle the dependencies and hopefully work around this limitation within the beta period...

**Comment by Marooned-MB** [comment]
So it looks like `tns create` create incompatible environment for newly created project? I haven't done anything manually, just install NS from scratch on clean PC, call `tns create` and got this error when trying to launch, so it's up to NS to add proper version of webpack to dependencies.

**Comment by rigor789** [comment]
@Marooned-MB it should be working (we have tested the templates multiple times on windows & mac machines, and they have been working at the time - the issue could be related to a transitive dependency change that updated in the meantime), but I've seen variances between different systems and occasionally `node_modules` is different causing that error. It's definitely up to us to find a once-for-all fix - just sharing what I know/seen related to this to hopefully get it running on your end.

**Comment by Marooned-MB** [comment]
I'll try to update node/npm in the evening and start yet another fresh project to test if maybe npm version is the case. Will update here after this test. Thanks.

**Comment by rigor789** [comment]
@Marooned-MB the `--bundle` flag has been enabled by default since NS 5 I believe so no need to use it - what it does is bundle the application code using webpack. Prior versions worked without bundling by transferring all files as-is, but that workflow is no longer supported.

**Comment by farfromrefug** [comment]
that error happens when 2 different versions of webpack are used. in my case it was because I was adding webpack to my app package.json. then my webpack config was using my version  but @nativescript/webpack was using a different version (from its node_modules folder inside my node_modules one). 
it is an error coming from the way node_modules work. 
bad thing but the only solution is to not have webpack in your package.json

**Comment by Marooned-MB** [comment]
Ok, I'll check that but as I said, I did not alter any files that `tns create` has created. Just `tns create` and then `tns run android` or `tns preview` to check if it's working.

**Comment by Marooned-MB** [comment]
Ok, I have created yet another clean project from scratch and this time with better luck (no Idea what was the difference, I've removed the old one).
```
c:\ns>tns create

# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)
√ First, what will be the name of your app? ... Foo

√ Next, which style of NativeScript project would you like to use: » Angular

√ Finally, which template would you like to start from: » Hello World

> @nativescript/core@8.0.5 postinstall c:\ns\Foo\node_modules\@nativescript\core
> node cli-hooks/postinstall.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @ngtools/webpack@11.2.13 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.

added 447 packages from 285 contributors and audited 448 packages in 24.08s

40 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[@nativescript/webpack] Initialized config.

Project Foo was successfully created.

Now you can navigate to your project with $ cd Foo

After that you can preview it on device by executing $ ns preview


c:\ns>cd Foo

c:\ns\Foo>ns preview
```
then after some logs:
```
webpack 5.31.2 compiled successfully in 26112 ms
The files to upload exceed the maximum allowed size of 15MB. Your app might not work as expected.
```
(quite a large project for hello world but let's move forward)
```
Start syncing changes for device phone (id).
Successfully synced 'bundle.js,bundle.0e86216c6bdf5183407f.hot-update.js,bundle.0e86216c6bdf5183407f.hot-update.json' for device phone (id).
LOG from device phone: An uncaught Exception occurred on "main" thread.
Error running script /data/user/0/org.nativescript.preview/files/internal/livesync.js
Error: com.tns.playlivesync.NativeScriptActivity@9df6268[CALLBACKS] is null or undefined

StackTrace:
error(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/trace/trace.js:204:17)
        at Frame.reloadPage(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/frame.js:78:28)
        at livesync(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/application/application-common.js:81:9)
        at __onLiveSync(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/application/application.js:205:26)
        at (/data/user/0/org.nativescript.preview/files/internal/livesync.js:2:9)
        at com.tns.Runtime.runScript(Native Method)
        at com.tns.Runtime.access$2100(Runtime.java:39)
        at com.tns.Runtime$2.run(Runtime.java:699)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

So I stopped it and run `ns preview` again.
```
webpack 5.31.2 compiled successfully in 597 ms
Webpack compilation complete. Watching for file changes.
The files to upload exceed the maximum allowed size of 15MB. Your app might not work as expected.
Start syncing changes for device phone (id).
Successfully synced 'bundle.js,bundle.0e86216c6bdf5183407f.hot-update.js,bundle.0e86216c6bdf5183407f.hot-update.json' for device phone (id).
LOG from device phone: [HMR][id] success | Successfully applied update.
LOG from device phone: Unhandled Promise rejection: Cannot find android activity callbacks. ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find android activity callbacks. Error: Cannot find android activity callbacks.
LOG from device phone: at Object._resetRootView [as resetRootView] (file:///data/data/org.nativescript.preview/files/app/vendor.js:101690:15) [<root>]
LOG from device phone: ERROR TypeError: Cannot set property 'nodeName' of undefined
LOG from device phone: at drainMicroTaskQueue (file:///data/data/org.nativescript.preview/files/app/vendor.js:144079:35) [<root>]
LOG from device phone: at file:///data/data/org.nativescript.preview/files/app/vendor.js:144367:34 [<root>]
LOG from device phone: at file:///data/data/org.nativescript.preview/files/app/vendor.js:95075:74 [<root>]
LOG from device phone: Angular is running in development mode. Call enableProdMode() to enable production mode.
```

But it worked, I saw the list. So I decided to check live update. I changed `<ActionBar title="My App"> </ActionBar>` to `<ActionBar title="Foo"> </ActionBar>` - rather simple change I would guess. Unfortunately, I got yet another error:

```
webpack 5.31.2 compiled successfully in 2628 ms
Webpack compilation complete. Watching for file changes.
Start syncing changes for device phone (id).
Successfully synced 'bundle.js,bundle.be8144010575d99d0057.hot-update.js,bundle.be8144010575d99d0057.hot-update.json' for device phone (id).
LOG from device phone: Error: Could not load CSS from app.css: Error: require's first parameter should be string
LOG from device phone: An uncaught Exception occurred on "main" thread.
Error running script /data/user/0/org.nativescript.preview/files/internal/livesync.js
TypeError: Cannot read property '_callbacks' of undefined

StackTrace:
Frame.reloadPage(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/frame.js:69:33)
        at livesync(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/application/application-common.js:81:9)
        at __onLiveSync(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/application/application.js:205:26)
        at (/data/user/0/org.nativescript.preview/files/internal/livesync.js:2:9)
        at com.tns.Runtime.runScript(Native Method)
        at com.tns.Runtime.access$2100(Runtime.java:39)
        at com.tns.Runtime$2.run(Runtime.java:699)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Unable to get LiveSync status from the Preview app for device phone (id). Ensure the app is running in order to sync changes.
```
And at this point no more changes have been updated on the phone despite next changes, so I give it another try with fresh `ns preview`:
```
webpack 5.31.2 compiled successfully in 947 ms
Webpack compilation complete. Watching for file changes.
Unable to apply changes for device phone (id). Error is: Error: ENOENT: no such file or directory, open 'c:\ns\Foo\platforms\android\app\src\main\assets\app\bundle.48f05606f50dfa5c8e8c.hot-update.js', {
  "errno": -4058,
  "syscall": "open",
  "code": "ENOENT",
  "path": "c:\\ns\\Foo\\platforms\\android\\app\\src\\main\\assets\\app\\bundle.48f05606f50dfa5c8e8c.hot-update.js"
}.
```

So.. I managed to see the list (so proper application) a few times but some of initial compilation gave the error and also simple change also lead to another error.

Definitely some progress since the last attempt but still not there. Any suggestions? Thanks

```
>node -v
v14.16.0
>npm -v
6.14.11
```

**Comment by Ziggymusician** [comment]
Hi al, any luck on this... I just migrated my Angular Shared Project (Web + App) to Angular v12 and NativeScript v8 and I get the 2 errors related to "The 'compilation' argument must be an instance of Compilation".

`webpack 5.31.2 compiled with 2 errors and 1052 warnings`

The 1052 warnings are warnings like: 

```
WARNING in /src/app/store/utils/router-custom-serializer.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in /src/environments/environment.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in /src/main.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

And 2 errors:

```
ERROR in ./src/main.tns.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (/angular_nativescript/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:125:10)
    at /angular_nativescript/node_modules/webpack/lib/javascript/CommonJsChunkFormatPlugin.js:43:19
    at Hook.eval [as call] (eval at create (/angular_nativescript/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/angular_nativescript/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:1016:30)
    at /angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:1059:29
    at Hook.eval [as callAsync] (eval at create (/angular_nativescript/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/angular_nativescript/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:1054:28)
    at Compiler.runAsChild (/angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:518:8)
    at /angular_nativescript/node_modules/@ngtools/webpack/src/resource_loader.js:150:27
    at new Promise (<anonymous>)
    at WebpackResourceLoader._compile (/angular_nativescript/node_modules/@ngtools/webpack/src/resource_loader.js:149:16)
    at WebpackResourceLoader.get (/angular_nativescript/node_modules/@ngtools/webpack/src/resource_loader.js:239:44)
    at Object.resourceHost.readResource (/angular_nativescript/node_modules/@ngtools/webpack/src/ivy/host.js:30:35)
    at AdapterResourceLoader.preload (/angular_nativescript/node_modules/@angular/compiler-cli/src/ngtsc/resource/src/loader.js:88:39)

ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (/angular_nativescript/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:125:10)
    at /angular_nativescript/node_modules/webpack/lib/javascript/CommonJsChunkFormatPlugin.js:43:19
    at Hook.eval [as call] (eval at create (/angular_nativescript/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/angular_nativescript/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:1016:30)
    at /angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:1059:29
    at Hook.eval [as callAsync] (eval at create (/angular_nativescript/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/angular_nativescript/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:1054:28)
    at Compiler.runAsChild (/angular_nativescript/node_modules/@nativescript/webpack/node_modules/webpack/lib/Compiler.js:518:8)
    at /angular_nativescript/node_modules/@ngtools/webpack/src/resource_loader.js:150:27
    at new Promise (<anonymous>)
    at WebpackResourceLoader._compile (/angular_nativescript/node_modules/@ngtools/webpack/src/resource_loader.js:149:16)
    at WebpackResourceLoader.get (/angular_nativescript/node_modules/@ngtools/webpack/src/resource_loader.js:239:44)
    at Object.resourceHost.readResource (/angular_nativescript/node_modules/@ngtools/webpack/src/ivy/host.js:30:35)
    at AdapterResourceLoader.preload (/angular_nativescript/node_modules/@angular/compiler-cli/src/ngtsc/resource/src/loader.js:88:39)
```
This is thrown by Webpack: node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:125:10

```
class JavascriptModulesPlugin {
	/**
	 * @param {Compilation} compilation the compilation
	 * @returns {CompilationHooks} the attached hooks
	 */
	static getCompilationHooks(compilation) {
		if (!(compilation instanceof Compilation)) {
			throw new TypeError(
				"The 'compilation' argument must be an instance of Compilation"
			);
		}
		let hooks = compilationHooksMap.get(compilation);
........
```
Meaning it expects a Compilation object... but some plugin is providing a non-Compilation object. Anyone please help... need to do some work on the App... 

Thanks.
