### ISSUE TITLE
Livesync reload crashes android preview app

### ISSUE THREAD

**Issue by swiperthefox** [NativeScript/NativeScript#9442]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - Cross-platform modules: android
 - Android Runtime: 8.0.0
 - iOS Runtime: N/A
 - XCode Version:
 - Plugin(s): N/A
 - Preview App version: 1.30.0
 - Runtime version (of the preview app): 6.5.0

**Describe the bug**

While previewing the app in the Android `NS Preview` app, livesync will fail and throws the following error message.
```
An uncaught Exception occurred on "main" thread.
Error running script /data/user/0/org.nativescript.preview/files/internal/livesync.js
TypeError: Cannot read property '_callbacks' of undefined

StackTrace:
Frame.reloadPage(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/frame.js:69:33)
        at livesync(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/application/application-common.js:81:9)
        at __onLiveSync(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/application/application.js:205:26)
        at (/data/user/0/org.nativescript.preview/files/internal/livesync.js:2:9)
        at com.tns.Runtime.runScript(Native Method)
        at com.tns.Runtime.access$2100(Runtime.java:39)
        at com.tns.Runtime$2.run(Runtime.java:699)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
**To Reproduce**

1. Create a new app (vue version if it matters) using the "blank" template.
2. Run "tns preview" to start preview.
3. Open the app on an Android phone.
4. Change the text of message in the "home.vue".
5. Save to trigger a livesync.
6. Livesync will fail with exception raised.

**Expected behavior**
The app should rfreshed with the new content.

**Sample project**

**Additional context**

*Update*: The following problem of livesync with playground examples has gone after I restarted my x-session. But the issue described above still exists.
~I also experienced problems with preview livesyncing the examples from  [Playground](https://play.nativescript.org), but with different symptom: open the example in the preview app, make a simple change, and click the "preview" button. This time nothing happens in the preview app, no exceptions throwed, but app is not synchronized neither.~

**Comment by timchen0607** [comment]
I also encountered the same problem.

**Comment by swiperthefox** [comment]
#### Update and Closing this Issue

Now I am using "tns run" command to run the app during development. It has everything I am looking for in the `Preview` app:
1. Live synchronization on code changes
2. Minimal change set: only the relevant js diffs are sent, unless I made changes that affect the android part of the app (like changing the app id, or add an plugin), in which case a full build is triggered.

Furthermore, the preview app might has some missing plugins, or some outdated ones, while the app built by "tns run" command always has the plugins just as you configured.

It seems for me that the preview app is phasing out (updated 1 year ago, lagging android version,...etc), so I am going to closing this issue.
