### ISSUE TITLE
[ios] Application fails to start using JSC runtime and Webpack 5

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#9469]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules: 8.0.8
 - Android Runtime: 8.0
 - iOS Runtime: 6.5.4
 - XCode Version:
 - Plugin(s):

**Describe the bug**
Seems there is some problem with starting applications with the Webpack 5 and that run on the old JSC iOS runtime. Running the app on Android works just fine. Also running the app with the v8 runtime works fine. Here is a snip of the error log that shows up - seems for some reason it cannot find the start module. I've checked the `bundle.js` that gets created and the module is present there and looks fine. 

```
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.test>
CONSOLE WARN file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/web-view/index.ios.js:111:0 Objective-C class name "UIScrollViewDelegateImpl" is already in use - using "UIScrollViewDelegateImpl1" instead.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x102dbb62e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x102dfc3a8 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x1037f7c90 ffi_closure_unix64_inner
4   0x1037f86b2 ffi_closure_unix64
5   0x1055cd851 ___CFXRegistrationPost_block_invoke
6   0x1055ccf81 _CFXRegistrationPost
7   0x1055cc8ef _CFXNotificationPost
8   0x10409f027 -[NSNotificationCenter postNotificationName:object:userInfo:]
9   0x1071964a5 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]
10  0x10719bd63 -[UIApplication _runWithMainScene:transitionContext:completion:]
11  0x1067bd29b -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
12  0x106d49726 _UIScenePerformActionsWithLifecycleActionMask
13  0x1067bddad __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
14  0x1067bd86e -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
15  0x1067bdbda -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
16  0x1067bd46f -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
17  0x1067c56d8 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
18  0x106c5377d +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
19  0x106d6660e _UISceneSettingsDiffActionPerformChangesWithTransitionContext
20  0x1067c53de -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
21  0x1065e87d5 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
22  0x1065e724e -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
23  0x1065e840e -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
24  0x10719a203 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
25  0x106c7bab4 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
26  0x10fcc140b -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:]
27  0x10fce9e55 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.176
28  0x10fccef12 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
29  0x10fce9b28 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke
30  0x105e878df _dispatch_client_callout
31  0x105e8aa87 _dispatch_block_invoke_direct
JavaScript stack trace:
loadInternal(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:104:0
at createViewFromEntry(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:36:0
at createRootView(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:317:50
at setWindowContent(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:258:0
at notifyAppStarted(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:169:0
at didFinishLaunchingWithOptions(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:152:0
at didFinishLaunchingWithOptions([native code])
at file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:42:0
at UIApplicationMain([native code])
at run(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:336:0
at ./app/app.ts(file:///app/bundle.js:69:64)
at __webpack_require__(file: app/webpack:/@nativescript/template-hello-world-ts/webpack/bootstrap:24:0
at __webpack_exec__(file:///app/bundle.js:372:58)
at file:///app/bundle.js:373:159
at file: app/webpack:/@nativescript/template-hello-world-ts/webpack/runtime/startup entrypoint:6:0
at file:///app/bundle.js:373:48
at anonymous(file:///app/bundle.js:378:3)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:104:0 JS ERROR Error: Failed to load component from module: app-root
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Failed to load component from module: app-root
at
loadInternal(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:104:0
at createViewFromEntry(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:36:0
at createRootView(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:317:50
at setWindowContent(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:258:0
at notifyAppStarted(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:169:0
at didFinishLaunchingWithOptions(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:152:0
at didFinishLaunchingWithOptions([native code])
at file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:42:0
at UIApplicationMain([native code])
at run(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:336:0
at ./app/app.ts(file:///app/bundle.js:69:64)
at __webpack_require__(file: app/webpack:/@nativescript/template-hello-world-ts/webpack/bootstrap:24:0
at __webpack_exec__(file:///app/bundle.js:372:58)
at file:///app/bundle.js:373:159
at file: app/webpack:/@nativescript/template-hello-world-ts/webpack/runtime/startup entrypoint:6:0
at file:///app/bundle.js:373:48
at anonymous(file:///app/bundle.js:378:3)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native c<…>
NativeScript caught signal 6.
Native Stack:
1   0x102e0c171 sig_handler(int)
2   0x7fff60335d7d _sigtramp
3   0x7ffeed5cece0
4   0x106045cb5 abort
5   0x105d45692 abort_message
6   0x105d36dfd demangling_unexpected_handler()
7   0x104f6cace _objc_terminate()
8   0x105d44aa7 std::__terminate(void (*)())
9   0x105d44a49 std::terminate()
10  0x105e878f3 _dispatch_client_callout
11  0x105e8aa87 _dispatch_block_invoke_direct
12  0x10fd0f5d0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
13  0x10fd0f2b6 -[FBSSerialQueue _targetQueue_performNextIfPossible]
14  0x10fd0f77b -[FBSSerialQueue _performNextFromRunLoopSource]
15  0x1055faede __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  0x1055fadd6 __CFRunLoopDoSource0
17  0x1055fa300 __CFRunLoopDoSources0
18  0x1055f49f7 __CFRunLoopRun
19  0x1055f41a7 CFRunLoopRunSpecific
20  0x110016d85 GSEventRunModal
21  0x1071984df -[UIApplication _run]
22  0x10719d39c UIApplicationMain
23  0x1037f84f5 ffi_call_unix64
24  0x11c0b5790
JS Stack:
UIApplicationMain([native code])
at run(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:336:0
at ./app/app.ts(file:///app/bundle.js:69:64)
at __webpack_require__(file: app/webpack:/@nativescript/template-hello-world-ts/webpack/bootstrap:24:0
at __webpack_exec__(file:///app/bundle.js:372:58)
at file:///app/bundle.js:373:159
at file: app/webpack:/@nativescript/template-hello-world-ts/webpack/runtime/startup entrypoint:6:0
at file:///app/bundle.js:373:48
at anonymous(file:///app/bundle.js:378:3)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob
```

**To Reproduce**
```
tns create test --ts
cd test
npm install -D @nativescript/ios@JSC
tns run ios
```

**Expected behavior**
The app should run when using the old JSC runtime. 

**Sample project**

**Additional context**

**Comment by PeterStaev** [comment]
I've traced this a bit further - seems the problem is with the loading of the modules. In the `bundle.js` there is the following code:
```js
var __webpack_exports__ = __webpack_require__.X(0, ["vendor"], () => (__webpack_exec__("./node_modules/@nativescript/core/globals/index.js"), __webpack_exec__("./app/app.ts"), __webpack_exec__("./app/__@nativescript_webpack_virtual_entry_typescript__")));
```
This basically loads the application module before loading the virtual entry points which add all the pages' modules. I guess with the V8 runtime this is not a problem but for JSC this messes up the app. I've changed the line to read:
```js
var __webpack_exports__ = __webpack_require__.X(0, ["vendor"], () => (__webpack_exec__("./node_modules/@nativescript/core/globals/index.js"), __webpack_exec__("./app/__@nativescript_webpack_virtual_entry_typescript__"), __webpack_exec__("./app/app.ts")));
```

And now the test app seems to work fine. 

So seems this line:
https://github.com/NativeScript/NativeScript/blob/0fd53e3abbbb035dd11914663c0f92de97717c95/packages/webpack5/src/configuration/typescript.ts#L24

Should be changed and instead of appending the virtual module at the end, to add it just before the app module. 

Related to #9038

**Comment by PeterStaev** [comment]
I was able to workaround the problem by overwriting the bad webpack config in the app's webpack config:
```js
    webpack.chainWebpack((config) => {
        // HACK: Fix bundle entry points order. 
        const bundleEntry = config.entry("bundle");
        const bundleItems = bundleEntry.values();
        for (const item of bundleItems) {
            if (item.indexOf("app.ts") > 0) {
                bundleEntry.delete(item);
                bundleEntry.add(item);
                break;
            }
        }
        // END HACK
    });

```
