### ISSUE TITLE
ns device android throws error

### ISSUE THREAD

**Issue by bradrice** [NativeScript/NativeScript#9503]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 ✔ Component nativescript has 8.0.2 version and is up to date.
✔ Component @nativescript/core has 8.0.8 version and is up to date.
✔ Component @nativescript/ios has ^8.0.0 version and is up to date.
✔ Component @nativescript/android has 8.0.0 version and is up to date.

**Describe the bug**
running ns device throws this error

Searching for devices...
Error: spawn C:\Users\brice\AppData\Roaming\npm\node_modules\nativescript\node_modules\ios-device-lib\bin\win32\x64ios-device-lib ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**To Reproduce**
ns device android

I'm running it on a Windows 10 machine using a Powershell.

**Expected behavior**
Should give a list of devices or say no devices available

**Comment by bradrice** [comment]
I restarted my terminal and am getting the right behavior now.
