### ISSUE TITLE
nativescript-ui-autocomplete crash on type 

### ISSUE THREAD

**Issue by ouss4m4** [NativeScript/NativeScript#9538]
**Environment**
 - CLI: 8.0.2
 - Cross-platform modules:  Provided in package.json below
 - Android Runtime: N/A
 - iOS Runtime: 14.4
 - XCode Version: 12.4
 - Plugin(s): nativescript-ui-autocomplete

**Package.json**

```
"dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/theme": "^3.0.1",
    "@ngrx/effects": "^9.0.0",
    "@ngrx/store": "^9.0.0",
    "@ngrx/store-devtools": "^9.0.0",
    "@triniwiz/nativescript-socketio": "^5.0.1",
    "nativescript-feedback": "^2.0.0",
    "nativescript-modal-datetimepicker": "^2.1.5",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^8.0.0",
    "nativescript-ui-chart": "^9.0.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.4.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",
    "@nativescript/android": "8.0.0",
    "@nativescript/webpack": "~5.0.0-beta.0",
    "@ngtools/webpack": "~11.2.6",
    "@nativescript/types": "~8.0.0",
    "codelyzer": "^4.5.0",
    "tslint": "^5.11.0",
    "typescript": "~4.0.0"
  }
```

**Describe the bug**
when i run ns platform add android , i get this warning: 

```
WARNING in ./node_modules/nativescript-ui-autocomplete/__ivy_ngcc__/angular/fesm2015/nativescript-ui-autocomplete-angular.js 165:48-74
export 'extractSingleViewRecursive' (imported as 'extractSingleViewRecursive') was not found in '@nativescript/angular'
```
the app runs on both platforms. and crashes when i type anything inside the autocomplete input. with the following error: 

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateViewHolder failed
System.err: TypeError: rootLocator is not a function
System.err:
System.err: StackTrace:
System.err: getItemViewRoot(file: node_modules\nativescript-ui-autocomplete\__ivy_ngcc__\angular\fesm2015\nativescript-ui-autocomplete-angular.js:166:0)
System.err:     at RadAutoCompleteTextViewComponent._autoCompleteTextView.itemViewLoader(file: node_modules\nativescript-ui-autocomplete\__ivy_ngcc__\angular\fesm2015\nativescript-ui-autocomplete-angular.js:29:0)
System.err:     at getViewForViewType(file: node_modules\nativescript-ui-autocomplete\common.js:277:0)
System.err:     at AutoCompleteAdapter.onCreateViewHolder(file: node_modules\nativescript-ui-autocomplete\index.android.js:90:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.com.telerik.widget.autocomplete.AutoCompleteAdapter_vendor_161763_28_AutoCompleteAdapter.onCreateViewHolder(AutoCompleteAdapter_vendor_161763_28_AutoCompleteAdapter.java:47)
System.err:     at com.tns.gen.com.telerik.widget.autocomplete.AutoCompleteAdapter_vendor_161763_28_AutoCompleteAdapter.onCreateViewHolder(AutoCompleteAdapter_vendor_161763_28_AutoCompleteAdapter.java:8)
System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
System.err:     at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
System.err:     at android.view.View.layout(View.java:20672)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
System.err:     at android.view.View.layout(View.java:20672)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at android.view.View.layout(View.java:20672)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at android.view.View.layout(View.java:20672)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6194)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:696)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Expected behavior**
should show a list of items i can click on to add as chips, this happened after i migrated to ns{8} from 6
this happens with the nativescript-ui-autocomplete ^8.x.x
when i tried with the autocomplete version 7.x.x i got a crashing error,
the 6.x.x version does not work with my current angular/ns i guess

**Comment by NathanWalker** [comment]
Thank you for reporting this, we'll get a patch update out shortly for this.

**Comment by NathanWalker** [comment]
Actually @ouss4m4 could you update all your Angular dep's to latest: `"^12.0.0",

And also the following:
```
"@nativescript/angular": "^12.0.0",
"@ngrx/effects": "12.4.0",
 "@ngrx/store": "12.4.0",
"@ngrx/store-devtools": "12.4.0",
```
You can also remove `reflect-metadata` as no longer used.

Your devDependencies should look like this:
```
"devDependencies": {
    "@angular/compiler-cli": "^12.0.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/webpack": "rc",
    "@ngtools/webpack": "^12.0.0",
    "@nativescript/types": "~8.0.0",
    "tslint": "^5.11.0",
    "typescript": "~4.2.0"
  }
```
You can also add the `polyfills.ts` file mentioned here - see this post for all the details:
https://blog.nativescript.org/nativescript-angular-12/index.html

nativescript-ui-autocomplete ^8.x.x - is for Angular 12+

**Comment by ouss4m4** [comment]
Thank you for the clarification @NathanWalker .
i just updated my package.json  ,added my pollyfills, referenced my namespace, that removed all the errors on my side.
but now i am struggling with 4 errors that are related to webpack removing pollyfills on version 5 i guess ?.  

`ERROR in ./node_modules/css/lib/stringify/source-map-support.js 9:9-22
Module not found: Error: Can't resolve 'fs' in '~\node_modules\css\lib\stringify'`

`ERROR in ./node_modules/source-map-resolve/index.js 3:14-29
Module not found: Error: Can't resolve 'path' in '~\node_modules\source-map-resolve'`


`ERROR in ./node_modules/source-map-resolve/index.js 2:13-27
Module not found: Error: Can't resolve 'url' in '~\node_modules\source-map-resolve'`

i tried with both: 

`"@nativescript/webpack": "rc",`

`"@nativescript/webpack": "beta",`

**Comment by NathanWalker** [comment]
I haven't seen these before - perhaps @rigor789 may have idea?

**Comment by kandangit** [comment]
In my case, the app crashes after upgrade of @nativescript/core from 8.0.0 to 8.1.0

I believe is the same or related to this issue.

It does on a screen with a ListView;
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method getView failed
System.err: ReferenceError: __UI_USE_EXTERNAL_RENDERER__ is not defined
System.err:
System.err: StackTrace:
System.err: createView(file: src\webpack:\@nativescript\template-blank-ng\node_modules\@nativescript\core\ui\list-view\list-view-common.js:20:0)
System.err:     at ListViewAdapter.getView(file: src\webpack:\@nativescript\template-blank-ng\node_modules\@nativescript\core\ui\list-view\index.android.js:310:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.android.widget.BaseAdapter_vendor_102261_28_ListViewAdapter.getView(BaseAdapter_vendor_102261_28_ListViewAdapter.java:39) 
```

I reverted the version back to 8.0.0 so it works.

**Comment by rigor789** [comment]
@ouss4m4 @NathanWalker first time seeing that, suspect it's some dependency loading issue, but would need a test project to debug/figure out. One thing that could affect it is if your `main` in `package.json` is incorrect, it should point to the actual entry file of your app like `"main": "./src/main.ts"`.

@kandangit if you are using `@nativescript/webpack` update it to `5.0.0` - if you are on webpack4, you need to add 3 lines to your webpack config:

<details>

<summary>These are the webpack4 config changes required</summary>

```js
new webpack.DefinePlugin({
  'global.TNS_WEBPACK': 'true',
  'global.isAndroid': platform === 'android',
  'global.isIOS': platform === 'ios',
  process: 'global.process',
  // add these 3:
  __UI_USE_XML_PARSER__: true,
  __UI_USE_EXTERNAL_RENDERER__: false,
  __CSS_PARSER__: JSON.stringify('css-tree')
}),
```

</details>

**Comment by kandangit** [comment]
@rigor789 

Many thanks, that worked. I had already upgraded but to "5.0.0-beta.16" with `npm i --save-dev @nativescript/webpack` instead.

Setting to 5.0.0 fixed the issue. Cheers.

**Comment by ouss4m4** [comment]
@rigor789 @NathanWalker 

i could not resolve the issue with nativescript-ui-automcplete 8 and angular 12. 
i rolled back to the following config 

```
"dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7", 
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/core": "~8.0.0",  <-------
    "@nativescript/theme": "^3.0.1",
    "@ngrx/effects": "^9.0.0",
    "@ngrx/store": "^9.0.0",
    "@ngrx/store-devtools": "^9.0.0",
    "@triniwiz/nativescript-socketio": "^5.0.1",
    "nativescript-feedback": "^2.0.0",
    "nativescript-modal-datetimepicker": "^2.1.5",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "~7.0.0",  <-------
    "nativescript-ui-chart": "^9.0.0",
    "rxjs": "^6.4.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",  <-------
    "@nativescript/android": "8.0.0",
    "@nativescript/webpack": "~5.0.0-beta.0",
    "@ngtools/webpack": "~11.2.6",
    "@nativescript/types": "~8.0.0",
    "tslint": "^5.11.0",
    "typescript": "~4.0.0"
  }
```
Now everything works on Android again. 

but in iOS i got the multitask error when 2 different packages rely on the same package but on different version,  i used xCode to remove one binary from being assigned (the - key on xCode after i build up the platform) 

iOS now bundles again and run the app, but when i type something in the autocomplete it crashed, with the following error

`Uncaught TypeError: Cannot read property 'itemview' of undefined` 

i'm pretty sure this is still a non compatible version error, but i can not find a nativescript-ui-autocomplete version that works with angular 11, 
due to the urgency, i will deploy my ns{6} version. with both platforms using autocomplete, 
and migrate to angular 12 again, and try to resolve the webpack issues if i can not find a version that works with NS8 + NG11

**Comment by zaSmilingIdiot** [comment]
I'm appending to this with more info related to my specific use case as its related to the `Uncaught TypeError: Cannot read property 'itemview' of undefined` error.

applicable dependencies are as follows:
```
  "dependencies": {
    "@nativescript/core": "~8.1.1",
    "nativescript-ui-autocomplete": "^8.0.0",
    "nativescript-ui-dataform": "^8.0.0",
    "nativescript-ui-listview": "^10.0.0",
    "nativescript-vue": "~2.9.0",
  },
  "devDependencies": {
    "@nativescript/android": "~8.1.1",
    "@nativescript/ios": "~8.1.0",
    "@nativescript/webpack": "~5.0.0",
    "nativescript": "^8.1.5",
    "nativescript-vue-template-compiler": "~2.9.0",
    "vue": "~2.6.12"
  }
```
There's a couple more but those are the just of it.

The error generated from running `ns debug ios --no-hmr` is as follows (note that I've replaced the project folder with XXXXXXX:
```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'itemView' of undefined
at
SuggestionViewCell.layoutSubviews(file: app/webpack:/XXXXXXX/node_modules/nativescript-ui-autocomplete/index.ios.js:60:0)
```

In our particular case, I'm using the async data fetching described here: https://v7.docs.nativescript.org/vuejs/ns-ui/autocompletetextview/aync-data

What has been noted is that the first data fetch works perfectly. The SuggestView window displays the correct results, and on selection of a suggested token the autocomplete control does what it does correctly.
The selected token can then be removed, and re-added multiple times, with the express constraint that the suggestions eventually rendered into the SuggestionView are exactly the same as before.

However, if the suggested token(s) rendered in the SuggestionView are not the same as the first successful rendering, then the `Cannot read property 'itemView' of undefined` error occurs.
From the debug output, nativescript appears to be creating the SuggestionView template layouts correctly for each of the new suggestions. At least the CreateElement and AppendChild ouputs are created for each of the suggestions that should be rendered. Its during the layout/render of the suggestions that the error occurs.

Might be helpful to note that prior to the app crashing, it can be very briefly seen that the suggestion view does in fact display, but with the incorrect suggestions shown (the suggestions shown are the ones loaded from the first successful rendering).

Also, I'm happy to provide more info if necessary.
