### ISSUE TITLE
Android app is always crushing on the emulator on windows10

### ISSUE THREAD

**Issue by Pritom-Mazhi** [NativeScript/NativeScript#9544]
**Environment**
 - NS CLI: 5.4.1
 - Node: 12.18.2

**Describe the bug**

**tns doctor**
```
D:\Shigoto\panama\panama-sp\src>tns doctor

Support for Node.js 12.18.2 is not verified. NativeScript CLI might not install or run properly.

√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.4.1 and the latest available version is 8.1.1.
‼ Update available for component tns-core-modules. Your current version is 5.4.3 and the latest available version is 6.5.27.
‼ Update available for component tns-android. Your current version is 5.4.0 and the latest available version is 6.5.3.
× Component tns-ios is not installed.
```

**tns buld android**
```
D:\Shigoto\panama\panama-sp\src>tns build android

Support for Node.js 12.18.2 is not verified. NativeScript CLI might not install or run properly.


* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*                                                                                                               *
*  You are using the Legacy Workflow.                                                                           *
*                                                                                                               *
*  With the upcoming NativeScript 6.0 the Webpack workflow will become the only way of building apps.           *
*  More info about the reasons for this change and how to migrate your project can be found in the link below:  *
*  https://www.nativescript.org/blog/the-future-of-building-nativescript-apps                                   *
*                                                                                                               *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *


Found peer TypeScript 2.9.2
Preparing project...
Successfully prepared plugin custom-social-google-plus-signin for android.
Successfully prepared plugin nativescript-background-http for android.
Successfully prepared plugin nativescript-barcodescanner for android.
Successfully prepared plugin nativescript-camera for android.
Successfully prepared plugin nativescript-carousel for android.
Successfully prepared plugin nativescript-fresco for android.
Successfully prepared plugin nativescript-i18n for android.
Successfully prepared plugin nativescript-imagepicker for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-ui-sidedrawer for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-permissions for android.
Successfully prepared plugin nativescript-ui-core for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from D:\Shigoto\panama\panama-sp\src\app\App_Resources\Android\app.gradle
         + using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-background-http\platforms\android\nativescript_background_http.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-barcodescanner\platforms\android\barcodescanner-release-2.1.6.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-barcodescanner\platforms\android\nativescript_barcodescanner.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-camera\platforms\android\nativescript_camera.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-fresco\platforms\android\processors-release.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-ui-sidedrawer\platforms\android\TNSSideDrawer-release.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
         + adding aar plugin dependency: D:\Shigoto\panama\panama-sp\src\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Task: traverseDirectory: Folder will be traversed completely: D:\Shigoto\panama\panama-sp\src\platforms\android\app\src\main\assets\app\tns_modules\tns-core-modules\ui
(node:10132) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Skip com.facebook.animated.gif.GifFrame
        Error: java.lang.NullPointerException
Skip com.facebook.animated.gif.GifImage
        Error: java.lang.NullPointerException
Project successfully built.
The build result is located at: D:\Shigoto\panama\panama-sp\src\platforms\android\app\build\outputs\apk\debug\app-debug.apk
```

**tns run android**　**CMD Log**
```
D:\Shigoto\panama\panama-sp\src>tns run android

Support for Node.js 12.18.2 is not verified. NativeScript CLI might not install or run properly.

Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Starting Android emulator with image name
Waiting for emulator device initialization...
Found peer TypeScript 2.9.2

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*                                                                                                               *
*  You are using the Legacy Workflow.                                                                           *
*                                                                                                               *
*  With the upcoming NativeScript 6.0 the Webpack workflow will become the only way of building apps.           *
*  More info about the reasons for this change and how to migrate your project can be found in the link below:  *
*  https://www.nativescript.org/blog/the-future-of-building-nativescript-apps                                   *
*                                                                                                               *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *


Skipping prepare.
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
JS: >>>> Initializing and checking for android/fresco
JS: ===================
JS: >>> Key: login.password  => strings.xml: Password
JS: >>> Key: login.email_address  => strings.xml: Email Address
JS: >>> Key: app_name  => strings.xml: Panama
JS: >>> Key: Panama  => strings.xml: Panama
JS: >>> Key: error.login.invalid_email_password  => strings.xml: Invalid email/password combination.
JS: =========================
JS: application.start() is deprecated; use application.run() instead
JS: Initializing fresco
Successfully synced application jp.co.waja.panama.mobile on device emulator-5554.
JS: Done, Initialized fresco
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.co.waja.panama.mobile/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "@nativescript/core/application", relative to: app/tns_modules/
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "@nativescript/core/application", relative to: app/tns_modules/
System.err:     at com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     at com.tns.Module.resolvePath(Module.java:55)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
System.err:     at android.app.Activity.performCreate(Activity.java:7136)
System.err:     at android.app.Activity.performCreate(Activity.java:7127)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err:     ... 11 more
JS: !!! NativeScriptError:  Error: The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
JS: Trace: !!! NativeScriptError:  Error: The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
JS: at <anonymous> (file:///data/data/jp.co.waja.panama.mobile/files/app/app.js:23:17)
JS: at Observable.notify (file:///data/data/jp.co.waja.panama.mobile/files/app/tns_modules/tns-core-modules/data/observable/observable.js:110:23)
JS: at global.__onUncaughtError (file:///data/data/jp.co.waja.panama.mobile/files/app/tns_modules/tns-core-modules/application/application-common.js:97:12)
```

**Emulator Log**
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.co.waja.panama.mobile/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "@nativescript/core/application", relative to: app/tns_modules/
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.tns.NativeScriptException: Failed to find module: "@nativescript/core/application", relative to: app/tns_modules/
	at com.tns.Module.resolvePathHelper(Module.java:146)
	at com.tns.Module.resolvePath(Module.java:55)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	... 11 more
```
Screenshot:
![emulator-problem-windows](https://user-images.githubusercontent.com/23057928/133223797-8d4e977b-d019-405e-95c9-3a58d519c106.png)

**Comment by rigor789** [comment]
NS CLI: 5.4.1 is a very old version - try updating to the latest version.

I believe the 8.1.1 CLI should be able to run your project, just a few things that will definitely need to be updated:
- `tns-core-modules` to `6.5.27`
- `tns-android` to `6.5.3`

If your app is not using webpack, then you will also need to integrate webpack, non-webpack apps are considered legacy and will not be supported.

**Comment by samiul-gtmi** [comment]
I'm trying to run a client project by building their existing environment. So that If it runs, I can perform some feature tests on it. After the test, the upgrade will be decided. Currently It runs perfectly fine on this environment on the client's windows machine.  So, therefore I need a fix on the old **nativescript-5.4.1** version.

**Comment by edusperoni** [comment]
> Failed to find module: "@nativescript/core/application", relative to: app/tns_modules/

This error implies that some plugin/dependency in your project is using the scoped package, which was introduced in 6.0 or 6.2 I believe. This means that one of your dependencies is in the wrong version that is not compatible with your NativeScript version (5.4). Your client probably has a different version of a package on their machine, so I suggest checking your package-lock.json.

There isn't any fix we can provide as there isn't a fix we can apply on core that would solve your issue. Also 5.4 is more than 3 years old and I believe that many changes from Google and Apple side regarding APIs and targetSdk would probably make you unable to publish an app/update on those stores (not only due to core version, but plugins as well). As such, there's very little incentive in supporting a version that can't be deployed to the stores anymore.

**Comment by samiul-gtmi** [comment]
Thank you very much for your detailed reply. I really appreciate it, because it helped me to understand the problem more clearly.
Can you kindly tell me the name of the plugin/dependency, that is using the scoped package and was introduced in later 6.0 or 6.2?

**Comment by sebj54** [comment]
If you'd like to run the project exactly like on your customer's computer, you should grap his `package-lock.json` file. 

Once you have this file in your project, run `npm ci`. You should then have the dependencies in the same version as your customer now.

`package-lock.json` is a very important file, it allows to pin dependencies on specific versions. [More info](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json).

**Comment by Pritom-Mazhi** [comment]
@sebj54  Thank you very much for your detailed reply, it solved the problem.
