### ISSUE TITLE
App crashes on Android with background-image: none

### ISSUE THREAD

**Issue by sebj54** [NativeScript/NativeScript#9546]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.1
 - Cross-platform modules: 8.1.1
 - Android Runtime: 8.1.1
 - iOS Runtime: N/A
 - XCode Version: N/A
 - Plugin(s): none

**Describe the bug**

When using `background-image: none` on a `Page`  or a `GridLayout` (did not test further), the app crashes.

Start the demo app, you'll see the crash.

```
An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: java.lang.StringIndexOutOfBoundsException: length=4; index=6

StackTrace:
refreshBorderDrawable(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:34056:24)
	at onBackgroundOrBorderPropertyChanged(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:33964:17)
	at _redrawNativeBackground(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:20608:66)
	at [backgroundInternal:setNative](file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:20588:14)
	at applyAllNativeSetters(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:18548:37)
	at initNativeView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:18475:9)
	at onResumeNativeUpdates(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19452:68)
	at _resumeNativeUpdates(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:18997:18)
	at onLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:18952:14)
	at onLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:20028:15)
	at (file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19035:74)
	at callFunctionWithSuper(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19029:9)
	at callLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19035:14)
	at loadView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19175:18)
	at (file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:18954:18)
	at eachChildView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:16745:13)
	at eachChildView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:31641:15)
	at eachChild(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:21626:14)
	at onLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:18953:14)
	at onLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:20028:15)
	at onLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:31413:15)
	at (file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19035:74)
	at callFunctionWithSuper(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19029:9)
	at callLoaded(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19035:14)
	at loadView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19175:18)
	at _addViewCore(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19170:18)
	at _addView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:19156:14)
	at onCreateView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:25731:19)
	at onCreateView(file:///data/data/org.nativescript.nsdebugbackground/files/app/vendor.js:23555:40)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.StringIndexOutOfBoundsException: length=4; index=6
	at java.lang.String.substring(String.java:2027)
	at org.nativescript.widgets.Utils.getDrawable(Utils.java:39)
	at org.nativescript.widgets.image.Worker.loadImage(Worker.java:136)
	at org.nativescript.widgets.BorderDrawable.refresh(BorderDrawable.java:272)
	... 26 more
```

**To Reproduce**

```
git clone https://github.com/sebj54/ns-debug-background.git
cd ns-debug-background
ns debug android
```

The sample app has been created with this command: `ns create ns-debug-background --vue`. I just added a CSS class on the main `GridLayout` and a style: `background-image: none`. 

**Expected behavior**

The app does not crash 😅 

**Sample project**

https://github.com/sebj54/ns-debug-background

**Additional context**

**Comment by farfromrefug** [comment]
@sebj54 thanks for the report will fix it tomorrow (if no one does it before ;))

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/NativeScript/releases/tag/8.1.2-core

**Comment by sebj54** [comment]
Thank you guys for the quick fix! You're awesome 😎
