### ISSUE TITLE
Can't seem to extend android application

### ISSUE THREAD

**Issue by Lucaszw** [NativeScript/NativeScript#9549]
I've been following the procedure to extend the android application here.:

https://docs.nativescript.org/advanced-concepts.html#extending-the-android-application

However i continually get the following error:
```bash
Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/kitchenmate/Desktop/kitchenmate-kiosk/platforms/android/app/src/main/java/com/kitchenmate/Application.java Class: com.kitchenmate.Application
```

I can surpress the problem by commenting the following after the first build in the webpack config
```js

	// webpack.chainWebpack(config => {
	// 	if (webpack.Utils.platform.getPlatformName() === 'android') {
	// 	  // make sure the path to the applicatioon.android.(js|ts)
	// 	  // is relative to the webpack.config.js
	// 	  // you may need to use `./app/application.android if
	// 	  // your app source is located inside the ./app folder.
	// 	  config.entry('application').add(resolve(__dirname, './app/application.android'))
	// 	}
	// })
	
	```

However, this seems to prevent the application from ever launching

I am using the latest version of nativescript (8.1.2), nativescript-android (8.1.1)

**Comment by Lucaszw** [comment]
Update: appears to work with angular starter projects (but not vanilla typescript / javascript projects)

**Comment by rigor789** [comment]
@Lucaszw ok I know why this is happening, and the "solution" right now would be to move the file outside the app/src folder.

Core has a `require.resolve` call in the entry file to resolve all other xml, ts etc files in the project. It also picks up this custom application class and conflicts with the custom entry added for it...

**Comment by Lucaszw** [comment]
Thanks @rigor789 ! That worked :)

**Comment by abdallahkadour** [comment]
@Lucaszw If I move the file outside the app/src folder. I get the following error on app start:
```js
ReferenceError: Cannot access 'SDK_VERSION' before initialization
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application org.vois.international.mgov.MGOVApplication: com.tns.NativeScriptException: Error calling module function 
System.err: ReferenceError: Cannot access 'SDK_VERSION' before initialization
System.err: File: (file: src/webpack:/vois-mgov/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: SDK_VERSION(file:///data/data/org.vois.international.mgov/files/app/vendor.js:43044:60)
System.err: 	at getFileAccess(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/file-system/index.js:11:32)
System.err: 	at (file: src/webpack:/vois-mgov/node_modules/@nativescript/core/file-system/index.js:623:0)
System.err: 	at ./node_modules/@nativescript/core/file-system/index.js(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/file-system/index.js:624:1)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/utils/debug.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:42970:70)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/utils/index.android.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:43084:64)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/accessibility/accessibility-service.android.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:2300:64)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/accessibility/accessibility-css-helper.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:2009:80)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/application/index.android.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:3862:97)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/platform/index.android.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:12983:70)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/http/http-request/index.android.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:10498:67)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./node_modules/@nativescript/core/xhr/index.js(file:///data/data/org.vois.international.mgov/files/app/vendor.js:44013:63)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at (file: src/webpack:/vois-mgov/node_modules/@nativescript/core/globals/index.js:263:43)
System.err: 	at loadModule(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/globals/index.js:202:0)
System.err: 	at get(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/globals/index.js:8:28)
System.err: 	at (file: src/webpack:/vois-mgov/node_modules/@nativescript/core/fetch/index.js:12:0)
System.err: 	at (file: src/webpack:/vois-mgov/node_modules/@nativescript/core/fetch/index.js:17:13)
System.err: 	at ./node_modules/@nativescript/core/fetch/index.js(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/fetch/index.js:539:1)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at (file: src/webpack:/vois-mgov/node_modules/@nativescript/core/globals/index.js:265:45)
System.err: 	at loadModule(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/globals/index.js:202:0)
System.err: 	at get(file: src/webpack:/vois-mgov/node_modules/@nativescript/core/globals/index.js:8:28)
System.err: 	at patchMethod(file: src/webpack:/vois-mgov/node_modules/zone.js/fesm2015/zone.js:966:0)
System.err: 	at (file: src/webpack:/vois-mgov/node_modules/zone.js/fesm2015/zone.js:1531:0)
System.err: 	at __load_patch(file: src/webpack:/vois-mgov/node_modules/zone.js/fesm2015/zone.js:91:0)
System.err: 	at ./node_modules/zone.js/fesm2015/zone.js(file: src/webpack:/vois-mgov/node_modules/zone.js/fesm2015/zone.js:1041:0)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at fn(file: src/webpack:/vois-mgov/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./src/polyfills.ts(file:///data/data/org.vois.international.mgov/files/app/bundle.js:4457:65)
System.err: 	at __webpack_require__(file: src/webpack:/vois-mgov/webpack/bootstrap:24:0)
System.err: 	at __webpack_exec__(file:///data/data/org.vois.international.mgov/files/app/bundle.js:4846:39)
System.err: 	at (file:///data/data/org.vois.international.mgov/files/app/bundle.js:4847:71)
System.err: 	at __webpack_require__.X(file: src/webpack:/vois-mgov/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/org.vois.international.mgov/files/app/bundle.js:4847:47)
System.err: 	at (file:///data/data/org.vois.international.mgov/files/app/bundle.js:4852:3)
System.err: 	at require(:1:266)
System.err: 

```

**Comment by rigor789** [comment]
> @rigor789 If I move the file outside the app/src folder. I get the following error on app start:

Is this with latest core? (8.4.1)

**Comment by abdallahkadour** [comment]
@rigor789 with 8.2.2. I will update to 8.4.1 and try

**Comment by abdallahkadour** [comment]
@rigor789 There is no version `8.4.1`, I tried with `8.4.0` and it didn't work.

**Comment by abdallahkadour** [comment]
In webpack.config.js I have 
```js
  nsWebpack.chainWebpack((config) => {
    if (nsWebpack.Utils.platform.getPlatformName() === 'android') {
      // make sure the path to the application.android.(js|ts)
      // is relative to the webpack.config.js
      // you may need to use `./app/application.android if
      // your app source is located inside the ./app folder.
      config.entry('application').add('./application.android')
    }
    config.plugin('polyfills').use(NodePolyfillPlugin)
    config.plugin('DefinePlugin').tap((args) => {
      Object.assign(args[0], { 'process.env': JSON.stringify(dotEnv) })
      return args
    })
  })

and added the file application.android.ts outside the src folder relative `webpack.config.js`.

```

**Comment by rigor789** [comment]
> @rigor789 There is no version `8.4.1`, I tried with `8.4.0` and it didn't work.

Are you looking at the right place? `@nativescript/core` has 8.4.1 released, which I believe should fix that issue (https://github.com/NativeScript/NativeScript/commit/82d60ae057f0f14718c1065f51bf3edbf36ad96a)

![image](https://user-images.githubusercontent.com/879060/205080725-ad49fa48-efc7-402d-80bf-bba40022993c.png)

**Comment by abdallahkadour** [comment]
@rigor789 I looked at the [releases](https://github.com/NativeScript/NativeScript/releases) After I got an npm error. It seems our nexus server doest not have this version. I should wait until tomorrow...

**Comment by abdallahkadour** [comment]
@rigor789 It works, thank you for your support.
