### ISSUE TITLE
Unable to create project - template not found

### ISSUE THREAD

**Issue by ccpplinux** [NativeScript/NativeScript#9635]
### Issue Description

When I am creating a new project then I am getting following error message:

https://packagecloud.io/github/git-lfs/npm/@nativescript/template-hello-world/-/template-hello-world-8.1.0.tgz

What could be the reason for this? Please help.

### Reproduction

[ccpplinux@ccpplinux NativeScript]$ ns create hello_ns

# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)

✔ First, which style of NativeScript project would you like to use: › Plain JavaScript

✔ Next, which template would you like to start from: › Hello World
404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/@nativescript/template-hello-world/-/template-hello-world-8.1.0.tgz
[ccpplinux@ccpplinux NativeScript]$ 

### Relevant log output (if applicable)

```shell
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--yes',
0 verbose cli   '--',
0 verbose cli   'nativescript-envinfo'
0 verbose cli ]
1 info using npm@8.1.1
2 info using node@v16.11.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/ccpplinux/Nextcloud/NativeScript/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/ccpplinux/.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 17ms
19 timing npm:load:configload Completed in 17ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 4ms
23 timing npm:load:cleanupLog Completed in 3ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 26ms
27 http fetch GET 200 https://registry.npmjs.org/nativescript-envinfo 2875ms (cache miss)
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing idealTree:init Completed in 5ms
32 timing idealTree:userRequests Completed in 2ms
33 silly idealTree buildDeps
34 silly fetch manifest nativescript-envinfo@*
35 http fetch GET 200 https://registry.npmjs.org/nativescript-envinfo 412ms (cache hit)
36 silly placeDep ROOT nativescript-envinfo@1.0.9 OK for:  want: *
37 silly fetch manifest @types/envinfo@^7.8.1
38 silly fetch manifest envinfo@^7.8.1
39 http fetch GET 200 https://registry.npmjs.org/@types%2fenvinfo 446ms (cache miss)
40 http fetch GET 200 https://registry.npmjs.org/envinfo 1087ms (cache miss)
41 timing idealTree:#root Completed in 1512ms
42 silly placeDep ROOT @types/envinfo@7.8.1 OK for: nativescript-envinfo@1.0.9 want: ^7.8.1
43 silly placeDep ROOT envinfo@7.8.1 OK for: nativescript-envinfo@1.0.9 want: ^7.8.1
44 timing idealTree:node_modules/nativescript-envinfo Completed in 7ms
45 timing idealTree:node_modules/@types/envinfo Completed in 0ms
46 timing idealTree:node_modules/envinfo Completed in 0ms
47 timing idealTree:buildDeps Completed in 1522ms
48 timing idealTree:fixDepFlags Completed in 1ms
49 timing idealTree Completed in 1531ms
50 timing reify:loadTrees Completed in 1532ms
51 timing reify:diffTrees Completed in 1ms
52 silly reify moves {}
53 timing reify:retireShallow Completed in 0ms
54 timing reify:createSparse Completed in 4ms
55 timing reify:loadBundles Completed in 0ms
56 silly audit bulk request {
56 silly audit   'nativescript-envinfo': [ '1.0.9' ],
56 silly audit   '@types/envinfo': [ '7.8.1' ],
56 silly audit   envinfo: [ '7.8.1' ]
56 silly audit }
57 silly tarball no local data for @types/envinfo@https://packagecloud.io/github/git-lfs/npm/@types/envinfo/-/envinfo-7.8.1.tgz. Extracting by manifest.
58 silly tarball no local data for envinfo@https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz. Extracting by manifest.
59 silly tarball no local data for nativescript-envinfo@https://packagecloud.io/github/git-lfs/npm/nativescript-envinfo/-/nativescript-envinfo-1.0.9.tgz. Extracting by manifest.
60 http fetch POST 404 https://packagecloud.io/github/git-lfs/npm/-/npm/v1/security/advisories/bulk 286ms
61 silly audit bulk request failed <!DOCTYPE html>
61 silly audit <html>
61 silly audit <head>
61 silly audit   <title>The page you were looking for doesn't exist (404)</title>
61 silly audit   <style>
61 silly audit   body {
61 silly audit     background-color: #EFEFEF;
61 silly audit     color: #2E2F30;
61 silly audit     text-align: center;
61 silly audit     font-family: arial, sans-serif;
61 silly audit   }
61 silly audit
61 silly audit   div.dialog {
61 silly audit     width: 25em;
61 silly audit     margin: 4em auto 0 auto;
61 silly audit     border: 1px solid #CCC;
61 silly audit     border-right-color: #999;
61 silly audit     border-left-color: #999;
61 silly audit     border-bottom-color: #BBB;
61 silly audit     border-top: #B00100 solid 4px;
61 silly audit     border-top-left-radius: 9px;
61 silly audit     border-top-right-radius: 9px;
61 silly audit     background-color: white;
61 silly audit     padding: 7px 4em 0 4em;
61 silly audit   }
61 silly audit
61 silly audit   h1 {
61 silly audit     font-size: 100%;
61 silly audit     color: #730E15;
61 silly audit     line-height: 1.5em;
61 silly audit   }
61 silly audit
61 silly audit   body > p {
61 silly audit     width: 33em;
61 silly audit     margin: 0 auto 1em;
61 silly audit     padding: 1em 0;
61 silly audit     background-color: #F7F7F7;
61 silly audit     border: 1px solid #CCC;
61 silly audit     border-right-color: #999;
61 silly audit     border-bottom-color: #999;
61 silly audit     border-bottom-left-radius: 4px;
61 silly audit     border-bottom-right-radius: 4px;
61 silly audit     border-top-color: #DADADA;
61 silly audit     color: #666;
61 silly audit     box-shadow:0 3px 8px rgba(50, 50, 50, 0.17);
61 silly audit   }
61 silly audit   </style>
61 silly audit </head>
61 silly audit
61 silly audit <body>
61 silly audit   <!-- This file lives in public/404.html -->
61 silly audit   <div class="dialog">
61 silly audit     <h1>The page you were looking for doesn't exist.</h1>
61 silly audit     <p>You may have mistyped the address or the page may have moved.</p>
61 silly audit   </div>
61 silly audit   <p>If you are the application owner check the logs for more information.</p>
61 silly audit </body>
61 silly audit </html>
62 http fetch GET 404 https://packagecloud.io/github/git-lfs/npm/@types/envinfo/-/envinfo-7.8.1.tgz 320ms (cache skip)
63 http fetch POST 404 https://packagecloud.io/github/git-lfs/npm/-/npm/v1/security/audits/quick 320ms
64 verbose audit error HttpErrorGeneral: 404 Not Found - POST https://packagecloud.io/github/git-lfs/npm/-/npm/v1/security/audits/quick
64 verbose audit error     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
64 verbose audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
64 verbose audit error     at async Map.[getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:337:21)
64 verbose audit error     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:107:19)
64 verbose audit error  HttpErrorGeneral: 404 Not Found - POST https://packagecloud.io/github/git-lfs/npm/-/npm/v1/security/audits/quick
64 verbose audit error     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
64 verbose audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
64 verbose audit error     at async Map.[getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:337:21)
64 verbose audit error     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:107:19) {
64 verbose audit error   headers: [Object: null prototype] {
64 verbose audit error     date: [ 'Tue, 02 Nov 2021 17:23:01 GMT' ],
64 verbose audit error     'content-type': [ 'text/html' ],
64 verbose audit error     'content-length': [ '146' ],
64 verbose audit error     connection: [ 'keep-alive' ],
64 verbose audit error     server: [ 'nginx' ],
64 verbose audit error     'x-fetch-attempts': [ '1' ]
64 verbose audit error   },
64 verbose audit error   statusCode: 404,
64 verbose audit error   code: 'E404',
64 verbose audit error   method: 'POST',
64 verbose audit error   uri: 'https://packagecloud.io/github/git-lfs/npm/-/npm/v1/security/audits/quick',
64 verbose audit error   body: <Buffer 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e 0d ... 96 more bytes>,
64 verbose audit error   pkgid: 'quick'
64 verbose audit error }
65 silly audit error <html>
65 silly audit error <head><title>404 Not Found</title></head>
65 silly audit error <body>
65 silly audit error <center><h1>404 Not Found</h1></center>
65 silly audit error <hr><center>nginx</center>
65 silly audit error </body>
65 silly audit error </html>
66 timing auditReport:getReport Completed in 623ms
67 silly audit report null
68 timing reify:audit Completed in 624ms
69 http fetch GET 404 https://packagecloud.io/github/git-lfs/npm/nativescript-envinfo/-/nativescript-envinfo-1.0.9.tgz 1259ms (cache skip)
70 http fetch GET 404 https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz 1265ms (cache skip)
71 timing reify:rollback:createSparse Completed in 6ms
72 timing reify:rollback:retireShallow Completed in 0ms
73 timing command:exec Completed in 5743ms
74 verbose stack HttpErrorGeneral: 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz
74 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
74 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
75 verbose statusCode 404
76 verbose pkgid envinfo@https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz
77 verbose cwd /home/ccpplinux/Nextcloud/NativeScript
78 verbose Linux 5.10.70-1-MANJARO
79 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "exec" "--yes" "--" "nativescript-envinfo"
80 verbose node v16.11.0
81 verbose npm  v8.1.1
82 error code E404
83 error 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz
84 error 404
85 error 404 'envinfo@https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz' is not in this registry.
86 error 404 You should bug the author to publish it (or use the name yourself!)
87 error 404 Note that you can also install from a
88 error 404 tarball, folder, http url, or git url.
89 verbose exit 1
```

### Environment

npm ERR! code E404
npm ERR! 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz
npm ERR! 404 
npm ERR! 404  'envinfo@https://packagecloud.io/github/git-lfs/npm/envinfo/-/envinfo-7.8.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ccpplinux/.npm/_logs/2021-11-02T17_23_02_349Z-debug.log

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by ccpplinux** [comment]
As suggested by rigor789#4046 on discord when I commented the packagecloud registry from the file /home/ccpplinux/.npmrc then it started working. Now I am able to create project.
