### ISSUE TITLE
Nativescrip Crash in new install with Vuex

### ISSUE THREAD

**Issue by gbelot2003** [NativeScript/NativeScript#9660]
### Issue Description

This happens on a new install of Nativescrip Vue from "ns create app --vue", once install the Vuex and created the store.
When imported the store, the system crash. It seems a problem with webpack, but I have no idea what could if be.
Once you remove the store import, the system works again.
I try to downgrade the vuex to 3.3.0 but the problem persist.

### Reproduction

steps
- ns create app --vue
- npm i
- npm i vuex@next --save
- create store
- ns run android

app.js
```
import Vue from 'nativescript-vue'

import Home from './components/Home'

import store from './store/store';

new Vue({
  store:store,
  render: (h) => h('frame', [h(Home)])
}).$start()
```
store.js
```import Vue from 'nativescript-vue';
import Vuex from 'vuex';

Vue.use(Vuex);

const store = new Vuex.Store({
  state: {
          engines: 50,
          weapons: 50
  },
  mutations: {
      increaseEngines(state) {
          if (state.engines < 100) {
              state.engines++;
              state.weapons--;
          }
      },
      decreaseEngines(state) {
          if (state.engines > 0) {
              state.engines--;
              state.weapons++;
          }
      },
      increaseWeapons(state) {
          if (state.weapons < 100) {
              state.weapons++;
              state.engines--;
          }
      },
      decreaseWeapons(state) {
          if (state.weapons > 0) {
              state.weapons--;
              state.engines++;
          }
      }
  }
});

module.exports = store;
```

### Relevant log output (if applicable)

```shell
Successfully synced application org.nativescript.client on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app/store/store.js
System.err: File: (file: app/webpack:/client/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: set(file: app/webpack:/client/webpack/runtime/harmony module decorator:7:0)
System.err: 	at ./app/store/store.js(file: app/webpack:/client/app/store/store.js:39:0)
System.err: 	at __webpack_require__(file: app/webpack:/client/webpack/bootstrap:24:0)
System.err: 	at fn(file: app/webpack:/client/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./app/app.js(file:///data/data/org.nativescript.client/files/app/bundle.js:16:70)
System.err: 	at __webpack_require__(file: app/webpack:/client/webpack/bootstrap:24:0)
System.err: 	at __webpack_exec__(file:///data/data/org.nativescript.client/files/app/bundle.js:405:39)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:406:221)
System.err: 	at __webpack_require__.X(file: app/webpack:/client/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:406:47)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:411:3)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app/store/store.js
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app/store/store.js
System.err: File: (file: app/webpack:/client/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: set(file: app/webpack:/client/webpack/runtime/harmony module decorator:7:0)
System.err: 	at ./app/store/store.js(file: app/webpack:/client/app/store/store.js:39:0)
System.err: 	at __webpack_require__(file: app/webpack:/client/webpack/bootstrap:24:0)
System.err: 	at fn(file: app/webpack:/client/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./app/app.js(file:///data/data/org.nativescript.client/files/app/bundle.js:16:70)
System.err: 	at __webpack_require__(file: app/webpack:/client/webpack/bootstrap:24:0)
System.err: 	at __webpack_exec__(file:///data/data/org.nativescript.client/files/app/bundle.js:405:39)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:406:221)
System.err: 	at __webpack_require__.X(file: app/webpack:/client/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:406:47)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:411:3)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app/store/store.js
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app/store/store.js
System.err: File: (file: app/webpack:/client/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: set(file: app/webpack:/client/webpack/runtime/harmony module decorator:7:0)
System.err: 	at ./app/store/store.js(file: app/webpack:/client/app/store/store.js:39:0)
System.err: 	at __webpack_require__(file: app/webpack:/client/webpack/bootstrap:24:0)
System.err: 	at fn(file: app/webpack:/client/webpack/runtime/hot module replacement:61:0)
System.err: 	at ./app/app.js(file:///data/data/org.nativescript.client/files/app/bundle.js:16:70)
System.err: 	at __webpack_require__(file: app/webpack:/client/webpack/bootstrap:24:0)
System.err: 	at __webpack_exec__(file:///data/data/org.nativescript.client/files/app/bundle.js:405:39)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:406:221)
System.err: 	at __webpack_require__.X(file: app/webpack:/client/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:406:47)
System.err: 	at (file:///data/data/org.nativescript.client/files/app/bundle.js:411:3)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./app/store/store.js
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:689)
System.err: 	at com.tns.Runtime.run(Runtime.java:681)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)

```

### Environment

{
  "name": "client",
  "main": "app/app.js",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@nativescript/core": "~8.1.1",
    "@nativescript/theme": "~3.0.1",
    "nativescript-vue": "~2.9.0",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@nativescript/android": "8.1.1",
    "@nativescript/webpack": "~5.0.0",
    "nativescript-vue-template-compiler": "~2.9.0"
  }
}

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by vallemar** [comment]
try change this line `module.exports = store;` by  `export const store = new Vuex.Store(....`
Your error is `Error: ES Modules may not assign module.exports or exports.*`

The javascript ES modules do not use `module.export`, this is from node.js

**Comment by gbelot2003** [comment]
Thanks Vallemar, correct, that solve this part of the problem.
