### ISSUE TITLE
Android: conflict beetween Tabs and BottonNavigation causes app crash  (playground demo)

### ISSUE THREAD

**Issue by AedonStorm** [NativeScript/NativeScript#9662]
### Issue Description

I have a popup with Tabs and a BottomNavigation in same layer. The BottomNavigation has a frame on each item, as we can find in Nativescript documentation.
[https://v6.docs.nativescript.org/core-concepts/nested-navigation#nesting-forward-in-lateral-navigation](url)

Having Tabs and BottomNavigation in same layer causes app crash interacting with the BottomNavigation. I have created a simple project in Nativescript Playground to show the problem.

**Sample project**
[https://play.nativescript.org/?template=play-tsc&id=8t5W6u](url)

### Reproduction

1. Click on second item of the BottonNavigation

### Relevant log output (if applicable)

```shell
An uncaught Exception occurred on "main" thread.
No view found for id 0x4 (unknown) for fragment fragment2[2]<Page(23)@home/frame/frame-two.xml:1:1;>

StackTrace:
java.lang.IllegalArgumentException: No view found for id 0x4 (unknown) for fragment fragment2[2]<Page(23)@home/frame/frame-two.xml:1:1;>
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
at android.os.Handler.handleCallback(Handler.java:914)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:225)
at android.app.ActivityThread.main(ActivityThread.java:7563)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by edusperoni** [comment]
Tabs and BottomNavigation are no longer part of NativeScript core and now can be found on https://www.npmjs.com/package/@nativescript-community/ui-material-tabs and https://www.npmjs.com/package/@nativescript-community/ui-material-bottom-navigation.

The Playground still uses an old version of NativeScript and we're working on updating it to the latest version.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
