### ISSUE TITLE
Unable to connect to simulator or real device [Android]

### ISSUE THREAD

**Issue by TravJav** [NativeScript/NativeScript#9723]
### Issue Description

When I  run a simulator ( GemyMotion ) I receive an error as shown in the message section of this issue

When I  run on my android device  I receive an error as shown in the message section of this issue

I use the CLI like so "tns devices" which prints out my devices as expected; when they're connected.

When I run "tns run android" with the log trace I encounter this error that I cannot get past

### Reproduction

Ubuntu 20.* Host machine:

TNS version: 8.1.5

ANGULAR VERSION 12.

Node.js: v14.15

with an android device or GemyMotion personal use simulator run "tns run android" with the log trace activated and you will be met with this error

### Relevant log output (if applicable)

```shell
Error message:

Webpack compilation complete. Watching for file changes.
[WatchStatePlugin] Notify:  {
  type: 'compilation',
  version: 1,
  hash: 'f2a08a7758009c546757',
  data: { emittedAssets: [], staleAssets: [] }
}
Message from webpack {
  type: 'compilation',
  version: 1,
  hash: 'f2a08a7758009c546757',
  data: { emittedAssets: [], staleAssets: [] }
}
Received message from webpack process: {
  type: 'compilation',
  version: 1,
  hash: 'f2a08a7758009c546757',
  data: { emittedAssets: [], staleAssets: [] }
}
Webpack build done!

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1567)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Command ./gradlew failed with exit code 1
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Make sure you can access services.gradle.org in your browser. May be a temporary downtime or a firewall issue on your machine (or a dns cache issue).

**Comment by TravJav** [comment]
I dont know what it was, but it just stopped. I did a reboot and let it sit after running the run command with the simulator. Hung for a long time then rendered
