### ISSUE TITLE
TypeError: Cannot read property 'navigate' of undefined

### ISSUE THREAD

**Issue by lyenking** [NativeScript/NativeScript#9762]
### Issue Description

xml:
<Page loaded="pageLoaded" navigatingTo="onNavigatingTo">
    <StackLayout orientation="vertical">
        <Image src="~/images/apple.jpg" />
        <TextField hint="email address" keyboardType="email" autocorrect="false" autocapitalizationType="none" />
        <TextField hint="password" secure="true" />
        <Button class="bnt" text="sign in" tap="login" />
        <Button text="sign up for goes" tap="navigateToMainPage" />
    </StackLayout>

</Page>

js:
export function navigateToMainPage() {
  Frame.topmost().navigate({
    moduleName: "views/register/register",
    animated: false
  });
}

### Reproduction

tns run android --watch

### Relevant log output (if applicable)

```shell
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onClick failed
System.err: TypeError: Cannot read property 'navigate' of undefined
System.err:
System.err: StackTrace:
System.err: navigateToMainPage(file: app\webpack:\HelloWorld\app\views\login\login.js:8:15)
System.err:     at _handleEvent(file: app\webpack:\HelloWorld\node_modules\@nativescript\core\data\observable\index.js:233:0)
System.err:     at notify(file: app\webpack:\HelloWorld\node_modules\@nativescript\core\data\observable\index.js:216:0)
System.err:     at _emit(file: app\webpack:\HelloWorld\node_modules\@nativescript\core\data\observable\index.js:256:0)
System.err:     at ClickListenerImpl.onClick(file: app\webpack:\HelloWorld\node_modules\@nativescript\core\ui\button\index.android.js:28:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.java.lang.Object_vendor_16521_28_ClickListenerImpl.onClick(Object_vendor_16521_28_ClickListenerImpl.java:18)
System.err:     at android.view.View.performClick(View.java:7125)
System.err:     at android.view.View.performClickInternal(View.java:7102)
System.err:     at android.view.View.access$3500(View.java:801)
System.err:     at android.view.View$PerformClick.run(View.java:27336)
System.err:     at android.os.Handler.handleCallback(Handler.java:883)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Please include more code - where are you importing `Frame` from?
