### ISSUE TITLE
Slow Build times on MacBook Pro M1 32GB RAM

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#9796]
### Issue Description

After migrating my projects to a new MacBook Pro M1 my builds seem very slow. 

NS Doctor:-

✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 13.2.1 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.1.5 version and is up to date.
✔ Component @nativescript/core has 8.1.5 version and is up to date.
✔ Component @nativescript/ios has 8.1.0 version and is up to date.
✔ Component @nativescript/android has 8.1.1 version and is up to date.

My previous MacBook Pro was intel based with 16GB RAM and was much quicker building.
I've cleaned the project, updated plugins etc but build time are still slower.

### Environment

OS: macOS 12.2.1
CPU: (8) x64 Apple M1 Pro
Shell: /bin/zsh
node: 14.11.0
npm: 7.11.2
nativescript: 8.1.5

# android
java: 1.8.0_172
ndk: Not Found
apis: 25, 27, 28
build_tools: 25.0.2, 27.0.3, 28.0.3
system_images: 
  - android-28 | Google APIs Intel x86 Atom

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.2
python: 2.7.18
python3: 3.9.0
ruby: 2.6.8
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/gps": "^3.1.3",
  "@nativescript-community/ui-mapbox": "^6.2.14",
  "@nativescript/appavailability": "^2.0.0",
  "@nativescript/background-http": "^5.0.2",
  "@nativescript/camera": "^5.0.10",
  "@nativescript/core": "^8.1.5",
  "@nativescript/datetimepicker": "^2.1.9",
  "@nativescript/theme": "^3.0.2",
  "@proplugins/nativescript-drop-down": "^9.0.2",
  "@proplugins/nativescript-platform": "^1.4.15",
  "@triniwiz/nativescript-videorecorder": "^4.0.2",
  "nativescript": "^7.2.0",
  "nativescript-accelerometer": "^3.0.0",
  "nativescript-background-fetch": "^1.2.1",
  "nativescript-fresco": "^5.3.0",
  "nativescript-google-maps-sdk": "^3.0.2",
  "nativescript-intl": "^4.0.2",
  "nativescript-iqkeyboardmanager": "^1.5.1",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-theme-core": "^2.0.24",
  "nativescript-ui-dataform": "^8.0.1",
  "nativescript-ui-listview": "^10.0.2",
  "nativescript-videoplayer": "^5.0.1",
  "reflect-metadata": "0.1.13",
  "rxjs": "6.5.4",
  "rxjs-compat": "6.5.4",
  "zone.js": "0.10.2"
},
"devDependencies": {
  "@nativescript/android": "~8.1.1",
  "@nativescript/ios": "8.1.0",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "~5.0.0-beta.14",
  "typescript": "~4.0.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Everything 1st party in NativeScript works without rosetta, so definitely try native node and running without rosetta to see if that makes a difference.

**Comment by mrwrighty** [comment]
Updated Node and now have v17.6.0

Running ns doctor does not complete and stops at getting Nativescript components

No issues were detected.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 13.2.1 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...

ns doctor stops at the line above.

when entering ns --version this error occurs

8.1.5
⠼ Checking for updates...Error: Command failed: npm view nativescript  dist-tags --json
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../lib/cli.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
}

Node.js v17.6.0

    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:157:27)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:130:21)
    at NodePackageManager.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:104:30)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:12:65)
⠼ Checking for updates...%

**Comment by edusperoni** [comment]
@mrwrighty seems like you have an incomplete installation, as that error is coming straight from npm itself. Most likely you updated node and is still using different versions of npm or a dirty npm package folder (from the old installation). I suggest switching to nvm instead of using a global node installation to avoid these issues.

**Comment by mrwrighty** [comment]
Getting the same error whether I use Terminal with or without Rosetta.

Not sure how this manifested itself as I can no longer compile apps. Compilation stops at the last line of the error above: -

If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript or EsLint.

**Comment by msn444** [comment]
Did anyone figure this out? I'm seeing it all of a sudden.
