### ISSUE TITLE
Could not determine java version from '11.0.6'.

### ISSUE THREAD

**Issue by faisalansari20** [NativeScript/NativeScript#9815]
### Issue Description

Suddenly Android started to fail. with below error. Please help

### Relevant log output (if applicable)

```shell
nativescript-plugin-firebase: /Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/platforms/android/.pluginfirebaseinfo not found, forcing prepare!
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.6'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Failed to build plugin @nativescript/email : 
Error: Command ./gradlew failed with exit code 1
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
```
npm i -g nativescript@next # <- we'll be releasing this soon, but this has updated gradle
npm i --save-dev @nativescript/android@latest # <- should install 8.2.0 with updated gradle as well
ns clean && ns run android
```

The above should work - though you may see 2 errors after upgrading:
- Error related to `android:exported` not being set. In `App_Resources/Android/src/main/AndroidManifest.xml` make sure you add `android:exported="true"` to the `<activity>` tag.
- Error related to `compile` - gradle removed `compile` as it's been deprecated for a while, but some plugins in your project may still be using `compile` instead of `implementation`. Check if those plugins have updates published already, or an alternative version - if not, the plugin will need to be updated to work with gradle 7.

**Comment by faisalansari20** [comment]
that worked thanks alot for the quick response @rigor789 smile

**Comment by Woongsik** [comment]
Hi, the workaround is not worked for me.
The issue is coming from "@nativescript-community/ui-pulltorefresh": "^2.5.0", and still required to use JAVA 11.

```
Where:
Build file '/platforms/tempPlugin/ui_pulltorefresh/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'ui_pulltorefresh'.
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

Could you give me some idea to make it work?

**Comment by rigor789** [comment]
@Woongsik that's a different issue - you need to install java 11 for 8.2 and gradle7.

On a mac you can do
```bash
brew tap homebrew/cask-versions
brew install --cask temurin11
```
As well as this in your `.bash_profile`, `.zshrc` or whatever your shell reads from:
```bash
export JAVA_HOME=$(/usr/libexec/java_home -v"11");
```

On windows it would be something like:

```bash
choco install -y temurin11
```
And then set `JAVA_HOME` in env variables... But it depends how you set up your system - you might not have choco etc.

**Comment by Woongsik** [comment]
@rigor789 Thanks for the reply. I tried to switch it to JAVA_HOME pointing to JAVA 11 instead of JAVA 1.8 
and now there is another one came,

```
 Gradle build...
         + applying user-defined configuration from /app/App_Resources/Android/before-plugins.gradle

FAILURE: Build failed with an exception.

* Where:
Script 'app/App_Resources/Android/before-plugins.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Could not find method android() for arguments [before_plugins_6wzlwok1oqpuourvrpuq3s9ya$_run_closure1@439365a0] on root project 'some_project_name' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 601ms
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
```

I am using "@nativescript/android": "^8.2.2" like you mention above.
Could you check it out, at least workaround ??

**Comment by rigor789** [comment]
@Woongsik if you have `android {}` in your `before-plugins.gradle` in App_Resources, remove it... Do share what you have in that file though, since some things you may still need from there.

**Comment by stefalda** [comment]
Hi, 
I've got a similar problem on macOS M1 and after installing temurin11 I got, now I have a new problem:

```
webpack 5.70.0 compiled successfully in 1991 ms
Webpack compilation complete.
(node:2393) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/ste/Developer/prova/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Failed to build plugin @nativescript/core : 
Error: spawn ./gradlew ENOENT
ste@Stefanos-MacBook-Pro prova % Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input/output error
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Input/output error
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
        ... 1 more
         ~ applying user-defined configuration from /Users/ste/Developer/prova/App_Resources/Android/before-plugins.gradle
```

`before-plugins.gradle` hasn't any `android{}`

Just created a new app with NS 8.2 and then tried the android build:

`ns build android`

Thanks

**Comment by ShimonKh** [comment]
> @Woongsik if you have `android {}` in your `before-plugins.gradle` in App_Resources, remove it... Do share what you have in that file though, since some things you may still need from there.

I need to use googlePlayServicesVersion. It added to before-plugins.gradle   `android {
  project.ext {
      googlePlayServicesVersion = "15.0.1"
  }
}`
If I remove `android {}` in my `before-plugins.gradle`, how I can add googlePlayServicesVersion to project?

**Comment by rigor789** [comment]
@ShimonKh You would do something like: 

```groovy
project.ext { 
  googlePlayServicesVersion = "15.0.1"
}
```
without the wrapping `android {}`.

**Comment by mpcref** [comment]
@stefalda I had the same issue. This is going to sound very strange but.... you're probably using node that was installed by homebrew. There seems to be an issue with the way it handles spawned child processes. Try installing node using n. https://www.npmjs.com/package/n
Make sure its path has highest prio in your PATH env var by checking `which node`.

**Comment by stefalda** [comment]
Thank you @mpcref, it worked! 👍

**Comment by vickyATD** [comment]
i've tried the before-plugin file approacha and after this got this error
"Could not initialize class com.android.repository.impl.generated.v2.ArchiveType"

**Comment by objczl** [comment]
> i've tried the before-plugin file approach and after this ,i got below error
> 
> Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input/output error at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62) at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41) at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127) at java.base/java.lang.Thread.run(Thread.java:835) Caused by: java.io.IOException: Input/output error at java.base/java.io.FileInputStream.readBytes(Native Method) at java.base/java.io.FileInputStream.read(FileInputStream.java:273) at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290) at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351) at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98) ... 1 more ~ applying user-defined configuration from /Users/vickykumar/Desktop/projects/atd-mobile-apps/ATD/App_Resources/Android/before-plugins.gradle
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not initialize class com.android.repository.impl.generated.v2.ArchiveType
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

Hi, I have the same issue  ` Could not initialize class com.android.repository.impl.generated.v2.ArchiveType`, I fix it by using different jdk

```
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Homebrew (build 11.0.17+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.17+0, mixed mode)
```
