### ISSUE TITLE
App crash only release mode

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#9829]
### Issue Description

Hi,

After updating my project to the latest version, the app gives an error in release mode, but I'm not finding it exactly why. In development mode ``ns run android`` it works fine, but when I install via APK in release mode or ``ns run android --release`` the error occurs. Any idea what it could be or how I go about finding the error?

### Reproduction

My release command:

```
tns run android --release  --bundle \
  --key-store-path /certificados/cert.keystore \
  --key-store-password pass \
  --key-store-alias alias \
  --key-store-alias-password pass
```

### Relevant log output (if applicable)

```shell
03-17 11:09:57.160  2556  9737 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=br.com.mobloja.redeinovast/com.tns.NativeScriptActivity bnds=[540,712][789,978]} from uid 10045
03-17 11:09:57.182  2556  9130 I ActivityManager: Start proc 31747:br.com.mobloja.redeinovast/u0a680 for activity br.com.mobloja.redeinovast/com.tns.NativeScriptActivity
03-17 11:09:57.242 31747 31747 W ComponentDiscovery: Class com.google.firebase.dynamicloading.DynamicLoadingRegistrar is not an found.
03-17 11:09:57.260 31747 31747 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
03-17 11:09:57.272 28985 28985 I GsaVoiceInteractionSrv: Handling ACTION_STOP_HOTWORD
03-17 11:09:57.274 28985 29059 E HwDetectorWithState: a: 3
03-17 11:09:57.294 31747 31747 I FirebaseInitProvider: FirebaseApp initialization successful
03-17 11:09:57.319 31747 31747 W com.facebook.UserSettingsManager: Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
03-17 11:09:57.319 31747 31747 W com.facebook.UserSettingsManager: You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
03-17 11:09:57.339 31747 31774 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-17 11:09:57.356 31747 31782 W com.facebook.internal.NativeProtocol: Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.
03-17 11:09:57.404 31747 31747 I TNS.Runtime: NativeScript Runtime Version 8.2.1, commit no commit sha was provided by build.gradle build
03-17 11:09:57.438 31747 31747 D TNS.Runtime: V8 version 8.3.110.9
03-17 11:09:57.713   810   810 I SFPerfTracer:      triggers: (rate: 224:11457) (compose: 0:6) (post: 0:18) (render: 0:33) (21:340273 frames) (22:398321)
03-17 11:09:57.713   810   810 D SFPerfTracer:        layers: (5:8) (NavigationBar#0 (0xac71a000): 0:19649) (StatusBar#0 (0xac71c000): 1:49805) (com.android.systemui.ImageWallpaper#0 (0xac7ea000): 0:765) (DimLayerController/Stack=0#0 (0xac75b000): 0:3026)* (Sprite#0 (0xac7fb000): 0:16)* (com.android.launcher3/com.android.launcher3.CustomizationPanelLauncher#0 (0xac756000): 0:4)* (com.android.launcher3/com.android.launcher3.CustomizationPanelLauncher#1 (0xac759000): 2:93) (Splash Screen br.com.mobloja.redeinovast#0 (0xac703000): 22:24) 
03-17 11:09:59.408 31747 31747 D AndroidRuntime: Shutting down VM
03-17 11:09:59.409 31747 31747 E AndroidRuntime: FATAL EXCEPTION: main
03-17 11:09:59.409 31747 31747 E AndroidRuntime: Process: br.com.mobloja.redeinovast, PID: 31747
03-17 11:09:59.409 31747 31747 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: TypeError: Cannot read property 'widget' of undefined
03-17 11:09:59.409 31747 31747 E AndroidRuntime: File: (file:///data/data/br.com.mobloja.redeinovast/files/app/vendor.js:2:1065827)
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: StackTrace: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 3786(file:///data/data/br.com.mobloja.redeinovast/files/app/vendor.js:2:1065828)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:212)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at 1926(file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:936793)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:212)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at 7978(file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:39695)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:212)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_exec__(file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1023876)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at (file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1023951)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__.X(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:1286)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at (file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1023889)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at (file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1024116)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at require(:1:266)
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: TypeError: Cannot read property 'widget' of undefined
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6626)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
03-17 11:09:59.409 31747 31747 E AndroidRuntime: Caused by: com.tns.NativeScriptException: Error calling module function 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: TypeError: Cannot read property 'widget' of undefined
03-17 11:09:59.409 31747 31747 E AndroidRuntime: File: (file:///data/data/br.com.mobloja.redeinovast/files/app/vendor.js:2:1065827)
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: StackTrace: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 3786(file:///data/data/br.com.mobloja.redeinovast/files/app/vendor.js:2:1065828)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:212)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at 1926(file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:936793)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:212)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at 7978(file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:39695)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:212)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_exec__(file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1023876)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at (file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1023951)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at __webpack_require__.X(file:///data/data/br.com.mobloja.redeinovast/files/app/runtime.js:1:1286)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at (file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1023889)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at (file:///data/data/br.com.mobloja.redeinovast/files/app/bundle.js:1:1024116)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at require(:1:266)
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: 
03-17 11:09:59.409 31747 31747 E AndroidRuntime: TypeError: Cannot read property 'widget' of undefined
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at com.tns.Runtime.runModule(Native Method)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at com.tns.Runtime.runModule(Runtime.java:689)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at com.tns.Runtime.run(Runtime.java:681)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1141)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5854)
03-17 11:09:59.409 31747 31747 E AndroidRuntime:        ... 8 more
03-17 11:09:59.417  2556  8486 W ActivityManager:   Force finishing activity br.com.mobloja.redeinovast/com.tns.NativeScriptActivity
03-17 11:09:59.422  2556  2619 I ActivityManager: Showing crash dialog for package br.com.mobloja.redeinovast u0
03-17 11:09:59.423  2556  2618 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
03-17 11:09:59.423  2556  2618 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
03-17 11:09:59.446   810  1017 I SFPerfTracer:      triggers: (rate: 0:0) (24955 sw vsyncs) (0 skipped) (109:342277 vsyncs) (111:424921)
03-17 11:09:59.566   810   810 I SFPerfTracer:      triggers: (rate: 224:11457) (compose: 0:6) (post: 0:18) (render: 0:33) (1:340367 frames) (2:398421)
03-17 11:09:59.566   810   810 D SFPerfTracer:        layers: (3:9) (NavigationBar#0 (0xac71a000): 0:19740) (StatusBar#0 (0xac71c000): 0:49806) (com.android.systemui.ImageWallpaper#0 (0xac7ea000): 0:766)* (DimLayerController/Stack=0#0 (0xac75b000): 0:3026)* (Sprite#0 (0xac7fb000): 0:16)* (com.android.launcher3/com.android.launcher3.CustomizationPanelLauncher#0 (0xac756000): 0:5)* (com.android.launcher3/com.android.launcher3.CustomizationPanelLauncher#1 (0xac759000): 0:94)* (Splash Screen br.com.mobloja.redeinovast#0 (0xac703000): 0:26)* (Application Error: br.com.mobloja.redeinovast#0 (0xac38e000): 2:6) 
03-17 11:09:59.919  2556  2618 W ActivityManager: Activity pause timeout for ActivityRecord{240d47d u0 br.com.mobloja.redeinovast/com.tns.NativeScriptActivity t215 f}
03-17 11:09:59.935  2556  2618 I ActivityManager: moveHomeStack, setupComplete:true
03-17 11:10:00.014  4015  4015 D Launcher.Utilities: Wakeup weather: Intent { act=com.motorola.launcher3.action.WAKEUP_WEATHER cmp=com.motorola.timeweatherwidget/com.motorola.commandcenter.weather.WakeUpService }

```
```


### Environment

```yaml
OS: Linux 5.15 Debian GNU/Linux 10 (buster) 10 (buster)
CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
Shell: /bin/bash
node: 15.14.0
npm: 7.7.6
nativescript: 8.2.2

# android
java: 11.0.14.1
ndk: Not Found
apis: 28, 29, 30, 31, 32
build_tools: 28.0.3, 29.0.1, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
system_images: 
  - android-23 | Google APIs Intel x86 Atom
  - android-28 | Google Play Intel x86 Atom
  - android-29 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google Play Intel x86 Atom
  - android-32 | Google APIs Intel x86 Atom_64
  - android-32 | Google Play Intel x86 Atom_64

# ios
xcode: Not Found
cocoapods: Not Found
python: 2.7.16
python3: 3.7.3
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-collectionview": "4.0.48",
  "@nativescript-community/ui-drawer": "^0.0.33",
  "@nativescript/core": "~8.2.1",
  "@nativescript/geolocation": "8.0.2",
  "@nativescript/theme": "~3.0.1",
  "moment-mini": "^2.24.0",
  "nativescript-alarm": "https://github.com/mobilemindtec/nativescript-alarm.git",
  "nativescript-apple-sign-in": "^2.0.0",
  "nativescript-appversion": "1.4.4",
  "nativescript-background-task": "https://github.com/mobilemindtec/nativescript-background-task.git",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-db-orm": "https://github.com/mobilemindtec/nativescript-db-orm.git",
  "nativescript-device-uuid": "https://github.com/mobilemindtec/nativescript-device-uuid.git",
  "nativescript-extra-call": "https://github.com/mobilemindtec/nativescript-extra-call.git",
  "nativescript-facebook": "https://github.com/mobilemindtec/nativescript-facebook.git",
  "nativescript-fonticon": "https://github.com/mobilemindtec/nativescript-fonticon.git",
  "nativescript-google": "https://github.com/mobilemindtec/nativescript-google.git",
  "nativescript-google-maps-sdk": "https://github.com/mobilemindtec/nativescript-google-maps-sdk.git",
  "nativescript-iqkeyboardmanager": "https://github.com/mobilemindtec/nativescript-iqkeyboardmanager.git",
  "nativescript-masked-text-field": "https://github.com/mobilemindtec/nativescript-masked-text-field/releases/download/1.0.3/nativescript-masked-text-field-1.0.3.tgz",
  "nativescript-message-bar-manager": "https://github.com/mobilemindtec/nativescript-message-bar-manager.git",
  "nativescript-mobilemind": "https://github.com/mobilemindtec/nativescript-mobilemind.git",
  "nativescript-network-checker": "https://github.com/mobilemindtec/nativescript-network-checker.git",
  "nativescript-permissions": "1.3.12",
  "nativescript-push-notifications": "https://github.com/mobilemindtec/push-plugin.git",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-ui-listview": "10.0.2",
  "nativescript-ui-sidedrawer": "10.0.2",
  "nativescript-view-util": "https://github.com/mobilemindtec/nativescript-view-util.git",
  "nativescript-vue": "~2.9.1",
  "nativescript-websockets": "^2.0.0",
  "typescript": "^4.5.2",
  "vuex": "^2.2.0"
},
"devDependencies": {
  "@babel/core": "~7.1.0",
  "@babel/preset-env": "~7.1.0",
  "@nativescript/android": "~8.2.2",
  "@nativescript/ios": "~8.2.1",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.0",
  "babel-loader": "~8.0.0",
  "coffee-loader": "^2.0.0",
  "coffeescript": "^2.5.1",
  "nativescript-vue-template-compiler": "~2.9.0",
  "sass": "~1.39.0",
  "vue-cli-plugin-coffee": "^1.0.0",
  "vue-loader": "~15.9.6"
}
```

```
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.2.2 version and is up to date.
✔ Component @nativescript/core has 8.2.1 version and is up to date.
✔ Component @nativescript/ios has 8.2.1 version and is up to date.
✔ Component @nativescript/android has 8.2.2 version and is up to date.

```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
@mobilemindtec this is likely due to one of those plugins using an invalid androidx check - for example here is a plugin recently updated from a contributor which had invalid androidx check:
https://github.com/nstudio/nativescript-plugins/commit/a6dc932f7f700ed896afbdfeaa67d38fe1e44eb3
In that case `useAndroidX` was returning false causing this check:
```
const AppCompatCheckBox_Namespace = useAndroidX() ? androidx.appcompat.widget : (android.support as any).v7.widget;
```
to fallback to `android.support.v7` to be undefined leading to same error `TypeError: Cannot read property 'widget' of undefined` because `v7` was unavailable. In fact with 8.2 and SDK 32 targeted most android apps should be using androidx.

I don't notice that particular plugin in your package you shared but that hopefully provides a clue to go on as likely one of those plugins is doing something similar.

You can find it for sure which plugin it's coming from by building the app locally and then unpack the `.apk` file like this:
```
unzip /path/to/build.apk -d unzipped_apk
```
Then open the unzipped_apk folder in IDE and open the `vendor.js` in the app files and Ctrl+G (In VS Code for example) to go directly to the line,column the stack mentions by entering `2,1065827` and ENTER. That will go precisely to which one it is and you should be able to determine what plugin that is referenced in.

**Comment by mobilemindtec** [comment]
Hi,

Yes!! that's right, plugin update with problem and it worked a! Thank you!

**Comment by NathanWalker** [comment]
@mobilemindtec great to hear! when you get a chance, if don't mind sharing which one? we could probably help update the androidx check if it needs to be.

**Comment by mobilemindtec** [comment]
@NathanWalker,

is a plugin of its own, the code that was with error was this:

`const Snackbar_Namespace = useAndroidX() ? com.google.android.material.snackbar : android.support.design.widget`

It was declared at the top of the file, so I put it inside a method that only runs on android.

The complete code: 

https://github.com/mobilemindtec/nativescript-message-bar-manager/blob/master/index.js

**Comment by NathanWalker** [comment]
Excellent nice find 👌

**Comment by cristiandaulisio** [comment]
how can we fix it?
