### ISSUE TITLE
Release Android crashes app

### ISSUE THREAD

**Issue by Noppey** [NativeScript/NativeScript#9838]
### Issue Description

When running ns run android, everything works.
When running ns run android --release the app crashes on opening.

### Relevant log output (if applicable)

```shell
--------- beginning of main
03-17 14:15:32.439 24635 24635 E ht.meterinsigh: Not starting debugger since process cannot load the jdwp agent.
03-17 14:15:32.443 24635 24635 E USNET   : USNET: appName: com.meterinsight.meterinsight
03-17 14:15:32.444 24635 24635 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
03-17 14:15:32.449 24635 24635 D ActivityThread: setConscryptValidator
03-17 14:15:32.449 24635 24635 D ActivityThread: setConscryptValidator - put
--------- beginning of system
03-17 14:15:32.473 24635 24635 D ActivityThread: handleBindApplication()++ app=com.meterinsight.meterinsight
03-17 14:15:32.474 24635 24635 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10464; state: ENABLED
03-17 14:15:32.481 24635 24635 W ht.meterinsigh: Entry not found
03-17 14:15:32.482 24635 24635 W ht.meterinsigh: Entry not found
03-17 14:15:32.482 24635 24635 W ht.meterinsigh: Entry not found
03-17 14:15:32.487 24635 24635 W ht.meterinsigh: JIT profile information will not be recorded: profile file does not exist.
03-17 14:15:32.487 24635 24635 W ht.meterinsigh: JIT profile information will not be recorded: profile file does not exist.
03-17 14:15:32.487 24635 24635 W ht.meterinsigh: JIT profile information will not be recorded: profile file does not exist.
03-17 14:15:32.499 24635 24635 V GraphicsEnvironment: ANGLE Developer option for 'com.meterinsight.meterinsight' set to: 'default'
03-17 14:15:32.499 24635 24635 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
03-17 14:15:32.502 24635 24635 D LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=com.meterinsight.meterinsight appContext.mBasePackageName=com.meterinsight.meterinsight
03-17 14:15:32.503 24635 24635 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-17 14:15:32.504 24635 24635 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-17 14:15:32.514 24635 24635 D ActivityThread: handleBindApplication() --
03-17 14:15:32.520 24635 24635 I TNS.Runtime: NativeScript Runtime Version 8.2.1, commit no commit sha was provided by build.gradle build
03-17 14:15:32.528 24635 24635 D TNS.Runtime: V8 version 8.3.110.9
03-17 14:15:32.950 24635 24635 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-17 14:15:32.951 24635 24635 E AndroidRuntime: FATAL EXCEPTION: main
03-17 14:15:32.951 24635 24635 E AndroidRuntime: Process: com.meterinsight.meterinsight, PID: 24635
03-17 14:15:32.951 24635 24635 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime: File: (file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986783)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: StackTrace:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: 46384(file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986784)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at 6295(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:98578)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_exec__(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129960)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130037)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__.X(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:1167)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129973)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130204)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at require(:1:266)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7481)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.access$1700(ActivityThread.java:310)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8633)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
03-17 14:15:32.951 24635 24635 E AndroidRuntime: Caused by: com.tns.NativeScriptException: Error calling module function
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime: File: (file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986783)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: StackTrace:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: 46384(file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986784)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at 6295(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:98578)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_exec__(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129960)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130037)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__.X(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:1167)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129973)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130204)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at require(:1:266)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.Runtime.runModule(Native Method)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.Runtime.runModule(Runtime.java:689)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.Runtime.run(Runtime.java:681)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7476)--release

--------- beginning of main
03-17 14:15:32.439 24635 24635 E ht.meterinsigh: Not starting debugger since process cannot load the jdwp agent.
03-17 14:15:32.443 24635 24635 E USNET   : USNET: appName: com.meterinsight.meterinsight
03-17 14:15:32.444 24635 24635 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
03-17 14:15:32.449 24635 24635 D ActivityThread: setConscryptValidator
03-17 14:15:32.449 24635 24635 D ActivityThread: setConscryptValidator - put
--------- beginning of system
03-17 14:15:32.473 24635 24635 D ActivityThread: handleBindApplication()++ app=com.meterinsight.meterinsight
03-17 14:15:32.474 24635 24635 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10464; state: ENABLED
03-17 14:15:32.481 24635 24635 W ht.meterinsigh: Entry not found
03-17 14:15:32.482 24635 24635 W ht.meterinsigh: Entry not found
03-17 14:15:32.482 24635 24635 W ht.meterinsigh: Entry not found
03-17 14:15:32.487 24635 24635 W ht.meterinsigh: JIT profile information will not be recorded: profile file does not exist.
03-17 14:15:32.487 24635 24635 W ht.meterinsigh: JIT profile information will not be recorded: profile file does not exist.
03-17 14:15:32.487 24635 24635 W ht.meterinsigh: JIT profile information will not be recorded: profile file does not exist.
03-17 14:15:32.499 24635 24635 V GraphicsEnvironment: ANGLE Developer option for 'com.meterinsight.meterinsight' set to: 'default'
03-17 14:15:32.499 24635 24635 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
03-17 14:15:32.502 24635 24635 D LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=com.meterinsight.meterinsight appContext.mBasePackageName=com.meterinsight.meterinsight
03-17 14:15:32.503 24635 24635 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-17 14:15:32.504 24635 24635 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-17 14:15:32.514 24635 24635 D ActivityThread: handleBindApplication() --
03-17 14:15:32.520 24635 24635 I TNS.Runtime: NativeScript Runtime Version 8.2.1, commit no commit sha was provided by build.gradle build
03-17 14:15:32.528 24635 24635 D TNS.Runtime: V8 version 8.3.110.9
03-17 14:15:32.950 24635 24635 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-17 14:15:32.951 24635 24635 E AndroidRuntime: FATAL EXCEPTION: main
03-17 14:15:32.951 24635 24635 E AndroidRuntime: Process: com.meterinsight.meterinsight, PID: 24635
03-17 14:15:32.951 24635 24635 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime: File: (file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986783)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: StackTrace:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: 46384(file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986784)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at 6295(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:98578)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_exec__(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129960)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130037)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__.X(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:1167)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129973)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130204)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at require(:1:266)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7481)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.access$1700(ActivityThread.java:310)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8633)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
03-17 14:15:32.951 24635 24635 E AndroidRuntime: Caused by: com.tns.NativeScriptException: Error calling module function
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime: File: (file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986783)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: StackTrace:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: 46384(file:///data/data/com.meterinsight.meterinsight/files/app/vendor.js:2:986784)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at 6295(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:98578)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:197)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_exec__(file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129960)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130037)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at __webpack_require__.X(file:///data/data/com.meterinsight.meterinsight/files/app/runtime.js:1:1167)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:129973)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at (file:///data/data/com.meterinsight.meterinsight/files/app/bundle.js:1:130204)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at require(:1:266)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime:
03-17 14:15:32.951 24635 24635 E AndroidRuntime: TypeError: Cannot read property 'content' of undefined
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.Runtime.runModule(Native Method)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.Runtime.runModule(Runtime.java:689)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.Runtime.run(Runtime.java:681)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
03-17 14:15:32.951 24635 24635 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7476)
```

### Environment

```yaml
OS: Windows 10 10.0.22000
CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Shell: Not Found
node: 14.16.0
npm: 6.14.11
nativescript: Not Found

# android
java: 17.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: 3.0.2
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "^13.2.2",
  "@angular/common": "^13.2.2",
  "@angular/compiler": "^13.2.2",
  "@angular/core": "^13.2.2",
  "@angular/forms": "^13.2.2",
  "@angular/platform-browser": "^13.2.2",
  "@angular/platform-browser-dynamic": "^13.2.2",
  "@angular/router": "^13.2.2",
  "@azure/storage-blob": "^12.9.0",
  "@nativescript/angular": "^13.0.3",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.10",
  "@nativescript/core": "~8.2.0",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-camera-plus": "^4.1.0",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "angular-azure-blob-service": "^1.1.0",
  "guid-typescript": "^1.0.9",
  "nativescript-barcodescanner": "file:nstudio-nativescript-barcodescanner-5.0.1-no-android-arm64m1.tgz",
  "nativescript-ngx-fonticon": "^7.0.0",
  "nativescript-ui-dataform": "^8.0.1",
  "rxjs": "~7.5.4",
  "zone.js": "^0.11.4"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^13.2.0",
  "@angular/cli": "^13.2.3",
  "@angular/compiler-cli": "^13.2.2",
  "@nativescript/android": "~8.2.2",
  "@nativescript/ios": "~8.2.1",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "^13.2.3",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
I would try disabling minification in `--release` mode, and see the crash still occurs. I suspect it may be a Terser (the minifier) breaking the code in release mode, and that we might need to set a few more settings after identifying what exactly breaks...

I believe adding this to the webpack config should disable minifying (this is for debugging the issue, you'd still want to enable it for releases in general)

```js
webpack.chainWebpack(config => {
  config.optimization.minimize(false)
})
```

**Comment by Noppey** [comment]
This is my current webpack.config, with the same result unfortunately:

const webpack = require('@nativescript/webpack')

module.exports = env => {
    webpack.init(env);
    webpack.chainWebpack(config => {
        config.optimization.minimize(false)
    })

    return webpack.resolveConfig();
}

**Comment by rigor789** [comment]
Ok, that's "good" now look at the crash logs - and see what line it crashes on in `vendor.js` - open `platforms` folder and find vendor.js and look at that line there, and see if it has any clues

**Comment by triniwiz** [comment]
@Noppey you can use the mlkit contains the completed version of the barcodescanner,  the code that's causing the issue is from another [barcodescanner](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/eafe2657c871055d3947f9e4cf7b9e09d100e30f/src/barcodescanner.android.ts#L10)

**Comment by Noppey** [comment]
We're currently using a file:
file:nstudio-nativescript-barcodescanner-5.0.1-no-android-arm64m1.tgz
as our barcodescanner. How do I use mlkit barcodescanner? I don't see any plugin available, and I'm not sure if I can get rid of our native view?

barcode-scanner-view-android.ts right now is:
import { View, Application, AndroidActivityRequestPermissionsEventData, AndroidApplication } from '@nativescript/core';
declare const io: any;
export class BarcodeScannerView extends View {
  public static onScanResultEvent = 'scanResult';
  private camera: any;
  private permissionListener: any;
  private _permissionListenerFn(args: AndroidActivityRequestPermissionsEventData) {
    if (this.camera) {
      console.log('permissionListener', this.camera.hasCameraPermission() || this.camera.hasPermission());
      if (this.camera.hasCameraPermission() || this.camera.hasPermission()) {
        this.camera.startPreview();
      }
    }
  }
  private barcodeScannerListener: any;
  constructor() {
    super();
    this.permissionListener = this._permissionListenerFn.bind(this);
  }
  createNativeView() {
    Application.android.on(AndroidApplication.activityRequestPermissionsEvent, this.permissionListener);
    this.camera = new io.github.triniwiz.fancycamera.FancyCamera(this._context);
    return this.camera;
  }

  initNativeView() {
    super.initNativeView();
    const ref = new WeakRef(this);
    const listenerImpl = (io as any).github.triniwiz.fancycamera.CameraEventListenerUI.extend({
      owner: null,
      onReady(): void {},
      onCameraCloseUI(): void {},
      onCameraError(message: string, ex: java.lang.Exception): void {
        console.log('onCameraError', message);
        ex.printStackTrace();
      },
      onCameraPhotoUI(event?: java.io.File) {},
      onCameraOpenUI(): void {
        console.log('onCameraOpen');
      },
      onCameraVideoStartUI(): void {},
      onCameraVideoUI(event?: java.io.File): void {},
      onCameraAnalysisUI(imageAnalysis: any): void {}
    });
    const listener = new listenerImpl();
    listener.owner = ref;
    const fancycamera = this.camera.getChildAt(0);
    if (fancycamera) {
      const options = new io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.Options();
      options.setBarcodeFormat([io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.QR_CODE, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.CODE_128, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.CODE_39, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.CODE_93, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.CODABAR, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.EAN_13, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.EAN_8, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.ITF, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.UPC_A, io.github.triniwiz.fancycamera.barcodescanning.BarcodeScanner.BarcodeFormat.UPC_E]);
      this.barcodeScannerListener = new io.github.triniwiz.fancycamera.ImageAnalysisCallback({
        onSuccess(result: string) {
          try {
            const value = JSON.parse(result);
            let first = value[0];
            if (first) {
              if (typeof first === 'string') {
                first = JSON.parse(first);
              }
              if (ref && ref.get) {
                const owner = ref.get();
                if (owner) {
                  owner.notify(<any>{
                    eventName: BarcodeScannerView.onScanResultEvent,
                    text: first.rawValue,
                    format: first.format
                  });
                }
              }
            }
          } catch (e) {
            console.log(e);
          }
        },
        onError(message: string, exception: java.lang.Exception) {
          console.log(message);
          exception.printStackTrace();
        }
      });
      fancycamera.setBarcodeScannerOptions(options);
    }
    this.camera.setDetectorType(io.github.triniwiz.fancycamera.DetectorType.Barcode);
    this.camera.setListener(listener);
    this.camera.setOnBarcodeScanningListener(this.barcodeScannerListener);
    if (!this.camera.hasCameraPermission()) {
      this.camera.requestCameraPermission();
    }
  }

  disposeNativeView() {
    console.log('disposeNativeView.');
    Application.android.off(AndroidApplication.activityRequestPermissionsEvent, this.permissionListener);
    this.camera.release();
    super.disposeNativeView();
  }
}

**Comment by triniwiz** [comment]
The new version that scanner being used can be found [here](https://github.com/NativeScript/mlkit/tree/main/packages/mlkit-core)

**Comment by Noppey** [comment]
When following that, I get:
@nativescript/mlkit-core"' has no exported member 'DetectionEvent'

**Comment by Noppey** [comment]
Same error unfortunately, I've also ran ns clean to make sure there is no conflict with previous alpha versions.

**Comment by Noppey** [comment]
I also tried removing all those dependencies from app.gradle, cleaning, running, but same FaceDetection exception.

**Comment by triniwiz** [comment]
Remove the following 

```gradle
  implementation('io.github.triniwiz:fancycamera:3.0.0-alpha23'){
        transitive = true
  }
  implementation('io.github.triniwiz.fancycamera:barcodeScanning:1.0.0-alpha0'){
        transitive = true
  }
```

**Comment by Noppey** [comment]
This is my current app.gradle which results in the same exception:

```
android {  
  packagingOptions {
    pickFirst 'lib/armeabi-v7a/libRSSupport.so'
    pickFirst 'lib/arm64-v8a/libRSSupport.so'
    pickFirst 'lib/x86_64/libRSSupport.so'
    pickFirst 'lib/x86/libRSSupport.so'
    pickFirst 'lib/armeabi-v7a/librsjni.so'
    pickFirst 'lib/arm64-v8a/librsjni.so'
    pickFirst 'lib/x86_64/librsjni.so'
    pickFirst 'lib/x86/librsjni.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'META-INF/barcodeScanning_release.kotlin_module'
  }

  compileSdkVersion 32
  buildToolsVersion "32.0.0"
  defaultConfig {  
    minSdkVersion 23
    targetSdkVersion 32
    generatedDensities = []
    ndk {
        abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
    }
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
```

**Comment by triniwiz** [comment]
The last issue was a [bug](https://github.com/NativeScript/mlkit/commit/6b5e77559e173455ae097f20b0939d2ecea68e7c) , version 1.0.1 should finally work for you
