### ISSUE TITLE
The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available

### ISSUE THREAD

**Issue by faisalansari20** [NativeScript/NativeScript#9854]
### Issue Description

After upgrading nativescript 8 from 7. I see The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available 

Below is my package json

{
  "name": "@nativescript/template-hello-world-ng",
  "main": "./src/main.ts",
  "version": "7.0.2",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "./src/scripts/nativescript-camera/nativescriptCamera.sh",
    "android-build": "tns clean && tns prepare android && tns run android",
    "ios-build": "tns clean && tns prepare ios && tns run ios",
    "ios": "tns run ios --device 'iPhone 12 Pro'"
  },
  "nativescript": {
    "id": "com.atd.atdmobileapp",
    "tns-android": {
      "version": "6.5.3"
    }
  },
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@dmi/camera": "file:./src/thirdPartyLibraries/camera",
    "@nativescript-community/ui-material-bottom-navigation": "^7.0.3",
    "@nativescript/angular": "^13.0.0",
    "@nativescript/auto-fit-text": "^1.0.1",
    "@nativescript/background-http": "^5.0.1",
    "@nativescript/core": "~8.2.0",
    "@nativescript/email": "^2.0.0",
    "@nativescript/firebase": "11.1.3",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/local-notifications": "^5.1.0",
    "@nativescript/localize": "^5.0.2",
    "@nativescript/theme": "~2.3.0",
    "@nota/nativescript-accessibility-ext": "^7.0.3",
    "@nstudio/nativescript-cardview": "^2.0.0",
    "@nstudio/nativescript-pulltorefresh": "^3.0.1",
    "axios": "^0.23.0",
    "emitter": "^0.0.5",
    "file-base64": "^1.0.0",
    "follow-redirects": "^1.13.2",
    "jspdf": "^2.1.1",
    "nativescript-appversion": "^1.4.4",
    "nativescript-barcodescanner": "^4.0.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-clipboard": "^2.0.0",
    "nativescript-fingerprint-auth": "^7.0.2",
    "nativescript-gif": "^5.0.0",
    "nativescript-numeric-keyboard": "^5.0.0",
    "nativescript-orientation": "file:./src/thirdPartyLibraries/nativescript-orientation",
    "nativescript-permissions": "1.3.11",
    "nativescript-phone": "^2.0.0",
    "nativescript-secure-storage": "^2.6.2",
    "nativescript-speech-recognition": "^2.0.0",
    "nativescript-ui-calendar": "^7.0.2",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-videoplayer": "^5.0.1",
    "nativescript-xml2js": "^0.5.2",
    "pdfmake": "^0.1.68",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~7.5.0",
    "stream": "^0.0.2",
    "timer": "^1.0.1",
    "util": "^0.10.3",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/cli": "^13.2.0",
    "@angular/compiler-cli": "~13.2.0",
    "@nativescript/android": "~8.2.0",
    "@nativescript/ios": "~8.2.0",
    "@nativescript/schematics": "^10.1.0",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.6",
    "@ngtools/webpack": "~13.2.0",
    "@schematics/angular": "^13.2.0",
    "tns-android": "6.5.3",
    "typescript": "~4.5.5"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

### Relevant log output (if applicable)

```shell
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application com.atd.atdmobileapp on device emulator-5554.
JS: JIT compilation failed for injectable class PlatformLocation {
JS:     historyGo(relativePosition) {
JS:         throw new Error('Not implemented');
JS:     }
JS: }
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
System.err: 
System.err: The injectable is part of a library that has been partially compiled.
System.err: However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
System.err: 
System.err: Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
System.err: Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
System.err: or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
System.err: File: (file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: getCompilerFacade(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/core/fesm2015/core.mjs:4067:0)
System.err:     at ɵɵngDeclareFactory(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/core/fesm2015/core.mjs:28617:0)
System.err:     at ./node_modules/@angular/common/fesm2015/common.mjs(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/common/fesm2015/common.mjs:90:45)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/hot module replacement:62:0)
System.err:     at ./node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs(file:///data/data/com.atd.atdmobileapp/files/app/vendor.js:264635:74)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/hot module replacement:62:0)
System.err:     at ./src/main.ts(file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:13:79)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at __webpack_exec__(file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25791:39)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25792:189)
System.err:     at __webpack_require__.X(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/startup entrypoint:6:0)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25792:47)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25797:3)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
System.err: 
System.err: The injectable is part of a library that has been partially compiled.
System.err: However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
System.err: 
System.err: Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
System.err: Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
System.err: or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
System.err: 
System.err: The injectable is part of a library that has been partially compiled.
System.err: However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
System.err: 
System.err: Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
System.err: Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
System.err: or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
System.err: File: (file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: getCompilerFacade(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/core/fesm2015/core.mjs:4067:0)
System.err:     at ɵɵngDeclareFactory(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/core/fesm2015/core.mjs:28617:0)
System.err:     at ./node_modules/@angular/common/fesm2015/common.mjs(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/common/fesm2015/common.mjs:90:45)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/hot module replacement:62:0)
System.err:     at ./node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs(file:///data/data/com.atd.atdmobileapp/files/app/vendor.js:264635:74)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/hot module replacement:62:0)
System.err:     at ./src/main.ts(file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:13:79)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at __webpack_exec__(file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25791:39)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25792:189)
System.err:     at __webpack_require__.X(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/startup entrypoint:6:0)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25792:47)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25797:3)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
System.err: 
System.err: The injectable is part of a library that has been partially compiled.
System.err: However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
System.err: 
System.err: Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
System.err: Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
System.err: or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
System.err: 
System.err: The injectable is part of a library that has been partially compiled.
System.err: However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
System.err: 
System.err: Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
System.err: Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
System.err: or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
System.err: File: (file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:27:0)
System.err: 
System.err: StackTrace: 
System.err: getCompilerFacade(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/core/fesm2015/core.mjs:4067:0)
System.err:     at ɵɵngDeclareFactory(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/core/fesm2015/core.mjs:28617:0)
System.err:     at ./node_modules/@angular/common/fesm2015/common.mjs(file: src/webpack:/@nativescript/template-hello-world-ng/node_modules/@angular/common/fesm2015/common.mjs:90:45)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/hot module replacement:62:0)
System.err:     at ./node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs(file:///data/data/com.atd.atdmobileapp/files/app/vendor.js:264635:74)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at fn(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/hot module replacement:62:0)
System.err:     at ./src/main.ts(file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:13:79)
System.err:     at __webpack_require__(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/bootstrap:24:0)
System.err:     at __webpack_exec__(file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25791:39)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25792:189)
System.err:     at __webpack_require__.X(file: src/webpack:/@nativescript/template-hello-world-ng/webpack/runtime/startup entrypoint:6:0)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25792:47)
System.err:     at (file:///data/data/com.atd.atdmobileapp/files/app/bundle.js:25797:3)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
System.err: 
System.err: The injectable is part of a library that has been partially compiled.
System.err: However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
System.err: 
System.err: Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
System.err: Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
System.err: or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by edusperoni** [comment]
If you check the start of your build log you'll see a warning about a missing `@angular-devkit` package that is required to build angular 13. Just install that as a dev dependency.

**Comment by NathanWalker** [comment]
Specifically you need this in devDependencies:
```
"@angular-devkit/build-angular": "~13.0.0",
Keep in mind angular major or minor should match so if project is using ~13.1.0, then that dep should also be ~13.1.0 (or ^13.0.0 or ~13.2.0 - whatever your other angular project deps are using, it should match.
That was a new requirement with angular 13 (to have that in devDeps')
```
