### ISSUE TITLE
Release Android crashes app

### ISSUE THREAD

**Issue by csivor** [NativeScript/NativeScript#9866]
### Issue Description

When running ns run android, everything works.
When running ns run android --release the app crashes on opening.

### Relevant log output (if applicable)

```shell
--------- beginning of crash
2022-04-11 14:45:30.359 10596-10596/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.nativescript.LibraIgazoloApp, PID: 10596
    java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
    TypeError: Cannot read property 'content' of undefined
    File: (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/vendor.js:2:1089897)
    
    StackTrace: 
    46384(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/vendor.js:2:1089898)
        at __webpack_require__(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/runtime.js:1:212)
        at 93987(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:40261)
        at __webpack_require__(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/runtime.js:1:212)
        at __webpack_exec__(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164192)
        at (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164269)
        at __webpack_require__.X(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/runtime.js:1:1312)
        at (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164205)
        at (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164437)
        at require(:1:266)
    
    
    TypeError: Cannot read property 'content' of undefined
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.tns.NativeScriptException: Error calling module function 
    TypeError: Cannot read property 'content' of undefined
    File: (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/vendor.js:2:1089897)
    
    StackTrace: 
    46384(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/vendor.js:2:1089898)
        at __webpack_require__(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/runtime.js:1:212)
        at 93987(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:40261)
        at __webpack_require__(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/runtime.js:1:212)
        at __webpack_exec__(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164192)
        at (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164269)
        at __webpack_require__.X(file:///data/data/org.nativescript.LibraIgazoloApp/files/app/runtime.js:1:1312)
        at (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164205)
        at (file:///data/data/org.nativescript.LibraIgazoloApp/files/app/bundle.js:1:164437)
        at require(:1:266)
    
    
    TypeError: Cannot read property 'content' of undefined
        at com.tns.Runtime.runModule(Native Method)
        at com.tns.Runtime.runModule(Runtime.java:689)
        at com.tns.Runtime.run(Runtime.java:681)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        	... 8 more
2022-04-11 14:45:30.365 497-2332/? W/ActivityTaskManager:   Force finishing activity org.nativescript.LibraIgazoloApp/com.tns.NativeScriptActivity
2022-04-11 14:45:30.367 497-10616/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2022-04-11 14:45:30.367 286-286/? D/goldfish-address-space: claimShared: Ask to claim region [0x3f73a8000 0x3f78b8000]
2022-04-11 14:45:30.408 10596-10596/? I/Process: Sending signal. PID: 10596 SIG: 9
2022-04-11 14:45:30.409 497-528/? D/EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_CANCELLED
```

### Environment

{
  "name": "the-name",
  "main": "./src/main.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.2.2",
    "@angular/common": "~13.2.2",
    "@angular/compiler": "~13.2.2",
    "@angular/core": "~13.2.2",
    "@angular/forms": "~13.2.2",
    "@angular/platform-browser": "~13.2.2",
    "@angular/platform-browser-dynamic": "~13.2.2",
    "@angular/router": "~13.2.2",
    "@nativescript-community/ui-drawer": "^0.0.33",
    "@nativescript/angular": "^13.0.3",
    "@nativescript/background-http": "^6.0.0",
    "@nativescript/camera": "^5.0.10",
    "@nativescript/core": "~8.2.0",
    "@nativescript/imagepicker": "^1.0.6",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "~3.0.2",
    "@nstudio/nativescript-loading-indicator": "^3.0.4",
    "atob": "^2.1.2",
    "base-64": "^0.1.0",
    "crypto-js": "^3.1.9-1",
    "lodash": "^4.17.15",
    "nativescript-barcodescanner": "^4.1.2",
    "nativescript-download-progress": "^1.7.0",
    "nativescript-ui-listview": "^10.0.2",
    "q-encoding": "^1.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~7.5.0",
    "ts-patch": "^2.0.1",
    "utf8": "^2.1.2",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.2",
    "@angular/compiler-cli": "~13.2.2",
    "@nativescript/android": "~8.2.2",
    "@nativescript/ios": "~8.2.3",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.6",
    "@ngtools/webpack": "~13.2.2",
    "tslint": "5.7.0",
    "typescript": "~4.5.5"
  }
}

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by matteonatale** [comment]
Hi everyone, I have the same issue of @csivor.  Is there any solution? It's a couple of days now that I'm trying to publish a new version of my app on Google Play Store but the app crashes on every startup.

**Comment by matteonatale** [comment]
Hi, @csivor did you solve the issue?

**Comment by csivor** [comment]
Hi, @matteonatale ! No, unfortunately ... I first update my packages, then build my application in release mode, and the application still crashes when I open it ...

**Comment by farfromrefug** [comment]
@matteonatale @csivor if you have a stacktrace like shown here you are able to investigate this and try to find where the error comes from. clearly accessing `content` on an undefined object.
we cant do the investigation for you.
Now I would suggest to try and run your app with `--env.production --env.uglify` to see if you can reproduce the issue in a non production environment

**Comment by csivor** [comment]
@matteonatale @farfromrefug I checked the error again, but now I went into more detail ... 
I'm using the barcodescanner plugin, which had a reference to `androidx.localbroadcastmanager.content` in its code,
so **app.grandle** _had to put_ `implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'`
**This way the application is working properly.**

**Comment by farfromrefug** [comment]
@csivor you should create anissue on the plugin repo so that it could get fixed on the plugin side
