### ISSUE TITLE
Crash su Realme Device

### ISSUE THREAD

**Issue by a92c** [NativeScript/NativeScript#9924]
### Issue Description

On realme device with android 12 I'have randomly crash.
Log error:
E/OplusTrack-ApkInfoUtil: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference.

Versione NS 8.2.1-next-03-09-2022-1954817296

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Try narrowing down the crash to a specific feature/area in your app, or a specific action that triggers the crash randomly.

Unfortunately without any other info we won't be able to help, as there's simply not enough context to go off of.

**Comment by a92c** [comment]
I'm sorry but if the crash is random it occurs on different scenarios, on device with android 12 (oppo, realme) I report the error trace:
2022-05-23 15:25:42.309 1656-7198/? E/OplusTrack-ApkInfoUtil: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
2022-05-23 15:25:42.309 1656-7198/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.h.b.d(ApkInfoUtil.java:136)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.b.b.a(TrackEvent.java:141)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.b.b.<init>(TrackEvent.java:47)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.b.a.<init>(CommonBean.java:37)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.a(OplusTrack.java:223)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.e.a.a$a.a(AppLaunchEventRecorder.java:116)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.e.a.a$a.a(AppLaunchEventRecorder.java:75)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.e.a.-$$Lambda$2fHLmT8JZlr5OzkT2xnqiCVdLEk.onAppSwitch(Unknown Source:2)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.b.a(AppSwitchMonitor.java:81)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.b.lambda$yF2sSrETF4wpk07pjuI1ubPVnB8(Unknown Source:0)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.-$$Lambda$b$yF2sSrETF4wpk07pjuI1ubPVnB8.accept(Unknown Source:4)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:832)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.b.b(AppSwitchMonitor.java:81)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.b.lambda$fX4Hi7f3z5t3AW9aa0q-E6iGF5w(Unknown Source:0)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at com.oplus.statistics.c.-$$Lambda$b$fX4Hi7f3z5t3AW9aa0q-E6iGF5w.run(Unknown Source:4)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-05-23 15:25:42.309 1656-7198/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by rigor789** [comment]
I understand it's random - so no worries, try gathering information over time and maybe we can identify the cause. I'm mainly stating that based on the info you have so far, we are unlikely to be able to help (just to set expectations clearly), but feel free to keep this issue open, and add any info/context as you come across it. If you have one of the affected devices, try observing if there are any specific actions you take that eventually crash etc. and keep notes.
